### ISSUE TITLE
Should MDCButton include string manipulation APIs?

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#100]
Notably, `shouldCapitalizeTitle` is an API that should exist at the app level or at best in a string manipulation utility. MDCButton shouldn't be getting into the business of string manipulation (this smells of API creep).

I realize that the intent may have been to provide a "Material" convenience for capitalizing titles, but this logic should still not live in the button API. If we want to encourage teams to capitalize titles then we should encourage doing so at call sites when the titles are set rather than taking on the string manipulation burden in our button API.

**Comment by ianegordon** [comment]
This bug hasn't been updated in over two years!

Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄
