### ISSUE TITLE
Email addresses are mistakenly highlighted even if I use message instead of attributedMessage

### ISSUE THREAD

**Issue by galiak11** [material-components/material-components-ios#10011]
# Summary
Email addresses are mistakenly highlighted even if I use message instead of attributedMessage.

# Mirroring internal issue
b/158313059

# Steps to Reproduce
Setup an MDCAlertViewController with email address in message.
See the email address is being highlighted.

# Expected Behavior
No highlight when I set message.

# Actual Behavior
Email address was highlighted when I set message.

**Comment by codeman7** [comment]
The linked internal issue has been closed therefore closing this as well.
