### ISSUE TITLE
[MDCOutlinedTextArea] Does not resize to fit leadingAssistiveLabel in IB

### ISSUE THREAD

**Issue by chamitha** [material-components/material-components-ios#10018]
I have created a MDCOutlinedTextArea in Interface Builder (using a UIView) and defined it as
```
    @IBOutlet var textArea: MDCOutlinedTextArea! {
        didSet {
            textArea.maximumNumberOfVisibleRows = 3
            textArea.minimumNumberOfVisibleRows = 3
        }
    }
```
I have no helper text therefore the initial value for leadingAssistiveLabel is nil. However I utilise leadingAssistiveLabel to display validation errors. On such an error the MDCOutlinedTextArea is not resized to fit the leadingAssistiveLabel. Therefore the contents of the leadingAssistiveLabel are truncated. 

![Screen Shot 2020-06-11 at 9 59 19 am](https://user-images.githubusercontent.com/13659666/84330637-46a2b300-abcb-11ea-9c18-be7348ac20c0.png)

`textArea.sizeToFit()` does update the bounds of the MDCOutlinedTextArea correctly but this is not reflected in the UI. Forcing a layout with `textArea.setNeedsLayout()` and `textArea.layoutIfNeeded()` had no effect.

A workaround is to set a height constraint for textArea in IB and set its `constant` value to the new height returned by `sizeToFit` after leadingAssistiveLabel is set. 

## Reproduction steps

Create a MDCOutlinedTextArea in Interface Builder using a UIView.
Set the initial value for leadingAssistiveLabel to nil.
Set the value for leadingAssistiveLabel to a non empty string at a later time.

## Expected behavior

The leadingAssistiveLabel text is displayed and fully visible. I.e. the height of the MDCOutlinedTextArea is resized to fit.

## Actual behavior

The leadingAssistiveLabel is displayed but partially truncated. I.e. the height of the MDCOutlinedTextArea did not resize to fit.

PS: MDCOutlinedTextField works this way, as expected.

## Platform

 - Device: iOS Simulator
 - OS: 13.5
- Xcode: 11.5

**Comment by andrewoverton** [comment]
Hello @chamitha, is the issue that it's not resizing _within Interface Builder_? Is the sizing behavior correct when the app is actually running?

**Comment by andrewoverton** [comment]
When you say "Set the initial value for leadingAssistiveLabel to nil." are you talking about having a line like this in your view controller? `self.textArea.leadingAssistiveLabel.text = nil`

**Comment by chamitha** [comment]
Hi @andrewoverton. Thanks for the reply. No, I don't mean the issue is in IB rather that the MDCOutlinedTextArea is created using IB (a UIView) instead of programatically in code.
Yes, in my case there is no helper text therefore I start with `self.textArea.leadingAssistiveLabel.text = nil` in the vc BUT on a validation error I set `self.textArea.leadingAssistiveLabel.text = "This field is required"` which does not re-size the view  (as pictured) to show the contents of the `leadingAssistiveLabel` despite the use of `sizeToFit()`, `setNeedsLayout()` and `layoutIfNeeded()`

**Comment by andrewoverton** [comment]
Got it, okay. Do you have any height constraints set on the view? If so, you shouldn't. When used in an Auto Layout environment, the text area should use its `intrinsicContentSize.height` for its height. When you set breakpoints can you see a change in `intrinsicContentSize.height` before and after calling `-sizeToFit`, `-setNeedsLayout`, etc.?

It's currently not happening in our examples, so I think it might be something about the way it's set up for you.

**Comment by chamitha** [comment]
No, I have not set any height constraint explicitly. The only constraints set in IB are to top, left, bottom and right margins of the superview. I can indeed see the height of the textArea adjust correctly if I call `sizeToFit()`. However this size does not seem to be reflected in the layout even after calling `setNeedsLayout` or / and `layoutIfNeeded()`

I have recreated the issue in a sample project attached. Note the textArea does not resize whilst the textField does.

[Test.zip](https://github.com/material-components/material-components-ios/files/4834899/Test.zip)

**Comment by andrewoverton** [comment]
Hi @chamitha, What happens if you try something like this in your view controller?

```
    NSLayoutConstraint.activate([
      superview.heightAnchor.constraint(
        greaterThanOrEqualTo: textArea.heightAnchor),
      textArea.leadingAnchor.constraint(
        equalTo: superview.leadingAnchor),
      textArea.trailingAnchor.constraint(
        equalTo: superview.trailingAnchor),
      textArea.topAnchor.constraint(equalTo: superview.topAnchor),
      textArea.bottomAnchor.constraint(equalTo: superview.bottomAnchor),
    ])
```

**Comment by chamitha** [comment]
@andrewoverton These constraints made no difference to the sample project. I added the code snippet to the `viewDidLoad` and also tested using the same constraints in IB (all of which except for the height constraint already existed in the sample).

**Comment by andrewoverton** [comment]
Taking another look at this:
>The only constraints set in IB are to top, left, bottom and right margins of the superview.

Is it possible the bottom constraint is causing your issues? Is the _superview's_ height constrained in any way?

https://github.com/material-components/material-components-ios/commit/6e52d049a67499ca83c2b3094a4979e12cb06f7d just got merged into develop. It adds KVO to the assistive labels, which will make height changes due to assistive label text changes more automatic in Auto Layout environments. Calling sizeToFit will still be necessary in Manual Layout environments.

**Comment by chamitha** [comment]
> Is it possible the bottom constraint is causing your issues? Is the _superview's_ height constrained in any way?

No, the there are no height constraints. The parent (stack) view in the sample project takes the height of the screen via the top, bottom constraints.

I upgraded to v112.1.0 and the text area does now resize as expected. Thank you for investigating this.
