### ISSUE TITLE
[Component] Add @IBInspectable support to properties.

### ISSUE THREAD

**Issue by tylerjames** [material-components/material-components-ios#10030]
## Feature Request/Suggestion

Please add `@IBInspectable` to some properties of `MDCButton`. In particular I'd like to see `enableRippleBehavior` and `inkColor` though other properties would be welcome.

## Additional context

The docs claim to support this but I don't see any of the properties in MDCButton marked as inspectable.

From the docs here: https://material.io/develop/ios/docs/faq/

> **Can we use Material Components for iOS with storyboards?**
Yes! Storyboards and nibs/xibs are great places to use Material Components for iOS. Almost every component has support for Interface Builder development that includes IBDesignable. Note: IBInspectable support is not where it conflicts with UIAppearance support.

**Comment by jverkoey** [comment]
As of July 15 MDC entered maintenance mode. Learn more at https://github.com/material-components/material-components-ios#material-components-for-ios
