### ISSUE TITLE
Dependency "material-components-ios" has no shared framework schemes for any of the platforms: iOS

### ISSUE THREAD

**Issue by serhatleventyavas** [material-components/material-components-ios#10035]
Hi guys, I have tried to add this library to my project with carthage. When I tried it, carthage threw an error.

`Dependency "material-components-ios" has no shared framework schemes for any of the platforms: iOS
If you believe this to be an error, please file an issue with the maintainers at https://github.com/material-components/material-components-ios/issues/new`

My Cartfile file is like:

```
github "Alamofire/Alamofire" ~> 5.2
github "material-components/material-components-ios" ~> 110.2.0
```

and My Makefile file is like:
```
carthage_bootstrap:
	(cd Vendor && carthage bootstrap --platform ios)
	rm -Rf Vendor/Carthage/Checkouts
carthage_update:
	(cd Vendor && carthage update --platform ios)
	rm -Rf Vendor/Carthage/Checkouts
```
I have tried terminal code.
`make carthage_update`

How can I solve this problem?
Thanks everybody

**Comment by andrewoverton** [comment]
We currently don't support Carthage. The Carthage support feature request is here: https://github.com/material-components/material-components-ios/issues/75.

**Comment by bryanoltman** [comment]
Closing this in favor of #75, the existing ticket to add Carthage support
