### ISSUE TITLE
[MDCOutlinedTextField] setTrailingView for MDCOutlineTextField

### ISSUE THREAD

**Issue by aabanaag** [material-components/material-components-ios#10039]
> For usage questions: ask on [Stack  Overflow](https://stackoverflow.com/questions/tagged/material-components+ios).

## Reproduction steps

1. create an instance of MDCOutlinedTextField
2. set TrailingView 

## Expected behavior

It should be able to set the trailingView

## Actual behavior

How do you set a trailing view for the password field to toggle on/off the secureInput?

MDCOutlinedTextField is just a subclass of MDCBaseTextField but 
![image](https://user-images.githubusercontent.com/2245822/87685289-cb2db600-c7b5-11ea-9206-35c9100486cc.png)
![image](https://user-images.githubusercontent.com/2245822/87685347-dda7ef80-c7b5-11ea-922c-32a84d0cd449.png)

**Comment by andrewoverton** [comment]
Hello,

If you're in Objective-C you can set the `trailingView` in one of these two ways:
```
  textField.trailingView = aView;
  [textField setTrailingView:aView];
```
If you're in Swift I think the only way to set it is like this:
```
outlinedTextField.trailingView = aView
```
Hope this helps!

**Comment by aabanaag** [comment]
I tried doing this but the view is not showing either.

**Comment by andrewoverton** [comment]
Did you associate a selector with it using [this method](https://developer.apple.com/documentation/uikit/uicontrol/1618259-addtarget)? [Here](https://stackoverflow.com/a/24814958) is an example of how to use it.

**Comment by aabanaag** [comment]
Yes I did.

**Comment by andrewoverton** [comment]
I'm not having a problem doing what you're trying to do. I would suggest setting breakpoints in the selector and methods related to receiving touches and trying to pinpoint where things stop working. Good luck!
