### ISSUE TITLE
[MDCOutlinedTextField] + isSecureTextEntry with RxSwift cause freezing UI

### ISSUE THREAD

**Issue by feipe56** [material-components/material-components-ios#10041]
> For usage questions: ask on [Stack  Overflow](https://stackoverflow.com/questions/tagged/material-components+ios).

I found a bug when i was using isSecureTextEntry + MDCOutlinedTextField with RxSwift controlEvent. 
This bug is very strangers because it only happens when the applyTheme()/applyErrorTheme() method is used.

## Reproduction steps

1. Add MDCOutlinedTextField
2. Set isSecureTextEntry to true
3. Implement rx.controlEvent(.editingChanged) to MDCOutlinedTextField

## Expected behavior

When rx.controlEvent is called and i click outside MDCOutlinedTextField or in another text field, the app turn freezing

## Actual behavior

I use this inside rx event: txtField.applyErrorTheme(withScheme: MDCContainerScheme.normalStateTheme)

## Platform (please complete the following information)

 - Device: Simulators iPhone 6s, iPhone 7
 - OS: iOS 12.4

## Additional context

I don't have ideia about this problem

**Comment by samweareloup** [comment]
We are facing a similar issue without RxSwift. On iOS 12 the MDCOutlinedTextFields freeze when the isSecureTextEntry = true. 

We tried disabling the custom theme, but still the issue is persisting. The only way it goes away is when you set isSecureTextEntry = false. Is this a known issue?

**Comment by andrewoverton** [comment]
Thanks for filing a bug. I'm going to try to reproduce without RxSwift first...

**Comment by andrewoverton** [comment]
Is there anything else you two can tell me about your setups? Tried to reproduce on an iOS 12 iPhone X but couldn't. If I had to guess it's probably something like an infinite loop of layout passes. What happens if you put a breakpoint in layoutSubviews? Does it hit the breakpoint repeatedly?

![securetextentry](https://user-images.githubusercontent.com/8020010/88067283-cd3c9f80-cb3c-11ea-90f6-be2e4d81241e.gif)

**Comment by andrewoverton** [comment]
Oh wait, I just reproduced it!

**Comment by feipe56** [comment]
> We are facing a similar issue without RxSwift. On iOS 12 the MDCOutlinedTextFields freeze when the isSecureTextEntry = true.
> 
> We tried disabling the custom theme, but still the issue is persisting. The only way it goes away is when you set isSecureTextEntry = false. Is this a known issue?

Exactly man! but i found provisory solution for this.
In iOS Simulator -> Edit -> Automatically Sync Pasteboard, mark that and close the simulator and reopened. 
Running its ok for me now.

I talked with another devs and they reported what physical device it's ok, maybe be a simulator bug.

**Comment by feipe56** [comment]
> Thanks for filing a bug. I'm going to try to reproduce without RxSwift first...

I have also reproduced without RxSwift

**Comment by andrewoverton** [comment]
Hello, I think b18a919 resolves this issue. This commit should make it into next week's release, which should be available on Cocoapods by next Tuesday or Wednesday. Please re-open if you encounter it again!
