### ISSUE TITLE
Unable to install MaterialComponentsBeta

### ISSUE THREAD

**Issue by RoqueCampos** [material-components/material-components-ios#10069]
I want to test the MDCTabBarView, which belongs to the Beta program but I'm unable to download the pod.

## Reproduction steps

I added the following to my podfile (as explained in https://github.com/material-components/material-components-ios/blob/develop/contributing/beta_components.md)

pod 'MaterialComponents', :git => 'https://github.com/material-components/material-components-ios.git', :branch => 'develop'
   pod 'MaterialComponentsBeta', :git => 'https://github.com/material-components/material-components-ios.git'

and I ran pod install from the command line

## Expected behavior

The beta components should be installed.

## Actual behavior

The following error message is printed:
[!] Unable to find a specification for 'MaterialComponentsBeta'.

 And with pod install -verbose

> Pre-downloading: `MaterialComponentsBeta` from `https://github.com/material-components/material-components-ios.git`
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/material-components/material-components-ios.git /var/folders/xd/ts3w2yyj66732_54xj7nhrtr0000gn/T/d20200826-3560-1rpqb2g --template= --single-branch --depth 1
     Cloning into '/var/folders/xd/ts3w2yyj66732_54xj7nhrtr0000gn/T/d20200826-3560-1rpqb2g'...
     # is not a valid attribute name: .gitattributes:2
  $ /usr/bin/git -C /var/folders/xd/ts3w2yyj66732_54xj7nhrtr0000gn/T/d20200826-3560-1rpqb2g rev-parse HEAD
  805a2af3a84866b7361d27faeb74b343cfcdbca3
[!] Unable to find a specification for 'MaterialComponentsBeta'.

## Platform (please complete the following information)

 - Device: Mac Mini 
 - OS: Cataline v10.15.6
- cocoapods version: 1.9.3

**Comment by andrewoverton** [comment]
Hello, MDCTabBarView actually moved to the main podspec. We deleted the beta podspec. See [here](https://github.com/material-components/material-components-ios/blob/develop/components/Tabs/README.md#installing-tabs) for instructions on installing MDCTabBarView.

**Comment by andrewoverton** [comment]
I'm going to delete `beta_components.md`. Thanks for pointing that out!
