### ISSUE TITLE
[TextFields] MDCTextInputControllerOutlined does not vertically center text

### ISSUE THREAD

**Issue by beckettsimmons** [material-components/material-components-ios#10063]
When using the MDCTextInputControllerOutlined, the field's text is not vertically centered as the MD guildelines would suggest.
The main issue with this is that the input text will no longer align with trailing or leading icons/views.

### Example
![image](https://user-images.githubusercontent.com/3991373/90269844-aae22d00-de2f-11ea-801b-8d7aebeddf2e.png)

### Possibly helpful commentary
It seems like the text is vertically centered within the entire view .
But then entire view also includes the helper text at the bottom.
Hence, the text is no longer centered relative to the outlined border (which ends above the helper text).
On the other hand, it looks like the placeholder text (when the field is empty) is exactly vertically aligned as expected. Perhaps a new constraint similar to that can be added.

**Comment by andrewoverton** [comment]
Hi @beckettsimmons, I encourage you to switch to our newer text field offering, specifically the `MDCOutlinedTextField`. To use it add `TextControls+OutlinedTextFields` and/or `TextControls+OutlinedTextFieldsTheming` to your Podfile, and then `#import "MaterialTextControls+OutlinedTextFields.h"`. See our [text field docs](https://github.com/material-components/material-components-ios/blob/develop/components/TextControls/README.md) for more info.

**Comment by beckettsimmons** [comment]
Great, thanks for the help. That works as expected. I guess the old documentation lead me down the garden path.
