### ISSUE TITLE
[TextFields] Text fields that are set to password fields leak memory in IOS 14 when custom font is used

### ISSUE THREAD

**Issue by Korbin73** [material-components/material-components-ios#10081]
`        
        passwordController = MDCTextInputControllerFilled(textInput: password)
        passwordController?.textInputFont = UIFont(name: "Futura-Medium", size: 17)
        password.font = UIFont(name: "Futura", size: 17)
        passwordController?.inlinePlaceholderFont = SRPBrandFonts.smallerTextFieldSetting
        passwordController?.borderFillColor = UIColor(hexString: "#E5EDF3")
        passwordController?.floatingPlaceholderScale = 0.5
        passwordController?.errorColor = UIColor(hexString: SRPBrandColors.red)
        
        password.isSecureTextEntry = true`

## Reproduction steps

1. Enter the field setup as a password field (isSecureTextEntry) and a custom font
2. Enter text and then leave the field
3. The application will consume all of the available memory and crash

## Expected behavior

The behavior should work like IOS 13 and not leak memory

## Actual behavior

<img width="810" alt="Screen Shot 2020-09-17 at 4 13 17 PM" src="https://user-images.githubusercontent.com/885138/93537572-c04fe880-f900-11ea-8370-4d203c8cd432.png">

## Platform (please complete the following information)

 - Device: [e.g. iPhone11 Pro]
 - OS: [e.g. iOS14.0]

## Additional context

This problem on occurs with password.isSecureTextEntry = true. When it is false the application behaves as expected.

**Comment by intiocean** [comment]
+1 This appears to also be happening to me - need to investigate further but if I debug my app via xcode it crashes with an out of memory error when I try and type in the password text field. However I have tried installing a previous version (from the app store) and the issue doesn't occur there (thankfully!).

**Comment by andrewoverton** [comment]
Thanks for filing the bug! I encourage everyone to switch to our newer text field offering, specifically the `MDCFilledTextField`. I don't think it has this issue. To use the filled text fields add `TextControls+FilledTextFields` and/or `TextControls+FilledTextFieldsTheming` to your Podfile, and then `#import "MaterialTextControls+FilledTextFields.h"`. See our [text field docs](https://github.com/material-components/material-components-ios/blob/develop/components/TextControls/README.md) for more info.

**Comment by Korbin73** [comment]
Looks like this has been resolved in the latest version (MaterialComponents 116.0). Thanks a lot for the help.

**Comment by intiocean** [comment]
I can confirm this is working for me with MaterialComponents 116.0

**Comment by khatri6168** [comment]
> I can confirm this is working for me with MaterialComponents 116.0

What is min support for your app using pod 'MaterialComponents', '116.0'?
Please confirm.

In my case, I have set min iOS support to 11.0 & I always get 114.0, Instead of 116.0 version of materialcomponenets
Can anyone guide me?

Thanks in advance

**Comment by intiocean** [comment]
Hi - I have min iOS support of 10.0. I was also having issues getting cocoa
pods to let me update but discovered it was because I was depending on a
material components pod/subspec that had been decommissioned and then
deleted and so cocoa pods “cleverly” keeps me at the last version that has
the components I depend on.

El dg, 27 set 2020 a les 10:04 Khatri Jigar <notifications@github.com> va
escriure:
