### ISSUE TITLE
[BottomSheet] Dismiss from child view controller

### ISSUE THREAD

**Issue by Kedar-27** [material-components/material-components-ios#10092]
I searched everywhere, but didnt get any solution. Is it possible to dismiss bottom sheet controller from child view controller manually using button, etc?

**Comment by afweiss** [comment]
Yes, this would be possible. As long as you have a reference to the bottom sheet controller then when you want to manually dismiss it (ie after a button is pressed) you should be able to call [bottomSheetController dismissViewControllerAnimated:BOOL completion:completion]; . Hope this helps!
