### ISSUE TITLE
[ActivityIndicator] Animation flickering in iOS 14

### ISSUE THREAD

**Issue by guillermolechuga** [material-components/material-components-ios#10109]
When executing the project for iOS 14, the activity indicator animation shows a flicker after each animation cycle.

## Reproduction steps

Just execute the animation for an indeterminate activity indicator.

## Expected behavior

The animation should be smooth after each cycle.

## Actual behavior

The animations flickers after each animation cycle.

## Platform

 - Device: iPhone 12 (Simulator)
 - OS: 14.1
 - Xcode: 12.1

**Comment by aserdobintsev** [comment]
The same problem - flickering on iOS 14 if build with  iOS 14 SDK.
![blink](https://user-images.githubusercontent.com/5861270/97955842-01c12800-1dc9-11eb-975e-62e3fd56ba67.gif)

**Comment by salmaanahmed** [comment]
Facing same issues, any workaround or solution?

**Comment by shadowstriker15** [comment]
Issue still persists

**Comment by jverkoey** [comment]
https://github.com/material-motion/motion-animator-objc/pull/127 out to fix this.

**Comment by jverkoey** [comment]
For folks on this thread, if you can take a moment to share how you're using MDC in https://github.com/material-components/material-components-ios/issues/8464 it'd help us have a better understanding of how and where MDC's being used in the wild :)

**Comment by jverkoey** [comment]
This is fixed as of https://github.com/material-motion/motion-animator-objc/releases/tag/v4.0.1. Please update your dependencies accordingly.

**Comment by aserdobintsev** [comment]
@jverkoey good news) thanks for that)
But why did you close the issue? MotionAnimator dependency is declared to be version "~> 2.0" (in the podspec file), though bug fixed in version v4.0.1. 
Shouldn't it need to be updated?

**Comment by jverkoey** [comment]
Ah! Thanks for the heads up. I'll update the dependency here.

**Comment by jverkoey** [comment]
https://github.com/material-components/material-components-ios/pull/10177 to address.
