### ISSUE TITLE
MDCTextField with an MDCTextInputControllerOutlined

### ISSUE THREAD

**Issue by Fernandez-Aldo** [material-components/material-components-ios#10110]
How can I set accesibilityIdentifier for Helper/error text label?

**Comment by Fernandez-Aldo** [comment]
Hello. Just following up with my question. Do you have an answer?

**Comment by Fernandez-Aldo** [comment]
Hello team, can someone help with my question please?

**Comment by andrewoverton** [comment]
Hi @Fernandez-Aldo, there is a chance you are looking for [this method](https://github.com/material-components/material-components-ios/blob/develop/components/TextFields/src/MDCTextInputController.h#L321). All the text input controller classes implement it. It allows you to assign error text and an error `accessibilityValue`. Note that this is not how `accessibilityValue` should be used. Label text should be the `accessibilityLabel`. This method sort of got it wrong..

If you want to set the `accessibilityIdentifier`, you could probably just do it directly on the `leadingUnderlineLabel`? It's exposed publicly if I remember correctly?

**Comment by Fernandez-Aldo** [comment]
Hello @andrewoverton, thanks a lot for your help. I was looking for the `leadingUnderlineLabel accessibilitydentifier` 
Now, regarding what you mention about the accessibilityLabel, I didn't really understand what you wanted to say?

**Comment by andrewoverton** [comment]
Oh, I was just trying to say that I think having the method be `-setErrorText:errorAccessibilityLabel:` would have made more sense than `-setErrorText:errorAccessibilityValue:`

**Comment by andrewoverton** [comment]
I'll close the issue if you're unblocked. Thanks!
