### ISSUE TITLE
is there any iOS source code for this Selection controls iOS ViewController

### ISSUE THREAD

**Issue by atebitsy** [material-components/material-components-ios#10112]
is there any iOS source code for this Selection controls iOS ViewController here on the website here is the screenshot of it too [Image screenshot](https://lh3.googleusercontent.com/771zxWG7CmVmdAEpiLrSCIKZsHa-AyyK59iOK8hTRnG7_k3vVmIoDU439EA-qI2n7qNrL8BkTU0sLAozP5sTln99-qhACvvRtkVN-A=w1064-v0) https://material.io/components/selection-controls#usage

**Comment by jverkoey** [comment]
For switches, our recommendation is to use a UISwitch placed in a UITableViewCell.

For checkboxes and radio buttons, our recommendation is to use a UITableViewCell accessoryType set to "checkmark" and to implement the selection handling logic via the UITableViewDelegate.

**Comment by atebitsy** [comment]
oh so there's no example code for this exact [screenshot](https://lh3.googleusercontent.com/nB7T_vNxinJaLEKEex8WHYb4LdQbLu27Z_nyj5Lrkta3YZVzxMLqAmhqyu2VOMQ9Hqa-n9bZzIMC1HENspEP-MZeRlsyIbO8k6J8MKE=w1064-v0) then
