### ISSUE TITLE
swift package manager

### ISSUE THREAD

**Issue by MajidBashir** [material-components/material-components-ios#10120]
I tried to install using swift package manager, this error comes
https://github.com/material-components/material-components-ios.git has no Package.swift manifest for version 119.0.0
Is there any active development for this feature or it will not be provided ?

**Comment by andrewoverton** [comment]
Hi @MajidBashir, thanks for filing this issue. Please follow https://github.com/material-components/material-components-ios/issues/7559 for updates related to Swift Package Manager. I'm going to close this bug as a duplicate. Thanks!
