### ISSUE TITLE
[MDCTextArea] How to handle text changed event?

### ISSUE THREAD

**Issue by GaoShin** [material-components/material-components-ios#10124]
There is no delegate method that can tell application the text inside MDCTextArea changed.
Also I have tried addTarget:action:forControlEvents: method provided by UIControl but the selector method is never triggered.

So how can I know the text changes when user is tapping inside MDCTextArea?

**Comment by andrewoverton** [comment]
Hi @GaoShin, `MDCBaseTextArea` exposes a readonly `UITextView` property. You can assign that text view's `delegate` property to whatever you need. Hope this helps!

I'm going to close this issue, but feel free to re-open if you need anything else. Thanks!

**Comment by GaoShin** [comment]
Thanks! It's working
