### ISSUE TITLE
[Snackbar] Snackbars that closes when a ViewController is dismissed

### ISSUE THREAD

**Issue by chrsp** [material-components/material-components-ios#10133]
## Feature Request/Suggestion

The way the Snackbars works now the Snacks keep presenting even when I call it on a screen and I go to another. If I'm using it to present a specific message for that screen, that sometimes doesn't make much sense. It's possible to have here a way to restrict that the Snackbar will be visible only until the controller that called It is visible?

**Comment by andrewoverton** [comment]
If I understand correctly, you want snackbars presented while view controller A is visible to go away away when view controller B becomes visible. Is that correct? If so, would you be able to do this by calling [`-dismissAndCallCompletionBlocksWithCategory:`](https://github.com/material-components/material-components-ios/blob/develop/components/Snackbar/src/MDCSnackbarManager.h#L99) before presenting view controller B?

**Comment by randallli** [comment]
yea I think you are looking for the features explained in this example:
https://github.com/material-components/material-components-ios/blob/develop/components/Snackbar/examples/SnackbarSuspensionExample.m

If not please reopen.
