### ISSUE TITLE
[BottomSheet] MDCBottomSheet keyboard pushes view controller

### ISSUE THREAD

**Issue by buraknurcicek** [material-components/material-components-ios#10143]
Hello, I am getting a problem with keyboard observers on your MDCSheetContainerView. When keyboard opened state at my bottomSheet controller for textView, keyboard is pushing my view controller like on video. You have observers at MDCSheetContainerView and keyboard is triggering when keyboard becomeFirstResponder() at my controller. If ı commented out your observers at MDCSheetContainerView, my problem is fixing. Can you fix this issue ? I should be able to remove your keyboard observers from my controller.

EDIT: internal issue is [b/176180891](http://b/176180891)

**Comment by AntonijoDev** [comment]
I am using MDCBottomSheet in my chat app and it is working great but am having a lot of problems trying to sync sheet with keyboard movement it is almost impossible to do it without some kind of bouncing, so it would be better if my sheet stays still and keyboard just shows above it. Did you make any progress regarding this issue?

**Comment by buraknurcicek** [comment]
fixed with this
func customEventBeforeTextViewBeginEditing() {

NotificationCenter.default.removeObserver(MDCKeyboardWatcher.shared())
    }

    func textViewDidEndEditing() {
        MDCKeyboardWatcher.load()
    }


Antonijo Bezmalinovic <notifications@github.com>, 5 Oca 2021 Sal, 12:02
tarihinde şunu yazdı:

**Comment by AntonijoDev** [comment]
Yeah I did it the same way :)

**Comment by andrewoverton** [comment]
I believe this was fixed with https://github.com/material-components/material-components-ios/commit/4deaee13215776f82c104e4008c68168f8a62fba.
