### ISSUE TITLE
Is using a MDCSelfSizingStereoCell with UISwitch possible?

### ISSUE THREAD

**Issue by atebitsy** [material-components/material-components-ios#10150]
Is using a MDCSelfSizingStereoCell with UISwitch possible?

**Comment by randallli** [comment]
Apple HIG:
**Use switches in table rows only**. Switches are intended for use in tables, such as in a list of settings that can be toggled on and off. If you need similar functionality in a toolbar or navigation bar, use a button instead, and provide two distinct icons that communicate the states.

-https://developer.apple.com/design/human-interface-guidelines/ios/controls/switches/

We agree. There are accessibility concerns with using a switch anywhere else. The height does not meet minimum touch target sizes that HIG and internal Google recommends.

**Comment by randallli** [comment]
Apple HIG:
**Provide ample touch targets for interactive elements.** Try to maintain a minimum tappable area of 44pt x 44pt for all controls.

-https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/adaptivity-and-layout/
