### ISSUE TITLE
Won't let me set MDCNavigationBarTitleAlignmentLeading in my swift project

### ISSUE THREAD

**Issue by atebitsy** [material-components/material-components-ios#10155]
swift:54:57: error: cannot find 'MDCNavigationBarTitleAlignmentLeading' in scope
    appBarViewController.navigationBar.titleAlignment = MDCNavigationBarTitleAlignmentLeading

**Comment by afweiss** [comment]
For using this in swift, can you try instead:
appBarViewController.navigationBar.titleAlignment = .leading

**Comment by atebitsy** [comment]
works perfect, thank you

**Comment by atebitsy** [comment]
Code below fixed my issue.
appBarViewController.navigationBar.titleAlignment = .leading
