### ISSUE TITLE
Double-quoted include "UIApplication+MDCAppExtensions.h" in framework header, expected angle-bracketed instead

### ISSUE THREAD

**Issue by aarashgoodarzi** [material-components/material-components-ios#10185]
i have 119 warnings:
Double-quoted include "UIApplication+MDCAppExtensions.h" in framework header, expected angle-bracketed instead
please continue updating the source. it really needs to be updated.

**Comment by jverkoey** [comment]
As of July 15 MDC entered maintenance mode. Learn more at https://github.com/material-components/material-components-ios#material-components-for-ios
