### ISSUE TITLE
[Snackbar] Glitch when tapping on a snackbar to dismiss.

### ISSUE THREAD

**Issue by Arcank** [material-components/material-components-ios#1018]
For usage questions please ask on [Stack  Overflow](http://stackoverflow.com/questions/tagged/material-components-ios).
This will allow others to find answers to your questions too.

Providing the following information will increase the chances of your issue being dealt with quickly:
### Overview of the issue
[Snackbar] Glitch when tapping on a snackbar to dismiss.

### Reproduction steps
- Open Catalog.
- Go down to SnackBar.
- Open the first demo.
- Tap to display a snackbar.
- Tap on the snackbar to have it disappear.
=> The snackbar animates out but at the end of the animation, it flickers back to the initial position (and disappears).

### Motivation and context
This used to work a couple releases ago.

### Version number
b1273dad

### Operating system and hardware
iPhone SE iOS 10 simulator, iPhone 7 Plus iOS 10 device

**Comment by ajsecord** [comment]
This seems to have been fixed as of today.

**Comment by Arcank** [comment]
This is not fixed in MDC as of 8ab5505d. I repro in the Catalog.

**Comment by jyaif** [comment]
Friendly ping :-)
I would love to not ship Chrome iOS with this bug.

**Comment by samnm** [comment]
My solution broke the overlay positioning. Will have a fix soon.

**Comment by Arcank** [comment]
Tested locally in Chrome, fix looks good. Thank you!

**Comment by randallli** [comment]
https://github.com/material-components/material-components-ios/pull/1166 is a second attempt
