### ISSUE TITLE
[TextFields] MDCOutlinedTextField error view not displaying properly in iOS 12.4

### ISSUE THREAD

**Issue by deepaliverma11** [material-components/material-components-ios#10184]
### Overview
I am using MDCOutlinedTextField to create a form. The textfield works properly in iOS 14 simulator but when the same screen is opened in iOS 12 simulator, the textfield boundaries gets distorted, and the error message starts showing inside the textfield. I am attaching the screenshot for both iOS 14 and iOS 12 below:
 
**iOS 14 simulator screenshot:** 
![Simulator Screen Shot - iPhone 7 - 2021-03-24 at 18 27 40](https://user-images.githubusercontent.com/81307835/112314943-9c19fd80-8ccf-11eb-8361-70071aa8fd73.png)

**iOS 12 simulator screenshot:**
![Simulator Screen Shot - iPhone 7 - 2021-03-24 at 18 27 06](https://user-images.githubusercontent.com/81307835/112315024-b05dfa80-8ccf-11eb-8343-415d95676ba4.png)

### Reproduction steps
Add MDCOutlinedTextField using outlet and show the error theme using following method: - _(void)applyErrorThemeWithScheme:(nonnull id<MDCContainerScheming>)containerScheme;_

**Code**: 
`[textfield applyThemeWithScheme:self.containerScheme];`
`[textfield sizeToFit];`

**PS**: I have not applied any height constraint to the textfield.

### Pod Version
MaterialComponents/TextControls+OutlinedTextFields (110.2.0)

### Operating system and device
iOS 12.4 simulator

**Comment by andrewoverton** [comment]
Thank you filing this issue! I will most likely get a chance to look into this next week.

**Comment by andrewoverton** [comment]
Hi @deepaliverma11, you mention that you're not applying a height constraint. Have you tried doing that? You might have luck specifying an exact height and then updating it in [this MDCBaseTextFieldDelegate method](https://github.com/material-components/material-components-ios/blob/develop/components/TextControls/src/BaseTextFields/MDCBaseTextFieldDelegate.h#L68).

**Comment by andrewoverton** [comment]
When you see this issue, what happens if you open the view debugger? Is the entire thing within the bounds of the frame? Or does the frame stop where the red lines stop on the sides?

These text fields have a lot of iOS 12 specific bugs. I think UITextField was buggy in iOS 12. That may have something to do with it.

**Comment by deepaliverma11** [comment]
Hi @andrewoverton, thanks for the response.

### iOS 12.4 simulator view debugger screenshot:
<img width="339" alt="Screenshot 2021-04-12 at 10 00 31 AM" src="https://user-images.githubusercontent.com/81307835/114340885-2d192180-9b76-11eb-8ced-db947a4cc6c3.png">

In the above-attached screenshot, there is an extra layer: _UITextFieldRoundedRectBackgroundViewNeue, the highlighted one in the screenshot overlapping the red-bordered MDCOutlined Textfield.

When I checked for the same thing in iOS 14, this layer was not present, please refer the screenshot below:
### iOS 14 simulator view debugger screenshot:
<img width="313" alt="Screenshot 2021-04-12 at 10 05 48 AM" src="https://user-images.githubusercontent.com/81307835/114341135-add81d80-9b76-11eb-9360-1b3b2e50ac53.png">

I am not sure if this is the root cause of the issue.

I also tried using the delegate method that you suggested in the previous comment, but it did not help.

**Comment by andrewoverton** [comment]
Interesting! This seems to be related to related to the `borderStyle` property. `_UITextFieldRoundedRectBackgroundViewNeue` looks like an internal Apple class related to the `.roundedRect` border style.  Maybe [marking `borderStyle` as unavailable](https://github.com/material-components/material-components-ios/blob/develop/components/TextControls/src/OutlinedTextFields/MDCOutlinedTextField.h#L27) was a mistake. Thanks for checking that.

**Comment by deepaliverma11** [comment]
@andrewoverton Any update on this? Any ideas on how to make this work in the current version?

**Comment by andrewoverton** [comment]
Are you using a storyboard? If so, can you try changing the border style to None from within the storyboard?

**Comment by andrewoverton** [comment]
Closing this, as I believe you just need to set `borderStyle` to `.none`.
