### ISSUE TITLE
Adding scrollable style 'scrollableLeadingCentered'

### ISSUE THREAD

**Issue by plaps153** [material-components/material-components-ios#10187]
## Feature Request/Suggestion

In Tabs, When I set the style 'scrollableCentered' it has leading padding 52 (kScrollableTabsLeadingEdgeInset) so tabs start with leading padding. 

I want to scrollableCentered tabs with leading-aligned without padding.

So this 'scrollableLeadingCentered' is works as 'scrollableLeading' without leading padding.

How do you think about this?

**Comment by andrewoverton** [comment]
Hi @plaps153, we probably will not be prioritizing adding this since I don't think it exists in our design guidelines. Do you think there is a way to add it simply though?

**Comment by plaps153** [comment]
Hi,

I think the simple way is to change this padding 'static' variable to property which has setter. 

AFAIK android can handle this value so it can stick to leading.

**Comment by jverkoey** [comment]
As of July 15 MDC entered maintenance mode. Learn more at https://github.com/material-components/material-components-ios#material-components-for-ios
