### ISSUE TITLE
MDCTextfield and MDCButton are not responsive on iOS 14+ when running on Xcode 12+

### ISSUE THREAD

**Issue by isalmanqureshi** [material-components/material-components-ios#10199]
I have used MDCTextField and MDCButton in the UITableViewCell, and it's not responding when tapping on the button or text field. Also, I had tried with the different previous version but still issue remains the same. 
Note: It works fine when I am using Xcode 11.5 and used to deploy before to Testflight. But recently as testflight accepts Xcode 12 and plus to upload the build the text field and the button stops working for iOS 14+ devices but it works lower version.

## Expected behavior
It should tap on the button and text field to respond

## Actual behavior
Not responding when tap on text field and button used through Material design component

## Platform (please complete the following information)

 - Device: iPad 8, iPhone 11 pro max 
 - OS: iOS 14.5, iOS 14.4.2

## Additional context
Currently, I am using version 124.0.0 of Material Design Components.

**Comment by PinkeshGjr** [comment]
i am also facing exact same issue

**Comment by jverkoey** [comment]
Material libraries for iOS entered maintenance mode as of July 15, 2021. Learn more at https://github.com/material-components/material-components-ios#material-components-for-ios.
