### ISSUE TITLE
xcode archive error

### ISSUE THREAD

**Issue by nimamogh** [material-components/material-components-ios#10209]
# Intro
I know there are multiple issues on the product archive part of MC ios and if you think this is repeated apologies! and I appreciate it if you could point me to the solution.

# Description
There is no problem when I am using simulators but I cannot product archive my project in xcode 12.5, with following error

ld: warning: ignoring file ....Intermediates.noindex/ArchiveIntermediates/..../BuildProductsPath/Release-iphoneos/MDFInternationalization/MDFInternationalization.framework/MDFInternationalization, building for iOS-armv7 but attempting to link with file built for iOS-arm64
Undefined symbols for architecture armv7:
  "_MDFInsetsMakeWithLayoutDirection", referenced from:
      -[MDCCollectionViewTextCell contentWrapperFrame] in MDCCollectionViewTextCell.o
      -[MDCNavigationBar layoutSubviews] in MDCNavigationBar.o
  "_MDFTrailingMarginAutoresizingMaskForLayoutDirection", referenced from:
      -[MDCCollectionViewCell updateInterfaceForEditing] in MDCCollectionViewCell.o
      -[MDCCollectionViewTextCell commonMDCCollectionViewTextCellInit] in MDCCollectionViewTextCell.o
  "_MDFInsetsFlippedHorizontally", referenced from:
      -[MDCFloatingButton insetBoundsForBounds:] in MDCFloatingButton.o
  "_MDFLeadingMarginAutoresizingMaskForLayoutDirection", referenced from:
      -[MDCCollectionViewCell updateInterfaceForEditing] in MDCCollectionViewCell.o
  "_MDFRectFlippedHorizontally", referenced from:
      -[MDCAlertControllerView layoutHorizontalButtons:actionSize:] in MDCAlertControllerView+Private.o
      -[MDCAlertControllerView layoutVerticalButtons:] in MDCAlertControllerView+Private.o
      -[MDCChipFieldTextField textRectForBounds:] in MDCChipField.o
      -[MDCChipField layoutSubviews] in MDCChipField.o
      -[MDCChipView layoutSubviews] in MDCChipView.o
      -[MDCCollectionViewCell layoutForegroundSubviews] in MDCCollectionViewCell.o
      -[MDCCollectionViewCell drawSeparatorIfNeeded] in MDCCollectionViewCell.o
      ...
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

## Expected behavior
Archiving the app just like in the simulator.

## Actual behavior
The linker seems is trying to mix different architectures.

## Platform (please complete the following information)
ProductName:	macOS
ProductVersion:	11.4
BuildVersion:	20F71

## Additional context
My Podfile is like this

target 'OFood' do
 ...
  pod 'MaterialComponents'
 ...
end

post_install do |pi|
  pi.pods_project.targets.each do |t|
    t.build_configurations.each do |bc|
      if bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] == '8.0'
        bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end

**Comment by FelipePlaza** [comment]
Same issue.

Undefined symbols for architecture armv7:
  "_MDFInsetsMakeWithLayoutDirection", referenced from:
      -[MDCCollectionViewTextCell contentWrapperFrame] in MDCCollectionViewTextCell.o
      -[MDCNavigationBar layoutSubviews] in MDCNavigationBar.o
  "_MDFTrailingMarginAutoresizingMaskForLayoutDirection", referenced from:
      -[MDCCollectionViewCell updateInterfaceForEditing] in MDCCollectionViewCell.o
      -[MDCCollectionViewTextCell commonMDCCollectionViewTextCellInit] in MDCCollectionViewTextCell.o
  "_MDFInsetsFlippedHorizontally", referenced from:
      -[MDCFloatingButton insetBoundsForBounds:] in MDCFloatingButton.o
  "_MDFLeadingMarginAutoresizingMaskForLayoutDirection", referenced from:
      -[MDCCollectionViewCell updateInterfaceForEditing] in MDCCollectionViewCell.o
  "_MDFRectFlippedHorizontally", referenced from:
      -[MDCAlertControllerView layoutHorizontalButtons:actionSize:] in MDCAlertControllerView+Private.o
      -[MDCAlertControllerView layoutVerticalButtons:] in MDCAlertControllerView+Private.o
      -[MDCChipFieldTextField textRectForBounds:] in MDCChipField.o
      -[MDCChipField layoutSubviews] in MDCChipField.o
      -[MDCChipView layoutSubviews] in MDCChipView.o
      -[MDCCollectionViewCell layoutForegroundSubviews] in MDCCollectionViewCell.o
      -[MDCCollectionViewCell drawSeparatorIfNeeded] in MDCCollectionViewCell.o

But I think is a Xcode issue because in the version 118.1.0 work fine in xcode 12.3. And now the this version lunch the same error

**Comment by nimamogh** [comment]
I just noticed there is another open issue here

[https://github.com/material-components/material-components-ios/issues/10203](url)

**Comment by nimamogh** [comment]
I just want to note that I did the following two steps and it resolved the issue (a mix of actions in the link abovE)

- Add the following to your Podfile
 
pod 'MDFInternationalization'

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
  end
 end
end


Cheers

**Comment by davidrazmadze** [comment]
> I just want to note that I did the following two steps and it resolved the issue (a mix of actions in the link abovE)
> 
> * Add the following to your Podfile
> 
> pod 'MDFInternationalization'
> 
> post_install do |installer| installer.pods_project.targets.each do |target| target.build_configurations.each do |config| config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0' end end end
> 
> Cheers

THIS WORKED FOR ME. THANK YOU!

**Comment by ShailendraKushwaha** [comment]
Any other solution this didnt work for me.
