### ISSUE TITLE
using Multiple pods in same project creating issues

### ISSUE THREAD

**Issue by rashdan** [material-components/material-components-ios#10208]
I am trying to use two pods in the same project `pod 'MaterialComponents/Tabs+TabBarView'` and `pod 'MaterialComponents/BottomNavigation'` 
but I am facing a lot of errors 

most of the errors are like 

 -> In file included from /Users/user/Documents/project/Baseapp/Categories/CategoriesViewController.m:19:
-> /Pods/Headers/Public/MaterialComponents/MDCTabBarView.h:88:46: error: property has a previous declaration
-> Pods/Headers/Public/MaterialComponents/MDCTabBarView.h:62:3: error: redefinition of enumerator 'MDCTabBarViewLayoutStyleNonFixedClusteredCentered'

fatal error: too many errors emitted, stopping now [-ferror-limit=]

**Comment by sultan-arshi** [comment]
+1

**Comment by subhani-ali** [comment]
+1

**Comment by sultan-arshi** [comment]
I can install both 
for me the problem arises when i `implement` protocol `MDCBottomNavigationBarDelegate`

**Comment by jverkoey** [comment]
We are unlikely to pursue this now that MDC is in maintenance mode: https://github.com/material-components/material-components-ios#materials-ios-libraries-are-in-maintenance-mode-as-of-july-15-2021
