### ISSUE TITLE
Cannot archive app since version 124.2.0

### ISSUE THREAD

**Issue by artemisia-absynthium** [material-components/material-components-ios#10203]
## Description

After updating my `MaterialComponents` pods from version 124.1.1, I cannot archive my app anymore, I get the following error whenever I try:
```
Undefined symbol: _MDFInsetsFlippedHorizontally
```
Just before I have the following warning:
```
ld: warning: ignoring file {Build_dir}/MDFInternationalization/MDFInternationalization.framework/MDFInternationalization, building for iOS-armv7 but attempting to link with file built for iOS-arm64
Undefined symbols for architecture armv7:
  "_MDFInsetsFlippedHorizontally", referenced from:
      -[MDCFloatingButton insetBoundsForBounds:] in MDCFloatingButton.o
ld: symbol(s) not found for architecture armv7
```
Here's what's in my `Podfile`:
```ruby
pod 'MaterialComponents/Banner'
pod 'MaterialComponents/Banner+Theming'
pod 'MaterialComponents/Snackbar'
```

This is the output I got from running `pod update`:

```
Update all pods
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing MDFInternationalization 3.0.0 (was 2.0.0)
Installing MaterialComponents 124.2.0 (was 124.1.1)
Generating Pods project
Integrating client project
Pod installation complete! There are 4 dependencies from the Podfile and 5 total pods installed.
```

## Reproduction steps

1. Unzip the following sample project: [ArchiveBug.zip](https://github.com/material-components/material-components-ios/files/6479423/ArchiveBug.zip)
2. `cd` in its root folder
3. run `pod install`
4. Try to archive it in Xcode

## Expected behavior

An archive is successfully generated.

## Actual behavior

The archiving task fails with the error detailed before.

## Platform

 - Devices: MacBook Pro (13-inch, M1, 2020) and MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)
 - OS: macOS Big Sur Version 11.3 (20E232) both
 - Xcode: Version 12.5 (12E262) both
 - CocoaPods: Version 1.10.1 both

Thank you very much, have a nice day!

**Comment by JJaviMS** [comment]
Hi, after some research, I think it could be related with the latest release of MDFInternationalization. As you can see in it [latest release page](https://github.com/material-foundation/material-internationalization-ios/releases/tag/v3.0.0) they have droped the support for iOS 9 and 10, which I think could have lead to unsupport armv7. As I have seen, Material Components it´s still supporting armv7, which leads that the linker can´t link the armv7 version.

I have found a workaround that allows archiving, in your Podfile make explicit the MDFInternationalization version to the previous one.
`pod 'MDFInternationalization','~>2.0'`

**Comment by karanayyana** [comment]
add deployment target in pod file, this should work.
config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'

https://stackoverflow.com/questions/54704207/the-ios-simulator-deployment-targets-is-set-to-7-0-but-the-range-of-supported-d

**Comment by nimamogh** [comment]
I also want to confirm that I had the same issue & in my case, the mix of solutions by both @karanayyana and @JJaviMS worked (not separately though). Meaning I needed to add the following to my Podfile:

pod 'MDFInternationalization'

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
  end
 end
end

**Comment by artemisia-absynthium** [comment]
Eventually I ended up using @karanayyana 's solution, that also freed me from a lot of Pods warnings, but I'm not 100% convinced I'm totally ok with it either because I think it should work out of the box (by pinning the MDFInternationalization version to 2.0.0 in MaterialComponents Podspec or by raising its deployment target), and because I have always been afraid of adopting said solution because of [these comments](https://github.com/CocoaPods/CocoaPods/issues/7314#issuecomment-494648469) on a Cocoapods issue that raise a rightful concern about arbitrarily changing the deployment target of Pods.

I'd like to hear the maintainers' opinion about this topic.

**Comment by federicopolesello** [comment]
+1

**Comment by diegogarciar** [comment]
for me adding armv7 to excluded architectures on the `MDFInternationalization`, `MDFTextAccessibility` and `MaterialComponents` pod targets fixed it for me, maybe this be added to cocoapods?

**Comment by artemisia-absynthium** [comment]
@diegogarciar unfortunately this cannot be considered a definitive solution because it breaks building the project on Macs with M1.

**Comment by jverkoey** [comment]
Material libraries for iOS entered maintenance mode as of July 15, 2021. Learn more at https://github.com/material-components/material-components-ios#material-components-for-ios.

**Comment by ZXERSTON** [comment]
Hi, this

post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
end
end
end

is not a solution because now flutter uses this

post_install do |installer|
  installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)
  end
end


i am facing the same issue. Anyone has any idea?

**Comment by Haileysayhi** [comment]
Hey!
For me adding this work!!!
Thanks so much!

pod 'MDFInternationalization'

post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
end
end
end
