### ISSUE TITLE
Voice over not speaking leading and trailing views in MaterialIO filled textfield component

### ISSUE THREAD

**Issue by HimanDhawan** [material-components/material-components-ios#10202]
### Overview
 Here is my code. I have added accessibility for leading view as well as info button but still voice over is not speaking info button. The info button and leading view are accessible elements in the below code.

### Reproduction steps
let infoIconButton = UIButton.init(frame: CGRect.init(x: 0, y: 0, width: 15, height: 15))
infoIconButton.contentMode = .scaleAspectFill
infoIconButton.addTarget(self, action: #selector(infoButtonPressed(button:)), for: .touchUpInside)
infoIconButton.accessibilityLabel = "Icon button"
infoIconButton.setImage(UIImage.init(named: "iconu", in: nil, compatibleWith: nil), for: .normal)
            
textField.leadingViewMode = .always
textField.leadingView = infoIconButton
textField.leadingView?.isAccessibilityElement = true
textField.leadingView?.accessibilityTraits = .button
textField.leadingView?.accessibilityLabel = "Icon button"

### Version number
 - Foind in 124.2.0

### Operating system and device

IOS 14 and other version which supports voice over.

**Comment by andrewoverton** [comment]
Hi @HimanDhawan , which text field are you using specifically? What is the name of the class?

**Comment by HimanDhawan** [comment]
@andrewoverton : I am using MDCFilledTextField.

**Comment by HimanDhawan** [comment]
@andrewoverton I need the voice over for distributing build. Can we have a quick solution?

**Comment by andrewoverton** [comment]
Hi @HimanDhawan, I sent out an internal change. It will hopefully land in the `develop` branch soon. It'll make it into a release in the next week or two. Thanks for filing this issue!
