### ISSUE TITLE
Why is any class in material design not open?

### ISSUE THREAD

**Issue by dineybomfim** [material-components/material-components-ios#10218]
https://github.com/material-components/material-components-ios/blob/e77917902f563d81affa526bf72c62e2a43baad3/components/TextControls/src/OutlinedTextFields/MDCOutlinedTextField.h#L22

Why would the developers make any class in material design not open?
As any other UI component, it's necessary to make changes and customization as different apps have different requirements.

Maybe they thought the idea of Themeing could solve it all. But there are "things we don't know we don't know", so restricting customization just to theming isn't enough

In the end of the day, not making it open wont stop anyone from subclassing it...  after all people will Fork it to make the changes, or do it locally.

If the goal of MDC is making it easier to create UI, it's just logical that every class should be subclassable, just like in UIKit

**Comment by jverkoey** [comment]
The primary reason for this is that subclassing makes migrations within a mono repo incredibly challenging. We generally prefer exposing explicit APIs and composing interfaces together in order to enable specific features or customizations over subclassing for this reason.
