### ISSUE TITLE
MDCAlertController, can't setup accessibility label to message text.

### ISSUE THREAD

**Issue by paveltereschenko** [material-components/material-components-ios#10210]
> For usage questions: ask on [Stack  Overflow](https://stackoverflow.com/questions/tagged/material-components+ios).

## Reproduction steps

![image](https://user-images.githubusercontent.com/85117696/120214135-bb3b8b00-c23c-11eb-8b93-236f1830f36b.png)

1. Enable Voice Over.
2. Call any MDCAlertController.

## Expected behavior

Device must read accessibility from message.

**Comment by codeman7** [comment]
Hey @paveltereschenko by default a Dialog's message is accessible, if you want the accessibilityLabel to be something different that what the message is it is recommended to use the `messageAccessibilityLabel` API.
