### ISSUE TITLE
Has no Package.swift manifest for version 124.2.0

### ISSUE THREAD

**Issue by MalinGunasekara** [material-components/material-components-ios#10224]
When I Try to install material-components-ios with XCode Version 12.5 (12E262) with Swift Package Manager.
XCode is not allowing me to continue.

error ->
Has no Package.swift manifest for version 124.2.0 in https://github.com/material-components/material-components-ios/

<img width="657" alt="Screenshot 2021-08-12 at 11 05 24 AM" src="https://user-images.githubusercontent.com/22995308/129161142-48a4ec12-f3a6-4c8e-b264-eb5b2ecc4409.png">

**Comment by jverkoey** [comment]
As of July 15 MDC entered maintenance mode. Learn more at https://github.com/material-components/material-components-ios#material-components-for-ios
