### ISSUE TITLE
[ButtonBar] List of issues needing to be triaged

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#1023]
ButtonBar is a possible replacement for UIToolbar. UIToolbar has some API that we don't mimic yet: style, initWithBarButtonSystemItem:, landscapeImagePhone, imageInsets, landscapeImagePhoneInsets, possibleTitles.

Are any of them a very good idea to implement?

Comes from this original note.
>
#### Unsupported

TODO(featherless): File issues for each of these.

- `style` is ignored.
- instances initialized with `initWithBarButtonSystemItem:`. See
  issue [#264](https://github.com/material-components/material-components-ios/issues/264) for more details.
- `landscapeImagePhone`
- `imageInsets`
- `landscapeImagePhoneInsets`
- `possibleTitles`
>

Triage and split into individual issues.

---
#### Internal data
- Associated internal bug: [b/117179255](http://b/117179255)

**Comment by ajsecord** [comment]
What are we doing with this issue? Does @jverkoey know about it?

**Comment by willlarche** [comment]
No updates. Needs attention. I don't believe he does.

**Comment by ajsecord** [comment]
@willlarche can you investigate and possibly make individual issues that contributors can pick up?

**Comment by willlarche** [comment]
I've updated title and description

**Comment by material-mirror** [comment]
The internal issue [b/117179255](http://b/117179255) is now closed. This issue is being closed as a result.
