### ISSUE TITLE
[Typography] Verify standalone FontLoader repo has current testing and samples.

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1032]
We are removing FontLoader and RobotoFontLoader from the MDC repo.

Ensure that the stand alone repo has that 'final' tests and samples from MDC.

**Comment by ajsecord** [comment]
@ianegordon can we close this? I don't have enough information here.

**Comment by ianegordon** [comment]
I see the examples and tests/unit.
LGTM.
