### ISSUE TITLE
[SpritedAnimationView] Verify standalone repo has current testing and samples. 

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1033]
We are removing SpritedAnimationView from the MDC repo.

Ensure that the stand alone repo has that 'final' tests and samples from MDC.

**Comment by ajsecord** [comment]
@ianegordon if this is complete, can you close? If not, add what needs to happen here.

**Comment by ianegordon** [comment]
MDFSpritedAnimationView has a sample app and initial tests.
LGTM.
