### ISSUE TITLE
[NavigationBar] Add how-to replace UINavigationBar with MDCNavigationBar instructions

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#1034]
Replaces 
>TODO(featherless): Describe the most common integration steps.>

---
#### Internal data
- Associated internal bug: [b/117179213](http://b/117179213)

**Comment by ajsecord** [comment]
This particular TODO seems to have gone away. There is still another in there, but do you want this to remain open?

**Comment by willlarche** [comment]
I can't say for sure. @jverkoey can you remind us what you had planned here?

**Comment by willlarche** [comment]
Updated title. There needs to be some documentation on dropping this class in to replace a UINavigationBar

**Comment by material-mirror** [comment]
The internal issue [b/117179213](http://b/117179213) is now closed. This issue is being closed as a result.
