### ISSUE TITLE
[FlexibleHeaderView] Fails unit tests on iPhone 5 simulator - 8.4

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1040]
From the MDCCatalog project - iPhone 5 (8.4), kick off a Test.

Actual behavior:
The following two tests fail:
testFlexibleHeaderViewControllerTopLayoutGuideHeightOffsetScrollingUpOffscreenKeepStatus
testFlexibleHeaderViewControllerTopLayoutGuideHeightOffsetScrollingUpOffscreenHideStatus

Expected behavior:
The tests pass.

These tests work on iOS 9+.  We should not have different behavior on iOS 8.

**Comment by ajsecord** [comment]
@ShepJGoogle should take a look at this. Also, can we rename `flexibleHeaderViewControllerHeightOffset` to something shorter, please?
