### ISSUE TITLE
-ic_arrow_backUseNewStyle: is in a private component

### ISSUE THREAD

**Issue by Arcank** [material-components/material-components-ios#1078]
### Overview
`ic_arrow_backUseNewStyle:` is in a private component. I would need to set it to `YES` because it will make a disparate UI until other surfaces not using `NavigationBar` are adapted.

### Reproduction steps
Have an app with a back arrow resource in one place, and a `NavigationBar` in another. If not setting `ic_arrow_backUseNewStyle:YES`, the UI is disparate.

### Version number
67e80ddbebf3ad81d3a881e674365710f0ca1732

### Operating system and device
All iOS

**Comment by jverkoey** [comment]
This looks obsolete, but if I'm wrong please re-open.

**Comment by jverkoey** [comment]
I don’t believe the intent here is to make the icons component public. It’s to add an api to allow using the old-style back icons. We do not intend to support the old-style icons, so unless this is still a needed feature (which I’ll defer to @arcank on) then this issue is obsolete.

**Comment by romoore** [comment]
This API can be deleted, there are no internal clients using it.

**Comment by jverkoey** [comment]
Rad - can you file an issue to track deleting the API?
