### ISSUE TITLE
[Collections] Only some select/reorder icons are animated in when scrolling in edit mode

### ISSUE THREAD

**Issue by jyquinn** [material-components/material-components-ios#1089]
### Overview
After first entering edit mode and scrolling, the first few cells have the select/reorder icons animated in and the rest are scrolled in with the icons in place. 

### Reproduction steps
Open catalog app
Tap Collections
Tap Cell Editing Example
Tap EDIT
Scroll down. Observe that the the first view cells have the controls animated in, and the rest do not.

### Version number
19.0.3

### Related issues
#988

**Comment by ajsecord** [comment]
Thanks for the report—I'm curious if this is still occurring given that #988 is closed?

**Comment by jyquinn** [comment]
Yes, this is still happening. It's a follow on to #998 - the solution there prevented the icon overlap, but not the animation discrepancy.

**Comment by ianegordon** [comment]
We are not intending on any significant updates to the current Collections component. 😞
We are working on a much simpler [List component](https://github.com/material-components/material-components-ios/tree/develop/components/List). 😄
