### ISSUE TITLE
[AppBar] Add RTL Support

### ISSUE THREAD

**Issue by gambard** [material-components/material-components-ios#1099]
AppBar does not provide RTL support. Is it expected?
Might be duplicate of #1056

**Comment by Arcank** [comment]
#1056 is about PageControl.
AppBar RTL should be handle by https://github.com/material-components/material-components-ios/commit/d4ec6ee060c88cac48ceac1ce7e14158070f9ef3, but it gives us wrong layout in Chromium.
Gauthier, could you add screenshots (either in Catalog or Chromium)?

**Comment by gambard** [comment]
Here are the screen shots.
This is the "AppBarTypicalUseExample" but adding a _appBar.navigationBar.titleAlignment = MDCNavigationBarTitleAlignmentLeading style.
![simulator screen shot dec 20 2016 3 01 42 pm](https://cloud.githubusercontent.com/assets/1257452/21353228/62e80c66-c6c5-11e6-80d2-29bfd00d0414.png)

As the problem might not be directly visible, here is a screenshot of the frames for all objects.
![screen shot 2016-12-20 at 3 01 45 pm](https://cloud.githubusercontent.com/assets/1257452/21353220/5541467c-c6c5-11e6-8e1d-1a47392b9494.png)

Directly linked to #579 then.

**Comment by gambard** [comment]
Thanks for the fix. Do you know if a release is planned this week so we can include those changes?

**Comment by jgunaratne** [comment]
The latest release should have this fix included.
