### ISSUE TITLE
[AlertController] Width is too long after rotation.

### ISSUE THREAD

**Issue by gambard** [material-components/material-components-ios#1104]
### Overview
![simulator screen shot dec 23 2016 2 22 44 pm](https://cloud.githubusercontent.com/assets/1257452/21454767/6c0d3c46-c91b-11e6-94ce-d3f8bab82934.png)
Screen size is important. Best reproducible on 6+/6s+/7+

### Reproduction steps
 - Launch the DialogAlertViewController demo in portrait
 - Click show alert
 - Rotate the device in landscape
 - Rotate back in portrait
 - The width is not right

### Version number
 - b1eb638d70792b7aa06118b128e3518c20e2aaae

### Operating system and device
 - iOS 10.2.1, iPhone 6s+

**Comment by ianegordon** [comment]
Width layout after the second rotation is broken.
Reproducible on sims and devices.
Reproducible on iOS 8.1 - 10.2.

As gambard@ noted, it is much more reproducible on the iPhone + sizes and on later version of iOS.

**Comment by ianegordon** [comment]
A call to preferredContentSize was resulting in bounds getting updated, but we were still calculating based an on old cached bounds.
