### ISSUE TITLE
[AppBar] AppBar button's ink does not disappear after rotation in form sheet

### ISSUE THREAD

**Issue by gambard** [material-components/material-components-ios#1105]
### Overview
While presenting a View in UIModalPresentationFormSheet, when moving from a horizontally compact environment to a horizontally regular environment while having an AppBar button highlighted, the ink of the button is still present even if the button is no longer highlighted.
Doing it again will add ink again, making the button darker (and so on).
Reproducible on iPhone 6+/6s+/7+ only

### Reproduction steps
 - Open a UIModalPresentationFormSheet ViewController with an AppBar in portrait.
 - Press an AppBar button without releasing it
 - Rotate device orientation (the view is now displayed as a form sheet)
 - Release the button
 - The ink is still present

### Version number
 - 4e5a18715bedf3ada7fd35ba9d2d41082fbf7437

### Operating system and device
 - iOS 10.2.1 iPhone 6s+

---
#### Internal data
- Associated internal bug: [b/117179312](http://b/117179312)

**Comment by material-mirror** [comment]
The internal issue [b/117179312](http://b/117179312) is now closed. This issue is being closed as a result.
