### ISSUE TITLE
[New Feature] Implement the bottom bar for navigation

### ISSUE THREAD

**Issue by omerziv** [material-components/material-components-ios#1127]
Following today's reviews, build the bottom bar components. 

- Play Newsstand seems to follow Material Design guidelines very well, we should consider reaching out to them (Sehee should review to make sure we're actually matching the guidelines.)
- We need to make sure we're building all 3 options: Icons and text, text only, icons only.

**Comment by ajsecord** [comment]
@liquidx @omerziv I think our original guidance was to use the UIKit tabs on iOS apps. Do recall if this has changed?

**Comment by romoore** [comment]
I believe this was implemented as Bottom Navigation.  Please reopen if something is missing.
