### ISSUE TITLE
[Docs] Best practices document

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#1140]
### Overview
Knowledge that's been captured internally but affects common decisions in MDC should be available for reference to the OSS community.

### Example: 

 - UIAppearance and default values: @ianegordon collected research and recommendations

---
#### Internal data
- Associated internal bug: [b/117179409](http://b/117179409)

**Comment by material-mirror** [comment]
The internal issue [b/117179409](http://b/117179409) is now closed. This issue is being closed as a result.
