### ISSUE TITLE
MDCButton tintColor overrides customTitleColor

### ISSUE THREAD

**Issue by Icycle** [material-components/material-components-ios#1195]
### Overview
For usage questions: ask on [Stack  Overflow](https://stackoverflow.com/questions/tagged/material-components+ios).

 - Context, problem or idea, solution or next step
 - Screenshots/Video (if possible)
 - Stack trace (if possible)

A recent change updated MDCButton to respect tintColor.  This was accomplished by setting the customTitleColor property when tintColor changes.  This means that if tintColor is directly or indirect set, any customTitleColor value will be overwritten.

The documentation comment for the customTitleColor property strongly implies that this property takes highest precedence and overrides any automatic color setting.

I believe that either the button title color setting logic should be updated to respect the tintColor property and also respect customTitleColor as set by the client OR the documentation comment for customTitleColor should be updated to reflect the fact that it will be set if tintColor is set.

### Reproduction steps
N/A

### Version number
21.0.1

### Operating system and device
N/A

### Related issues
#602

**Comment by romoore** [comment]
customTitleColor has been deprecated and we will rely instead on `-[UIButton titleColor:forState:]`
