### ISSUE TITLE
[Typography] traitsForTextStyle: is marked nonnull but can return null

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#1199]
Found using static analyzer. Implementation needs nullability decoration too.

Should it be nullable? Or should there be a backup to prevent sending nil?

**Comment by willlarche** [comment]
Xcode 8.3

**Comment by ianegordon** [comment]
This is not an actual bug, but we need to identify to the static analyzer that this is safe.

Unless it is causing immediate distress, I'd prefer to wait until Xcode 8.3 final is available to fix this.
