### ISSUE TITLE
MDCCollectionViewController SupplementaryView Implementation Refactor

### ISSUE THREAD

**Issue by ShepJGoogle** [material-components/material-components-ios#1208]
### Overview
The MDCCollectionViewController implements the collectionView:viewForSupplementaryElementOfKind:atIndexPath: UICollectionViewDataSource method. Within, the collection view lazily registers classes for header and footer views used in editing mode. This leads to a crash for collection views entering edit mode with section headers or footers.

- Class registration should be moved out of the data source method
- Find alternatives for current MDCCollectionInfoBarKindHeader and MDCCollectionInfoBarKindFooter implementation  

### Version number
21.1.0

### Sample Code
Below is the implementation file of an MDCCollectionViewController subclass.
`
//  ViewController.m
//  CollectionHeader
//

#import "ViewController.h"

@interface ViewController ()

@property(strong, nonatomic) NSMutableArray *colors;

@end

@implementation ViewController

- (void)viewDidLoad {
  [super viewDidLoad];

  [self updatedRightBarButtonItem:NO];
  self.view.backgroundColor = [UIColor whiteColor];

  [self.collectionView registerClass:[MDCCollectionViewTextCell class]
          forCellWithReuseIdentifier:@"CollectionCell"];
  [self.collectionView registerClass:[MDCCollectionViewTextCell class]
          forSupplementaryViewOfKind:UICollectionElementKindSectionHeader
                 withReuseIdentifier:UICollectionElementKindSectionHeader];
  
  _colors = [NSMutableArray arrayWithArray:@[ @"red", @"blue", @"green", @"black", @"yellow", @"purple" ]];

  self.styler.cellStyle = MDCCollectionViewCellStyleCard;
}

- (void)updatedRightBarButtonItem:(BOOL)isEditing {
  self.navigationItem.rightBarButtonItem =
  [[UIBarButtonItem alloc] initWithTitle:isEditing ? @"Cancel" : @"Edit"
                                   style:UIBarButtonItemStyleDone
                                  target:self
                                  action:@selector(toggleEditMode:)];
}

- (void)toggleEditMode:(id)sender {
  BOOL isEditing = self.editor.isEditing;
  [self updatedRightBarButtonItem:!isEditing];
  [self.editor setEditing:!isEditing animated:YES];
}

- (void)didReceiveMemoryWarning {
  [super didReceiveMemoryWarning];
  // Dispose of any resources that can be recreated.
}

#pragma mark - <UICollectionViewDataSource>

- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView *)collectionView {
  return 1;
}

- (NSInteger)collectionView:(UICollectionView *)collectionView
     numberOfItemsInSection:(NSInteger)section {
  return _colors.count;
}

- (UICollectionViewCell *)collectionView:(UICollectionView *)collectionView
                  cellForItemAtIndexPath:(NSIndexPath *)indexPath {
  MDCCollectionViewTextCell *cell =
  [collectionView dequeueReusableCellWithReuseIdentifier:@"CollectionCell"
                                            forIndexPath:indexPath];
  cell.textLabel.text = _colors[indexPath.item];
  return cell;
}

- (UICollectionReusableView *)collectionView:(UICollectionView *)collectionView viewForSupplementaryElementOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath
{
  MDCCollectionViewTextCell *supplementaryView =
  [collectionView dequeueReusableSupplementaryViewOfKind:kind
                                     withReuseIdentifier:kind
                                            forIndexPath:indexPath];

  if ([kind isEqualToString:UICollectionElementKindSectionHeader]) {
    supplementaryView.textLabel.text = @"Section header";

  } else if ([kind isEqualToString:UICollectionElementKindSectionFooter]) {
    supplementaryView.textLabel.text = @"Section footer";
  }

  return supplementaryView;
}

#pragma mark UICOllectionViewFlowLayoutDelegate

- (CGSize)collectionView:(UICollectionView *)collectionView
                  layout:(UICollectionViewLayout *)collectionViewLayout
referenceSizeForHeaderInSection:(NSInteger)section {
  if (section == 0) {
    return CGSizeMake(collectionView.bounds.size.width, MDCCellDefaultOneLineHeight);
  }
  return CGSizeZero;
}

#pragma mark - <MDCCollectionViewEditingDelegate>

- (BOOL)collectionViewAllowsEditing:(UICollectionView *)collectionView {
  return YES;
}

- (BOOL)collectionViewAllowsReordering:(UICollectionView *)collectionView {
  return YES;
}

- (BOOL)collectionViewAllowsSwipeToDismissItem:(UICollectionView *)collectionView {
  return self.editor.isEditing;
}

- (void)collectionView:(UICollectionView *)collectionView
willDeleteItemsAtIndexPaths:(NSArray<NSIndexPath *> *)indexPaths {
  NSArray *sortedArray = [indexPaths sortedArrayUsingSelector:@selector(compare:)];
  for (NSIndexPath *indexPath in [sortedArray reverseObjectEnumerator]) {
    [_colors removeObjectAtIndex:indexPath.item];
  }
}

- (void)collectionView:(UICollectionView *)collectionView
willMoveItemAtIndexPath:(NSIndexPath *)indexPath
           toIndexPath:(NSIndexPath *)newIndexPath {
    [_colors exchangeObjectAtIndex:indexPath.item
                                     withObjectAtIndex:newIndexPath.item];
}

@end
`

### Reproduction

1.) Load viewcontroller on screen
2.) Attempt to enter edit mode by pressing "Edit"
3.) Crash
 
![screen shot 2017-02-15 at 11 58 56 am](https://cloud.githubusercontent.com/assets/19916772/22985389/47a5c8d4-f376-11e6-9d34-f38b20fd07ed.png)

### Crash Report
![screen shot 2017-02-15 at 11 59 34 am](https://cloud.githubusercontent.com/assets/19916772/22985458/7ce22038-f376-11e6-8307-6dc646532430.png)

Any subclass of MDCCollectionViewController will look for a header and footer which is registered in the superclass. When it can't find it, the application terminates.

**Comment by Arcank** [comment]
Can you provide more details on the crash? Is it because headers and footers are only present in edit mode?
Can you point to the code?

**Comment by ShepJGoogle** [comment]
Hey @Arcank just updated the description.

**Comment by ianegordon** [comment]
We are not intending on any significant updates to the current Collections component. 😞
We are working on a much simpler [List component](https://github.com/material-components/material-components-ios/tree/develop/components/List). 😄
