### ISSUE TITLE
dynamic text api's ignores font set by font loader.

### ISSUE THREAD

**Issue by randallli** [material-components/material-components-ios#1217]
[mdc_preferredFontForMaterialTextStyle](https://github.com/material-components/material-components-ios/blob/develop/components/Typography/src/UIFont%2BMaterialTypography.h#L27) does not use the fonts from the font loader.

This should either start using the fonts from the loader or it should assert if a font loader has been set. A second assert should be thrown if the font loader API is used after the mdc_preferredFontForMaterialTextStyle API

**Comment by ianegordon** [comment]
Done in the PR above.

**Comment by ianegordon** [comment]
This is complete.
