### ISSUE TITLE
[Palettes] Replace hex to RGB functions w/ dependency to Palettes and its function

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#1221]
### Overview
Several pods have a hex to RGB function. There's already one in the Palettes tho. Let's migrate to that and make Palettes a common lightweight dependency.

### Reproduction steps

See:
37:MDCPalettes.m:
static inline UIColor *ColorFromRGB(uint32_t rgbValue) 

65:MDCButton.m:
static inline UIColor *MDCColorFromRGB(uint32_t rgbValue)

36:MDCCollectionInfoBarView.m:
static inline UIColor *ColorFromRGB(uint32_t rgbValue) 

30:MDCProgressView.m:
static inline UIColor *MDCColorFromRGB(uint32_t rgbValue) 

33:MDCSlider.m:
static inline UIColor *MDCColorFromRGB(uint32_t rgbValue)

**Comment by sigito** [comment]
@willlarche, regarding `Snackbar`. It has a few RGB encoded colors. However, some of them are black colors with different alpha. Should they be replaced to `UIColor.blackColor#colorWithAlphaComponent:`?

Also, according to the [spec](https://material.io/guidelines/components/snackbars-toasts.html#snackbars-toasts-specs) a default background color is `0x323232`, which is not in [the color palette](https://material.io/guidelines/style/color.html#color-color-palette). Any ideas on how to approach this?

**Comment by romoore** [comment]
No longer desired. See conversation in #2962
