### ISSUE TITLE
[Palettes] Convert hardcoded colors in component to relative palette value

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#1222]
### Overview
Almost every component uses a color chosen by the Material designers. Right now those colors are hardcoded to avoid using Palettes as a dependency. 

If the Material palette changed, we would not get those changes 'for free' in the components; each one would have to be found and changed. As they are almost always stored by hex value, that would be incredibly difficult to do.

### Reproduction steps
See:
56:MDCButton.m:
// Blue 500 from http://www.google.com/design/spec/style/color.html#color-color-palette .
static const uint32_t MDCButtonDefaultBackgroundColor = 0x2196F3;

That could be replaced with the much more human readable, and verifiably correct,:
[[MDCPalette bluePalette] tint500]

### Related issues
#1221

**Comment by sigito** [comment]
Hi @willlarche, I can take care of this. I can see that in some places you have inline functions which simply return a proper color. Is it the way all of the color constants should be replaced?

E.g., [`MDCCollectionViewCell`](https://github.com/material-components/material-components-ios/blob/develop/components/CollectionCells/src/MDCCollectionViewCell.m#L36): 
```
static inline UIColor *MDCCollectionViewCellGreyColor(void) {
  return MDCPalette.greyPalette.tint700;
}
```

**Comment by willlarche** [comment]
Hey! No, those functions are fine. They are actually the best way to have "constant objects" (which doesn't really exist.)

This may be done-ish now but this ticket is to replace all cases of colors defined by float values (RGB or CMYK or HSB) with palettes. So, your example is actually done!

**Comment by sigito** [comment]
Yeah, the function was an example of how this issue should be fixed.

1. What about `Palettes` component itself? Should it stay untouched?
1. As per #1221, as I understand the ideal case would be to remove any RGB/CMYK/HSB encoded colors with just a call to `MDCPallette` fields, right?

**Comment by willlarche** [comment]
Oh, sorry! I mis-read.

1. The Palettes component should not be changed. Just used.
2. That's right! And it would be great if any times it's not possible (because the color is bespoke to the work) that it's commented as such.
3. For examples, try to avoid unless you think it's a fabulous place to showcase Palettes that won't confuse novices. For tests, use your judgement and lean to 'no'. For example, if the test is testing that something that's supposed to be palettes blue 500 actually IS palettes blue 500, that's a keeper. But if something is being set to purple to make sure that changing colors works, don't change that. You'll find both in TextFields, BTW.

**Comment by jverkoey** [comment]
We'll likely continue to use hard-coded values to minimize the risk of changes in downstream dependencies affecting downstream clients of our components.
