### ISSUE TITLE
[Collections] Xcode 8.3 Static Analyzer identifies nonnull methods returning nil

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1227]
Internal client noted that the static analyzer was throwing some valid warning about return nil from nonnull methods in MDCCollectionViewController.

**Comment by ianegordon** [comment]
Looks like the static analyzer in Xcode 8.3 has been updated and has identified a few instances where we aren't handling every case.

**Comment by ShepJGoogle** [comment]
Most of the analyzer issues have been cleared however one, though valid, relates to issue [1208](https://github.com/material-components/material-components-ios/issues/1208) and will require a larger refactor than a few lines of code change. I will submit the current fix and can address 1208 in that ticket.
