### ISSUE TITLE
Enforce private/public distinction in our CocoaPods structure

### ISSUE THREAD

**Issue by ajsecord** [material-components/material-components-ios#1241]
We have two kinds of "private" code in MDC:

1. Private parts of the implementation of a _single_ component.
1. Entirely private components.

Right now our CocoaPods structure doesn't (can't?) enforce privacy, unlike other build systems. 

Private parts of a single component are just built in the same library as their public parts, so problems like circular dependencies between public/private parts can't be detected. Users do have to specify private headers using `#import "private/FooBar.h"`, so at least private parts can't be used accidentally.

Private components have their own subspecs that would have to be referenced in a clients' Podfile as `"MaterialComponents/private/FooBar"`, so they can't be used accidentally.

However, in both cases it would be better to enforce the privacy in some way.

**Comment by randallli** [comment]
we dont include the src/private/*.h in the public headers in our Podspec so we are not exposing the 
1. Private parts of the implementation of a single component.

https://github.com/material-components/material-components-ios/blob/develop/MaterialComponents.podspec#L158

**Comment by ajsecord** [comment]
Ah, you're right. Also, CocoaPods doesn't have a notion of private subspecs, so this won't work. Closing!
