### ISSUE TITLE
[Snackbar] Add haptic feedback when a snackbar is shown

### ISSUE THREAD

**Issue by Arcank** [material-components/material-components-ios#1245]
### Overview
[Snackbar] Add haptic feedback when a snackbar is shown

### Reproduction steps
- Have a snackbar appear.
- Feature request: generate notification haptic feedback.

### Related issues
https://github.com/material-components/material-components-ios/commit/6aae38dfa70db77929ef2952ff3b8fce3caea60b implemented impact feedback for Switch.
Snackbar should issue a [notification haptic feedback](https://developer.apple.com/reference/uikit/uinotificationfeedbackgenerator?language=objc). An example: https://cs.chromium.org/chromium/src/ios/chrome/browser/ui/uikit_ui_util.mm?type=cs&q=TriggerHapticFeedbackForNotification&l=687

---
#### Internal data
- Associated internal bug: [b/117179428](http://b/117179428)

**Comment by willlarche** [comment]
I think should be optional too.

**Comment by ianegordon** [comment]
Consider:
https://www.deque.com/blog/dynamic-notifications/

**Comment by material-mirror** [comment]
The internal issue [b/117179428](http://b/117179428) is now closed. This issue is being closed as a result.
