### ISSUE TITLE
[FlexibleHeaderView] Re-enable sanity check assert on viewDidPan

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1254]
An assert has started firing on iOS 10.3b.
We will temporarily disable it for this release.
We should investigate the root cause and re-enable.

---
#### Internal data
- Associated internal bug: [b/117179529](http://b/117179529)

**Comment by material-mirror** [comment]
The internal issue [b/117179529](http://b/117179529) is now closed. This issue is being closed as a result.
