### ISSUE TITLE
[CollectionCells] Misalignment in MDCCollectionViewTextCell

### ISSUE THREAD

**Issue by gambard** [material-components/material-components-ios#1274]
### Overview
I think the alignment of the labels in MDCCollectionViewTextCell are done on the wrong baseline: 
```
      textFrame.origin.y =
          kCellTwoLinePaddingTop + _textLabel.font.ascender - textFrame.size.height;
      detailFrame.origin.y = boundsHeight - kCellTwoLinePaddingBottom - detailFrame.size.height -
                             _detailTextLabel.font.descender;
```
should probably be modified in 
```
      textFrame.origin.y =
          kCellTwoLinePaddingTop + _textLabel.font.descender - textFrame.size.height;
      detailFrame.origin.y = boundsHeight - kCellTwoLinePaddingBottom - detailFrame.size.height -
                             _detailTextLabel.font.ascender;
```

**Comment by jverkoey** [comment]
Marking as Obsolete because we do not intend to continue to invest effort into Collections. Please consider using the new List component instead: https://github.com/material-components/material-components-ios/tree/develop/components/List

**Comment by atebitsy** [comment]
but you tell us to use Lists instead but they don't support accessoryViews?
