### ISSUE TITLE
[Typography] isLargeForContrastRatios: should return true for medium system fonts on ios 8.0

### ISSUE THREAD

**Issue by randallli** [material-components/material-components-ios#1275]
### Overview
I suspect that we are using an ios 9 api that retrieves the font weight. The end result is that we always return the normal weight rather than medium because the dictionary does not have the values.

### Reproduction steps
 - button with system font loader that shows a text not in the color that was set because the accessibility.

**Comment by maplemuse** [comment]
The font in question is as follows: 

`<UICTFont: 0x162cfe90> font-family: "HelveticaNeue-Medium"; font-weight: normal; font-style: normal; font-size: 14.00pt`

The UIFontWeightTrait for this font is 0.2
```
po [font.fontDescriptor objectForKey:UIFontDescriptorTraitsAttributes]
{
    NSCTFontSlantTrait = 0;
    NSCTFontSymbolicTrait = 16384;
    NSCTFontUIFontDesignTrait = NSCTFontUIFontDesignDefault;
    NSCTFontWeightTrait = "0.2";
}
```

The medium weight being used to determine large font metrics is 0.23.

**Comment by maplemuse** [comment]
b/36466059
