### ISSUE TITLE
[Collections] Add cellWidthAtSectionIndex:

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1283]
We have a request to make [MDCCollectionViewController cellWidthAtSectionIndex:] a public method.

Should we?  Why / why not?

**Comment by willlarche** [comment]
Can we see wireframes or some other secure / redacted visual representation?

**Comment by chatura-atapattu** [comment]
We have a major use case where we want to inset the content from the edges of the screen more than the normal material design as set for a phone.  This is usually the case on tablets, to make the content appear to be better sized than full screen.

**Comment by ianegordon** [comment]
This issue should be solvable via MDCCollectionFlowLayout.sectionInset.

See #1303
