### ISSUE TITLE
Move Overlay from private component to public

### ISSUE THREAD

**Issue by ajsecord** [material-components/material-components-ios#1295]
Overlay is a private component, but while it's private there is no way to actually use it to, e.g., move a floating action button out of the way of a snackbar. The previous internal implementation was public, not private.

SnackbarOverlayViewExample.m uses Overlay to move the FAB, but to do so accidentally uses a private component, which doesn't make sense for example code, which should only use the public API.

An additional twist is that OverlayWindow _is_ a public component, but really it should just be a part of Overlay.

Steps:

1. Move components/private/Overlay to components/Overlay and update clients. This requires an API review, but the API should be pretty much ready to go. Update the Snackbar example to use the public API.
1. Move OverlayWindow into the new Overlay component.

---
#### Internal data
- Associated internal bug: [b/117179548](http://b/117179548)

**Comment by material-mirror** [comment]
The internal issue [b/117179548](http://b/117179548) is now closed. This issue is being closed as a result.
