### ISSUE TITLE
Decommission Phabricator & Diffusion

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1309]
As we are now solely on GitHub, we should turn off the Phabricator instance we were using.

**Comment by willlarche** [comment]
Is any information stored there that's not found here?

**Comment by ianegordon** [comment]
We will lose our historical code reviews and attached comments and some outdated documentation:
http://codereview.cc/diffusion/MDC/

**Comment by ianegordon** [comment]
Approval at Weekly Meeting - 2017 - 4 - 25.

**Comment by ianegordon** [comment]
@jverkoey has disabled this for us.
