### ISSUE TITLE
[Tabs] Text in tabs with title only is not centered vertically

### ISSUE THREAD

**Issue by mms-svhe** [material-components/material-components-ios#1321]
### Overview
In tabs with title only the text is not properly vertically centered, it's slightly off. 

![screen shot 2017-04-13 at 14 15 01](https://cloud.githubusercontent.com/assets/1199100/25004384/725c7e0a-2054-11e7-9169-1f8ac82da12c.png)

### Version number
23.0.1

**Comment by romoore** [comment]
I can take a look at this.
