### ISSUE TITLE
is there a way to know when snackbar/toast is dismissed (callback)? 

### ISSUE THREAD

**Issue by vance** [material-components/material-components-ios#1323]
### Overview
Looking at the the android API, there is addCallback() to know when the toast message is dismissed. Is there a similar API hook for the pod? I looked through the source and didn't see anything obvious. 

thanks

**Comment by ajsecord** [comment]
Yes! You can use the [completion handler](https://github.com/material-components/material-components-ios/blob/develop/components/Snackbar/src/MDCSnackbarMessage.h#L125).

**Comment by patrikqvarnstrom** [comment]
Sorry for commenting on this closed issue but how would I use that exactly? Is there a example somewhere?

**Comment by romoore** [comment]
In [SnackbarSimpleExample](https://github.com/material-components/material-components-ios/blob/develop/components/Snackbar/examples/SnackbarSimpleExample.m), you can assign the completion handler block directly to the message. Be careful of introducing retain cycles if you retain the snackbar message!

```objectivec
- (void)showSimpleSnackbar:(id)sender {
  MDCSnackbarMessage *message = [[MDCSnackbarMessage alloc] init];
  message.text = @"Snackbar Message";
  // Added this assignment to demonstrate completion blocks.
  message.completionHandler = ^(BOOL userInitiated) {
    NSLog(@"Hello, world!");
  };
  [MDCSnackbarManager showMessage:message];
}
```

**Comment by patrikqvarnstrom** [comment]
Wow! Thank you for the this quick and informative response. Great work.

**Comment by romoore** [comment]
You're welcome. Thanks for checking out MDC-iOS!
