### ISSUE TITLE
Adjust warnings in DEBUG versus RELEASE

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1338]
While debugging, treating certain warnings as errors is causing friction.
For instance, if I'm adding logging or inspecting flow, "Unused variable" throwing an error slows development.

We should allow certain warnings through on DEBUG builds, but maintain strict warnings as errors in RELEASE builds so our continuous integration will still catch them.

---
#### Internal data
- Associated internal bug: [b/117179234](http://b/117179234)

**Comment by ajsecord** [comment]
I don't totally agree—since we don't block on CI failing, it feels like this will end up allowing warnings to slip into our build. Historically we had our settings to be as least as strict as the strictest of our clients, and many of our clients have warnings-as-errors on all the time.

**Comment by ianegordon** [comment]
To be explicit, I recommend:
- Enable all possible warnings
- Disable treat warning as errors on DEBUG builds only.

We should be blocking on CI failure.
CI should be testing against RELEASE.

The friction of "Unused Variable" throwing errors during development is excessive.

**Comment by ianegordon** [comment]
From #1986 
We also like want to add:
DEBUG: -Wno-used-but-marked-unused 
RELEASE: -wused-but-marked-unused

**Comment by ianegordon** [comment]
This was bumped into today.
*BUMP*

**Comment by jverkoey** [comment]
One possible solution for this would be to have CI builds enable treating warnings as errors for both debug and release builds.

**Comment by ianegordon** [comment]
Lets adjust the CI builds to treat warnings as errors for both and disable the warnings that make dev / debugging difficult in DEBUG only.

**Comment by ianegordon** [comment]
We haven't taken any action on this in over a year.
Closing as obsolete.
