### ISSUE TITLE
Relayout MDCAppBar when minimumHeight / maximumHeight is set

### ISSUE THREAD

**Issue by thkeen** [material-components/material-components-ios#1339]
After calling **[self.appBar addSubviewsToParent]**, there's no effect of setting **minimumHeight** or **maximumHeight** anymore. This behavior is currently undocumented and the need to change the appBar height after -viewDidLoad is essential in my opinion. At the moment, the workaround is to make the **appBar** track a scrollView, then its frame will be updated accordingly.

---
#### Internal data
- Associated internal bug: [b/117179212](http://b/117179212)

**Comment by material-mirror** [comment]
The internal issue [b/117179212](http://b/117179212) is now closed. This issue is being closed as a result.
