### ISSUE TITLE
Add a note to MDCOverlayWindow docs regarding overriding `window` property

### ISSUE THREAD

**Issue by samnm** [material-components/material-components-ios#1344]
'If you want to provide a custom window for your app, you must implement the getter method of this property and use it to create and return your custom window.'

This isn't commonly known so we should probably have a note in the MDCOverlayWindow docs/comments somewhere.

https://developer.apple.com/reference/uikit/uiapplicationdelegate/1623056-window

---
#### Internal data
- Associated internal bug: [b/117179311](http://b/117179311)

**Comment by material-mirror** [comment]
The internal issue [b/117179311](http://b/117179311) is now closed. This issue is being closed as a result.
