### ISSUE TITLE
Document faithfulness with MD, or iOS adaptations

### ISSUE THREAD

**Issue by dandv** [material-components/material-components-ios#1348]
It would be nice to mention in the README if these components respect MD faithfully, or if they [adapt MD to better fit in with the iOS design concepts](https://material.io/guidelines/platforms/platform-adaptation.html).

**Comment by ajsecord** [comment]
Thanks for the issue! Minor point: Material is designed with the web, iOS, and Android in mind, so "faithful" doesn't mean "identical".
