### ISSUE TITLE
[Buttons] Unable to set the background of a button in a storyboard

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1359]
---
#### Internal data
- Associated internal bug: [b/117179268](http://b/117179268)

**Comment by romoore** [comment]
@ianegordon  - Can you please provide acceptance criteria for this issue? Given that we use a `forState:` API, I'm not sure how much we can connect this to IB.

**Comment by romoore** [comment]
Closing since this was a mirror of itself.
