### ISSUE TITLE
[Codelab] Pull the Codelabs into their own repo

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1360]

**Comment by willlarche** [comment]
I can't think of any good reason to do so. We have all our education code in the same repo as our source. If we move the codelabs, we should move all the other demos too.

**Comment by willlarche** [comment]
I'm starting to change my tune. They add a lot of weight and it will double when we have a Swift version of the one we just wrote.

**Comment by willlarche** [comment]
@joelyoungblood , thanks to your work, the codelab has been successfully updated and [published](https://codelabs.developers.google.com/codelabs/mdc-ios-swift).

**Comment by ianegordon** [comment]
I share your concern about the size of codelabs.  Incredibly useful, (and now with Swift!), but they do take up some room.

Lets revisit this when you are back in the office.

**Comment by joelyoungblood** [comment]
@willlarche yay!

**Comment by ianegordon** [comment]
@ajsecord proposes:
1. Create github.com/material-components/material-components-ios-codelabs
1. Copy the code labs into the new repo. Ditch the history.
1. Delete the code labs from HEAD of MDC-iOS.
1. Delete the giant binaries from our history using BFG repo cleaner.

**Comment by ajsecord** [comment]
Thanks for finding this! I'm doing this now.

**Comment by ajsecord** [comment]
The [new repo](https://github.com/material-components/material-components-ios-codelabs) has been created.

Next steps:

1. Update the [codelab's](https://codelabs.developers.google.com/codelabs/mdc-ios/index.html) source to refer to the new location.
1. Verify re-writing history will not impact client teams.
1. Delete the code labs from HEAD of MDC-iOS.
1. Delete the giant binaries from our history using BFG repo cleaner.

**Comment by willlarche** [comment]
Btw: we should take history with us to the new repo. It's not really fair
to the external contributor that worked on this to be removed.

**Comment by ajsecord** [comment]
Agreed about fairness to the contributor. I'll start again with [these instructions](https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/).

**Comment by willlarche** [comment]
Great! Thank you.

**Comment by ajsecord** [comment]
Ok, https://github.com/material-components/material-components-ios-codelabs now has history again. Thanks @willlarche !

**Comment by willlarche** [comment]
Thanks, Adrian!

**Comment by ajsecord** [comment]
[Codelabs](https://codelabs.developers.google.com/codelabs/mdc-ios/index.html) are updated.

**Comment by willlarche** [comment]
This is done.
