### ISSUE TITLE
collectionview delete

### ISSUE THREAD

**Issue by Brynogay** [material-components/material-components-ios#1399]
### Overview
For usage questions: ask on [Stack  Overflow](https://stackoverflow.com/questions/tagged/material-components+ios).

 - Context, problem or idea, solution or next step
 - Screenshots/Video (if possible)
 - Stack trace (if possible)

### Reproduction steps
 - Detailed steps to reproduce

### Version number
 - Found in CHANGELOG.md

### Related issues
 - Type `#` and the issue number or `#` and select the from the inline drop down.

**Comment by ianegordon** [comment]
It looks like we lost the body of your issue.  Can you offer some insight into your problem?
