### ISSUE TITLE
[FeatureHighlight] Make the FeatureHighlightView private again?

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1416]
We recently moved FeatureHighlightView from private to public to expose some UI_APPEARANCE properties.

Can we move it back to private and just expose the properties we need publicly?  This will allow us to make changes to MDCFeatureHighlightView without going through deprecation.

This could be done with a public category in MDCFeatureHighlightView+MDCAppearance.h:

@interface MDCHighlightView (MDCAppearance)

@property(nonatomic, strong) UIColor *outerHighlightColor UI_APPEARANCE_SELECTOR;
@property(nonatomic, strong) UIColor *innerHighlightColor UI_APPEARANCE_SELECTOR;

@end

**Comment by ianegordon** [comment]
Discussed offline.
@jgunaratne is preparing a PR.

**Comment by jgunaratne** [comment]
Addressed in https://github.com/material-components/material-components-ios/pull/1422
