### ISSUE TITLE
Audit code for non-copy block properties

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1423]
We have non-copy block properties.
Should we change them to copy?

---
#### Internal data
- Associated internal bug: [b/117179466](http://b/117179466)

**Comment by ajsecord** [comment]
[Yes](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/WorkingwithBlocks/WorkingwithBlocks.html#//apple_ref/doc/uid/TP40011210-CH8-SW12)

> Note: You should specify copy as the property attribute, because a block needs to be copied to keep track of its captured state outside of the original scope. This isn’t something you need to worry about when using Automatic Reference Counting, as it will happen automatically, but it’s best practice for the property attribute to show the resultant behavior.

**Comment by ianegordon** [comment]
Make all block properties copy.

**Comment by romoore** [comment]
Looks like they all have `copy` semantics.
