### ISSUE TITLE
[Typography] Support for font customization when using Dynamic Type

### ISSUE THREAD

**Issue by Icycle** [material-components/material-components-ios#1424]
### Overview

The current implementation of MDC Typography handles Dynamic Type by constructing a UIFontDescriptor with specific weight for the given style and size category, and a point
size for the given style and size category, and a font is constructed with the font descriptor. The font family attribute is left unspecified, so the specific font family returned is left to the undocumented behavior of UIFont.  Based on some preliminary experimentation, it appears that a UIFont in the Helvetica family will be returned.

I would suggest that the default behavior of MDC should be to extract the family attribute from a font returned by MDCSystemFontLoader, and use that to explicitly specify the font family attribute for Dynamic Type fonts so that they will come from the same family as non-Dynamic Type fonts in the same app.

I would further suggest that the MDCTypographyFontLoading protocol be extended with an additional optional method, named something like dynamicTypeFontFamily which returns a string value.  When MDC is constructing a Dynamic Type font, if the currently set font loader responds to this selector, it should use the return value of this selector to specify the font family.

### Reproduction steps
N/A

### Version number

23.1.0

### Operating system and device

iOS 10.X

### Related issues
 N/A

**Comment by ianegordon** [comment]
The font family is now explicitly noted.

Regarding support for custom fonts, iOS 11 has added UIFontMetrics to address this issue.

**Comment by ianegordon** [comment]
Done.
