### ISSUE TITLE
[Palette] Make MDCPalette entries class properties

### ISSUE THREAD

**Issue by mpetrov** [material-components/material-components-ios#1436]
### Overview

Currently MDCPalette entries are defined as methods:
`  + (nonnull MDCPalette *)redPalette;`

It would be nice if these were instead defined as class properties.
`  @property(class, readonly, strong, nonnull) MDCPalette *redPalette;`

This would change Swift calls from `MDCPalette.red()` to `MDCPalette.red`, and would be more consistent with UIColor.

### Version number
 - Found in 23.2.0

**Comment by ianegordon** [comment]
SGTM.  
Note that this will cause an API change for Swift users that we may not be able to deprecate first.
