### ISSUE TITLE
[FeatureHighlight] Setting outerHighlightColor changes the text color to surprising values

### ISSUE THREAD

**Issue by mpetrov** [material-components/material-components-ios#1442]
### Overview

Setting a custom outerHighlightColor produces dark text when we'd typically expect light.

### Reproduction steps

Based on the material spec (https://material.io/guidelines/style/color.html#color-color-palette) we  would expect setting an outer highlight to blue500 to set the text color to white:
`outerHighlightColor = MDCTypography.blue().tint500`

Instead the text is black, and only shifts to white at blue700. Not sure if this is due to a bug in MDFTextAccessibility.

### Version number
 - 23.2.0

**Comment by samnm** [comment]
There seems to be a problem with either the Material spec or MDFTextAccessibility... I have created an issue here #1447 and will update this bug when I get more details.

**Comment by samnm** [comment]
Closing this as you can now set the text color if the automatically provided value isn't what you're after. See #1496.
