### ISSUE TITLE
MDC Dialog animation duration feels slow

### ISSUE THREAD

**Issue by thkeen** [material-components/material-components-ios#1445]
Currently it is set to 0.5s which roughly double the time of a normal duration for pushing view controllers in iOS. I have been trying but never get used to it, too different from normal iOS transition (0.27s). Can we double check and make necessary adjustment?

https://github.com/material-components/material-components-ios/blob/develop/components/Dialogs/src/MDCDialogTransitionController.m#L23

Thanks!

**Comment by ianegordon** [comment]
Hi Kien, it does seem like this should be faster.  Let me see if I can track down guidance, but if it becomes tricky I'm happy to lower it to the OS default (0.27).

**Comment by thkeen** [comment]
That sounds good.
