### ISSUE TITLE
[Collections] Hiding ink prevent interaction

### ISSUE THREAD

**Issue by gambard** [material-components/material-components-ios#1446]
### Overview
Having collectionView:hidesInkViewAtIndexPath: returning YES prevents interaction with the cells at the given indexPath. If the function returns NO, the interactions are fine.

### Reproduction steps
 - Implements collectionView:hidesInkViewAtIndexPath:, returning YES for some cells, NO for some others
 - collectionView:didSelectItemAtIndexPath: is never called for the cell which have the ink hidden

### Version number
23.2

**Comment by willlarche** [comment]
After watching a client struggle with this recently, I believe it needs to
be on the cell level. People are expecting to just have hasInk = false

**Comment by gambard** [comment]
Sorry for the late answer, I was OOO.
The CollectionView-level function is fine for me, it is just not working as it is now.
I can workaround the issue by setting the ink color to clearColor for those cell but it is not ideal.
