### ISSUE TITLE
[MDCCollectionViewCell|MDCShadowLayer] elevation rendered incorrectly when using opaque background in MDCCollectionViewCell

### ISSUE THREAD

**Issue by bosbefok** [material-components/material-components-ios#1454]
I'm having an issue with the appearance of an elevated MDCCollectionViewCell being inconsistent after scrolling or updating the collectionView. The issue only occurs when using an opaque background.

Elevation was implemented as per example and is set to 2pt within the cell init:
```
    override init(frame: CGRect) {
        super.init(frame: frame)
        backgroundColor = UIColor.groupTableViewBackground
        setElevation(points: 2.0)
    }

    override class var layerClass: AnyClass {
        return MDCShadowLayer.self
    }
    
    var shadowLayer: MDCShadowLayer {
        return self.layer as! MDCShadowLayer
    }
    
    func setElevation(points: CGFloat) {
        self.shadowLayer.elevation = points
    }
```
Unsure if this is an issue with my implementation or the material component. Please advise.

Initial appearance with opaquebackground:
![screen shot 2017-05-25 at 9 27 04 am](https://cloud.githubusercontent.com/assets/7425648/26429822/a0654e14-412c-11e7-9006-19cb1fcd2a07.png)

After scrolling or updating collectionView:
![screen shot 2017-05-25 at 9 27 26 am](https://cloud.githubusercontent.com/assets/7425648/26429821/a0397faa-412c-11e7-818c-d28d56388b50.png)

Appearance without opaque background (issue not present):
![screen shot 2017-05-25 at 9 28 03 am](https://cloud.githubusercontent.com/assets/7425648/26429820/a034ec92-412c-11e7-8870-ee74a8d0f931.png)

### Version number
23.2.0

**Comment by ianegordon** [comment]
Thank you for reporting the issue, we will investigate.

**Comment by ianegordon** [comment]
We are not intending on any significant updates to the current Collections component. 😞
We are working on a much simpler [List component](https://github.com/material-components/material-components-ios/tree/develop/components/List). 😄
