### ISSUE TITLE
[AppBar] Navigation controller behavior (stack)

### ISSUE THREAD

**Issue by CHENkai8385** [material-components/material-components-ios#1456]
can i used appbar like a navigationcontroller to push or pop?or are there any methods to make the appbar can used like the navigationcontroller overall?

**Comment by ShepJGoogle** [comment]
Hi @CHENkai8385, Material App Bar itself does not have the push and pop features of a navigation controller though it is meant to work in tandem with the navigation controller itself. You can find information on that topic [here](https://github.com/material-components/material-components-ios/tree/develop/components/AppBar#app-bar--uinavigationcontroller).
