### ISSUE TITLE
SnackBar Missing After Pod Install

### ISSUE THREAD

**Issue by talkaboutdesign** [material-components/material-components-ios#1459]
import MaterialComponents.MaterialSnackBar results in error. "No such Module"

---
#### Internal data
- Associated internal bug: [b/131896477](http://b/131896477)

**Comment by aryan-ghassemi-ck** [comment]
same issue, did you resolve?
It's there because setting in IB applies the styling, but can't reference it in code

**Comment by Drakot** [comment]
Same issue.

**Comment by romoore** [comment]
@Drakot What version of CocoaPods are you using? Could you also post the relevant portions of your Podfile so we can try to reproduce?

**Comment by Drakot** [comment]
I solved it cleaning Pod cache like this:

`rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
rm -rf ~/Library/Developer/Xcode/DerivedData/*
pod deintegrate
pod setup
pod install`

**Comment by codeman7** [comment]
@talkaboutdesign did @Drakot suggestion work for you as well?

**Comment by romoore** [comment]
Closing this due to a lack of activity. Please feel free to reopen it with reproduction steps if you still cannot use Snackbar.
