### ISSUE TITLE
[Dialogs] Add loadViewIfNeeded to MDCTransitionController

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1461]
In MDCDialogTransitionController we check if fromView and toView are nil.  If they are we force a load by invoking the .view property on the view controller.

Should we call [viewController loadViewIfNeeded] instead?

---
#### Internal data
- Associated internal bug: [b/117179254](http://b/117179254)

**Comment by material-mirror** [comment]
The internal issue [b/117179254](http://b/117179254) is now closed. This issue is being closed as a result.
