### ISSUE TITLE
[Codelabs] Convert Building Beautiful Apps to Swift

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#1462]
### Overview
The codelab only has ObjC source right now. We should have both.

**Comment by willlarche** [comment]
Finished ObjC found [here](https://codelabs.developers.google.com/codelabs/mdc-ios/index.html?index=..%2F..%2Findex#0)

**Comment by willlarche** [comment]
If done by outside contributor, a member of the core team will have to update the Codelabs system to include a Swift version.

**Comment by ianegordon** [comment]
Thanks Will & Joel!
