### ISSUE TITLE
[RTL] Allow flipping regardless of passed direction

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#1474]
### Overview
Right now the functions require passing in the direction and then if that is LTR, it does nothing.

CGRect MDCRectFlippedForRTL(CGRect leftToRightRect,
                            CGFloat boundingWidth,
                            UIUserInterfaceLayoutDirection layoutDirection);

There should be a function that just flips no matter what.

**Comment by ianegordon** [comment]
Blocked on #1475

**Comment by sigito** [comment]
As I mentioned in #1475, in `MDFInternationalization` there is a `MDFRectFlippedHorizontally` function, which does exactly what is necessary.

**Comment by sigito** [comment]
#1475 has been fixed, `MDFRectFlippedHorizontally` is the only option now.

**Comment by ianegordon** [comment]
Fixed in MDFInternationalization.
Closing as obsolete.
