### ISSUE TITLE
Migrate to MDFInternationalization

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1475]
Migrate from our private/MDCInternationalization methods to MDFInternationalization.

The API is nearly identical.

We can use MDFTextAccessibility as an example of how to import an external dependency.

**Comment by sigito** [comment]
Hi, @ianegordon. Indeed the APIs are almost the same. However there are some minor internal implementation differences in `UIImage+MaterialRTL` between:
1) `MDCRTLFlippedImage` vs `MDFRTLFlippedImage`;
2) `mdc_imageFlippedForRightToLeftLayoutDirection` vs `mdf_imageWithHorizontallyFlippedOrientation`.

Do you think this needs extra attention?

Also `MDCRectFlippedForRTL` function receives a layout direction, while `MDFRectFlippedHorizontally` does not. An additional check in the code would be necessary before calling.

I can replace the usage of `MaterialRTL.h`. Do you think it should be done per component or is it fine to do it all together? Also are there tests for RTL in place already or should I rely on visual testing (check manually)?

Total mapping:

| MaterialRTL  | MDFInternationalization |
| --- | --- | 
| **MDCRTL.h** | **MDFRTL.h** |
| `MDCAutoresizingFlexibleLeadingMargin` | `MDFLeadingMarginAutoresizingMaskForLayoutDirection` |
| `MDCAutoresizingFlexibleTrailingMargin` | `MDFTrailingMarginAutoresizingMaskForLayoutDirection` |
| `MDCRectFlippedForRTL` | `mdc_effectiveUserInterfaceLayoutDirection` + `MDFRectFlippedHorizontally` |
| `MDCInsetsMakeWithLayoutDirection` | `MDFInsetsMakeWithLayoutDirection` |
| | `MDFInsetsFlippedHorizontally` |
| **UIImage+MaterialRTL.h** | **UIImage+MaterialRTL.h** |
| `mdc_imageFlippedForRightToLeftLayoutDirection` | `mdf_imageWithHorizontallyFlippedOrientation` |
| **UIView+MaterialRTL.h** | **UIView+MaterialRTL.h** |
| `mdc_semanticContentAttribute` | `mdf_semanticContentAttribute` |
| `mdc_effectiveUserInterfaceLayoutDirection` | `mdf_effectiveUserInterfaceLayoutDirection` |
| `mdc_userInterfaceLayoutDirectionForSemanticContentAttribute` | `mdf_userInterfaceLayoutDirectionForSemanticContentAttribute` |
| `mdc_userInterfaceLayoutDirectionForSemanticContentAttribute` | `mdf_userInterfaceLayoutDirectionForSemanticContentAttribute` |

**Comment by ianegordon** [comment]
Hi @sigito, thanks for taking a look.

The changes in implementation between private/MDCRTL and MDFI18n should have no significant effect.  I *think* they were mostly to eliminate edge case warnings from the static analyzer.

MDFRectFlippedHorizontally intentionally dropped the layout direction parameter.  This was to allow you to move the LTR/RTL switch back out into the layoutSubviews code.

I would recommend doing any changes on a per-component basis as each component will require dependency updates to the internal BUILD files.

Visual testing will likely be the best way forward, as we don't have any runtime / testtime switches to set LTR/RTL and the associated screenshots to verify against.

A bigger concern might be the tighter warning requirements brought about with Xcode 9.  MDFI18n went from being warning-free to having 23 warnings around availability.  I've been hesitant to migrate more components until those warnings have been handled / silenced.
If you are interested:
https://github.com/material-foundation/material-internationalization-ios/issues/19

Although, if you start sending MDC-iOS migration PRs, I might be able to bump up the priority on sorting the MDFI18n warnings. :smile:

**Comment by sigito** [comment]
@ianegordon, I have updated all the existing PRs to include Podspec changes. Also the new PRs finish code migration to MDFi18n. After all these RPs land, I will send a final one to remove `private/RTL` entirely from the codebase.
