### ISSUE TITLE
[Snackbar] Can the  action buttons click space be increased, and/or disable touch snackbar to dismiss.

### ISSUE THREAD

**Issue by babramovitch** [material-components/material-components-ios#1483]
I'm running into an issue where a touch anywhere on the snackbar that's not the action is dismissing the snackbar.

It's problematic, because the action buttons touch area is very small, so unless you tap the button exactly, and not slightly beside it, the action does not trigger and the snackbar goes away.

http://imgur.com/a/xqNpc

If you look at the image, only the narrow sliver around the OK button triggers the action.  If you click anywhere outside it (which I'm personally doing a lot even in my personal testing) it simply dismisses the snackbar.

Ideally, the entire right side of the button would be part of the button, and more space to the left.

**Comment by babramovitch** [comment]
Okay, so I just realized, I can pad the OK text with spaces to add more space on the left, but it looks like that right padding is set.  I do think that right area should be included in the touch zone.

**Comment by ajsecord** [comment]
Hi, thanks for the report! What you're suggesting is a bit tricky because the user can swipe on the snackbar to dismiss it.

More importantly, for your use case, I think a dialog would fit much better. Snackbars are really for transient confirmations like "Logged on as foo@bar.com" or "Email sent", and not main flows in your app

These bits from the [Material guidelines](https://material.io/guidelines/components/snackbars-toasts.html#) seem to be appropriate:

> For usability reasons, snackbars should not contain the only way to access a core use case.

> If the action described in the snackbar is important enough to block the use of the screen, it should be a dialog.

**Comment by babramovitch** [comment]
Oh well =(  For this use case, alarms actually are secondary in nature to favoriting something.  People will have way more favorites than alarms, so I do think it's a good use, otherwise I'd be blocking the UI every single time they tapped a heart.

**Comment by ajsecord** [comment]
Hm. What about adding a little clock icon or alarm icon next to the heart icon so users can just tap that?

**Comment by babramovitch** [comment]
The UI is already constrained on smaller phones.  When you tap the OK button below, the heart fills in with a small alarm clock to indicate an alarm is set.

**Comment by babramovitch** [comment]
If you're curious what that looks like - https://imgur.com/a/CtVp0

**Comment by ajsecord** [comment]
Or perhaps force touch to pop up the extra menu and set an alarm from there? That might be nice.

**Comment by babramovitch** [comment]
That could work, could also do a long press, but in both scenarios it's a hidden thing then.  I'd at least need to have a mention of it once, such as the first time you favorite an item.
