### ISSUE TITLE
[PageControl] When used from IB/Storyboard radius is not configurable

### ISSUE THREAD

**Issue by rustyshelf** [material-components/material-components-ios#1487]
### Overview
The PageControl is quite nifty, but on iOS when used from an Interface Builder file, you can't set the radius. The only place that allows it is the constructor. Would be great if you could also do it in code, after it's created by IB, for example:
```
@IBOutlet weak var pageControl: MDCPageControl! {
    didSet {
        pageControl.numberOfPages = 3
        pageControl.radius = 12
    }
}
```

### Reproduction steps
- Add MDCPageControl via IB
- Be sad that you can't change the size of the dots

### Version number
 - 23.4.1

### Operating system and device
- iOS, all devices

**Comment by rustyshelf** [comment]
Actually, I mis-read the code slightly, the radius is hard coded into: `kPageControlIndicatorRadius` so I guess my actual issue is I'd love to be able to set it (we like our dots smaller, because we're weird like that)

**Comment by ianegordon** [comment]
Hi Rusty, thanks for the feature request.

We need to determine whether this would be better as an appearance proxy (set once for the entire app) or IBInspectable (explicitly set for each instance) value.

We need to ensure that Objective-c clients can also take advantage without requiring didSet.

I've opened up a tracking issue at #1494.

**Comment by rustyshelf** [comment]
@ianegordon makes sense, happy either way. Also the didSet was just as an example, there shouldn't be any reason an Objective-C client can't call it in something like viewDidLoad. Would be great if it was coded in a way where if you change the radius the control redraws itself.
