### ISSUE TITLE
[TextFields] require layout constraints to become visible.

### ISSUE THREAD

**Issue by randallli** [material-components/material-components-ios#1488]
### Overview
Following the readme instructions does not result in a visible textField. I believe it is the layout constraints that prevent the textField from being visible.
I created a textField and placed it in a non-scolling UIView. When I used [Debugging View Hierarchies](https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/debugging_with_xcode/chapters/special_debugging_workflows.html) it tells me that the position is ambiguous. Even if I set the frame of the textInput.

**Comment by willlarche** [comment]
The example code is out of date. I'll submit an PR to correct it.

**Comment by willlarche** [comment]
Fixed in #1525
