### ISSUE TITLE
Button + Appearance causing test failures

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1492]
In order to unblock a release we rolled back some of the UIAppearance changes in MDCButton.

We should not be required to explicitly set UIAppearance properties in our init methods.  Doing so is incompatible with the UIAppearance proxy.

Identify what is happening to cause client's tests to fail.

**Comment by randallli** [comment]
Turns out setBackgroundColor:forState was not yet labeled with UI_APPEARANCE_SELECTOR

pr that reverted the original change: https://github.com/material-components/material-components-ios/pull/1490

**Comment by ianegordon** [comment]
Closing as obsolete.  😞 
Please open a new bug if this is still an issue.  😄
