### ISSUE TITLE
[PageController] Make indicator size configurable

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1494]
MDCPageControl sizes the indicator based on kPageControlIndicatorRadius.  Consider making this configurable by clients as well as supporting different sizes for sizeCategories and interfaceIdioms.

If exposed, radius should be configurable via the appearance proxy or Interface Builder.

@rustyshelf #1487 for use case / repro steps.

---
#### Internal data
- Associated internal bug: [b/117179211](http://b/117179211)

**Comment by material-mirror** [comment]
The internal issue [b/117179211](http://b/117179211) is now closed. This issue is being closed as a result.
