### ISSUE TITLE
 pod 'MaterialComponents/TextFields' not working

### ISSUE THREAD

**Issue by nitishrana28** [material-components/material-components-ios#1506]
This is my podfile :

```
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'LoginUserControl' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoginUserControl

pod 'MaterialComponents/TextFields'
end
```

But getting following error :

```
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `MaterialComponents/TextFields` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `MaterialComponents/TextFields`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```  
  
**Also, why is there separate pod for TextFields when pod 'MaterialComponents' installs most of the components.**

**Comment by ajsecord** [comment]
Thanks for the report—we need to publish to Cocoapods to pick this up, that was somehow missed in last week's release. I'll do so now.

You can use `MaterialComponents/TextFields` to get just the text fields, or `MaterialComponents` to get everything.

**Comment by nitishrana28** [comment]
Thanks. Is that fixed now ? As I can't see any commit on this.
So now after your release, will MaterialComponents install everything including TextFields ? As previous to that, it didn't.

**Comment by nitishrana28** [comment]
That is still not working.

**Comment by ianegordon** [comment]
This should be fixed in 24.0.2 #1512 
@nitishrana28 can you verify that things are working as expected?

**Comment by ajsecord** [comment]
I just verified locally that the example @nitishrana28 posted now works. Thanks for the report!

**Comment by nitishrana28** [comment]
Again, that is not working. 
Podfile :

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test

pod ‘MaterialComponents’

end
```

*********************

Screenshots which suggest TextField is not there in the components :

![screen shot 2017-06-14 at 12 00 26 pm](https://user-images.githubusercontent.com/1484780/27118547-5d390f22-50f9-11e7-989c-31eb3e208fe6.png)


![screen shot 2017-06-14 at 11 58 32 am](https://user-images.githubusercontent.com/1484780/27118528-4ca2775c-50f9-11e7-8550-fcbf29c3a97d.png)

Anything else I need to do ?

**Please reopen the issue, and that should be closed ONLY once it is confirmed.**

**Comment by nitishrana28** [comment]
Seems to work. Thanks for the fix.

**Comment by anuraagdjain** [comment]
Cannot find MDCTextfield in `24.0.2`. 
My podfile
```
pod 'MaterialComponents' ,'~> 24.0.2'
```
