### ISSUE TITLE
[ActivityIndicator] Asserts instead of using default values

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1508]
MDCActivityIndicator.m (revision 9)
------------------------------------
Line 387 (MDCActivityIndicator.setCycleColors:(NSArray<UIColor *> *)cycleColors):
  NSAssert(cycleColors.count > 0, @"Cycle colors array cannot be empty.");

The header comment for this property says "An empty array results in a blue spinner with no color cycling." which this assert contradicts. Should it be removed?

If you send an empty array we should revert to the default values.

**Comment by romoore** [comment]
Closed by #1540
