### ISSUE TITLE
[FlexibleHeader] StatusBar Artifact

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1518]
In certain cases the FlexibleHeaderView will mirror the StatusBar when scrolling causing a strange rendering artifact.

Repro:
Open Catalog on the iPhone 5 8.3 Simulator
Choose Flexible Header
Choose Configurator
Enable the "Enable with status bar" option
Scroll the content view up

Notice the rendering of the status bar as you scroll up.

**Comment by jverkoey** [comment]
This was a bug caused by view controller status bar management not being enabled in the app. It has been resolved.
