### ISSUE TITLE
[Collections] MDCCollectionViewTextCell contentWrapper has 1 pixel line shown.

### ISSUE THREAD

**Issue by deoryp** [material-components/material-components-ios#1519]
### Overview

There is a 1 pixel line leaking through from the internal view for contentWrapper that is not customizable.

<img width="200" alt="screen shot 2017-06-14 at 3 40 56 pm" src="https://user-images.githubusercontent.com/1637797/27157727-f8b9a362-5117-11e7-9a44-a9301817c788.png">

<img width="208" alt="screen shot 2017-06-14 at 3 39 56 pm" src="https://user-images.githubusercontent.com/1637797/27157714-ec18a1f8-5117-11e7-84a0-f83c9794d9d0.png">

### Reproduction steps

- Set a background color on the contentView in the cell.
- Set the background color on the collection view
- Note the white line in the collection view on top of the cell view.

### Version number

 - 23.4.1

### Operating system and device

ios

**Comment by ianegordon** [comment]
We are not intending on any significant updates to the current Collections component. 😞
We are working on a much simpler [List component](https://github.com/material-components/material-components-ios/tree/develop/components/List). 😄
