### ISSUE TITLE
[Collections] Support automatic integration with UISwitch as an accessoryView

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1526]
From an internal user:
Regarding using MDCCollectionView to build a settings interface:
Some of the rows on this screen have switches as accessory views. I would like for Voice Over to recognize the row as one "accessibility element", reading out the cell's text label and switch state together and allowing the user to double tap to toggle the switch. Instead, the text label and the switch within any cell are currently traversed and read as two separate elements. I am also able to reproduce this in the tutorial app posted to the material-components-ios github repo. Do you have any suggestions as to how to achieve the desired behavior? I would like to avoid rolling our own string formatting and "ON"/"OFF" labels if possible so that we don't create a11y behavior inconsistent with other apps.

**Comment by Arcank** [comment]
Chrome has an implementation of this for accessibility:
https://cs.chromium.org/search/?q=accessibility+file:ios/chrome/browser/ui/collection_view/cells/collection_view_switch_item.mm&type=cs

We roll our own ON/OFF and HINT, but I guess they could be retrieved from an invisible UISwitch, if really needed?

Note that we use accessibilityLabel (the text on the cell), accessibilityValue (ON/OFF), accessibilityHint, and accessibilityActivationPoint to automatically toggle the switch when the entire cell is tapped (double-tap with one finger in VoiceOver).

Note that you need the cell to be the accessibleElement. MDC does a great job only reporting the card as the accessibility frame, so it even looks pretty nice when browsing the UI with accessibility tools (switch control, VoiceOver).

**Comment by ajsecord** [comment]
@kmh287 FYI

I might be way off here, but this looks like it might be [automatic in some contexts](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/UIKitUICatalog/UISwitch.html), if the switch is set to the be [accessory view of the cell](https://stackoverflow.com/questions/24498614/combine-uiswitch-and-uitableviewcell-for-voiceover-interaction). Would that work?

**Comment by kmh287** [comment]
I think that automatic behavior would be ideal and would ensure consistency across apps. Unfortunately, setting a UISwitch as the accessory view for a MDCCollectionViewTextCell does not give that behavior.

**Comment by romoore** [comment]
This looks like a feature request for specific functionality related only to UISwitch integration. Removed the `bug` label.

**Comment by romoore** [comment]
Shouldn't this be fixed for the entire cell UI and not only for UIAccessibility? If I'm tapping on a cell with a UISwitch as its accessoryView, I would hope that the Switch would toggle. If that's not the case, then I don't think it should be different for VoiceOver users.

**Comment by ianegordon** [comment]
We are not intending on any significant updates to the current Collections component. 😞
We are working on a much simpler [List component](https://github.com/material-components/material-components-ios/tree/develop/components/List). 😄
