### ISSUE TITLE
Can we remove the .yaml preamble from our .md files?

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#153]
They show up as rather peculiar tables on GitHub:

![screen shot 2016-03-10 at 2 27 12 am](https://cloud.githubusercontent.com/assets/45670/13662331/a38efb24-e667-11e5-882d-b05f421076a9.png)

**Comment by ianegordon** [comment]
This bug hasn't been updated in over two years!

Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄

**Comment by jverkoey** [comment]
The answer was "yes" in the end :)
