### ISSUE TITLE
ActivityIndicator does not implement NSCoding

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#1530]
### Overview
MDCActivityIndicator does not restore cycleColors values after archiving/unarchiving.  This is due to missing implementation in `-initWithCoder:` and an absent `-encodeWithCoder:`

### Reproduction steps
```objectivec
MDCActivityIndicator *activityIndicator = [[MDCActivityIndicator alloc] initWithFrame:CGRectMake(0,0,1,1)];
  NSArray *cycleColors = @[UIColor.blackColor, UIColor.redColor];
  activityIndicator.cycleColors = cycleColors;
  NSData *data = [NSKeyedArchiver archivedDataWithRootObject:activityIndicator];
  activityIndicator = [NSKeyedUnarchiver unarchiveObjectWithData:data];
  NSAssert([activityIndicator.cycleColors isEqualToArray:cycleColors], @"The unarchived ActivityIndicator has the wrong cycleColors.");
```

### Version number
25.0.0

### Operating system and device
iPhone 7 Plus (Simulator) running iOS 10.3 (Simulator) 14E269

### Related issues
N/A

**Comment by jverkoey** [comment]
We will no longer be supporting NSCoding on our UI components unless explicitly required.
