### ISSUE TITLE
Implement Material Date Picker

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1536]
https://material.io/guidelines/components/pickers.html#

---
#### Internal data
- Associated internal bug: [b/117179310](http://b/117179310)

**Comment by romoore** [comment]
Does Material Design support all calendar types (e.g., Gregorian, Julian, Chinese Lunar, Hebrew, etc.)?

**Comment by codeman7** [comment]
Hey guys, I mentioned in Discord that I have previously implemented a Date Picker in Swift. Will Larche said to share this link here. 

https://github.com/codeman7/htlaehOld/blob/master/Htlaeh/DatePicker.swift

It's not the most elegant implementation but it may be a starting point. I would love to help implement this component in Objective-C.

**Comment by willlarche** [comment]
Thanks @codeman7 ! Great work.

If you wanted to submit a date picker for MDC, we'd start with an API review / design process which might end up changing your work so much you have to start from scratch. :(

Here's some of the features we need in date picker that are not obvious from the guidelines:

- Accessibility
- RTL
- Internationalization / more than just Gregorian calendar support
- Scrolling wheels

You can find more by looking at the [checklist](https://github.com/material-components/material-components-ios/blob/develop/contributing/checklist.md) which now also links to a spreadsheet!

It would be great to have! And yes, we would require ObjectiveC right now.

**Comment by material-mirror** [comment]
The internal issue [b/117179310](http://b/117179310) is now closed. This issue is being closed as a result.

**Comment by Cliabhach** [comment]
May I ask why the linked issue was closed?

**Comment by romoore** [comment]
The request was more than 2 years old and we haven't made any progress on it. Feel free to reopen the issue if you think we should work on it soon. Otherwise, it's likely that a new issue will be created once Date Pickers are planned for development.

**Comment by Cliabhach** [comment]
That makes sense. I think I'll leave it closed, then.

**Comment by J-Swift** [comment]
I'm a vote for 'leave open', this is one of the more glaring differences in the two platforms (ios/android). Especially since the UI/UX is so opinionated/iconic for the material version and the iOS default pickers are so bad.

**Comment by romoore** [comment]
Thanks everyone for your feedback. I'll reopen this and raise it to my team to consider reprioritizing.

**Comment by J-Swift** [comment]
Awesome @romoore! I really appreciate the time/effort you all put into maintaining these libraries. It greatly simplifies adhering to Material specs.

**Comment by jverkoey** [comment]
We recommend using UIDatePicker now instead of Material's on Apple platforms due to its cross-platform support.

**Comment by J-Swift** [comment]
Well thats disappointing. The material UX is such a step up from the apple versions.

**Comment by jverkoey** [comment]
UIKit's come quite a way :)

| Material | UIKit |
|:---------|:------|
| ![unnamed](https://user-images.githubusercontent.com/45670/129407287-f40b9c00-43ec-41f3-b33f-4d7aea043bec.png) | <img width="369" alt="date_picker_ios14_calendar" src="https://user-images.githubusercontent.com/45670/129407187-825b5059-cad9-4fec-9f76-e4e31295b6f5.png"> |
