### ISSUE TITLE
AlertController buttons are no longer visible after changing preferred font size.

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1548]
iPhone SE Simulator - 10.0

Catalog -> Dialogs -> AlertController -> Dynamic Alert
Alert buttons appear as expected.
Change your preferred font size to the largest setting (Settings -> General -> Accessibility -> Larger Text)
Select Dynamic Alert again
Alert buttons *may* be invisible due to the title font color being set to white on a white background.

![screen shot 2017-06-21 at 16 54 25](https://user-images.githubusercontent.com/1121006/27406242-4f68cafa-56a2-11e7-8963-807b8a59ffbb.png)

**Comment by romoore** [comment]
Could not reproduce on version 31.0.0 of the catalog on iPhone SE simulator running iOS 10.3

**Comment by ianegordon** [comment]
Fixed with a MDCButton rollback.

**Comment by ianegordon** [comment]
I was referring to another issue.  This issue may still exist.

**Comment by romoore** [comment]
Could not reproduce in 55.1.0 on iPhone 5c/iOS 11.2.6.

@ianegordon Could you attempt to reproduce in the latest catalog/dragons?

**Comment by jverkoey** [comment]
Please re-open if this is reproducible.
