### ISSUE TITLE
MDCCollectionViewController should not cause ink to ripple when user holds finger to scroll

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#1558]
### Overview
The Ink "ripple" ending animation fires if a user presses and drags a cell in an MDCCollectionViewController collection view and that gives the impression that the cell was selected.  However, `-collectionView:didSelectItemAtIndexPath:` does not fire (which is correct). 

It would make more sense for the Ink to "deactivate" in a visual manner that is distinct from the activate/ripple effect.

### Reproduction steps
1. Touch and hold on a cell in an MDCCollectionViewController.
1. While continuing to hold the cell, drag the cell up or down

#### Expected Behavior
Cell should dissipate Ink with an animation that does not look like activation.

#### Actual Behavior
Cell Ink dissipates and appears as if the user has activated the cell.

### Version number
25.0.1

### Operating system and device
iOS 10.3 (Simulator) on iPhone 5s (Simulator)

**Comment by ianegordon** [comment]
We are not intending on any significant updates to the current Collections component. 😞
We are working on a much simpler [List component](https://github.com/material-components/material-components-ios/tree/develop/components/List). 😄
