### ISSUE TITLE
[CI] Travis CI is failing because our logs are greater than 4MB

### ISSUE THREAD

**Issue by ajsecord** [material-components/material-components-ios#1568]
We changed our build scripts to output everything, but now our builds are failing (incorrectly) because the log output exceeds 4MB.

**Comment by ajsecord** [comment]
I'm seeing if xcpretty will help...

**Comment by willlarche** [comment]
The logs that we don't have access to.

**Comment by romoore** [comment]
I haven't seen our builds fail for this reason in several weeks, can this be closed?

**Comment by willlarche** [comment]
Yes. I fixed it with several changes.
