### ISSUE TITLE
MDCCollectionViewCellAccessoryDisclosureIndicator isn't set to UIImageRenderingModeAlwaysTemplate

### ISSUE THREAD

**Issue by jessupjn** [material-components/material-components-ios#1575]
MDCCollectionViewCellAccessoryDisclosureIndicator needs to be set to UIImageRenderingModeAlwaysTemplate

**Comment by jessupjn** [comment]
I have a patch ready that will be sent out soon in http://cl/160154483

**Comment by ianegordon** [comment]
Hi @jessupjn, thanks for filing the issue. Is the intention for the fix to open a PR here or export from internal?

**Comment by romoore** [comment]
Do we still want to change this image to template mode?

**Comment by jessupjn** [comment]
I would assume the answer is yes - it seems to me that the color of the chevron should be updated the same as the other accessory types.
