### ISSUE TITLE
Components vs Convenience

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#158]
By designing our components to have zero common dependencies (i.e. no core) we're now free to come up with novel ways to group components together both in our meta-APIs and in our documentation. As we add more components we will find it increasingly valuable to provide such "convenience" APIs that bind components together.

For example, the upcoming `AppBar` APIs will be a _convenience_ for the following _components_:
- ButtonBar
- NavigationBar
- FlexibleHeader
- HeaderStackView
- ShadowLayer
- ShadowElevations

I'd like to initiate this discussion with a question: **how do we put focus on convenience APIs?**

If we treat all of our components as equal, at best we'll have a sorted list of components on our website and in the `components/` directory. Someone coming to our repo will not know where to start.

Possible approaches to solving this organizational problem:
- **Provide a cookbook**. This cookbook would list a variety of common scenarios and provide concrete recommendations for joining components together.
- **Elevate some components above the others**. This can be done on our website, but won't reasonably map back to our source without creating a new directory structure. This is somewhat against the effort to keep the site and source organizational structure in-line with one another.
- **Provide examples**. In the README.md for a given component we should identify a variety of scenarios in which the component could be used. These examples could be extracted into the cookbook at site generation time.

**Comment by ianegordon** [comment]
This bug hasn't been updated in over two years!

Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄
