### ISSUE TITLE
Ensure that we are using umbrella headers between components.

### ISSUE THREAD

**Issue by randallli** [material-components/material-components-ios#1592]
Right now we can and do import various public headers of components from within other components. We should always import umbrella headers instead. This could be done via script.

**Comment by sigito** [comment]
Hi, @randallli. When I was working on #2192 I have written a hacky script, which I can adapt for use. It simply scans components dirs for headers and then goes through all the files and checks if the imported file belongs to the component. Would it be right to add it to`scripts/check` and do I need to do any extra work to integrate it?

**Comment by randallli** [comment]
Just follow the [check/readme](https://github.com/material-components/material-components-ios/blob/develop/scripts/check/README.md). 

We need to add this to the [checklist](https://github.com/material-components/material-components-ios/blob/develop/contributing/checklist.md) and add a row to the sheet too.

**Comment by sigito** [comment]
@randallli, please check out #2241.
