### ISSUE TITLE
[MDCNavigationBar] Title is not vertically centered for UIControlContentVerticalAlignmentTop

### ISSUE THREAD

**Issue by thkeen** [material-components/material-components-ios#1596]
It can be seen the the navigation bar title isn't centered vertically because it's always 16px to the top inset. This causes an obvious misalignment to the UI, especially with dynamic type in iOS. The smaller the font size, the more obvious it can be seen.

**Comment by thkeen** [comment]
Pull request: https://github.com/material-components/material-components-ios/pull/1576

**Comment by romoore** [comment]
Resolved by #1576
