### ISSUE TITLE
[Collections] Items (dis)appearing with alpha of 1

### ISSUE THREAD

**Issue by gambard** [material-components/material-components-ios#1600]
### Overview
When an item inside a collection moves (for example repositioned during a screen rotation), both items (the one in the new place, and the one in the old place) have an alpha of 1 for the whole duration of the animation (e.g. rotation).
This leads to a weird display as shown on this screenshot.
#
![simulator screen shot jul 6 2017 3 37 21 pm](https://user-images.githubusercontent.com/1257452/27913648-1caac6c0-6261-11e7-8bdd-7b6240a8ab54.png)

This is done on purpose on https://github.com/material-components/material-components-ios/blob/develop/components/Collections/src/MDCCollectionViewFlowLayout.m#L276 .
The main question is to know if this follows some MDC guidelines or not? I found nothing on material.io

## Reproduction steps
 - Change the position of some items during an animation (rotation)
 - Rotate
To change the position of some items, it should be possible to do it with a empty and transparent header which size change on rotation.

### Version number
 - 24

**Comment by ianegordon** [comment]
We are not intending on any significant updates to the current Collections component. 😞
