### ISSUE TITLE
Why is -imageWithContentsOfFile: used instead of -imageNamed:?

### ISSUE THREAD

**Issue by Arcank** [material-components/material-components-ios#1606]
### Overview
-imageWithContentsOfFile: doesn't use the image cache. Why is it preferred to -imageNamed:(inBundle:)?
The issue is that assets can then not be compiled as xcassets, thus not participating in App Thinning.

**Comment by willlarche** [comment]
We could do this in the examples that have their weird image bundles too,
couldn't we?

**Comment by ianegordon** [comment]
Agreed that we should prefer imageNamed: over imageWithContentsOfFile:.

**Comment by seanoshea** [comment]
I'm always reminded of https://www.alexcurylo.com/2009/01/13/imagenamed-is-evil/comment-page-1/ when `imageNamed:` is brought up. Obviously not an issue anymore (I think this was an issue waaaaaaaaay back in the pre-arc days). Still, an interesting note nonetheless.

**Comment by ianegordon** [comment]
Our use of imageWithContents: may be an artifact of our support for iOS 7.  As we have custom bundles for our components we need imageNamed:inBundle: which wasn't added until iOS 8.

**Comment by ajsecord** [comment]
I think it was a pre-iOS-8 thing. Bundle handling in the past was very confused.

**Comment by romoore** [comment]
MDCIcons categories now have  `- (UIImage *)imageFor_icon_name` methods that use `[UIImage imageNamed:inBundle:compatibleWithTraitCollection:]` to return the UIImage directly.

**Comment by Arcank** [comment]
@sdefresne : we should now use the API @romoore mentions.
