### ISSUE TITLE
[TextFields] Demo alert title doesn't change based on floating enabled/disabled.

### ISSUE THREAD

**Issue by DonnaLea** [material-components/material-components-ios#1611]
### Overview
Using the catalog app viewing the Demo of TextFields, switching the style to use floating or not doesn't change the title of the alert which always says Floating Enabled (regardless or floating being enabled or not).

### Reproduction steps
Launch catalog and navigate to TextFields > Demo > STYLE. Notice in the alert title is Floating Enabled. Select No. Select STYLE to show alert again, the title still says Floating Enabled.

### Version number
 - 26.0.0

### Operating system and device
- iPhone 7 Plus - iOS 10.3 Simulator.

**Comment by willlarche** [comment]
See comments in PR #1612.
