### ISSUE TITLE
[Header] Extra insets injected into tracking scroll views (iOS 11 beta)

### ISSUE THREAD

**Issue by brianjmoore** [material-components/material-components-ios#1626]
### Overview
When built against the iOS 11 beta SDK and run on iOS 11, all tracked scroll views of MDCFlexibleHeaderViews appear to have extra insets that are not present on iOS 10.

This is visible in a few ways:
* The top of scroll indicators is visibly ~20pt below the bottom of the header.
![image](https://user-images.githubusercontent.com/395995/28092367-18e455b6-6661-11e7-927d-29e4cda60d5c.png)

* If you stretch a flexible header larger than its minimum height 
![image](https://user-images.githubusercontent.com/395995/28092508-a6898a9e-6661-11e7-923d-44c7a86d424c.png) 
and let go, it settles on a height larger than its minimum height. 
![image](https://user-images.githubusercontent.com/395995/28092516-abf4a8ce-6661-11e7-873a-2c6881baa228.png)

* In custom layouts where elements are placed based on the content insets, there is ~20pt of extra space at the top of scroll views.

### Reproduction steps
1. Build MDCCatalog on iOS 11 beta 3 SDK and run on iOS 11 beta 3 device/sim.
2. On home page, scroll and observe scroll indicator.
3. Tap into "flexible header" tile.
4. Pull down to stretch header and let go. Observe that it settles at a size that is ~20pt larger than its minimum size.

### Version number
26.0.0

### Operating system and device
Xcode: Version 9.0 beta 3 (9M174d)
iPhone 7 simulator on iOS 11.0 beta 3 (15A5318e)
iPhone 7 plus on iOS 11.0 beta 3 (15A5318g)

**Comment by ShepJGoogle** [comment]
So after so investigation, it seems as though iOS 11 (as of the betas) forcefully injects the height of the status bar into  any scrollview's contentInset.top and contentOffset.top when the status bar is visible though does not include said injection in the values for those properties (i.e. - calling [scrollView.contentInset].top will return 0 but there is actually an inset of 20) to prevent the status bar obscuring the content view.

![screen shot 2017-07-25 at 4 02 33 pm](https://user-images.githubusercontent.com/19916772/28592116-06154dbe-7156-11e7-8846-f88619f43758.png)
MDCCatalog (iOS 10.1 vs iOS 11.0)

![screen shot 2017-07-25 at 4 02 07 pm](https://user-images.githubusercontent.com/19916772/28592201-39d73e14-7156-11e7-87af-3f2fdf613b13.png)
Bare bones tableView Controller (iOS 10.1 vs 11.0)

I'm hesitant to do much modification within the component for this issue as the components won't own the scrollviews they are injected into. Thoughts @brianjmoore ?

**Comment by brianjmoore** [comment]
I wonder if setting UIScrollViewContentInsetAdjustmentBehavior to .never would be appropriate here? Or is there a way for the flexible header to play nicely with safeAreaInsets?

**Comment by CaptainTeemo** [comment]
I'm having the same issue and  setting UIScrollViewContentInsetAdjustmentBehavior to .never works like a charm. Thanks @brianjmoore

**Comment by ShepJGoogle** [comment]
Thanks as well @brianjmoore. I'll check some code in with your suggestion and shoot you a pr if it's all square.

**Comment by brianjmoore** [comment]
Unfortunately it turns out that content inset adjustment is super useful when you have safe area insets on other edges besides the top, so disabling it doesn't seem like a great option long-term. 

Now that we have the full picture behind safe area insets, I think it's worth designing a fix that works with UIKit safe area insets and content inset adjustment as much as possible. Ideally, apps shouldn't need to disable adjustment at all to use MDCFlexibleHeader.

**Comment by chuga** [comment]
This has been fixed (we should've done it sooner though).
