### ISSUE TITLE
[CollectionCells] MDCCollectionViewTextCell does not reset text on labels

### ISSUE THREAD

**Issue by sigito** [material-components/material-components-ios#1631]
`MDCCollectionViewTextCell#prepareForReuse` does not set `text` property on `textLabel` and `detailTextLabel` to `nil`.

### Version number
26.0.0

**Comment by romoore** [comment]
###Example of the issue in the catalog###
Note that the example detail text is reused in the second cell from the top, and in the bottom cell the main/detail text numbers don't match.
![textcell-reuse-original](https://user-images.githubusercontent.com/1753199/28119736-e9cd5164-66e3-11e7-8be4-f80598518b89.png)
