### ISSUE TITLE
[Collections] Support Text Item Cells with customizable number of lines

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1634]
Our text cell currently limits users to 1, 2 or 3 lines of text.  Consider supporting any number.

This could be supported via self-sizing cells.

Original PR #1249 from @alexfacciorusso.

**Comment by cloudface** [comment]
Hello. Is there any news as to when this will be available? We could really use this in our project. Thanks for all the great work, guys! 

Kind regards
Chris

**Comment by ianegordon** [comment]
Done in #4718
