### ISSUE TITLE
AppBar Not Visible in XCode 9 Simulator

### ISSUE THREAD

**Issue by ShepJGoogle** [material-components/material-components-ios#1658]
### Overview
When building an application using XCode 9 simulator, MDCAppBar is not visible in viewcontrollers' views.

### Reproduction steps
 - Detailed steps to reproduce

### Version number
 - 27.0.0

### Operating system and device
All devices and all version

View Using Device:
![unnamed1](https://user-images.githubusercontent.com/19916772/28336665-da616ce6-6bd0-11e7-99b9-792641123ee0.png)

View Using Simulator:
![unnamed2](https://user-images.githubusercontent.com/19916772/28336685-e2e504c2-6bd0-11e7-9c4c-7bd6a9300bcd.png)

**Comment by ajsecord** [comment]
This was an Xcode Beta 2 bug, fixed in Xcode Beta 3.
