### ISSUE TITLE
[Collections] MDCCollectionViewTextCell elements are nullable

### ISSUE THREAD

**Issue by mpetrov** [material-components/material-components-ios#1663]
### Overview
`MDCCollectionViewTextCell`'s `textLabel`, `detailTextLabel`, and `imageView` are nullable. This leads to a lot of optional chaining and nil checking in client code. Would it me reasonable to change these to nonnull?

**Comment by romoore** [comment]
I think the one-size-fits-all approach to the MDCCollectionViewCell might be overly complex (it certainly leads to high CPU use while scrolling).  What do you think of different cell types for different combinations of text/detail text?  We could also consider using the `hidden` properties on some fields to adjust layouts.

**Comment by ianegordon** [comment]
We are not intending on any significant updates to the current Collections component. 😞
We are working on a much simpler [List component](https://github.com/material-components/material-components-ios/tree/develop/components/List). 😄
