### ISSUE TITLE
Deprecation warning in MDCButtonBarColorThemer

### ISSUE THREAD

**Issue by garrettmurray** [material-components/material-components-ios#1674]
### Overview

In MDCButtonBarColorTheme.m, line 30:

```
[MDCButtonBar appearanceWhenContainedIn:[MDCNavigationBar class], nil].backgroundColor
    = nil;
```

This uses `appearanceWhenContainedIn:`, which was deprecated in iOS 9. This will warn on builds.

### Reproduction steps
Build with Material Components in your project.

### Version number
28.0.0

### Operating system and device
iOS 9, iOS 10

**Comment by ianegordon** [comment]
Hi @garrettmurray.

Looks like we missed an appearanceWhenContainedInInstancesOfClasses:.  Thanks for letting us know!
