### ISSUE TITLE
Replace any constants that are actually methods

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#1682]
😢😢😢: https://github.com/romoore/material-components-ios/blob/develop/components/CollectionCells/src/MDCCollectionViewTextCell.m#L32

```objc
 #define kCellDefaultTextOpacity [MDCTypography subheadFontOpacity]
 #define kCellDefaultDetailTextFontOpacity [MDCTypography captionFontOpacity]
```

---
#### Internal data
- Associated internal bug: [b/117179408](http://b/117179408)

**Comment by jverkoey** [comment]
This should just be a find-and-replace of the "constants" with the actual invocations.

**Comment by romoore** [comment]
Also bad:
```objectivec
// Default cell fonts.
#define kCellDefaultTextFont [MDCTypography subheadFont]
#define kCellDefaultDetailTextFont [MDCTypography body1Font]
```

**Comment by ajsecord** [comment]
Yeah, macros are terrible... these should be static inline functions.

**Comment by jverkoey** [comment]
+1 to static inlines over find-and-replace in order to keep semantic remapping in place.

**Comment by romoore** [comment]
The remaining macros used in material components are either for iOS version checking, localized string handling, or material motion. Assigning to @jverkoey to determine if we can rewrite the motion macros as functions or methods.

**Comment by material-mirror** [comment]
The internal issue [b/117179408](http://b/117179408) is now closed. This issue is being closed as a result.
