### ISSUE TITLE
[Snackbar] MDCOverlayObserver reports the wrong frame if an overlay is present during rotation

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1701]
From Snackbar Overlay View in portrait.
Toggle bottom bar
Show Snackbar
Rotate to landscape (button disappears behind snackbar and bottombar)
Rotate back to portrait (button jump to the upper right corner)

![](https://user-images.githubusercontent.com/1121006/28634842-834376fc-7206-11e7-94be-6617c5e18c15.png)

**Comment by romoore** [comment]
Looks like the problem comes from different coordinate systems between the overlay (always portrait) and the example's view (landscape).  When the transition arrives at the delegate, the "height" of the SnackBar view is the width of the screen.

**Comment by romoore** [comment]
Digging deeper, this appears to be a combination of two issues:
* `MDCSnackbarOverlayView` and `MDCOverlayUtilities` both transform coordinates to the screen's coordinate space using the `fixedCoordinateSpace`, which is always in portrait
* The `willRotate:` method in `MDCSnackbarOverlayView` seems to be fired before the screen has rotated, so even if the fixed screen coordinates were replaced with the orientation-based screen coordinates, the overlay observers receive the wrong overlay rectangle.
