### ISSUE TITLE
Decoding needs “containsValueForKey:” when defaults are overridden by 0/nil

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#1715]
### Overview

Implementations of NSCoding’s decoding need to check for saved values before assigning to ivars as this fails gracefully returning 0 or nil which will wipe out default values. 

First calling “containsValueForKey:” is not needed on propertys that have a default of 0 or nil.

**Comment by willlarche** [comment]
This also needs to be captured in the checklist.

**Comment by romoore** [comment]
We should also consider the following as good recommendations:
* Document any nil/0 default values explicitly in the `-initWithCoder:`
* Write unit tests to document the expected behavior and protect against accidental changes

**Comment by jverkoey** [comment]
This is obsolete now that we are not supporting NSCoding on our components.
