### ISSUE TITLE
[NavigationBar] ButtonBarItems labels are not pixel-aligned, resulting in blurry text

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#1723]
### Overview
The UILabel in the MDCBarButtonItem is not pixel-aligned and can easily arrive on a non-pixel point location. This results in anti-aliased (blurry) text. 

**In the image below, "UPD1" and "Grid Example" are pixel-aligned, "UPD2" is not**
![navbar-upd2_blurry](https://user-images.githubusercontent.com/1753199/28836684-f90c50a6-76b7-11e7-89bf-5b9fa0669bae.png)

The issue seems to arrive from our attempts to align the baseline values of the NavigationBar's title label and the labels within any text BarButton items.

### Reproduction steps
Add a text button to a NavigationBar

### Version number
29.0.0

### Operating system and device
iPhone 5 (Simulator) iOS 10.3
iPhone 5S/iOS 10.3.2

**Comment by romoore** [comment]
Sample code to align:

```objectivec
CGRect MDCCGRectIntegral(CGRect rect) {
  CGFloat scale = [[UIScreen mainScreen] scale];
  if (MDCCGFloatEqual(scale, 1)) {
    return CGRectIntegral(rect);
  }
  return CGRectMake(MDCFloor(rect.origin.x * scale) / scale,
                    MDCFloor(rect.origin.y * scale) / scale,
                    MDCCeil(rect.size.width * scale) / scale,
                    MDCCeil(rect.size.height * scale) / scale);
}
```

**Comment by ianegordon** [comment]
Add MDCRectIntegral() to MDCMath?

Naming is hard, but I might argue the CGRectMake() is the function RectMake() with the CG (CoreGraphics) prefix.  So MDCRectIntegral might be acceptable over MDCCGRectIntegral.
