### ISSUE TITLE
[FeatureHighlight] Tap to dismiss is no longer working

### ISSUE THREAD

**Issue by FloresRobles** [material-components/material-components-ios#1735]
### Overview
Tapping outside the circles to dismiss isn't working.

### Reproduction steps
 - Trigger the component in the catalog, and tap outside the circle

### Version number
 - Found in 30.0.0

### Operating system and device
iOS 10 and iOS 11, all iPhones

**Comment by ajsecord** [comment]
Sam, this is closed, right?

**Comment by samnm** [comment]
Yes it is.
