### ISSUE TITLE
[Button] Unexpected Title Color

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1750]
#1725 introduced a change into the rendering of the button.

Originally we calculated a title color based on the background.  Now we are setting an explicit value (black).

This has lead to unexpected rendering results for some of our clients.

Do we want to set sane default colors for all of our components?
Do we want to calculate reasonable title colors based on the background value set?

---
#### Internal data
- Associated internal bug: [b/117179680](http://b/117179680)

**Comment by romoore** [comment]
I would suggest that all of our components should come with default colors that are compatible with one another.  In other words, if I built a UI without setting any specific colors, I should get something that is not impossible to use (but not necessarily beautiful).  That being said, aren't buttons supposed to get their title color from the tintColor?

>You can specify a custom button tint using the tintColor property. This property sets the color of the button image and text. If you do not explicitly set a tint color, the button uses its superview’s tint color.
&mdash; https://developer.apple.com/documentation/uikit/uibutton

**Comment by willlarche** [comment]
Agreed on having colors that are compatible.

AFAIK we stay away from tint color. Should come from titleColor:forState:

**Comment by romoore** [comment]
Given the undecided nature of the work for this Issues, I'm removing the "fixit" label for now.

**Comment by romoore** [comment]
@ianegordon  - Could you clarify what acceptance criteria are expected here? As it stands, this issue is mostly questions but nothing that we can act on.

**Comment by romoore** [comment]
Ping @ianegordon - Please take a look at this issue. It's blocking us from moving Buttons Theming Extensions to general availability (Ready).

**Comment by ianegordon** [comment]
In light of further on-going work on the color system, I'm going to close this as obsolete.
