### ISSUE TITLE
[FeatureHighlight] Allow user to drag and enlarge the circle

### ISSUE THREAD

**Issue by nirga** [material-components/material-components-ios#1753]
### Overview
Allow the user to click and hold the outside circle of the feature highlight, when opened, and drag to enlarge it. Once the user releases the touch, the outside circle should return to its original size.

### Version number
 - Found in 30.0.0

### Operating system and device
iOS 10 and iOS 11, all phones

**Comment by ianegordon** [comment]
Done.
