### ISSUE TITLE
[BottomSheet] BottomSheet is missing a README.md

### ISSUE THREAD

**Issue by ajsecord** [material-components/material-components-ios#1773]

**Comment by codeman7** [comment]
Is it ok if I start working on this?

**Comment by ajsecord** [comment]
Please do!

**Comment by codeman7** [comment]
Ok, I'll try and do that today and submit the PR tonight.

**Comment by ajsecord** [comment]
I invited you to be a read-only collaborator on the repo so I can assign issues to you, but if that's not important to you, feel free to ignore it.

**Comment by codeman7** [comment]
Thanks, @ajsecord  any privileges to work with great developers like the ones that fill this team on a project at a major company is welcomed on my end!

**Comment by ajsecord** [comment]
😄
