### ISSUE TITLE
Define a style guide for documentation screen shots

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#180]
Some things to consider:
- Colors. We likely want a light grey backdrop in order to differentiate from the site's white background.
- Chrome. No status bar or navigation bar chrome.
- Taken from a device.

---
#### Internal data
- Associated internal bug: [b/117179413](http://b/117179413)

**Comment by material-mirror** [comment]
The internal issue [b/117179413](http://b/117179413) is now closed. This issue is being closed as a result.
