### ISSUE TITLE
[Typography] Dynamic Type in MDCTypography

### ISSUE THREAD

**Issue by kolodny** [material-components/material-components-ios#1800]
Currently MDCTypography returns fonts as follows:

```objc
(UIFont *)display4Font {
  return [[self fontLoader] lightFontOfSize:112];
}
```

Hardcoding this value causes the [system accessibility font size](https://support.apple.com/en-us/HT202828) to be ignored.

Instead the function can use `mdc_preferredFontForMaterialTextStyle` which does respect the correct font size:

```objc
(UIFont *)display4Font {
  return [UIFont mdc_preferredFontForMaterialTextStyle:MDCFontTextStyleDisplay4];
}
```

**Comment by ianegordon** [comment]
Hi @kolodny.  You are absolutely correct.  mdc_preferredFont was added after MDCTypography with the intention of adding support for Dynamic Type.  However, we need to support existing interfaces that were not build with Dynamic Type in mind.  To put it another way; we need to support the Material 'default' values as well as the dynamic type-enabled values.

I've add #1807 to add some explicit documentation.

**Comment by romoore** [comment]
Due to [the upcoming deprecation of MDCTypography](https://github.com/material-components/material-components-ios/projects/13), I'm going to close this issue.
