### ISSUE TITLE
How to change the placeholder font in TextFields

### ISSUE THREAD

**Issue by jprossardalia** [material-components/material-components-ios#1825]
### Overview

How to change the placeholder font in TextField.
I'm doing this
_matTextField.placeholderLabel.font = [UIFont fontWithName:@"Lato-Regular" size:(IS_IPAD ? 20 : 14)]; 
but it is not working.

On further examining I found that the font of the textField is changing while the placeholder remains same (<UICTFont: 0x7fc445f8dd90> font-family: ".SFUIText"; font-weight: normal; font-style: normal; font-size: 14.00pt) 

### Version number
31.0.1

### Operating system and device
iPad Pro (9.7inch) ,iOS 10.3

**Comment by willlarche** [comment]
Hey @jprossardalia !

This ticket got lost in the shuffle. Thanks for your patience!

You can change the placeholder's font by setting the `inlinePlaceholderFont` property on all text input controllers. [See header](https://github.com/material-components/material-components-ios/blob/develop/components/TextFields/src/MDCTextInputController.h#L152)

If you wanted to change the placeholder font of every text field, set the `inlinePlaceholderFontDefault` property on the respective class early in the app's lifecycle.
