### ISSUE TITLE
Determine ink color based on tint and background color.

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1837]
If someone has set a primary and background color on a button, do we want to calculate a reasonable inkColor?

This functionality was raised by @eccelor in #1728.

---
#### Internal data
- Associated internal bug: [b/117179464](http://b/117179464)

**Comment by material-mirror** [comment]
The internal issue [b/117179464](http://b/117179464) is now closed. This issue is being closed as a result.
