### ISSUE TITLE
[Catalog] Consider removing theming from applicationDidFinishLaunching

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1840]
Consider not applying our themes in applicationDidFinishLaunching.

Yes, this is the normal procedure for people theming / using UIAppearance proxy.

However, by doing so, we can't easily test our components default state.

I recommend we not apply a theme unless the user has chosen one explicitly under the Themes component.  

As a stretch goal, we may want to consider storing a client's Scheme choice (or the lack thereof) in user defaults and applying on startup.

**Comment by romoore** [comment]
The use case (not theming) can be experienced by loading the Dragons app.
