### ISSUE TITLE
[ActivityIndicator] Accessibility behavior should match UIProgressView

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1841]
The accessibility behavior of MDCActivityIndicator should match UIProgressView.

See @romoore comments in #1765 

Research to determine how UIProgressView behaves and document the desired behavior for MDCActivityIndicator.

---
#### Internal data
- Associated internal bug: [b/117179545](http://b/117179545)

**Comment by jverkoey** [comment]
@romoore / @ianegordon Can you clarify what research needs to be done for this issue?

**Comment by jverkoey** [comment]
I don't believe then that this issue is blocked on any research - this issue is the research.

**Comment by jverkoey** [comment]
All of the "Needs" labels are implicitly "Blocked by: needing this thing".

**Comment by romoore** [comment]
Sadly that wasn't very clear (at least to me).  Can we change them to start with "Blocked:"? Like "Blocked: Needs Research"?  I thought "Needs Research" is a way to distinguish a Spike/Research story from a Feature Request. We also have "Needs Design Review" which I thought was for a story that involves meeting with designers.

**Comment by jverkoey** [comment]
Let's move this conversation to chat.

**Comment by material-mirror** [comment]
The internal issue [b/117179545](http://b/117179545) is now closed. This issue is being closed as a result.
