### ISSUE TITLE
[TextFields] Retrieving fonts for text fields consumes much CPU time

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#1853]
### Overview
Typing into a basic textfield on an iPhone 5S/iOS 10.3.3 resulted in 15% of main thread time being spent creating/retrieving fonts.

<img width="947" alt="profiler-textfield-typing" src="https://user-images.githubusercontent.com/1753199/29483038-f4443270-846b-11e7-8e76-c9d25cdd2374.png">

### Reproduction steps
1. Load the MDC Catalog onto a physical device using the Time Profiler instrument in Xcode
1. Type some text into a textfield
1. Look at the methods taking the most time on the main thread of the app

### Version number
31.0.2

### Operating system and device
iPhone 5s/iOS 10.3.3

---
#### Internal data
- Associated internal bug: [b/117179639](http://b/117179639)

**Comment by willlarche** [comment]
Is this still relevant?

**Comment by jverkoey** [comment]
I think so. Do you still want to look into this @willlarche ?

**Comment by willlarche** [comment]
Not until a client says it’s an issue for them.

**Comment by material-mirror** [comment]
The internal issue [b/117179639](http://b/117179639) is now closed. This issue is being closed as a result.
