### ISSUE TITLE
KeyboardWatcher & OverlayWindow should support iOS slide-over view mode

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1859]
From internal cl/165778873.

For KeyboardWatcher, rather than using:
CGRect screenBounds = [[UIScreen mainScreen] bounds];
Use:
CGRect screenBounds = [UIApplication sharedApplication].keyWindow.bounds;

Will this continue to work as expected on pre-iOS 11 devices?

---
#### Internal data
- Associated internal bug: [b/117179308](http://b/117179308)

**Comment by romoore** [comment]
We may want to look at the OverlayWindow as well while we're in there. It currently uses the main screen rather than the application's window for positioning.

**Comment by material-mirror** [comment]
The internal issue [b/117179308](http://b/117179308) is now closed. This issue is being closed as a result.
