### ISSUE TITLE
Porting to Xamarin

### ISSUE THREAD

**Issue by alaeddineG** [material-components/material-components-ios#1865]
Is there any plan to port this to Xamarin ?

**Comment by willlarche** [comment]
I know I personally don't know what that would entail. Could you point us to more info?

**Comment by alaeddineG** [comment]
the following is an attempt port Google MD to iOS : https://github.com/fpt-software/Material-Controls-For-iOS (https://components.xamarin.com/view/MaterialControls)

I cannot point more that your work is much more complete and maintained then the one I mentioned. 

There is different way to do it : 
https://developer.xamarin.com/guides/ios/advanced_topics/binding_objective-c/walkthrough/
https://developer.xamarin.com/guides/cross-platform/macios/binding/objective-sharpie/
( I tried the Xcode and the Pod method but I run into some trouble ... )

Anyway hope this project will end up as component is Xamarin catalog like other Google product did.

**Comment by alaeddineG** [comment]
There is already a suggestion to port this project to Xamarin but it's since February ... https://xamarin.uservoice.com/forums/145075-xamarin-component-ideas/suggestions/18457699-materialcomponents-for-ios

**Comment by willlarche** [comment]
I've marked it New Collaborator Friendly. Hopefully someone will see this ticket and help out! Tell your peers in the Xamarin community.

**Comment by gedw99** [comment]
THis is an awesome idea.
I have been using xamarin the last few weeks on Visual Studio for MAC, and its very productive. 
The walk through bindings a framework to c# is actually pretty easy.

I also program in golang and can compile to android and ios as a framework.
This means that i can code all logic in golang and then bind to c# / Xamarin.

**Comment by jverkoey** [comment]
It's unlikely that this will be work that we own, but we're definitely curious too see any progress made here if you'd like to continue using this thread to report back!

**Comment by davidallen-bluemetal** [comment]
Xamarin have an official binding to this library:
https://www.nuget.org/packages/Xamarin.iOS.MaterialComponents/  
https://github.com/xamarin/XamarinComponents/tree/master/iOS/MaterialComponents 

hope this helps

**Comment by esskar** [comment]
@davidallen-bluemetal thanks for pointing, but it still lacks controls... :(
