### ISSUE TITLE
[TextFields] Last Baseline alignment does not work in Interface Builder

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#1893]
### Overview
Using InterfaceBuilder to align a UILabel and MDCTextField along "Last Baseline" (where MDCTextField is the last baseline) does not work correctly.

#### Constraints for UILabel
![screen shot 2017-08-24 at 10 12 05 am](https://user-images.githubusercontent.com/1753199/29670477-bedf0a54-88b4-11e7-8791-b16a619954ef.png)

#### Layout on iPhone 5s Simulator
![textfield-baseline](https://user-images.githubusercontent.com/1753199/29670486-c6985868-88b4-11e7-9a32-16b9a4880903.png)

### Reproduction steps
1. Create a UILabel and an MDCTextField
2. Constrain them to equal baselines

### Version number
33.0.0

### Operating system and device
iPhone 5s/iOS 11.0 (Simulator) (Xcode 9.0 beta5)

### Related issues
#1891 - Catalog example using these constraints

---
#### Internal data
- Associated internal bug: [b/117179463](http://b/117179463)

**Comment by material-mirror** [comment]
The internal issue [b/117179463](http://b/117179463) is now closed. This issue is being closed as a result.
