### ISSUE TITLE
[TextFields] Multiline VoiceOver support needs improvement

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#1895]
Individual elements are being enumerated instead of the overall component.

---
#### Internal data
- Associated internal bug: [b/117179586](http://b/117179586)

**Comment by romoore** [comment]
This needs to be re-tested to determine what work is outstanding.

**Comment by material-mirror** [comment]
The internal issue [b/117179586](http://b/117179586) is now closed. This issue is being closed as a result.
