### ISSUE TITLE
Delete ROADMAP.md

### ISSUE THREAD

**Issue by codeman7** [material-components/material-components-ios#1909]
I believe the Roadmap needs an update. All the items that are high priority seem to already be done should we move the next up to high priority?

---
#### Internal data
- Associated internal bug: [b/117179558](http://b/117179558)

**Comment by jverkoey** [comment]
The real roadmap is now here: https://github.com/material-components/material-components/blob/develop/ROADMAP.md

**Comment by material-mirror** [comment]
The internal issue [b/117179558](http://b/117179558) is now closed. This issue is being closed as a result.
