### ISSUE TITLE
[Math] Implement MDCCeilScaled()

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1917]
Throughout Text Fields there are many instances of the following:

CGFloat scale = UIScreen.mainScreen.scale;
CGFloat placeholderEstimatedHeight = 
    MDCCeil(self.textInput.placeholderLabel.font.lineHeight * scale) / scale;

We should consider if we want to pull this into MDCMath.

Name and interface TBD.

**Comment by willlarche** [comment]
@jverkoey @romoore FYI

**Comment by ianegordon** [comment]
Add MDCCeilScaled() and MDCFloorScaled() to MDCMath.
