### ISSUE TITLE
push View Controller

### ISSUE THREAD

**Issue by adelbios** [material-components/material-components-ios#1918]
i have this code ....
` let appBar = MDCAppBar()`

now how i can implement push View Controller 

this code not working ?!
 ` self.appBar.headerViewController.navigationController?.pushViewController(PaymentVC(), animated: true)`

**Comment by romoore** [comment]
Hi @adelbios, thanks for checking out MDC-iOS! I'm still a bit new to the team, but I don't believe MDCAppBar has built-in navigation the way you're expecting.  If you take a look at [MDCNodeListViewController](https://github.com/romoore/material-components-ios/blob/develop/catalog/MDCCatalog/MDCNodeListViewController.swift#L361), you can see that it prepares a container view with an MDCAppBar for any presented child view controllers. 

Someone else on the team may have more insight, but hopefully looking at how it's done for the MDC Catalog app should get you unblocked.

**Comment by romoore** [comment]
I've opened a Feature Request to support the functionality that you've described.  I'm going to close this question for now, please feel free to re-open if you feel I've missed something.  Thanks for asking! 😄
