### ISSUE TITLE
[FeatureHighlight] Elevation of circle

### ISSUE THREAD

**Issue by codeman7** [material-components/material-components-ios#1919]
I am confused if the circle should be elevated or not. Within the material guidelines the first example  https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B4kv-3uZbS1qQVhNbFlVdlNsOEE/engagement-featurediscovery-single-flow.mp4 clearly the circle is elevated but in the third example, it is not elevated https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B4kv-3uZbS1qSUVvZzBiZFJ5bWs/engagement-featurediscovery-multi-flow.mp4. 

Not sure if this is the right place to ask this if not feel free to close the issue.  I have also asked @googledesign on twitter as I just came across this inconsistency today.

**Comment by samnm** [comment]
Hey @codeman7, good question. Internally we concluded that Feature Highlights should not have shadows but I agree the docs are inconsistent with this conclusion.

For design oriented questions, email material@google.com. That address goes to the whole design team for them to collaborate on answers to questions like this.

I have emailed them and cc'd you on the conversation.

**Comment by samnm** [comment]
Sorry I thought our design communication alias was public, but maybe it isn't... I'll update you when I get a reply!

**Comment by codeman7** [comment]
Thanks Sam!
