### ISSUE TITLE
"deleteButtonString" doesn't support i18n

### ISSUE THREAD

**Issue by sczs** [material-components/material-components-ios#1927]
We (Chromium) are using MDCCollectionViewController for some of our settings screens. We've realized that the  MDCCollectionStringResources(deleteButtonString) _footerInfoBar message doesn't support i18n, so this "Delete" text is never translated. 

On the other hand _footerInfoBar is not exposed so I can't set the message directly. I'm not sure if I could use a different bundle for MDC or there's some configuration that we might be missing. 

Any help or input is appreciated!

**Comment by romoore** [comment]
Hi @sczs .  Sorry about this, unfortunately due to the way we handle translations, I don't believe there's any way you can add translations to your app directly (without forking).  I'm going to take this to the team and see how we can get the translations out ASAP.

**Comment by sczs** [comment]
Thanks @romoore , let me know if there's something I can help with!

**Comment by jverkoey** [comment]
Marking as Obsolete because we do not intend to continue to invest effort into Collections. Please consider using the new List component instead: https://github.com/material-components/material-components-ios/tree/develop/components/List
