### ISSUE TITLE
[AppBar] MDCNavigationController similar to UINavigationController should support MDCAppBar and MDCNavigationBar 

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#1934]
### Overview
Currently MDCAppBar and MDCNavigationBar are simple views and do not provide any mechanisms for containment or presentation of other view controllers.  MDC should provide a UINavigationController-style view controller that supports push/pop semantics to make adoption of app-wide AppBar or MDC Navigation Bar easier.

Related to #1918

**Comment by jverkoey** [comment]
Resolved by https://github.com/material-components/material-components-ios/pull/4650
