### ISSUE TITLE
Fix incorrect use of NSBundle

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1941]
A common pattern in our code is:

```
// Bad
 NSBundle *bundle = [NSBundle bundleForClass:[self class]];
```

Per @brianjmoore in #1930 this will fail for subclasses.  We should be explicit about the class as in:

```
 NSBundle *bundle = [NSBundle bundleForClass:[MDCActivityIndicator class]];
```

Fix incorrect use throughout codebase.

**Comment by willlarche** [comment]
This is ok in examples or should we do it there too?

**Comment by romoore** [comment]
I vote for "yes": I think our examples should demonstrate best/recommended practices as much as practical.

**Comment by willlarche** [comment]
Oh, wait. Aren't these all for assets that should now be in asset catalogs?

**Comment by brianjmoore** [comment]
Yes, though you still need to figure out the appropriate bundle (App/extension vs framework) for the asset catalog so you can pass that to `+imageNamed:inBundle:compatibleWithTraitCollection:`.

**Comment by willlarche** [comment]
On it.
