### ISSUE TITLE
[Dialogs] Dialogs look bad when buttons have UIAppearance'd contentEdgeInsets

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#1943]
### Overview
While testing Dialogs in the MDC Catalog, I noticed several of the examples no longer show any text (except an ellipsis) for the button text.  This does not seem to be caused by dynamic type.

It looks like something changed in #1896 (commit [3951775](https://github.com/material-components/material-components-ios/commit/395177518777a355457dc0829903e47483420984)). The bug is present in that commit but not the previous commit.

### Reproduction steps
1. Open MDC Catalog &rarr; Dialogs
1. Open "Demo"
1. Tap on "Programmatic"

### Examples
![simulator screen shot sep 1 2017 10 54 03 pm](https://user-images.githubusercontent.com/1753199/29992399-7883ed12-8f68-11e7-83ff-3aa16508afe5.png)

![simulator screen shot sep 1 2017 10 48 03 pm](https://user-images.githubusercontent.com/1753199/29992400-7e5e7e28-8f68-11e7-967e-0c0e05591cda.png)

### Version number
34.0.1

### Operating system and device
iPhone 5s/iOS 9.3 (Simulator)

**Comment by romoore** [comment]
It looks like because we are using UIAppearance proxy for setting contentEdgeInsets, any calls to `[button sizeToFit]` before the button is in the view hierarchy will result in wrong (too small) dimensions.  The earliest time the buttons can be resized in the layout process appear to be in `-viewWillLayoutSubviews`.

```objectivec
- (void)viewWillAppear:(BOOL)animated {
  // Insets are {0, 0, 0, 0}
  [super viewWillAppear:animated];
}

- (void)viewWillLayoutSubviews {
  // Insets are {8, 16, 8, 16}
  [super viewWillLayoutSubviews];
  [_button sizeToFit];
}
```

**Comment by samnm** [comment]
There are two problems here. One, when we place a button in an example often we call sizeToFit before adding it to the view hierarchy. This is incompatible with UIApperance'd contentEdgeInsets.

The other is that Dialogs seem to also sizeToFit buttons at the wrong time.

**Comment by samnm** [comment]
I'm rolling back the buttons change until this issue gets resolved. See #1948 for rollback.

Also I'll update any examples that incorrectly sizeToFit a button before it is in the view hierarchy.
