### ISSUE TITLE
[Catalog] NavBar examples status bar glitch

### ISSUE THREAD

**Issue by chuga** [material-components/material-components-ios#1952]
Some of the NavBar examples are built assuming that we can hide the status bar, but change #1499 removed that per-vc functionality by setting UIViewControllerBasedStatusBarAppearance to false.

![simulator screen shot sep 7 2017 12 00 13 pm](https://user-images.githubusercontent.com/4545451/30172941-21142410-93c4-11e7-88fe-b579d8f75e2c.png)

**Comment by sigito** [comment]
This is an obsolete bug, since the status bar appearance was changed in https://github.com/material-components/material-components-ios/commit/80d054e3a571604b2eb2adbc8a09cd5cfbe674a8.
