### ISSUE TITLE
[Catalog] A few Tab Bar examples are visually broken

### ISSUE THREAD

**Issue by chuga** [material-components/material-components-ios#1953]
Looks like something went wrong when theming was implemented.

Examples:
![simulator screen shot sep 7 2017 12 07 18 pm](https://user-images.githubusercontent.com/4545451/30173313-3585524c-93c5-11e7-9d61-7397bbc40632.png)
![simulator screen shot sep 7 2017 12 07 27 pm](https://user-images.githubusercontent.com/4545451/30173316-37485fca-93c5-11e7-83b5-8010aa173793.png)

**Comment by romoore** [comment]
I think we should decide how much of the catalog will be themed versus providing a backdrop against which to display themed components.
