### ISSUE TITLE
[Catalog] Theme examples should provide at least 2 colors

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#1957]
### Overview
Our single-color theme examples do not work with some of our MDC components (notably MDCNavigationBar and by extension MDCHeaderStackView) and so should not be provided as examples.  We should highlight the use of two-color schemes or two-palette schemes instead.

In the case of MDCNavigationBar, the "Green Theme" results in a navigation bar with the same color for background and tint.  This means any MDCButtonBarButtons have the same image tint color as their background view.

![screen shot 2017-09-08 at 3 12 19 pm](https://user-images.githubusercontent.com/1753199/30227668-71ce64da-94a8-11e7-9eb9-7b74a86b871c.png)

### Reproduction steps
1. Open the MDC Catalog and navigate to Themes &rarr; Demo &rarr; Green Theme
1. Navigate to Navigation Bar &rarr; Demo

### Version number
34.0.01

### Operating system and device
Any/all

**Comment by jgunaratne** [comment]
The nav bar tint color is not longer changed. This was fixed in https://github.com/material-components/material-components-ios/pull/2016
