### ISSUE TITLE
[Tabs] MDCTabBarViewController Subclass issue

### ISSUE THREAD

**Issue by vksid** [material-components/material-components-ios#1959]
I'm using MDCTabBarViewController subclass for custom MDCTabBar implementation, however, tabs in Tabbar are not showing selection indicator. Also When the tabs are selected, image of tab shifts slightly in the vertical direction.

Here is the link of demo project:  [https://www.dropbox.com/s/hvkaeejh2oz87hx/tabbardemo.zip?dl=0](url)

**Comment by vksid** [comment]
This issue got fixed for me, when I added following method to subclass.


`
override func position(for bar: UIBarPositioning) -> UIBarPosition {
        
        return .top
    }
`

**Comment by beraybentesen** [comment]
@vksid can you share the complete solution again? The link is dead it seems.
