### ISSUE TITLE
[Collections][iOS 11] Collections have a 20pt padding at the top

### ISSUE THREAD

**Issue by gambard** [material-components/material-components-ios#1962]
### Overview
When used with iOS 11, there is a 20pt padding at the top of the collections in the catalog app. This is particularly visible once a submenu is opened.
![simulator screen shot - iphone 7 - 2017-09-11 at 15 00 30](https://user-images.githubusercontent.com/1257452/30275564-0dae878a-9702-11e7-857b-1494de4252be.png)
Probable root cause and possible fix: https://stackoverflow.com/questions/44390971/automaticallyadjustsscrollviewinsets-was-deprecated-in-ios-11-0

Maybe there is also a fix to do at the MDCCollectionViewController level (but I think the user should have the default configuration).

### Reproduction steps
 - Open MDCCatalog on an iOS 11 device
 - Check that there is a 20pt padding at the top

### Version number
 - 34.0

### Operating system and device
iOS 11 only

**Comment by chuga** [comment]
This has been fixed
