### ISSUE TITLE
MDCButton ignores/overwrites alpha.

### ISSUE THREAD

**Issue by randallli** [material-components/material-components-ios#1964]
If you try to set the alpha of a button the button will get set it back to 1.0. 

Internal logic uses the enabled/disabled state to set the alpha of the button.

 `   self.alpha = self.enabled ? 1.0f : _disabledAlpha;`
https://github.com/material-components/material-components-ios/blob/cda52f4e6b29f0ed72a4de47974c603970bfe142/components/Buttons/src/MDCButton.m#L643

**Comment by randallli** [comment]
in order to return the alpha to a user custom value we should store it on the setter of alpha.

**Comment by romoore** [comment]
Does it make sense to have a `setAlpha:forState:`? It looks like that's the behavior we're implementing for `.Normal` and `.Disabled`.

**Comment by randallli** [comment]
Long term I'd like to remove disabledAlpha and encourage fully opaque buttons. Opaque buttons are hard to measure for accessibility.
