### ISSUE TITLE
[Catalog] FlexibleHeaderView Top Layout Guide example doesn't scroll on iPhone X

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#1970]
### Overview
The FlexibleHeaderView "Utilizing Top Layout Guide" example does not scroll - it's content size is probably too short for the iPhone X. It has a bit of scrollable area on iPhone 8+.

### Reproduction steps
1. Open MDC Catalog on iPhone X &rarr; Flexible Header View &rarr; Utilizing Top Layout Guide
1. Scroll the view below the Flexible Header

### Version number
34.0.01

### Operating system and device
iPhone X/iOS 11 (Simulator)

### Related issues
#1969

**Comment by wenyuzhang666** [comment]
Verified on the iPhoneX. This issue has been fixed, and the view is scrollable.
