### ISSUE TITLE
[Catalog] FlexibleHeaderView Standard UINavigationBar example overlaps status bar on iPhone X

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#1971]
### Overview
On an iPhone X, the UINavigationBar embedded in the Flexible Header View overlaps the status bar. The buttons do not seem to be tappable. On an iPhone 8+, the navigation bar is clearly overlapping part of the status bar, but not as much.

**iPhone 8+**
![fhv-uinavbar-ip8](https://user-images.githubusercontent.com/1753199/30379847-cb367ea8-98d2-11e7-967d-ca1338444fd3.png)

**iPhone X**
![fhv-uinavbar-ipx](https://user-images.githubusercontent.com/1753199/30379849-cf9d67c2-98d2-11e7-94a7-2536e5252548.png)

### Reproduction steps
1. Open MDC Catalog on iPhone X &rarr; Flexible Header &rarr; Standard UINavigationBar

### Version number
34.0.01

### Operating system and device
iPhone X/iOS 11 (Simulator)

### Related issues
#1970 #1969

**Comment by chuga** [comment]
This seems to be something that should be fixed in the Catalog example and not in the actual component, correct?
Related to #2008

**Comment by romoore** [comment]
Yes, I believe this is a catalog bug but I haven't gone through the code to see if it's unique to the way this example places the flexible header or if it's in the component.

**Comment by wenyuzhang666** [comment]
Verified on iPhoneX. It doesn't happen now. 
Screenshot attached:
![simulator screen shot - iphone x - 2018-08-27 at 14 37 45](https://user-images.githubusercontent.com/8836258/44678622-c798b680-aa06-11e8-95e4-f5c43d5d7d84.png)
