### ISSUE TITLE
[Catalog] Masked Transition Full Screen demo overlaps the top cut-out on iPhone X

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#1972]
### Overview
The Masked Transition Full Screen example overlaps the cut-out and rounded corners at the top of the iPhone X and some content cannot be viewed.  It also fails to account for the Home bar at the bottom of the screen.  

![mt-fs-ipx](https://user-images.githubusercontent.com/1753199/30380008-54e84a78-98d3-11e7-8440-214799c9e23d.png)

### Reproduction steps
1. Open MDC Catalog on iPhone X &rarr; Masked Transition &rarr; Demo
1. Tap on "Full Screen" and then tap on one of the Floating Action Buttons

### Version number
34.0.01

### Operating system and device
iPhone X/iOS 11 (Simulator)

---
#### Internal data
- Associated internal bug: [b/117179679](http://b/117179679)

**Comment by material-mirror** [comment]
The internal issue [b/117179679](http://b/117179679) is now closed. This issue is being closed as a result.
