### ISSUE TITLE
[MDCPalette] Issue in Swift usage

### ISSUE THREAD

**Issue by codeman7** [material-components/material-components-ios#1984]
I updated my pod to 34.0.2 and have imported the class.

`
import MaterialComponents.MaterialPalettes
`

When you go to use it there are only four colors (blue, green, red, yellow). No tints are available. 

![screen shot 2017-09-14 at 9 36 10 am](https://user-images.githubusercontent.com/7131294/30442645-e039aae6-9931-11e7-976a-b9cd917caefa.png)
![screen shot 2017-09-14 at 9 36 35 am](https://user-images.githubusercontent.com/7131294/30442647-e1dc4912-9931-11e7-8e43-6ff1f6049302.png)

**Comment by codeman7** [comment]
I had another file that redefined MDCPalette that's what caused the error.

**Comment by willlarche** [comment]
Awesome! Thanks.
