### ISSUE TITLE
Components should respect the device's safe area

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#1987]
The iPhone X' screen has a cut out on the top for sensors and rounded corners.

Material components should respect a device's safe area.

The height of the status bar will also be variable.

**Comment by ianegordon** [comment]
Apple's HIG - iPhone X
https://developer.apple.com/ios/human-interface-guidelines/overview/iphone-x/

**Comment by ianegordon** [comment]
Consider back-porting UIView safeAreaLayoutGuide to use across our components.
https://developer.apple.com/documentation/uikit/uiview/2891102-safearealayoutguide?language=objc

**Comment by ianegordon** [comment]
If we choose to backport, we will likely need to handle the entire API:
UILayoutGuide safeAreaLayoutGuide
UIEdgeInset safeAreaInsets
-[UIView safeAreaInsetsDidChange]

UILayoutGuide was introduced in iOS 9.

**Comment by romoore** [comment]
Also [[UIViewController viewSafeAreaInsetsDidChange]](https://developer.apple.com/documentation/uikit/uiviewcontroller/2891116-viewsafeareainsetsdidchange)

**Comment by gambard** [comment]
FYI, it seems that the applications compiled with an iOS < 11 sdk have black strips at the top/bottom of iPhone X.

**Comment by chuga** [comment]
Marking this as closed as we have issues for each component.
