### ISSUE TITLE
[TextFields] Outlined needs to support keeping placeholder from changing color

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#2000]
Outlined text field controllers need to handle a state where the outline (and decorations) are colored like error but the placeholder does not change color.

---
#### Internal data
- Associated internal bug: [b/117179526](http://b/117179526)

**Comment by jverkoey** [comment]
Are there specs/mocks describing the behavior you'd like implemented here?

**Comment by willlarche** [comment]
Yes. Crane. https://material.io/design/material-studies/crane.

Error color does not affect floating placeholder.

**Comment by andrewoverton** [comment]
That link is giving me a 404

**Comment by willlarche** [comment]
https://material.io/design/material-studies/crane.html

**Comment by adamirowe** [comment]
We would like this functionality as well.

**Comment by material-mirror** [comment]
The internal issue [b/117179526](http://b/117179526) is now closed. This issue is being closed as a result.
