### ISSUE TITLE
[BottomSheet] Support Safe Area

### ISSUE THREAD

**Issue by chuga** [material-components/material-components-ios#2005]
### Overview
Issues visible in the Catalog: Full screen is unusable because of the top notch. Potential issues with the Home indicator and the content. On portrait, the content doesn’t adhere to the safe area.

![bottomsheetlandscape](https://user-images.githubusercontent.com/4545451/30612088-70cebeac-9d51-11e7-9dda-60238a10bb10.png)

![bottomsheetfullscreen](https://user-images.githubusercontent.com/4545451/30612135-9387edc4-9d51-11e7-8c3a-c73a644e328e.png)

### Version number
35.0.0

### Operating system and device
iOS 11 / iPhoneX

**Comment by ajsecord** [comment]
Compare to internal change 172890984 for implementation details.

**Comment by ajsecord** [comment]
Related internal issue 67918500.
