### ISSUE TITLE
[Collections] Support Safe Area

### ISSUE THREAD

**Issue by chuga** [material-components/material-components-ios#2006]
### Overview
Issues visible in the Catalog: Background, content and accessory views don’t adhere to the safe area guidelines. 

![portrait](https://user-images.githubusercontent.com/4545451/30612286-0927efd4-9d52-11e7-8b30-bb88725a1eea.png)

### Version number
35.0.0

### Operating system and device
iOS 11 / iPhone X

**Comment by gambard** [comment]
Depending on how you want to fix this, it might be a Collections issue more than a CollectionCell. The bounds used to style the cards is computed in MDCCollectionViewController.
So if the correct behavior is to have the cards drawn completely inside the safe area, it is a Collections problem. If it is to have the cards taking the whole screen but having the content of the card respecting the safe area, it is a CollectionCell problem.
I guess it can be both as we might want the cards to be drawn inside the safe area, but to have the cell taking the full width with the content inside the safe area for the "grouped" style.

**Comment by chuga** [comment]
Good point, I've renamed this bug to track any Collection-related fixes.
