### ISSUE TITLE
[Dialog] Support Safe Area

### ISSUE THREAD

**Issue by chuga** [material-components/material-components-ios#2007]
### Overview
Issues visible in the Catalog: The padding needs to be adjusted to make sure it fits into the safe area

![simulator screen shot - iphone x - 2017-09-19 at 15 51 57](https://user-images.githubusercontent.com/4545451/30612463-aa8bae24-9d52-11e7-8776-5fe4e021dae4.png)

### Version number
35.0.0

### Operating system and device
iOS 11 / iPhone X

**Comment by romoore** [comment]
Related to #1973
