### ISSUE TITLE
[TextField] Floating label animation

### ISSUE THREAD

**Issue by codeman7** [material-components/material-components-ios#2017]
When `editingEnded` is called on a TextField that has no text the placeholder label snaps back to its original size and place. 

I think the `movePlaceholderToUp` method is where the bug is but I can't seem to find a fix for it.

**Comment by willlarche** [comment]
`editingEnded`? Do you mean `endEditing:YES`?

**Comment by codeman7** [comment]
I think I may have been working with an old version of TextFields that was causing the error. For three days it would not animate down it would just go from up and 3/4 size after the transform to its original size and position. Now, it's working as intended.

**Comment by willlarche** [comment]
Ok, great! Refile if you have additional trouble.
