### ISSUE TITLE
[Tabs] Determine Landscape versus Portrait layout

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#2022]
In iOS 11:
TabBars in portrait mode are laid out with an icon centered above a label
TabBars in landscape mode are laid out with a leading icon and a trailing label

Should this be incorporated into the Material Spec?
Should this be a platform exception?

---
#### Internal data
- Associated internal bug: [b/117179406](http://b/117179406)

**Comment by ianegordon** [comment]
Internal issue: b/66156092

**Comment by romoore** [comment]
Closing as obsolete. We have Bottom Navigation now.
