### ISSUE TITLE
[TabBar] Text tabs should support 2-lines of text

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#2025]
### Overview
Tabs (which are not Bottom Navigation) should support 2 lines of text.  The label should wrap text to 2 lines and then shrink the text down to 85% of original size to fit before using truncation rules.  85% uses UILabel's `minimiumScaleFactor` to accomplish the Material Design guideline of dropping from 14 sp to 12 sp font sizes (12/14 = 0.857).

https://material.io/guidelines/components/tabs.html#tabs-specs

### Reproduction steps
1. Open MDC Catalog &rarr; Tab Bar &rarr; Text Tabs
1. Scroll to the right and notice the "very long" tab title - it should be 2 lines long.

### Version number
35.1.0

### Operating system and device
All/Any

### Related issues
#1321

**Comment by ianegordon** [comment]
I would recommend pushing back on spec for a platform exception.
Unless there are clients with a compelling use case, I do not believe we should support multiline tabs.
