### ISSUE TITLE
[Tabs] Scrollable tabs should limit width to 360 pt 

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#2029]
### Overview
Material Design requires that Scrollable Tab widths be no more than 360 points or the width of the parent view minus 56 points.  Currently, tabs can be as wide as the parent view, even if that width is 480 points.

### Reproduction steps
1. Open MDC Catalog &rarr; Tab Bar &rarr; Text Tabs
1. The width of the widest tab should be no more than 360 points on any device.

### Version number
35.1.0

### Operating system and device
All/any

### Related issues
https://material.io/design/components/tabs.html#spec

---
#### Internal data
- Associated internal bug: [b/117179233](http://b/117179233)

**Comment by material-mirror** [comment]
The internal issue [b/117179233](http://b/117179233) is now closed. This issue is being closed as a result.
