### ISSUE TITLE
AppBar IconButtons should have bigger hit area

### ISSUE THREAD

**Issue by appsforartists** [material-components/material-components-ios#203]
In the Pesto demo, it feels like I have to hit the hamburger button perfectly to have it open the drawer.  As [mentioned in Spec](https://www.google.com/design/spec/layout/structure.html#structure-app-bar), an IconButton should be a 56dp square with 16dp padding, leaving 24dp for the asset.  This makes sure it is finger-friendly.

**Comment by ianegordon** [comment]
This was fixed in the A11y spike.
Thank you @appsforartists for being *way* ahead of the curve on this one.  😄
