### ISSUE TITLE
[AppBar] Rendering issue with a scrollview with section headers

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#2032]
There is an internal report of rendering failure when using an AppBar with a child tableview.
The sections headers are getting rendered within the bounds of the appbar.

This is may be related to having section headers in the child view controller.

A fix should verify that the indicies perform as expected.

---
#### Internal data
- Associated internal bug: [b/117179544](http://b/117179544)

**Comment by macourteau** [comment]
The PR above demonstrates the issue. Here's a couple screenshots:

![simulator screen shot - iphone 8 - 2017-09-26 at 15 42 03](https://user-images.githubusercontent.com/4503886/30880654-4edbef4c-a2d1-11e7-88f4-34215db8f093.png)
![simulator screen shot - iphone 8 - 2017-09-26 at 15 42 21](https://user-images.githubusercontent.com/4503886/30880653-4edad12a-a2d1-11e7-9852-7714c01168b3.png)

**Comment by material-mirror** [comment]
The internal issue [b/117179544](http://b/117179544) is now closed. This issue is being closed as a result.
