### ISSUE TITLE
[MDCAlertController] Support customizing text color

### ISSUE THREAD

**Issue by zubko** [material-components/material-components-ios#2046]
### Overview
It would be great if there was a way to customize the text of the alert to be a different color.
The customization only works for the buttons so far.
(Ideally of course the best is to be able to set different color for the title and for the message)

### Reproduction steps
    [[UILabel appearanceWhenContainedIn:[MDCAlertController class], nil] setTextColor:UIColor.redColor];

### Version number
31.0.1

### Related issues
#1671

### Temporary workaround
It's possible to enumerate subviews of the alert and change the color directly:

    for (UILabel *label in [alertController.view subviewsOfClass:[UILabel class]]) {
      label.textColor = [UIColor blueColor];
    }

**Comment by ianegordon** [comment]
Added again in #3218.
