### ISSUE TITLE
Snackbar message text will not grow to more than 2 lines.

### ISSUE THREAD

**Issue by billgriesau** [material-components/material-components-ios#2059]
### Overview
Snackbar message text will not grow to more than 2 lines. It should grow as tall as needed to fit the entire string.

### Reproduction steps
```
let message = MDCSnackbarMessage()
message.text = "This is a long string, a string that is long enough to span more than two lines. This 
    is a long string, a string that is long enough to span more than two lines."
MDCSnackbarManager.show(message)
```

### Version number
 34.0.1

### Operating system and device
iOS 10 on iPhone 7

---
#### Internal data
- Associated internal bug: [b/117179382](http://b/117179382)

**Comment by romoore** [comment]
This is resolved. The Snackbar will allow multiple lines but shrinks the text.

![Simulator Screen Shot - iPhone 7 - 2019-06-04 at 09 28 32](https://user-images.githubusercontent.com/1753199/58883665-e0787b80-86ac-11e9-9655-354435208389.png)
