### ISSUE TITLE
[Catalog] Fix MDCNodeListViewController's use of MDCAppBarContainerViewController

### ISSUE THREAD

**Issue by chuga** [material-components/material-components-ios#2069]
### Overview
MDCNodeListViewController hardcodes the frame of the contentViewController. This breaks the layout on rotation, as the flexible header might've changed in size.

https://github.com/material-components/material-components-ios/blob/80d054e3a571604b2eb2adbc8a09cd5cfbe674a8/catalog/MDCCatalog/MDCNodeListViewController.swift#L403

### Version number
35.0.2

### Operating system and device
iOS 11 / iPhone X

**Comment by jverkoey** [comment]
Closed by https://github.com/material-components/material-components-ios/pull/4650
