### ISSUE TITLE
[Collections] MDCCollectionViewCell doesn't support XIB on Xcode8

### ISSUE THREAD

**Issue by ulukaya** [material-components/material-components-ios#2083]
When I'm trying to create a new file inheriting from "MDCCollectionViewCell", Xcode8 wouldn't let me create a XIB file with it, whereas Xcode9 does.
Also subclassing "UICollectionViewCell" does as well.

<img width="479" alt="screen shot 2017-10-03 at 11 25 04 am" src="https://user-images.githubusercontent.com/821349/31133468-9ca022f0-a82d-11e7-93d1-bbc4229b4d31.png">

**Comment by ianegordon** [comment]
We are not intending on any significant updates to the current Collections component. 😞
We are working on a much simpler [List component](https://github.com/material-components/material-components-ios/tree/develop/components/List). 😄
