### ISSUE TITLE
Subheader font doesn't match spec.

### ISSUE THREAD

**Issue by chriscox** [material-components/material-components-ios#210]
MDCTypography shows font at regular-16, however spec shows it should be medium-14.

Spec reference:
https://www.google.com/design/spec/components/subheaders.html#

MDCTypography reference:
https://github.com/google/material-components-ios/blob/develop/components/Typography/src/MDCTypography.m#L113

**Comment by jverkoey** [comment]
MDCTypography is now a legacy API.
