### ISSUE TITLE
MDCCollectionView - Long text in main and detail over laps entirely

### ISSUE THREAD

**Issue by somberImp** [material-components/material-components-ios#2110]
### Overview
I'm trying to create some MDCCollectionViewTextCells that have long text in textLabel and detailTextLabel. Even in the simplest test app, these labels end up **overlapping**. If I just make one of the two labels' text long, that long text formats as expected.

### Reproduction steps
- (UICollectionViewCell *)collectionView:(UICollectionView *)collectionView
                  cellForItemAtIndexPath:(NSIndexPath *)indexPath {
  MDCCollectionViewTextCell *cell =
      [collectionView dequeueReusableCellWithReuseIdentifier:@"cell" forIndexPath:indexPath];
  NSString * longSentence = @"Lions Lions Lions Lions Lions Lions Lions Lions Lions Lions Lions Lions Lions Lions Lions";
  NSArray<NSString *> *animals = @[longSentence, @"Tigers", @"Bears", @"Monkeys", @"Monkeys", @"Monkeys"];
  cell.textLabel.text = animals[indexPath.section];
  cell.detailTextLabel.text = longSentence;

  cell.textLabel.lineBreakMode = NSLineBreakByWordWrapping;
  cell.textLabel.numberOfLines = 0;

  cell.detailTextLabel.lineBreakMode = NSLineBreakByWordWrapping;
  cell.detailTextLabel.numberOfLines = 0;

  return cell;
}

- (CGFloat)collectionView:(UICollectionView *)collectionView
    cellHeightAtIndexPath:(NSIndexPath *)indexPath {
  // crazy big number
  return 240;
}

### Version number
MaterialComponents (35.3.0)

View of both long
![simulator screen shot - iphone x - 2017-10-05 at 18 22 06](https://user-images.githubusercontent.com/2817234/31259316-b67482a6-a9fa-11e7-995c-a2b98114cbce.png)

View of one long
![simulator screen shot - iphone x - 2017-10-05 at 18 27 06](https://user-images.githubusercontent.com/2817234/31259357-eb3a6d5c-a9fa-11e7-8173-ce61dbc3e507.png)

**Comment by romoore** [comment]
Thanks, @somberImp !  The MDCCollectionViewCell and MDCCollectionViewTextCell only support 1, 2, and 3-line text at present.  Material Guidelines [only recommend these 3 styles](https://material.io/guidelines/components/lists.html#lists-specs) so they are the ones that were built first.  We have an [existing issue (#1806)](https://github.com/material-components/material-components-ios/issues/1806) outlining this limitation.  I'm going to close this issue as a duplicate, but if you feel like tackling the issue with a Pull Request, we're always happy to review! 😃 

Duplicates #1806
