### ISSUE TITLE
[Tabs] MDCTabBarViewController should respect child VC status bar settings

### ISSUE THREAD

**Issue by Icycle** [material-components/material-components-ios#2111]
### Overview
MDCTabBarViewController is designed to present one more more child view controllers which control the top area of the screen including the status bar area.  Therefore MDCTabBarViewController should delegate control of the status bar area to the currently selected child view controller

### Reproduction steps
Create an instance of MDCTabBarViewController with one child view controller with a black navigation bar and status bar.  The status bar text will be dark and not legible.

### Version number
35.3.0

### Operating system and device
iOS 11 / iPhone X (simulator)

**Comment by Icycle** [comment]
I think the problem can be resolved by adding this code:

- (UIViewController *)childViewControllerForStatusBarHidden {
  return self.selectedViewController;
}

- (UIViewController *)childViewControllerForStatusBarStyle {
  return self.selectedViewController;
}

**Comment by codeman7** [comment]
You should open a PR, the team is very friendly and will help you if there are issues.
