### ISSUE TITLE
[Examples] Convert to Swift 4.0

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#2119]
When Xcode 8 support is dropped. The majority of the work can be gleaned from #2089 

---
#### Internal data
- Associated internal bug: [b/117179037](http://b/117179037)

**Comment by ianegordon** [comment]
Blocked on #2087

**Comment by material-mirror** [comment]
The internal issue [b/117179037](http://b/117179037) is now closed. This issue is being closed as a result.
