### ISSUE TITLE
[TextFields] Floating label in MDCTextInputControllerLegacyDefault is sometimes indented.

### ISSUE THREAD

**Issue by JessBattrick** [material-components/material-components-ios#2121]
### Overview
Occasionally, the floating label for the placeholder is showing as indented.  I believe this happens with both the MDCTextInputControllerDefault & MDCTextInputControllerLegacyDefault.  It appears to be related to setting the MDCTextField's text programatically.

### Reproduction steps
 Set both the placeholder & text programatically. The floating label will be indented (both when field is active & inactive).
![image](https://user-images.githubusercontent.com/32578245/31290237-b4983fbe-aa99-11e7-87d6-d4b3a685c73b.png)

### Version number
 35.3.0

### Operating system and device
iOS 10.3 iPhone 7 Plus (simulator)

**Comment by willlarche** [comment]
I've discovered what I think is the issue: the floating position of the placeholder is actually a calculated point that relies on the text's value since it's transformed. When you set text that isn't exactly the same size as the one that was there, it doesn't recalculate. I'll try adding that check in.

**Comment by JessBattrick** [comment]
I've changed to using placeholderText in the controller, but I still see this issue (version 38.0.1)

**Comment by willlarche** [comment]
My mistake! I was replicating some cases on single-line but not being exhaustive on multi-line. Reopening issue.

**Comment by willlarche** [comment]
Reopening. Seeing behavior in Multiline.

**Comment by willlarche** [comment]
Was happening only in text area controller.
