### ISSUE TITLE
[FlexibleHeader] Navigation bar elements visible when collapsed

### ISSUE THREAD

**Issue by brianjmoore** [material-components/material-components-ios#2127]
### Overview
When the app bar/flexible header has shifting enabled (without status bar), the navigation bar's content is still visible even when in the most-collapsed state.

Looks hidden on iPhone X:
![simulator screen shot - iphone x - 2017-10-07 at 11 36 42](https://user-images.githubusercontent.com/395995/31309417-d908980c-ab53-11e7-82d9-f7ad5537e3d6.png)

…but actually isn't (when swiping up from home indicator):
![simulator screen shot - iphone x - 2017-10-07 at 11 36 46](https://user-images.githubusercontent.com/395995/31309418-da845888-ab53-11e7-84b6-fd9df4054805.png)

### Reproduction steps
1. Open Catalog, go to Flexible Header -> Configurator
2. Enable Shift behavior (without status bar)
3. Scroll up on content so the header collapses
4. Swipe up interactively on the home indicator
RESULT: You can see the title appear from under the sensor housing
EXPECTED: All navigation bar content is hidden when the header is collapsed.

In the more general case:
* On 20pt status bar devices (not iPhone X), partial buttons and other parts of the nav bar appear at the very top of the screen
* Non-app bar uses of flexible headers have a similar need to hide certain header content when collapsed. This is currently possible using the layoutDelegate, but tricky to implement robustly.

This behavior makes it hard to justify using the header in shifting-but-not-hiding-status-bar mode, which is unfortunate given the new emphasis on not hiding the status bar with iPhone X.

### Version number
35.3.0 (develop @ 5135ecc27a9effaad989f2b568b35b59847be154)

### Operating system and device
iPhone X, iOS 11.0

**Comment by chuga** [comment]
Note: This isn't a new iOS 11.0 / iPhone X bug, just more visible on an iPhone X because of the bigger status bar height.

AFAIK, the flexible header shifter mechanism doesn't take care of actually hiding anything, it just pushes the content up. I'll re-assign this to @jverkoey as he might have a better idea of how to properly address this.

**Comment by jverkoey** [comment]
This is a tricky one because we can't necessarily assume anything about the contents of the flexible header. We could introduce a new opt-in API that adds a default opacity shifting behavior, with the intent to eventually make it the default behavior with an opt-out API. What do you think?

**Comment by jverkoey** [comment]
A few of the cases that I'm aware of where we wouldn't want default-fade-out behavior:

- Full-bounds images.
- Non-textual content.

**Comment by chuga** [comment]
An opt-in API sgtm, do we have a sense of how frequently people want this fade-out behavior?

**Comment by jverkoey** [comment]
App Bar - and any components like it - wants the fade out behavior all the time on the title. I believe it already implements it. App Bar probably wouldn't want the full content fade out behavior because it'll want to only fade out the navigation bar.

**Comment by jverkoey** [comment]
Oh, hm. Seems the App Bar does not actually implement the fade out behavior by default >.<

**Comment by chuga** [comment]
Re-opening as I'll be adding a simple API to the AppBar itself in a follow-up PR.

**Comment by jverkoey** [comment]
There is now an API to ensure that the app bar's contents are hidden when it scrolls, so marking this as closed.
