### ISSUE TITLE
[TextFields] Setting text programmatically causes placeholder & text to overlap

### ISSUE THREAD

**Issue by JessBattrick** [material-components/material-components-ios#2152]
### Overview
Setting the text programatically, after the MDCTextInputController has already been defined, results in the placeholder overlapping with the text.
![image](https://user-images.githubusercontent.com/32578245/31461924-e583744c-ae98-11e7-98e9-6325f42f6806.png)

### Reproduction steps
1. Initialize a MDCMultilineTextField
2. Create a MDCTextInputControllerDefault with the text input from step 1
3. Set both the text & placeholder on the text field programatically

### Version number
35.3.0

### Operating system and device
iOS 10.3 iPhone 7 Plus (simulator)

---
#### Internal data
- Associated internal bug: [b/139730186](http://b/139730186)

**Comment by willlarche** [comment]
@JessBattrick Just want to verify, setting these properties is done before it's on screen?

**Comment by JessBattrick** [comment]
Yes, but I've also replicated in a scenario where the text was changed later on (I was able to work around this by creating a new MDCTextInputController)

**Comment by abdelrahman-badary** [comment]
Hello this still happens to me on version 84.3.0

**Comment by romoore** [comment]
@abdelrahman-badary Can you please provide a snippet of code showing how you can reproduce this issue? I see in `TextFieldLegacySwiftExample` that this exact situation (a `LegacyDefault` controller used with pre-populated `text` and `placeholderText`) but without the errant presentation here.

**Comment by yarneo** [comment]
We were now able to reproduce this on our end, and the reason this happens is because the MDCTextInputController is not retained and only initialized and retained in the local scope of the method it is set up in.

The solution is to have the controller be a @property or an iVar in your class.

**Comment by abdelrahman-badary** [comment]
@yarneo Hello, Thank your for your response but i am already doing this, the controller is retained as property in my class.

**Comment by romoore** [comment]
Thanks, @abdelrahman-badary. Could you please post the relevant code snippets for the text field/controller set-up so we can reproduce the failure conditions?

**Comment by abdelrahman-badary** [comment]
@romoore re 
Here is my property:
`    fileprivate var fieldController: MDCTextInputControllerUnderline? `

and here is the code i have in my setup method: 

`                 fieldController = MDCTextInputControllerUnderline(textInput: multiLineInputField)
        fieldController?.underlineViewMode = .always
        fieldController?.floatingPlaceholderActiveColor = configuration.placeholderColor
        fieldController?.activeColor = UIColor.lightGray
        fieldController?.inlinePlaceholderFont = configuration.placeholderFont
        fieldController?.inlinePlaceholderColor = UIColor.black
        fieldController?.underlineHeightActive = 1.0
        fieldController?.underlineHeightNormal = 1.0
        fieldController?.textInputFont = configuration.inputFont
        multiLineInputField.clearButtonMode = .whileEditing
        multiLineInputField.minimumLines = 3
        multiLineInputField?.textView?.delegate = self
        multiLineInputField.textView?.isScrollEnabled = true
        multiLineInputField.textView?.textContainer.lineBreakMode = .byTruncatingTail `

**Comment by romoore** [comment]
@abdelrahman-badary I'm not seeing your issue. I modified `TextFieldKitchenSinkExample.swift` from our catalog to reproduce your code as closely as possible. However, I'm seeing reasonable behavior when I test. 

![multiline-underline-placeholder](https://user-images.githubusercontent.com/1753199/70547759-70f1b600-1b3f-11ea-925f-2da507dd7e7a.gif)

```swift
    let multilineTextFieldUnderlinePlaceholder = MDCMultilineTextField()
    multilineTextFieldUnderlinePlaceholder.translatesAutoresizingMaskIntoConstraints = false
    scrollView.addSubview(multilineTextFieldUnderlinePlaceholder)

//    multilineTextFieldUnderlinePlaceholder.textView?.delegate = self

    let multilineTextFieldControllerUnderlinePlaceholder =
      MDCTextInputControllerUnderline(textInput: multilineTextFieldUnderlinePlaceholder)
//    multilineTextFieldControllerUnderlinePlaceholder.isFloatingEnabled = false
    multilineTextFieldControllerUnderlinePlaceholder.placeholderText =
      "This is a multi-line text field with placeholder"
    multilineTextFieldControllerUnderlinePlaceholder.underlineViewMode = .always
    multilineTextFieldControllerUnderlinePlaceholder.underlineHeightActive = 1
    multilineTextFieldControllerUnderlinePlaceholder.underlineHeightNormal = 1
    multilineTextFieldUnderlinePlaceholder.minimumLines = 3
    multilineTextFieldUnderlinePlaceholder.textView?.delegate = self
    multilineTextFieldUnderlinePlaceholder.textView?.isScrollEnabled = true
    multilineTextFieldUnderlinePlaceholder.textView?.textContainer.lineBreakMode = .byTruncatingTail
```

Since you are having a separate problem (not a controller retention issue) and for a different controller, would you please open a separate Issue and include both a screenshot/gif of the problem along with the snippet above?  You may also want to double-check your constraints (if you're using them) to ensure there are no invalid combinations or inconsistencies.
