### ISSUE TITLE
[ShadowElevations] Delete MDCShadowElevationSwitch

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#2157]
### Overview
`MDCShadowElevationSwitch` is deprecated but still used by some internal clients. These components should be migrated away from this value if they are no longer using the retired `MDCSwitch` component.

### Version number
35.5.0

---
#### Internal data
- Associated internal bug: [b/117179325](http://b/117179325)

**Comment by material-mirror** [comment]
The internal issue [b/117179325](http://b/117179325) is now closed. This issue is being closed as a result.
