### ISSUE TITLE
[Cocoapods] Relative URLs in markdown files don't resolve properly when viewed in cocoapods.org

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#2162]
### Overview
Cocoapods.org reproduces the README.md for the repo but links that are written relatively in the original document are broken.

```
- [How To Use MDC-iOS](howto/)
- [All Components](components/)
- [Demo Apps](demos/)
- [Contributing](contributing/)
```
### Reproduction steps
1. Go to Cocoapods.org/pods/materialcomponents
1. Click on a link like "How To Use MDC-iOS"
1. You'll be redirected to `https://raw.githubusercontent.com/material-components/material-components-ios/v35.3.0/howto/` and it'll be `400: Invalid Request`

**Comment by jverkoey** [comment]
Our primary priority is the material.io website, so am marking this as obsolete.
