### ISSUE TITLE
[FlexibleHeader] Flakiness on testFlexibleHeaderViewControllerTopLayoutGuideHeightOffPullDownRelease

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#2164]
Unreproducible but it happened twice. `testFlexibleHeaderViewControllerTopLayoutGuideHeightOffPullDownRelease` failed being, if I remember, 5 points off.

**Comment by willlarche** [comment]
iOS 11.1, 7 Plus

**Comment by romoore** [comment]
I've seen it on the iOS 11 (XCode 9/GM) simulators as well.
