### ISSUE TITLE
[TextFields] Floating placeholder out of bounds

### ISSUE THREAD

**Issue by KevinTMiller** [material-components/material-components-ios#2170]
### Overview
First letter of floating place holder goes out of bounds

![screen shot 2017-10-12 at 11 22 24 pm](https://user-images.githubusercontent.com/32279052/31529038-a626bc20-afa4-11e7-811a-f9e72b037945.png)

### Version number
35.3.0

### Operating system and device
iPhone SE iOS 11.0

.

**Comment by willlarche** [comment]
Thank you! This is a bug on our side.
