### ISSUE TITLE
[TextFields] Clear button out of bounds

### ISSUE THREAD

**Issue by KevinTMiller** [material-components/material-components-ios#2171]
### Overview
Clear button out of bounds

### Reproduction steps
Text field clipped to bounds

### Version number
35.3.0

### Operating system and device
iPhone SE iOS 11.0

![screen shot 2017-10-12 at 11 49 52 pm](https://user-images.githubusercontent.com/32279052/31529634-6c0635ee-afa8-11e7-8b95-4368812345fa.png)

**Comment by willlarche** [comment]
This is a tiny rounding error probably. Easy fix! Thank you ;)

**Comment by willlarche** [comment]
Not found in styles that override the default clear button X value like Filled.
