### ISSUE TITLE
[TextFields] Doesn't support text alignment in Interface Builder

### ISSUE THREAD

**Issue by KevinTMiller** [material-components/material-components-ios#2172]
### Overview
Alignment in IB set to center, cursor not at center.

### Version number
35.3.0

![screen shot 2017-10-12 at 11 22 24 pm](https://user-images.githubusercontent.com/32279052/31529802-8cb399d4-afa9-11e7-9e90-5d54f3e5e407.png)

---
#### Internal data
- Associated internal bug: [b/117179425](http://b/117179425)

**Comment by material-mirror** [comment]
The internal issue [b/117179425](http://b/117179425) is now closed. This issue is being closed as a result.
