### ISSUE TITLE
[Xcode 9] New projects show all availability warnings

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#2173]
### Overview
When a user is integrating with a fresh Xcode 9 project, `-Wunguarded-availability` is on and shows 141 warnings for MDC.

### Reproduction steps
To reproduce in catalog, edit `catalog/MaterialComponentsWarnings.xcconfig`:
- Remove `-Werror`
- Change `-Wno-partial-availability` to `-Wpartial-availability`
- Clean build folder
- Rebuild

![screen shot 2017-10-13 at 12 06 15 pm](https://user-images.githubusercontent.com/1271525/31555637-c672ad20-b00f-11e7-8040-dd8702b66d8b.png)

---
#### Internal data
- Associated internal bug: [b/117179678](http://b/117179678)

**Comment by j-nguyen** [comment]
Is there a way to hide these availability warnings?

**Comment by willlarche** [comment]
Yes. In the Pods project, go to Build Settings -> Apple LLVM 9.0 - Warnings - All languages -> Unguarded availability and set it to `No`.

If you, for some reason, are manually passing warning flags, add `-Wno-partial-availability`.

**Comment by ianegordon** [comment]
Add warning guards to MDFInternationalization.
