### ISSUE TITLE
Component tests and example should be required to declare their dependencies

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#218]
Catalog and Testing by convention presently depend on `MaterialComponents` which pulls in every component.

This has the short term benefit of lowering the overhead of writing tests and examples.

In the long term, we want every component's examples and tests to explicitly define their dependencies. This will allow us to pull in outside dependencies and may give us some degree of import enforcement.
## Potential solutions
- Every component has its own Podspec file. If we move the component's specification into a .rb file then our MaterialComponents.podspec file could import each of these. This would have the added advantage of allowing each component to have its own truely-independent `podspec` file that also imports that ruby file. This approach is similar to how we're generating the Icons constellation.

**Comment by ianegordon** [comment]
Closing as obsolete.  😞 
Please open a new bug if this is still an issue.  😄
