### ISSUE TITLE
[TextFields] Motion: error: title missing wiggle, leading underline label missing Y translation

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#2181]
---
#### Internal data
- Associated internal bug: [b/73832824](http://b/73832824)

**Comment by romoore** [comment]
We may want to consider only showing the wiggle if reduceMotion is enabled. [`UIAccessibilityIsReduceMotionEnabled`](https://developer.apple.com/documentation/uikit/1615133-uiaccessibilityisreducemotionena)

**Comment by willlarche** [comment]
+1

**Comment by Andyccs** [comment]
May I know details about this bug? Does it happens when error text is turn on and off using `MDCTextInputControllerDefault`?

**Comment by willlarche** [comment]
Sure! See the guidelines: https://material.io/guidelines/components/text-fields.html#text-fields-field-variations

In the video there (in the text boxes section but applicable to all styles) there are some details of the motion when error is turned on. I've updated the title.

**Comment by willlarche** [comment]
This is still outstanding to my knowledge.

**Comment by material-mirror** [comment]
The internal issue [b/73832824](http://b/73832824) is now closed. This issue is being closed as a result.
