### ISSUE TITLE
[FlexibleHeader] Flaky Test

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#2190]
testFlexibleHeaderViewControllerTopLayoutGuideHeightOffPullDownRelease
Fails iPhone X... sometimes.

There is a UITest failing on the iPhone X (11.0), but working on the iPhone 5s (8.1).

Xcode 9.0 - iPhone X - testFlexibleHeaderViewControllerTopLayoutGuideHeightOffPullDownRelease
UI Test Activity:
Assertion Failure: FlexibleHeaderViewControllerTopLayoutGuideTests.m:183: ((self.vc.fhvc.flexibleHeaderViewControllerHeightOffset) equal to (randomHeight)) failed: ("56") is not equal to ("63")

**Comment by willlarche** [comment]
Duplicate of #2164 but better info so closing that one.

**Comment by chuga** [comment]
Update: I can consistently repro on any device running iOS 11 if the value that the random number generator is bigger than the minimumHeight.
Also, this is not related to our iOS 11/ iPhone X fixes as I can repro with an older version of the flexible header.

Side note: We should never test things using random values.

**Comment by chuga** [comment]
Update2: I can also consistently repro on devices running older iOS versions. It happens whenever the random number we set as the maximum height is bigger than the minimum height. I'm so confused by this test that I don't know how to fix it.

**Comment by ianegordon** [comment]
git blame indicates that @ajsecord may have some insight he said hopefully.
Any reason when we would want to use a random value for the height?

**Comment by ianegordon** [comment]
Closing as obsolete.
