### ISSUE TITLE
[Tabs] MDCTabBar can sometimes misplace image/title

### ISSUE THREAD

**Issue by csilv** [material-components/material-components-ios#2191]
### Overview
We have seen an intermittent bug where MDCTabBar can result in incorrect layout. This seems to affect the selected tab. See example screenshot:

![mdctabbar_bug](https://user-images.githubusercontent.com/50584/31586962-d1bde7b0-b18d-11e7-909e-d99d7d4aca94.png)

### Reproduction steps
Unfortunately I don't currently have reproduction steps. It doesn't occur often, but it does occur. I will keep investigating to see if I can come up with steps. I looked at the layoutSubviews method in MDCItemBarCell.m and nothing jumps out there. I am filing this issue in case others have run into this as well.

### Version number
Last reported against 35.3.0.

### Operating system and device
iOS 10/11.

### Related issues
Related internal issue at b/67730575

---
#### Internal data
- Associated internal bug: [b/117179523](http://b/117179523)

**Comment by willlarche** [comment]
Thank you! Off the top of my head, is the label left or natural aligned? that can be a few pixels.

**Comment by csilv** [comment]
> Off the top of my head, is the label left or natural aligned?

The titles are center aligned. It's more than a few pixels. In the screenshot, the "Sharing" tab is selected on the right. But the title is misplaced a bit to the left and almost at the top of the cell. The icon is also at the top of the cell, we can only see part of the icon since the top is clipped.

**Comment by willlarche** [comment]
Oh, sorry. I couldn't see the sharing one. I thought it was just centering the labels I could see.

**Comment by csilv** [comment]
No worries. I will try to get reproduction steps... or see if I can come up with a patch.

**Comment by willlarche** [comment]
Thank you so much!

**Comment by material-mirror** [comment]
The internal issue [b/117179523](http://b/117179523) is now closed. This issue is being closed as a result.
