### ISSUE TITLE
[Flexible Header] Consider streamlining required glue code

### ISSUE THREAD

**Issue by bhamiltoncx** [material-components/material-components-ios#2198]
The docs at https://github.com/material-components/material-components-ios/blob/fb32dccf2d0e87427d4c792fe811526a985a49e1/components/FlexibleHeader/README.md#objective-c-5 suggest two options for MDCAppBar glue code:

1) Set the UIScrollViewDelegate to the MDCFlexibleHeaderViewController (if you don't need to implement UIScrollViewDelegate methods or methods of a subclass)

2) Implement four delegate methods (-scrollViewDidScroll: and friends) and forward them to the header view: https://gist.github.com/bhamiltoncx/9dd3b2ff127f58a7d7b2dc83da608707

It seems fairly common to use MDCCollectionViewController, which means you can't do 1) above without giving up access to UICollectionViewDelegate methods.

That means you need to write the same boilerplate (https://gist.github.com/bhamiltoncx/9dd3b2ff127f58a7d7b2dc83da608707) for every MDCCollectionViewController which uses a flexible header.

It'd be great to provide a pattern (a macro or similar) to automatically implement these four methods.

**Comment by bosbefok** [comment]
+1

**Comment by jverkoey** [comment]
observesTrackingScrollViewScrollEvents is now available and reduces boilerplate if you do not require shift behaviors.

https://github.com/material-components/material-components-ios/blob/develop/components/FlexibleHeader/src/MDCFlexibleHeaderView.h#L321
