### ISSUE TITLE
[Catalog] AppBar does not have the Collections example as tracking scroll view

### ISSUE THREAD

**Issue by gambard** [material-components/material-components-ios#2209]
### Overview
The AppBar used in the Collections example does not have the collection as tracking scroll view. It creates problems, in particular on iPhone X: when rotating, there is a visible gap between the AppBar and the collection.
Also the shadow is not displayed below the AppBar when scrolling the collection.

![simulator screen shot - iphone x - 2017-10-17 at 17 04 12](https://user-images.githubusercontent.com/1257452/31673093-9a342232-b35e-11e7-815d-db0a0b7345f2.png)

### Reproduction steps
 - Open a Collection example and rotate the device.

### Version number
 - 36.3.0

### Operating system and device
- iPhone X, iOS 11.

**Comment by chuga** [comment]
Related to https://github.com/material-components/material-components-ios/issues/2069
