### ISSUE TITLE
[BottomSheet] UIScrollView.contentInset is ignored

### ISSUE THREAD

**Issue by sigito** [material-components/material-components-ios#2218]
### Overview
Bottom sheet does not take into account `contentInset` of a `UIScrollView` it is presenting.

### Reproduction steps
1. Create a `UICollectionViewController` with some arbitrary content that doesn't take up all the screen.
2. Set `collectionView.contentInsets` to a non-zero value (e.g., `contentInset.top = 100`).
3. Present `MDCBottomSheetController` with a view controller from (1).

Result:
Bottom sheet does not extend to full view height. E.g., for `contentInset.top = 100` the bottom 100 points of the content view are off the screen.

Expected result:
Bottom sheet can be extended to display full presented view.

Example code:
Add to `loadView` in `BottomSheetDummyCollectionViewController`:
```
UIEdgeInsets inset = collectionView.contentInset;
inset.top = 100;
collectionView.contentInset = inset;
```

### Version number
36.3.0

---
#### Internal data
- Associated internal bug: [b/117179543](http://b/117179543)

**Comment by jverkoey** [comment]
@codeman7 I think we've been finding that this works as expected in the action sheet implementation - can you confirm and close if so?

**Comment by material-mirror** [comment]
The internal issue [b/117179543](http://b/117179543) is now closed. This issue is being closed as a result.
