### ISSUE TITLE
[MaskedTransition] Include shadows during transitioning

### ISSUE THREAD

**Issue by codeman7** [material-components/material-components-ios#2219]
**Overview**
Currently, the example has only views with elevation of 0 but if you create a MDCFloatingButton instead of the current UIButton and slow the animation down you can see that the animation masks the view, therefore, cutting off its shadow. 

**Reproduction steps**
1. Change the buttons to MDCFloatingButtons
2. Update MDCMaskedTransiontionMotionSpec duration to 10.xxx instead of 0.xxx so you can better see the transition.
3. Navigate to MaskedTransion in the Catalog
4. Initiate any transition.

*Result*
Flat views during animation then the elevation pops at the end.

*Expected Result*
Maintain elevation during animation.

Also, this may need research but I don't know how you guys want to handle elevation updates should they be during the animation, at the start or at the end. For example, going from a FAB to a Dialog should it slowly rise to 24pt, do it all at the start or all at the end?

---
#### Internal data
- Associated internal bug: [b/117179117](http://b/117179117)

**Comment by jverkoey** [comment]
Hey @codeman7 - would be happy to check out the fix. Can you link to it here?

**Comment by codeman7** [comment]
I have it in Swift. Is it ok if I give you a link to the playground?

**Comment by codeman7** [comment]
@jverkoey I had all the pieces of a working solution in separate places now that I am putting them together I am running into some bugs. I should have it to you by Monday.

**Comment by codeman7** [comment]
https://github.com/codeman7/MaskedAnimation

@jverkoey I still have to fix the timing for the animations and I am having an issue with the shadows, but you can take a look at the overall approach.

**Comment by jverkoey** [comment]
Hey @codeman7 - thanks for exploring this! Do you think it's possible to merge your explorations into the Objective-C implementations? I wager with some of the improvements made to shadow animations recently that it will be much easier to animate the shadow now.

**Comment by codeman7** [comment]
Yeah, I think I can port them over. I am curious if about the approach I am taking and if you think it is appropriate. I think some of the PR should be within Material-Motion. I have added you and @willlarche as contributors to a repo that I would use for the transition but I think that part should possibly be in Material-Motion. It allows an animation curve to be split into multiple curves and the timing each animation would need. For example, the approach I am using on MaskedTransition create a layer then move it to its new point, that would take 100% of the animation timing but I break the shape of the transition into three shapes each would take x% of the animation. Also, I think this would require additions to the Shapes component.

**Comment by material-mirror** [comment]
The internal issue [b/117179117](http://b/117179117) is now closed. This issue is being closed as a result.
