### ISSUE TITLE
[SnackBar] Consider a different layout

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#2224]
We have an internal request to revisit our Snack Bar implementation.

Can we do something more along the lines of what is suggested here:
http://blog.maxrudberg.com/post/165590234593/ui-design-for-iphone-x-bottom-elements

**Comment by willlarche** [comment]
Looks like there are a few designs in there. Which one?

**Comment by ianegordon** [comment]
@samnm Assigning to you as I believe you may have already gotten the ball rolling.  Feel free to unassign if you have nothing to add.

**Comment by ianegordon** [comment]
@willlarche I believe the request was to align our SnackBar presentation with the Banner presentation in the article.

**Comment by samnm** [comment]
I discussed this with design and we have no plans to make any immediate changes to the snackbar. There will inevitably be updates down the line but nothing as of this moment.
