### ISSUE TITLE
[NavigationBar] Bar item with MDCFlatButton has misaligned text and image

### ISSUE THREAD

**Issue by sigito** [material-components/material-components-ios#2230]
### Overview
When `MDCFlatButton` is used as a navigation bar item for `MDCNavigationBar`, its text and images get misaligned.

Example code: #2229.

![MDCNavigationBar with MDCFlatButton as a bar item](https://user-images.githubusercontent.com/1129082/31742112-ea350762-b456-11e7-9c27-27ed81e0fb75.png)

### Version number
36.0.0

---
#### Internal data
- Associated internal bug: [b/117179424](http://b/117179424)

**Comment by sigito** [comment]
This happens because [MDCButtonBar](components/ButtonBar/src/MDCButtonBar.m#L141) aligns the title of a bar item with the bar title if the bar item is a `UIButton`.

While I do not know what is an expected behavior according to Material Spec, but Apple also aligns item text with the title. They also reposition the icon to have the same center as the item text.

**Comment by romoore** [comment]
So do you think that MDCButtonBar (or maybe only within MDCNavBar) should reposition the button images so that their center aligns with the center of the button labels (or possibly text)?

**Comment by sigito** [comment]
I think it is one of the most elegant solutions. However with such change spacing between the icon and the bar bottom would reduce, and I am not sure if it would be an acceptable change.

**Comment by material-mirror** [comment]
The internal issue [b/117179424](http://b/117179424) is now closed. This issue is being closed as a result.
