### ISSUE TITLE
[Chips] Please implement missing Chips MDC spec

### ISSUE THREAD

**Issue by bhamiltoncx** [material-components/material-components-ios#2231]
ROADMAP.md has had Chips listed for a while:

https://github.com/material-components/material-components-ios/blob/develop/ROADMAP.md

They're specced out here:

https://material.io/guidelines/components/chips.html

**Comment by romoore** [comment]
API Review: #2215

**Comment by bhamiltoncx** [comment]
Very timely!

**Comment by bhamiltoncx** [comment]
Thanks, @romoore ! Can we update the roadmap?

https://github.com/material-components/material-components-ios/blob/develop/ROADMAP.md

**Comment by romoore** [comment]
Created #2887 and assigned to @ianegordon . Thanks for reminding us. 👍
