### ISSUE TITLE
[TextFields] TrailingView does not work in RTL

### ISSUE THREAD

**Issue by JessBattrick** [material-components/material-components-ios#2237]
### Overview
The documentation for the MDCTrailingView trailingView property indicates that it will display on the left when in RTL mode.  However, while the trailingView displays properly in LTR mode, when in RTL mode, it doesn't show at all.

It looks like the trailingView property should be updated to check the layout direction, similar to the implementation of the trailingViewMode property.

### Reproduction steps
- Create a view with the trailingView set.  Change language to an RTL language.  The trailingView is not visible.

### Version number
37.0.0

**Comment by JessBattrick** [comment]
iOS 10.  After further investigation, I don't think setting the rightView or leftView depending on the layout will solve it.  In my own testing, I removed the layout checks when setting the trailingViewMode, so that it only set the rightView, and that fixed it.  I'm not sure what other implications that would have for the rest of the implementation though.

**Comment by willlarche** [comment]
Just verified that there is no problem on multi-line.

**Comment by JessBattrick** [comment]
I believe I encountered this issue in an MDCTextField, rather than an MDCMultilineTextField.  I should have clarified before.  Sorry about that.

**Comment by willlarche** [comment]
No no. I understand. Was just documenting that I'm isolating scope. Sorry.

**Comment by willlarche** [comment]
I've also found that if you have both a trailing and leading view, there's no problem. I've updated the kitchen sink to using `.trailingView` and `.leadingView` and this is the result:
![simulator screen shot - iphone 5s - 2017-10-24 at 14 49 49](https://user-images.githubusercontent.com/1271525/31962128-b36e9bf8-b8ca-11e7-99fd-b062a52a8585.png)

**Comment by willlarche** [comment]
Verified the problem is 9+ but below 9, the leading and trailing are not swapped in RTL. That means Apple had not started doing the `.rightView` is really a trailing view thing.

**Comment by willlarche** [comment]
I have verified that the issue is a combination of #2271 and not checking for iOS 8. I have a temporary solution that involves replacing `mdc_effectiveUserInterfaceLayoutDirection` with the standard `userInterfaceLayoutDirection` but I'm hoping I can actually remove the iOS 8 specific code in `UIView+MaterialRTL` that is causing the RTL info to be dropped in the first place. But that affects many components.

**Comment by willlarche** [comment]
Migrating to MDCInternationalization will correct this. Working on a PR now.
