### ISSUE TITLE
[FlexibleHeader] Pre-iOS 11 can result in wrong insets

### ISSUE THREAD

**Issue by csilv** [material-components/material-components-ios#2251]
There is a regression with MDCFlexibleHeader that may affects apps that set minMaxHeightIncludesSafeArea to NO, and are then run on pre iOS 11. The result of this regression is that the top content inset is set incorrectly... it will be 20pt smaller than it should be.

The issue is that after minMaxHeightIncludesSafeArea is set to NO, it is critical that fhv_adjustTrackingScrollViewInsets execute to update the contentInset. On iOS 11, this will generally happen because safeAreaInsetsDidChange will get called which itself calls fhv_adjustTrackingScrollViewInsets. But on pre-iOS 11, this may never happen unless the app changes the maximumHeight to a new value.

A possible solution is to call fhv_adjustTrackingScrollViewInsets from within _minMaxHeightIncludesSafeArea. (I tested this and it appears to resolve the issue.)

For now, I am working around the issue by setting the maximumHeight to the default value + 1, and then immediately setting it back to the default value. This is enough to ensure that fhv_adjustTrackingScrollViewInsets gets executed.

**Comment by chuga** [comment]
Thanks for reporting @csilv. @jverkoey is currently writing some of the internals of the flexible header to prevent it from shrinking when something else hides the status bar. This might be also fixing the bug you're describing, would you mind giving https://github.com/material-components/material-components-ios/pull/2263 a go and reporting back?

**Comment by chuga** [comment]
I tried reproing this in our catalog by changing setting minMaxHeightIncludesSafeArea to NO in MDCNodeListViewController, and I'm not seeing what you're describing. Do I need to set some custom min/max height as well?

**Comment by chuga** [comment]
Ping

**Comment by csilv** [comment]
Hello Andrés,

Sorry for taking so long to respond. I have re-tested this issue, and can confirm that #2263 appears to resolve the issue I reported. I have been able to successfully remove the work-around I had put in place.

Therefore, closing this issue. Thank you for your patience!
