### ISSUE TITLE
[TextFields] Placeholder over multiple lines

### ISSUE THREAD

**Issue by jprossardalia** [material-components/material-components-ios#2268]
In MDCTextField if the placeholder text is large then it is word wrapping with '...'
Is there a way to make the placeholder text multiline.

![simulator screen shot - ipad pro 9 7 inch - 2017-10-25 at 10 54 10](https://user-images.githubusercontent.com/22931369/31982073-54f09e14-b974-11e7-8286-0056932bef05.png)

Version number
31.0.0

Operating system and device
iOS 9.3.5 and iPad

---
#### Internal data
- Associated internal bug: [b/117179582](http://b/117179582)

**Comment by willlarche** [comment]
Hi! That’s a great feature request. Are these multi-line TextFields? If so,
that’s not too hard to add. If not, that would be very difficult since it
change the height.

**Comment by sigito** [comment]
I guess it is related to #2115.

**Comment by jprossardalia** [comment]
Hi, These are not multi-line TextFields. Also I only want to the change the placeholder label multi-line not the textfield text.

**Comment by willlarche** [comment]
A shoot. That would have been easier. I will submit this to the Material Design Committee and see if they can green light it. Then we can discuss solutions!

**Comment by willlarche** [comment]
The designers didn't approve multi-line placeholders on single-line text fields. 

We will keep this open to represent adding multi-line placeholders to multi-line text fields tho.

**Comment by material-mirror** [comment]
The internal issue [b/117179582](http://b/117179582) is now closed. This issue is being closed as a result.
