### ISSUE TITLE
[Snackbar] Feature request: auto-shrink font to avoid truncation

### ISSUE THREAD

**Issue by MEnnabah** [material-components/material-components-ios#2270]
### Overview

Is there any API to autofit the text so there is no "..." at the end?

![simulator screen shot - iphone x - 2017-10-25 at 16 52 08](https://user-images.githubusercontent.com/16809714/32005668-248480d4-b9a5-11e7-8a5e-d53bc26b5a3c.png)

**Comment by MEnnabah** [comment]
Can I contribute and submit a PR with this feature request? @willlarche

**Comment by willlarche** [comment]
@samnm is the owner. He can answer.

**Comment by samnm** [comment]
Hi @MEnnabah, this is an intentional constraint of Snackbars. If you need to show text longer than two lines I would recommend considering a different approach. Maybe an alert or a label embedded in your UI.
