### ISSUE TITLE
[TextField] Character count is not updated when the user taps the "clear" button

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#2276]
![xcount](https://user-images.githubusercontent.com/45670/32023757-47d0cea0-b9a8-11e7-810b-533d2595d03d.gif)

Repro:

1. Type content into a text field.
2. Tap the "clear" button.

Expected behavior: the character count resets to zero.
Actual behavior: the character count remains at its previous value.

**Comment by willlarche** [comment]
Related to previous PR #2143.

**Comment by willlarche** [comment]
Regression introduced in #2206.

```
  if (!self.isFirstResponder) {
    [[NSNotificationCenter defaultCenter]
        postNotificationName:MDCTextFieldTextDidSetTextNotification
                      object:self];
  }
```
