### ISSUE TITLE
[Tabs] Fix RTL weirdness on the iPhone X

### ISSUE THREAD

**Issue by chuga** [material-components/material-components-ios#2303]
The collection view is only respecting the adjusted content inset when it wants to. This can be reproduced with a vanilla UICollectionViewFlowLayout as well.

**Comment by ianegordon** [comment]
We are not intending on any significant updates to the current Collections component. 😞
We are working on a much simpler [List component](https://github.com/material-components/material-components-ios/tree/develop/components/List). 😄
