### ISSUE TITLE
[Collections] Header cells' background is displayed above the scroll indicator on iPhone X

### ISSUE THREAD

**Issue by gambard** [material-components/material-components-ios#2309]
### Overview
When the iPhone X is in landscape, the scroll indicator is displayed above the cells but below the header, creating a weird effect.
It should be above all of them.

![simulator screen shot - iphone x - 2017-10-31 at 09 44 45](https://user-images.githubusercontent.com/1257452/32214840-69afb802-be20-11e7-9a02-c7bc93811e6f.png)

### Reproduction steps
 - Open the Catalog>Collections>Header/Footer Demo
 - Rotate to landscape
 - Scroll up to the point where the scroll indicator pass below a header

### Version number
 - 38.0.1

### Operating system and device
 - iOS 11
 - iPhone X

**Comment by chuga** [comment]
This appears to be an iOS 11 bug https://stackoverflow.com/questions/46694144/scrollbar-incorrectly-appears-underneath-uicollectionview-section-header
