### ISSUE TITLE
[TextFields] Placeholder does not stop floating when text set to nil from dequeued view

### ISSUE THREAD

**Issue by jprossardalia** [material-components/material-components-ios#2310]
When using the MDCTextField in a cell for tableview (added from storyboard) and the textField have some text , the placeholder label position is not coming correctly for MDCTextFields .

I'm attaching a demo project replicating the issue. Here initially the position of the placeholder label is coming correctly but after scrolling down and up we can see the position of the placeholder label is shifted towards top left. 

[MDCTextFieldTest.zip](https://github.com/material-components/material-components-ios/files/1430250/MDCTextFieldTest.zip)

Screenshot 1:
![simulator screen shot - iphone 7 - 2017-10-31 at 15 25 51](https://user-images.githubusercontent.com/22931369/32218095-d87f95de-be4f-11e7-8316-bc7dca9554d2.png)

Screenshot 2:
![simulator screen shot - iphone 7 - 2017-10-31 at 15 25 59](https://user-images.githubusercontent.com/22931369/32218096-d8d137ae-be4f-11e7-94cd-8de89c83abfd.png)

Version number
31.0.1 & 38.0.1

**Comment by willlarche** [comment]
Thanks for the issue! I'm guessing this has to be related to the fact that it's dequeued. We can would on better support for that.

**Comment by willlarche** [comment]
Probably related to #2298 .

**Comment by willlarche** [comment]
@jprossardalia  Can you verify if this is still an issue? There was some recent work around this area.

**Comment by jprossardalia** [comment]
@willlarche Yes it is still an issue. I updated the pod to 40.0.2 version and still getting the same problem

**Comment by jprossardalia** [comment]
Any progress regarding this issues ?

**Comment by willlarche** [comment]
No but I can make it a priority next week.

**Comment by willlarche** [comment]
Work is very busy right now as I/O is two weeks away. I wouldn't expect any completion of this until after then. So May 14+

**Comment by jprossardalia** [comment]
ok

**Comment by vikt0r40** [comment]
This issue is still up, is it going to be fixed soon or any work around to fix it temporary ?

**Comment by willlarche** [comment]
Took a stab at this today. I can't reproduce. Here's how I'm handling my cells:

``` objective-c
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
  UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:TextFieldTableViewCellIdentifier];
  if ([cell isKindOfClass:[TextFieldTableViewCell class]]) {
    TextFieldTableViewCell *textFieldCell = (TextFieldTableViewCell*)cell;

    textFieldCell.textField.tag = indexPath.row;
    textFieldCell.textField.delegate = self;

    if (indexPath.row < (NSInteger)self.strings.count) {
      NSString *string = self.strings[indexPath.row];
      if (string.length) {
        textFieldCell.textFieldController.textInput.text = string;
      } else {
        textFieldCell.textFieldController.textInput.text = nil;
      }
    }
    textFieldCell.textFieldController.placeholderText = [NSString stringWithFormat:@"TextField #%lu", indexPath.row];
  }

  return cell;
}
```

Please check how you're handling the text against how I did and write back with what the difference is.

**Comment by vikt0r40** [comment]
Hi again @willlarche , 

This code did the trick, now it is not reproducing it was my mistake, thank you !

**Comment by willlarche** [comment]
Great! Could you explain what was different?

**Comment by jprossardalia** [comment]
Hi @willlarche,
I looked through the code and it did the trick. The difference was in my case I was initializing the textFieldController every time when cellForRowAtIndexPath was being called. When I shifted it to awakeFromNib in the cellViewController it fixed the issue.

**Comment by willlarche** [comment]
Thank you!
