### ISSUE TITLE
[Tabs] MDCTabBarViewController should provide its entire bounds to child View Controllers

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#2311]
### Overview
To provide as much functional parity between `MDCTabBarViewController` and `UITabBarController`, the child view controller should receive the TabBar VC's entire bounds as its frame. This would provide the following benefits:
* Match the behavior of `UITabBarController` and make drop-in replacement easier.
* Allow for translucency effects to reveal color/shape information about the view behind the tabs. For example, a table or collection view that happens to align a row right at the top of the tabs might appear to have no additional scrollable content.
* Permit the child view controller to decide how to reposition its content relative to the safe area on iOS 11+.

#### MDCTabBarViewController (subclass)
The purple (?) view is the child VC's view.
![screen shot 2017-10-31 at 8 55 13 am](https://user-images.githubusercontent.com/1753199/32224970-d0d92a24-be19-11e7-9ab2-d322b720f39a.png)

#### UITabBarcontroller
The white view is the child VC's view.
![screen shot 2017-10-31 at 8 54 25 am](https://user-images.githubusercontent.com/1753199/32224980-d88d49bc-be19-11e7-82cd-5f8f9a3395cb.png)

### Version number
37.0.0

### Operating system and device
Any/all

---
#### Internal data
- Associated internal bug: [b/117179324](http://b/117179324)

**Comment by material-mirror** [comment]
The internal issue [b/117179324](http://b/117179324) is now closed. This issue is being closed as a result.
