### ISSUE TITLE
[Dialogs] Recent iPhone X changes broke maximum width enforcement

### ISSUE THREAD

**Issue by ajsecord** [material-components/material-components-ios#2314]
From internal issue:

> The documentation for `[MDCDialogPresentationController sizeForChildContentContainer:withParentContainerSize:]` claims:

```
/**
 Returns the size of the specified child view controller's content.

 The size is initially based on container.preferredSize. Width is will have a minimum of 280 and a
 maximum of the parentSize - 40 for the padding on the left and right size.

 Height has no minimum.  Height has a maximum of the parentSize - height of any displayed
 keyboards - 48 for the padding on the top and bottom.  If preferredSize.height is 0, height will
 be set to the maximum.
 */
```
>
> However, in the latest revision the code no longer enforces a maximum width for the dialog: https://github.com/material-components/material-components-ios/blob/2d8a51e5d5d473d0753929133d54c7cbccc34eb1/components/Dialogs/src/MDCDialogPresentationController.m#L79
>
> This broke our dialog sizing as we were relying on this method. I'm not sure why this change was made, but at the very least the comments in the header should be amended.

I think this is a regression that should be fixed, unless safe area handling specifically usurps the maximum width?

**Comment by ianegordon** [comment]
The maximum width is the width of self.containerView inset by the greater of the Material Specs and safeAreaInsets.

Can you attach the original bug or add some repro steps?

Tested by setting our samples to request a preferred width of 800 which was rightfully shrunk to our container width - insets.

**Comment by ianegordon** [comment]
Closing as Unable to repro.
Please re-open if there are steps or a source bug we can investigate.
