### ISSUE TITLE
[Collections] MDCCollectionViewController while editing - Delete Action Bar Strange Behaviour

### ISSUE THREAD

**Issue by muzoman** [material-components/material-components-ios#2319]
I've just implemented a Collection using this class using the example Swift code and have observed strange behaviour I can't explain:

1) Once edit mode is entered and a row is selected the Delete Action Bar is not visible unless you scroll the collection and then it appears.

2) If you select 2 rows there's no Delete Action Bar but if you then unselect 1 row it appears correctly.

Version 38.0.1

Any thoughts?

**Comment by chuga** [comment]
Hi Jim, I see this working as expected in our Cell Editing Example in the catalog (at least on iOS 11 / iPhone X). This example is not in Swift, but if you haven't already I'd suggest taking a look and confirming that you did set up everything correctly. If that doesn't help, can you upload a demo app that shows this bug?

**Comment by chuga** [comment]
Ping

**Comment by muzoman** [comment]
Hi there,
Sorry for the delay in following this up. I've identified the problem -  in my override of didSelectItemAt I was not calling super.collectionView(collectionView, didSelectItemAt: indexPath). If you DONT call this then the strange behaviour occurs as I originally described. If you DO call this at the start of your override then all is well.

**Comment by chuga** [comment]
Thanks for the update Jim, it sounds like we can close this issue. Cheers.
