### ISSUE TITLE
Add a "take a screenshot" button to the Catalog's "exit demo" bar

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#233]
As seen in the screenshot below, we'll be introducing some form of chrome around each of our demos. This Chrome could be extended to provide some valuable feature for documentation purposes.

One such feature could be "take a screenshot". Touching the button could hide all of the chrome for the demo (status bar, catalog bar) until a hardware screenshot has been taken (listen for `UIApplicationUserDidTakeScreenshotNotification` to know when this happens). Once the screenshot has been taken we can re-show the chrome.

![simulator screen shot mar 28 2016 3 30 59 pm](https://cloud.githubusercontent.com/assets/45670/14088399/4c69a7dc-f4fd-11e5-96d3-1d4868b73823.png)

**Comment by ianegordon** [comment]
Opened more than two years ago.
Please re-open if you feel strongly.
