### ISSUE TITLE
[Math] Document the implementation of MDCCGFloatEqual

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#2333]
What's going on here?

```
static inline bool MDCCGFloatEqual(CGFloat a, CGFloat b) {
  const CGFloat constantK = 3;
#if CGFLOAT_IS_DOUBLE
  const CGFloat epsilon = DBL_EPSILON;
  const CGFloat min = DBL_MIN;
#else
  const CGFloat epsilon = FLT_EPSILON;
  const CGFloat min = FLT_MIN;
#endif
  return (MDCFabs(a - b) < constantK * epsilon * MDCFabs(a + b) || MDCFabs(a - b) < min);
}
```

---
#### Internal data
- Associated internal bug: [b/117179096](http://b/117179096)

**Comment by romoore** [comment]
A relevant link (found by @willlarche).
https://www.jessesquires.com/blog/floating-point-swift-ulp-and-epsilon

**Comment by ianegordon** [comment]
Good question.  I suspect that was C&P from our internal implementation (which has no linked documentation).  I will assign to our resident mathematical mind in the hopes of insight.
@ajsecord ?

**Comment by material-mirror** [comment]
The internal issue [b/117179096](http://b/117179096) is now closed. This issue is being closed as a result.
