### ISSUE TITLE
[Math] Explore whether tgmath.h can replace the need for most of MDCMath.h

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#2347]
---
#### Internal data
- Associated internal bug: [b/117179581](http://b/117179581)

**Comment by ianegordon** [comment]
Per b/26069185 ~two years ago:
"tgmath is currently broken on iOS when modules are enabled."

If this is no longer the case, it would be great to drop much of MDCMath in favor of tgmath.

**Comment by material-mirror** [comment]
The internal issue [b/117179581](http://b/117179581) is now closed. This issue is being closed as a result.
