### ISSUE TITLE
[Release] Update the weight in the FAQ when it changes

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#2382]
We have a weight for the library that's stuck at 5.3MB and an average of .2MB per component.

**Comment by romoore** [comment]
I did a quick measurement (which includes duplicate dependencies) and it looks like we're currently around 5 MB added to an `.ipa` if all components are included. 

Mean component size is 200 kB.
Median component size is 139 kB.

I'm putting together an internal target that will depend on every library and roll them into a single application for measurement. That should eliminate duplicate dependencies between libraries.

The table below are individual component sizes and include some duplicated dependencies.

|Component|Size (KiB)|
|----------|------------:|
ActivityIndicator|119
AnimationTiming|	9
AppBar	|476
BottomAppBar|	387
ButtonBar	|292
Buttons	|261
Collections|	497
Dialogs	|330
FeatureHighlight|	158
FlexibleHeader	|139
HeaderStackView	|10
Ink	|83
NavigationBar|	340
OverlayWindow|	21
PageControl	|60
Palettes	|55
ProgressView|	37
ShadowElevations|	4
ShadowLayer	|26
Slider	|253
Snackbar|	426
Tabs	|360
TextFields|	590
Themes	|26
Typography|	50

**Comment by romoore** [comment]
Based on internal measurements this morning on both x86_64 and arm64 platforms, it looks like including all of MDC-iOS will add around 2,130 KiB to an application. This excludes any required system frameworks like UIKit or QuartzCore.

**Comment by romoore** [comment]
I did another test using a generic Xcode project to which I added the MaterialComponents pod and installed onto my iPad Mini 4. I configured the project to strip symbols on copy and use DWARF + DSYM for both Release and Debug builds. 

|Application | Installed Size (iOS Reported) | App Size | Documents & Data|
|--|--:|-:|-:|
Bare Tabbed App | 1.1 MB | 1.0 MB | 61 KB|
With MaterialComponents | 3.9 MB | 3.8 MB | 61 KB|

**Comment by willlarche** [comment]
Awesome. I think we can also be pretty proud of that.

**Comment by ianegordon** [comment]
I'm glad our numbers are decent, but I'm concerned this will be difficult to track update.  Also, based on app-thinning, I expect our added size will change based on device.
Can we remove this question from our FAQ?  Should we add a step to our release playbook to update this number?  (If so, perhaps @romoore could document the process so we have a standard way to calculate?)

**Comment by willlarche** [comment]
Alastair was sure we needed this number somewhere since over the air apps, etc.

We could simplify it with an "about" like "The entire library is less that 6MB."

**Comment by ajsecord** [comment]
It's an important consideration for clients considering taking on our library as a dependency, at least for apps who are serious about their download sizes. I agree with Will, something like "A typical component adds ~140 kB and including every component adds less than 6 MB to your app." would be a reasonable tradeoff between precision and having to update the statement every release.

**Comment by romoore** [comment]
I like Adrian's phrasing, and we can update the documentation whenever the size changes measurably. Now that we have size measurements in place internally, we can at least keep track of relative increases. 

As documented above, installing a build via Xcode to a specific device resulted in a 2.8MB increase in on-device storage. The installation package is measured at around 2.1Mb. Both numbers generally agree if the .IPA is compressed and after installation portions (or all) are decompressed.

Would app thinning make a difference for these builds that targeted only a single architecture? I noticed a "generic" archive via Xcode resulted in a an uncompressed binary around 6MB, which would make sense if it had to support 64- and 32-bit ARM platforms.

**Comment by willlarche** [comment]
I think it would make a difference. Which is so hard to say. But we could
say “before app thinning / bit code”.

**Comment by romoore** [comment]
Aside from the internal measurements, the way I measured was pretty primitive:

1. Create a new Xcode Tabbed Application from the built-in template
1. Change the project Build Settings to:
    * Change "Debug Information Format" to "DWARF with dSYM File" for both Release and Debug
    * Change "Strip Debug Symbols During Copy" to "YES" for both Release and Debug
    * Change "Strip Linked Product" to "YES" for both Release and Debug
1. Install the project to an ARM64 device (I used an iPad Mini 4 on iOS 10.3.2)
1. After install, open the Settings app.
    * Navigate to "General" &rarr; "Storage & iCloud Usage" &rarr; "Manage Storage" under "Storage" &rarr; Find the installed test app and note the "App Size" and "Documents & Data" size
1. In the created project directory initialize CocoaPods with `pod init`
1. Edit the Podfile to include `pod MaterialComponents`
1. Run `pod install` to create the Xcode workspace. Open the workspace
1. Install the project to an ARM64 device
1. After install, open the Settings app.
    * Navigate to "General" &rarr; "Storage & iCloud Usage" &rarr; "Manage Storage" under "Storage" &rarr; Find the installed test app and note the "App Size" and "Documents & Data" size

The estimated size of our library is the difference between the two installed app sizes. "Documents & Data" should be identical, but "App Size" will differ based on the binary size.
