### ISSUE TITLE
Step-sequence doesn't render ideally on GitHub

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#240]
I recently attempted to apply the nice home page list style to the App Bar's 4-step setup sequence: http://codereview.cc/D396

![screen shot 2016-03-28 at 8 07 08 pm](https://cloud.githubusercontent.com/assets/45670/14094373/a2fa7cfe-f523-11e5-90a3-78ecee161ff4.png)

Sadly it appears that this method of formatting the list doesn't render as expected on GitHub:

https://github.com/jverkoey/material-components-ios/tree/pretty/components/AppBar

**Comment by ianegordon** [comment]
Obsolete.
