### ISSUE TITLE
[AppBar] Multiple UIBarButtonItems take a lot of horizontal space

### ISSUE THREAD

**Issue by seriyvolk83** [material-components/material-components-ios#2402]
### Overview

let appBar = MDCAppBar()
...
navigationItem.rightBarButtonItems = [moreItem, searchItem, filterItem]

3 buttons take more than a half of the screen width.

Solution - UIBarButtonItem(customView: view) where view has fixed size.
Other UIBarButtonItem initializers produce the mentioned issue.

### Reproduction steps
 - see code above

### Operating system and device
 - iPhone

---
#### Internal data
- Associated internal bug: [b/117179403](http://b/117179403)

**Comment by jverkoey** [comment]
This is technically working as intended, but I understand that it would be preferable if there were more control over the button sizes, so I've marked this issue as a feature request.

**Comment by material-mirror** [comment]
The internal issue [b/117179403](http://b/117179403) is now closed. This issue is being closed as a result.
