### ISSUE TITLE
[BottomSheet] Implement unit test verifying gesture recognizer cancellation behavior

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#2405]
From @romoore:

> I think it would be a good improvement to provide a unit test for the cancellation behavior. The test should ensure that this behavior will call touchesCancelled:withEvent:.

---
#### Internal data
- Associated internal bug: [b/117179541](http://b/117179541)

**Comment by material-mirror** [comment]
The internal issue [b/117179541](http://b/117179541) is now closed. This issue is being closed as a result.
