### ISSUE TITLE
[Documentation]: iOS Swift tutorial doesn’t build

### ISSUE THREAD

**Issue by swashcap** [material-components/material-components-ios#2413]
### Overview

I'm following along with the [iOS Tutorial](https://material.io/components/ios/docs/tutorial/). The [“Add a app-bar button” section](https://material.io/components/ios/docs/tutorial/#6--add-a-button-to-the-app-bar) displays Swift code that won't compile:

```swift
class ViewController: MDCCollectionViewController {
  override func viewDidLoad() {
    // ...
    navigationItem.rightBarButtonItem = UIBarButtonItem(title: "Edit",
                                                        style: .plain,
                                                        target: self,
                                                        action: #selector(ViewController.barButtonDidTap(_:)))
  }

  // ...
  func barButtonDidTap(sender: UIBarButtonItem) {
    editor.isEditing = !editor.isEditing

    let buttonTitle =  editor.isEditing ? "Cancel" : "Edit"
    navigationItem.rightBarButtonItem = UIBarButtonItem(title: buttonTitle,
                                                        style: .plain,
                                                        target: self,
                                                        action: #selector(ViewController.barButtonDidTap(_:)))
  }
}
```

### Reproduction steps

See snapshot at https://github.com/swashcap/MDC-Tutorial/blob/8b6a994f1bc4b31f6cc8e0af00a66733101c9918/MDC-Tutorial/ViewController.swift

### Version number
 
n/a

### Operating system and device

OS: macOS 10.12.6
Xcode: 8.3.3
Swift: 3

### Related issues

n/a

**Comment by swashcap** [comment]
Looks like there’s a view more `ViewController.<method>(_:)` calls in the remainder of the tutorial. I [copied the full source (diff)](https://github.com/swashcap/MDC-Tutorial/commit/bac38cb0a1d1886afa1a879ebb75d5652a16082c) into my project. Errors!

![wat](https://user-images.githubusercontent.com/1858316/32744786-8d2e9dc6-c865-11e7-8781-6dc33adb50b3.jpg)

Any thoughts?

**Comment by willlarche** [comment]
It would be great if you could put in PRs to fix these!

**Comment by swashcap** [comment]
Looks like the problem lies in the `ViewController#fabDidTap` and `ViewController#barButtonDidTap` function definitions. [Swift uses `_`](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Functions.html#//apple_ref/doc/uid/TP40014097-CH10-ID166) as a placeholder for unnamed function parameters. [This StackOverflow](https://stackoverflow.com/a/30876295) has a fix; I’ll apply it to the PR.
