### ISSUE TITLE
MDCCatalog crashing when trying to display ButtonsStoryboardAndProgrammatic

### ISSUE THREAD

**Issue by DonnaLea** [material-components/material-components-ios#2425]
### Overview
MDCCatalog crashes when trying to display ButtonsSwiftAndStoryboardController. The initial class from the ButtonsStoryboardAndProgrammatic.storyboard is extracted as _TtC25MaterialComponentsCatalog35ButtonsSwiftAndStoryboardController and can't be found and thus a plain UIViewController is loaded, resulting in IBOutlets not being found and crashing due to it not being key value coding-compliant. 

This is the output and stack trace:
2017-11-14 13:46:33.208207-0800 MDCCatalog[70805:2576278] Unknown class _TtC25MaterialComponentsCatalog35ButtonsSwiftAndStoryboardController in Interface Builder file.
2017-11-14 13:46:33.240855-0800 MDCCatalog[70805:2576278] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UIViewController 0x7fc5e3f88d80> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key storyboardFlat.'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000109a581ab __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00000001090f5f41 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000109a580f9 -[NSException raise] + 9
	3   Foundation                          0x0000000108b181e3 -[NSObject(NSKeyValueCoding) setValue:forKey:] + 292
	4   UIKit                               0x000000010a781777 -[UIViewController setValue:forKey:] + 87
	5   UIKit                               0x000000010aa70cb1 -[UIRuntimeOutletConnection connect] + 109
	6   CoreFoundation                      0x00000001099fb4fd -[NSArray makeObjectsPerformSelector:] + 317
	7   UIKit                               0x000000010aa6f667 -[UINib instantiateWithOwner:options:] + 1856
	8   UIKit                               0x000000010a788838 -[UIViewController _loadViewFromNibNamed:bundle:] + 383
	9   UIKit                               0x000000010a789164 -[UIViewController loadView] + 177
	10  UIKit                               0x000000010a789495 -[UIViewController loadViewIfRequired] + 195
	11  UIKit                               0x000000010a789cf2 -[UIViewController view] + 27
	12  MDCCatalog                          0x0000000107cfc812 _T010MDCCatalog25MDCNodeListViewControllerC05tableD0ySo07UITableD0C_10Foundation9IndexPathV14didSelectRowAttF + 5106
	13  MDCCatalog                          0x0000000107cfd86c _T010MDCCatalog25MDCNodeListViewControllerC05tableD0ySo07UITableD0C_10Foundation9IndexPathV14didSelectRowAttFTo + 92
	14  UIKit                               0x000000010a725487 -[UITableView _selectRowAtIndexPath:animated:scrollPosition:notifyDelegate:] + 1810
	15  UIKit                               0x000000010a7256a2 -[UITableView _userSelectRowAtPendingSelectionIndexPath:] + 344
	16  UIKit                               0x000000010a5f0625 _runAfterCACommitDeferredBlocks + 318
	17  UIKit                               0x000000010a5debc5 _cleanUpAfterCAFlushAndRunDeferredBlocks + 280
	18  UIKit                               0x000000010a60ec1c _afterCACommitHandler + 137
	19  CoreFoundation                      0x00000001099fad37 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	20  CoreFoundation                      0x00000001099fac8e __CFRunLoopDoObservers + 430
	21  CoreFoundation                      0x00000001099df254 __CFRunLoopRun + 1572
	22  CoreFoundation                      0x00000001099de9b9 CFRunLoopRunSpecific + 409
	23  GraphicsServices                    0x000000010f9e49c6 GSEventRunModal + 62
	24  UIKit                               0x000000010a5e45e8 UIApplicationMain + 159
	25  MDCCatalog                          0x0000000107d079a7 main + 55
	26  libdyld.dylib                       0x000000010e3a8d81 start + 1
	27  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

### Reproduction steps
Run MDCCatalog, scroll and tap Buttons, tap Buttons (Swift and Storyboard)

### Version number
39.0.0

### Operating system and device
iPhone 8 Simulator, tested with iOS 8.0 and 11.1

**Comment by romoore** [comment]
Looks like the storyboard was assigned incorrectly to the "catalog" module.

**Comment by romoore** [comment]
Thanks for the bug report, @DonnaLea! It should be fixed in develop later today.
