### ISSUE TITLE
DatePicker!

### ISSUE THREAD

**Issue by SagarUnagar** [material-components/material-components-ios#2446]
Hello,

Does DatePicker implemented? Where I can find it? I want to add DatePicker in my app. I'm already using other components.

Thanks in advance!

**Comment by willlarche** [comment]
Hi, @SagarUnagar ! We already have a ticket open tracking this issue. But you should know it's a rather low priority at the moment. There are details in there about what would be involved in contributing one.

#1536 

Closing as Duplicate.
