### ISSUE TITLE
Disable travis for pull requests

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#2461]
Must verify that:

- [ ] we are testing against the same matrix of simulators that travis.yml is.
- [x] we're testing against the same matrix of Xcode versions that travis is. This is blocked by internal support for Xcode 8.3.3 and Xcode 9.
- [x] code coverage can be generated from kokoro cocoapods builds. https://github.com/material-components/material-components-ios/pull/2459
- [x] we are testing against the same matrix of architectures that travis.yml is. https://github.com/material-components/material-components-ios/pull/2458

**Comment by jverkoey** [comment]
Xcode 8.3.3 and 9.0/9.1 are now available on kokoro.

**Comment by ianegordon** [comment]
Can we test against 9.0 / 9.1 externally?
Can we test against 9.2?

**Comment by jverkoey** [comment]
Yep - once kokoro deploys those instances.

**Comment by ianegordon** [comment]
Excellent!  I'll leave as blocked until the deployment happens.
👍
