### ISSUE TITLE
[ProgressView] Visual jump when the progress view re-appears.

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#2462]
Repro:

1. Open the catalog.
2. Visit the progress view demo.
3. Watch the progress views.

Expected behavior: the progress views hide and reappear.
Actual behavior: the progress views reappear but flicker their progress from 50% to 0%.

This may be a bug in the catalog example rather than the progress view itself.

---
#### Internal data
- Associated internal bug: [b/117179580](http://b/117179580)

**Comment by jverkoey** [comment]
May be related to https://github.com/material-components/material-components-ios/issues/2846

**Comment by material-mirror** [comment]
The internal issue [b/117179580](http://b/117179580) is now closed. This issue is being closed as a result.
