### ISSUE TITLE
[TextFields] `-Default` is misleading and should be renamed

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#2499]
`MDCTextInputControllerDefault`'s name is left over from previous API. It should be renamed `-Underline`. 

To avoid all the other floating placeholder controllers having to subclass something with that name, its functionality should be moved to a class `private/MDCTextInputControllerBaseFloatingPlaceholder` and leaves `-Underline` with just styling info like `-Filled` does already.

**Comment by mohammadcazig** [comment]
Already Done.
