### ISSUE TITLE
[FeatureHighlight] Document MDCFeatureHighlightView

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#2502]
`MDCFeatureHighlightView` has no public API documentation and seemingly no public usage. Can we make it private? If not, its public APIs need to be documented.

---
#### Internal data
- Associated internal bug: [b/117179095](http://b/117179095)

**Comment by ianegordon** [comment]
We need the properties exposed for UIAppearance, so documentation is the way.

**Comment by ianegordon** [comment]
We are not intending on any significant work on UIAppearance support.
Closing as obsolete.  😞 
Please open a new bug if this is still an issue.  😄

**Comment by material-mirror** [comment]
The internal issue [b/117179095](http://b/117179095) is now closed. This issue is being closed as a result.
