### ISSUE TITLE
FlexibleHeader navigationBar iOS 9 & 10

### ISSUE THREAD

**Issue by josmanperez** [material-components/material-components-ios#2512]
Hello!,

I've been struggling for the past two days with this extrange behaviour that is happening in my app with the **FlexibleHeader** and the navigationBar items when targering iOS 9 & iOS 10.

This is the view for the FlexibleHeader in a iPhone 6s with iOS 11

![screen shot 2017-11-23 at 13 18 46](https://user-images.githubusercontent.com/5773453/33172535-e1b282a2-d050-11e7-8745-13db4c43e519.png)

As you see this is the expected behaviour

But when seeing the same app on an iPhone 6s but with iOS 9 or iOS 10 this is what I got:

![screen shot 2017-11-23 at 13 17 59](https://user-images.githubusercontent.com/5773453/33172520-cd3c6eb4-d050-11e7-99d9-2733b5ab3756.png)

I don't know why this is happening? maybe something with the safe areas? (I'm using the top and bottom layout) my app target iOS 9 and above..

This is the code I'm using for creating the Flexible header plus the navigation bar:

        headerViewController.view.frame = view.bounds
        let headerView = headerViewController.headerView
        
        //añadir imagen de fondo
        let imageView = UIImageView(image: UIImage(named:"cabecera_curso_detalle"))
        imageView.frame = headerView.bounds
        imageView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        headerView.insertSubview(imageView, at: 0)
        imageView.contentMode = .scaleAspectFill
        imageView.clipsToBounds = true
        
        // Creamos una vista para oscurecerla
        backgroundOverlayView = UIView(frame: imageView.frame)
        titleBackgroundOverlay = detailContentView.courseTitle.clone() as? UILabel
        if let backgroundOverlayView = self.backgroundOverlayView {
            backgroundOverlayView.alpha = 0
            backgroundOverlayView.backgroundColor = appFacade.appColor
            backgroundOverlayView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
            headerView.insertSubview(backgroundOverlayView, at: 1)
            backgroundOverlayView.contentMode = .scaleAspectFit
            backgroundOverlayView.clipsToBounds = true
        }
        
        //Al principio la altura minima es la máxima para que aparezca la cabecera abierta y en el viewdidappear se cambia
        if UIDevice.current.userInterfaceIdiom == .pad {
            headerView.maximumHeight = kFlexibleHeaderMaxHeightPad
        } else {
            headerView.maximumHeight = kFlexibleHeaderMaxHeightPhone
        }
        headerView.minimumHeight = kFlexibleHeaderMinHeight
        
        //Añadir navbar
        let navBarFrame = CGRect(x: 0, y: 20, width: headerView.frame.size.width, height: 60)
        let navBar = UINavigationBar(frame: navBarFrame)
        navBar.setBackgroundImage(UIImage(), for: UIBarMetrics.default)
        navBar.shadowImage = UIImage()
        navBar.isTranslucent = true
        navBar.autoresizingMask = UIViewAutoresizing.flexibleWidth
        navBar.tintColor = UIColor.white
        navBar.backgroundColor = UIColor.clear
        
        headerView.addSubview(navBar)
        
        // Añadir el titulo en el nav Bar
        if let backgroundOverlayView = self.backgroundOverlayView, let label = titleBackgroundOverlay {
            label.translatesAutoresizingMaskIntoConstraints = false
            label.textColor = UIColor.white
            label.font = UIFont(name: "HelveticaNeue-Light", size: 18)!
            backgroundOverlayView.addSubview(label)
            NSLayoutConstraint.activate([
                label.leadingAnchor.constraint(equalTo: navBar.leadingAnchor, constant: 54),
                label.trailingAnchor.constraint(equalTo: navBar.trailingAnchor, constant: -54),
                label.centerYAnchor.constraint(equalTo: navBar.centerYAnchor, constant: -10)
            ])
        }
        
        
        //Añadir botones del navbar
        var navItems : [UINavigationItem] = []
        
        let backItem = UIBarButtonItem(image: UIImage(named: "arrow_left"), style: .plain, target: self, action: #selector(backButton))
        let navItemLeft = UINavigationItem()
        navItemLeft.leftBarButtonItem = backItem
        
       
        if let c = course, c.hasCommunity() {
            let communityItem = UIBarButtonItem(image: UIImage(named: "course_community"), style: .plain, target: self, action: #selector(goToCommunity))
            //let navItemRight = UINavigationItem()
            navItemLeft.rightBarButtonItem = communityItem
            //navItems.append(navItemRight)
        }
        navItems.append(navItemLeft)
        navBar.setItems(navItems, animated: true)
        
        //Añadir imagen avatar
        var margin = kMarginLeadingAvatarPad
        if UIDevice.current.userInterfaceIdiom != .pad {
            margin = kMarginLeadingAvatarPhone
        }
        self.avatarImage = UIImageView(frame: CGRect(x: 0, y: 0, width: 100, height: 100))
        if let course = course, let avatarImage = self.avatarImage {
            
            avatarImage.sd_setImage(with: URL(string: appFacade.getCentralUrl() + course.imageUrl), placeholderImage: UIImage(named: "course_placeholder"))
            avatarImage.layer.cornerRadius = avatarImage.frame.height / 2
            avatarImage.layer.borderColor = UIColor.white.cgColor
            avatarImage.layer.borderWidth = 1
            avatarImage.layer.masksToBounds = true
        
            headerView.insertSubview(avatarImage, at: 10)
            avatarImage.translatesAutoresizingMaskIntoConstraints = false
            NSLayoutConstraint.activate([
                avatarImage.leadingAnchor.constraint(equalTo: headerView.leadingAnchor, constant: margin),
                avatarImage.heightAnchor.constraint(equalToConstant: 100),
                avatarImage.widthAnchor.constraint(equalToConstant: 100),
                avatarImage.bottomAnchor.constraint(equalTo: imageView.bottomAnchor, constant: avatarImage.bounds.width / 2)
                ])
        }

        // añadir a la vista la cabecera
        view.addSubview(headerViewController.view)
        headerViewController.didMove(toParentViewController: self)
        headerViewController.headerView.trackingScrollView = self.scrollView
 
        detailContentView.layoutIfNeeded()

### Operating system and device
 - iOS 9 or iOS 10

**Comment by jverkoey** [comment]
Hi @josmanperez - if this is still a bug for you please check out the new behavior that landed in https://github.com/material-components/material-components-ios/pull/4596.

We also have many examples of integrating the flexible header in https://github.com/material-components/material-components-ios/tree/develop/components/FlexibleHeader/examples, many of which show the new behavior. I think the [typical use](https://github.com/material-components/material-components-ios/blob/develop/components/FlexibleHeader/examples/FlexibleHeaderTypicalUseExample.m) example is probably the simplest example.

If the above is unclear or you're still stuck with this integration, please feel free to reopen the issue and I'll take another look.

**Comment by josmanperez** [comment]
Thank you @jverkoey :)
