### ISSUE TITLE
[Collections] Scrolling in large collections is janky in edit mode

### ISSUE THREAD

**Issue by gambard** [material-components/material-components-ios#2531]
### Overview
When scrolling a collection with a large number of items, in edit mode, the scrolling is not smooth at all.

### Reproduction steps
 - Open the "Cell Editing Example (1000+)" example of the Catalog app
 - Enter edit mode
 - Scroll

### Version number
 - 40.0.3

### Operating system and device
 - iOS 11
 - iPhone

**Comment by romoore** [comment]
Thanks @gambard . This is a known issue and a duplicate of #1707.
