### ISSUE TITLE
MaterialChips: Module Not Found

### ISSUE THREAD

**Issue by chaitanya-ramji** [material-components/material-components-ios#2532]
### I tried adding a chip component but I'm getting an error saying the module isn't found.

 - I have imported MaterialComponents
 - Remaining components work inside the same ViewController
 - I'm running the latest version of MDC available on pods
 - My test devices are iPhone X on iOS 11.2b4 and iPhone 6s on iOS 11.1

**Comment by chaitanya-ramji** [comment]
Reproducing the steps above, I'm getting the following errror

`[!] Unable to satisfy the following requirements:

- `MaterialComponents/Chips` required by `Podfile`

Specs satisfying the `MaterialComponents/Chips` dependency were found, but they required a higher minimum deployment target.`

My podfile is as follows

`
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Carpet Area' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Carpet Area

pod 'MaterialComponents'
pod  'MaterialComponents/Chips'

end
`

**Comment by chaitanya-ramji** [comment]
<img width="571" alt="screen shot 2017-12-01 at 10 46 51 am" src="https://user-images.githubusercontent.com/9416558/33468822-02b8514a-d685-11e7-958e-fa539da90696.png">

I'm getting this error by following your steps. My target iOS version is 11. My podfile is exactly like yours.

**Comment by ianegordon** [comment]
Hi @chaitanya-ramji
Is you deployment target iOS 11 or is your iOS SDK 11?
Note that in the Podfile above the following line is actually commented out, so we are going with the default:
# platform :ios, '8.0'

Can you try 'pod install --verbose' and ensure your Applications target deployment target is 8.0 or higher?

**Comment by chaitanya-ramji** [comment]
My podfile mimics yours. It still throws me the same error.

**Comment by ianegordon** [comment]
Hi @chaitanya-ramji I'm still not able to repro.  Would you zip up your sample project that mimics the steps above and send it to me?
iangordon@google.com

**Comment by ianegordon** [comment]
Closing as obsolete.  😞 
Please open a new bug if this is still an issue.  😄
