### ISSUE TITLE
[Masked Transition] Left/Right Card example goes off-screen when rotating device

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#2533]
### Overview
The "left card" and "right card" will rotate off-screen if loaded in landscape and rotated to portrait.

### Reproduction steps
1. Rotate device to landscape
1. Select "left card" or "right card"
2. Tap on either FAB
1. Rotate device to portrait

![masked-landscape](https://user-images.githubusercontent.com/1753199/33380768-27ab322a-d4ea-11e7-973a-599f19f27a43.png)

![masked-portrait](https://user-images.githubusercontent.com/1753199/33380774-2b26a844-d4ea-11e7-80d5-e4b5b32bf8ed.png)

### Version number
40.0.3

### Operating system and device
Any iPhone. Tested iOS 11

---
#### Internal data
- Associated internal bug: [b/117179380](http://b/117179380)

**Comment by material-mirror** [comment]
The internal issue [b/117179380](http://b/117179380) is now closed. This issue is being closed as a result.
