### ISSUE TITLE
[Dialogs] Investigate exposing hooks for dismissal

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#2535]
Should there be hooks for operations based on viewWillDismiss: and viewDidDismiss: ?
Do these already exist?

See #2490 for additional context.

---
#### Internal data
- Associated internal bug: [b/117179113](http://b/117179113)

**Comment by romoore** [comment]
@ianegordon  Could you please outline the acceptance criteria for this issue? If this issue were "complete", what would be the outcomes? Bugs, a design doc, a prototype?
