### ISSUE TITLE
[AppBar] Update additionalSafeAreaInsets when layoutGuides are updated

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#2540]
Research how to best have AppBar support additionalSafeAreaInsets.

As part of view controller containment AppBar should support additionalSafeAreaInsets for embedded controllers.

PR #2521 demonstrates the intended goal, although we are unable to land as it crashes / conflicts with our existing implementation.

Thank you @DonnaLea for the PR!

**Comment by chuga** [comment]
Related (or duplicate?) https://github.com/material-components/material-components-ios/issues/2471
