### ISSUE TITLE
Add compile time flag for import style

### ISSUE THREAD

**Issue by Arcank** [material-components/material-components-ios#2550]
### Overview
Bazel builds and other build setups that don't build MDC as a dynamic framework need to import with quotes instead of angle brackets.

To fix, we'd need IS_BAZEL_BUILD, similar to https://github.com/material-foundation/material-internationalization-ios/pull/34.

**Comment by jverkoey** [comment]
Hey @Arcank: in what context are you running in to this issue? Our `.kokoro` script is meant to handle these import rewrites automatically, so this the associated PR is causing a duplication of rewrites and local source modifications as a result.
