### ISSUE TITLE
[NavigationBar] Catalog examples show the bar clipped on iPhoneX examples

### ISSUE THREAD

**Issue by yarneo** [material-components/material-components-ios#2580]
Because the catalog examples don't take into consideration the safeAreaLayoutGuide that was introduced in iOS 11 for iPhoneX, then the examples show the navigation bars as clipped.

---
#### Internal data
- Associated internal bug: [b/117179094](http://b/117179094)

**Comment by material-mirror** [comment]
The internal issue [b/117179094](http://b/117179094) is now closed. This issue is being closed as a result.
