### ISSUE TITLE
App Bar scrolls title some during stretch

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#260]
Settings controller
![simulator screen shot mar 30 2016 11 11 23 am](https://cloud.githubusercontent.com/assets/1271525/14147104/2bf35d10-f668-11e5-9d5c-b76f0ea944c0.png)
![simulator screen shot mar 30 2016 11 11 19 am](https://cloud.githubusercontent.com/assets/1271525/14147105/2bfffda4-f668-11e5-9e5e-6570358f57f8.png)

**Comment by romoore** [comment]
Cannot reproduce in version 45.0.0 of the MDC repository.
