### ISSUE TITLE
[Collections] Can see two collections views when rotating on iPhone X

### ISSUE THREAD

**Issue by Arcank** [material-components/material-components-ios#2604]
### Overview
[Collections] Can see two collections views when rotating on iPhone X

### Reproduction steps
1. In MDC Catalog, go to `Collection Cells` > `Cell Text Example`.
1. Rotate.

=> We can see two collection views overlaid during the rotation. One with the old layout, one with the new layout.

### Version number
6791dc49

### Operating system and device
iPhone X, iOS 11. Simulator and device.

### Related issues
https://bugs.chromium.org/p/chromium/issues/detail?id=787591

**Comment by strangewiz** [comment]
Added video to https://bugs.chromium.org/p/chromium/issues/detail?id=787591 with MDC catalog reproducing the issue.

**Comment by ianegordon** [comment]
Felix recalls possibly also seeing this on a non-iPhone X.

**Comment by yarneo** [comment]
I am seeing this in on an iPhone 8 as well. Will try to dig more into it

**Comment by ianegordon** [comment]
I have a theory:
My phone is in landscape and showing 3 rows: A,B and C.
I rotate to portrait allowing 2 more rows to become visible: D & E.
D & E are getting sized to the new portrait orientation, so they are not as wide even though they are displayed during the rotation.
As A, B and C are shrinking it appears that D and E are in a second collection.
This may be exacerbated by some strange shadow rendering along the top of the screen.

**Comment by gambard** [comment]
I think it is the same problem as #1600

**Comment by ianegordon** [comment]
We are not intending on any significant updates to the current Collections component. 😞
We are working on a much simpler [List component](https://github.com/material-components/material-components-ios/tree/develop/components/List). 😄
