### ISSUE TITLE
Avoid casting CGFloats as float

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#2605]
In multiple areas across our codebase we are explicitly initializing a CGFloat with a float.
CGFloat height = 112.0f;

Can we avoid this in some way without an explicit cast?

CGFloat height = (CGFloat)112.0;  // Arguably worse

---
#### Internal data
- Associated internal bug: [b/117179229](http://b/117179229)

**Comment by romoore** [comment]
It seems clang does not support `-fsingle-precision-constant` compiler flag.

http://llvm.1065342.n5.nabble.com/Clang-Reasons-for-lack-of-fsingle-precision-constant-support-Alternatives-td83749.html

**Comment by material-mirror** [comment]
The internal issue [b/117179229](http://b/117179229) is now closed. This issue is being closed as a result.
