### ISSUE TITLE
MDCTextInputControllerDefault - helperText and errorText not showing under the text field

### ISSUE THREAD

**Issue by steviemo** [material-components/material-components-ios#2614]
### Overview
I have a MDCTextField in a nib file with an outlet to my view controller. In the  view controller I add this text field to a MDCTextInputControllerDefault. If I set the helperText or the errorText via the controller methods the text appears overlaid on top of input.

Am I missing something?

### Version number
40.1.1

### Operating system and device
iOS 11.2

**Comment by sigito** [comment]
MDC does not decode `errorText` and `helperText` in `initWithCoder:`.

**Comment by willlarche** [comment]
@steviemo , is this still the case?

**Comment by RaoulNL** [comment]
I'm experiencing a similar problem described [here](https://github.com/material-components/material-components-ios/issues/4363).
In my case the MDCTextFields reside in a UIScrollView. First I constrained these TextFields with a fixed height, but that resulted in the leadingUnderlineLabel's text being shown on top of the actual TextField.
Removing this fixed height resolved the issue. However the view takes more space than it initially needs, when there is no text in the leadingUnderlineLabel.

Could you verify that you also gave the nib's a fixed height? Or have you come up with a different solution for this matter?

Also, when the text in the leadingUnderlineLabel (I use it for displaying an error message) is quite large it should be displayed in two (or more) lines. Setting the numberOfLines on the leadingUnderlineLabel does not solve this problem. (B.t.w. I'm using MDCTextInputControllerUnderline)

**Comment by willlarche** [comment]
@Raoulnl the underline labels do not support more than one line right now. 

I’m going to close this ticket since I haven’t heard back from OP. Reopen if you continue to experience an issue.

**Comment by georgmay** [comment]
I have the same issue here. How do I set several lines of helper text?

**Comment by adrianodiasx93** [comment]
+1

**Comment by RaoulNL** [comment]
If you're looking for a good alternative, have a look at [this repo](https://github.com/stephsharp/MaterialTextField) by Steph Sharp.

**Comment by romoore** [comment]
There is a tracking issue to [add multi-line support for helper and error text to Filled and Outlined controllers](https://github.com/material-components/material-components-ios/issues/5762), but not the Default controller.
