### ISSUE TITLE
MDCTextInputControllerDefault show/hide password

### ISSUE THREAD

**Issue by steviemo** [material-components/material-components-ios#2615]
Hi I have looked through documentation and can see no mention of a show/hide icon for a password MDCTextInputControllerDefault.

Am I missing something? This is supported in android material design

Thanks,
Stephen

---
#### Internal data
- Associated internal bug: [b/117179265](http://b/117179265)

**Comment by daveleenew** [comment]
I am also looking for this functionality~~~~~

**Comment by material-mirror** [comment]
The internal issue [b/117179265](http://b/117179265) is now closed. This issue is being closed as a result.
