### ISSUE TITLE
MDCTextInputControllerDefault multiple line for error text?

### ISSUE THREAD

**Issue by steviemo** [material-components/material-components-ios#2617]
Hi

I have an error message that needs to span a couple of lines. Is there anyway to change the number of lines supported by MDCTextInputControllerDefault when setting the error text?

Thanks,
Stephen

---
#### Internal data
- Associated internal bug: [b/117179460](http://b/117179460)

**Comment by polenoso** [comment]
I have the same issue. Error leading label and helper text (leading label) not autoresize for multiple lines even if `setNumberOfLines:0`

**Comment by romoore** [comment]
This is permitted (though discouraged) in the Material Guidelines article.
https://material.io/design/components/text-fields.html#anatomy

**Comment by material-mirror** [comment]
The internal issue [b/117179460](http://b/117179460) is now closed. This issue is being closed as a result.
