### ISSUE TITLE
[Typography] Consider implementing UIFontMetrics materialMetrics

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#2618]
This would mimic the existing UIFontMetrics.

---
#### Internal data
- Associated internal bug: [b/117179249](http://b/117179249)

**Comment by ianegordon** [comment]
UIFontMetrics was introduced in iOS 11.
Our clients who are targeting iOS 11+ may find them useful.

**Comment by ianegordon** [comment]
Investigate if this is feasible.

**Comment by material-mirror** [comment]
The internal issue [b/117179249](http://b/117179249) is now closed. This issue is being closed as a result.
