### ISSUE TITLE
Document the need to set tintColor in the MDCNavigationBar

### ISSUE THREAD

**Issue by liquidx** [material-components/material-components-ios#263]
When you create an AppBar that contains a MDCNavigationBar and you push a new view controller on it, the default color of the back button is blue.

The reason is that you need to set the tintColor on the MDCNavigationBar instance so that all the buttons pick up the right color, eg:

self.navigationBar?.tintColor = UIColor.whiteColor().colorWithAlphaComponent(0.87)

We should document that in our component docs and highlight that requirement.

**Comment by jverkoey** [comment]
I believe this is no longer an issue now that we have comprehensive theming.
