### ISSUE TITLE
[TextFields] Support Shape theming

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#2631]
## Story
As a designer with customized shapes in my app, I want my text fields to reflect my shape theming.  A good example would be a Text Area with a cut corner to mimic corners on my buttons.

## Acceptance Criteria
1. Text Fields (Outlined, Filled) support Shape theming. 

---
#### Internal data
- Associated internal bug: [b/117179034](http://b/117179034)

**Comment by georgepurusniuc** [comment]
Any update on this one?

**Comment by romoore** [comment]
I'm going to change this Issue to supporting Shapes in Text Fields - I don't believe the team has time to build it in the near future but we are always happy to review a Pull Request. :)

**Comment by material-mirror** [comment]
The internal issue [b/117179034](http://b/117179034) is now closed. This issue is being closed as a result.
