### ISSUE TITLE
Intercept text changes MDCMultilineTextField

### ISSUE THREAD

**Issue by neolio42** [material-components/material-components-ios#2638]
How intercept a text change in a MDCMultilineTextField ?
It is written in the documentation :

```
let textFieldFloating = MDCMultilineTextField()
textFieldFloating.delegate = self
```
But .delegate is not available. We have just .layoutDelegate and .multilineDelegate.
Do you have a example or tell me the correct way to do that.

Thank you.

**Comment by willlarche** [comment]
The documentation has an error. It should be `textFieldFloating.textView.delegate`. Thank you for finding that!
