### ISSUE TITLE
Research ButtonBar support for system item types

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#264]
## Context

ButtonBar does not presently support UIBarButtonItem instances that were created with `initWithBarButtonSystemItem:`. This is due to the underlying system item _type_ being unavailable to us via any public API.
## The ideal

Ideally, the Button Bar would support the list of system item types defined by [UIBarButtonSystemItem](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIBarButtonItem_Class/#//apple_ref/c/tdef/UIBarButtonSystemItem).
## Potential solutions
- Provide a subclass of UIBarButtonItem that adds explicit setters and getters for the system item type.

---
#### Internal data
- Associated internal bug: [b/117179589](http://b/117179589)

**Comment by romoore** [comment]
As a stop-gap measure, we may wish to document this limitation in the [AppBar documentation](https://github.com/material-components/material-components-ios/tree/develop/components/AppBar).

**Comment by material-mirror** [comment]
The internal issue [b/117179589](http://b/117179589) is now closed. This issue is being closed as a result.
