### ISSUE TITLE
[ShadowLayer] Create tests for shadow layer resizing animations

### ISSUE THREAD

**Issue by samnm** [material-components/material-components-ios#2643]
#2523 introduced implicit animations for MDCShadowLayer resizing. This is complex and should be better tested.

We should build similar tests for MDCShapedShadowLayer (#2619)

---
#### Internal data
- Associated internal bug: [b/117179379](http://b/117179379)

**Comment by material-mirror** [comment]
The internal issue [b/117179379](http://b/117179379) is now closed. This issue is being closed as a result.
