### ISSUE TITLE
[FeatureHighlight] Move Dynamic Type Support to the View

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#2650]
UIContentSizeCategoryAdjusting is typically implemented on UIView.
Move from MDCFeatureHighlightViewController to MDCFeatureHightView:
@property(nonatomic, readwrite, setter=mdc_setAdjustsFontForContentSizeCategory:)
    BOOL mdc_adjustsFontForContentSizeCategory UI_APPEARANCE_SELECTOR;

**Comment by mohammadcazig** [comment]
The view is not private and not accessible in public interface, are you suggesting to move the logic to the view and have view controller pass the boolean to the view?

**Comment by romoore** [comment]
@ianegordon Could you please clarify what you expect the resulting API to look like?

**Comment by ianegordon** [comment]
Done.
