### ISSUE TITLE
Remove legacy code for iOS8

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#2651]
We should remove code adding special handling for iOS 8 devices.

This is blocked until we drop support for iOS 8.

---
#### Internal data
- Associated internal bug: [b/117179401](http://b/117179401)

**Comment by romoore** [comment]
What is blocking this issue?

**Comment by ianegordon** [comment]
As of today, we still support iOS 8 😄 

This issue was created so I could tag some TODOs in the codebase with an associated issue.

**Comment by jverkoey** [comment]
This is blocked on us dropping iOS 8 support: https://github.com/material-components/material-components-ios/issues/4656

**Comment by material-mirror** [comment]
The internal issue [b/117179401](http://b/117179401) is now closed. This issue is being closed as a result.
