### ISSUE TITLE
[AppBar] Rotation breaks Y offset

### ISSUE THREAD

**Issue by ArEnSc** [material-components/material-components-ios#2658]
<img width="1673" alt="screenshot 2017-12-06 03 19 57" src="https://user-images.githubusercontent.com/6252325/33746236-f2b1798e-db89-11e7-8a32-093c102b637a.png">

Just add a AppTabbar to an iPad app and rotate it and you have this problem .,...
### Overview
For usage questions: ask on [Stack  Overflow](https://stackoverflow.com/questions/tagged/material-components+ios).

 - Context, problem or idea, solution or next step
 - Screenshots/Video (if possible)
 - Stack trace (if possible)

### Reproduction steps
 - Detailed steps to reproduce

### Version number
 - Found in CHANGELOG.md

### Related issues
 - Type `#` and the issue number or `#` and select the from the inline drop down.

**Comment by jverkoey** [comment]
This should no longer be an issue. Please re-open if you're still encountering this.
