### ISSUE TITLE
Button Bar support for animating item changes

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#266]
### The problem

UIToolbar provides `-setItems:animated:`. Button Bar provides no equivalent API.
### Potential work ahead

The work required here is roughly:
1. Implement button reuse. On setItems we need to identify items that have been added, removed, or reordered.
2. Implement animations for each of added, removed, and rearranged.
3. Create an example that demonstrates all three types of animations.

---
#### Internal data
- Associated internal bug: [b/117179430](http://b/117179430)

**Comment by material-mirror** [comment]
The internal issue [b/117179430](http://b/117179430) is now closed. This issue is being closed as a result.
