### ISSUE TITLE
[Shrine] Header logo extends outside safe area

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#2678]
### Overview
Running the Shrine app on the iPhone X simulator shows that its header does not correctly position elements within the safe area.

![screen shot 2017-12-11 at 8 51 45 am](https://user-images.githubusercontent.com/1753199/33834323-9153f9b8-de50-11e7-92bf-0151a0d05b84.png)

### Reproduction steps
Run the Shrine app on an iPhone X

### Version number
42.0.0

### Operating system and device
iPhone X (Simulator), iOS 11.1 (Simulator)

**Comment by yarneo** [comment]
fixed
