### ISSUE TITLE
[Shrine] CollectionView does not respect safe area (landscape)

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#2679]
### Overview
In the Shrine App on an iPhone X, landscape mode produces cells that overlap the safe area. This obscures avatar images and prices.

![screen shot 2017-12-11 at 8 53 16 am](https://user-images.githubusercontent.com/1753199/33834450-fe308998-de50-11e7-9fd1-409de5713612.png)
![screen shot 2017-12-11 at 8 53 03 am](https://user-images.githubusercontent.com/1753199/33834455-ffd70b64-de50-11e7-88fb-412c448be1ee.png)

### Reproduction steps
Run Shrine on an iPhone X. Rotate to landscape.

### Version number
42.0.0

### Operating system and device
iPhone X (Simulator), iOS 11.1 (Simulator)

### Related issues
#2678

**Comment by yarneo** [comment]
fixed
