### ISSUE TITLE
[Shrine] Product Detail FAB is partially outside safe area

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#2680]
### Overview
The Shrine app's product detail FAB resides partly outside the safe area. On an iPhone X, this makes the bottom edge of the FAB untappable because it overlaps the "Home Bar" area.

![screen shot 2017-12-11 at 8 56 41 am](https://user-images.githubusercontent.com/1753199/33834603-763e15e0-de51-11e7-8c4b-d39f76378bae.png)

### Reproduction steps
Run Shrine on an iPhone X

### Version number
42.0.0

### Operating system and device
iPhone X (Simulator), iOS 11.1 (Simulator)

### Related issues
#2678 , #2679

**Comment by yarneo** [comment]
fixed
