### ISSUE TITLE
Flexible Header + ShadowLayer = curvy shadows

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#270]
This doesn't seem like desired behavior:

![screen shot 2016-03-31 at 12 05 27 pm](https://cloud.githubusercontent.com/assets/45670/14182364/ea4f1daa-f738-11e5-9b63-4dd403ffdec6.png)

Note that the shadow curves off before reaching the edge of the screen.

Compared to using a standard shadow:

![screen shot 2016-03-31 at 12 07 37 pm](https://cloud.githubusercontent.com/assets/45670/14182444/37d93484-f739-11e5-84bd-2fa643312bc7.png)

**Comment by ianegordon** [comment]
Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄
