### ISSUE TITLE
[Typography] Have a single source of truth for fonts

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#2709]
We have a Typography singleton that maps a set of font styles (body, headline, caption, etc.) to a specific UIFont.
We also have [UIFont standardFontForStyle:] that also maps a set of font styles to a specific UIFont.

We should only have a single source of truth for fonts.

Typography Singleton:
By default, these fonts use the system font, but the font loader can be replaced with a custom font loader to return a specific font (Roboto for instance).  Is often called internally by our components to determine their fonts.

[UIFont standardFont]:
Mimic's Apple's [UIFont preferredFont].  Does *not* allow font face customization.  It always return system font.

We want the ability to customize font faces on a per component and per instance basis and will be exposing customFont properties on our text elements.
As such, we should migrate people to the new font properties and [UIFont mdc_standardFontForStyle:] APIs when possible.

---
#### Internal data
- Associated internal bug: [b/117179112](http://b/117179112)

**Comment by material-mirror** [comment]
The internal issue [b/117179112](http://b/117179112) is now closed. This issue is being closed as a result.
