### ISSUE TITLE
[Collections] Swiping with two fingers dismisses the cell in the middle

### ISSUE THREAD

**Issue by gambard** [material-components/material-components-ios#2722]
### Overview
When swiping with two fingers, with a different Y position, on a collection where swipe-to-dismiss is enabled, the cell in the middle of the two tap position is dismissed.
I would have expected to have either a swipe-to-dismiss action on the elements positioned directly under my fingers, or no action.

### Reproduction steps
 - Open the Swipe-To-Dismiss-Row Example of the MDC Collection app
 - Place one finger on the Section-0 Item-0 item, and another finger on the Section-0 Item-4 item
 - Swipe both finger right or left

See that the Section-0 Item-2 item is dismissed

### Version number
 - 42

### Operating system and device
 - iOS 11, iPhone/iPad.

**Comment by yarneo** [comment]
Hey @gambard thanks for bringing this to our attention!

I went ahead and pushed a commit to the develop branch that will stop the swipe-to-dismiss of swiping the wrong cell if using multiple fingers. The outcome now when using multiple fingers is a no action.
