### ISSUE TITLE
[Chips] Subviews should be pixel aligned

### ISSUE THREAD

**Issue by samnm** [material-components/material-components-ios#2730]
We had to rollback the previous pixel alignment behavior due to it causing a layout error in some cases (#2719).

Correctly pixel aligning subviews will require updating both layoutSubviews AND sizeThatFits.

---
#### Internal data
- Associated internal bug: [b/117179264](http://b/117179264)

**Comment by material-mirror** [comment]
The internal issue [b/117179264](http://b/117179264) is now closed. This issue is being closed as a result.
