### ISSUE TITLE
[TextFields] Cannot set different default colors for different controller classes

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#2733]
### Overview
The default color properties are backed by static variables in superclasses. As a result, I cannot set different color defaults for different subclasses.

### Reproduction steps

```objectivec
MDCTextInputControllerOutlined.activeColorDefault = UIColor.purpleColor;
MDCTextInputControllerUnderline.activeColorDefault = UIColor.redColor;
MDCTextInputControllerOutlinedTextArea.activeColorDefault = UIColor.greenColor;
NSLog(@"%@", MDCTextInputControllerOutlined.activeColorDefault); // greenColor
NSLog(@"%@", MDCTextInputControllerUnderline.activeColorDefault); // greenColor
NSLog(@"%@", MDCTextInputControllerOutlinedTextArea.activeColorDefault); // greenColor
```

### Version number
43.1.0

---
#### Internal data
- Associated internal bug: [b/117179322](http://b/117179322)

**Comment by material-mirror** [comment]
The internal issue [b/117179322](http://b/117179322) is now closed. This issue is being closed as a result.
