### ISSUE TITLE
[BottomNavBar] UIAppearance properties should be nullable

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#2738]
As it is a UIAppearance-friendly property, itemTitleFont should be null.
In the implementation, if _itemTitleFont is nil, ask the UIFont standardFont for the default font.

The same goes for other UIAppearance properties currently annotated as nonnull.

**Comment by jverkoey** [comment]
Marking as Obsolete because we do not intend to continue to invest effort into UIAppearance. Please consider using the explicit themer APIs instead.
