### ISSUE TITLE
Typo in ink documentation

### ISSUE THREAD

**Issue by bernaferrari** [material-components/material-components-ios#2755]
From this page: https://material.io/components/ios/catalog/ink/

```
let inkTouchController = MDCInkTouchController(view: myButton)
inkTouchController?.addInkView()
```

> Cannot use optional chaining on non-optional value of type 'MDCInkTouchController' on Xcode. 

The "?" should disappear.

**Comment by yarneo** [comment]
Thanks @bernaferrari from bringing this to our attention! We will update the docs accordingly
