### ISSUE TITLE
[Themers] Remove any theming in Dragons

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#2762]
We should to see baseline / default values by default.

Currently we are applying a Black & White theme to all of our components making evaluation of the rendering difficult.

**Comment by yarneo** [comment]
Hey @ianegordon , are you referring to the theming done in the AppDelegate.swift in MDCCatalog (https://github.com/material-components/material-components-ios/blob/develop/catalog/MDCCatalog/AppDelegate.swift#L64)? If so, that theming isn't applied for the Dragons app. If you are referring to something else I am happy to look into it.

**Comment by ianegordon** [comment]
SGTM.
