### ISSUE TITLE
[Tabs] 2 errors find on documentation

### ISSUE THREAD

**Issue by LeChatNoir69** [material-components/material-components-ios#2767]
Hi there,

I've found 2 issues when trying to use Tabs components with Obj-C :

=> In the exemple, you missed a "h" caractère (initWitFrame) : 
`MDCTabBar *tabBar = [[MDCTabBar alloc] initWithFrame:self.view.bounds];`

=> I have to import headers like this : 
#import <MaterialComponents/MaterialTabs.h>

 If you could update the doc for others. Thank you for the good work !

**Comment by ianegordon** [comment]
Hi LeChatNoir69, thanks for catching our missing 'h'.

As far as the headers, I'm not sure why you need the import headers with the angle brackets.  I just tested a demo project with a simple Podfile and "#import "MaterialTabs.h" worked as expected.

What version of Xcode are you using?
Can you attach a sample project showing the issue?

**Comment by LeChatNoir69** [comment]
You’re right,

No pb in sample project but in my main project, I can’t simply import « .h ».
Maybe because of my settings or because the project is Obj-C/Swift mix ?

**Comment by ianegordon** [comment]
Done.
