### ISSUE TITLE
[Tabs] MDCTabBar selectedItemTitleFont doesn't update

### ISSUE THREAD

**Issue by LeChatNoir69** [material-components/material-components-ios#2769]
Just install Material with pod install in my app.

My pod file is : pod 'MaterialComponents'

In my lockFile, I can see that version is 35.2.0.

But the method selectedItemTitleFont appear in a 4x.x.x version...

Does I have to specify version I want in my podFile ?

**Comment by romoore** [comment]
Hi @LeChatNoir69, thanks for your interest in MDC-iOS! It sounds like you may need to update your pods. Can you try the following two commands? The firsts will update the master CocoaPods repository, the second will update to the latest version of MDC-iOS that your Podfile allows. If you are not specifying a version, it should be the latest published version.

```bash
pod repo update
pod update
```

If this doesn't solve the issue for you, can you add a link to your project or upload your `Podfile`?

**Comment by LeChatNoir69** [comment]
Ok, thank you. It did the trick !

Unfortunately, font doesn't change.
This is my code
`MDCTabBar *_tabBar = [[MDCTabBar alloc] initWithFrame:_appBar.headerViewController.headerView.bounds];

    _tabBar.items = @[
                     [[UITabBarItem alloc] initWithTitle:@"Recents" image:nil tag:0],
                     [[UITabBarItem alloc] initWithTitle:@"Favorites" image:nil tag:0],
                     ];
    _tabBar.itemAppearance = MDCTabBarItemAppearanceTitles;
    _tabBar.autoresizingMask =
    UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleBottomMargin;
    _tabBar.delegate=self;
    CGFloat width=[UIScreen mainScreen].bounds.size.width;
    UIFont *font=[UIFont systemFontOfSize:32];
  
    _tabBar.unselectedItemTitleFont=font;
    _tabBar.selectedItemTitleFont=font;`

Font doesn't change...

**Comment by romoore** [comment]
In your code, are you returning a value for the delegate method `positionForBar:`? If you do and return `UIBarPositionBottom`, [then the font will be ignored](https://github.com/material-components/material-components-ios/blob/develop/components/Tabs/src/MDCTabBar.m#L539).  

I made the same change in `TabBarIconExample.m` from the examples code and I saw that the font change was working as expected.  Here's excerpted code:

```objectivec
#pragma mark - Private

- (void)loadTabBar {
  MDCTabBar *tabBar = [[MDCTabBar alloc] init];
  tabBar.delegate = self;
  tabBar.alignment = MDCTabBarAlignmentCenterSelected;
  ...
  tabBar.unselectedItemTintColor = [[UIColor whiteColor] colorWithAlphaComponent:.38f];
  tabBar.itemAppearance = MDCTabBarItemAppearanceTitledImages;

  // Added the following 2 lines
  tabBar.unselectedItemTitleFont = [UIFont systemFontOfSize:32];
  tabBar.selectedItemTitleFont = [UIFont systemFontOfSize:32];

  self.tabBar = tabBar;
  self.appBar.headerStackView.bottomBar = self.tabBar;
  [self.appBar.headerStackView setNeedsLayout];
}
```

If you modify the examples in the catalog, does it work for you? Are you also seeing the same bug if you try to modify the example?

**Comment by LeChatNoir69** [comment]
You're right !
I've made some tests to place the tabbar but I did the wrong way.
Thank you very much for everything :)

**Comment by romoore** [comment]
You're welcome! Let us know if you have any other questions or problems. 😃
