### ISSUE TITLE
Observe changes to titleTextAttributes

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#277]
If possible, we should observe changes to UIBarItem's `titleTextAttributesForState`.

**Comment by romoore** [comment]
Is this a duplicate of #3692 ?

**Comment by jverkoey** [comment]
This bug looks like a subset duplicate, yep.

**Comment by jverkoey** [comment]
Duplicate of https://github.com/material-components/material-components-ios/issues/3692.
