### ISSUE TITLE
MDCDialogs freezing iOS keyboard

### ISSUE THREAD

**Issue by bernaferrari** [material-components/material-components-ios#2770]
How to reproduce:
- Download the code below.
- Run. If on emulator, you need to toggle off Hardware->Keyboard->Connect Hardware Keyboard. We want the software keyboard.
- Tap on name (or any other field, preferably in the top), keyboard will show up.
- Press enter multiple times (it should go to next field). After about 5 times (or basically, when it goes offscreen), keyboard will freeze. "Done" will not work. If you close the MDCDialog the keyboard will stay up.

[DialogsKeyboardBug.zip](https://github.com/material-components/material-components-ios/files/1592418/DialogsKeyboardBug.zip)

MaterialComponents (43.1.1)
iOS 11
Tested and reproducable both on iPad and iPhone, both in emulator (without hardware keyboard) and in 'real life'.

**Comment by yarneo** [comment]
I'll close this issue for now until we are able to reproduce this using a native implementation without the use of 3rd party libraries.

**Comment by bernaferrari** [comment]
Well, that was hard, thanks!! I will keep using iOS native dialogs for now 😢 but if I am able to reproduce with native parts, I will warn you.
Thanks for the effort!!
