### ISSUE TITLE
[Chips] Support encoding of shapeGenerator property

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#2771]
### Overview
MDCChipView supports NSCoding, but not for its `shapeGenerator` property. Any archived and unarchived Chip will lose its shape.

### Reproduction steps
1. Create an MDCChipView and set a value for the `shapeGenerator` property
2. Archive and unarchive the chip view
3. Verify that the `shapeGenerator` property is the correct object

### Version number
43.1.0

**Comment by jverkoey** [comment]
We'll dropping support for coding view components until there is a more clear justification for the need for this functionality.
