### ISSUE TITLE
[Dialogs] Mark MDCAlertController as final / not intended to be subclassed

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#2787]
Like UIAlertController, MDCAlertController is not intended to be subclasses.

Annotate it as final and document this fact.

**Comment by ianegordon** [comment]
This is already the case, and has been since the class was written.

MDCAlertController.m:26
MDCAlertController class is intended to be used as-is and does not support subclassing. The view
 hierarchy for this class is private and must not be modified.

**Comment by romoore** [comment]
Let's move the documentation to the header, preferably in the @interface docs.

**Comment by romoore** [comment]
Nevermind, the doc *is* in the header, not the implementation.

**Comment by romoore** [comment]
Should we not use the subclassing_restricted attribute as the "mark" part of this Issue?

**Comment by ianegordon** [comment]
Why yes, yes it should. 👍
