### ISSUE TITLE
Interaction tests need more support code to be scalable

### ISSUE THREAD

**Issue by ajsecord** [material-components/material-components-ios#2798]
We currently have a single interaction test using EarlGrey that tests Snackbars. That test contains general code for scrolling the main catalog view to a particular component, tapping on the component, choosing a demo, etc, which has to be duplicated for any other interaction tests. This should be extracted and put somewhere available to all interaction tests.

Consider #2797 before doing this, though—that might be a better approach.

**Comment by jverkoey** [comment]
We do not have public interaction tests.
