### ISSUE TITLE
Flexible header doesn't take into account alwaysBounceVertical

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#281]
### The bug

Not taking alwaysBounceVertical into account allows the header to shift on-screen when `alwaysBounceVertical` is enabled and the content height is smaller than the bounds height. 
### The context

`fhv_isOverExtendingBottom` contains the following logic:

```
  BOOL canOverExtendBottom =
      (_trackingScrollView.contentSize.height > _trackingScrollView.bounds.size.height);
```
### Possible solutions

canOverExtendBottom needs to take into account alwaysBounceVertical and short-circuit to YES if alwaysBounceVertical is true.

---
#### Internal data
- Associated internal bug: [b/117179552](http://b/117179552)

**Comment by samnm** [comment]
This appears to be behaving as expected, but I'm a little uncertain what the expected behavior is.

Right now with `alwaysBounceVertical = YES` the header tracks with the scrollview (which is what feels right to me), but the description implies that is a bug. @jverkoey is this behaving as expected?

**Comment by material-mirror** [comment]
The internal issue [b/117179552](http://b/117179552) is now closed. This issue is being closed as a result.
