### ISSUE TITLE
[Snackbar]  Add capability to extend height if there is a lot of text

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#2813]
As shown in the spec:
https://material.io/guidelines/components/snackbars-toasts.html#snackbars-toasts-specs

Bottom entry in the following Image:
https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B57Y8yNEHsZPcS1OaVBVajhpeDQ/components-toasts-mobile4.png

If there is sufficient text, the body will be given the full width with up to two lines and the action button will be moved below.

**Comment by jverkoey** [comment]
Duplicate of https://github.com/material-components/material-components-ios/issues/2059
