### ISSUE TITLE
[Release] `scripts/release bump` does not seem to do anything

### ISSUE THREAD

**Issue by ajsecord** [material-components/material-components-ios#2817]
I tried 

```
scripts/release bump 45.0.0
scripts/release bump 45.0.0 44.0.0
scripts/release bump v45.0.0
scripts/release bump v45.0.0 v44.0.0
```

all to no avail. :(

**Comment by ajsecord** [comment]
#2754 broke the script 17 days ago when it switched grep to use fixed strings but didn't change the regexes from regexes to fixed strings.

**Comment by randallli** [comment]
I was able to use the release bump command for 47.0.0
