### ISSUE TITLE
[Typography] Migrate MDCFontTextStyle from NS_ENUM(Integer) to NS_STRING_ENUM

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#2834]
See UIFont & UIFontTextStyle for a template.

---
#### Internal data
- Associated internal bug: [b/117179033](http://b/117179033)

**Comment by material-mirror** [comment]
The internal issue [b/117179033](http://b/117179033) is now closed. This issue is being closed as a result.
