### ISSUE TITLE
[Ink] Ink not covering entire view when tapped on the edge

### ISSUE THREAD

**Issue by yarneo** [material-components/material-components-ios#2835]
In certain UIView bounds, when pressing on the edge of the UIView, the ink doesn't fit the entire view.

Please see gif attached (look for the bottom left corner) 
![naklypotdv](https://user-images.githubusercontent.com/4066863/34897436-f869d63e-f7bb-11e7-881c-99cdf5795e12.gif)

---
#### Internal data
- Associated internal bug: [b/117179227](http://b/117179227)

**Comment by material-mirror** [comment]
The internal issue [b/117179227](http://b/117179227) is now closed. This issue is being closed as a result.
