### ISSUE TITLE
[Ink] weird behavior when using smaller maxRippleRadius

### ISSUE THREAD

**Issue by yarneo** [material-components/material-components-ios#2836]
When using a maxRippleRadius smaller than the UIView, it tries to center the ripple center.

see gif:

![apd0ncxig9](https://user-images.githubusercontent.com/4066863/34897531-698c0116-f7bc-11e7-8508-842526ed08fc.gif)

---
#### Internal data
- Associated internal bug: [b/117179056](http://b/117179056)

**Comment by material-mirror** [comment]
The internal issue [b/117179056](http://b/117179056) is now closed. This issue is being closed as a result.
