### ISSUE TITLE
[Ink] Ink completion block not called upon invoking `startTouchEndedAnimationAtPoint`

### ISSUE THREAD

**Issue by yarneo** [material-components/material-components-ios#2839]
Ink completion block not called upon invoking `startTouchEndedAnimationAtPoint`.
This is only broken for the new ink, but works fine for the legacy ink.

---
#### Internal data
- Associated internal bug: [b/117179208](http://b/117179208)

**Comment by material-mirror** [comment]
The internal issue [b/117179208](http://b/117179208) is now closed. This issue is being closed as a result.
