### ISSUE TITLE
[ProgressView] Progress going backward when setting it to 0 without animation then to a value with animation

### ISSUE THREAD

**Issue by gambard** [material-components/material-components-ios#2846]
### Overview
When setting the value of the ProgressView progress from 1 to 0 without animation, then setting it to another value (let's say 0.1) with animation in the same runloop, the animation is going backward.

### Reproduction steps
 - Set the progress to the progress view to 1.
 - Wait until it completes.
 - Set the progress to 0 without animation
 - Set the progress to 0.1 with animation, in the same runloop

### Version number
 - 44

---
#### Internal data
- Associated internal bug: [b/117179091](http://b/117179091)

**Comment by material-mirror** [comment]
The internal issue [b/117179091](http://b/117179091) is now closed. This issue is being closed as a result.
