### ISSUE TITLE
Shadow elevations demo for Swift

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#285]
Regarding http://codereview.cc/D486, should it show short-form Swift API names? Is this possible?

It may be reasonable to turn the shadow elevations into an enum so that Swift can use the `.value` short-hand.

**Comment by jgunaratne** [comment]
This has been considered before. The shadow layer needs to support floats for point elevations, and therefore shadow elevations are floats rather than integers. This makes it difficult to use an enum for shadow elevations since enums are ints.

**Comment by jverkoey** [comment]
This should be possible with swift enum typing. An example from [Material Motion](https://github.com/material-motion/motion-animator-objc/blob/develop/src/MDMAnimatableKeyPaths.h).

**Comment by jgunaratne** [comment]
Similar issue noted in: https://github.com/material-components/material-components-ios/issues/2105

**Comment by jgunaratne** [comment]
Address in: https://github.com/material-components/material-components-ios/pull/2116
