### ISSUE TITLE
[MaskedTransition] Centered Card Crashes

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#2857]
In MDCCatalog -> MaskedTransition
Selected the centered card transition.
Click on the orange button.
Click on the card to dismiss.
Crash.

This will repro on the iPhone 5s @ 8.1 and iPhone 5s @ 11.2 simulators.

**Comment by romoore** [comment]
Proposed fix: https://github.com/material-motion/motion-animator-objc/pull/110

**Comment by jverkoey** [comment]
This is resolved.
