### ISSUE TITLE
[Snackbar] Snackbars cover the FAB in a bottom app bar

### ISSUE THREAD

**Issue by samnm** [material-components/material-components-ios#2870]
Snackbars cover the FAB in the BottomAppBar component.

---
#### Internal data
- Associated internal bug: [b/117179135](http://b/117179135)

**Comment by jamirais3036** [comment]
All only my iphone5

**Comment by material-mirror** [comment]
The internal issue [b/117179135](http://b/117179135) is now closed. This issue is being closed as a result.
