### ISSUE TITLE
[Tabs] Controller is not setting the transition to the parentVC

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#2876]
https://github.com/material-components/material-components-ios/blob/2afa8c57d806da6fcdfdf669ff8943a65fdf1f68/components/Tabs/src/MDCTabBarViewController.m#L151

---
#### Internal data
- Associated internal bug: [b/117179321](http://b/117179321)

**Comment by material-mirror** [comment]
The internal issue [b/117179321](http://b/117179321) is now closed. This issue is being closed as a result.
