### ISSUE TITLE
Text Field Autocomplete?

### ISSUE THREAD

**Issue by JustinBobo** [material-components/material-components-ios#2883]
Hi all,

Firstly, great job with this library! Out of curiosity, do the text fields offer autocomplete functionality (either inline or a dropdown, or both). For reference: http://www.material-ui.com/#/components/auto-complete. If not, is this something that you plan to implement eventually? Thanks!

---
#### Internal data
- Associated internal bug: [b/117179303](http://b/117179303)

**Comment by material-mirror** [comment]
The internal issue [b/117179303](http://b/117179303) is now closed. This issue is being closed as a result.
