### ISSUE TITLE
pod 'MaterialComponents/TextFields' Not working

### ISSUE THREAD

**Issue by WeiLiangTan** [material-components/material-components-ios#2888]
I have tried to pod 'MaterialComponents/TextFields', and receiving this error.

`Analyzing dependencies`
`[!] Unable to satisfy the following requirements:`

`- MaterialComponents/TextFields required by Podfile`

`None of your spec sources contain a spec satisfying the dependency: MaterialComponents/TextFields.`

`You have either:`
 `* out-of-date source repos which you can update with pod repo update or with pod install --repo-update.`
 `* mistyped the name or version.`
 `* not added the source repo that hosts the Podspec to your Podfile.`

`Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by `default.`

### Version number
 - 44.5.0

**Comment by romoore** [comment]
What message do you get if you run `pod repo update` before a `pod install`?

**Comment by WeiLiangTan** [comment]
### After running `pod repo update` and `pod install`
`Analyzing dependencies`
`[!] CocoaPods could not find compatible versions for pod "MaterialComponents/TextFields":`
 ` In Podfile:`
    `MaterialComponents/TextFields`

`Specs satisfying the MaterialComponents/TextFields dependency were found, but they required a higher minimum deployment target.`


### This is my podfile

`platform :ios, '9.0'`

`target 'target' do`
  `# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!`

`  # Pods for mySGHome``
`  pod 'MaterialComponents/AppBar'`
`  pod 'MaterialComponents/Buttons'`
`  pod 'MaterialComponents/Collections'`
`  pod 'MaterialComponents/TextFields'`
  
`end`

**Comment by romoore** [comment]
I tried the same set-up on a new Single-View application (Xcode template) on Xcode 9. I didn't get the errors you're receiving.

```bash
rsmoore:MDCTextFieldApp rsmoore$ pod init
rsmoore:MDCTextFieldApp rsmoore$ vi Podfile 
rsmoore:MDCTextFieldApp rsmoore$ pod install
Analyzing dependencies
Downloading dependencies
Installing MDFInternationalization (1.0.4)
Installing MDFTextAccessibility (1.2.0)
Installing MaterialComponents (44.5.0)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `MDCTextFieldApp.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There are 4 dependencies from the Podfile and 3 total pods installed.

[!] Automatically assigning platform ios with version 11.2 on target MDCTextFieldApp because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
rsmoore:MDCTextFieldApp rsmoore$ vi Podfile
rsmoore:MDCTextFieldApp rsmoore$ pod install
Analyzing dependencies
Downloading dependencies
Using MDFInternationalization (1.0.4)
Using MDFTextAccessibility (1.2.0)
Using MaterialComponents (44.5.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 4 dependencies from the Podfile and 3 total pods installed.
rsmoore:MDCTextFieldApp rsmoore$ pod --version
1.3.1
rsmoore:MDCTextFieldApp rsmoore$
```

Here's my Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MDCTextFieldApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for MDCTextFieldApp
  pod 'MaterialComponents/AppBar'
  pod 'MaterialComponents/Buttons'
  pod 'MaterialComponents/Collections'
  pod 'MaterialComponents/TextFields'

  target 'MDCTextFieldAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MDCTextFieldAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

Do you get the same error when you create a brand new project with the same MaterialComponents pods?  Given the error message, you may have another dependency that requires a higher iOS version.

**Comment by WeiLiangTan** [comment]
It's working fine on a new project. 

I have tried to set my project's deployment target to latest version, however I still getting the same error.

I will create a new project and move the files to the new project.

Thanks for your quick response.

**Comment by romoore** [comment]
Sorry you're having trouble with it.  Please update this thread with anything you learned so others can find the solution in the future. 👩‍🏫
