### ISSUE TITLE
[Themes] Add FontScheme documentation to the README

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#2889]
### Overview
The README for Themes does not discuss MDCFontScheme. It should be updated to explain how clients can use Themes for theming their applications' fonts.

---
#### Internal data
- Associated internal bug: [b/117179519](http://b/117179519)

**Comment by material-mirror** [comment]
The internal issue [b/117179519](http://b/117179519) is now closed. This issue is being closed as a result.
