### ISSUE TITLE
Audit for 9.*+ deployment target warnings

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#289]
### Context

While we do support iOS 7 and above, many clients will be using iOS 9 and above as a deployment target. This will result in a wider variety of warnings than building against 7.0.
### Potential work ahead

It may be helpful to create a "latest" pod target that has its deployment target set to the latest SDK at all times.

**Comment by romoore** [comment]
Obsolete.

**Comment by romoore** [comment]
Oh wait, I'm not sure what the "latest" pod target means. Leaving this open for @jverkoey  to provide more detail.

**Comment by jverkoey** [comment]
We generally rely on internal infrastructure to catch any warnings related to this, so I'm marking this as obsolete.
