### ISSUE TITLE
MDCChipField Issues

### ISSUE THREAD

**Issue by JustinBobo** [material-components/material-components-ios#2893]
Hi all,

I'm having trouble implementing the MDCChipField in a TableViewCell. There seems to be an issue with resizing as additional lines are added (alternatively, the MultilineTextField handles this fine). When more lines are added, the cell doesn't resize properly and seems to be static with overflow going into the next tableviewcell. Additionally, it appears that I can't use the interface builder to add a chip field (this also isn't an issue with other text fields). 

Perhaps I'm just doing something wrong but I followed the example provided (there's only one with the chip field) and still had these issues. Thanks!

---
#### Internal data
- Associated internal bug: [b/117179090](http://b/117179090)

**Comment by ianegordon** [comment]
TODO: Add example demonstrating these issues.

**Comment by material-mirror** [comment]
The internal issue [b/117179090](http://b/117179090) is now closed. This issue is being closed as a result.
