### ISSUE TITLE
Automated mechanism for identifying visual changes between releases

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#290]
### Context

When we cut a release we need to identify whether it is introducing any visual changes. If there are visual changes then our release automatically becomes a "breaking" release and we need to communicate such changes accordingly.
### The missing functionality

We have no means of identifying visual changes other than human eyes. We need an automated approach to this.
### Potential work ahead

This is a good opportunity to use screenshot-based testing to identify changes at release time. These tests should **strictly** be part of the release work flow as a signal for visual breaking changes.

---
#### Internal data
- Associated internal bug: [b/117179272](http://b/117179272)

**Comment by ianegordon** [comment]
Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄

**Comment by jverkoey** [comment]
Not fully ignored! We have this internally now and may be able to use it as part of our release notes. E.g. take the screenshot deltas and include them in the release notes. Might be worth exploring still (will reopen just in case).

**Comment by codeman7** [comment]
We now have screenshot test
