### ISSUE TITLE
Some of our classes do not conform to NSSecureCoding ⚠️

### ISSUE THREAD

**Issue by stephanemoore** [material-components/material-components-ios#2904]
Source:
https://github.com/material-components/material-components-ios/blob/fdfb54f/components/Themes/src/MDCTonalPalette.h
https://github.com/material-components/material-components-ios/blob/fdfb54f/components/Themes/src/MDCTonalPalette.m

NSSecureCoding documentation:
https://developer.apple.com/documentation/foundation/nssecurecoding?language=objc
http://nshipster.com/nssecurecoding/

**Comment by ianegordon** [comment]
Audit our components to ensure that all are conforming to NSSecureCoding.
Context in the links above.
MDCTonalPalette is an example where we are not.

**Comment by mohammadcazig** [comment]
All tracked and done.
