### ISSUE TITLE
[Typography] UIAccessibilityIsBoldTextEnabled should affect font weight

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#2905]
`[+ UIFont mdc_preferredFontForMaterialTextStyle:]` should return a heavier-weighted font.

b/69049139

---
#### Internal data
- Associated internal bug: [b/117179539](http://b/117179539)

**Comment by romoore** [comment]
Adding the UIFontWeightTrait to the descriptors appears to do nothing. UIFont is already returning `.SFUIText-Semibold` instead of `.SFUIText` when the setting is enabled.  Asking for side-by-side reproduction steps and expected results on the internal ticket.

**Comment by material-mirror** [comment]
The internal issue [b/117179539](http://b/117179539) is now closed. This issue is being closed as a result.
