### ISSUE TITLE
Ensure that all MDC classes that implement -isEqual: also implement -hash ⚠️

### ISSUE THREAD

**Issue by stephanemoore** [material-components/material-components-ios#2908]
"If two objects are equal, they must have the same hash value. This last point is particularly important if you define isEqual: in a subclass and intend to put instances of that subclass into a collection. Make sure you also define hash in your subclass."
https://developer.apple.com/documentation/objectivec/1418956-nsobject/1418795-isequal?language=objc

---
#### Internal data
- Associated internal bug: [b/72971974](http://b/72971974)

**Comment by ianegordon** [comment]
TODO: Audit MDC, open bugs against individual components

**Comment by material-mirror** [comment]
The internal issue [b/72971974](http://b/72971974) is now closed. This issue is being closed as a result.
