### ISSUE TITLE
[BottomNavigation]  Abandoned ink persists in bottom navigation bar after rotation (b/73060904)

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#2909]
Originally reported by @brianjmoore 

### Overview
The bottom navigation bar can sometimes end up with abandoned ink that sticks around seemingly indefinitely.

![bottomnav-ink-bug](https://user-images.githubusercontent.com/1753199/35926175-8b51d440-0bf5-11e8-9f59-e44237cbb41d.PNG)

### Reproduction steps
1. Build and run the MDC catalog
2. Open the bottom nav example
3. Touch one of the tabs and while holding rotate the device

RESULT: Ink is abandoned, sticks around indefinitely.

### Version number
44.6.0

### Operating system and device
iPhone 5/iOS 10.3.3

**Comment by brianjmoore** [comment]
Seems to be a general touch-cancelling thing? This also happens very easily on iPhone X if you just swipe up on the home indicator while you're touching the tab.

**Comment by romoore** [comment]
It would be good to test this with "legacy ink" first to narrow the scope of the problem.
