### ISSUE TITLE
Should clarify contributing instructions for normal and core contributors

### ISSUE THREAD

**Issue by jmstriegel** [material-components/material-components-ios#291]
Just went through code review process for the first time and had to wrestle few a number of things (needed major help from someone who'd been here before). This is my recollection of the big stumbling points:
- installing arc
- some clang and other plugins for arc
- updating and re-permissioning brew
- existence of arc diff, how to properly use it, etc.
- xcode lint-friendly settings
- podfile locks needing to be reverted and re-installed before/after arc diffing

If we're recommending this process externally:
- thoroughly document the installation for the above
- create a quick guide in contributing(?) to walk through the usual steps taken for code submission and review
-  should include recommendations for branch/workflow in git that will work well with arc

If we're also allowing users to submit using pull requests:
- document xcode settings
- document how to auto-lint code manually, before submission

**Comment by ianegordon** [comment]
Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄
