### ISSUE TITLE
[ActivityIndicator] setProgress should not animate

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#2910]
In order to be consistent with UIProgressBar, setting activityIndicator.progress should not animate.

We should add:
- (void)setProgress:animated:

setProgress: should call the method above with animated: parameter set to NO.

We will have to update internal clients.

---
#### Internal data
- Associated internal bug: [b/117179226](http://b/117179226)

**Comment by romoore** [comment]
I'm not sure this is a "Fixit" bug given that we will need to update internal clients.  Removing the label for now, but we can re-add it if the internal work can be done separately.

**Comment by material-mirror** [comment]
The internal issue [b/117179226](http://b/117179226) is now closed. This issue is being closed as a result.
