### ISSUE TITLE
Implement prepareForReuse on MDCChipCollectionViewCell

### ISSUE THREAD

**Issue by jmdetloff** [material-components/material-components-ios#2914]
Include prepare for reuse on this cell, to reset the font.

- (void)prepareForReuse {
  [super prepareForReuse];
  self.chipView.titleFont = nil;
}

**Comment by ianegordon** [comment]
Directly setting this property will break anything explicitly set in the UIAppearance proxy.

**Comment by mohammadcazig** [comment]
I believe clients should handle this themselves, either in tableview data source or implementing prepare for reuse in a subclass.
