### ISSUE TITLE
[Dialogs] Black boxes appear around dialogs during rotation.

### ISSUE THREAD

**Issue by danblakemore** [material-components/material-components-ios#2915]
### Overview
Black box(es) appear around dialogs during rotation.

Internal issue b/73121486.

### Reproduction steps
 - Present a dialog.
 - Rotate the phone.
Expected Results
 Dialog appears to simply rotate in place.
Actual Results
 Black boxes appear around the dialog during the rotation animation.

### Version number
 - 44.6.0

### Operating system and device
 - iOS 11, iPhone/iPad.

### Related issues
 - #2824 

---
#### Internal data
- Associated internal bug: [b/117179518](http://b/117179518)

**Comment by ianegordon** [comment]
I'm unable to repro this in develop.  It is possible that rolling back our Motion integration eliminated this issue.
Can you still repro?

![dialogrotation-original](https://user-images.githubusercontent.com/1121006/37119422-56e46024-2225-11e8-88a7-4582c484b544.gif)

**Comment by danblakemore** [comment]
I cannot (just pulled and verified).

I can still see #2824.  Was the rollback only for dialogs?

**Comment by material-mirror** [comment]
The internal issue [b/117179518](http://b/117179518) is now closed. This issue is being closed as a result.
