### ISSUE TITLE
Icons collisions possible 

### ISSUE THREAD

**Issue by randallli** [material-components/material-components-ios#2917]
Icons we offer via MDCIcons may collide with  other icons:

internal bug: b/73132837

**Comment by romoore** [comment]
Let's try to add a test to cover the possibility of a nil bundle coming back in [`[MDCIcon bundleNamed]`](https://github.com/material-components/material-components-ios/blob/develop/components/private/Icons/src/MDCIcons.m#L34)

**Comment by ianegordon** [comment]
This is caused by icon de-duplication as part of our internal build process.
It is out of scope of MDC-iOS.
