### ISSUE TITLE
UIColor not Equal after archiving and unarchiving.

### ISSUE THREAD

**Issue by mohammadcazig** [material-components/material-components-ios#2931]
When Archiving and Unarchiving UIColor equality tests fail. The issue seem to be due to the fact that archiving happens with float precision but the equality test happens in double precision when ran on 64bits. This seem to be a bug on apple side:
Here is discussion related to this issue:
https://stackoverflow.com/questions/22338594/why-does-this-code-behave-differently-on-64-bit-builds-ios-uicolor-uikeyed

**Comment by romoore** [comment]
@mohammadcazig Is this something that we can fix? It seems UIColor has been like this for a long time.  Should we open a Radar with Apple to track or should we add some documentation to our checklist?

**Comment by ianegordon** [comment]
Unfortunately this is not something we can fix on our side.  I would update the checklist / docs as a known issue in iOS and close this issue.

**Comment by mohammadcazig** [comment]
Added a tip to our checklist.

**Comment by romoore** [comment]
Where was the tip added? I don't see any edits around March 15 in the public checklist.
