### ISSUE TITLE
[BottomNavigation] MaterialBottomNavigation.strings missing license stanza

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#2938]
### Overview
MaterialBottomNavigation.strings is missing the copyright stanza at the top of the file. Since this is content/source, it should include a copyright notice.

### Version number
45.0.0

---
#### Internal data
- Associated internal bug: [b/117179320](http://b/117179320)

**Comment by material-mirror** [comment]
The internal issue [b/117179320](http://b/117179320) is now closed. This issue is being closed as a result.
