### ISSUE TITLE
Discuss our supported release contract

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#294]
### Context

We cut releases once a week and generally support the latest release at all times. There will be clients that stay on older releases for a number of reasons. We need to discuss and communicate what the oldest release we support is.
### The missing functionality

We need a doc explaining our support contract.
We need an agreement on how far back we want to support.
### Potential work ahead

One suggestion: support the last two major releases and their corresponding minor/patch releases.

**Comment by ianegordon** [comment]
Internal clients are always on the latest version.
External clients are able to pick and choose.
Opened more than two years ago.
Please re-open if you feel strongly.
