### ISSUE TITLE
[ButtonBar] MDCButtonBarDelegate cannot be used

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#2943]
### Overview
MDCButtonBar has a protocol (MDCButtonBarDelegate) which does not have a corresponding property for clients to set. There is a single implementation which is hard-coded or use within MDCButtonBar.

Clients should be able to implement the protocol (and act as a Builder) and return views for button items.

### Version number
45.0.0

**Comment by jverkoey** [comment]
This API is not intended to be used for implementing builders publicly, so I will be marking its sole method as deprecated accordingly.
