### ISSUE TITLE
[CocoaPods] IB_DESIGNABLE auto layout render issues

### ISSUE THREAD

**Issue by yarneo** [material-components/material-components-ios#2946]
When adding an IB_DESIGNABLE component to one of our xibs/storyboards, an error comes up in xcode. The error states that it fails to render and update auto layout status for the UIView due to the MDFInternationalization library not loaded. Reason is image not found. 

I suspect this could be a CocoaPods issue, but this needs further investigation.

---
#### Internal data
- Associated internal bug: [b/140930518](http://b/140930518)

**Comment by yarneo** [comment]
This is indeed a CocoaPods issue with the build settings; needing to add the frameworks to the runpath search paths

**Comment by jverkoey** [comment]
Material libraries for iOS entered maintenance mode as of July 15, 2021. Learn more at https://github.com/material-components/material-components-ios#material-components-for-ios.
