### ISSUE TITLE
[Collections] MDCCollectionViewCell contentView overlaps shadow

### ISSUE THREAD

**Issue by ssar** [material-components/material-components-ios#2951]
When using a subclass of MDCCollectionViewCell in an MDCCollectionView with cell style MDCCollectionViewCellStyleCard, the cell contentView overlaps the added shadow.
There seems to be no easy way to get the available content frame. This is especially important when adding custom subviews to the contentView.

**Comment by ianegordon** [comment]
We are not intending on any significant updates to the current Collections component. 😞
We are working on a much simpler [List component](https://github.com/material-components/material-components-ios/tree/develop/components/List). 😄
