### ISSUE TITLE
[Pesto] Settings App Bar shadow absent in iOS 9-10, broken in iOS 11

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#2952]
### Overview
The Pesto Settings screen's app bar does not show the drop-shadow when the setting collection view is scrolled behind it. On iOS 10 and below, the shadow is completely absent. On iOS 11 it only shows in Portrait orientation and only after rotating the screen at least once.

![pesto-ios11](https://user-images.githubusercontent.com/1753199/36314248-3ac6b0c2-1302-11e8-887a-e8791039df3a.gif)

I cannot reproduce this issue in the MDC Catalog app, so I expect it's a mistake in how the Pesto app is configuring the app bar.

### Reproduction steps
1. Launch Pesto
1. Tap on "Gear" icon to open settings
1. Scroll the collection view and note the shadow under the app bar
1. Rotate the device to landscape, back to portrait
1. Scroll again and note the app bar shadow

### Version number
45.0.0

### Operating system and device
iOS 10 and below - completely broken
iOS 11 and above - partially broken

---
#### Internal data
- Associated internal bug: [b/117179302](http://b/117179302)

**Comment by material-mirror** [comment]
The internal issue [b/117179302](http://b/117179302) is now closed. This issue is being closed as a result.
