### ISSUE TITLE
[TextFields] MDCTextInputControllerLegacyDefault placeholder color wrong on initial active

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#2965]
The placeholder label is not changing to the `self.activeColor` when it becomes first responder. It will change colors if there is an error and then the error is removed.

See Zip Code. It should be amber.
![simulator screen shot - iphone 6s plus - 2018-02-16 at 19 10 50](https://user-images.githubusercontent.com/1271525/36335325-1f6e1770-134d-11e8-9087-564e25b03a48.png)

**Comment by mohammadcazig** [comment]
Already fixed.
