### ISSUE TITLE
[Slider] Anchored slider should have hollow circle at anchor point

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#2970]
### Overview
An anchored Slider currently shows a "hollow" circle at the minimum value. Instead, it should be "hollow" at the anchor point. 

![mdcslider-anchored-min1-max2](https://user-images.githubusercontent.com/1753199/36444947-b11eca5c-164a-11e8-88f8-1d86fcd01a71.png)

### Reproduction steps
1. Create an MDCSlider with a minimum of 1, maximum of 2, anchor point of 1.5, value of 1.5
2. Look at it. The "hollow" circle should be at the anchor point.

### Version number
45.0.0

---
#### Internal data
- Associated internal bug: [b/117179055](http://b/117179055)

**Comment by material-mirror** [comment]
The internal issue [b/117179055](http://b/117179055) is now closed. This issue is being closed as a result.
