### ISSUE TITLE
 MDCSnackbarManager.show(message), shows at UIAlertController instead of bottom

### ISSUE THREAD

**Issue by niravdesai** [material-components/material-components-ios#2980]
### Overview
For usage questions: ask on [Stack  Overflow](https://stackoverflow.com/questions/tagged/material-components+ios).

` let message = MDCSnackbarMessage()
 message.duration = 10.0
message.text = msg
MDCSnackbarManager.show(message)`
 
works fine normally at the bottom but if this UIAlertController comes when the Snackbar is still shown the snackbar frame moves to the bottom of UIAlertController frame.

`let alertController = UIAlertController(title: "Failed?", message: appStatus!["error"] as? String, preferredStyle: .alert)
let defaultAction = UIAlertAction(title: "OK", style: .default, handler: nil)
        alertController.addAction(defaultAction)`

---
#### Internal data
- Associated internal bug: [b/117179319](http://b/117179319)

**Comment by KingOfBrian** [comment]
This isn't a fix, but if you use an `MDCOverlayWindow` as your apps window, the snack will show up as expected, not inside the UIAlertController.

**Comment by jverkoey** [comment]
Un-assigning due to inactivity. Please re-assign if you are working on this.

**Comment by material-mirror** [comment]
The internal issue [b/117179319](http://b/117179319) is now closed. This issue is being closed as a result.

**Comment by benedictchen** [comment]
Why is material-mirror showing an Google-internal buganizer link?
