### ISSUE TITLE
[TextFields] Add unit test for placeholder changing when textInsets: returns a new value

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#2997]
Related to #2989 

* What the constraint values should be given different textField (and _textInput) states.
* When updateConstraints needs to be called.

---
#### Internal data
- Associated internal bug: [b/117179077](http://b/117179077)

**Comment by material-mirror** [comment]
The internal issue [b/117179077](http://b/117179077) is now closed. This issue is being closed as a result.
