### ISSUE TITLE
[NavigationBar] Support custom inkColor

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3007]
### Overview
MDCNavigationBar has no public property that enables setting inkColor for its subviews. There should be a single public property (`inkColor`) that will update the ink color for all subviews in the NavigationBar except for `titleView`, since that is a custom UIView set by the user.

### Version number
45.0.0

**Comment by jverkoey** [comment]
This is done:

https://github.com/material-components/material-components-ios/blob/f1b8cef7c8186bf5932b6ec4b52de487d2a70c6b/components/NavigationBar/src/MDCNavigationBar.h#L155-L160
