### ISSUE TITLE
[Cards] Edit/Reorder example cannot reorder on iOS 8.1

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3021]
### Overview
I was trying the Edit/Reorder example on an iPhone 5/iOS 8.1 (Simulator) and was unable to get drag-and-drop reordering to work.

### Reproduction steps
1. Launch the catalog on an iOS 8.1 device or simulator
1. Open Cards&rarr;Edit/Reorder (Swift)
1. When the navigationbar button says, "Reorder", try to drag-and-drop cards

### Version number
46.0.0

### Operating system and device
iPhone 5/iOS 8.1 (Simulator)

---
#### Internal data
- Associated internal bug: [b/117179261](http://b/117179261)

**Comment by RahulSriram** [comment]
+1 was about to post an issue myself, this issue also exists in the swipe to delete function
the app crashes when swiping or reordering with this stack trace

*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndexedSubscript:]: index 1 beyond bounds [0 .. 0]'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010ce1e12b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010c4b2f41 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010ce5e0cc _CFThrowFormattedException + 194
	3   CoreFoundation                      0x000000010ce4f9cf -[__NSArrayM objectAtIndexedSubscript:] + 175
	4   UIKit                               0x000000010a9067ad -[UICollectionViewFlowLayout _getSizingInfosWithExistingSizingDictionary:] + 1735
	5   UIKit                               0x000000010a9086b0 -[UICollectionViewFlowLayout _fetchItemsInfoForRect:] + 136
	6   UIKit                               0x000000010a901077 -[UICollectionViewFlowLayout prepareLayout] + 272
	7   UIKit                               0x000000010a92e0e5 -[UICollectionViewData _prepareToLoadData] + 156
	8   UIKit                               0x000000010a92e992 -[UICollectionViewData validateLayoutInRect:] + 53
	9   UIKit                               0x000000010a8c3bb9 -[UICollectionView layoutSubviews] + 260
	10  UIKit                               0x0000000109eb7a6d -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1439
	11  QuartzCore                          0x000000010906261c -[CALayer layoutSublayers] + 159
	12  QuartzCore                          0x00000001090667ad _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 401
	13  UIKit                               0x0000000109ea17ca -[UIView(Hierarchy) layoutBelowIfNeeded] + 662
	14  testApp                         0x0000000105cf4c71 _T011testApp35MyPracticesCollectionViewControllerC010collectionF0SC6CGSizeVSo012UICollectionF0C_So0jF6LayoutC6layout10Foundation9IndexPathV13sizeForItemAttF + 81
	15  testApp                         0x0000000105cf4d7a _T011testApp35MyPracticesCollectionViewControllerC010collectionF0SC6CGSizeVSo012UICollectionF0C_So0jF6LayoutC6layout10Foundation9IndexPathV13sizeForItemAttFTo + 122
	16  UIKit                               0x000000010a906c9b -[UICollectionViewFlowLayout _getSizingInfosWithExistingSizingDictionary:] + 2997
	17  UIKit                               0x000000010a9086b0 -[UICollectionViewFlowLayout _fetchItemsInfoForRect:] + 136
	18  UIKit                               0x000000010a901077 -[UICollectionViewFlowLayout prepareLayout] + 272
	19  UIKit                               0x000000010a92e0e5 -[UICollectionViewData _prepareToLoadData] + 156
	20  UIKit                               0x000000010a8d431e -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:] + 12822
	21  UIKit                               0x000000010a8ddac1 -[UICollectionView _endUpdatesWithInvalidationContext:tentativelyForReordering:animator:] + 71
	22  UIKit                               0x000000010a8dde06 -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:animator:] + 435
	23  UIKit                               0x000000010a8ddc30 -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:] + 91
	24  UIKit                               0x000000010a8ddbb2 -[UICollectionView _performBatchUpdates:completion:invalidationContext:] + 74
	25  UIKit                               0x000000010a8ddb07 -[UICollectionView performBatchUpdates:completion:] + 53
	26  MaterialComponents                  0x00000001087b781b -[MDCCollectionViewController deleteIndexPaths:] + 395
	27  MaterialComponents                  0x00000001087b74c4 -[MDCCollectionViewController collectionView:didEndSwipeToDismissItemAtIndexPath:] + 180
	28  MaterialComponents                  0x00000001087bddd7 -[MDCCollectionViewEditor animateFinalItemDismissalToTranslationX:] + 503
	29  MaterialComponents                  0x00000001087bd9e6 -[MDCCollectionViewEditor panToDismissWithRecognizer:] + 3718
	30  MaterialComponents                  0x00000001087bc280 -[MDCCollectionViewEditor handlePanGesture:] + 112
	31  UIKit                               0x000000010a3e7273 -[UIGestureRecognizerTarget _sendActionWithGestureRecognizer:] + 57
	32  UIKit                               0x000000010a3f01aa _UIGestureRecognizerSendTargetActions + 109
	33  UIKit                               0x000000010a3ed9ba _UIGestureRecognizerSendActions + 307
	34  UIKit                               0x000000010a3ecc26 -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:] + 1002
	35  UIKit                               0x000000010a3d199c _UIGestureEnvironmentUpdate + 1329
	36  UIKit                               0x000000010a3d141f -[UIGestureEnvironment _deliverEvent:toGestureRecognizers:usingBlock:] + 484
	37  UIKit                               0x000000010a3d04cb -[UIGestureEnvironment _updateGesturesForEvent:window:] + 288
	38  UIKit                               0x0000000109e5ef14 -[UIWindow sendEvent:] + 4102
	39  UIKit                               0x0000000109e02365 -[UIApplication sendEvent:] + 352
	40  UIKit                               0x000000010a74ea1d __dispatchPreprocessedEventFromEventQueue + 2809
	41  UIKit                               0x000000010a751672 __handleEventQueueInternal + 5957
	42  CoreFoundation                      0x000000010cdc1101 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	43  CoreFoundation                      0x000000010ce60f71 __CFRunLoopDoSource0 + 81
	44  CoreFoundation                      0x000000010cda5a19 __CFRunLoopDoSources0 + 185
	45  CoreFoundation                      0x000000010cda4fff __CFRunLoopRun + 1279
	46  CoreFoundation                      0x000000010cda4889 CFRunLoopRunSpecific + 409
	47  GraphicsServices                    0x0000000110ed69c6 GSEventRunModal + 62
	48  UIKit                               0x0000000109de65d6 UIApplicationMain + 159
	49  testApp                         0x0000000105ca0417 main + 55
	50  libdyld.dylib                       0x000000010e65ed81 start + 1
	51  ???                                 0x0000000000000001 0x0 + 1

**Comment by romoore** [comment]
@RahulSriram I think your issue may be different from this one. As far as I know, the Card reorder/edit example does not have swipe-to-dismiss enabled.  Your crash looks like it's a bug in Collections. I'll copy your report to a new Issue for that component.

**Comment by ianegordon** [comment]
@yarneo Since Re-order capability isn't available on iOS8, please disable / hide the toggle on iOS 8.

**Comment by jverkoey** [comment]
Un-assigning due to inactivity. Please re-assign if you are still working on this.

**Comment by material-mirror** [comment]
The internal issue [b/117179261](http://b/117179261) is now closed. This issue is being closed as a result.
