### ISSUE TITLE
[FeatureHighlight] Setting `titleColor` or `bodyColor` via UIAppearance does not work

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3023]
### Overview
Setting the UIAppearance proxy values for `MDCFeatureHighlightView.bodyColor` and `MDCFeatureHighlightView.titleColor` does nothing when using `MDCFeatureHighlightViewController` because the VC will inspect their values in `viewWillAppear` (before UIAppearance) and will reassign new values instead.  The logic for this behavior&mdash;checking the `backgroundColor` and computing an accessible color&mdash;will also fail when UIAppearance is used for the `backgroundColor` property of the FHV.

It would make more sense (and match other components like Buttons) to extract the accessible text color behavior into a **Mutator** object and allow clients to decide if they're going to use it or not.

### Reproduction steps
1. Set the `titleColor` and `bodyColor` values on `MDCFeatureHighlightView` via UIAppearance
1. Use the `MDCFeatureHighlightViewController` to present a FHV

Expect that the `titleColor` and `bodyColor` values match the UIAppearance proxied values.

### Version number
46.0.0

### Operating system and device
iPhone 5/iOS 8.1 (Simulator)

**Comment by ianegordon** [comment]
+1 to having this be opt-in behavior via a mutator.

We can also query the UIAppearance proxy to see if a value has been set, which can happen in viewWillAppear:

**Comment by romoore** [comment]
We could design the mutator to accept a FHVC and FHV (both appearance proxies) and use the FHV as the backup color values if the FHVC doesn't have one.
