### ISSUE TITLE
[Collections] Rotating device causes crash

### ISSUE THREAD

**Issue by RahulSriram** [material-components/material-components-ios#3024]
### Overview
When device orientation changes, the collectionviewcontroller crashes trying to adapt to the new orientation

### Reproduction steps
 - Create a CollectionViewController in a storyboard
 - Link it to an MDCCollectionViewController sub-class
 - Set some data in the datasource, and run app & rotate screen

### Version number
 - 46.1

### Operating system and device
iPhone 8 Plus simulator - iOS 11.2

**Comment by RahulSriram** [comment]
This issue is fixed after changing
```
func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
    return CGSize(width: collectionView.bounds.size.width, height: 80.0)
}
```
to this
```
override func collectionView(_ collectionView: UICollectionView, cellHeightAt indexPath: IndexPath) -> CGFloat {
        return 80
    }
```

**Comment by ianegordon** [comment]
We are not intending on any significant updates to the current Collections component. 😞
We are working on a much simpler [List component](https://github.com/material-components/material-components-ios/tree/develop/components/List). 😄
