### ISSUE TITLE
Provide best-practice recommendations for Flexible Header

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#303]
There are a number of configurable properties on the Flexible Header/App Bar. We should provide some best practices of when to use certain configurations.
### Best practices
- [ ] Settings screens should never enable the shift behavior.
- [ ] Shift behavior should generally only be used to showcase content. Typically these are the main application experiences, such as the Photos app's photos and albums screens.
- [ ] The App Bar's `headerStackView.bottomBar` property is generally reserved for Tab Bars.

---
#### Internal data
- Associated internal bug: [b/117179561](http://b/117179561)

**Comment by material-mirror** [comment]
The internal issue [b/117179561](http://b/117179561) is now closed. This issue is being closed as a result.
