### ISSUE TITLE
[TextFields] Base controller overwrites decoded values

### ISSUE THREAD

**Issue by sigito** [material-components/material-components-ios#3034]
When an `initWithCoder:` is called on `MDCTextInputControllerBase`, at one point of the constructor it calls `commonMDCTextInputControllerBaseInitialization`, which overwrites just decoded values for:

- [ ] `disabledColor`;
- [ ] `expandsOnOverflow`;
- [ ] `isFloatingEnabled`;
- [ ] `minimumLines`;
- [ ] `underlineHeightActive`;
- [ ] `underlineHeightNormal`;
- [ ] `underlineViewMode`.

**Comment by sigito** [comment]
There already checks for other variables changed in the common init, like:
```
if ([aDecoder containsValueForKey:MDCTextInputControllerBaseCharacterCountMaxKey]) {
  _characterCountMax =
      [aDecoder decodeIntegerForKey:MDCTextInputControllerBaseCharacterCountMaxKey];
}
```
Should the same be added for the rest of the variables?

**Comment by mohammadcazig** [comment]
We do not maintaining or dowing extra work to support encoding/decoding view states anymore.
