### ISSUE TITLE
AppBar/HeaderStackView hides top bar when adding a bottom bar

### ISSUE THREAD

**Issue by samskiter** [material-components/material-components-ios#3038]
### Overview

 - Context, problem or idea, solution or next step
I've added an app bar to a view controller and constrained the main content to the top layout guide - no problem. Then I've tried to add a bottom bar and I've had a few issues:

1. The bottom bar I'm adding is fully constrained use autolayout, but the `HeaderStackView` [uses `sizeThatFits()`](https://github.com/material-components/material-components-ios/blob/e68fff55dea351fe49e61bdaf2eabf676b9d1e99/components/HeaderStackView/src/MDCHeaderStackView.m#L24) to measure the bottom bar. It would be great if the requirement for this method to be implemented could be included in [the usage section of the readme](https://github.com/material-components/material-components-ios/tree/develop/components/HeaderStackView#usage).

2. After fixing the above the bottom bar is displayed but the app bar is translated up. [`layoutSubviews()` in the `HeaderStackView`](https://github.com/material-components/material-components-ios/blob/e68fff55dea351fe49e61bdaf2eabf676b9d1e99/components/HeaderStackView/src/MDCHeaderStackView.m#L49) seems to be the issue as "Negative value causes the top bar to slide up and away." I suspect this could be because I'm adding the bottom bar asynchronously - is there any way to force the bar to be remeasured?

Essentially this is about the AppBar/HeaderStackView supporting views that use autolayout (that may change size)

### Reproduction steps
 - Detailed steps to reproduce
I set this up by following the instructions:

- Add the app bar as a child view controller
- Call `navigationController?.setNavigationBarHidden(true, animated: animated)` in `viewWillAppear()`
- Call `appBar.addSubviewsToParent()` in `viewDidLoad()`
- Call `appBar.headerViewController.updateTopLayoutGuide()` in `viewWillLayoutSubviews()`
- Constraint my view controller's content to the `topLayoutGuide`
- Assign a view to the bottom bar: `appBar.headerStackView.bottomBar = blah`

(feel free to ping me on hangouts chat (samduke@) if you need any more information!

### Version number
`MaterialComponents (44.6.0)` (from podfile.lock)

### Operating system and device
macOS High Sierra 10.13.2 
XCode Version 9.2 (9C40b)
Simulator iPhone 7 iOS 11.2

---
#### Internal data
- Associated internal bug: [b/117179419](http://b/117179419)

**Comment by samskiter** [comment]
Seems that you need to manually set the minimum and maximum height on the flexible header view to solve this. I would expect the app bar to be able to handle all this. There is knowledge about the height of the top and bottom bars in [layoutSubviews() in the HeaderStackView](https://github.com/material-components/material-components-ios/blob/develop/components/HeaderStackView/src/MDCHeaderStackView.m#L59) so it seems theres something missing in terms of passing that information to the flexible header

**Comment by samskiter** [comment]
Regarding autolayout and sizeThatFits. I believe that `systemLayoutSizeFitting` is smart enough to know to call `sizeThatFits` if the called view is not laid out with autolayout and that might be the better method to call:

https://asciiwwdc.com/2014/sessions/226

>And systemLayoutSizeFittingSize is smart enough to understand if you've implemented constraints in your cell and if so, the Autolayout engine delivers the size.
>And if you haven't implemented Autolayout constraints, systemLayoutSizeFittingSize calls sizeThatFits.

**Comment by jverkoey** [comment]
Summarizing what we just discussed offline:

Ideally the App Bar can be configured such that it's able to automatically adjust the min/max height of the flexible header based on the presence of a top/bottom bar.

**Comment by jverkoey** [comment]
To address point #1:
- We should support systemLayoutSizeFitting.

**Comment by jverkoey** [comment]
Down-grading this from client blocking because there exists alternative solutions.

**Comment by samskiter** [comment]
@jverkoey Just to confirm, the suggested solution of managing min/max height is:

- build callbacks from our custom bottom bar view back to the app bar container to indicate it may require laying out
- when the callback is received, size the bottom bar by using systemLayouSizeFitting/sizeThatFits and use that to set the min/max height

**Comment by jverkoey** [comment]
Correct - we're working on implementing a similar set of APIs in the AppBar logic (see 471936b842e7473e51b5dc02df619a7e67a0c5b2 for the first part of this in ButtonBar).

**Comment by samskiter** [comment]
Regarding:

>We need to add this delegate because I'm not aware of an equivalent UIKit
mechanism that works with views that aren't using auto layout

Can I ask what the mechanism that works with view that **are** using
autolayout is?

**Comment by jverkoey** [comment]
Are you able to hook in to the invalidateIntrinsicContentSize API?

**Comment by samskiter** [comment]
I don't think so, are you saying you could observe invalidateIntrinsicContentSize being called on subviews?

**Comment by jverkoey** [comment]
Concretely this would mean detecting when your custom bottom view’s height has changed (via delegate) and updating the min/max height accordingly.

**Comment by samskiter** [comment]
Sure, sorry, I was particularly honing in on your comment that implied there is some way of detecting intrinsic content size change in a subview.... Did you mean perhaps overriding layoutSubviews or updateConstraints? Would that work?

**Comment by material-mirror** [comment]
The internal issue [b/117179419](http://b/117179419) is now closed. This issue is being closed as a result.
