### ISSUE TITLE
[ButtonBar] Support UIAppearance and color theming

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3053]
### Overview
MDCButtonBar does not currently support any `UI_APPEARANCE_SELECTOR` properties or methods in its public header.  For color theming, it should expose:

* barTintColor - sets the `backgroundColor` of the buttonBar
* buttonTintColor - sets the `tintColor` of the buttonBar and updates the `tintColor` and `titleColor`  (for `.normal` state) on the buttons
* buttonInkColor - sets the `inkColor` of the buttons in the buttonBar

### Version number
46.1.1

**Comment by ianegordon** [comment]
We are not intending on any significant updates our UIAppearance support. 😞
