### ISSUE TITLE
[Ink] (New) Ink does not cover resized views.

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3056]
### Overview
When Chips are tapped, they trigger an Ink ripple and may resize to accommodate a check mark or other selection image. When this happens the "new" ink animation does not fill the bounds of the newly-resized Chip.

![ink-resize-bug](https://user-images.githubusercontent.com/1753199/37103925-658198e4-21f9-11e8-938d-8c6cf1615609.gif)

### Reproduction steps
1. Open the catalog
1. Navigate to Chips &rarr; Filter
1. Tap on a Chip to select it

### Version number
46.1.1

### Related issues
#754, #2835

---
#### Internal data
- Associated internal bug: [b/117179459](http://b/117179459)

**Comment by romoore** [comment]
This is a bug in Ink (see related issues) and I won't be able to get it it immediately.

**Comment by material-mirror** [comment]
The internal issue [b/117179459](http://b/117179459) is now closed. This issue is being closed as a result.
