### ISSUE TITLE
[Dialogs] MDCAlertController should support UIAppearance color properties for its views

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3057]
### Overview
To support color theming of MDCAlertController-presented views, MDCAlertController should provide several new UIAppearance-proxied properties. 

Consider:
* `alertBackgroundColor` - `backgroundColor` of the content view of the alert
* `alertShadowColor` - the color of the alert's shadow
* `titleColor`(or `titleTextAttributes`) - the color (or all attributes) of the title text 
* `messageColor` (or `messageTextAttributes`) - the color (or all attributes) of the message text

### Version number
46.1.1

### Related issues
#2788

**Comment by ianegordon** [comment]
We are not intending on any significant updates our UIAppearance support. 😞
