### ISSUE TITLE
[BottomSheet] Black background on rotation

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#3060]
There is an unexpected black box rendered over the background when rotating an interface with a presented BottomSheet.

Repro:
MDCCatalog -> BottomSheet -> Demo
Click the Show bottom sheet button
Rotate the device
Note the strange black box than gets rendered.

Internal Tracking bug:
b/74221540

**Comment by romoore** [comment]
Related to #2824 ?

**Comment by ianegordon** [comment]
Indeed, duplicate of #2824
