### ISSUE TITLE
[Chips] As a developer using Input Chips, I want an API to edit Chips in a ChipField

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3072]
### Overview
Chips should provide clear guidance on how clients can implement editing of Input Chips after they are created. For instance, if a user taps on an Input Chip, the app can present an interface for Chip editing. Once finished, the new information needs to be stored in the Chip and the ChipField has to be updated.  A simple demonstration of setting a new `title` on the Chip and forcing a ChipField to layout results in the textfield's placeholder label being mispositioned.

**Chips/ChipField should provide and document the API for editing the contents of an already-created Chip.**

```objectivec
- (void)chipField:(nonnull MDCChipField *)chipField didTapChip:(nonnull MDCChipView *)chip {
  chip.titleLabel.text = @"Changed";
  [chipField setNeedsLayout];
}
```

![chipfield-change-layout](https://user-images.githubusercontent.com/1753199/37211641-99d573cc-237a-11e8-9f29-dbab234c7e30.gif)

### Version number
46.1.1

### Operating system and device
iPhone 4s/iOS 8.1 (Simulator)

---
#### Internal data
- Associated internal bug: [b/117179110](http://b/117179110)

**Comment by material-mirror** [comment]
The internal issue [b/117179110](http://b/117179110) is now closed. This issue is being closed as a result.

**Comment by anuragfluke** [comment]
I am also looking for same functionality... attached video from material design site.. can you please let us know... how to implement that ?
