### ISSUE TITLE
[Tabs] MDCTabBar badges should have a background similar to Bottom Navigation

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3077]
### Overview
Tabs currently support a simple "badge" where just a label is shown. To permit sufficient differentiation between the label+icon and the badge text, a background circle/pill shape similar to BottomNavigation should be supported.

**Tabs**
![tabs-badge](https://user-images.githubusercontent.com/1753199/37300774-3854de50-25fd-11e8-9903-ea3e3f64464a.png)

**BottomNavigation**
![bottomnav-badge](https://user-images.githubusercontent.com/1753199/37300779-3ac4b958-25fd-11e8-82d9-c268d65c4fee.png)

### Version number
46.1.1

---
#### Internal data
- Associated internal bug: [b/117178917](http://b/117178917)

**Comment by mohammadcazig** [comment]
Tabs badge is UITabBarItem badge property and out of our access there are ways to implement the background for the badge but I don't think that should be in the scope of Tabs, we could create a MDCTabBarItem. Let me know what you think.
