### ISSUE TITLE
[TextFields] MDCTextField less responsive with MDCTextInputControllerUnderline

### ISSUE THREAD

**Issue by gmann1** [material-components/material-components-ios#3088]
The textfield becomes a lot less responsive to touch events.I have to click the upper portion of the text field to get it to register.

e.g. when I type text in and click the X on the right I have to click the top of the X and clicking the dead center of it does nothing.

Basically any touch event below the top 30% of the view doesn't do anything.

v46.1.0

OS 11.3 and 11.2.6

**Comment by willlarche** [comment]
Can you open an inspector like Reveal or the view inspector in Xcode and verify nothing is in the way and that the frame encompasses the entire MDCTextField? I'm not able to reproduce.

**Comment by gmann1** [comment]
![withcontroller](https://user-images.githubusercontent.com/6133289/37368211-d2ddd4c0-26c2-11e8-8591-59e228b8d7e6.png)
![withoutcontroller](https://user-images.githubusercontent.com/6133289/37368212-d2fa7666-26c2-11e8-80f3-002c7cb61eda.png)

One image has the controller the other does not. The blue area in each image is the MDCTextInputBorderView. It seems anything outside of that area doesn't register touch events. There are no other views blocking.

Also, not sure why, but in this mode it enlarged the X 🤷‍♂️

**Comment by willlarche** [comment]
Can you post any of the layout code?

**Comment by gmann1** [comment]
@willlarche 

`<scenes>
        
        <scene sceneID="g6N-dF-xHl">
            <objects>
                <viewController id="Kbp-8m-Ed9" customClass="LoginViewController" customModule="omni" customModuleProvider="target" sceneMemberID="viewController">
                    <view key="view" contentMode="scaleToFill" id="bKZ-Zr-XeW">
                        <rect key="frame" x="0.0" y="0.0" width="320" height="480"/>
                        <autoresizingMask key="autoresizingMask" widthSizable="YES" heightSizable="YES"/>
                        <subviews>
                            <textField opaque="NO" contentMode="scaleToFill" verticalHuggingPriority="1000" contentHorizontalAlignment="left" contentVerticalAlignment="center" borderStyle="roundedRect" placeholder="Email" minimumFontSize="17" translatesAutoresizingMaskIntoConstraints="NO" id="m2R-lG-ufe" customClass="MDCTextField">
                                <rect key="frame" x="10" y="190" width="300" height="30"/>
                                <color key="tintColor" name="Funraise Blue"/>
                                <constraints>
                                    <constraint firstAttribute="height" constant="30" id="F99-Yb-lan"/>
                                    <constraint firstAttribute="width" constant="300" id="aXg-3a-ltJ"/>
                                </constraints>
                                <nil key="textColor"/>
                                <fontDescription key="fontDescription" type="system" pointSize="20"/>
                                <textInputTraits key="textInputTraits" returnKeyType="next" textContentType="username"/>
                            </textField>
                            <textField opaque="NO" contentMode="scaleToFill" contentHorizontalAlignment="left" contentVerticalAlignment="center" borderStyle="roundedRect" placeholder="Password" textAlignment="natural" minimumFontSize="17" translatesAutoresizingMaskIntoConstraints="NO" id="6NP-2X-fPh" customClass="MDCTextField">
                                <rect key="frame" x="10" y="260" width="300" height="30"/>
                                <color key="tintColor" name="Funraise Blue"/>
                                <constraints>
                                    <constraint firstAttribute="height" constant="30" id="6Jr-uf-ZHS"/>
                                    <constraint firstAttribute="width" constant="300" id="Awh-Bp-FCe"/>
                                </constraints>
                                <nil key="textColor"/>
                                <fontDescription key="fontDescription" type="system" pointSize="20"/>
                                <textInputTraits key="textInputTraits" returnKeyType="go" secureTextEntry="YES" textContentType="password"/>
                            </textField>
                            <imageView userInteractionEnabled="NO" contentMode="scaleAspectFit" horizontalHuggingPriority="251" verticalHuggingPriority="251" image="logo" translatesAutoresizingMaskIntoConstraints="NO" id="znh-JT-zzr">
                                <rect key="frame" x="40" y="90" width="240" height="60"/>
                                <constraints>
                                    <constraint firstAttribute="height" constant="60" id="3Sv-PD-4Qk"/>
                                    <constraint firstAttribute="width" constant="240" id="dB6-fN-bhC"/>
                                </constraints>
                            </imageView>
                            <button opaque="NO" contentMode="scaleToFill" highlighted="YES" selected="YES" contentHorizontalAlignment="center" contentVerticalAlignment="center" buttonType="roundedRect" lineBreakMode="middleTruncation" translatesAutoresizingMaskIntoConstraints="NO" id="pLg-TZ-gnA" customClass="MDCRaisedButton">
                                <rect key="frame" x="160" y="360" width="150" height="30"/>
                                <color key="backgroundColor" name="Funraise Blue"/>
                                <constraints>
                                    <constraint firstAttribute="height" constant="30" id="2r3-TN-bdk"/>
                                    <constraint firstAttribute="width" constant="150" id="oyU-6t-gil"/>
                                </constraints>
                                <fontDescription key="fontDescription" type="system" pointSize="14"/>
                                <state key="normal" title="LOGIN">
                                    <color key="titleColor" white="1" alpha="1" colorSpace="custom" customColorSpace="genericGamma22GrayColorSpace"/>
                                </state>
                                <state key="disabled" title="LOGIN"/>
                                <connections>
                                    <action selector="loginClicked:" destination="Kbp-8m-Ed9" eventType="touchUpInside" id="4wW-tb-9U1"/>
                                </connections>
                            </button>
                            <label opaque="NO" userInteractionEnabled="NO" contentMode="left" horizontalHuggingPriority="251" verticalHuggingPriority="251" text="Forgot?" textAlignment="natural" lineBreakMode="tailTruncation" baselineAdjustment="alignBaselines" adjustsFontSizeToFit="NO" translatesAutoresizingMaskIntoConstraints="NO" id="kZX-gm-naA">
                                <rect key="frame" x="9.5" y="367" width="49.5" height="17"/>
                                <fontDescription key="fontDescription" type="system" pointSize="14"/>
                                <color key="textColor" name="Funraise Blue"/>
                                <nil key="highlightedColor"/>
                            </label>
                        </subviews>
                        <color key="backgroundColor" white="1" alpha="1" colorSpace="custom" customColorSpace="genericGamma22GrayColorSpace"/>
                        <constraints>
                            <constraint firstItem="pLg-TZ-gnA" firstAttribute="trailing" secondItem="6NP-2X-fPh" secondAttribute="trailing" id="0Je-bJ-Axp"/>
                            <constraint firstItem="kZX-gm-naA" firstAttribute="leading" secondItem="6NP-2X-fPh" secondAttribute="leading" id="1uH-b4-Gzk"/>
                            <constraint firstItem="6NP-2X-fPh" firstAttribute="top" secondItem="m2R-lG-ufe" secondAttribute="bottom" constant="40" id="4Yy-gS-aKF"/>
                            <constraint firstItem="6NP-2X-fPh" firstAttribute="centerX" secondItem="FGi-81-bgK" secondAttribute="centerX" id="Bwl-MW-gcY"/>
                            <constraint firstItem="znh-JT-zzr" firstAttribute="centerX" secondItem="m2R-lG-ufe" secondAttribute="centerX" id="O11-f4-uPq"/>
                            <constraint firstItem="m2R-lG-ufe" firstAttribute="top" secondItem="bKZ-Zr-XeW" secondAttribute="top" multiplier="0.6" constant="190" id="bpk-wf-ak2"/>
                            <constraint firstItem="pLg-TZ-gnA" firstAttribute="top" secondItem="6NP-2X-fPh" secondAttribute="bottom" constant="70" id="fLG-it-jU7"/>
                            <constraint firstItem="kZX-gm-naA" firstAttribute="centerY" secondItem="pLg-TZ-gnA" secondAttribute="centerY" id="fu0-ll-aPJ"/>
                            <constraint firstItem="m2R-lG-ufe" firstAttribute="top" secondItem="znh-JT-zzr" secondAttribute="bottom" constant="40" id="gWc-yD-qio"/>
                            <constraint firstItem="m2R-lG-ufe" firstAttribute="centerX" secondItem="FGi-81-bgK" secondAttribute="centerX" id="pzX-vY-mro"/>
                        </constraints>
                        <viewLayoutGuide key="safeArea" id="FGi-81-bgK"/>
                    </view>
                    <connections>
                        <outlet property="emailTextField" destination="m2R-lG-ufe" id="o5H-8x-RhA"/>
                        <outlet property="forgotLabel" destination="fu0-ll-aPJ" id="2IU-MF-uBd"/>
                        <outlet property="passwordTextField" destination="6NP-2X-fPh" id="yi0-hw-jfr"/>
                    </connections>
                </viewController>
                <placeholder placeholderIdentifier="IBFirstResponder" id="10s-bX-t3u" userLabel="First Responder" sceneMemberID="firstResponder"/>
            </objects>
            <point key="canvasLocation" x="-997.60000000000002" y="-361.16941529235385"/>
        </scene>`

**Comment by gmann1** [comment]
@willlarche I figured it out... I had height constraints set on both textfields!

**Comment by willlarche** [comment]
Oh! You don't need those! It has an intrinsicContentSize
