### ISSUE TITLE
[SearchBar] Support Material search pattern

### ISSUE THREAD

**Issue by samskiter** [material-components/material-components-ios#3105]
### Overview
For usage questions: ask on [Stack  Overflow](https://stackoverflow.com/questions/tagged/material-components+ios).

 - Context, problem or idea, solution or next step
I'd like to add search to my app as per the spec (https://material.io/guidelines/patterns/search.html#search-in-app-search), but there doesn't seem to be any support in MDC for this.

Is there an easy way of doing this by combining existing components? Or is this a currently unimplemented feature that's in the pipeline?

---
#### Internal data
- Associated internal bug: [b/117179109](http://b/117179109)

**Comment by samskiter** [comment]
New link: https://material.io/design/navigation/search.html#persistent-search

I think that aside from the design spec which mentions persistent and expandable search there are two broad patterns that matter from an implementation point of view: filtering and searching

Filtering is taking what is already on screen and searching through it - you do this on the screen you are already on.

Pure search is more like, clear the contents of the screen and start looking for something - this might even involve moving to a new, dedicated search screen.

**Comment by jverkoey** [comment]
There is successful precedent of people using a Flexible Header with a transparent background and a custom search view. If you do so, please consider using `MDCFlexibleHeaderContentImportanceHigh ` for the flexible header if you allow it to shift on/off-screen. This will ensure that the flexible header behavior matches that of other apps that use search bars in the header.

https://github.com/material-components/material-components-ios/blob/develop/components/FlexibleHeader/src/MDCFlexibleHeaderView.h#L55

**Comment by jverkoey** [comment]
I think an actionable outcome of this bug would be for us to implement a "floating search bar" example in the catalog. The essential traits of this example would be:

- A flexible header with a transparent background.
- A custom "search bar" view is added to the flexible header.
- The content importance is set to high.
- Shifting is enabled.

**Comment by jverkoey** [comment]
Though that outcome assumes we want a floating search bar.

It's likely worth implementing an edge-to-edge search bar experience as well, as shown in the spec.

**Comment by samskiter** [comment]
As the primary use case of our app is not search, we would be happy with the edge-to-edge style of search bar shown here: https://material.io/design/navigation/search.html#expandable-search

**Comment by samskiter** [comment]
Given future potential improvements to the App Bar API, it might be best if you can enable search without direct access to the AppBar. Thankfully NavigationItem already supports a search controller.

This would allow the MDC library to dictate the 'correct' way to transition into search according to MDC design specs.

What is interesting there is supporting the Filtering vs Dedicated search use cases mentioned above

(Filtering is moving into search within the current VC, Dedicated is moving to a new VC explicitly for search)

**Comment by material-mirror** [comment]
The internal issue [b/117179109](http://b/117179109) is now closed. This issue is being closed as a result.
