### ISSUE TITLE
[TextFields] Trailing and Leading underline labels can overlap with dynamic size fonts.

### ISSUE THREAD

**Issue by mohammadcazig** [material-components/material-components-ios#3108]
when Font sizes are too big Trailing and Leading Underline Labels overlap instead of one truncating.
Use Dynamic Size Example in Dragons to replicate this issue.

---
#### Internal data
- Associated internal bug: [b/117178916](http://b/117178916)

**Comment by willlarche** [comment]
Can also happen when text is too long. Compression resistance is too high. Needs to be ~249.

**Comment by material-mirror** [comment]
The internal issue [b/117178916](http://b/117178916) is now closed. This issue is being closed as a result.
