### ISSUE TITLE
[TextFields] TextFields layout implementation relies on auto layout for motion and doesn't follow spec

### ISSUE THREAD

**Issue by mohammadcazig** [material-components/material-components-ios#3109]
We should spend sometime finding solutions to how we can decrease the complexity of TextFields layout.
Currently constraints are being set by, fundament, controller, and text fields which could override each other. There is also a mix of custom calculation and constraints together.

---
#### Internal data
- Associated internal bug: [b/117179301](http://b/117179301)

**Comment by material-mirror** [comment]
The internal issue [b/117179301](http://b/117179301) is now closed. This issue is being closed as a result.
