### ISSUE TITLE
MDCCollectionViewTextCell does not horizontally center non-square image

### ISSUE THREAD

**Issue by bhamiltoncx** [material-components/material-components-ios#3111]
Passing an image which is taller than it is wide to MDCCollectionViewTextCell.imageView.image causes the cell to lay out the image non-centered.

Repro (apologies, I did this with cornerRadius set, but it doesn't affect the layout, just the repro image):

```
  MDCCollectionViewTextCell *cell = [[MDCCollectionViewTextCell alloc]
      initWithFrame:CGRectMake(0, 0, 320, MDCCellDefaultOneLineWithAvatarHeight)];
  cell.textLabel.text = @"All human beings are born free and equal in dignity and rights.";
  cell.imageView.layer.clipsToBounds = YES;
  cell.imageView.layer.cornerRadius = 20;
  cell.imageView.image = [UIImage imageNamed:@"NonSquare"
                                    inBundle:[NSBundle bundleForClass:[self class]]
	       compatibleWithTraitCollection:nil];
```

Expected: MDCCollectionViewTextCell should center the image horizontally.

Actual: MDCCollectionViewTextCell lays out the image all the way to the left.

![nonsquare](https://user-images.githubusercontent.com/671827/37545500-ae7659fe-292e-11e8-8d95-a19c98e9f356.png)
![nonsquare_repro](https://user-images.githubusercontent.com/671827/37545534-c5a7e962-292e-11e8-9529-e2dc5f615c86.png)

**Comment by jverkoey** [comment]
Marking as Obsolete because we do not intend to continue to invest effort into Collections. Please consider using the new List component instead: https://github.com/material-components/material-components-ios/tree/develop/components/List
