### ISSUE TITLE
[Collections] Collections should support UIAppearance- or default-based theming

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3113]
### Overview
Collections should allow clients to set theming properties once-and-done during app startup. This could follow the UIAppearance styling that most views use, or a default-based approach used by Text Fields.  The end goal would be the same - a mechanism to set the styling (colors, fonts) of Collections without any per-instance adjustments.

### Version number
48.0.0

**Comment by ianegordon** [comment]
We are not intending on any significant updates to the current Collections component. 😞
We are working on a much simpler [List component](https://github.com/material-components/material-components-ios/tree/develop/components/List). 😄
