### ISSUE TITLE
[Snackbar] Compilation is failing because of deprecation

### ISSUE THREAD

**Issue by gambard** [material-components/material-components-ios#3120]
### Overview
We are not able to build the new release (48.0) as https://github.com/material-components/material-components-ios/commit/85c5351ec74354d5750fafb8d51bb2be0f58389e deprecate a method and still use it. As we treat warnings as error, we are failing to compile.
We can ignore the warning on the MDC files, but we want to make sure this is the intended behavior.

So is it the intended behavior and it will stay as is, or is it a temporary fix?

### Version number
 - 48.0

**Comment by gambard** [comment]
This is about this change: https://github.com/material-components/material-components-ios/commit/85c5351ec74354d5750fafb8d51bb2be0f58389e

**Comment by ianegordon** [comment]
Discussed offline.
@gambard please re-open if this is still an issues.
👍
