### ISSUE TITLE
Flexible header jumps when changing to a tracking scrollview with a different offset

### ISSUE THREAD

**Issue by samskiter** [material-components/material-components-ios#3130]
### Overview

 - Context, problem or idea, solution or next step
   - I'm creating a paging view controller with tabs and a flexible appbar header.
   - Each page has a vertical scrollview
   - When moving from a page that is at the top to one that is scrolled down, the header animates to it's minimum height (00:13 in the video below). I assume this is intentional. It's a little distracting but it's ok.
   - When moving from a page that is scrolled down to one with limited content (ie cannot be scrolled down) the header jumps to a larger size with no animation (0:17 in video).

   - Ideal solution:
As mentioned in previous tickets we're moving over to material design at the minute. We've previously had a flexible header of sorts and we implemented a solution that would never change the size of the header when moving between tabs. But, you could scroll the scrollviews and if it were the wrong size, it would resize as you scrolled in the direction that you would expect to resize it. It's hard to articulate in words, I'll try to find a video of that working, but the code read like so:
```swift
let insetOffsetScrollingPercentage = TopTabController.insetOffsetScrollingPercentage(forScrollView: scrollView)
let topInset = scrollView.contentInset.top

let oldHeight = self.heightConstraint.constant
let calculatedNewHeight = min(self.minimumHeaderHeight + (topInset * insetOffsetScrollingPercentage), self.maximumHeaderHeight)

let newHeight: CGFloat

if let change = change {

    let proposedHeightChange = calculatedNewHeight - oldHeight
    let proposedHeightChangeAmmount = proposedHeightChange.magnitude
    let heightChangeSign = proposedHeightChange.sign

    // Only let the header move in the direction we are scrolling

    if heightChangeSign == change.sign {

        let changeAmmount = change.magnitude
        let newHeightAmmount = min(changeAmmount, proposedHeightChangeAmmount)
        newHeight = oldHeight + CGFloat(sign: heightChangeSign, exponentBitPattern: newHeightAmmount.exponentBitPattern, significandBitPattern: newHeightAmmount.significandBitPattern)

    } else {

        newHeight = oldHeight
    }

} else {

    newHeight = calculatedNewHeight
}

self.heightConstraint.constant = newHeight
```

 - Screenshots/Video (if possible)
Video of jumping behaviour (only visible for Googlers): https://drive.google.com/file/d/106UNExqT-X-ci_nU1sJqCZtwp0JgrIA9/view?usp=sharing
 - Stack trace (if possible)

### Reproduction steps
 - Detailed steps to reproduce
Can provide more about our exact setup if required.

### Version number
MaterialComponents (44.6.0) (from Podfile.lock)

### Operating system and device

- macOS High Sierra 10.13.2 (17C88)
- XCode 9.2
- iOS 11.2
- iPhone 7 simulator

### Related issues
 - #3038 

### Desired fixes

- [x] When moving from a collapsed header to an expanded one, maintain the collapsed header height. Resolved in https://github.com/material-components/material-components-ios/pull/4601
- [ ] When moving from an expanded header to a collapsed one, maintain the expanded height.

**Comment by samskiter** [comment]
@ianegordon not sure we have any choice but to fork to fix this one? (and potentially the other app bar bugs)

**Comment by jverkoey** [comment]
Are you already making use of `trackingScrollWillChangeToScrollView:`? This method should be called when you start scrolling horizontally to one of the new scroll views.

**Comment by samskiter** [comment]
yes
```
extension MyViewController: TabChangeListener {

    func topTabController(_ topTabController: TopTabControllerProtocol, willChangeToViewController nextViewController: UIViewController) {

        guard let pagedViewController = nextViewController as? PagedViewController else { return }

        self.appBar.headerViewController.headerView.trackingScrollWillChange(toScroll: pagedViewController.scrollView)
    }

    func topTabController(_ topTabController: TopTabControllerProtocol, didChangeToViewController newViewController: UIViewController) {

        guard let pagedViewController = newViewController as? PagedViewController else { return }

        self.appBar.headerViewController.headerView.trackingScrollView = pagedViewController.scrollView
    }
}
```

**Comment by jverkoey** [comment]
Yep - thanks for confirming. I'm currently deep in https://github.com/material-components/material-components-ios/issues/4104, but once I get the PR out for that (hopefully by end of day tomorrow) I'll look at this next.

**Comment by samskiter** [comment]
Thanks so much, also shameless plug for the other app bar issues we've raised ;)

#4393 
#3139
#3038

I think most of which would need nasty workaround or patching to fix...

**Comment by jverkoey** [comment]
I've edited the issue description to include the two fixes I see as being required here.

**Comment by samskiter** [comment]
@jverkoey thanks! I suppose there are additional ACs you could tag onto those that when you do scroll, the header doesn't jump, but moves as you scroll

**Comment by jverkoey** [comment]
Yep - that will be a significantly more complex PR than the one that addresses the first half of this issue, so I'll pursue that separately.

**Comment by jverkoey** [comment]
I think that the latter half of this bug will be resolved by https://github.com/material-components/material-components-ios/issues/4393 if we do pursue it, so I'll unassign myself from this for now and mark the issue as blocked on needing design review as well.

**Comment by yarneo** [comment]
@jverkoey are we still blocked on design input for this bug?
