### ISSUE TITLE
I can't use version 49.0.0 in my Swift project

### ISSUE THREAD

**Issue by fedecastelli** [material-components/material-components-ios#3131]
I've seen that you've added the customization for Material Dialogs in version 49.0.0.
I was trying to install that version in my project using pod. 
I've added this line to my Podfile:
```
pod 'MaterialComponents', '~> 49.0.0'
```
And then I run the command:
```
pod install --repo-update
```
But I'm getting this error:
```
CocoaPods could not find compatible versions for pod "MaterialComponents":
  In Podfile:
    MaterialComponents (~> 49.0.0)
```

I also tried to use Cartage adding:
```
github "material-components/material-components-ios" ~> 49.0.0
```
And running:
```
Carthage update --platform iOS
```
But I'm getting this error:
```
Skipped building material-components-ios due to the error:
Dependency "material-components-ios" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/material-components/material-components-ios/issues/new
```

What am I doing wrong? Can't I use this version in Swift Projects?

**Comment by romoore** [comment]
Hi @fedecastelli . Can you post the contents of your Podfile?  Did you [add `enable_frameworks`](https://github.com/material-components/material-components-ios/blob/2c0d0b9b1a55e9c3918237a7288535abfd2409cc/README.md#requirements)?

**Comment by fedecastelli** [comment]
Contents of my Podfile:
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyTestApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyTestApp
  pod 'MaterialComponents'
end
```
When I run `pod install`, I see this output:
```
Analyzing dependencies
Downloading dependencies
Installing MDFInternationalization (1.0.4)
Installing MDFTextAccessibility (1.2.0)
Installing MaterialComponents (48.0.0)
Installing MotionAnimator (2.8.1)
Installing MotionInterchange (1.6.0)
Installing MotionTransitioning (5.0.0)
Generating Pods project
Integrating client project
```
I want to install the MaterialComponents version 49.0.0 but I can't do that.

**Comment by romoore** [comment]
It looks like [49.0.0 has not yet been pushed to Cocoapods](https://github.com/CocoaPods/Specs/tree/master/Specs/0/1/9/MaterialComponents).  Assigning to @randallli  who performed the latest release.

**Comment by fedecastelli** [comment]
Thanks, @romoore!

**Comment by fedecastelli** [comment]
Do you think 49.0.0 will be released soon? @randallli

**Comment by romoore** [comment]
Version 49.0.0 is still absent from cocoapods. Can we just checkout the release from Git and push it up to trunk?

**Comment by romoore** [comment]
Pushed 49 to Cocoapods, although 52.0.0 is now available as well. 😉
