### ISSUE TITLE
MDCAppBar headerStackView's ViewController is private making further embedding of container view controller's hacky

### ISSUE THREAD

**Issue by samskiter** [material-components/material-components-ios#3139]
### Overview

 - Context, problem or idea, solution or next step

I have a ViewController (call it `DetalsViewController`) that fetches data and displays it. It's intended to be used as a ChildViewController and actually intended to be placed in the 'bottom bar' of the `MDCAppBar`. The view of this view controller therefore needs to be a subview of the `headerStackView` in the AppBar.

But the view controller itself must also be added as a child view controller of whichever view controller contains the `headerStackView`. Unfortunately, the `MDCAppBar`'s `appBarController` is private so this is not possible.

For now we are using this (hacky!) workaround method on an `MDCAppBar` subclass to get hold of the view controller required:
```swift
    func stackViewController() -> UIViewController? {
        var parentResponder: UIResponder? = self.headerStackView
        while parentResponder != nil {
            parentResponder = parentResponder!.next
            if let viewController = parentResponder as? UIViewController {
                return viewController
            }
        }
        return nil
    }
```

### Version number
MaterialComponents (44.6.0) (from Podfile.lock)

### Operating system and device

- macOS High Sierra 10.13.2 (17C88)
- XCode 9.2
- iOS 11.2
- iPhone 7 simulator

### Related issues
 - #3038

**Comment by TheAggie** [comment]
I'm not sure if this issue is related, but I have been trying to assign a custom view to the headerStackView's bottomBar both directly:

self.appBar.headerStackView.bottomBar = self.bottomBarView;

and via adding it as a subview:

[self.appBar.headerStackView.bottomBar addSubview:self.bottomBarView];

Unfortunately, buttomBarView contains UIButtons which are not responsive. I felt like this issue had something to do w/ the headerStackView intercepting touches, but read that shouldn't apply to subviews of the bottomBar/topBar, so I'm not really sure what is going on. I attempted to use "Debug View Hierarchy" to better make sense of what may be happening, but that features hasn't worked for me in a while (I can only see the UIWindow). Any help would be greatly appreciated!

**Comment by samskiter** [comment]
Probably an issue of its own. But related to this one and also https://github.com/material-components/material-components-ios/issues/3038

**Comment by jverkoey** [comment]
You can achieve what you're describing by adding the view controller to the appBar's headerViewController (which is the parent of the private App Bar view controller) and then assigning the view controller's view to the bottomBar, like so:

```objc
  UIViewController *child = [[UIViewController alloc] init];
  [self.appBar.headerViewController addChildViewController:child];

  child.view.autoresizingMask = 0; // You probably want this to be flexible width, but not height
  child.view.frame = CGRectMake(0, 0, 50, 50);

  self.appBar.headerStackView.bottomBar = child.view;
  [child didMoveToParentViewController:self.appBar.headerViewController];

  // To show the dummy view
  self.appBar.headerStackView.bottomBar.backgroundColor = [UIColor redColor];
```

![simulator screen shot - iphone se - 2018-07-20 at 10 05 53](https://user-images.githubusercontent.com/45670/43006748-7f0754aa-8c04-11e8-86d0-ec87334c71c0.png)

I'm hesitant to expose the app bar view controller as a public API, and given that it is technically feasible to achieve the behavior you're describing I will mark this bug as working as intended. Please re-open if the above example code doesn't address your needs.

**Comment by samskiter** [comment]
@jverkoey I believe (may be wrong) that you don't get the correct forwarding of View Controller lifecycle methods if you don't add the view controller as a child of the stack view controller.

cc'ing @babakbo who pointed this out originally and wrote our hack above.

**Comment by jverkoey** [comment]
Do you mean correct as in order? Assuming UIKit is doing a depth-first traversal I'd expect it to be the same order of operations either way, with events being sent in the following order:

1. Flexible header
2. App bar
3. Child

**Comment by samskiter** [comment]
Not sure. I don't know enough about this issue (there may be something about timing). We will try what you are doing and get back to you though.
