### ISSUE TITLE
[TextFields] `inlinePlaceholderFont` has no corresponding `floatingPlaceholderFont`

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3142]
### Overview
MDCTextInputController.h documents `inlinePlaceholderFont` as:

>  The font applied to the placeholder when inline (not floating).

However, this font is also applied when the placeholder *is floating*.  Either the documentation (and property name?) should be updated, or a corresponding property should be provided in `MDCTextInputControllerFloatingPlaceholder`.

### Version number
49.0.0

---
#### Internal data
- Associated internal bug: [b/117179075](http://b/117179075)

**Comment by romoore** [comment]
Based on internal requests, it looks like the extra font property should be provided.

**Comment by mohammadcazig** [comment]
We need to clarify how the animation works? is fade in fade out acceptable?

**Comment by willlarche** [comment]
The motion is the problem. You can't animate between fonts on iOS.

**Comment by romoore** [comment]
Would we have to animate between two UIViews that each act as the placeholder (depending on its location)?

**Comment by willlarche** [comment]
Ask motion designers to define

**Comment by material-mirror** [comment]
The internal issue [b/117179075](http://b/117179075) is now closed. This issue is being closed as a result.
