### ISSUE TITLE
[FeatureHighlight] FeatureHighlightViewController should expose FeatureHighlightView as a property.

### ISSUE THREAD

**Issue by mohammadcazig** [material-components/material-components-ios#3144]
FeatureHighlightViewController should expose FeatureHighlightView as a property instead of having properties to style the featureHighlightView (e.g TitleColor, BodyColor). 
Currently we have these properties on both view and view controller which can be confusing.

---
#### Internal data
- Associated internal bug: [b/117179205](http://b/117179205)

**Comment by material-mirror** [comment]
The internal issue [b/117179205](http://b/117179205) is now closed. This issue is being closed as a result.
