### ISSUE TITLE
[TextFields] .editingChanged not fired on clear button.

### ISSUE THREAD

**Issue by yokoe** [material-components/material-components-ios#3150]
MDCTextField doesn't fire `UIControlEvents.editingChanged` when user tapped its clear button while UITextField does.

```
// UITextField
textField.addTarget(self, action: #selector(onTextFieldEditingChanged(_:)), for: .editingChanged)

// MDCTextField
materialTextField.addTarget(self, action: #selector(onTextFieldEditingChanged(_:)), for: .editingChanged)

@objc
func onTextFieldEditingChanged(_ textField: UITextField) {
    debugPrint(textField.text ?? "")
}
```

We can confirm this difference simply with the code below.

I think this behavior should be adjusted.

**Comment by iNima** [comment]
Yes it is very important to have an event for the clear button in situations where we are validating users' entry while they are typing (e.g. Enable/Disable login button)
Currently, we have to remove clear button in those cases which is not a solution.
