### ISSUE TITLE
[BottomNavigation] The font size is very small

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#3166]
From an internal thread:

The font size of the notifications in the bottom navigation tabs is very, very small. i'm concerned about this as an overall trend.

Apple does not typically resize navigational elements with Dynamic Type. In UITabBar if you long press an item, you get a 'full screen' rendering of the item in question. We may be able to do something similar.

**Comment by romoore** [comment]
@ianegordon Is this a request to build the tap-and-hold to zoom feature into MDCBottomNavigation?

**Comment by romoore** [comment]
Closing in favor of #4159
