### ISSUE TITLE
[Chips] Chip Collections should leave greater space between lines

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#3169]
b/74111126

**Comment by jverkoey** [comment]
Context: we need greater space between chip lines because the chips expand their hit test region beyond the bounds (to 48x48). This can cause the chip hit test regions to overlap. We want give more space between the chips so that they do not overlap.

**Comment by jverkoey** [comment]
Related to https://github.com/material-components/material-components-ios/issues/3746

**Comment by romoore** [comment]
This is an internal issue (see the b/ link above). Closing since it's being tracked separately from the baseline MDC Component.
