### ISSUE TITLE
[Typography] Add new type style names to `MDCFontTextStyle.h`

### ISSUE THREAD

**Issue by ajsecord** [material-components/material-components-ios#3170]
Add new type style names to [MDCFontTextStyle](https://github.com/material-components/material-components-ios/blob/develop/components/Typography/src/MDCFontTextStyle.h).

The new styles are below, with equivalent current styles listed where appropriate based on matching the actual font sizes/styles as best as possible. The old enumeration values should not change for backwards compatibility. Where there is a match from new to old, the two should have the same value.

- Headline 1 = Display 4
- Headline 2 = Display 3
- Headline 3 = Display 2
- Headline 4 = Display 1
- Headline 5 = Headline
- Headline 6 = Title
- Subtitle 1 = Subheading
- Subtitle 2
- Body 1
- Body 2
- Caption
- Button
- Overline

**Comment by jverkoey** [comment]
I believe this was addressed in #3258.
