### ISSUE TITLE
[MDCTabBarViewController] Initial view controller crash with storyboard

### ISSUE THREAD

**Issue by pontago** [material-components/material-components-ios#3172]
### Overview
Initial view cotroller is a MDCTabBarViewController in storyboard.
It crashed and got error message.

`
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle 
`

I think this commit code is affecting.
This problem isn't crash with earlier commit it.
https://github.com/material-components/material-components-ios/commit/ca02350c09360ca350750dd8c8d71580c3e44108

### Version number
49.0.0

### Operating system and device
- macOS 10.12.6 (16G1212)
- XCode 9.2
- iOS 11.2

---
https://www.pivotaltracker.com/story/show/156804991

**Comment by romoore** [comment]
@pontago  Is there any additional error message?  Can you post a (redacted) stack trace?  Is it possible the crash is caused by a missing  `-initWithNibName:bundle:` for the class?

**Comment by pontago** [comment]
@romoore I think this crash caused by a -initWithCoder. And I used Swift4.

Stack trace is this.
`
*** First throw call stack:
(
	0   CoreFoundation                      0x000000011214d12b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00000001117e9f41 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001121c2245 +[NSException raise:format:] + 197
	3   UIKit                               0x000000011316e098 -[UINib instantiateWithOwner:options:] + 501
	4   UIKit                               0x0000000112e853ff -[UIViewController _loadViewFromNibNamed:bundle:] + 383
	5   UIKit                               0x0000000112e85d2b -[UIViewController loadView] + 177
	6   UIKit                               0x0000000112e8605c -[UIViewController loadViewIfRequired] + 195
	7   UIKit                               0x0000000112e868b9 -[UIViewController view] + 27
	8   MaterialComponents                  0x000000010f732f63 -[MDCTabBarViewController updateTabBarItems] + 1603
	9   MaterialComponents                  0x000000010f7323a9 -[MDCTabBarViewController setViewControllers:] + 777
	10  MaterialComponents                  0x000000010f731532 -[MDCTabBarViewController initWithCoder:] + 226
	11  CryptocurrencyFolio                 0x000000010ee385ee _T019CryptocurrencyFolio24MainTabBarViewControllerCACSgSo7NSCoderC5coder_tcfc + 158
	12  CryptocurrencyFolio                 0x000000010ee3869f _T019CryptocurrencyFolio24MainTabBarViewControllerCACSgSo7NSCoderC5coder_tcfcTo + 47
	13  UIKit                               0x000000011316f4c8 -[UIClassSwapper initWithCoder:] + 246
	14  UIKit                               0x00000001133c4109 UINibDecoderDecodeObjectForValue + 704
	15  UIKit                               0x00000001133c3e3e -[UINibDecoder decodeObjectForKey:] + 89
	16  UIKit                               0x000000011316f194 -[UIRuntimeConnection initWithCoder:] + 178
	17  UIKit                               0x00000001133c4109 UINibDecoderDecodeObjectForValue + 704
	18  UIKit                               0x00000001133c42a7 UINibDecoderDecodeObjectForValue + 1118
	19  UIKit                               0x00000001133c3e3e -[UINibDecoder decodeObjectForKey:] + 89
	20  UIKit                               0x000000011316e391 -[UINib instantiateWithOwner:options:] + 1262
	21  UIKit                               0x00000001135fefc2 -[UIStoryboard instantiateViewControllerWithIdentifier:] + 181
	22  UIKit                               0x0000000112cdddcc -[UIApplication _loadMainStoryboardFileNamed:bundle:] + 112
	23  UIKit                               0x0000000112cde283 -[UIApplication _loadMainInterfaceFile] + 228
	24  UIKit                               0x0000000112cdc9b8 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1413
	25  UIKit                               0x00000001130a66f8 __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke + 924
	26  UIKit                               0x000000011347c4c8 +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:] + 153
	27  UIKit                               0x00000001130a62f1 -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:] + 249
	28  UIKit                               0x00000001130a6b6b -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:] + 696
	29  UIKit                               0x0000000113a24a69 __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke + 262
	30  UIKit                               0x0000000113a24922 -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:] + 444
	31  UIKit                               0x00000001137019c8 __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke + 221
	32  UIKit                               0x0000000113900b06 _performActionsWithDelayForTransitionContext + 100
	33  UIKit                               0x000000011370188b -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:] + 231
	34  UIKit                               0x000000011347bb25 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:] + 392
	35  UIKit                               0x0000000112cdb36a -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 523
	36  UIKit                               0x00000001132b6605 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 369
	37  FrontBoardServices                  0x000000011bdedcc0 -[FBSSceneImpl _didCreateWithTransitionContext:completion:] + 338
	38  FrontBoardServices                  0x000000011bdf67b5 __56-[FBSWorkspace client:handleCreateScene:withCompletion:]_block_invoke_2 + 235
	39  libdispatch.dylib                   0x0000000116c2333d _dispatch_client_callout + 8
	40  libdispatch.dylib                   0x0000000116c289f3 _dispatch_block_invoke_direct + 592
	41  FrontBoardServices                  0x000000011be22498 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
	42  FrontBoardServices                  0x000000011be2214e -[FBSSerialQueue _performNext] + 464
	43  FrontBoardServices                  0x000000011be226bd -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	44  CoreFoundation                      0x00000001120f0101 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	45  CoreFoundation                      0x000000011218ff71 __CFRunLoopDoSource0 + 81
	46  CoreFoundation                      0x00000001120d4a19 __CFRunLoopDoSources0 + 185
	47  CoreFoundation                      0x00000001120d3fff __CFRunLoopRun + 1279
	48  CoreFoundation                      0x00000001120d3889 CFRunLoopRunSpecific + 409
	49  GraphicsServices                    0x000000011a34e9c6 GSEventRunModal + 62
	50  UIKit                               0x0000000112cde5d6 UIApplicationMain + 159
	51  CryptocurrencyFolio                 0x000000010ee65d67 main + 55
	52  libdyld.dylib                       0x0000000116c9fd81 start + 1
)
`

**Comment by romoore** [comment]
Assigning to @mohammadcazig to investigate this crash since he is a co-owner and authored the commit suspected of introducing the crash.

**Comment by pontago** [comment]
Closing this issue. @jverkoey fixed it.
https://github.com/material-components/material-components-ios/commit/4bede1313cdbcfdb0ce57d815504080a9837fb9d
