### ISSUE TITLE
[Typography] Add new font style values

### ISSUE THREAD

**Issue by ajsecord** [material-components/material-components-ios#3174]
Depends on #3170.

Add the following new font styles:
- Headline 1 | Light 96 / -1.5 tracking
- Headline 2 | Light 60 / -.5 tracking
- Headline 3 | Regular 48 / 0 tracking
- Headline 4 | Regular 34 / .25 tracking
- Headline 5 | Regular 24 / 0 tracking
- Headline 6 | Medium 20 / .25 tracking
- Subtitle 1 | Regular 16 / .15 tracking
- Subtitle 2 | Medium 14 / .1 tracking
- Body 1 | Regular 16 / .5 tracking
- Body 2 | Regular 14 / .25 tracking
- Caption | Regular 12 / .4 tracking
- Button | Medium all caps 14 / 1.25 tracking
- Overline | Medium all caps 12 / 2 tracking

Note:
- We support Dynamic Type, which complicates this picture, but for now, implement using `UIContentSizeCategoryLarge` (the default) only and #3175 will track the rest of the work.
- `MDCFontTraits` currently has tracking as a parameter but they are all set to zero. Set the above tracking values for the `UIContentSizeCategoryLarge` category and leave the rest to zero. Not having tracking for certain categories is a smaller issue.

---
#### Internal data
- Associated internal bug: [b/117178997](http://b/117178997)

**Comment by jverkoey** [comment]
To confirm, the current API in the TypographyScheming protocol does not meet the requirements for this issue?

https://github.com/material-components/material-components-ios/blob/develop/components/schemes/Typography/src/MDCTypographyScheme.h#L25

**Comment by ianegordon** [comment]
Tracking is a specific to font face and size.  Generic guidance based on size may not make sense.  These values are embedded into the font by the font designer and I would be hesitant to override there decisions in a general case.

**Comment by material-mirror** [comment]
The internal issue [b/117178997](http://b/117178997) is now closed. This issue is being closed as a result.
