### ISSUE TITLE
[Typography] Fill out new font styles for other Dynamic Type categories

### ISSUE THREAD

**Issue by ajsecord** [material-components/material-components-ios#3175]
Follow up work to #3174, blocked on that.

#3174 added new font styles, but only for `UIContentSizeCategoryLarge`. Work with design to interpolate the styles for the other categories and implement.

---
#### Internal data
- Associated internal bug: [b/117179299](http://b/117179299)

**Comment by material-mirror** [comment]
The internal issue [b/117179299](http://b/117179299) is now closed. This issue is being closed as a result.
