### ISSUE TITLE
[BottomSheet] Verify stutter fix is in MDC

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#3176]
The sheet shifts laterally a pixel or two  when you let go. It should only move up and down

Internal Bug:
b/77234872

Internal Fix:
cl/190846975 

---
#### Internal data
- Associated internal bug: [b/117179074](http://b/117179074)

**Comment by material-mirror** [comment]
The internal issue [b/117179074](http://b/117179074) is now closed. This issue is being closed as a result.
