### ISSUE TITLE
[ButtonBar] Examples should provide accessibilityHint values

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3184]
### Overview
Each of our ButtonBar buttons should provide values for their `accessibilityHint` attributes.

### Reproduction steps
1. Open the Catalog&rarr;Button Bar
1. Open each example

**Expected Result**
Every button has an accessibilityHint

**Actual Result**
No hints

### Version number
50.0.0

---
#### Internal data
- Associated internal bug: [b/117178937](http://b/117178937)

**Comment by andrewoverton** [comment]
Is this one definitely needed @romoore? The apple docs say that "An accessibility hint helps users understand what will happen when they perform an action on the accessibility element when that result is not obvious from the accessibility label." In this scenario do the accessibility labels provide adequate context?

**Comment by romoore** [comment]
@andrewoverton Yep, you are correct. We should probably change this so that the buttons have meaningful verbs. :-\

**Comment by material-mirror** [comment]
The internal issue [b/117178937](http://b/117178937) is now closed. This issue is being closed as a result.
