### ISSUE TITLE
[ButtonBar] Buttons show no ink on tap

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3185]
### Overview
The ButtonBar examples do not seem to show any Ink ripples when tapping or activating the buttons.

### Reproduction steps
1. Open the catalog&rarr;Button Bar
1. Open any example
1. Tap on a button

**Expected Result**
Ink ripple is shown

**Actual Result**
No ink ripple is visible

### Version number
50.0.0

---
#### Internal data
- Associated internal bug: [b/117179130](http://b/117179130)

**Comment by material-mirror** [comment]
The internal issue [b/117179130](http://b/117179130) is now closed. This issue is being closed as a result.
