### ISSUE TITLE
[ButtonBar] Layout is incorrect on iPad devices

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3186]
### Overview
On iPads, the button bars appear to be misaligning the buttons.

iPhone 5c:
![bbar-iphone5c](https://user-images.githubusercontent.com/1753199/38107562-4d80864c-3360-11e8-8a34-b1b4071ba7af.png)

iPad Mini:
![bbar-ipad](https://user-images.githubusercontent.com/1753199/38107672-a1b7b29e-3360-11e8-8163-2fd24dc1ad17.png)

### Reproduction steps
1. Open the catalog&rarr;Button Bar&rarr;Button Bar (Icons)
1. Look at the buttons

**Expected Result**
The buttons are horizontally centered (as a group) within the bar.

**Actual Result**
The buttons are misaligned (to the right side) on an iPad device.

### Version number
50.0.0

---
#### Internal data
- Associated internal bug: [b/117178976](http://b/117178976)

**Comment by material-mirror** [comment]
The internal issue [b/117178976](http://b/117178976) is now closed. This issue is being closed as a result.
