### ISSUE TITLE
[Chips] "Clear" button in ChipsTypicalUseViewController has no accessibilityHint

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3187]
### Overview
The "Clear" button in the navigation bar of the ChipsTypicalUseViewController has no accessibilityHint value. It's not clear what it would clear.  Perhaps it should also be dimmed if there is no selection to clear.

### Reproduction steps
1. Open Catalog&rarr;Chips&rarr;Demo
1. Use VoiceOver to select the "Clear" Button near the beginning of the screen

**Expected Result**
Clear button is only enabled when it can perform an action.
Selecting it will read the hint, "Unselects all chips"

**Actual Result**
Clear button is always enabled.
It has no `accessibilityHint`.

### Version number
50.0.0

**Comment by andrewoverton** [comment]
Closed by https://github.com/material-components/material-components-ios/pull/4504
