### ISSUE TITLE
[Chips]  Chips catalog listing is missing a description

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3188]
### Overview
The Chips catalog component has no Description above the list of examples.

![img_0021](https://user-images.githubusercontent.com/1753199/38109590-a1a16fec-3366-11e8-9c49-eb3569d6e88b.PNG)

### Reproduction steps
1. Open the catalog&rarr;Chips

**Expected Result**
Below the "Description" header should be text describing Chips

**Actual Result**
The text box is empty

### Version number
50.0.0

---
#### Internal data
- Associated internal bug: [b/117179014](http://b/117179014)

**Comment by material-mirror** [comment]
The internal issue [b/117179014](http://b/117179014) is now closed. This issue is being closed as a result.
