### ISSUE TITLE
[FlexibleHeader] Flexible Header does not calculate accumulator when there is no tracking scroll view (b/74439161)

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3200]
### Overview
 If you use an MDCFlexibleHeader, like in the MDCAppBar, but you do not have a scrolling view, then fhv_commitAccumulatorToFrame never gets called, and the shadow layer is never set.

Simple fix, in MDCFlexibleHeaderView.m fhv_updateLayout make this one line change

```objectivec
- (void)fhv_updateLayout {
  if (!_trackingScrollView) {
    [self fhv_commitAccumulatorToFrame]; // Add this line
    return;
  }
```

### Version number
49.0.0

### Pivotal tracker story
https://www.pivotaltracker.com/story/show/156409055

---
#### Internal data
- Associated internal bug: [b/117179260](http://b/117179260)

**Comment by jverkoey** [comment]
This is blocking an internal team and needs to land before the next release.

**Comment by jverkoey** [comment]
https://www.pivotaltracker.com/story/show/156409055

**Comment by jverkoey** [comment]
This will be reopened by #3225.

**Comment by material-mirror** [comment]
The internal issue [b/117179260](http://b/117179260) is now closed. This issue is being closed as a result.
