### ISSUE TITLE
[NavigationBar] titleView should be center aligned with and without bar buttons

### ISSUE THREAD

**Issue by yarneo** [material-components/material-components-ios#3202]

**Comment by romoore** [comment]
I believe the current expected behavior is to bring the title *as close to the center* as possible, rather than to center it in the remaining space.  As a feature request, this would be a highly visible change in behavior, but is probably desirable.

**Comment by jverkoey** [comment]
This is now supported:

https://github.com/material-components/material-components-ios/blob/f1b8cef7c8186bf5932b6ec4b52de487d2a70c6b/components/NavigationBar/src/MDCNavigationBar.h#L21-L27
