### ISSUE TITLE
Please support the Swift Package Manager (SPM)

### ISSUE THREAD

**Issue by Morpheu5** [material-components/material-components-ios#3207]
I love CocoaPods and use them extensively, but [SPM](https://swift.org/package-manager/) is a little less intrusive.

Pretty please? :)

**Comment by ianegordon** [comment]
Hi @Morpheu5 .  We have been keeping an eye on SPM, but unfortunately it doesn't officially support iOS.

"Note that at this time the Package Manager has no support for iOS, watchOS, or tvOS platforms"
https://github.com/apple/swift-package-manager/blob/master/README.md

Hopefully we'll be able to revisit soon 👍

**Comment by Morpheu5** [comment]
Ah, Yes, you have a point :) It had been a while for me doing iOS and I was starting a new project after loads of cli-based Swift. I realised the lack of support for iOS much later.

**Comment by artemisia-absynthium** [comment]
Hi @ianegordon ! I don't know if it's more correct to reply here or open a new issue, anyway the moment SPM supports iOS has finally come! The beta of Xcode 11 with official SPM support for all platforms is out now!
I'm currently using material components in production apps and I really would like to be able to start migrating all of my projects from release day!

Pretty please! 😃

**Comment by andrewoverton** [comment]
Hi @artemisia-absynthium, Swift Package Manager is on our radar. Going forward this issue will be tracked by #7559. I can't make any promises on when this work will make it into one of our sprints but hopefully it's soon.

**Comment by artemisia-absynthium** [comment]
Thanks a lot @andrewoverton I subscribed to the exploratory ticket and hope for sooner than later! Thanks for the great work you do! 🙏

**Comment by CriptoCosmo** [comment]
is it right to leave the feature request closed considering that you planning to put this work in a future sprint?

**Comment by romoore** [comment]
Looks like this has become a duplicate of the newer issue #7559. Please bump that issue to raise its visibility to our team.

**Comment by oguzparlak** [comment]
Please support SPM guys. Everything migrates from Pod to SPM nowadays.

**Comment by debadaracco** [comment]
I need this migration to remove cocoapods on my project, Please add the support

**Comment by carlosmejiagrove** [comment]
For those still migrating away from Cocoapods, I managed to create an alternative version with SPM support. Just keep in mind that this repository fills my project needs, if you need to add extra files from other Components, it should be easy enough to fork the repository and add the missing files.

folder Source <- every .m
folder include <- every .h

that's it

https://github.com/carlosmejiagrove/material-components-ios-spm
