### ISSUE TITLE
[Scripts] `release` script should validate that `origin` is the master repository

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3208]
### Overview
The `release` script should ensure that the `remotes/origin` repository is the "real" repository and not a fork.  If the check fails, the script should terminate with an error message and non-zero return value. There should be an option to force the script to execute and ignore errors.

---
#### Internal data
- Associated internal bug: [b/117179240](http://b/117179240)

**Comment by material-mirror** [comment]
The internal issue [b/117179240](http://b/117179240) is now closed. This issue is being closed as a result.
