### ISSUE TITLE
[Buttons] Unset `titleFontForState:` reverts to system font, not .normal font value

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3222]
### Overview
MDCButton's `titleFontForState:` will return a system font if a state is not explicitly set. This may be intentional, but does not match the behavior of `titleForState:`, `titleColorForState:`, `titleShadowColorForState:` nor `attributedTitleForState:`.  I think it will be more expected for clients if the titleFont defaults to the value for the `.normal` state to match the related properties.

### Reproduction steps

```objectivec
- (void)testButtonFontThemer {
  // Given
  MDCButton *button = [[MDCButton alloc] init];
  MDCBasicFontScheme *fontScheme = [[MDCBasicFontScheme alloc] init];

  // When
  [button setTitleFont:fontScheme.button forState:UIControlStateNormal];

  // Then
  UIControlState maximalControlState = UIControlStateNormal | UIControlStateSelected |
      UIControlStateDisabled | UIControlStateHighlighted;
  for (NSUInteger state = 0; state <= maximalControlState; ++state) {
      XCTAssertEqualObjects([button titleFontForState:state], fontScheme.button);
   }
}
```

### Version number
49.0.0

---
#### Internal data
- Associated internal bug: [b/117179203](http://b/117179203)

**Comment by material-mirror** [comment]
The internal issue [b/117179203](http://b/117179203) is now closed. This issue is being closed as a result.
