### ISSUE TITLE
[FeatureHighlight] FeatureHighlightViewController's -featureHighlightView should be nonnull

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3226]
### Overview
The new API for Feature Highlight to expose the view directly on the view controller resulted in a `nullable` property `featureHighlightView`. Although this view is backed by `[UIView view]` (which is `null_resettable`), the public header has it exposed as `nullable`. Instead, it should be `nonnull`.

### Version number
50.0.0

---
#### Internal data
- Associated internal bug: [b/117178996](http://b/117178996)

**Comment by material-mirror** [comment]
The internal issue [b/117178996](http://b/117178996) is now closed. This issue is being closed as a result.
