### ISSUE TITLE
[Scripts]  `release` script `notes` command ignores PRs without "[ComponentName]"

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3248]
### Overview
When running `scripts/release notes` the output markdown excludes any commits that do not have a component in square braces (`[]`) in the summary line.  This results in some commits not being listed in the release notes.

### Reproduction steps
Run `scripts/release notes` and examine the output.

**Expected Result**
For every commit that affects a component, the commit should be listed under the component section.

**Actual Result**
Commits are only listed under a component if that component name was listed in square braces (`[]`) in the commit summary line.

### Version number
51.0.0

**Comment by jverkoey** [comment]
I believe this behavior was due to an edge case in the local history and that it is not easily reproducible.
