### ISSUE TITLE
[Scripts] Release script using deprecated "gh" npm package

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3251]
### Overview
The "gh" package is deprecated.

```bash
sudo npm install -g gh
npm WARN deprecated github@0.2.4: 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)
/usr/local/bin/gh -> /usr/local/lib/node_modules/gh/bin/gh.js
+ gh@1.12.11
added 170 packages in 5.549s
```

### Reproduction steps
Follow the Releasing instructions and install `gh` via npm when prompted.

### Version number
50.0.0

---
#### Internal data
- Associated internal bug: [b/117179013](http://b/117179013)

**Comment by material-mirror** [comment]
The internal issue [b/117179013](http://b/117179013) is now closed. This issue is being closed as a result.
