### ISSUE TITLE
'

### ISSUE THREAD

**Issue by FarajiMehrdad** [material-components/material-components-ios#3286]
### Overview
For usage questions: ask on [Stack  Overflow](https://stackoverflow.com/questions/tagged/material-components+ios).

 - Context, problem or idea, solution or next step
 - Screenshots/Video (if possible)
 - Stack trace (if possible)

### Reproduction steps
 - Detailed steps to reproduce

### Version number
 - Found in CHANGELOG.md

### Related issues
 - Type `#` and the issue number or `#` and select the from the inline drop down.

**Comment by romoore** [comment]
Hi @FarajiMehrdad, it looks like this issue was opened in error. Please create a new issue if you've found a bug or are requesting a feature.
