### ISSUE TITLE
Bounded ink should ignore the maxRippleRadius property

### ISSUE THREAD

**Issue by ajsecord** [material-components/material-components-ios#329]
Right now it's possible to have bounded ink (should fill the view) with a smaller maxRippleRadius and the visual result looks like unbounded ink (a circle). 
1. Create an MDCFlatButton
2. Set .inkMaxRippleRadius to some smaller value.
3. Result: Circular ink, not filling the view.

In MDCInk, just ignore maxRippleRadius if the style is unbounded.

**Comment by romoore** [comment]
Looks like this behavior has been deprecated since October, 2016. Are we ready to bite the bullet and finally change the behavior?

**Comment by ajsecord** [comment]
Sure.
