### ISSUE TITLE
[FeatureHighlights] We should not overwriting view's Property of UIViewController.

### ISSUE THREAD

**Issue by mohammadcazig** [material-components/material-components-ios#3294]
We should not overwrite the view property of UIViewController, instead use the separate property. 
Also make sure view it's not loaded unless it's required externally. In order to do so we need to have properties in the view controller holding the state.

---
#### Internal data
- Associated internal bug: [b/117179073](http://b/117179073)

**Comment by material-mirror** [comment]
The internal issue [b/117179073](http://b/117179073) is now closed. This issue is being closed as a result.
