### ISSUE TITLE
[Dialogs] We should not overwriting view's Property of UIViewController.

### ISSUE THREAD

**Issue by mohammadcazig** [material-components/material-components-ios#3295]
We should not overwrite the view property of UIViewController, instead use the separate property. 
Also make sure view it's not loaded unless it's required externally. In order to do so we need to have properties in the view controller holding the state.

---

Pivotal story: https://www.pivotaltracker.com/story/show/156777785

**Comment by ianegordon** [comment]
This has been implemented.
