### ISSUE TITLE
[Chips] MDCChipView flips layout of subclass' subviews

### ISSUE THREAD

**Issue by brianjmoore** [material-components/material-components-ios#3307]
### Overview
In MDCChipView's layoutSubviews, it applies RTL layout by flipping all of its subviews:
https://github.com/material-components/material-components-ios/blob/f9b034955f1e7b3ed825150f14294cb1f9a97b91/components/Chips/src/MDCChipView.m#L614

Unfortunately this also flips any subviews that subclasses have added, which can cause unexpected layout behavior such as double-flipping.

### Reproduction steps
Subclass MDCChipView, add your own view and try to make it support RTL.

---

Pivotal story: https://www.pivotaltracker.com/story/show/156777784

---
#### Internal data
- Associated internal bug: [b/117179259](http://b/117179259)

**Comment by material-mirror** [comment]
The internal issue [b/117179259](http://b/117179259) is now closed. This issue is being closed as a result.
