### ISSUE TITLE
Consider making trackingScrollView a setter only.

### ISSUE THREAD

**Issue by randallli** [material-components/material-components-ios#331]
@property(nonatomic, weak, nullable) UIScrollView *trackingScrollView;
allows someone to:
appBar.headerViewController.headerView.trackingScrollView?.delegate = appBar.headerViewController; 

in this concrete case the delegate is a collectionViewDelegate and not a scrollViewDelegate.

**Comment by jverkoey** [comment]
In practice the ability to read the API hasn't necessarily resulted in the mentioned code, so marking this as working as intended.
