### ISSUE TITLE
[ButtonBar] Paddings are wrong for trailing button bars

### ISSUE THREAD

**Issue by AlimoRabbani** [material-components/material-components-ios#3315]
Trailing button bars on MDCNavigationBar have an incorrect notion of "first" and "last" button when building the buttons. The inset/padding logic below works fine for leading button bars, but on trailing button bars, the first button is still on the outer edge, which is the right side for LTR:

https://github.com/material-components/material-components-ios/blob/0797becc18f005263dfe72eb75e63246948c11e6/components/ButtonBar/src/private/MDCAppBarButtonBarBuilder.m#L182

In LTR, this issue leads to the left-most button on the trailing button bar to have additional inset on the right side, and the right-most button to have additional inset on the left side.

Internal discussion about this is in b/77863407.

**Comment by AlimoRabbani** [comment]
@jverkoey Any suggestions on how I can fix this without breaking current behavior?

**Comment by jverkoey** [comment]
This may be a bug fix that is reasonable to fix in-place (may not need a runtime flag) because it looks like the current behavior is incorrect. Do you have a PR proposal for fixing the behavior?
