### ISSUE TITLE
[Releases] Update scripts to include private component changes in CHANGELOG

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3320]
### Overview
When private components change they can have visible effects in public components. Changes to private components should be included in the CHANGELOG release notes.

### Version number
54.3.0

---

Pivotal story: https://www.pivotaltracker.com/story/show/156777781

---
#### Internal data
- Associated internal bug: [b/117179032](http://b/117179032)

**Comment by material-mirror** [comment]
The internal issue [b/117179032](http://b/117179032) is now closed. This issue is being closed as a result.
