### ISSUE TITLE
MDCTextField leadingView layout problem

### ISSUE THREAD

**Issue by rafiki270** [material-components/material-components-ios#3337]
**Release**: 54.3

**Problem**: when `leadingView` is used together with a floating placeholder, on second enter of the field the placeholder partially hides behind the `leadingView`.

**Screenshot**: https://www.dropbox.com/s/p19hucjzh828zlc/Screen%20Shot%202018-04-12%20at%2012.23.50.png?dl=0

---

Pivotal story: https://www.pivotaltracker.com/story/show/156728034

**Comment by andrewoverton** [comment]
Closing in response to https://github.com/material-components/material-components-ios/issues/3904#issuecomment-389218291
