### ISSUE TITLE
MDCChipView used inside UICollectionView crashes on iOS 9 and behaves strangely on iOS 10

### ISSUE THREAD

**Issue by cloudface** [material-components/material-components-ios#3339]
### Overview
I'm trying to display chips inside a UICollectionView. I have a button with which I can add a new chip to the collection view. 

- On iOS 11, everything works as expected: I press the button and the chip appears. 

- On iOS 10 I've noticed that the chip is added the first time I press the button but when I press the button again, no chip is added. When I press the button a third time, the second chip appears in the UICollectionView.

- On iOS 9 I can add the first chip by pressing the button once but when I press the button again, the app crashes on line 704 inside MDCChipView.m with a bad access (Thread 1: EXC_BAD_ACCESS (code=2, address=0x7ffeee5f3ffc)):

`CGSize originalTitleSize = [_titleLabel sizeThatFits:titlePaddedSize];`

 Screenshot of the sample app:
<img width="421" alt="screen shot 2018-04-12 at 13 48 09" src="https://user-images.githubusercontent.com/1231070/38675485-2f1c9bde-3e58-11e8-8cf6-93fa2f60f04d.png">

Sample app and crash logs:

[ChipsApp.zip](https://github.com/material-components/material-components-ios/files/1902995/ChipsApp.zip)

### Reproduction steps

App crash on iOS 9
1. Launch the sample app on an iOS simulator or a device with iOS 9

2. Press 'Add chip'. A chip with the text 'Chip' will appear below the button

3. Press 'Add chip' again. The app will crash

Strange behavior on iOS 10:

1. Launch the sample app on an iOS simulator or device with iOS 10

2. Press 'Add chip'. A chip with the text 'Chip' will appear below the button

3. Press 'Add chip' again. No new chip will appear

4. Press 'Add chip' again. The second chip will appear but the third one won't

### Version number
 - MaterialComponents (51.0.0)

### Operating system and device
iOS 9: Crash
iOS 10: Odd behavior
iOS 11: OK

---

Pivotal story: https://www.pivotaltracker.com/story/show/156727994

**Comment by jmdetloff** [comment]
Unfortunately this seems to be a UIKit bug. http://www.openradar.me/22948986

It seems any time you use UICollectionView with an estimatedItemSize larger than the resulting item size (with or without chips) you will see this crash on iOS 9.
