### ISSUE TITLE
Rendering MDCCard into ImageContext doesn't show the shadows

### ISSUE THREAD

**Issue by cloudface** [material-components/material-components-ios#3366]
### Overview
When trying to render an MDCCard into an image context, the card is rendered without its shadow. Is there a way to render the shadow of the card in an image context? We use a snapshot testing framework in our project [(](https://github.com/uber/ios-snapshot-test-case) which uses the image context to create screenshots (and test that our app still matches those screenshots). It would be great if the cards rendered correctly in those screenshots.

The MDCCards are rendered correctly when the app is run in the simulator so it doesn't seem to be a simulator issue. However, when the cards are rendered in an image context, the shadow is not shown:

<img width="421" alt="screen shot 2018-04-16 at 12 27 59" src="https://user-images.githubusercontent.com/1231070/38804145-a961ac4c-4171-11e8-85ce-5cf2c0fbd14b.png">

### Reproduction steps

- Download sample app

 - Open the sample app

- Launch the app in the simulator

- The card which was added through IB will appear normally. When a card is rendered into an image context, the resulting image does not contain the shadow of the card

### Version number
 - MaterialComponents (51.0.0)

### Sample app
[CardsInImageContext.zip](https://github.com/material-components/material-components-ios/files/1914855/CardsInImageContext.zip)

---
#### Internal data
- Associated internal bug: [b/117178995](http://b/117178995)

**Comment by material-mirror** [comment]
The internal issue [b/117178995](http://b/117178995) is now closed. This issue is being closed as a result.
