### ISSUE TITLE
[TextFields] How to set the MDCTextField hide/show password icon???

### ISSUE THREAD

**Issue by daveleenew** [material-components/material-components-ios#3386]
### Overview
For usage questions: ask on [Stack  Overflow](https://stackoverflow.com/questions/tagged/material-components+ios).

 - Context, problem or idea, solution or next step
 - Screenshots/Video (if possible)
 - Stack trace (if possible)

### Reproduction steps
 - Detailed steps to reproduce

### Version number
 - Found in CHANGELOG.md

### Related issues
 - Type `#` and the issue number or `#` and select the from the inline drop down.

---
https://www.pivotaltracker.com/story/show/156881905

**Comment by jverkoey** [comment]
Hi @daveleenew, can you provide a bit more context about what you're trying to do? What have you tried already?

**Comment by willlarche** [comment]
Set a UIButton or UIImageView for `.trailingView`.

**Comment by surfingtomchen** [comment]
I  find a bug, trailingview I set for the TextField will “JUMP” to the end of textFieldController placeholder text, which is the up left corner of the input box, when I call setErrorText() for the TextFieldController.


![Screen Shot 2019-12-06 at 11 19 44](https://user-images.githubusercontent.com/1343798/70350101-eb0dfc00-181a-11ea-83e7-bfcad4cdf200.png)

![Screen Shot 2019-12-06 at 11 26 00](https://user-images.githubusercontent.com/1343798/70350297-51931a00-181b-11ea-98af-9b413667f3b7.png)

the environment is iOS simulator, iOS version 13.2.2. While I run the program on iOS 10.0, there will be no such bug.

**Comment by sarojraut** [comment]
> I find a bug, trailingview I set for the TextField will “JUMP” to the end of textFieldController placeholder text, which is the up left corner of the input box, when I call setErrorText() for the TextFieldController.
> 
> ![Screen Shot 2019-12-06 at 11 19 44](https://user-images.githubusercontent.com/1343798/70350101-eb0dfc00-181a-11ea-83e7-bfcad4cdf200.png)
> 
> ![Screen Shot 2019-12-06 at 11 26 00](https://user-images.githubusercontent.com/1343798/70350297-51931a00-181b-11ea-98af-9b413667f3b7.png)
> 
> the environment is iOS simulator, iOS version 13.2.2. While I run the program on iOS 10.0, there will be no such bug.

UIKit - Resolved Issues

Prior to iOS 13, UITextField assumed that the frames of its leftView and rightView were correctly set when assigned and would never change. Starting in iOS 13, the implementation of leftViewRect(forBounds:) and rightViewRect(forBounds:) now ask the view for its systemLayoutSizeFitting(:). To achieve the previous behavior when linking against and running on iOS 13, add explicit sizing constraints on the view, wrap it in a plain UIView, or subclass the view and implement systemLayoutSizeFitting(:). (51787798)

So, to achieve same behavior, you need  implement 
override func rightViewRect(forBounds bounds: CGRect) -> CGRect {
        return CGRect(x: bounds.width - 30, y: 0, width: 24 , height: bounds.height)
    }
