### ISSUE TITLE
[ButtonBar] Document fallback behavior in `-titleFont:forState:`

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3399]
### Overview
The `titleFont:forState:` API has fallback behavior similar to UIButton. This should be documented.

---
https://www.pivotaltracker.com/story/show/156938967

**Comment by jverkoey** [comment]
I believe the titleFontForState: APIs are now behaving more similarly to our other components and the documentation has been updated to reflect this.

**Comment by jverkoey** [comment]
To confirm which components it behaves like: Chips is the other component that implements the "fall back to normal" behavior that the button bar was modeled after.

**Comment by romoore** [comment]
@jverkoey  So do Buttons and Slider.

This was fixed in #3389
