### ISSUE TITLE
Move logic for creating a back button from AppBar to NavigationBar

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#340]
The App Bar presently creates the back button in `viewWillAppear`. App Bar should still be doing this, but the actual logic for getting the back button contained in `-backButtonItem` could be moved to Navigation Bar. This will make it easier to create back buttons with Navigation Bar as a standalone component.

---
#### Internal data
- Associated internal bug: [b/117179758](http://b/117179758)

**Comment by material-mirror** [comment]
The internal issue [b/117179758](http://b/117179758) is now closed. This issue is being closed as a result.
