### ISSUE TITLE
[Slider] Write color themers that support the stateful API

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3401]
### Overview
The MDCSliderColorThemer methods should use the stateful API and drop the legacy API.

The current migrations are:

|Legacy API|Stateful API|Notes|
|---|----|----|
|color|inkColor|Ink is not currently visible|
|color|thumbColorForState:UIControlStateNormal||
|color|trackFillColorForState:UIControlStateNormal||
|disabledColor|thumbColorForState:UIControlStateDisabled||
|disabledColor|trackBackgroundColorForState:UIControlStateDisabled||
|trackBackgroundColor|trackBackgroundColorForState:UIControlStateNormal||

### Version number
54.8.0

---
#### Internal data
- Associated internal bug: [b/117179072](http://b/117179072)

**Comment by material-mirror** [comment]
The internal issue [b/117179072](http://b/117179072) is now closed. This issue is being closed as a result.
