### ISSUE TITLE
[FlexibleHeader] Incorrect safe area inset

### ISSUE THREAD

**Issue by a1anyip** [material-components/material-components-ios#3407]
### Overview
It seems like the flexible header view assumes that it is always placed at the top of the screen. While in cases like presenting a view controller in `UIPopoverController`, `MDCDeviceTopSafeAreaInset()` used for retrieving top safe area inset will return a wrong top padding, which should be zero in this case.

### Reproduction steps
 - Set up a view controller that contains `MDCFlexibleHeaderView` or `MDCAppBar`
 - Present it in `UIPopoverController`
 - There is an extra padding at the top of the nav bar, which results from the default status bar height (or safe area inset of the screen on iPhone X) returned by `MDCDeviceTopSafeAreaInset()`

**Comment by jverkoey** [comment]
Thank you for filing a bug! The flexible header view exposes `statusBarHintCanOverlapHeader` which is meant to change the behavior you mentioned, but I just looked at the code and don't see anything that affects the safe area insets when statusBarHintCanOverlapHeader is disabled.

I think an approach to fixing this might be to replace all MDCDeviceTopSafeAreaInset() calls with a method that conditionally returns the safe area insets depending on whether statusBarHintCanOverlapHeader is enabled.

**Comment by jverkoey** [comment]
This was resolved in https://github.com/material-components/material-components-ios/pull/4596. Please consider enabling `inferTopSafeAreaInsetFromViewController` on the flexible header view controller. This behavior will also be landing in the App Bar soon.
