### ISSUE TITLE
[Buttons] Unset `borderColorForState:` reverts to 0, not .normal color value

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3409]
### Overview
MDCButton's `borderColorForState:` will return `nil` if a state is not explicitly set. This may be intentional, but does not match the behavior of `titleForState:`, `titleColorForState:`, `titleShadowColorForState:` nor `attributedTitleForState:`.  I think it will be more expected for clients if the border width defaults to the value for the `.normal` state to match the related properties.

### Reproduction steps

```objectivec
- (void)testButtonBorderColorForStateFallbackBehavior {
  // Given
  MDCButton *button = [[MDCButton alloc] init];

  // When
  [button setBorderColor:UIColor.magentaColor forState:UIControlStateNormal];

  // Then
  UIControlState maximalControlState = UIControlStateNormal | UIControlStateSelected |
      UIControlStateDisabled | UIControlStateHighlighted;
  for (NSUInteger state = 0; state <= maximalControlState; ++state) {
      XCTAssertEqualObjects([button borderColorForState:state], UIColor.magentaColor);
   }
}
```

### Version number
54.8.0

---
#### Internal data
- Associated internal bug: [b/125311810](http://b/125311810)

**Comment by material-mirror** [comment]
The internal issue [b/73451677](http://b/73451677) is now closed. This issue is being closed as a result.

**Comment by romoore** [comment]
That was the wrong internal issue.
