### ISSUE TITLE
Release tooling for identifying issues that landed in a given release

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#342]
### Context

It's helpful to see what issues were resolved as part of a release. We do not currently include any such information.
### The missing functionality

When we a cut a release we should include the list of bugs that have been closed as part of the release.

The issues should be generated using a script. The script should accept a start and end git ref, similar to the `api_diff` script:

```
scripts/release/issues -o <sha> -n <sha>
```

The output of this command should be a list of closed issues in Markdown form:

```
- Closed [#333](link to issue)
- Closed [#335](link to issue)
```
### Potential work ahead
- Look into how we can identify closed issues for a range of commits. We should be able to inspect the commit messages for the `Closes|Fixes|etc... url` statement.

---
#### Internal data
- Associated internal bug: [b/117179684](http://b/117179684)

**Comment by ianegordon** [comment]
Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄

**Comment by jverkoey** [comment]
We could still benefit from having this. Might be a good first issue for someone familiar with scripting + GitHub APIs.

**Comment by material-mirror** [comment]
The internal issue [b/117179684](http://b/117179684) is now closed. This issue is being closed as a result.
