### ISSUE TITLE
[MDCActivityIndicator] is not displayed.

### ISSUE THREAD

**Issue by devRizvan13** [material-components/material-components-ios#3486]
Added MDCActivityIndicator to Storyboard. But for some reason it is not displayed. Checked on the simulator.

#Here is the code

```
import MaterialComponents

extension MDCActivityIndicator {
    func setup(with radius: CGFloat) {
        self.isHidden = true
        self.backgroundColor = .clear
        self.radius = radius
        self.cycleColors = [.white]
    }
    
    func show() {
        self.isAnimating = true
        self.isHidden = false
    }
    
    func hide() {
        self.isHidden = true
        self.isAnimating = false
    }
}
```

Method setup I call in viewDidLoad()

```
override func viewDidLoad() {
    super.viewDidLoad()
    loadingIndicator.setup(with: 8)
}
```

I call the show method when I click the button

```
func showLoading() {
    loadingIndicator.show()
}
```

---
https://www.pivotaltracker.com/story/show/157072258

**Comment by jverkoey** [comment]
Hi @devRizvan13, it looks like our API may be a bit misleading here. `isAnimating` is meant to be a readonly property — we'll be sure to fix that. Instead of setting `isAnimating` to true, you have to call `.startAnimating()` on the indicator.

**Comment by jverkoey** [comment]
Closing this issue, but please re-open if you have further questions.
