### ISSUE TITLE
Add memory leak detection

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#350]
Just open sourced: https://code.facebook.com/posts/583946315094347

---
#### Internal data
- Associated internal bug: [b/117179330](http://b/117179330)

**Comment by ianegordon** [comment]
Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄

**Comment by jverkoey** [comment]
Might be a good first issue.

**Comment by material-mirror** [comment]
The internal issue [b/117179330](http://b/117179330) is now closed. This issue is being closed as a result.
