### ISSUE TITLE
Make icons generated source borderline unreadable

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#351]
We've had multiple changes be made to the generated Icons source files now. The "Do not modify this file directly" comment is not working.

Let's fill the file with the comments over and over again. Possibly introduce some ASCII art.

**Comment by romoore** [comment]
Why is this obsolete? I think the Icons-generated source is pretty readable and nicely formatted.

**Comment by jverkoey** [comment]
Yep and that’s ok. The intent of this change was to obfuscate the results so that they wouldn’t be manually edited, but that hasn’t proven to be a problem.
