### ISSUE TITLE
[BottomSheet] Providing a trackingScrollView doesn't allow the sheet to expand

### ISSUE THREAD

**Issue by dstancioff** [material-components/material-components-ios#3519]
### Overview

The bottom sheet presentation controller is created and has it's trackingScrollViewSet _only_ on the first call to mdc_bottomSheetPresentationController. This is (as of #3325) being called from setDismissOnBackgroundTap, which when using a Bottom Sheet Controller is called during initialization. This results in the Bottom Sheet controller's trackingScrollView property to be ignored and instead relies on the discovery of a scroll view based on the contentViewController type.

### Reproduction steps
 - Create a view controller that has a nested scroll view.
 - Set the scroll view from that view controller to BottomSheetController's trackingScrollView property.
 - Present the BottomSheetController
 - Scroll the scroll view.

The scroll view will scroll in place rather than tracking.

### Version number
54.12.0

### Operating system and device
All iOS

---
#### Internal data
- Associated internal bug: [b/117179202](http://b/117179202)

**Comment by jverkoey** [comment]
I believe this should be addressed by https://github.com/material-components/material-components-ios/pull/3413. Can you try patching in to verify?

**Comment by material-mirror** [comment]
The internal issue [b/117179202](http://b/117179202) is now closed. This issue is being closed as a result.
