### ISSUE TITLE
[FlexibleHeader] Hidden views don't reappear on disabling shiftBehavior

### ISSUE THREAD

**Issue by AlimoRabbani** [material-components/material-components-ios#3559]
Hidden views due to flexible header being shifted off the screen don't reappear after setting shiftBehavior to disabled.

### Reproduction steps
  - Set shiftBehavior on the flexible header to enabled.
  - Make some view disappear when shifting off the screen using hideViewWhenShifted:
  - Make the flexible header go off the screen by scrolling.
  - Set shiftBehavior to disabled.
  - The flexible header "unshifts", but the hidden view(s) don't reappear.

**Comment by jverkoey** [comment]
By "hidden view" do you mean the flexible header view?

**Comment by AlimoRabbani** [comment]
No I think it can be *any* view that's passed on to [flexibleHeader hideViewWhenShifted:view]. This view fades out as the flexible header shifts off the screen.

https://github.com/material-components/material-components-ios/blob/f11269ad6b15cb50f9b137a4a0ff7512058166da/components/FlexibleHeader/src/MDCFlexibleHeaderView.h#L341

**Comment by jverkoey** [comment]
Oh! Got it.
