### ISSUE TITLE
MDCCatalog Themes menu doesn't appear correctly

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3570]
Repro steps:

1. Open MDCCatalog.
2. Navigate to a component landing page.
3. Tap the app settings menu.
4. Tap Themes.

Expected behavior: Nothing clipped by the app bar.
Actual behavior:

![simulator screen shot - iphone se - 2018-04-27 at 18 06 02](https://user-images.githubusercontent.com/45670/39387090-b4801032-4a45-11e8-886a-3f8d0c7df7ab.png)

---
https://www.pivotaltracker.com/story/show/157166496

**Comment by romoore** [comment]
What are the steps to reproduce this?

**Comment by jverkoey** [comment]
Added repro steps.

**Comment by romoore** [comment]
Can't reproduce.

![simulator screen shot - iphone x - 2018-05-04 at 12 58 32](https://user-images.githubusercontent.com/1753199/39641044-def0d14e-4f9a-11e8-92f2-75c9383c7b40.png)

![simulator screen shot - iphone se - 2018-05-04 at 12 59 04](https://user-images.githubusercontent.com/1753199/39641087-01e77ba8-4f9b-11e8-8d69-1708cd9e19ce.png)
