### ISSUE TITLE
Flexible header's status bar style inferrence doesn't match the onPrimary color

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3571]
Reproduction steps:

- Open MDCCatalog.
- Tap any component.
- Open the settings menu.
- Tap "Themes".
- Choose "red".

Expected behavior (colors are consistently applied):
![simulator screen shot - iphone se - 2018-04-27 at 18 30 44](https://user-images.githubusercontent.com/45670/39387719-2a69ffbc-4a49-11e8-949c-b938c8f23903.png)

Actual behavior (colors are inconsistently applied):
![simulator screen shot - iphone se - 2018-04-27 at 18 31 08](https://user-images.githubusercontent.com/45670/39387722-2cf5642e-4a49-11e8-8d20-6254af04fb5b.png)

---

Flexible header uses contrast ratios to determine whether to show a light or dark status bar, while our Catalog never changes the "onPrimary" colors (the 500 tint is often, but not always, white as far as the Material color palette is concerned).

In this case, we're using tint500 red and the FHV logic wants the status bar to be black, while the palette colors on [material.io](https://material.io/guidelines/style/color.html#color-color-palette) imply that the color should be white. Either the palettes are wrong or our FHV contrast ratio logic is wrong.

---
#### Internal data
- Associated internal bug: [b/117179239](http://b/117179239)

**Comment by jverkoey** [comment]
The research required here is to determine whether we need to update our color palette colors or whether our logic needs to be updated.

**Comment by material-mirror** [comment]
The internal issue [b/117179239](http://b/117179239) is now closed. This issue is being closed as a result.
