### ISSUE TITLE
IB Designables errors

### ISSUE THREAD

**Issue by pmiotto** [material-components/material-components-ios#3573]
### Overview
Installed this library via cocoapods/Xcode 9.3 and I keep getting the following error message:

file:///<...>.storyboard: error: IB Designables: Failed to render and update auto layout status for BookingViewController (o2P-dM-u0B): dlopen(MaterialComponents.framework, 1): no suitable image found.  Did find:
  MaterialComponents.framework: required code signature missing for 'MaterialComponents.framework'

The library is not even being used anywhere.

### Version number
Latest

### Operating system and device
Xcode 9.3, osx 10.13.4

**Comment by box86rowh** [comment]
I am getting the same error

**Comment by ianegordon** [comment]
Hi @pmiotto & @box86rowh 

Are you building an extension?
Can you verify that the MaterialComponents.framework target has a team and signing certificate?

**Comment by box86rowh** [comment]
@ianegordon in my case, I am just using the pod and get this error in Xcode until I re-run "pod install" - then it goes away for a bit but comes back almost right away

**Comment by proghjy** [comment]
@pmiotto Add FRAMEWORK_SEARCH_PATHS to the runpath search path. [CocoaPods/CocoaPods/#5334](https://github.com/CocoaPods/CocoaPods/issues/5334#issuecomment-255831772)

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['LD_RUNPATH_SEARCH_PATHS'] = ['$(FRAMEWORK_SEARCH_PATHS)']
        end
end
```

**Comment by bamz3r** [comment]
I dont think this related or not, but after updating openssl, cocoapods git and other dependencies for cocoapod to the latest, this problem gone in my project.

for updating openssl & cocoapods i found [this stackoverflow answer](https://stackoverflow.com/a/48962041/3336322)

**Comment by ianegordon** [comment]
Thanks to everyone for the insights.  It looks like this has been resolved, but if that is not the case, please re-open.
