### ISSUE TITLE
Document differences between using Flexible Header with a UIScrollView and a UITableView

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#358]
Notably: we need to document the behavior of how contentOffset is modified when contentInsets are modified in UITableView, but **not** with UIScrollView.

---
#### Internal data
- Associated internal bug: [b/117179412](http://b/117179412)

**Comment by material-mirror** [comment]
The internal issue [b/117179412](http://b/117179412) is now closed. This issue is being closed as a result.
