### ISSUE TITLE
[Buttons] Update README.md to document Interface Builder must mark MDCButtons as `custom` type

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3586]
### Overview
To prevent incorrect tint being applied to MDCButtons in their `.highlighted` state, MDCButton must be initialized as a `.custom` UIButton type.  The README should specifically call-out the case for Interface Builder, since the class initializers take care of the code-based use cases.

**Comment by jverkoey** [comment]
Added this to https://www.pivotaltracker.com/story/show/157119329.
