### ISSUE TITLE
Perform a heavy-duty instrumentation pass on the catalog and demo apps

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#364]
### Context

We want our components to consume as few cycles as is reasonably possible so that applications have more compute time per screen refresh.
### Potential work ahead

For each of our applications:
- Deploy the app to a device and run the CPU profiling instrument.
- Navigate through the entire application.
- Check the profiling results and identify any surprising metrics.
- File bugs identifying the performance problem.

---
#### Internal data
- Associated internal bug: [b/117179530](http://b/117179530)

**Comment by ianegordon** [comment]
Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄

**Comment by jverkoey** [comment]
This may actually be a good first issue because it will potentially highlight some good places to optimize our codebase.

**Comment by romoore** [comment]
I did this when I joined. I feel this is more of a "toothbrush" task: we should be doing it regularly to prevent ~tooth decay~ performance degradation.

**Comment by jverkoey** [comment]
Agreed. What do you think is a good way to schedule this sort of work?

**Comment by romoore** [comment]
Perhaps we make it a rotation of sorts? Or link it to our Fix-it Fridays? I understand not everyone that does iOS development has a lot of experience with Instruments, so it would be good to get everyone on the team familiar with performance profiling.

**Comment by material-mirror** [comment]
The internal issue [b/117179530](http://b/117179530) is now closed. This issue is being closed as a result.
