### ISSUE TITLE
Card should have a resting elevation in the typical use example

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3643]
Repro steps:

- Open the MDCCatalog
- Open the Cards typical use example.

Expected behavior: The card has a shadow border due to its resting elevation.

Actual behavior: No border in any way:

![simulator screen shot - iphone se - 2018-05-02 at 11 31 37](https://user-images.githubusercontent.com/45670/39533217-8b7ce66e-4dfc-11e8-9013-67f5cc97910e.png)

**Comment by wenyuzhang666** [comment]
This issue has been fixed. 
Screenshot:
![simulator screen shot - iphone x - 2018-08-27 at 16 56 20](https://user-images.githubusercontent.com/8836258/44685751-2e739b00-aa1a-11e8-8c29-fc42a0c019fa.png)
