### ISSUE TITLE
[FeatureHighlight] Support customized `accessibilityHint` value

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3644]
### Overview
FeatureHighlight should allow clients to set a custom value for `accessibilityHint` on the title text.  The default hint should also reference the "escape command" from VoiceOver (a 2-finger z-shaped swipe) instead of the (inaccurate) double-tap to dismiss it has currently.

### Reproduction steps
1. Open the Catalog &rarr; Feature Highlight &rarr; Start Demo
2. Turn on VoiceOver
3. Navigate to "Action" and activate it
4. Listen to the hint on the Feature Highlight title

### Version number
48.0.0, 54.13.0

Internal issue b/77907063

**Comment by romoore** [comment]
Should not reference escape command. That's bad. I was wrong.

**Comment by codeman7** [comment]
@romoore can you please confirm this is no longer and issue.
