### ISSUE TITLE
[Chips] Only apply imagePadding or titlePadding if there is an image or title (b/79146431)

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3645]
### Overview
I noticed that titlePadding/imagePadding still applies even there's no text/image set. Would it make sense to change MDCChipView to not apply titlePadding/imagePadding if the text/image is nil? I would have assumed that titlePadding doesn't apply if there's no title.

For an internal client use case, they have a chip that can either be a image+title or just an image, in which case the chip should be a perfectly round circle. But because there's titlePadding set even when text is nil, it's a lob-sided chip.

### Version number
54.13.0

Internal issue b/79146431

---
#### Internal data
- Associated internal bug: [b/79146431](http://b/79146431)

**Comment by material-mirror** [comment]
The internal issue [b/79146431](http://b/79146431) is now closed. This issue is being closed as a result.

**Comment by chamitha** [comment]
What is the recommendation here? Was it fixed or ignored?
