### ISSUE TITLE
[Catalog] Buttons typical use VoiceOver order is backwards

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3654]
Elements are read right-to-left instead of left-to-right.

We may want to consider hiding the labels from VoiceOver and instead giving better labels to the buttons.

---
https://www.pivotaltracker.com/story/show/157261857

**Comment by jverkoey** [comment]
Makes sense. Do you think it would be reasonable to simply hide the labels from VoiceOver and give better labels to the buttons themselves?

**Comment by romoore** [comment]
Probably. If the buttons themselves set their titles to their style (instead of BUTTON), we shouldn't have to do anything special for VoiceOver.

**Comment by ianegordon** [comment]
Please implement expected leading - trailing behavior.
Please test in RTL mode.
