### ISSUE TITLE
[Snackbar] Flaky tests

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3657]
```
Test Case '-[components_Snackbar_unit_test_swift_sources.SnackbarManagerSwiftTests testMessagesResumedWhenTokenIsDeallocated]' started.
Invalid connection: com.apple.coresymbolicationd
<unknown>:0: error: -[components_Snackbar_unit_test_swift_sources.SnackbarManagerSwiftTests testMessagesResumedWhenTokenIsDeallocated] : Asynchronous wait failed: Exceeded timeout of 3 seconds, with unfulfilled expectations: "completion".
Test Case '-[components_Snackbar_unit_test_swift_sources.SnackbarManagerSwiftTests testMessagesResumedWhenTokenIsDeallocated]' failed (6.871 seconds).
```

https://fusion.corp.google.com/runanalysis/test/prod%3AMaterialComponents_iOS%2Fmacos_external%2Fpresubmit_bazel_xcode_910/prod%3AMaterialComponents_iOS%2Fmacos_external%2Fpresubmit_bazel_xcode_910/KOKORO/48f82322-f39b-4eb6-b7b7-c5466820b024/1525286003510/prod%3AMaterialComponents_iOS%2Fmacos_external%2Fpresubmit_bazel_xcode_910%20Build%20%23893/Target%20Transitions?target=MaterialComponents_iOS/macos_external/presubmit_bazel_xcode_910

---
#### Internal data
- Associated internal bug: [b/117178994](http://b/117178994)

**Comment by material-mirror** [comment]
The internal issue [b/117178994](http://b/117178994) is now closed. This issue is being closed as a result.
