### ISSUE TITLE
[AppBar] When there is a table view section index, Voice Over focuses on the index first instead of the App Bar's back button

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3660]
Repro steps:

- Enable VoiceOver
- Open MDCCatalog
- Open the UITableView with section headers example

Expected behavior:
- The app bar's back button is focused and announced

Actual behavior:
- The table view section index is highlighted instead.

---
#### Internal data
- Associated internal bug: [b/117179298](http://b/117179298)

**Comment by jverkoey** [comment]
The end result here may be to encourage making the App Bar be a sibling to the UITableView rather than a subview in the component's accessibility guide.

**Comment by jverkoey** [comment]
Haven't looked at this yet, so unassigning.

**Comment by material-mirror** [comment]
The internal issue [b/117179298](http://b/117179298) is now closed. This issue is being closed as a result.
