### ISSUE TITLE
[Dialogs] VoiceOver two-finger Z dismiss gesture does nothing

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3661]
Repro steps:

- Enable VoiceOver
- Open MDCCatalog
- Open the Dialogs typical use example
- Open any dialog
- Perform the two-finger Z dismiss gesture

Expected behavior:
- The dialog dismisses

Actual behavior:
- Nothing happens

**Comment by ianegordon** [comment]
This is possibly a regression, VO dismiss used to work.

**Comment by romoore** [comment]
It works for Alerts, not Dialogs as of v54.13.0

**Comment by romoore** [comment]
Related to #4259

**Comment by ianegordon** [comment]
UIAccessibilityActions don't appear to query the UIPresentationController.
This must be handled in the custom view controller itself.
Documented in #4509
