### ISSUE TITLE
[Dialogs] Alert button hit areas need to be at least 48 pt tall

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3664]
They are currently 33 points tall.

**Comment by jverkoey** [comment]
We're not sure if this behavior is already in place. Need to verify whether the bug is obsolete or not.

**Comment by codeman7** [comment]
One option is to update the hit area insets or we can update the MDCDialogActionButtonHeight constant. I believe updating the MDCDialogActionButtonHeight will possibly break some screenshot test. If we update the hit area insets it may not respect other elements in the dialog and later if we don't realize we are doing that then we may miss something.

**Comment by codeman7** [comment]
In order to maintain the same look, if we update the MDCDialogActionButtonHeight we also need to update the MDCDialogActionInsets that are used to layout the items within their scrollview.

**Comment by codeman7** [comment]
Adjusting the height of the buttons disables scrolling in the scrollview, possible that we need to also adjust scrollview content height.

**Comment by codeman7** [comment]
This may be a button issue.

**Comment by codeman7** [comment]
Had to revert this PR
