### ISSUE TITLE
[Buttons] TouchUpOutside is triggering ink

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#3667]
Reproducible in the catalog.
Press and hold a button.
Move your finger off the button.
Lift you finger.
This will generate a TouchUpOutside event.

It is triggering the ripple.
As no action is taken, it likely should not.

---
#### Internal data
- Associated internal bug: [b/117179127](http://b/117179127)

**Comment by jverkoey** [comment]
Can you provide repro steps for this behavior? Ink is supposed to start on tap down for buttons — does this issue mean ink is being fired twice?

**Comment by romoore** [comment]
@ianegordon Could you please provide reproduction steps for this in a specific demo? A screenshot/gif would be helpful in making it obvious what the defective behavior is.

**Comment by ianegordon** [comment]
Since our ripple has been rebuilt by @yarneo I'm going to close this as obsolete.
