### ISSUE TITLE
All examples should be setting their own title

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#367]
Each example view controller should be setting its own `title` property.

**Comment by ajsecord** [comment]
This seems to be in place now.

**Comment by chuga** [comment]
Sadly this isn't fixed yet. I can't delete https://github.com/material-components/material-components-ios/blob/develop/catalog/MDCCatalog/MDCNodeListViewController.swift#L387

**Comment by ianegordon** [comment]
Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄
