### ISSUE TITLE
[TextFields] Placeholder label gets stuck in expanded state when switching between controls

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3679]
Repro steps:

1. Open MDCCatalog
2. Open the TextFields main demo
3. Select a text field
4. Press tab to cycle through the text fields
5. Press shift-tab to cycle backwards
6. Repeat 4. and 5., cycling a couple times

Expected behavior:
Placeholders for non-focused text fields stay in their "resting" position within the text field.

Actual behavior:
Placeholders get "stuck" in their expanded position.

gif demonstrating the behavior:
![rapid-bug](https://user-images.githubusercontent.com/45670/39581455-9ab1251a-4eb9-11e8-8abd-d668d1763cc6.gif)

---
#### Internal data
- Associated internal bug: [b/117179031](http://b/117179031)

**Comment by Sopheak0** [comment]
I got the same issue! pls help

**Comment by Sopheak0** [comment]
@jverkoey is there any solution to this bug yet?
