### ISSUE TITLE
Describe a simple integration of UITableView/UICollectionView with MDCInk

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#368]
**NOTE: This is part of a goal to provide a light-weight mechanism for creating Material cells**

The ideal outcome would be to use an ink ripple to fill the cell. Notably UX we'd need to maintain:
- Cell should stay "selected" until the tapped view controller reappears. This provides context to the user.
- Cell deselection on controller reappearance should be gesturally-controllable in the same way the existing UIKit selection state is.
- Can be applied to any UICollectionView or cell combination.

**NOTE: This is part of a goal to provide a light-weight mechanism for creating Material cells**

**Comment by ianegordon** [comment]
Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄

**Comment by jverkoey** [comment]
Not ignored: landed as part of the work in Lists: https://github.com/material-components/material-components-ios/tree/develop/components/List
