### ISSUE TITLE
[AnimationTiming] Demo does not layout views correctly in Landscape or after rotation to Portrait

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3684]
### Overview
When opening the "Animation Timing" demo in Landscape mode, the circles and labels overlap one another.  Rotating to Portrait from Landscape makes things even worse - the views go off-screen. On the iPhone X, the safe area insets are not respected.

**Landscape (Original)**
![screen shot 2018-05-03 at 11 36 04 am](https://user-images.githubusercontent.com/1753199/39586880-335398aa-4ec6-11e8-8abc-a73550bdc24e.png)

**Portrait (rotated)**
![simulator screen shot - iphone x - 2018-05-03 at 11 34 33](https://user-images.githubusercontent.com/1753199/39586888-3a046030-4ec6-11e8-9b10-5fde83927924.png)

### Reproduction steps
1. Open the catalog
1. Rotate to Landscape
1. Open Animation Timing
1. Open "Start Demo"
1. Rotate to portrait

### Version number
55.0.0

### Operating system and device
iPhone X/iOS 11.3 (Simulator)

### Related issues
#3681

---
#### Internal data
- Associated internal bug: [b/117178934](http://b/117178934)

**Comment by material-mirror** [comment]
The internal issue [b/117178934](http://b/117178934) is now closed. This issue is being closed as a result.
