### ISSUE TITLE
[AnimationTiming] Example has extra black bar below AppBar when rotated to Landscape from Portrait

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3685]
### Overview
The AnimationTiming demo has an extra black "bar" between the AppBar and the content view. It's actually that the content view is offset incorrectly, so the black portion is just the container view's clear background color.

**Portrait (original)**
![simulator screen shot - iphone x - 2018-05-03 at 11 38 26](https://user-images.githubusercontent.com/1753199/39587156-d6564250-4ec6-11e8-9474-91390d150d02.png)

**Landscape (rotated)**
![simulator screen shot - iphone x - 2018-05-03 at 11 38 30](https://user-images.githubusercontent.com/1753199/39587164-dc9638fa-4ec6-11e8-8242-2c11c9a8cf49.png)

### Reproduction steps
1. Open the catalog.
1. Rotate to Portrait
1. Tap on AnimationTiming
1. Tap on Start Demo
1. Rotate to Landscape

### Version number
55.0.0

### Operating system and device
iPhone X/iOS 11.3 (Simulator)

### Related issues
#3684 

---
#### Internal data
- Associated internal bug: [b/117178877](http://b/117178877)

**Comment by material-mirror** [comment]
The internal issue [b/117178877](http://b/117178877) is now closed. This issue is being closed as a result.
