### ISSUE TITLE
[Catalog] "Themes" menu does not respect safe area

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3687]
### Overview
The "Themes" menu from the Catalog 3-dot menu does not respect the safe area insets.

![screen shot 2018-05-03 at 11 46 34 am](https://user-images.githubusercontent.com/1753199/39587497-a93fee46-4ec7-11e8-8f4e-116eff180d80.png)

### Reproduction steps
1. Open the catalog
1. Rotate to Landscape
1. Tap on "Activity Indicator" (or any component)
1. Tap on the 3-dot menu in the upper-right corner
1. Select "Themes"

### Version number
55.0.0

### Operating system and device
iPhone X/iOS 11.3 (Simulator)

### Related issues
#3681

**Comment by rami-a** [comment]
Closing this, as it seems to have been fixed earlier (possibly in #5143)
