### ISSUE TITLE
Describe a simple integration of UITableView/UICollectionView with MDCShadowLayer.

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#369]
**NOTE: This is part of a goal to provide a light-weight mechanism for creating Material cells**

The ideal outcome of this is an easy way to add Material shadows to cells while satisfying the following constraints:
- Performant.
- Flexible, allowing shadow elevations to be changed when necessary.
- Supporting lists, grids, and any other cell layout.
- Can be applied to any UICollectionView implementation or cell combination.

**NOTE: This is part of a goal to provide a light-weight mechanism for creating Material cells**

**Comment by ianegordon** [comment]
Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄

**Comment by jverkoey** [comment]
Not ignored: landed as part of the work in Lists: https://github.com/material-components/material-components-ios/tree/develop/components/List
