### ISSUE TITLE
[Buttons] Demo does not reposition buttons correctly after rotation

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3690]
### Overview
The Buttons demo does not correctly layout the buttons/labels on-screen after a rotation.  When starting in Portrait and rotating to Landscape, the content view is offset and the "empty background" of the container VC's view is visible (black box). When starting in Landscape and rotating to Portrait, the buttons are positioned higher than if started in Portrait.

**Landscape (rotated)**
![buttons-land-rotate](https://user-images.githubusercontent.com/1753199/39588607-19e4f720-4eca-11e8-9f4f-d9360eff70c3.png)

**Landscape (original)**
![buttons-land-orig](https://user-images.githubusercontent.com/1753199/39588624-22667536-4eca-11e8-9b93-0fbccaab608a.png)

### Reproduction steps
1. Launch the catalog in Portrait
1. Navigate to Buttons &rarr; Start Demo
1. Rotate to Landscape

### Version number
55.0.0

### Operating system and device
iPhone X/iOS 11.3 (Simulator)

### Related issues
#3685

**Comment by rami-a** [comment]
Issue no longer happens so this must have been fixed earlier.
