### ISSUE TITLE
breakpoint at mdcoverlaywindow

### ISSUE THREAD

**Issue by tipoc123** [material-components/material-components-ios#3696]
### Overview
Sample from documentation doesn't work. My app has stopped at breakpoint (see attached screenshot).
<img width="1691" alt="2018-05-03 22 28 19" src="https://user-images.githubusercontent.com/15922591/39598779-613ebf68-4f22-11e8-9594-e11056226cb2.png">

### Reproduction steps
Try to use Overlay Window in according to documentation

### Version number
Material components 54.10.0

### Operating system and device
MacBook Pro, macOS high Sierra 10.13.4, Xcode 9.3

---
#### Internal data
- Associated internal bug: [b/117179011](http://b/117179011)

**Comment by tipoc123** [comment]
My breakpoints are empty:
<img width="1691" alt="2018-05-03 22 37 20" src="https://user-images.githubusercontent.com/15922591/39598848-9a519dac-4f22-11e8-9390-46a8c1c2ebbe.png">

**Comment by tipoc123** [comment]
More data:
<img width="1691" alt="2018-05-03 22 42 36" src="https://user-images.githubusercontent.com/15922591/39599096-5ade2cd4-4f23-11e8-814c-38ab52a989eb.png">

**Comment by material-mirror** [comment]
The internal issue [b/117179011](http://b/117179011) is now closed. This issue is being closed as a result.
