### ISSUE TITLE
MDCButtonBar doesn't respect titleTextAttributes appearance settings

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#370]
There are multiple levels to this, in descending priority:
- [x] Actual titleTextAttributesForState set on the item itself.
- [ ] titleTextAttributesForState set via `appearanceWhenContainedIn:`.
- [ ] titleTextAttributesForState set via `appearanceForTraitCollection:`.
- [x] titleTextAttributesForState set via `appearance()`. http://codereview.cc/D625

**Comment by ianegordon** [comment]
Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄

**Comment by jverkoey** [comment]
Obsolete due to us no longer actively supporting UIAppearance.
