### ISSUE TITLE
[Buttons] ButtonsShapesExampleViewController does not respect safe area

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3703]
### Overview
The labels are overlapping the notch in landscape mode. When started in Portrait and rotated to Landscape, there is an extra black bar at the top (below the AppBar) that is the backing view's empty background.

![shaped-1](https://user-images.githubusercontent.com/1753199/39627699-bca7eed6-4f74-11e8-80ef-9c7b0162e2e0.png)

### Reproduction steps
1. Open the catalog in Portrait
1. Open Buttons &rarr; Shaped Buttons
1. Rotate to landscape

### Version number
55.0.1

### Operating system and device
iPhone X/iOS 11.3 (Simulator)

### Related issues
#3685

**Comment by wenyuzhang666** [comment]
I couldn't reproduce the extra black bar issue on iPhone X and iPhone 6 (Simulator). But there was some text label overlapping safe area issues there.
