### ISSUE TITLE
[Chips] ChipsFilterExampleViewController does not lay out views correctly after rotation

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3707]
### Overview
When started in Landscape, the chips overlap the notch and do not respect the safe area. When subsequently rotated to Portrait, several chips are hidden behind the AppBar. When started in Portrait and rotated to Landscape, the content view is offset below the AppBar and the "empty" backing view can be seen.

**Landscape (original)**
![screen shot 2018-05-04 at 8 58 04 am](https://user-images.githubusercontent.com/1753199/39629273-9e9b0ff4-4f79-11e8-9d73-3ecf841e1cc2.png)

**Landscape (rotated)**
![screen shot 2018-05-04 at 8 57 32 am](https://user-images.githubusercontent.com/1753199/39629278-a0e31cd4-4f79-11e8-9bd2-4ffd2dc37a58.png)

**Portrait (rotated)**
![screen shot 2018-05-04 at 8 58 12 am](https://user-images.githubusercontent.com/1753199/39629280-a3592396-4f79-11e8-9a3b-5b2f831a88be.png)

### Reproduction steps
1. Open the catalog in Landscape
1. Open Chips &rarr; Filter
1. Note the Chips overlap with the notch
1. Rotate to Portrait
1. Note the hidden row of chips at the top
1. Close and Open Chips &rarr; Filter
1. Rotate to Landscape
1. Note the black bar below the AppBar

### Version number
55.0.1

### Operating system and device
iPhone X/iOS 11.3 (simulator)

### Related issues
#3706 

---
https://www.pivotaltracker.com/story/show/157313807

**Comment by rami-a** [comment]
The AppBar overlap, as well as content view is offset below the AppBar, no longer happens.

The safe area is still not being respected however, so I'll take a look at this
