### ISSUE TITLE
[Dialogs] Several alerts examples do not display text when Dynamic Type text is large and in Portrait orientation

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3709]
### Overview
For sufficiently large settings of Dynamic Type, several of the AlertController examples simply stop rendering the body text in Portrait orientation. The text is present in Landscape.

**Long Alert (Portrait)**
![screen shot 2018-05-04 at 9 28 10 am](https://user-images.githubusercontent.com/1753199/39630506-7e2ee64c-4f7d-11e8-931f-3d0893570c20.png)

**Long Alert (Landscape)**
![screen shot 2018-05-04 at 9 28 35 am](https://user-images.githubusercontent.com/1753199/39630521-88e47a66-4f7d-11e8-9395-6bf0f9e21de0.png)

**Overpopulated Alert**
![screen shot 2018-05-04 at 9 29 36 am](https://user-images.githubusercontent.com/1753199/39630569-b2549a84-4f7d-11e8-839e-e8e18f336214.png)

**Dynamic Type setting**
![screen shot 2018-05-04 at 9 27 42 am](https://user-images.githubusercontent.com/1753199/39630487-6d8a5358-4f7d-11e8-9d89-69742d22a531.png)

### Reproduction steps
1. Enable a very large text setting in Settings App &rarr; General &rarr; Large Text
1. Open the catalog in portrait
1. Open Dialogs &rarr; AlertController
1. Tap on "Show Long Alert" or "Overpopulated Alert"
1. For each alert, rotate to Landscape and the text will appear

### Version number
55.0.1

### Operating system and device
iPhone X/iOS 11.3 (Simulator)

---
#### Internal data
- Associated internal bug: [b/117179106](http://b/117179106)

**Comment by romoore** [comment]
Still reproducible in recent builds.

**Comment by bryanoltman** [comment]
I'm able to reproduce this in the simulator only (see screenshots from testing on device). Closing.

![IMG_8666](https://user-images.githubusercontent.com/581764/68806448-ea2ae580-0633-11ea-8e6f-e95c5c4c84ba.PNG)
![IMG_8667](https://user-images.githubusercontent.com/581764/68806450-eac37c00-0633-11ea-840e-b14447a64df3.PNG)
