### ISSUE TITLE
[Lists] When using large Dynamic Type text settings, detail text is much larger than title text

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3712]
### Overview
When Dynamic Type is set to a large value, the detail text of a cell in the Lists Demo is significantly larger than the title text in the same cell.  This seems counter-intuitive, since I would expect the title to be more significant and therefore require greater visual prominence on the screen.

![simulator screen shot - iphone x - 2018-05-04 at 09 47 02](https://user-images.githubusercontent.com/1753199/39631485-4b6cde78-4f80-11e8-8fa4-ed254213a392.png)

### Reproduction steps
1. Set Dynamic Type to a large text size in the Settings App &rarr; General &rarr; Large Text
1. Open the catalog
1. Open Lists &rarr; Start Demo

### Version number
55.0.1

### Operating system and device
iPhone X/iOS 11.3 (Simulator)

---
#### Internal data
- Associated internal bug: [b/117179010](http://b/117179010)

**Comment by romoore** [comment]
This is not an accessibility leveling issue, it's a visual style problem with how we are using typography in lists.

**Comment by material-mirror** [comment]
The internal issue [b/117179010](http://b/117179010) is now closed. This issue is being closed as a result.
