### ISSUE TITLE
[MaskedTransition] Top cell behind App Bar after rotation to Portrait

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3713]
### Overview
The topmost cell is positioned partially behind the AppBar when the example is started in Landscape and rotated to Portrait.  The bottommost cell is occluded by the left FAB because insufficient scrolling space is provided if the user scrolls all the way down.

**Portrait (FAB occlusion)**
![simulator screen shot - iphone x - 2018-05-04 at 09 56 17](https://user-images.githubusercontent.com/1753199/39631943-a8c6196c-4f81-11e8-88f5-fff4d298abb2.png)

**Landscape (rotated, cell occlusion)**
![simulator screen shot - iphone x - 2018-05-04 at 09 57 56](https://user-images.githubusercontent.com/1753199/39631953-aee2c91c-4f81-11e8-8cc5-0727cf501533.png)

### Reproduction steps
1. Launch the catalog in Landscape
1. Open Masked Transition &rarr; Start Demo
1. Rotate to Portrait

### Version number
55.0.1

### Operating system and device
iPhone X/iOS 11.3 (Simulator)

---
#### Internal data
- Associated internal bug: [b/117179084](http://b/117179084)

**Comment by material-mirror** [comment]
The internal issue [b/117179084](http://b/117179084) is now closed. This issue is being closed as a result.
