### ISSUE TITLE
[MaskedTransition] Presented sheet ignores safe area

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3714]
### Overview
The Masked Transition example completely ignores the safe area when presenting the view controller. I'm not sure if the bottom sheet should be presented within the safe area or if the presented VC should position its content within the safe area instead.

![simulator screen shot - iphone x - 2018-05-04 at 10 18 52](https://user-images.githubusercontent.com/1753199/39632998-c0825bda-4f84-11e8-8bbb-b132a9d20a2a.png)

----

![simulator screen shot - iphone x - 2018-05-04 at 10 18 56](https://user-images.githubusercontent.com/1753199/39633001-c314cf40-4f84-11e8-9b92-e894caadabea.png)

----

![simulator screen shot - iphone x - 2018-05-04 at 10 19 06](https://user-images.githubusercontent.com/1753199/39633006-c59f5924-4f84-11e8-8891-08e9ee4a9e88.png)

### Reproduction steps
1. Open the catalog
1. Open Masked Transition &rarr; Start Demo
1. Tap on one of the FABs

### Version number
55.0.1

### Operating system and device
iPhone X/iOS 11.3 (Simulator)

**Comment by rami-a** [comment]
@romoore I think the bottom sheet should position its content within the safe area. This matches the other bottom sheet examples that I've seen.

**Comment by romoore** [comment]
Sounds good to me! 👍
