### ISSUE TITLE
[PageControl] View positioned incorrectly after rotation to Landscape

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3715]
### Overview
After rotating to Landscape, the content view is offset below the App Bar. The effect is  black "box" between the App Bar and the content.

![simulator screen shot - iphone x - 2018-05-04 at 10 26 59](https://user-images.githubusercontent.com/1753199/39633390-d1bc24c0-4f85-11e8-9fe6-683efd2c03e1.png)

### Reproduction steps
1. Open the catalog in Portrait
1. Open Page Control &rarr; Start Demo
1. Rotate to Landscape

### Version number
55.0.1

### Operating system and device
iPhone X/iOS 11.3 (Simulator)

### Related issues
#3705

**Comment by wenyuzhang666** [comment]
This issue has been fixed.

Screenshot:
![simulator screen shot - iphone x - 2018-08-27 at 17 13 06](https://user-images.githubusercontent.com/8836258/44686506-7abfda80-aa1c-11e8-9d32-c3ef65cfe7e3.png)
