### ISSUE TITLE
[PageControl] Demo allow scrolling in two directions

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3716]
### Overview
Not sure if it's desired, but tap-and-holding on the page control "Demo" allows the view to be dragged both horizontally and vertically.  This creates a very strange effect when trying to swipe to change pages.

![page-scroll](https://user-images.githubusercontent.com/1753199/39633642-9250a6a2-4f86-11e8-86c9-d92741413db7.gif)

### Reproduction steps
1. Open the catalog
1. Open Page Control &rarr; Start Demo
1. Tap and hold on the content area and drag around in circles

### Version number
55.0.1

### Operating system and device
iPhone X/iOS 11.3 (Simulator)

---
#### Internal data
- Associated internal bug: [b/117179126](http://b/117179126)

**Comment by jverkoey** [comment]
Un-assigning due to inactivity. Please re-assign if you are working on this.

**Comment by material-mirror** [comment]
The internal issue [b/117179126](http://b/117179126) is now closed. This issue is being closed as a result.
