### ISSUE TITLE
[Palettes] Demo header shows shadow in portrait, not in landscape

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3717]
### Overview
After rotating from Portrait to Landscape and back to Portrait, the App Bar has a shadow in Portrait. When rotating to Landscape, there is no shadow. There was no shadow initially when opening the demo in Portrait.

If the example is launched in Landscape, then there is sometimes a shadow and sometimes not. It seems to depend on the scroll offset BEFORE rotation.

 **Portrait (rotated)**
![simulator screen shot - iphone x - 2018-05-04 at 10 36 20](https://user-images.githubusercontent.com/1753199/39633945-6ddbe8f8-4f87-11e8-856d-ae7fb86c0e7f.png)

**Landscape (rotated)**
![simulator screen shot - iphone x - 2018-05-04 at 10 36 19](https://user-images.githubusercontent.com/1753199/39633950-710d33ce-4f87-11e8-9d8d-2e96bd7810b9.png)

### Reproduction steps
1. Launch the catalog in Portrait
1. Open Palettes &rarr; Start Demo (no shadow)
1. Rotate to Landscape (no shadow)
1. Rotate back to Portrait (shadow)

1. Launch the catalog in Landscape
1. Open Palettes &rarr; Start Demo (no shadow)
1. Rotate to Portrait (shadow)
1. Rotate back to Landscape (shadow)
1. Rotate to Portrait and then scroll all the way up (shadow)
1. Rotate back to Landscape (no shadow)

### Version number
55.0.1

### Operating system and device
iPhone X/iOS 11.3 (Simulator)

---
#### Internal data
- Associated internal bug: [b/117178875](http://b/117178875)

**Comment by material-mirror** [comment]
The internal issue [b/117178875](http://b/117178875) is now closed. This issue is being closed as a result.
