### ISSUE TITLE
[ProgressView] Demo does not lay out views correctly after rotation, ignores safe area

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3718]
### Overview
When starting it in Landscape, the notch is overlapping portions of the examples. When rotated to Portrait, the first example is hidden behind the App Bar. When starting in Portrait and rotating to landscape, the content is incorrectly offset from the App Bar and the superview's background can be seen. This results in a black "box" below the App Bar.

**Portrait (rotated)**
![simulator screen shot - iphone x - 2018-05-04 at 10 48 41](https://user-images.githubusercontent.com/1753199/39634523-0b07f06c-4f89-11e8-83b6-c5b0e7c3255e.png)

**Landscape (original)**
![screen shot 2018-05-04 at 10 51 34 am](https://user-images.githubusercontent.com/1753199/39634562-235c57b6-4f89-11e8-9e34-f9e702b2b7c9.png)

**Landscape (rotated)**
![screen shot 2018-05-04 at 10 51 25 am](https://user-images.githubusercontent.com/1753199/39634568-287e1432-4f89-11e8-934d-f06c06d919a3.png)

### Reproduction steps
1. Open the catalog in Portrait
1. Open Progress View &rarr; Start Demo
1. Note the overlap of the notch and the examples
1. Close and open Progress View &rarr; Start Demo
1. Rotate to Portrait
1. Note that the first progress bar is hidden behind the App Bar

### Version number
55.0.1

### Operating system and device
iPhone X/iOS 11.3 (Simulator)

### Related issues
#3705

**Comment by galiak11** [comment]
This might be related to ["[ProgressView] Demo - labels wrong alignment - iOS12"](https://github.com/material-components/material-components-ios/issues/4785).

**Comment by romoore** [comment]
The initial alignment has gotten even worse in recent builds.  The "Progress" label is no longer even visible.

![screen shot 2018-08-21 at 9 32 27 am](https://user-images.githubusercontent.com/1753199/44404913-079efb80-a526-11e8-9c92-dd40637de4a9.png)
