### ISSUE TITLE
[Shadow] Demo does not correctly position content below App Bar after rotation to Landscape

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3719]
### Overview
After rotating from Portrait to Landscape, there is a black box visible below the App Bar. This is caused by the content view being offset too far from the AppBar. 

![simulator screen shot - iphone x - 2018-05-04 at 10 54 17](https://user-images.githubusercontent.com/1753199/39634769-a47d0c64-4f89-11e8-95a6-f710fd209bc4.png)

### Reproduction steps
1. Open the catalog in Portrait
1. Open Shadow &rarr; Start Demo
1. Rotate to Landscape

### Version number
55.0.1

### Operating system and device
iPhone X/iOS 11.3 (Simulator)

### Related issues
#3718

**Comment by wenyuzhang666** [comment]
This issue has been fixed. Screenshot attached:
![simulator screen shot - iphone x - 2018-08-29 at 15 06 16](https://user-images.githubusercontent.com/8836258/44809715-8555ad80-ab9d-11e8-96a5-2d7364278cdf.png)
