### ISSUE TITLE
[Shadows] Shadow Elevations example layout very broken after rotation

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3720]
### Overview
When started in Landscape, the notch overlaps the slider and the "shadow square" does not fit on-screen. When rotated to Portrait, the "shadow square" becomes a very skinny rectangle. When started in Portrait and rotated to Landscape, the same errors are present as well as a black box below the App Bar caused by an incorrect offset.

**Portrait (rotated)**
![screen shot 2018-05-04 at 10 57 26 am](https://user-images.githubusercontent.com/1753199/39635009-4281d50c-4f8a-11e8-852a-69bf68910fa4.png)

**Landscape (original)**
![screen shot 2018-05-04 at 10 57 16 am](https://user-images.githubusercontent.com/1753199/39635017-46ed7f7e-4f8a-11e8-9e17-0de6ef94f89b.png)

**Landscape (rotated)**
![screen shot 2018-05-04 at 10 57 40 am](https://user-images.githubusercontent.com/1753199/39635022-4a1528f0-4f8a-11e8-8fe5-43133e0fea72.png)

### Reproduction steps
1. Open the catalog in Portrait
1. Open Shadows &rarr; Shadow Elevations
1. Rotate to Landscape
1. Black bar below AppBar, notch overlap, "shadow box" does not fit on-screen.
1. Close and Open Shadows &rarr; Shadow Elevations
1. Notch overlap, "shadow box" does not fit on-screen.
1. Rotate to Portrait
1. "Shadow box" is a "skinny" rectangle, title is off-screen (to the right).

### Version number
55.0.1

### Operating system and device
iPhone X/iOS 11.3 (Simulator)

### Related issues
#3708 

---
#### Internal data
- Associated internal bug: [b/117178972](http://b/117178972)

**Comment by material-mirror** [comment]
The internal issue [b/117178972](http://b/117178972) is now closed. This issue is being closed as a result.
