### ISSUE TITLE
[Snackbar] Demo uses two different toggle button styles

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3724]
### Overview
In the Snackbar Demo, the button, "DT Off" means that Dynamic Type is currently OFF. Tapping it will enable Dynamic Type and change the button to "DT On". In contrast, the "Legacy" button means that the Snackbar is using the new style. Tapping it will *change to Legacy Snackbars* and the button will change to "New."

The buttons should be consistent - preferably by showing the current state (which matches most other examples). Instead, each button behaves opposite the other.

![simulator screen shot - iphone x - 2018-05-04 at 11 23 13](https://user-images.githubusercontent.com/1753199/39636384-05988038-4f8e-11e8-9af3-6a68bf0fc1d0.png)

### Reproduction steps
1. Open the catalog
1. Open Snackbar &rarr; Start Demo

### Version number
55.0.1

### Operating system and device
iPhone X/iOS 11.3 (Simulator)

---
#### Internal data
- Associated internal bug: [b/117179030](http://b/117179030)

**Comment by material-mirror** [comment]
The internal issue [b/117179030](http://b/117179030) is now closed. This issue is being closed as a result.
