### ISSUE TITLE
[TextFields] Text fields examples reposition views incorrectly after rotation

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3729]
### Overview
After starting in Portrait and rotating to Landscape, there is a black bar below the App Bar caused by an incorrect offset. After starting in Landscape and rotating to Portrait, the top text field is partially obscured by the App Bar.

**Portrait (rotated)**
![simulator screen shot - iphone x - 2018-05-04 at 12 10 32](https://user-images.githubusercontent.com/1753199/39638514-6be5b5f8-4f94-11e8-96ce-b8cf05b38c4e.png)

**Landscape (rotated)**
![simulator screen shot - iphone x - 2018-05-04 at 12 11 15](https://user-images.githubusercontent.com/1753199/39638516-6f6065f2-4f94-11e8-9da3-f7a65461b2b0.png)

### Reproduction steps
1. Launch the app in Portrait
1. Open Text Fields &rarr; Start Demo
1. Rotate to Landscape
1. Close and Open Text Fields &rarr; Start Demo
1. Rotate to Portrait

Repeat for "Filled Text Fields" and "Outlined Text Fields"

### Version number
55.0.1

### Operating system and device
iPhone X/iOS 11.3 (Simulator)

### Related issues
#3705

**Comment by wenyuzhang666** [comment]
This issue has been fixed. The screenshot is attached:
![simulator screen shot - iphone x - 2018-08-28 at 17 05 01](https://user-images.githubusercontent.com/8836258/44750849-8bd41e80-aae4-11e8-9851-0c5e800338f6.png)
