### ISSUE TITLE
[Typography] Example will "scroll" each time the screen rotates if started in Landscape

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3730]
### Overview
The typography example will scroll down (slightly each time it's rotated if it was opened in Landscape orientation.

### Reproduction steps
1. Open the catalog in landscape orientation
1. Open Text Fields &rarr; Start Demo
1. Rotate to Portrait and back.
1. Repeat many times

### Version number
55.0.1

### Operating system and device
iPhone X/iOS 11.3 (Simulator)

---
#### Internal data
- Associated internal bug: [b/117179200](http://b/117179200)

**Comment by material-mirror** [comment]
The internal issue [b/117179200](http://b/117179200) is now closed. This issue is being closed as a result.
