### ISSUE TITLE
Catalog in landscape iPhone hides the status bar

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#374]
We should either show the status bar or shrink the header accordingly.

![simulator screen shot apr 18 2016 11 05 38 am](https://cloud.githubusercontent.com/assets/45670/14608904/7e5789a4-0555-11e6-8b6c-9e8133dc74fb.png)

**Comment by romoore** [comment]
Looks like we now show the status bar.

![simulator screen shot - iphone se - 2018-02-16 at 11 47 48](https://user-images.githubusercontent.com/1753199/36318932-469d47c8-130f-11e8-9e46-1a945bb0f82d.png)
