### ISSUE TITLE
[Slider] Discrete slider animation is different from continuous slider

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#3752]
### Overview
The "discrete" slider and "default" slider animations are not the same. Specifically, the "discrete" slider animation seems to lag behind the thumb.

![slider-animation-compare](https://user-images.githubusercontent.com/1753199/39778101-720ca080-52d3-11e8-9078-6bb6f52ca6f4.gif)

### Reproduction steps
1. Open the Catalog &rarr; Sliders &rarr; Start Demo
1. Slide the Default Slider
1. Slide the Discrete Slider

### Version number
55.0.2

---
#### Internal data
- Associated internal bug: [b/117179218](http://b/117179218)

**Comment by material-mirror** [comment]
The internal issue [b/117179218](http://b/117179218) is now closed. This issue is being closed as a result.
