### ISSUE TITLE
Catalog in landscape iPhone Hero pages could use some layout consideration

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#376]
We currently show the hero page in the catalog as a single column.

One idea: for larger iPhones we could show a two-column layout, with the hero demo on the left and the additional examples on the right.

![simulator screen shot apr 18 2016 11 09 25 am](https://cloud.githubusercontent.com/assets/45670/14608999/f1294760-0555-11e6-8e99-c65462f81ba8.png)

**Comment by ianegordon** [comment]
Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄
