### ISSUE TITLE
[Buttons] Update all documentation references to MDCFlatButton with MDCTextButton references instead

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3762]
As an iOS Developer using MDC-iOS, I want to see documentation using the most recent recommended APIs.

-----

Definition of done:

* All documentation referring to `MDCFlatButton` are updated to use `MDCTextButton` instead.

---
#### Internal data
- Associated internal bug: [b/117179125](http://b/117179125)

**Comment by romoore** [comment]
We don't have an MDCTextButton
