### ISSUE TITLE
Write a deprecation plan for MDCCollections

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3771]
Definition of done:

There is a deprecation plan written that includes the following:

1. Timeline.
2. Migration guides from MDCCollections to Cards/Lists

---
#### Internal data
- Associated internal bug: [b/117179083](http://b/117179083)

**Comment by material-mirror** [comment]
The internal issue [b/117179083](http://b/117179083) is now closed. This issue is being closed as a result.
