### ISSUE TITLE
[Buttons] Update all documentation references to MDCRaisedButton with MDCContainedButton references instead

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3772]
As an iOS Developer using MDC-iOS, I want to see documentation using the most recent recommended APIs.

-----

Definition of done:

* All documentation referring to `MDCRaisedButton` are updated to use `MDCContainedButton` instead.

---
#### Internal data
- Associated internal bug: [b/117179199](http://b/117179199)

**Comment by romoore** [comment]
We don't have an MDCContainedButton - we perform theming instead.
