### ISSUE TITLE
[AppBar] Write a technical guide on how to implement short app bars

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3773]
Definition of done:

- There is a technical guide in the AppBar README.md that describes how to make an App Bar be a short app bar in landscape mode.

---
#### Internal data
- Associated internal bug: [b/117178396](http://b/117178396)

**Comment by material-mirror** [comment]
The internal issue [b/117178396](http://b/117178396) is now closed. This issue is being closed as a result.
