### ISSUE TITLE
[Catalog] TabBarIndicatorTemplateExample truncates title, 

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3779]
### Repro steps

1. Go to TabBarIndicatorTemplateExample, 
2. Select titled images appearance.
3. Select the middle tab.  
4. "Sleep" is truncated

|Fly|Sleep|Eat|
|---|---|---|
|![Simulator Screen Shot - iPhone 7 - 2019-05-07 at 11 27 19](https://user-images.githubusercontent.com/1753199/57312208-1da41a80-70bb-11e9-9c31-c7299fd98f2e.png)|![Simulator Screen Shot - iPhone 7 - 2019-05-07 at 11 26 56](https://user-images.githubusercontent.com/1753199/57312219-21d03800-70bb-11e9-8a4e-3f8b34adf449.png)|![Simulator Screen Shot - iPhone 7 - 2019-05-07 at 11 27 01](https://user-images.githubusercontent.com/1753199/57312230-24cb2880-70bb-11e9-8d8e-d0ed4a241ab8.png)|

---
#### Internal data
- Associated internal bug: [b/117178931](http://b/117178931)

**Comment by material-mirror** [comment]
The internal issue [b/117178931](http://b/117178931) is now closed. This issue is being closed as a result.
