### ISSUE TITLE
[Catalog] Collections Grid Example have truncated title text, also cells text truncated.

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3780]
Open Catalog on iPhone SE,
Go to collections,
go to Grid Example,
Notice the title is truncated,
Notice the cells texts are truncated,
Change the texts or update the layout to render all values with no truncation.

**Comment by ianegordon** [comment]
We are not intending on any significant updates to the current Collections component. 😞
We are working on a much simpler [List component](https://github.com/material-components/material-components-ios/tree/develop/components/List). 😄
