### ISSUE TITLE
[Catalog] In Bottom App Bar Demo when FAB is on the left there is no way to navigate back.

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3781]
### Repro steps

1. Go to Bottom App Bar Demo,
2. Select Leading Floating Button,
Notice there is no way for user to go back in this state.

Suggested solution: Add a nav bar so user can navigate back in any scenario.

---
#### Internal data
- Associated internal bug: [b/117179052](http://b/117179052)

**Comment by material-mirror** [comment]
The internal issue [b/117179052](http://b/117179052) is now closed. This issue is being closed as a result.
