### ISSUE TITLE
[Snackbar] SnackbarSusupensionExample inconsistent message display behavior - 

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3782]
Show message with no category will show on top of message A or B but not the other way around. Behavior is inconsistent.

---
#### Internal data
- Associated internal bug: [b/117178873](http://b/117178873)

**Comment by material-mirror** [comment]
The internal issue [b/117178873](http://b/117178873) is now closed. This issue is being closed as a result.
