### ISSUE TITLE
Update the build environment documentation

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3783]
As an MDC iOS client, I want to know what the supported build environments are and how to set up my own build environment to make the best use of MDC.

The build environment doc is located here:
https://github.com/material-components/material-components-ios/tree/develop/docs/build-env

---

Definition of done:

- The document lists the versions of Xcode that we support: 8.3.3, 9.0, 9.1, and 9.2.
- The document lists the versions of iOS that we support: 8.0 and up.
- The document lists the version of CocoaPods we depend on: 1.5.0

---
#### Internal data
- Associated internal bug: [b/117178435](http://b/117178435)

**Comment by material-mirror** [comment]
The internal issue [b/117178435](http://b/117178435) is now closed. This issue is being closed as a result.
