### ISSUE TITLE
Verify that all examples show their content correctly

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3784]
Definition of done:

- All examples in MDCCatalog show their content without any clipping.

---
#### Internal data
- Associated internal bug: [b/117179104](http://b/117179104)

**Comment by jverkoey** [comment]
Un-assigning due to inactivity. Please re-assign if you are working on this.

**Comment by material-mirror** [comment]
The internal issue [b/117179104](http://b/117179104) is now closed. This issue is being closed as a result.
