### ISSUE TITLE
[Buttons] Update all Catalog and component references to MDCRaisedButton with MDCContainedButtonThemer references instead

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3785]
As an iOS Developer using MDC-iOS, I want to see examples using the most recent recommended APIs.

-----

Definition of done:

* All Catalog examples referring to `MDCRaisedButton` are updated to use `MDCContainedButtonThemer ` instead.

---
#### Internal data
- Associated internal bug: [b/117178969](http://b/117178969)

**Comment by romoore** [comment]
Obsolete now that we're moving to Theming Extensions
