### ISSUE TITLE
[Cards] Remove gestureRecognizer:shouldReceiveTouch: category method

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3787]
`UICollectionViewController+MDCCardReordering.h` is a category extension on UICollectionViewController that implements the method `gestureRecognizer:shouldReceiveTouch:`. This method is not prefixed with `mdc_`, meaning there is a possibility that this method may clash with an existing implementation of this method on UICollectionViewController.

---

Definition of done:

- The `gestureRecognizer:shouldReceiveTouch:` implementation has been removed from the extension.

---
#### Internal data
- Associated internal bug: [b/117179198](http://b/117179198)

**Comment by material-mirror** [comment]
The internal issue [b/117179198](http://b/117179198) is now closed. This issue is being closed as a result.
