### ISSUE TITLE
[Buttons] Update all Catalog and component references to MDCFlatButton with MDCTextButtonThemer references instead

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3790]
As an iOS Developer using MDC-iOS, I want to see examples using the most recent recommended APIs.

-----

Definition of done:

* All Catalog examples referring to `MDCFlatButton` are updated to use `MDCTextButtonThemer` instead.

---
#### Internal data
- Associated internal bug: [b/117178930](http://b/117178930)

**Comment by romoore** [comment]
We should be using the theming extensions instead of Themers moving forward. Marking this as obsolete.
