### ISSUE TITLE
Catalog in landscape iPhone 4S: Flexible Header demo doesn't fit

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#380]
![simulator screen shot apr 18 2016 12 17 21 pm](https://cloud.githubusercontent.com/assets/45670/14611305/7d10793e-055f-11e6-89ee-731785f3fef3.png)

**Comment by wenyuzhang666** [comment]
This issue has been fixed. Screenshot attached:
![simulator screen shot - iphone 5 - 2018-08-27 at 14 44 35](https://user-images.githubusercontent.com/8836258/44679000-c3b96400-aa07-11e8-839d-e429dd484de9.png)
