### ISSUE TITLE
[Collections] Test all use cases

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3822]
Definition of done:

- [ ] All of this component's use cases have been evaluated in the accessibility audit spreadsheet located at [go/mdc-ios-a11y-matrix](http://go/mdc-ios-a11y-matrix).
- [ ] Issues have been filed for bugs that are blocking our accessibility rating.

**Comment by romoore** [comment]
Collections are not part of the accessibility leveling project.

**Comment by ianegordon** [comment]
We are not intending on any significant updates to the current Collections component. 😞
We are working on a much simpler [List component](https://github.com/material-components/material-components-ios/tree/develop/components/List). 😄
