### ISSUE TITLE
[Snackbar] Add tests for centered/leading behavior with different size traits

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3823]
At a minimum:
* Present `.centered` on Compact/Compact -> `.centered`
* Present `.leading` on Compact/Compact -> `.centered`
* Present `.centered` on Regular/Regular -> `.centered`
* Present `.leading` on Regular/Regular -> `.leading`

---
#### Internal data
- Associated internal bug: [b/117179009](http://b/117179009)

**Comment by andrewoverton** [comment]
Let's be sure to test the leading alignment capabilities in regular width/regular height environments that https://github.com/material-components/material-components-ios/pull/4163 will add when merged in.

**Comment by material-mirror** [comment]
The internal issue [b/117179009](http://b/117179009) is now closed. This issue is being closed as a result.
