### ISSUE TITLE
[Catalog] All of the demo apps are available as targets in the Catalog workspace

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3824]
As an MDC iOS client and engineer, I want to have one workspace where all of the MDC iOS apps are available to build and test.

---

Definition of done:

- Bare, Pesto, and Shrine are all listed as targets in the MDC Catalog project.

---
#### Internal data
- Associated internal bug: [b/117178968](http://b/117178968)

**Comment by material-mirror** [comment]
The internal issue [b/117178968](http://b/117178968) is now closed. This issue is being closed as a result.
