### ISSUE TITLE
Standardize our stateful API docs

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3825]
The following snippet should live in each of our stateful setter APIs:

```
In general, if a property is not specified for a state, the default is to use the
@c UIControlStateNormal value. If the @c UIControlStateNormal value is not set, then the property
defaults to a default value. Therefore, at a minimum, you should set the value for the
normal state.
```

---
#### Internal data
- Associated internal bug: [b/117179068](http://b/117179068)

**Comment by material-mirror** [comment]
The internal issue [b/117179068](http://b/117179068) is now closed. This issue is being closed as a result.
