### ISSUE TITLE
[ActivityIndicator] Demonstrate how to theme an activity indicator

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3827]
Definition of done:

---

- There is a fourth activity indicator in the typical use demo that is themed using a themer.

---
#### Internal data
- Associated internal bug: [b/117178989](http://b/117178989)

**Comment by material-mirror** [comment]
The internal issue [b/117178989](http://b/117178989) is now closed. This issue is being closed as a result.
