### ISSUE TITLE
[TextFields] Expose floatingPlaceholderFont property for customizing typography

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3831]
Textfields should allow different fonts for floating and inline placeholder. Currently it is not possible to have the floating placeholder font different than inline placeholder.  

---
#### Internal data
- Associated internal bug: [b/117179051](http://b/117179051)

**Comment by material-mirror** [comment]
The internal issue [b/117179051](http://b/117179051) is now closed. This issue is being closed as a result.
