### ISSUE TITLE
[Ink] Move legacy ink demo to a separate dragons example

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3832]
Definition of done:

- There is a separate "legacy ink" example that shows the legacy ink behavior.
- The primary ink demo does not demonstrate legacy ink.

---
#### Internal data
- Associated internal bug: [b/117178837](http://b/117178837)

**Comment by material-mirror** [comment]
The internal issue [b/117178837](http://b/117178837) is now closed. This issue is being closed as a result.
