### ISSUE TITLE
[BottomAppBar] Polish the primary demo

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3833]
Definition of done:

- The primary demo shows an app bar with the demo title and a back button.
- "Toggle floating button visibility" has a switch that can be toggled.
- Tapping the floating button does not make it disappear.
- Tapping search does not make the floating button animate to a new position.
- The three options of "leading, center, trailing" are represented using a segmented control.
- The two options of "primary, secondary elevation" are represented as a segmented control.

---
#### Internal data
- Associated internal bug: [b/117179008](http://b/117179008)

**Comment by material-mirror** [comment]
The internal issue [b/117179008](http://b/117179008) is now closed. This issue is being closed as a result.
