### ISSUE TITLE
Ensure that all examples are using `init` to create schemes

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3834]
All catalog examples should be initialized to use the latest scheme defaults.

---

Definition of done:

- There are no references to `initWithDefaults:` in the catalog.

---
#### Internal data
- Associated internal bug: [b/117178395](http://b/117178395)

**Comment by material-mirror** [comment]
The internal issue [b/117178395](http://b/117178395) is now closed. This issue is being closed as a result.
