### ISSUE TITLE
[Catalog] Make all example titles fit an iPhone SE screen without clipping

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3835]
Definition of done:

- There are no examples whose title clips on an iPhone SE in the example list view.

---
#### Internal data
- Associated internal bug: [b/117179028](http://b/117179028)

**Comment by wenyuzhang666** [comment]
A PR (https://github.com/material-components/material-components-ios/pull/4793) was created for this issue. But some design spec needs to land before the PR actually can be merged in. Note here for reference.

**Comment by jverkoey** [comment]
Unassigning due to inactivity. Please re-assign yourself if you are working on this.

**Comment by material-mirror** [comment]
The internal issue [b/117179028](http://b/117179028) is now closed. This issue is being closed as a result.
