### ISSUE TITLE
[AppBar] Show how to theme an app bar with a surface variant

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3836]
Definition of done:

- There is a UI for selecting either primary or surface theming.
- Changing the selection immediately re-applies the scheme to the component with the selected variant.

---
#### Internal data
- Associated internal bug: [b/117178115](http://b/117178115)

**Comment by material-mirror** [comment]
The internal issue [b/117178115](http://b/117178115) is now closed. This issue is being closed as a result.
