### ISSUE TITLE
[BottomNavigation] Show how to theme a bottom navigation with a surface variant

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3837]
Definition of done:

- There is a UI for selecting either primary or surface theming.
- Changing the selection immediately re-applies the scheme to the component with the selected variant.

---
#### Internal data
- Associated internal bug: [b/117178929](http://b/117178929)

**Comment by romoore** [comment]
This is blocked on having color themers for Bottom Navigation.

**Comment by jverkoey** [comment]
What's the issue tracking that work?

**Comment by material-mirror** [comment]
The internal issue [b/117178929](http://b/117178929) is now closed. This issue is being closed as a result.
