### ISSUE TITLE
[Bottom Drawer] Verify that there is a guide in Bottom App Bar's readme on how to present a bottom sheet

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3844]
Definition of done:

- There is a guide in Bottom App Bar's README.md that shows how to present a bottom sheet.

---
#### Internal data
- Associated internal bug: [b/117178871](http://b/117178871)

**Comment by material-mirror** [comment]
The internal issue [b/117178871](http://b/117178871) is now closed. This issue is being closed as a result.
