### ISSUE TITLE
[Bottom Navigation] Verify that the component supports color and typography properties required by the spec

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3845]
Definition of done:

- BottomNavigation supports color and typography theming according to the spec.

---
#### Internal data
- Associated internal bug: [b/117179027](http://b/117179027)

**Comment by romoore** [comment]
Does this mean that it has sufficient properties for theming or that it has themers ready to use?

**Comment by material-mirror** [comment]
The internal issue [b/117179027](http://b/117179027) is now closed. This issue is being closed as a result.
