### ISSUE TITLE
[Chips] Verify that the component supports color, shape, and typography according to the spec

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3849]
Definition of done:

- Chips supports color, shape, and typography theming according to the spec.

---
#### Internal data
- Associated internal bug: [b/117178836](http://b/117178836)

**Comment by bhamiltoncx** [comment]
From my perspective, missing spec bits for `MDCChipsField` are:

1) Blue line under text input while focused
2) Shrinking placeholder text and turning it blue while focused
3) Gray background

**Comment by material-mirror** [comment]
The internal issue [b/117178836](http://b/117178836) is now closed. This issue is being closed as a result.
