### ISSUE TITLE
[Progress indicators] Verify that the ProgressBar component supports color theming according to the spec

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3856]
Definition of done:

- ActivityIndicator and ProgressView support color theming according to the spec.

---
#### Internal data
- Associated internal bug: [b/117178434](http://b/117178434)

**Comment by material-mirror** [comment]
The internal issue [b/117178434](http://b/117178434) is now closed. This issue is being closed as a result.
