### ISSUE TITLE
Catalog in landscape iPhone 4S: Shadow Elevations demo is cropped

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#386]
![simulator screen shot apr 18 2016 12 23 47 pm](https://cloud.githubusercontent.com/assets/45670/14611470/62b0d952-0560-11e6-835a-0280571de551.png)

---
#### Internal data
- Associated internal bug: [b/117179551](http://b/117179551)

**Comment by jverkoey** [comment]
Un-assigning due to inactivity. Please re-assign if you are working on this.

**Comment by material-mirror** [comment]
The internal issue [b/117179551](http://b/117179551) is now closed. This issue is being closed as a result.
