### ISSUE TITLE
[BottomAppBar] with voiceover on in bottom app bar, "leading floating button" "covers" the menu button and prevents a user from linearly swiping to get out of this page

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3867]
From Dahlia:

> With voiceover on in bottom app bar, "leading floating button" "covers" the menu button and prevents a user from linearly swiping to get out of this page. (also an issue if VO isn't on). also concerned about potential buttons in the middle behind on center FAB. if this is intended can we at least add an a11y hint?

**Comment by ianegordon** [comment]
What is the intended behavior?

**Comment by romoore** [comment]
That menu button is just there for the example. This sounds like a bug unique to the catalog example we have.

**Comment by jmdetloff** [comment]
If I'm understanding this correctly, I believe this bug is obsolete now that this example has an app bar with a back button. Assigning to @jverkoey just to confirm before closing

**Comment by jverkoey** [comment]
That sounds accurate.
