### ISSUE TITLE
[Catalog] Update examples to use protocols for their scheme properties rather than concrete examples

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3869]
MDCSemanticColorScheme -> MDCColorScheming
MDCTypographyScheme -> MDCTypographyScheming

---
#### Internal data
- Associated internal bug: [b/117179103](http://b/117179103)

**Comment by material-mirror** [comment]
The internal issue [b/117179103](http://b/117179103) is now closed. This issue is being closed as a result.
