### ISSUE TITLE
[Catalog] set cell selection style to none.

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3870]
UITableViewCellSelection needs to be none when there is no meaningful selection on the cell.
Examples to update:
Activity Indicator Demo
App Bar Demo
AppBarSectionHeaderExample
AppBarImageryExample

**Comment by romoore** [comment]
Should this also be on the BottomAppBar or Snackbar demos?  Is there a different issue for those?

**Comment by jverkoey** [comment]
There isn't a separate issue but we should ideally be consistent across all of the examples.
