### ISSUE TITLE
[MaskedTransition] Test all use cases

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3871]
Definition of done:

- [ ] All of this component's use cases have been evaluated in the accessibility audit spreadsheet located at [go/mdc-ios-a11y-matrix](http://go/mdc-ios-a11y-matrix).
- [ ] Issues have been filed for bugs that are blocking our accessibility rating.

---
#### Internal data
- Associated internal bug: [b/117179007](http://b/117179007)

**Comment by romoore** [comment]
This component is not part of the accessibility leveling project.

**Comment by material-mirror** [comment]
The internal issue [b/117179007](http://b/117179007) is now closed. This issue is being closed as a result.
