### ISSUE TITLE
Add accessibility notes to component READMEs

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3872]
- [ ] [Related internal bug b/78582666](http://b/78582666)

**Comment by romoore** [comment]
@jverkoey Didn't you file this issue?

**Comment by romoore** [comment]
This internal bug should not be tracked in GitHub.

**Comment by romoore** [comment]
Closing this bug. We shouldn't be doing "all the things" in one Issue. The internal reference is also unrelated to MDC-iOS docs.
