### ISSUE TITLE
[Buttons] Add an a11y guide on ensuring a minimum hit area

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3873]
## Definition of done

- [ ] There is a guide in the [Buttons/docs](https://github.com/material-components/material-components-ios/tree/develop/components/Buttons/docs) directory that explains how to ensure a minimum button hit area.
- [ ] `./scripts/generate_readme Buttons` has been run again to update the component's root readme.

**Comment by randallli** [comment]
starting this

**Comment by jverkoey** [comment]
Are you still working on this @randallli ? Please unassign yourself if not and post a comment describing the work you've done already.

**Comment by jverkoey** [comment]
Ah, this looks like it has already landed: https://github.com/material-components/material-components-ios/tree/develop/components/Buttons#minimum-touch-size
