### ISSUE TITLE
[Dialogs] Add a11y guide on enabling the two-finger z to dismiss gesture

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3878]
## Definition of done

- [ ] There is a guide in the [Dialogs/docs](https://github.com/material-components/material-components-ios/tree/develop/components/Dialogs/docs) directory that explains how to enable the two-finger z to dismiss gesture.
- [ ] `./scripts/generate_readme Dialogs` has been run again to update the component's root readme.

**Comment by jverkoey** [comment]
@ianegordon Are you still working on this? Please unassign if not.

**Comment by jverkoey** [comment]
This looks like something where we should support the Z-swipe gesture behavior out of the box. Is there anything that needs to be written here?

**Comment by ianegordon** [comment]
This was closed by #4509.
