### ISSUE TITLE
[ActivityIndicator] Make ActivityIndicatorExample.swift match the Objective-C demo

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3879]
Definition of done:

- The swift typical use example provides the same functionality as the Objective-C typical use example.
- The demo is still a dragons demo.

---
#### Internal data
- Associated internal bug: [b/117179080](http://b/117179080)

**Comment by material-mirror** [comment]
The internal issue [b/117179080](http://b/117179080) is now closed. This issue is being closed as a result.
