### ISSUE TITLE
[Catalog] Implement a color scheme builder

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3880]
As an MDC iOS client, I want to be be able to preview a custom theme.

---

Definition of done:

- In the theme selector UI, there is an option to create a new custom color scheme.
- Tapping this option will present a new UI for editing a color scheme.
- The created color scheme is saved in to the app's user defaults.
- The created color scheme is listed as a custom color scheme in the theme selector UI.

---
#### Internal data
- Associated internal bug: [b/117178987](http://b/117178987)

**Comment by material-mirror** [comment]
The internal issue [b/117178987](http://b/117178987) is now closed. This issue is being closed as a result.
