### ISSUE TITLE
[Catalog] Implement a theme previewer

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3881]
As an MDC-iOS developer, I want there to be an easy way to see the effects of changing my theme's properties on the individual components.

---

Definition of done:

- When changing the theme, it is possible to preview the theme with a stickersheet of components.
- Ideally, changes to the theme would immediately affect the components so that changes could be understood in real time.

---
#### Internal data
- Associated internal bug: [b/117178834](http://b/117178834)

**Comment by material-mirror** [comment]
The internal issue [b/117178834](http://b/117178834) is now closed. This issue is being closed as a result.
