### ISSUE TITLE
[Catalog] Examples that show on-screen text make use of the Banner component

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3882]
Examples should show informative text using a banner rather than showing the text in-line with the example's canvas area.

---

Definition of done:

- Any component that requires on-screen text to be displayed is updated to use the banner component.

---
#### Internal data
- Associated internal bug: [b/117178910](http://b/117178910)

**Comment by material-mirror** [comment]
The internal issue [b/117178910](http://b/117178910) is now closed. This issue is being closed as a result.
