### ISSUE TITLE
[Catalog] Update the home screen component icons

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3883]
Definition of done:

- Every component's home screen icon has been updated to match the latest mocks.
- The icons have been taken from the folder at the `mdc-ios-catalog-icons` short link.

---
#### Internal data
- Associated internal bug: [b/117179067](http://b/117179067)

**Comment by material-mirror** [comment]
The internal issue [b/117179067](http://b/117179067) is now closed. This issue is being closed as a result.
