### ISSUE TITLE
[Catalog] Implement a shared "configurations panel" component for example usage

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3884]
As an MDC iOS engineer, I want to be able to instantiate a configuration panel on some of my examples that allows me to configure certain aspects of the example.

A good example of one of these panels is in the Activity Indicator typical use example.

---

Definition of done:

- There is a private component that houses this configuration panel.
- The panel exposes a view controller class.
- The view controller can be initialized with a list of control types.
- The view controller has a delegate for responding to control changes.
- The view controller, once added to a view hierarchy, will show a list of configuration controls.
- Changing any of the configuration controls will inform the delegate.
- Each configurator consists of a title and a control.

Some of the desired controls are:

- Action buttons.
- Switches. For on/off behaviors.
- Segmented controls. For groups of related options.
- Sliders. When slider values change, the text label should change to reflect the new value.

---
#### Internal data
- Associated internal bug: [b/117178966](http://b/117178966)

**Comment by material-mirror** [comment]
The internal issue [b/117178966](http://b/117178966) is now closed. This issue is being closed as a result.
