### ISSUE TITLE
[ButtonBar] Migrate MDCButtonBarButton off of MDCFlatButton

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3887]
Definition of done:

- MDCButtonBarButton is no longer subclassing MDCFlatButton.

---
#### Internal data
- Associated internal bug: [b/117179047](http://b/117179047)

**Comment by material-mirror** [comment]
The internal issue [b/117179047](http://b/117179047) is now closed. This issue is being closed as a result.
