### ISSUE TITLE
[Chips] MDCChipCollectionViewCell alwaysAnimateResize does not work properly with collectionView Reload Data.

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3888]
Calling reload data and selecting the cells in code does not work properly when alwaysAnimateResize is true.
Step to reproduce:
set selected image for chips.
Select a chip in collection view reload data and reselect the cell to keep the selection.
Notice that selected image does not appear while layout is bigger.

---
#### Internal data
- Associated internal bug: [b/117178392](http://b/117178392)

**Comment by material-mirror** [comment]
The internal issue [b/117178392](http://b/117178392) is now closed. This issue is being closed as a result.
