### ISSUE TITLE
[BottomAppBar] Implement a typography themer

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3890]
Definition of done:

- There is a MDCBottomAppBarTypographyThemer API that matches our typography themer API patterns.

---
#### Internal data
- Associated internal bug: [b/117179102](http://b/117179102)

**Comment by jverkoey** [comment]
Unassigning due to inactivity. Please re-assign yourself if you are working on this.

**Comment by material-mirror** [comment]
The internal issue [b/117179102](http://b/117179102) is now closed. This issue is being closed as a result.
