### ISSUE TITLE
[ProgressView] Implement a color themer

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3891]
Definition of done:

- There is an applySemanticColorScheme API in MDCProgressViewColorThemer that accepts an MDCColorScheming type.

---
#### Internal data
- Associated internal bug: [b/117179065](http://b/117179065)

**Comment by material-mirror** [comment]
The internal issue [b/117179065](http://b/117179065) is now closed. This issue is being closed as a result.
