### ISSUE TITLE
[PageControl] Implement a color themer

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3893]
Definition of done:

- There is an applySemanticColorScheme API in MDCPageControlColorThemer that accepts an MDCColorScheming type.

---
#### Internal data
- Associated internal bug: [b/117178868](http://b/117178868)

**Comment by bond-** [comment]
@jverkoey Any ETA on this?

**Comment by material-mirror** [comment]
The internal issue [b/117178868](http://b/117178868) is now closed. This issue is being closed as a result.
