### ISSUE TITLE
[ActivityIndicator] isAnimating should be a readonly property

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3894]
As an MDC iOS client, I may find it confusing that isAnimating is a settable property. This was made apparent in #157072258.

---

Definition of done:

- setIsAnimating is marked deprecated for at least one release.
- The `isAnimating` property is marked as readonly.

---
#### Internal data
- Associated internal bug: [b/117179079](http://b/117179079)

**Comment by material-mirror** [comment]
The internal issue [b/117179079](http://b/117179079) is now closed. This issue is being closed as a result.
