### ISSUE TITLE
[TextFields] Remove transformation between inline and floating placeholder. (use separate UILabels)

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3906]
To have a pixel perfect quality and in order to customize the font of floating and inline placeholder, we need to use to different UILabels for them.

---
#### Internal data
- Associated internal bug: [b/117179046](http://b/117179046)

**Comment by material-mirror** [comment]
The internal issue [b/117179046](http://b/117179046) is now closed. This issue is being closed as a result.
