### ISSUE TITLE
Many examples do not allow you to go back

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#391]
Some of our catalog examples have no back button, making it difficult to go back to the previous context. Every example should have a back button.

---
#### Internal data
- Associated internal bug: [b/117179469](http://b/117179469)

**Comment by jgunaratne** [comment]
The text on the remaining swipe to go back examples now has accompanying text "swipe right from left edge to go back"

**Comment by romoore** [comment]
The following are still missing any text or a back button:

### Flexible Header
* "Floating Action Button"
* "Horizontal Paging"
* "Page Control in Flexible Header"
* "Utilizing Top Layout Guide"
* "Wrapped View Controller"

### Navigation Bar
* "Navigation Bar Item Layout"
* "Navigation Bar With Icons"

**Comment by material-mirror** [comment]
The internal issue [b/117179469](http://b/117179469) is now closed. This issue is being closed as a result.
