### ISSUE TITLE
[Slider] Implement a Typography themer

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3922]
As an iOS Developer using MDC-iOS, I want to be able to theme an instance of this component using MDCTypographyScheming.

-----

Requirements:

* All typography themer code lives in the component's `src/TypographyThemer` directory. 
* There is a class named `MDCSliderTypographyThemer`.
* The public API of `MDCSliderTypographyThemer` defines one static method that accepts a typography scheme (`nonnull id<MDCTypographyScheming>`) and an instance of the component.
* The static method's name follows the pattern of `applyTypographyScheme:toSlider:`.
* The implementation of the static method maps the parameters of the typography scheme to the relevant parameters on the component, as defined at the `mdc-ios-params` short link.
* A CocoaPods target exists for the TypographyThemer as an extension.
* A BUILD target exists for the TypographyThemer.

-----

Definition of done:

1. Given an `<MDCTypographyScheming>` and an instance of this component, I can apply the typography scheme to the component using the themer.
2. The Themer only uses the public API of the component.

---
#### Internal data
- Associated internal bug: [b/117178832](http://b/117178832)

**Comment by material-mirror** [comment]
The internal issue [b/117178832](http://b/117178832) is now closed. This issue is being closed as a result.
