### ISSUE TITLE
Document how to implement UIControlState-based APIs

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3925]
As an MDC iOS engineer, I want to know what the recommended best practice is for implementing UIControlState-based APIs. 

---

Definition of done:

- There is a document that defines the pattern for implementing UIControlState-based APIs.
- The document has been reviewed and accepted by the team.

---
#### Internal data
- Associated internal bug: [b/117179120](http://b/117179120)

**Comment by material-mirror** [comment]
The internal issue [b/117179120](http://b/117179120) is now closed. This issue is being closed as a result.
