### ISSUE TITLE
[AppBar] Expose API for customizing shape

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3926]
As an MDC iOS client, I want to be able to customize the shape of my App Bar.

---

Definition of done:

- There is an API for setting a shape generator on the app bar.

```
@property(nullable, nonatomic, strong) id<MDCShapeGenerating> shapeGenerator;
```

- Setting this API customizes the shape of the app bar's container view (the flexible header view) and shadow.

---
#### Internal data
- Associated internal bug: [b/117179063](http://b/117179063)

**Comment by material-mirror** [comment]
The internal issue [b/117179063](http://b/117179063) is now closed. This issue is being closed as a result.
