### ISSUE TITLE
[BottomAppBar] Implement a primary Color themer API

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3929]
As an MDC iOS client, I want to be able to theme my bottom app bar using an MDCColorScheming instance.

---

Definition of done:

- There is an API on MDCBottomAppBarColorThemer with the signature `+applySemanticColorScheme:toBottomAppBarView:`.
- The method accepts an id<MDCColorScheming> and an MDCBottomAppBarView.
- The method implements the primary mapping defined spec parameters document.

---
#### Internal data
- Associated internal bug: [b/117178865](http://b/117178865)

**Comment by material-mirror** [comment]
The internal issue [b/117178865](http://b/117178865) is now closed. This issue is being closed as a result.
