### ISSUE TITLE
Discuss alternate solutions to customizing cells

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#393]
Cells are typically subclassed with UIKit in order to customize them. This pattern leads to large subclassing trees, often with very little room for making minor adjustments.

Generally speaking there are a variety of other solutions to this problem being explored. We cannot assume that we are the only solution being used in an application.

Let's use this thread to discuss potential solutions.

**Comment by ianegordon** [comment]
Opened more than two years ago.
Please re-open if you feel strongly.
