### ISSUE TITLE
Define and roll out a comprehensive testing plan for stateful APIs

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3932]
Many of our components now expose stateful APIs, e.g. `setFont:forState:`. As an MDC iOS engineer, I want there to be a single, well-defined way to implement these tests.

---

Definition of done:

- There is some form of guidance, be it a design doc, code snippet, or shared testing API that encourages a consistent and thorough testing process for stateful APIs.

---
#### Internal data
- Associated internal bug: [b/117178430](http://b/117178430)

**Comment by material-mirror** [comment]
The internal issue [b/117178430](http://b/117178430) is now closed. This issue is being closed as a result.
