### ISSUE TITLE
Write a deprecation plan for MDCTypography

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3952]
As an MDC-iOS client, I want to know how to migrate off of the MDCTypography API.

---

Definition of done:

- The deprecation plan includes:
  1. A migration guide from MDCTypography to MDCTypographyScheme.
  2. A deprecation timeline indicating when MDCTypography will marked deprecated and when it will be deleted.
  3. The deprecation plan has been announced to Google mailing lists.

---
#### Internal data
- Associated internal bug: [b/117179119](http://b/117179119)

**Comment by material-mirror** [comment]
The internal issue [b/117179119](http://b/117179119) is now closed. This issue is being closed as a result.
