### ISSUE TITLE
[Catalog] Remove references to MDCTypography

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3953]
---
#### Internal data
- Associated internal bug: [b/117177677](http://b/117177677)
- Blocked by: https://github.com/material-components/material-components-ios/issues/3954
- Blocked by: https://github.com/material-components/material-components-ios/issues/3955
- Blocked by: https://github.com/material-components/material-components-ios/issues/3956
- Blocked by: https://github.com/material-components/material-components-ios/issues/3957
- Blocked by: https://github.com/material-components/material-components-ios/issues/3958
- Blocked by: https://github.com/material-components/material-components-ios/issues/3960
- Blocked by: https://github.com/material-components/material-components-ios/issues/3959
- Blocked by: https://github.com/material-components/material-components-ios/issues/3961
- Blocked by: https://github.com/material-components/material-components-ios/issues/3962

**Comment by material-mirror** [comment]
The internal issue [b/117177677](http://b/117177677) is now closed. This issue is being closed as a result.
