### ISSUE TITLE
Verify that there is no usage of MDCTypography within our repo

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3963]
As an MDC iOS engineer, I want our components to be initialized with sensible defaults without relying on MDCTypography.

---

Definition of done:

- Every reference to MDCTypography in our component source has been replaced with simpler defaults.

---
#### Internal data
- Associated internal bug: [b/117179023](http://b/117179023)
- Blocked by: https://github.com/material-components/material-components-ios/issues/3953

**Comment by material-mirror** [comment]
The internal issue [b/117179023](http://b/117179023) is now closed. This issue is being closed as a result.
