### ISSUE TITLE
Migrate internal client usage of UIAppearance to explicit APIs

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3965]
---
#### Internal data
- Associated internal bug: [b/117178906](http://b/117178906)

**Comment by ianegordon** [comment]
Closing as an internal issue.
If you would like to tracking this externally, please open an internal bug and mirror it to GitHub.

**Comment by jverkoey** [comment]
If we intend to do this work internally let’s file the internal bug before closing this issue. Closing the issue alone doesn’t help us solve the internal work.

**Comment by material-mirror** [comment]
The internal issue [b/117178906](http://b/117178906) is now closed. This issue is being closed as a result.
