### ISSUE TITLE
[Tabs] Discuss accessibility concerns of surface mapping with design

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3969]
The surface variant places a primary color on top of a surface color. There is no guarantee that this will pass accessibility requirements. We need to determine how the design system intends to handle this case so that the colors can pass accessibility.

---
#### Internal data
- Associated internal bug: [b/117177676](http://b/117177676)

**Comment by material-mirror** [comment]
The internal issue [b/117177676](http://b/117177676) is now closed. This issue is being closed as a result.
