### ISSUE TITLE
[ThumbTrack] MDCThumbTrack causes extra layout by realigning valueLabel to pixel boundaries

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3973]
### Overview
In `-updateViewsMainIsAnimated:withDuration:animationOptions:`, the `valueLabel` frame is updated twice. Once with `center` and again with `frame`. When the second alignment (for pixel-aligned text) is removed, the extra layout pass is stopped.

Ideally, we should only set the label's center/frame once. Instead of setting it, then realigning it, we should compute it once with the correct pixel alignment and then assign that value.

### Version number
54.3.0

---

https://github.com/material-components/material-components-ios/issues/3326

---
#### Internal data
- Associated internal bug: [b/117179022](http://b/117179022)

**Comment by material-mirror** [comment]
The internal issue [b/117179022](http://b/117179022) is now closed. This issue is being closed as a result.
