### ISSUE TITLE
Remove UIAppearance from our component checklist

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3977]
The checklist is here:

https://docs.google.com/spreadsheets/d/e/2PACX-1vRQLFMuo0Q3xsJp1_TdWvImtfdc8dU0lqX2DTct5pOPAEUIrN9OsuPquvv4aKRAwKK_KItpGs7c4Fok/pubhtml

---
#### Internal data
- Associated internal bug: [b/117178963](http://b/117178963)

**Comment by material-mirror** [comment]
The internal issue [b/117178963](http://b/117178963) is now closed. This issue is being closed as a result.
