### ISSUE TITLE
[kokoro] Add a linter for verifying that BUILD files use correct casing

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3978]
We've recently seen BUILD files reference folders using casing that did not match the file system casing, causing flaky builds. E.g. `//components/Schemes/Color` instead of `//components/schemes/Color`.

As an MDC iOS engineer, I want this type of mistake to be caught by automated lint tooling, probably on kokoro.

---

Definition of done:

- Create a kokoro job that performs lint checks on our code.
- One linter will be to validate that our BUILD file dependencies all reference folder paths with correct casing.

---
#### Internal data
- Associated internal bug: [b/117178113](http://b/117178113)

**Comment by material-mirror** [comment]
The internal issue [b/117178113](http://b/117178113) is now closed. This issue is being closed as a result.
