### ISSUE TITLE
[kokoro] Find a way to publish releases to CocoaPods automatically

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3979]
If we can somehow run `pod trunk publish` on kokoro once a tag is cut then we could save the 15-20 minutes required to lint the podspec before publishing.

---
#### Internal data
- Associated internal bug: [b/117178905](http://b/117178905)

**Comment by material-mirror** [comment]
The internal issue [b/117178905](http://b/117178905) is now closed. This issue is being closed as a result.
