### ISSUE TITLE
Flexible Header support for trait collections

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#398]
The following properties should be configurable for different trait collections:
- minimumHeight
- maximumHeight

https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITraitCollection_ClassReference/

---
#### Internal data
- Associated internal bug: [b/117179237](http://b/117179237)

**Comment by material-mirror** [comment]
The internal issue [b/117179237](http://b/117179237) is now closed. This issue is being closed as a result.
