### ISSUE TITLE
[kokoro] Shorten the github status names

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3981]
The kokoro github PR status names all have continuous-integration spelled out because codecov requires it in order to detect the status of CI.

Instead, only the kokoro runner that is actually posting to codecov (should be cocoapods Xcode 9.2) should have `ci` in the name. All other jobs should just list kokoro.

https://docs.codecov.io/v4.3.6/docs/detecting-ci-services

---
#### Internal data
- Associated internal bug: [b/117179045](http://b/117179045)

**Comment by material-mirror** [comment]
The internal issue [b/117179045](http://b/117179045) is now closed. This issue is being closed as a result.
