### ISSUE TITLE
[kokoro] Suggest enabling verbosity when builds/tests fail

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#3989]
From @romoore:

> Can we capture the return value of the builds/tests and if we detect a non-zero, spit out the VERBOSE=1 as a suggestion for debugging?

---
#### Internal data
- Associated internal bug: [b/117178904](http://b/117178904)

**Comment by material-mirror** [comment]
The internal issue [b/117178904](http://b/117178904) is now closed. This issue is being closed as a result.
