### ISSUE TITLE
Create a bootcamp checklist of essential skills for our team

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4001]
Skills:

- Cutting a release
- Cutting a hotfix release
- Patching in a change to an in-progress release
- Deprecating and removing an API
- Creating a new component (design doc, API review, etc...)
- Answering questions on help forums
- Reviewing others' code
- Writing tests

---
#### Internal data
- Associated internal bug: [b/117177637](http://b/117177637)

**Comment by material-mirror** [comment]
The internal issue [b/117177637](http://b/117177637) is now closed. This issue is being closed as a result.
