### ISSUE TITLE
Update the release process docs to tag the release only after the internal CL lands

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4008]

**Comment by ianegordon** [comment]
I believe the order is:

Cut a release-candidate from develop.

Release engineer
copybara import release-candidate to CL
Global Presubmit CL
(Repeat above three steps until CL passes testing)

Merge release-candidate to develop and stable

Tag vX.Y.Z release on stable

copybara import stable into CL (Should only change METADATA file)

We have an internal client that relies on this order.

**Comment by jverkoey** [comment]
This is done.
