### ISSUE TITLE
[TextFields] Modernize the styling implementation

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4009]
As an MDC-iOS client, I want to be able to theme MDC components in a consistent manner.

---

Definition of done:

- All of the global static styling methods are removed.
- Instance-based styling APIs are added to the relevant APIs.

---
#### Internal data
- Associated internal bug: [b/117179019](http://b/117179019)

**Comment by material-mirror** [comment]
The internal issue [b/117179019](http://b/117179019) is now closed. This issue is being closed as a result.
