### ISSUE TITLE
[FlexibleHeader] Migrate internal clients to the new color themer APIs

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4010]
As an internal MDC-iOS client, I want my usage of to-be-deprecated APIs to be migrated to the new APIs in an automatic fashion.

---

Definition of done:

- Internal automated cleanup changes have been issued that migrate clients from the old MDCFlexibleHeaderColorThemer APIs to the new ones introduced in #156522677.

**Comment by ianegordon** [comment]
Closing as an internal issue.
If you would like to tracking this externally, please open an internal bug and mirror it to GitHub.
