### ISSUE TITLE
[FlexibleHeader] Deprecate the old color themer APIs

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4011]
As an MDC-iOS client I want to be informed when I'm using deprecated APIs.

---

Definition of done:

- MDCFlexibleHeaderColorThemer's `applyColorScheme:toFlexibleHeaderView:` and `applyColorScheme:toMDCFlexibleHeaderController:` are marked deprecated.
- The deprecation notice encourages use of the new MDCColorScheming APIs introduced in #156522677.

---
#### Internal data
- Associated internal bug: [b/117178387](http://b/117178387)

**Comment by material-mirror** [comment]
The internal issue [b/117178387](http://b/117178387) is now closed. This issue is being closed as a result.
