### ISSUE TITLE
[FlexibleHeader] Delete the old color themer APIs

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4012]
Definition of done:

- MDCFlexibleHeaderColorThemer's `applyColorScheme:toFlexibleHeaderView:` and `applyColorScheme:toMDCFlexibleHeaderController:` have been deleted.

---
#### Internal data
- Associated internal bug: [b/117179118](http://b/117179118)

**Comment by material-mirror** [comment]
The internal issue [b/117179118](http://b/117179118) is now closed. This issue is being closed as a result.
