### ISSUE TITLE
Deprecate MDCTypography

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4013]
As an MDC-iOS third party developer, I want to know that MDCTypography will soon be deleted.

---

Definition of done:

- MDCTypography is marked as deprecated and its API docs describes a replacement API.

---
#### Internal data
- Associated internal bug: [b/117178112](http://b/117178112)
- Blocked by: https://github.com/material-components/material-components-ios/issues/3952
- Blocked by: https://github.com/material-components/material-components-ios/issues/3963

**Comment by material-mirror** [comment]
The internal issue [b/117178112](http://b/117178112) is now closed. This issue is being closed as a result.
