### ISSUE TITLE
Delete MDCTypography

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4014]
Definition of done:

- The MDCTypography API is removed from our codebase.

---
#### Internal data
- Associated internal bug: [b/117178316](http://b/117178316)
- Blocked by: https://github.com/material-components/material-components-ios/issues/4013

**Comment by material-mirror** [comment]
The internal issue [b/117178316](http://b/117178316) is now closed. This issue is being closed as a result.
