### ISSUE TITLE
[BottomSheetPresentationController] Implement as a vanilla UIPresentationController

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4022]
Currently our BottomSheet component asks that developers embed their custom view controller in a bottom sheet controller, then present the bottom sheet controller.  If possible we should expose this functionality via a standard UIPresentationController.

---
#### Internal data
- Associated internal bug: [b/117178315](http://b/117178315)

**Comment by material-mirror** [comment]
The internal issue [b/117178315](http://b/117178315) is now closed. This issue is being closed as a result.
