### ISSUE TITLE
[Catalog] Dragons app should automatically present / dismiss all view controllers automatically

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4024]
As we already create a list of presentable view controllers.  If we have a test target that automatically presented, then dismissed, all view controllers we will catch crashing bugs without having to manually navigate through the entire app.

**Comment by ianegordon** [comment]
Initially present and dismiss all example view controllers supporting CBC.

Future:
Ideally present, screenshot, rotate, screenshot, rotate, screenshot, dismiss
The first and third screen shot should be the same.
The first and second screen shot should be tested / compared as part of our PR checks.

**Comment by jverkoey** [comment]
This is done internally.

**Comment by romoore** [comment]
Can you please provide the internal link? I don't know how to do this and it would be helpful for our UI testing.
