### ISSUE TITLE
Replace Plus "+" with an Icon on FAB

### ISSUE THREAD

**Issue by Tobistor** [material-components/material-components-ios#4025]
Please how do I replaces the plus "+" with an Icon or image. Thanks.

**Comment by romoore** [comment]
Hi @Tobistor.  MDCFloatingButton is a UIButton subclass, so you can use [`setImage:forState:`](https://developer.apple.com/documentation/uikit/uibutton/1623997-setimage?language=objc) to assign an image instead of title text.
