### ISSUE TITLE
Theming docs should be published as their own section of m.io/develop/ios

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4026]
Right now MDC-iOS' theming docs have two problems as surfaced on the m.io site:

1) The 'Theming' group is under Components, but it's better as a top-level group, as Android does.
2) Shapes is orphaned away from the rest of the theming under Documentation. It should be placed in the Theming group.

Changing these will require
1) Updating the embedded metadata to place the docs in the right place in navigation
2) Adding redirects from the old pages to the new locations, or deciding to let the old pages 404.
3) Updating the following short links to point to the new locations:

material.io/go/ios-color-theming
material.io/go/ios-typography
material.io/go/ios-shape

---

This is an internal issue. If you are a Googler, please visit [b/79473306](b/79473306) for more details.

---
#### Internal data
- Associated internal bug: [b/79473306](http://b/79473306)

**Comment by material-mirror** [comment]
The internal issue [b/79473306](http://b/79473306) is now closed. This issue is being closed as a result.
