### ISSUE TITLE
[FeatureHighlight] Draws incorrectly if presented with animated = NO

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4032]
From the internal issue:

> I am using an MDCFeatureHightlightViewController in my app.
> 
> I set it up according to the provided code. When I set animated = NO in |presentViewController:animated:completion:| the view's masking layers do not draw correctly. 
> 
> I also observe this behavior happening when the view is popped from force touch, though I do not have as good of a repro case. I also note that after this happens, a screen rotation will trigger the view to redraw correctly - presumably because it's an animated change.
> 
> ## Reproduction steps
> 
> Use the following code, taken from https://github.com/material-components/material-components-ios/tree/develop/components/FeatureHighlight:
> `
> MDCFeatureHighlightViewController *highlightController =
> [[MDCFeatureHighlightViewController alloc] initWithHighlightedView:viewToHighlight
>                                                         completion:completion];
> highlightController.titleText = @"Just how you want it";
> highlightController.bodyText = @"Tap the menu button to switch accounts, change settings & more.";
> highlightController.outerHighlightColor =
>     [[UIColor blueColor] colorWithAlphaComponent:kMDCFeatureHighlightOuterHighlightAlpha];
> 
> // NOTE: animated is set to NO.
> [self presentViewController:highlightController animated:NO completion:nil];
> `
> 
> **Expected result:** What do you want to happen when the steps are followed?
> 
> I see the screenshot with the red promo on it.
> 
> **Actual Result:** What actually happens when the steps are followed?
> 
> I see the latter screenshot. The text is drawn but there is no background color. There is a dull pulsing black circle placed over the highlighted view.
> 
> ## Operating system and device model
> 
> iOS Simulator, iOS 11.2

---

This is an internal issue. If you are a Googler, please visit [b/79092088](http://b/79092088) for more details.

---
#### Internal data
- Associated internal bug: [b/79092088](http://b/79092088)

**Comment by material-mirror** [comment]
The internal issue [b/79092088](http://b/79092088) is now closed. This issue is being closed as a result.
