### ISSUE TITLE
[BottomNavigation] MDCBottomNavigationBar should not clip into iPhone X safe area

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4033]
From the internal bug:

> When used on the iPhone X, the ink effect for MDCBottomNavigationBar is currently clipped at the lower iPhone X safe area. UX would like the ink to be able to flow into the safe area (matching our current behavior).

Screenshot available in the internal report.

---

This is an internal issue. If you are a Googler, please visit [b/78889627](http://b/78889627) for more details.

---
#### Internal data
- Associated internal bug: [b/78889627](http://b/78889627)

**Comment by romoore** [comment]
This was fixed in https://github.com/material-components/material-components-ios/pull/6586
