### ISSUE TITLE
[BottomNavigation] Evaluate a11y support for vision affordance

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4035]
The primary indication of the selected tab is *only* color which may not meet accessibility standards. We need to provide a non-color cue for the selected tab.

---

This is an internal issue. If you are a Googler, please visit [b/78662144](http://b/78662144) for more details.

**Comment by romoore** [comment]
Which internal bug is this for?

**Comment by jverkoey** [comment]
b/78662144 is the parent bug.
