### ISSUE TITLE
[BottomNavigation] Icon and title are too close together

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4042]
@brianjmoore:

> The bottom nav bar seems to have too little space between the icon and title text for each tab.

It is unclear if this is actually the case. This issue is presently blocked on design feedback.

---

This is an internal issue. If you are a Googler, please visit [b/77790371](http://b/77790371) for more details.

**Comment by jverkoey** [comment]
@codeman7 @wenyuzhang666 What are the oustanding blockers for this issue?

**Comment by wenyuzhang666** [comment]
Chatted with Cody offline, and seems he had pushed a cool fix for it.

**Comment by codeman7** [comment]
cl/214489564

**Comment by codeman7** [comment]
Waiting until cl/214489564 lands

**Comment by jverkoey** [comment]
The internal issue is now closed, closing this issue.
