### ISSUE TITLE
[Tabs] Tabs at the bottom of the app rely on color to show which tab is selected

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4047]
From the internal bug:

> Tabs at the bottom of the app rely on color to show which tab is selected. There is a header at the topic of the page, but it for a colorblinded user the selected tile won't be very obvious. Having it colored in or have a line under it denoting it is selected is a better way to indicate it is selected. You can also consider removing the text labels from the non-selected tabs as a way to indicate selection state.

---

This is an internal issue. If you are a Googler, please visit [b/77288367](http://b/77288367) for more details.

---
#### Internal data
- Associated internal bug: [b/77288367](http://b/77288367)

**Comment by romoore** [comment]
Misfiled to our project.
