### ISSUE TITLE
[Typography] Concerned about small font size for: body 2, body 1, caption and buttons

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4052]
From the internal report:

> ## Overview
> 
>  - concerned about small font size for: body 2, body 1, caption and buttons. can we please make these as large as possible?
> 
> ## Reproduction steps
> Open material 46.1.0
> navigate to typography and fonts
> notice small font size on  body 2, body 1, caption, and button fonts
> 
> **Expected result:** comfortably able to read everything
> **Actual Result:** font is quite small.

---

This is an internal issue. If you are a Googler, please visit [b/75979125](http://b/75979125) for more details.

---
#### Internal data
- Associated internal bug: [b/75979125](http://b/75979125)

**Comment by jverkoey** [comment]
@ianegordon If you're still working on this please re-assign.

**Comment by material-mirror** [comment]
The internal issue [b/75979125](http://b/75979125) is now closed. This issue is being closed as a result.
