### ISSUE TITLE
[Cards] Should implement Motion spec

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4055]
> I know most of this is out of initial scope, but just wanted to create a bug to track implementing card motion that's in spec.

---

This is an internal issue. If you are a Googler, please visit [b/73963748](http://b/73963748) for more details.

---
#### Internal data
- Associated internal bug: [b/73963748](http://b/73963748)

**Comment by material-mirror** [comment]
The internal issue [b/73963748](http://b/73963748) is now closed. This issue is being closed as a result.
