### ISSUE TITLE
[Tabs] Indicator animation duration too slow

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4060]
This is an internal issue. If you are a Googler, please visit [b/73832804](http://b/73832804) for more details.

---
#### Internal data
- Associated internal bug: [b/73832804](http://b/73832804)

**Comment by jverkoey** [comment]
@ianegordon please reassign yourself if you're still working on this.

**Comment by material-mirror** [comment]
The internal issue [b/73832804](http://b/73832804) is now closed. This issue is being closed as a result.
