### ISSUE TITLE
[TextFields] Textfield label durations too long

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4061]
From the internal bug:

> The animation on the textfield label position feels slow, should be 150ms.

---

This is an internal issue. If you are a Googler, please visit [b/73833287](http://b/73833287) for more details.

---
#### Internal data
- Associated internal bug: [b/73833287](http://b/73833287)

**Comment by jverkoey** [comment]
@ianegordon please reassign yourself if you're still working on this.

**Comment by material-mirror** [comment]
The internal issue [b/73833287](http://b/73833287) is now closed. This issue is being closed as a result.
