### ISSUE TITLE
MaskedTransition transformations not built

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4063]
This is an internal issue. If you are a Googler, please visit [b/73832791](http://b/73832791) for more details.

---
#### Internal data
- Associated internal bug: [b/73832791](http://b/73832791)

**Comment by jverkoey** [comment]
This is fixed.

**Comment by material-mirror** [comment]
The internal issue [b/73832791](http://b/73832791) is now closed. This issue is being closed as a result.
