### ISSUE TITLE
[BottomNavigation] Motion specs off

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4079]
From the internal report:

> - It's hard to tell but it looks like Bottom nav icons are using Linear easing when it should be Standard. It could be that the duration is off. 
> 
> - Icon labels that fade in should be pinned to the icon.

---

This is an internal issue. If you are a Googler, please visit [b/72321822](http://b/72321822) for more details.

---
#### Internal data
- Associated internal bug: [b/72321822](http://b/72321822)

**Comment by material-mirror** [comment]
The internal issue [b/72321822](http://b/72321822) is now closed. This issue is being closed as a result.
