### ISSUE TITLE
[BottomAppBar] FAB enter and exit motion

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4080]
From the internal bug:

> It appears that the cut in the app bar and the FAB use slightly different easing and/or durations. It's most noticeable on the FAB exit where the motion on the cut healing looks detached from the FAB exiting.

---

This is an internal issue. If you are a Googler, please visit [b/72321720](http://b/72321720) for more details.

---
#### Internal data
- Associated internal bug: [b/72321720](http://b/72321720)

**Comment by jverkoey** [comment]
Unassigning due to inactivity. Please re-assign yourself if you are working on this.

**Comment by material-mirror** [comment]
The internal issue [b/72321720](http://b/72321720) is now closed. This issue is being closed as a result.
