### ISSUE TITLE
[BottomAppBar] Leading, Center and Trailing motion specs

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4081]
From the internal bug:

> Looking at the FAB transition in the catalogue app:
> 
> - The sliding transition on the FAB appears to use linear easing (should be standard)
>
> - Icons in the bar jump cut in and out instead of fading.

---

This is an internal issue. If you are a Googler, please visit [b/72321753](http://b/72321753) for more details.

---
#### Internal data
- Associated internal bug: [b/72321753](http://b/72321753)

**Comment by material-mirror** [comment]
The internal issue [b/72321753](http://b/72321753) is now closed. This issue is being closed as a result.
