### ISSUE TITLE
[FlexibleHeader] ContentOffset.y with a MDCFlexibleHeaderView is not properly set if it rotates underneath a pushed view.

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4085]
This is an internal issue. If you are a Googler, please visit [b/71844622](http://b/71844622) for more details.

---
#### Internal data
- Associated internal bug: [b/71844622](http://b/71844622)

**Comment by material-mirror** [comment]
The internal issue [b/71844622](http://b/71844622) is now closed. This issue is being closed as a result.
