### ISSUE TITLE
[TextFields] MDCTextField has wrong text insets when added as title view to navigation bar

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4090]
From the internal bug:

> When adding a MDCTextField to a navigation bar through 
> self.navigationItem.titleView = textField;
>
> The text fields uses the wrong text insets.
>
> The problem is present both for the placeholder as well as the text.

---

This is an internal issue. If you are a Googler, please visit [b/71571782](http://b/71571782) for more details.

---
#### Internal data
- Associated internal bug: [b/71571782](http://b/71571782)

**Comment by material-mirror** [comment]
The internal issue [b/71571782](http://b/71571782) is now closed. This issue is being closed as a result.
