### ISSUE TITLE
Status bar incorrectly remains on-screen in some setups

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4094]
From the bug filer:

> Repro steps:
>
> 1. Create a UIViewController using MDCFlexibleHeaderShiftBehaviorEnabledWithStatusBar, give it enough content to scroll the header/status bar off screen, scroll down so the appbar is hidden.
> 2. Use UINavigationController to push a similarly configured UIViewController using on top.
> 3. Navigate back to the original screen, observe status bar remains visible when appbar is hidden.

There are screenshots on the internal bug.

---

This is an internal issue. If you are a Googler, please visit [b/70239038](http://b/70239038) for more details.

**Comment by andrewoverton** [comment]
Closing based off the discussion in https://github.com/material-components/material-components-ios/pull/4442 and in the original bug.
