### ISSUE TITLE
[Dialogs] Presented views that are laid out with AutoLayout don't match with the trackingView

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4095]
This is an internal issue. If you are a Googler, please visit [b/69808461](http://b/69808461) for more details.

---
#### Internal data
- Associated internal bug: [b/69808461](http://b/69808461)

**Comment by ianegordon** [comment]
The frame of the trackingView should match the presentedView.

**Comment by material-mirror** [comment]
The internal issue [b/69808461](http://b/69808461) is now closed. This issue is being closed as a result.
