### ISSUE TITLE
[Typography] Integrate with UIAccessibilityIsBoldTextEnabled

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4096]
This is an internal issue. If you are a Googler, please visit [b/69049139](http://b/69049139) for more details.

---
#### Internal data
- Associated internal bug: [b/69049139](http://b/69049139)

**Comment by material-mirror** [comment]
The internal issue [b/69049139](http://b/69049139) is now closed. This issue is being closed as a result.
