### ISSUE TITLE
Catalog causes SpringBoard crash on launch on iOS 11 iPod Touch

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4102]
From the bug author:

> Description:
> 
> When launching the latest MDC Catalog on my iPod Touch (6th gen) running iOS 11,  I observing the following behavior:  after tapping the icon in SpringBoard, it remains selected/active for a LONG time, on the order of a minute or more.  Then the app launches to a plain white screen, which remains active for a LONG time on the order of a minute or more, with an network activity indicator in the status bar.  Eventually, the screen goes black with a white spinner in the middle, and console log in XCode looks like a SpringBoard crash and relaunch
> 
> Steps to reproduce:
> 
> 1.  Launch MDC Catalog
> 
> Expected results:
> 
> The app launches
> 
> Actual results:
> 
> It crashes SpringBoard, after a long time.
> 
> Device:  iPod Touch 6th gen (Model MKH22LL/A)
> iOS Version: 11.0 (15A372)
> MDC Catalog version: 35.2.0 (updated 2017-09-27)
> 
> Additional information:  MDC Catalog launches and behaves normally on my iPhone 7 running iOS > 10.3.3.

---

This is an internal issue. If you are a Googler, please visit [b/67098589](http://b/67098589) for more details.

---
#### Internal data
- Associated internal bug: [b/67098589](http://b/67098589)

**Comment by material-mirror** [comment]
The internal issue [b/67098589](http://b/67098589) is now closed. This issue is being closed as a result.
