### ISSUE TITLE
[AppBar] Changing the content insets leaves the header view shadow visible in some cases

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4103]
From the internal bug:

> Changing the content insets is causing this issue if contentSize of the collection is smaller than the bounds of the collection view. The shadow of the header ends up visible when it shouldn't probably because the contentOffset ends up being "restored" to the wrong place.
> 
> My case is the classic add / remove bottom insets when the keyboard is shown, but after the hide, the contentSize will end up being smaller than the view so nothing should be allowed to scroll and the contentOffset should be 0. I believe MDC is trying to keep it where it was when the collection view could scroll, with the keyboard insets in place.

---

This is an internal issue. If you are a Googler, please visit [b/66403945](http://b/66403945) for more details.

---
#### Internal data
- Associated internal bug: [b/66403945](http://b/66403945)

**Comment by material-mirror** [comment]
The internal issue [b/66403945](http://b/66403945) is now closed. This issue is being closed as a result.
