### ISSUE TITLE
[Ink] MDCInkView: On selection animation (ripple)

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4106]
From the internal bug:

> MDCInkView animation on selection seems unexpected.
> For bounded style: The ripple animation being shown might be too fast and undefined? I've compared it to the same behavior in Android and the one exampled in the Material Spec website 
> For unbounded style: There is no ripple animation at all. It just fades out.

---

This is an internal issue. If you are a Googler, please visit [b/65091658](http://b/65091658) for more details.

---
#### Internal data
- Associated internal bug: [b/65091658](http://b/65091658)

**Comment by material-mirror** [comment]
The internal issue [b/65091658](http://b/65091658) is now closed. This issue is being closed as a result.
