### ISSUE TITLE
[ShadowLayer] MDCShadowLayer doesn't animate properly

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4108]
This is an internal issue. If you are a Googler, please visit [b/64615049](http://b/64615049) for more details.

---
#### Internal data
- Associated internal bug: [b/64615049](http://b/64615049)

**Comment by ianegordon** [comment]
Duplicate of #1287

**Comment by material-mirror** [comment]
The internal issue [b/64615049](http://b/64615049) is now closed. This issue is being closed as a result.
