### ISSUE TITLE
[TextFields] 2.0 motion

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4109]
From the internal bug:

> Text fields support motion for:
> - error states
> - focus/selection animations (placeholder/helper text)

---

This is an internal issue. If you are a Googler, please visit [b/64002899](http://b/64002899) for more details.

---
#### Internal data
- Associated internal bug: [b/64002899](http://b/64002899)

**Comment by material-mirror** [comment]
The internal issue [b/64002899](http://b/64002899) is now closed. This issue is being closed as a result.
