### ISSUE TITLE
[FlexibleHeader] Header size changes when as trackingScrollView scrolls which messes up layout calculations

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4111]
This is an internal issue. If you are a Googler, please visit [b/62423787](http://b/62423787) for more details.

---
#### Internal data
- Associated internal bug: [b/62423787](http://b/62423787)

**Comment by material-mirror** [comment]
The internal issue [b/62423787](http://b/62423787) is now closed. This issue is being closed as a result.
