### ISSUE TITLE
[ActivityIndicator] Internal issue: b/38210571

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4113]
This is an internal issue. If you are a Googler, please visit [b/38210571](http://b/38210571) for more details.

---
#### Internal data
- Associated internal bug: [b/38210571](http://b/38210571)

**Comment by ianegordon** [comment]
Internal Client:
I created an MDCActivityIndicator, added it as a subview to my UIImageView, and called -startAnimating. This works great, except whenever my image view changes superviews, I noticed the activity indicator would reset (notice the color resets to red and the track resets to the initial position).  In comparison, the standard UIActivityIndicator handles changes to the view hierarchy without resetting the animation. See videos for more detail.

**Comment by ianegordon** [comment]
Our behavior should match UIActivityIndicator.

**Comment by material-mirror** [comment]
The internal issue [b/38210571](http://b/38210571) is now closed. This issue is being closed as a result.
