### ISSUE TITLE
[FlexibleHeader] Fix vertical alignment of scroll views when scrolling horizontally between two tabs

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4117]
This is an internal issue. If you are a Googler, please visit [b/38000471](http://b/38000471) for more details.

---
#### Internal data
- Associated internal bug: [b/38000471](http://b/38000471)

**Comment by jverkoey** [comment]
The internal issue is not yet closed, re-opening this issue. Googler: please check the state of the internal issue and update it accordingly.

**Comment by material-mirror** [comment]
The internal issue [b/38000471](http://b/38000471) is now closed. This issue is being closed as a result.
