### ISSUE TITLE
[Tabs] sizeToFit should not emit warnings if called on a tab bar with 0 items.

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4120]
This is an internal issue. If you are a Googler, please visit [b/36990741](http://b/36990741) for more details.

---
#### Internal data
- Associated internal bug: [b/36990741](http://b/36990741)

**Comment by romoore** [comment]
Why was this closed?

**Comment by material-mirror** [comment]
The internal issue [b/36990741](http://b/36990741) is now closed. This issue is being closed as a result.
