### ISSUE TITLE
[Collections] Setting section headers on a collection view that is also in edit mode currently results in an app crash

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4123]
This is an internal issue. If you are a Googler, please visit [b/34735403](http://b/34735403) for more details.

---
#### Internal data
- Associated internal bug: [b/34735403](http://b/34735403)

**Comment by material-mirror** [comment]
The internal issue [b/34735403](http://b/34735403) is now closed. This issue is being closed as a result.
