### ISSUE TITLE
[Typography] Support Dynamic Type

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4124]
This is an internal issue. If you are a Googler, please visit [b/34123401](http://b/34123401) for more details.

---
#### Internal data
- Associated internal bug: [b/34123401](http://b/34123401)

**Comment by romoore** [comment]
Internal issue is still open.

**Comment by material-mirror** [comment]
The internal issue [b/34123401](http://b/34123401) is now closed. This issue is being closed as a result.
