### ISSUE TITLE
[Ink] Ink Splash Animation

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4128]
This is an internal issue. If you are a Googler, please visit [b/32369947](http://b/32369947) for more details.

---
#### Internal data
- Associated internal bug: [b/32369947](http://b/32369947)

**Comment by romoore** [comment]
The internal issue is not closed.

**Comment by material-mirror** [comment]
The internal issue [b/32369947](http://b/32369947) is now closed. This issue is being closed as a result.
