### ISSUE TITLE
[Collections] AutoScroll not supported by MDCCollectionViewController

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4131]
From the internal bug:

> MDCCollectionViewController don't support scrolling while reordering a cell. Dragging it to the bottom of the screen does not cause the scroll view to scrollDown.

---

This is an internal issue. If you are a Googler, please visit [b/30927767](http://b/30927767) for more details.

---
#### Internal data
- Associated internal bug: [b/30927767](http://b/30927767)

**Comment by material-mirror** [comment]
The internal issue [b/30927767](http://b/30927767) is now closed. This issue is being closed as a result.
