### ISSUE TITLE
 [PageControl] l10n Strings generation

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4136]
Document a way to generate the translated strings.

---

This is an internal issue. If you are a Googler, please visit [b/22799564](http://b/22799564) for more details.

---
#### Internal data
- Associated internal bug: [b/22799564](http://b/22799564)

**Comment by romoore** [comment]
The internal issue is actually to find a GitHub-friendly way to do string translation, but this issue is about documenting the way to do it.  We need to clarify what the work of this issue will be.

**Comment by material-mirror** [comment]
The internal issue [b/22799564](http://b/22799564) is now closed. This issue is being closed as a result.
