### ISSUE TITLE
[Slider] Audit touch targets for the minimum size of 48x48

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4138]
The minimum touch target is supposed to be 48 x 48 dp, but the switch and the slider is smaller than that.

---

This is an internal issue. If you are a Googler, please visit [b/17658115](http://b/17658115) for more details.

---
#### Internal data
- Associated internal bug: [b/17658115](http://b/17658115)

**Comment by material-mirror** [comment]
The internal issue [b/17658115](http://b/17658115) is now closed. This issue is being closed as a result.
