### ISSUE TITLE
UI interaction testing

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#414]
A simple XCUITest runner that taps through all of the demos will help automate release testing.

**Comment by ianegordon** [comment]
Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄

**Comment by jverkoey** [comment]
Note that we now have this internally and as part of our regular release process. Adding this externally would increase our CI turnaround times so we're unlikely to add it to our public CI.
