### ISSUE TITLE
[BottomNavigation] support .largeContentSizeImage property for press-and-hold for accessibility

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4159]
> iOS 11 supports previewing a tab-bar item by pressing-and-holding it to see a preview, then optionally sliding one’s finger across other items.
>
> I *think* we don’t support a large image for this, although to be honest I can’t figure out what to turn on in Settings to try to feature even in Apple’s apps.
>
> See, e.g.,
> https://developer.apple.com/documentation/uikit/uibaritem/2865917-largecontentsizeimage
> https://stackoverflow.com/questions/46437772/how-do-i-support-large-tab-bar-previews-in-ios-11

---

This is an internal issue. If you are a Googler, please visit [b/79568178](http://b/79568178) for more details.

---
#### Internal data
- Associated internal bug: [b/79568178](http://b/79568178)
- Blocked by: https://github.com/material-components/material-components-ios/issues/7118
- Blocked by: https://github.com/material-components/material-components-ios/issues/7119
- Blocked by: https://github.com/material-components/material-components-ios/issues/7121
- Blocked by: https://github.com/material-components/material-components-ios/issues/7122
- Blocked by: https://github.com/material-components/material-components-ios/issues/7123
- Blocked by: https://github.com/material-components/material-components-ios/issues/6975
- Blocked by: https://github.com/material-components/material-components-ios/issues/6770

**Comment by romoore** [comment]
Removing this from the "Achieve Accessibility Level 4" project since although it is a very good idea (the badge text is very small), it's not strictly required for level 4 success.

**Comment by romoore** [comment]
Also see https://useyourloaf.com/blog/xcode-9-vector-images/ for tutorial about how UITabBarController API would work.

**Comment by romoore** [comment]
This is done. The flag needs to be removed.
