### ISSUE TITLE
[BottomNavigation] MDCBottomNavigation should provide view controller containment

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#4160]
### Overview
I would like the MDC Bottom Navigation component to provide a view controller that provides functionality similar to `UITabBarController`.  

---
#### Internal data
- Associated internal bug: [b/120947829](http://b/120947829)

**Comment by ianegordon** [comment]
Implement MDCBottomNavigationController keeps as close as possible to the interface and behavior in UITabBarController.

**Comment by romoore** [comment]
Well, I suppose it doesn't CLOSE this issue until the VC is in "ready".
