### ISSUE TITLE
Add I/O code labs to our CI

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4165]
The work here still needs to be spec'd out.

Open questions:

- How do we handle API-breaking changes?
- How do we stage changes to the codelabs?

---
#### Internal data
- Associated internal bug: [b/117178216](http://b/117178216)

**Comment by ianegordon** [comment]
Where should this code live?
Does it need to be in the main repo to interface with our CI?
How does this work with a possible tutorial repo?  #4179

**Comment by material-mirror** [comment]
The internal issue [b/117178216](http://b/117178216) is now closed. This issue is being closed as a result.
