### ISSUE TITLE
[TextFields] BorderWidth for MDCTextField

### ISSUE THREAD

**Issue by calube** [material-components/material-components-ios#4173]
## Feature Request/Suggestion

Modify border width of MDCTextField. 

## Additional context

I try to set the lineWidth of the borderView, but it doesn't seem to update the border's line width. 

If there is already existing support for this, I apologize.

**Comment by calube** [comment]
I am using the OutlinedTextFields controller, and when the text field becomes active I would like to change the lineWidth of the borderPath to 2.0.

Also, another feature request, if the textColor of the floating label matched the borderColor based off the state of the text field.  Currently, when my outlined text field controller enters error state I am switching it's active color to red so the label's text color will match the textField's borderColor.

I can achieve this by updating the active color to red, then switching it back to green and that will update the label's text color.  

Thank you for your consideration :)

**Comment by mohammadcazig** [comment]
@calube That is the current behavior of OutlinedTextFields. It will automatically set the lineWidth to 2.0 while editing. you can find this in `updateBorder` implementation in `MDCTextInputControllerOutlined`.

I am not sure what the exact behavior on your second feature request is. Could you create another issue with a bit more context. Thanks :)

**Comment by calube** [comment]
Oh nice!! Sorry I missed that on the lineWidth :) 

And thank you so much for your feedback 🙏

**Comment by mohammadcazig** [comment]
No problem! glad I could help.

**Comment by meanreaksmey** [comment]
@mohammadcazig  Can I set width border in MDCTextInputControllerOutlined ?

**Comment by itsprabin** [comment]
I am trying same, trying to change the border width and make corners more rounded for MDCTextInputControllerOutlined, but not being able to do so. Any help?

**Comment by itsprabin** [comment]
> @calube That is the current behavior of OutlinedTextFields. It will automatically set the lineWidth to 2.0 while editing. you can find this in `updateBorder` implementation in `MDCTextInputControllerOutlined`.
> 
> I am not sure what the exact behavior on your second feature request is. Could you create another issue with a bit more context.
> I will add some info here that might be helpful:
> we provide `errorColor` for error state and also to customize floating placeholder color we provide two properties:
> `floatingPlaceholderActiveColor`
> `floatingPlaceholderNormalColor`

Can we change the border width and rounded corners?

**Comment by itsprabin** [comment]
> @mohammadcazig Can I set width border in MDCTextInputControllerOutlined ?
> because I want set width size only 1.0

Have you been able to do so?

**Comment by romoore** [comment]
@itsprabin We don't currently expose customization of those properties because these controllers are for the Material Text Fields styles. If you want a custom border path or line width, you will probably need to either subclass an existing controller or write your own.

The border path grows in width intentionally to aid in making the changed state (editing/focused) more obvious to users who might not see the change in color.
