### ISSUE TITLE
[Catalog] "Dragons" target splits components into "Dragons" and "Catalog" without clear reason

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#4176]
The "Dragons" target in the Catalog app seems to randomly partition the components between "Dragons" and "Catalog". It's not clear why they're split and it makes it hard to find a component by scrolling since there are 2 independently-sorted lists.

Most importantly, the "Catalog" section excludes many components shown in the Catalog target.

## Reproduction steps
1. Launch the "Dragons" target
1. Look at the main screen

## Expected behavior
All components are listed in the same section of the table

## Actual behavior
Components seem to be randomly assigned to different sections. The assignment changes across launches of the app.

![dragons-2](https://user-images.githubusercontent.com/1753199/40139291-6aa67c80-591d-11e8-9798-3c1ca8574074.png)  ![dragons-1](https://user-images.githubusercontent.com/1753199/40139292-6ab2c148-591d-11e8-8a71-996760999b03.png)

## Platform (please complete the following information)
iPhone 5s/iOS 9.3 (Simulator)

---
#### Internal data
- Associated internal bug: [b/117177635](http://b/117177635)

**Comment by ianegordon** [comment]
Please flatten Dragons and examples to a single section.
Consider adding a last 3 recently opened examples section as section 0.

**Comment by material-mirror** [comment]
The internal issue [b/117177635](http://b/117177635) is now closed. This issue is being closed as a result.
