### ISSUE TITLE
[TextFields] attributedPlaceholder with NSTextAttachment doesn't work

### ISSUE THREAD

**Issue by osrl** [material-components/material-components-ios#4177]
## Reproduction steps

1. Add a MDCTextField with MDCTextInputControllerUnderline
2. Add attributedPlaceholder like below:
```
        let placeholderAttachment = NSTextAttachment()
        placeholderAttachment.image = UIImage(named: "placeholder_image")
        placeholderAttachment.bounds = CGRect(x: 0, y: -1, width: placeholderAttachment.image!.size.width, height: placeholderAttachment.image!.size.height)
        
        let attributes = [NSAttributedStringKey.foregroundColor : .red]
        let placeholderImage = NSAttributedString(attachment: placeholderAttachment)
        
        let phonePlaceholderString = NSMutableAttributedString(string: "Telefon Numaranız", attributes: attributes)
        phonePlaceholderString.insert(placeholderImage, at: 0)
        self.phoneNumberTextField.attributedPlaceholder = phonePlaceholderString
```

## Expected behavior

Placeholder should have icon on the left. Like below:
![screen shot 2018-05-17 at 16 09 20](https://user-images.githubusercontent.com/781453/40179374-d95dea8a-59ec-11e8-9b6f-a35125b27d80.png)

## Actual behavior

Doesn't have the icon:
![screen shot 2018-05-17 at 16 11 29](https://user-images.githubusercontent.com/781453/40179437-fd5001e4-59ec-11e8-898a-cdd8b20613f4.png)

## Platform (please complete the following information)

 - Device: iPhone8 Plus Simulator
 - OS: iOS11.2

## Additional context

Expected behavior can be achieved with `self.phoneNumberTextField.placeholderLabel.attributedText = phonePlaceholderString`

---
#### Internal data
- Associated internal bug: [b/117178111](http://b/117178111)

**Comment by romoore** [comment]
We're not actively working on improving support for Attributed Strings. I do think that this is a reasonable request, but I'm not able to work on it at the moment.

**Comment by osrl** [comment]
Expected behavior can be achieved somehow. Just don't remove it please :)

**Comment by willlarche** [comment]
#4282 improved one edge case for Attributed Strings. Feel free to submit PRs of your own if you make any improvements.

**Comment by material-mirror** [comment]
The internal issue [b/117178111](http://b/117178111) is now closed. This issue is being closed as a result.
