### ISSUE TITLE
[Documentation] Turn codelabs into a tutorial

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#4179]
Consider turning Google I/O 2018 iOS codelabs 101 - 104 into a tutorial.
(Or referencing the codelabs from our docs)

---
#### Internal data
- Associated internal bug: [b/117178386](http://b/117178386)

**Comment by ianegordon** [comment]
Does this make sense?
Should we just point people at the existing codelabs site?
If we do build this, we will need to standup another repo to house the code.
We will likely need an editor to take a pass or two.

**Comment by ianegordon** [comment]
What is the intended deliverable?

**Comment by material-mirror** [comment]
The internal issue [b/117178386](http://b/117178386) is now closed. This issue is being closed as a result.
