### ISSUE TITLE
MDCFlexibleHeaderViewController maximumHeight property counterintuitive

### ISSUE THREAD

**Issue by jpsachse** [material-components/material-components-ios#418]
The `maximumHeight` property of `MDCFlexibleHeaderViewController` seems to work completely counterintuitive. When setting the `maximumHeight` to 0, the header view is actually still very much visible (but no longer expanding under the statusbar, but instead floating below it (see screenshot below). 
Additionally, the header gets a shadow applied to it. When setting the `maximumHeight` to a value such as a third of the total screen space, the header takes much more space. It seems, as if the headerView takes `maximumHeight` + its default height, which is not documented. Instead, `MDCFlexibleHeaderView.h` states that it is 

```
The maximum height that this header can expand to.

If you change the value of this property and the minimumHeight of the receiver is above the new
maximumHeight, minimumHeight will be adjusted to match the new maximumHeight.
```

<img width="432" alt="screen shot 2016-04-21 at 11 15 54 am" src="https://cloud.githubusercontent.com/assets/8794550/14719645/42201654-07b2-11e6-83fb-91e675df2459.png">

---
#### Internal data
- Associated internal bug: [b/117179683](http://b/117179683)

**Comment by material-mirror** [comment]
The internal issue [b/117179683](http://b/117179683) is now closed. This issue is being closed as a result.
