### ISSUE TITLE
[FlexibleHeader] Status bar shifting results in duplicated status bar

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4183]
When the Flexible Header shifts the status bar off-screen, the status bar isn't being hidden resulting in two status bars appearing. This is because the status bar shifter takes a screenshot of the status bar in order to shift it off-screen. The status bar shifter depends on the status bar being hidden once the shifting starts happening.

## Reproduction steps

1. Open Dragons
2. Open the flexible header configurator example.
3. Enable status bar shifting.
4. Scroll the header until it shifts off screen.

## Expected behavior

The status bar shifts off-screen and there isn't a "ghost" status bar behind it.

## Actual behavior

![after](https://user-images.githubusercontent.com/45670/40084112-11c69906-5864-11e8-946b-b7957ace1a83.gif)

## Platform (please complete the following information)

 - Device: iPhoneX
 - OS: 11.4

**Comment by andrewoverton** [comment]
When `UIViewControllerBasedStatusBarAppearance` is set to `true` in the Info.plist file it's not an issue. Is there a reason it's set to `false`? I think when it's set to false you need to actively hide the status bar, as opposed to just making preferences about its appearance visible by overriding `UIViewController` methods like `-preferredStatusBarStyle` and whatnot

**Comment by jverkoey** [comment]
This is resolved in Dragons now that we're enabling UIViewControllerBasedStatusBarAppearance.
