### ISSUE TITLE
[FeatureHighlight] displaced on screen rotation

### ISSUE THREAD

**Issue by mohammadcazig** [material-components/material-components-ios#4185]
After presenting feature highlight rotate the device to landscape and notice that from time to time feature highlight will be placed in the wrong position.

---

This is an internal issue. If you are a Googler, please visit [b/79933393](http://b/79933393) for more details.

**Comment by ianegordon** [comment]
Internal bug:
b/79933393

**Comment by mohammadcazig** [comment]
Additional Context, if the presenting VC has implemented `viewWillTransitionToSize:withTransitionCoordinator` as well and updates the highlighted view frame in there, there is a possibility of race condition which causes a displaced featurehighlight.
