### ISSUE TITLE
[Textfield] Floating Placeholder text changes size when you type in the 2nd word into the text field

### ISSUE THREAD

**Issue by git-tyl** [material-components/material-components-ios#4189]
In a controller make a MDCTextfield a wrap a MDCTextInputControllerFilled controller on it

let textField:BITextField = BITextField()
MDCTextInputControllerFilled(textInput: textField)

In the text field type 1 letter in, the floating placeholder text will get smaller and go on top

When you type in a 2nd letter in, the floating placeholder text will get smaller again.

Expected behavior: The floating placeholder text should remain the same size and not change

---
#### Internal data
- Associated internal bug: [b/117178829](http://b/117178829)

**Comment by git-tyl** [comment]
Hi could I know if this will be fixed by the next version?

**Comment by yarneo** [comment]
The PR for this fix was reverted in the latest release, am reopening the issue for further tracking

**Comment by willlarche** [comment]
The solution to this may come in pieces. Bear with us.

**Comment by romoore** [comment]
This is not closed by #4334, GitHub was too eager.

**Comment by algrid** [comment]
I also have a problem like this one: https://github.com/material-components/material-components-ios/issues/4471

The problem only occurs when I set `textInputFont` for my `MDCTextInputControllerUnderline`. With default font everything is ok.

**Comment by hazam** [comment]
I can add that the problem happens when you set two **different** Fonts size on textInputFont and inlinePlaceholderFont (well it probably happens always but you notice only when fonts are different).

**Comment by hazam** [comment]
Root issue is in `MDCTextInputCommonFundament.m` 

```
- (void)didSetFont {
  UIFont *font = self.textInput.font;
  //following line causes looping interaction with the font setup done by MDCTextInputControllerUnderline
  self.placeholderLabel.font = font;
  [self updatePlaceholderPosition];
}
```

**Comment by hazam** [comment]
https://github.com/material-components/material-components-ios/pull/5810

**Comment by hazam** [comment]
Nope. Had to split the PR and don't have time right now.

**Comment by material-mirror** [comment]
The internal issue [b/117178829](http://b/117178829) is now closed. This issue is being closed as a result.
