### ISSUE TITLE
MDCFeatureHighlightViewController displaced on screen rotation

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4208]
> Ran into an issue where the feature highlight was getting displaced on screen rotation, because the frame of the highlightedView was not updated for landscape by the time MDCFeatureHighlightViewController needed it. This happens a disproportionally small amount of times, so it leads me to think that there's a race condition going on somewhere in our code. Has anyone seen behavior like this before? Any ideas on what might be causing this? Any help is much appreciated.

---

This is an internal issue. If you are a Googler, please visit [b/79933393](http://b/79933393) for more details.

**Comment by ianegordon** [comment]
Dupe: #4185
