### ISSUE TITLE
Each component README.md needs a "when to and not to use" section

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#424]
All of our components have a general set of "best practices" for when to use them and, importantly, when not to use them. We need to ensure that we clearly communicate this in each component's documentation.

An important aspect of this documentation is to explain when a simple UIKit implementation is preferred over using one of our components.
## Collections
- Explain the features.
- How to use a UICollectionView to get Material effects including: ink, layout.
## Flexible Header
- Shift behavior best practices.
- Header content importance best practices.
## Ink
- How to use Ink with UIButton.
## Buttons
- Floating action button best practices.
- When to use the different types of button.
## Typography
- Using the system font.
- When to use Roboto.

**Comment by ianegordon** [comment]
I expect this would be best handled in our Material.io spec / guidance where the context of the component is apparent.
Opened more than two years ago.
Please re-open if you feel strongly.
