### ISSUE TITLE
Internal bug: b/80076887

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4251]
## Definition of done

- [ ] We've set up an internal tracker for GitHub bugs.

---

This is an internal issue. If you are a Googler, please visit [b/80076887](http://b/80076887) for more details.

---
#### Internal data
- Associated internal bug: [b/80076887](http://b/80076887)

**Comment by jverkoey** [comment]
This is done. We now mirror bugs out to GitHub.

**Comment by jverkoey** [comment]
The internal issue is not yet closed, re-opening this issue. Googler: please check the state of the internal issue and update it accordingly.

**Comment by material-mirror** [comment]
The internal issue [b/80076887](http://b/80076887) is now closed. This issue is being closed as a result.
