### ISSUE TITLE
[FeatureHighlight] Create a dragon example for rotation issue.

### ISSUE THREAD

**Issue by mohammadcazig** [material-components/material-components-ios#4260]
When presenting a feature highlight on MDCAppBar barButtonItem, featureHighlight sometimes will be placed at the wrong position when device rotates and also the snapshot of displayed view becomes blank.
Please create a dragon example to demonstrate this use case.

More details b/79933393

---
#### Internal data
- Associated internal bug: [b/117179018](http://b/117179018)

**Comment by material-mirror** [comment]
The internal issue [b/117179018](http://b/117179018) is now closed. This issue is being closed as a result.
