### ISSUE TITLE
[Cards] Add accessibility labels to MDCCard and MDCCardCollectionCell

### ISSUE THREAD

**Issue by yarneo** [material-components/material-components-ios#4261]
We need to add accessibility support with labeling to our Card classes.

Currently the Cards component does not support accessibility and it should. We do not have any accessibility labels set up, and also we need to better approach how the card is presented in voice over as it is on its own tappable but it can have contents that are tappable, so we need to be able to have all items announced with VO.

## Definition of done

- [ ] It is possible to set accessibility labels on an MDCCard and MDCCardCollectionCell.
- [ ] There are written guidelines in [components/Cards/docs](https://github.com/material-components/material-components-ios/tree/develop/components/Cards/docs) on how to add accessibility to the content added inside of a card as that is user-configured.

**Comment by jverkoey** [comment]
Removed the bug label because this is more of a documentation request.

**Comment by jverkoey** [comment]
If there is a bug that this issue is describing though, please clarify here and we can re-label.

**Comment by yarneo** [comment]
clarified.

**Comment by jverkoey** [comment]
Awesome, thank you!

**Comment by yarneo** [comment]
Looks like this has been clarified, documented, and found proper a11y solutions for: https://github.com/material-components/material-components-ios/pull/4454
