### ISSUE TITLE
[FeatureHighlight] Remove the default autoresizing mask setting from the view

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4262]
In general, UIViewController instances should not set their self.view's autoresizing mask. This is because the view controller lacks the ability to know how and where the view will ultimately be presented. Any assumption it makes can and likely will be wrong, and view controller owners should not depend on any default behavior when laying out their view controller views.

## Definition of done

- [ ] The feature highlight view controller does not set any autoresizing masks on self.view (i.e. self.featureHighlightView).

---
#### Internal data
- Associated internal bug: [b/117178902](http://b/117178902)

**Comment by material-mirror** [comment]
The internal issue [b/117178902](http://b/117178902) is now closed. This issue is being closed as a result.
