### ISSUE TITLE
Add a public shared file showing companies using the Material iOS repo.

### ISSUE THREAD

**Issue by yarneo** [material-components/material-components-ios#4265]
## Feature Request/Suggestion

It would be great to have a better grasp on who is using our open source repository. It would also be great for external users thinking of using our open source to see that it is already well adopted.

We could create a shared Google doc or as another markdown file as part of the repo where companies can add themselves as users (and contributors?) of Material Components iOS! This doc would be linked to from the main Readme file under the section "Proud Material Components iOS users" with some instructions on how to add yourself to the list.

## Definition of done

- [ ] There is a place where anyone can add themselves to a list of people/companies that use Material Components for iOS.
- [ ] Anyone can view the list.

---
#### Internal data
- Associated internal bug: [b/117178385](http://b/117178385)

**Comment by material-mirror** [comment]
The internal issue [b/117178385](http://b/117178385) is now closed. This issue is being closed as a result.
