### ISSUE TITLE
[Dragons] Examples list is blank on launch

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#4267]
The list of examples is blank every time I launch the Dragons app in a simulator. Rotating fixes this problem.  There are no constraint violations or any other messages in the console.

![simulator screen shot - iphone 4s - 2018-05-24 at 14 14 26](https://user-images.githubusercontent.com/1753199/40503982-d50f287e-5f5d-11e8-9b6e-6b3c7def8ad8.png)

## Reproduction steps
1. Launch the Dragons app in an iPhone 4s/iOS 9 simulator in portrait

## Expected behavior
The list of examples is displayed

## Actual behavior
The header with search bar is visible, but not the examples list.

## Platform (please complete the following information)
iPhone 4s/iOS 9.0

## Additional context
Reveal shows the height of the table view is 0 and a bounds Y-origin of -133. It also shows NO subviews (cells) in the table view until after rotation.

**Screenshot of Reveal App displaying the UITableView properties**
![screen shot 2018-05-24 at 2 24 00 pm](https://user-images.githubusercontent.com/1753199/40504074-27a4c4a4-5f5e-11e8-950a-a4df4090dfed.png)

**Screenshot of Reveal App displaying absence of UITableView cells**
![screen shot 2018-05-24 at 2 25 51 pm](https://user-images.githubusercontent.com/1753199/40504148-6a798c9c-5f5e-11e8-86da-774b7b1a46f6.png)

---
#### Internal data
- Associated internal bug: [b/117178828](http://b/117178828)

**Comment by material-mirror** [comment]
The internal issue [b/117178828](http://b/117178828) is now closed. This issue is being closed as a result.
