### ISSUE TITLE
[Collections] FlowLayout causes cells with first responder to disappear

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4273]
From the bug author:

> Our view controller is inheriting from MDCCollectionViewController. When any cell has a text field that is currently the first responder, the cell disappears after scrolling off-screen, then back on again. This only happens when the -[MDCCollectionViewController editor] property has 'editing / isEditing' set to YES.
>
> The source of the issue is the conditional in the -[MDCCollectionViewFlowLayout shouldInvalidateLayoutForBoundsChange:] method that checks if the collection view is editing. If I remove 'self.editor.isEditing' from the conditional, the issue no longer reproduces. It's not clear to me why we're checking the isEditing property here, or why checking it causes the change to the visibility of the cell.

---

This is an internal issue. If you are a Googler, please visit [b/80239721](http://b/80239721) for more details.

**Comment by ianegordon** [comment]
Closing as an internal issue.
If you would like to tracking this externally, please open an internal bug and mirror it to GitHub.

**Comment by jverkoey** [comment]
This internal bug is still open.

**Comment by jverkoey** [comment]
The internal issue is not yet closed, re-opening this issue. Googler: please check the state of the internal issue and update it accordingly.

**Comment by jverkoey** [comment]
The internal issue is now closed, closing this issue.
