### ISSUE TITLE
[BottomSheet] Write an a11y guide explaining how to ensure that sheets can be dismissed in VoiceOver

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4275]
When VoiceOver is enabled, BottomSheets can only be dismissed using the two-finger z-swipe VoiceOver gesture when there are a11y elements in the presented view. We should document this fact in the component's documentation.

## Definition of done

- [ ] There is an accessibility guide in [components/BottomSheet/docs](https://github.com/material-components/material-components-ios/tree/develop/components/BottomSheet/docs) that explains how to ensure that the VoiceOver z-swipe gesture will work as expected.
- [ ] The docs have been regenerated by running `./scripts/generate_readme BottomSheet`.

---
#### Internal data
- Associated internal bug: [b/117178215](http://b/117178215)

**Comment by codeman7** [comment]
I believe we have updated our examples and added support for a11y but I can't find a doc the component.

**Comment by material-mirror** [comment]
The internal issue [b/117178215](http://b/117178215) is now closed. This issue is being closed as a result.
