### ISSUE TITLE
how Should i change the font family and font size in the tabbar (UITabBarItem) title? 

### ISSUE THREAD

**Issue by HariNarayanan777** [material-components/material-components-ios#4276]
## Feature Request/Suggestion

I need to change my title font family to custom font family, which is showing in the title.. please tell.!....

**Comment by HariNarayanan777** [comment]
then is it possible to change the custom fonts.!
?

**Comment by romoore** [comment]
Hi @HariNarayanan777 , I'm guessing that this is for either MDCBottomNavigationBar or MDCTabBar.

For MDCBottomNavigationBar, you can use [`-[MDCBottomNavigationBar itemTitleFont]`](https://github.com/romoore/material-components-ios/blob/develop/components/BottomNavigation/src/MDCBottomNavigationBar.h#L95).
For MDCTabBar, you can use [`-[MDCTabBar unselectedItemTitleFont]`](https://github.com/romoore/material-components-ios/blob/develop/components/Tabs/src/MDCTabBar.h#L119) and [`-[MDCTabBar selectedItemTitleFont]`](https://github.com/romoore/material-components-ios/blob/develop/components/Tabs/src/MDCTabBar.h#L109).

Please feel free to reopen this issue if it doesn't answer your question. Thanks for using MDC-iOS!

**Comment by HariNarayanan777** [comment]
can you please tell in swift language..
i used swift only..

**Comment by romoore** [comment]
Hi Hari, you can use the same properties in Swift and Objective-C: `itemTitleFont`, `selectedItemTitleFont` and `unselectedItemTitleFont`.  They are not named differently in Swift.

**Comment by HariNarayanan777** [comment]
But i cannot get this @romoore 
i used the below code
 

> let tabBar = MDCTabBar.init(frame: CGRect(x: 0, y: 4, width: self.view.frame.size.width, height: 0))

and there is no suggestion from the tabBar.selectedItemTitleFont
its showing `Value of type 'MDCTabBar' has no member 'selectedItemTitleFont'`
 please show me some example for this..

**Comment by romoore** [comment]
I modified the example, `TabBarIconExample.swift` do set the `selectedItemTitleFont` to  a point size 99.

```swift
let tabBar = MDCTabBar()
tabBar.selectedItemTitleFont = UIFont.systemFont(ofSize: 99)
```

![simulator screen shot - iphone 4s - 2018-05-25 at 09 30 54](https://user-images.githubusercontent.com/1753199/40546860-695061f6-5ffe-11e8-992b-672970991c00.png)

**Comment by romoore** [comment]
Just as a double-check, what version of MDC-iOS are you using?  Customized fonts support was added in December, 2017, so if you don't see the property in the header you may have an older version of the library.

**Comment by HariNarayanan777** [comment]
yeah i think its an old modal, may i know how to check the version which i used.?

**Comment by HariNarayanan777** [comment]
Now i am using `MaterialComponents, 54.7.0`

**Comment by romoore** [comment]
@HariNarayanan777 I appreciate your trying to use MDC-iOS, but I think this type of problem is probably best suited for [a StackOverflow question](https://stackoverflow.com/questions/tagged/material-components-ios).

**Comment by HariNarayanan777** [comment]
@romoore thank you so much for you replies 
i just uninstall the pod and then install it again in this would perfect now.. really #super.. 
now i can able to change the custom font family and font size itself.... Thank you..

**Comment by romoore** [comment]
Great! Glad to hear you worked it out. :)
