### ISSUE TITLE
[Chips] Support UIControlContentHorizontalAlignment

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#4277]
## Feature Request/Suggestion

As a UIControl subclass, MDCChipView should make use of `UIControlContentHorizontalAlignment` to allow clients to customize the position of the content within the Chip.

## Additional context
There is currently an undesirable effect when increasing the width of an MDCChipView. It will center the title but leave the imageView/accessoryView on the edges. We have internal clients that would like all of the contents to be centered within the ChipView, with appropriate layout/padding between the subviews.

![chip-sizing-mdcdragon](https://user-images.githubusercontent.com/1753199/40544490-80a5d514-5ff6-11e8-93b6-7b4ef7b8dc4c.png)

Related internal issue: b/80277575

**Comment by jverkoey** [comment]
I've requested some additional clarification on the internal bug.
