### ISSUE TITLE
Write a "How to" pick components to use in your app

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#428]
Big message here is that we want to encourage people to pick components to use, not to use the entire set of components all at once. The emphasis being we may add many many more components in the future, so their app likely does not want to track all of these components.

Some considerations:
- Where to find the list of components.
- Where to try out the components (link to building and installing catalog app)
- Pointing to demo apps and listing the components they use

**Comment by ianegordon** [comment]
Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄
