### ISSUE TITLE
[Continuous Integration] Bazel support for framework-style includes

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#4280]
Owner: iangordon

We recently landed a change in our upstream dependency (MDFI18n) removing #ifdef guards around our test imports.
https://github.com/material-foundation/material-internationalization-ios/pull/38

This will break MDC-iOS if we cut a release.
Work with the bazel team to enable framework-style imports or revert the change.

---
#### Internal data
- Associated internal bug: [b/117178923](http://b/117178923)

**Comment by jverkoey** [comment]
In case you get sniped onto other work @ianegordon, can you document what needs to happen here?

**Comment by material-mirror** [comment]
The internal issue [b/117178923](http://b/117178923) is now closed. This issue is being closed as a result.
