### ISSUE TITLE
[Story] As a designer, I want the Chips in Text Fields aligned with Placeholder or User text so that they look beautiful.

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#4283]
## Description
When adding MDCChipViews to the textView, we need to ensure that the Chip title, placeholder text, and the input text are baseline aligned.   It seems we may need to become the NSLayoutManager's delegate to correctly position the text fragments.

## Acceptance Criteria
1. The text within a Chip is baseline aligned to the placeholder and input text of the Text Field on the same line.
1. There is a way to increase the line height (vertical spacing) of the Text Field and Chips will remain properly aligned.
1. The alignment looks correct for [Latin characters](https://en.wikipedia.org/wiki/Latin_script)
1. The alignment looks correct for [CJK characters](https://en.wikipedia.org/wiki/CJK_characters) (e.g., [Japanese kanji](https://en.wikipedia.org/wiki/Kanji)).
1. The alignment looks correct for an RTL script (e.g., [Arabic script](https://en.wikipedia.org/wiki/Arabic_script)).
1. The alignment looks correct for a non-latin script (e.g., [Tamil script](https://en.wikipedia.org/wiki/Tamil_script))
1. Works for attributedText that does not adjust the baseline offset or perform any other line/paragraph manipulations.
1. The `accessibilityFrame` of each Chip is centered on the Chip.
1. Snapshot tests for each type of script.

## Considered alternatives
**Using lineSpacing**
![textchips-linespacing](https://user-images.githubusercontent.com/1753199/40558819-925ea1a6-6022-11e8-9b52-eed4b8f3b839.png)

**Using minimumLineHeight/maximumLineHeight**
![textchips-lineheight](https://user-images.githubusercontent.com/1753199/40558832-9a443908-6022-11e8-850a-37534b5a59bd.png)

## References
* https://christiantietze.de/posts/2017/07/nstextview-proper-line-height/

---
#### Internal data
- Associated internal bug: [b/117178177](http://b/117178177)

**Comment by material-mirror** [comment]
The internal issue [b/117178177](http://b/117178177) is now closed. This issue is being closed as a result.
