### ISSUE TITLE
[AppBar] Create an example showing a wrapped table view controller 

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4293]
For our accessibility audit, we need an example showing a table view controller that is wrapped. We already have one table view controller example that uses injection.

## Definition of done

- [ ] There is an example that shows a wrapped table view controller.

**Comment by romoore** [comment]
@jverkoey Can you clarify what you mean by "a wrapped view controller" versus "an injected view controller"?

**Comment by jverkoey** [comment]
Wrapping refers to making a view controller be the content view controller of a `MDCAppBarContainerViewController`.

Injecting refers to adding an app bar as a child view controller of another view controller.
