### ISSUE TITLE
[TextFields] Unit Tests: verify content size is invalidated when height/width of a view changes

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#4298]
> Intrinsic content size is not automatically invalidated when the height or width of a view changes. In iOS 10, when the trailing constraint of our text view is greater than -1.76 (no clue why that number), it doesn't have enough information to estimate the width so we can get a good height.
> &mdash; #4297

---
#### Internal data
- Associated internal bug: [b/117178214](http://b/117178214)

**Comment by jerrin15** [comment]
I have an issue of my auto layout width property allowing dynamic width not working when the UITextfield is set to MDCTextfield, any idea how to fix this?

**Comment by willlarche** [comment]
Can u explain some more? And share ur code

**Comment by jerrin15** [comment]
I have set the width of my textfield to be >70, so it will increase as the text length inside increases. But after subclassing the textfield to MDCTextfield, the textfield width doesn't increase as text length increases.

**Comment by willlarche** [comment]
Oh I see. Expanding width isn’t a feature of MDCTextField unfortunately.
Maybe you could just make it the max width.

**Comment by material-mirror** [comment]
The internal issue [b/117178214](http://b/117178214) is now closed. This issue is being closed as a result.
