### ISSUE TITLE
[BottomSheet] Update checklist for BottomSheet

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#4321]
OWNERs should update checklist to fill in missing values.
https://docs.google.com/spreadsheets/d/1H30t5r8rJcXkyG9tNpPSOgVEJ0enxaZlazQJrlfyYSo/edit#gid=0

---
#### Internal data
- Associated internal bug: [b/117177634](http://b/117177634)

**Comment by material-mirror** [comment]
The internal issue [b/117177634](http://b/117177634) is now closed. This issue is being closed as a result.
