### ISSUE TITLE
Move the GitHub squash-and-merge chrome extension out to its own repo

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4326]
The extension can live standalone from our repo and many others will likely find it beneficial.

The repo should/can probably live in material-foundation.

**Comment by romoore** [comment]
+1, Chrome extensions should definitely not live within our iOS repository.

**Comment by jverkoey** [comment]
I've created https://github.com/material-foundation/github-squash-and-merge-pr-descriptions/pull/1
