### ISSUE TITLE
[TextFields] Classes are using out of date text styles

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#4331]
[Code](https://github.com/material-components/material-components-ios/blob/1eee555258996ac8544e4c9ed6f6d5568976a1e3/components/TextFields/src/MDCTextInputControllerBase.m#L586)

`MDCFontTextStyleBody1` etc which is interfering with the typography theme.

---
#### Internal data
- Associated internal bug: [b/117178426](http://b/117178426)

**Comment by willlarche** [comment]
Also in fundament.

**Comment by romoore** [comment]
Closed by #4344

**Comment by willlarche** [comment]
Not closed yet

**Comment by romoore** [comment]
@willlarche Can you clarify what needs to be done? In #4189 it claims that by fixing this (#4331) it would fix that (#4189). Since #4189 is marked fixed, should this not also be fixed?

**Comment by willlarche** [comment]
The text fields component needs to be completely scrubbed of the out of date typography scale (MDCFontTextStyle...) and replaced with the new one from the updated guidelines.

**Comment by material-mirror** [comment]
The internal issue [b/117178426](http://b/117178426) is now closed. This issue is being closed as a result.
