### ISSUE TITLE
[BottomSheet] Inconsistency on whether MDCBottomSheet is presented underneath status bar for iPhone X vs other iPhones

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4333]
From the internal bug report:

> When presenting an MDCBottomSheet and swiping it to take up the full screen, on the iPhone X, the bottom sheet does not go underneath the status bar, whereas on other iPhone versions, it does.
>
> Steps to reproduce:
> 1.  Open the MDCCatalog
> 2.  Go to the Bottom Sheet demo.
> 3.  Present the bottom sheet, and swipe it upwards so that it takes up the entire screen.  
> 4.  On the iPhone X, the bottom sheet does not go underneath the status bar, whereas on other iPhone versions, it does. (See attached screen shots)
> 
> I'm not sure if this is the intended behavior, but I thought it was worth reporting this inconsistency.  It also might make sense to have the same behavior on this for all iPhones, and instead provide an option on whether the bottom sheet should go underneath the status bar or not.

### Screenshots

![simulator screen shot - iphone 8 - 2018-05-29 at 16 31 09](https://user-images.githubusercontent.com/45670/40781731-feb51fec-64aa-11e8-9a6a-1f1a7572fb3a.png)
![simulator screen shot - iphone x - 2018-05-29 at 16 30 56](https://user-images.githubusercontent.com/45670/40781735-ffd228f2-64aa-11e8-8999-bda0a92e7fdb.png)

---

This is an internal issue. If you are a Googler, please visit [b/80431923](http://b/80431923) for more details.

---
#### Internal data
- Associated internal bug: [b/80431923](http://b/80431923)

**Comment by material-mirror** [comment]
The internal issue [b/80431923](http://b/80431923) is now closed. This issue is being closed as a result.
