### ISSUE TITLE
[FlexibleHeader] Content inset is updated incorrectly after rotation

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4334]
From the internal bug report:

> Reported in b/78538466, this bug exists on non-iPhone X devices and when orientation changes, the content inset of the scroll view being tracked by MDCFlexibleHeaderViewController is incorrectly set.
>
>  There is a video attached to the internal bug report.
>
> From portrait to landscape, you can see there's an extra top padding above the options. From landscape back to portrait, the top padding became negative (too small content inset in this case).

---

This is an internal issue. If you are a Googler, please visit [b/80427451](http://b/80427451) for more details.

---
#### Internal data
- Associated internal bug: [b/80427451](http://b/80427451)

**Comment by material-mirror** [comment]
The internal issue [b/80427451](http://b/80427451) is now closed. This issue is being closed as a result.
