### ISSUE TITLE
[AppBar] AppBar does not respect UIBarButtonItem accessibility properties

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#4338]
## Description
The `accessibilityLabel`, `accessibilityValue`, or `accessibilityHint` properties for a UIBarButtonItem created with an image and  assigned to the `viewcontroller.navigationItem.rightBarButtonItem` are not read-out by VoiceOver. Instead only the image file name is read.

## Reproduction steps
1. Modify the AppBarTypicalUseExample so that the "Right"-titled UIBarButtonItem has an image instead.
1. Set the `accessibilityLabel`, `accessibilityValue`, and `accessibilityHint` properties on the bar button item
1. Assign the bar button item to the View Controller's navigationItem.rightBarbuttonItem

## Expected behavior
VoiceOver reads out the accessibility properties.

## Actual behavior
VoiceOver only reads the icon image asset catalog identifier.

## Platform (please complete the following information)
iPhone 5c/iOS 10.3.3

**Comment by jverkoey** [comment]
I can't reproduce this behavior as of 0e792aacf65d2aaea573437b98f308d998514fb1.
