### ISSUE TITLE
[TextFields] MDCTextField does not permit user input

### ISSUE THREAD

**Issue by TriumphT110** [material-components/material-components-ios#4341]
Bug description: When converting a very simple one-screen & one-textfield Xcode Swift App from UITextField to MDCTextField the ability to input data into the text field was lost. 

## Reproduction steps

1. Create a simple Xcode workspace with Pods (containing MaterialComponents installed through Cocoapods) and a new Swift single-view project 
2. Enter Xcode through the Workspace (including the basic Swift project and the Pods)
3. Using Interface Builder in main.storyboard add a single UITextField in the centre of the single view and set size and position constraints
4. Add an outlet from Interface Builder to View Controller (@IBOutlet weak var helloText: UITextField!)
5. Build this basic App (with no errors) and in the Simulator successfully enter text into the UITextField
**Convert the App to MaterialComponents**
6. In Interface Builder, change the Class from UITextField to MDCTextField
7. In ViewController, use Google's MDC-111 lesson as an example to make these changes:
- a) Type 'import MaterialComponents' below 'import UIKit' (no errors)
- b) Change the type of the outlet declaration (@IBOutlet weak var helloText: MDCTextField!)
- c) Declare a new property (var helloController: MDCTextInputControllerOutlined?)
- d) Add a single statement to 'func viewDidLoad' of: "helloController = MDCTextInputControllerOutlined(textInput: helloText)"
8. Build the project and in the Simulator notice that the field displays in nice Material Design style but does not permit the user to enter data.

## Expected behavior

I expected that the user input would cause the standard Material Design behaviour (keyboard displays, placeholder text moves up and user-input appears on the screen). 

## Actual behavior
The MDCTextField displayed passively in its default state and did not accept user input

## Platform (please complete the following information)
- Xcode 9.4 with Swift 4.1
- Xcode Simulator for iPhone 8 Plus
- MacBook Pro (2014 model)
- Mac OS 10.13.4 High Sierra

## Additional context
The Google lesson MDC-111 works correctly with MDCTextField behaving as expected. The only difference that I can see is that MDC-111 appears to have an Objective-C 'Main' and 'AppDelegate' modules. My project is entirely Swift with a single 'AppDelegate.swift' module. 

The 'user interaction enabled' flag is set on in Interface Builder. This is the default and I did not change it.

**Comment by TriumphT110** [comment]
OK. I've Pushed the project to GitHub as 'Test CocoaPods' in my 'TriumphT110' Github account. How do I connect you with it? (sorry I'm new to Github)

**Comment by jverkoey** [comment]
I found the repo here: https://github.com/TriumphT110/Test-CocoaPods

**Comment by TriumphT110** [comment]
Yepp. That's it!

**Comment by jverkoey** [comment]
@romoore Is this something you might be able to take a look at?

**Comment by willlarche** [comment]
@romoore , @jverkoey , this is based on the MDC-iOS codelab MDC-111 so I'll investigate.

**Comment by jverkoey** [comment]
Thanks Will!

**Comment by willlarche** [comment]
Hey, @TriumphT110 . Thanks for taking the MDC-111 codelab and thanks for reporting this issue. I think I know what's up.

### The issue

In `Main.storyboard`, the text field has a height constraint of 30. But our outline styled text field has an intrinsic height of about 82. So, the frame of the field is not tall enough for all of the elements. They are still drawn but they are outside the frame so they aren't 'touchable'.

See this Reveal where the frame is highlighted in light blue:
![screen shot 2018-05-31 at 8 11 49 pm](https://user-images.githubusercontent.com/1271525/40814653-79787d82-650f-11e8-8809-685d541bbc1f.png)

The text field still works if you touch the top 30 points of height like above the "Say Hello!" text.

### To fix this

Delete the height constraint. Here's the one I mean:
![screen shot 2018-05-31 at 8 14 10 pm](https://user-images.githubusercontent.com/1271525/40814659-86067d60-650f-11e8-8969-61130f0838d0.png)

Then the intrinsic height of the text field will expand the frame to the correct height and all parts will be touchable!

Let me know if this doesn't resolve your issue.

**Comment by Frankenstein666** [comment]
what if i want the height of the textfield to be less than 84, is there a way to customize the height property?

**Comment by romoore** [comment]
@Frankenstein666 I believe you would need to use a different style of Text Field. In this case, it's an Outlined controller with floating placeholders. There is [ongoing work to address "density" within Material](https://material.io/design/layout/density.html#usage), but we have not yet built out the new styles for Text Fields.
