### ISSUE TITLE
[TextFields] Typography theming not persisting in all states

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#4345]
Setting a placeholder font doesn't necessarily stick when you type letters after floating.

---
#### Internal data
- Associated internal bug: [b/117179040](http://b/117179040)

**Comment by jverkoey** [comment]
Can you add screenshots + a repro case? If the repro is just “always” then that’s fair as well.

**Comment by willlarche** [comment]
AFAIK, it's always.

**Comment by material-mirror** [comment]
The internal issue [b/117179040](http://b/117179040) is now closed. This issue is being closed as a result.
