### ISSUE TITLE
[Snackbar] Snackbar Manager buttonFont is not working

### ISSUE THREAD

**Issue by mbasnillo** [material-components/material-components-ios#4362]
I tried using the Material Components Snackbar earlier because it was the closest thing I could find that would match my requirements, and it was going well right until I tried styling the action button fonts. I've tried using the MDCSnackbarManager and the MDCSnackbarMessageView buttonFont attributes but none of them are working.

### My sample code

```
MDCSnackbarManager.messageFont = UIFont(name: "Lato-Bold", size: 18) // works
MDCSnackbarManager.buttonFont = UIFont(name: "Lato-Bold", size: 13) // doesn't work
MDCSnackbarMessageView.appearance().buttonFont = UIFont(name: "Lato-Bold", size: 13) // doesn't work
```

### Expected behavior

The action button font and size to change.

### Actual behavior

The action button font and size remain the same as it originally was.

### Platform (please complete the following information)

 - Tested on iPhone 6 and iPhone X Simulators
 - Both were iOS 11.3

**Comment by jverkoey** [comment]
Thank you for filing the bug report! @yarneo do you have a sense of what might be happening here?

**Comment by yarneo** [comment]
Thanks for reaching out @mbasnillo. 
Using `MDCSnackbarManager.buttonFont` should be the right way to set a custom font for the action button as you mentioned.

I was just looking up our current Snackbar example in the Catalog to test things out, namely [SnackbarSimpleExample.m](https://github.com/material-components/material-components-ios/blob/develop/components/Snackbar/examples/SnackbarSimpleExample.m#L138) , in there you would notice there is a "Customize Font Example" cell that when tapped presents a Snackbar with a custom font for both its message and button:
![2018-06-05 10_58_52](https://user-images.githubusercontent.com/4066863/40984261-75fac07c-68af-11e8-8d4e-18da78e92ca2.gif)

It looks like it is setting the button font as expected over there, but it could very much be the case that there is a bug that is occurring by changing the ordering of commands or maybe other things that are changing the behavior. I would love if possible to get a small snippet of how you initialize and present your snackbar message. Also could you possibly try initializing and setting the snackbar exactly as seen in the example and see if that works? (link to code snippet above) Lastly, are you using our latest version? it could be that we had bugs in the past that have now been fixed.

Thanks!

**Comment by mbasnillo** [comment]
So I just got back to the office, and was ready to check this problem again. Only this time the issue wasn't there anymore. Perhaps it was just a client-side issue where cleaning and rebuilding the project solved it. I only did just install the fonts yesterday so it may have had something to do with that.

Everything seems to be okay now, thank you for your quick responses!
