### ISSUE TITLE
[TextFields] : LeadingUnderlineLabel on top of TextField

### ISSUE THREAD

**Issue by RaoulNL** [material-components/material-components-ios#4363]
I've added three MDCTextFields to a VC using InterfaceBuilder. They all have a fixed height.
Furthermore I use MDCTextInputControllerUnderline. My main concern is that I want to have a message (in red) displayed under the TextField at some point.
However, this errormessage is displayed on top of the TextField and not below the underline.

## Reproduction steps

Here's my code so far.

```
let nameController = MDCTextInputControllerUnderline(textInput: textField)
nameController.textInput?.underline?.color = UIConfig.grayishBrown()
nameController.textInput?.underline?.lineHeight = 1
nameController.textInput?.placeholderLabel.font = UIConfig.defaultLabelFont()
nameController.textInput?.placeholderLabel.textColor = UIConfig.grayishBrown()
nameController.textInput?.font = UIConfig.defaultLabelFont()
nameController.textInput?.textColor = UIConfig.grayishBrown()
nameController.textInput?.leadingUnderlineLabel.text = "Errormessage"
nameController.placeholderText = "Name"
nameController.floatingPlaceholderNormalColor = UIConfig.grayishBrown()
nameController.floatingPlaceholderActiveColor = UIConfig.grayishBrown()
nameController.activeColor = UIConfig.grayishBrown()
nameController.leadingUnderlineLabelFont = UIConfig.defaultLabelFont()
nameController.leadingUnderlineLabelTextColor = UIConfig.scarlet()
allTextFieldControllers.append(nameController)
```

## Expected behavior

I expected the UnderlineLabel to be rendered below the underline.

## Actual behavior

The UnderlineLabel is placed on top of the UITextField

## Platform (please complete the following information)

This all happens in the simulator running iOS11.4

## Additional features
In both the UITextField, placeholder and leadingUnderlineLabel I use the AvenirNext font, which is a default MacOS font.
What is it that I'm missing here?

Regards, Raoul.

**Comment by RaoulNL** [comment]
Seems that setting a fixed height can cause an overlap of UnderlineLabel on the TextField.
Can anyone verify this?

**Comment by willlarche** [comment]
Hi! Yes I can verify this is expected behavior. The text fields should not have a fixed size. They size themselves. 

If you need it to have a fixed size, try setting the text field’s text insets mode to always.
