### ISSUE TITLE
[AppBar] Revisit the documentation for the top layout guide behavior

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4374]
Context:

> I'm thinking that we should not actively guide them to a deprecated solution. Can we push them to safeAreaLayoutGuide.topAnchor and maybe have a header-only comment (not docs) telling them to use topLayoutGuide as a fall-back?

https://github.com/material-components/material-components-ios/pull/4370#discussion_r193452295

---
#### Internal data
- Associated internal bug: [b/117177674](http://b/117177674)

**Comment by material-mirror** [comment]
The internal issue [b/117177674](http://b/117177674) is now closed. This issue is being closed as a result.
