### ISSUE TITLE
[Catalog] Detect deprecation warnings in our catalog examples

### ISSUE THREAD

**Issue by yarneo** [material-components/material-components-ios#4376]
Currently we aren't detecting if there is a use of a deprecated method/property in our examples. We should catch this in our CI so we won't use deprecated API in the future.

---
#### Internal data
- Associated internal bug: [b/117178826](http://b/117178826)

**Comment by material-mirror** [comment]
The internal issue [b/117178826](http://b/117178826) is now closed. This issue is being closed as a result.
