### ISSUE TITLE
[TextFields] Prevents functionally equivalent fonts from causing rendering jumps #4344 has been rolled back

### ISSUE THREAD

**Issue by yarneo** [material-components/material-components-ios#4385]
[TextFields] Prevents functionally equivalent fonts from causing rendering jumps #4344 has been rolled back in the latest release and should be looked at again to get it merged to develop.

The current blocking issue was the externalizing of the C symbol MDCFontIsSimplyEqualToFont that was causing build failures.

@willlarche and I chatted about this offline.

**Comment by randallli** [comment]
@yarneo  please add instructions to recreate the build failures. if you need add a b/ issue.

**Comment by yarneo** [comment]
b/109935610
