### ISSUE TITLE
Each component should include one section for adding the component, another for removing it

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#439]
Every component we create should be optimized for two things:
1. Adding the component to a project.
2. Removing the component from a project.

We cannot assume that the components as they are will be in use forever. Reasons for needing to move away from a component include, but aren't limited to:
- The platform providing a better solution.
- The community provides a better solution.
- A client does not want or perhaps even cannot use the component any longer.
- The client has acquired a code base written by a previous person and wants to "refactor the work".
## Tips for "Adding the component to a project"
- Provide CocoaPods, Carthage, and plain Xcode project options.
- Explain which umbrella header to import.
- Describe the most essential use cases.
- Describe advanced use cases.

These steps are more or less captured in our READMEs already.
## Tips for "Removing the component from a project"
- What alternatives exist at the time of this component's writing?
- Can the client move away from a component in small pieces of work — e.g. one view controller at a time — or will the client need to re-architect their entire application? We sincerely want to avoid the latter (we're **not** building a framework).

**Comment by ianegordon** [comment]
Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄
