### ISSUE TITLE
Remove legacy code for iOS 9

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#4390]
This is a catch-all issue for TODOs embedded in code indicating cleanup when we drop support for iOS 9.

Do not close this issue until all // TODO: (#4390) have been removed.

---
#### Internal data
- Associated internal bug: [b/117178960](http://b/117178960)

**Comment by ianegordon** [comment]
Work on this issue is blocked until we officially drop support for iOS 9.

**Comment by material-mirror** [comment]
The internal issue [b/117178960](http://b/117178960) is now closed. This issue is being closed as a result.
