### ISSUE TITLE
"Add badges to all components" Doesn't seem to work on github...

### ISSUE THREAD

**Issue by samskiter** [material-components/material-components-ios#4394]
Badges/images added don't appear to be showing on github. According to the latest release notes there should be badges on all components...

![screen shot 2018-06-13 at 14 49 07](https://user-images.githubusercontent.com/1271643/41355307-168a0a38-6f19-11e8-9616-48e0d6c7f219.png)

**Comment by ianegordon** [comment]
This appears to be working again...... strange.  

![screen shot 2018-06-15 at 12 55 32](https://user-images.githubusercontent.com/1121006/41480184-8bfa3986-709b-11e8-8309-3adedbdcc57c.png)


Please re-open if it pops up again / you can repro locally.
Many Thanks!
