### ISSUE TITLE
[List] Support shadow masking

### ISSUE THREAD

**Issue by samskiter** [material-components/material-components-ios#4395]
## Feature Request/Suggestion

As we have very large views, we'd like to be able to build up the appearance of a single shadow layer with multiple shadow layers in order to allow us to break our views up into multiple tableview cells.

Ideally we'd be able to ask for any combination of top/left/right/bottom shadows.

Happy to contribute this back if it's of interest

## Additional context

Collection view previously seemed to support something similar to this with [MDCCollectionViewOrdinalPosition](https://github.com/material-components/material-components-ios/blob/bc119b3b73778cdebab80a6eeaf0a957cfd5a09b/components/CollectionLayoutAttributes/src/MDCCollectionViewLayoutAttributes.h#L20) 

---
#### Internal data
- Associated internal bug: [b/117178998](http://b/117178998)

**Comment by ianegordon** [comment]
Hi @samskiter 

Could this case be handled via a supplementary view?  Why don't we discuss offline?

**Comment by samskiter** [comment]
Sure, fire me an email/hangout

**Comment by ianegordon** [comment]
Due to the complexity of MDCShadowLayer, we've decided against this.
Please reach out to me directly and we can go over the pros/cons.
Thanks @samskiter !

**Comment by jverkoey** [comment]
This feature request will be required to support grouped cells, so I think we may want to keep this open to track future work we do there.

**Comment by ianegordon** [comment]
@samskiter has a existing use case and mocks.  Let's coordinate with his team when we are ready to move forward.

**Comment by material-mirror** [comment]
The internal issue [b/117178998](http://b/117178998) is now closed. This issue is being closed as a result.
