### ISSUE TITLE
[Collections] Alternative for deprecated collections

### ISSUE THREAD

**Issue by cloudface** [material-components/material-components-ios#4396]
### Overview
Hello. I recently noticed that the [collections component](https://github.com/material-components/material-components-ios/tree/develop/components/Collections) has been deprecated and that we should use either [Cards](https://github.com/material-components/material-components-ios/tree/develop/components/Cards) or [Lists](https://github.com/material-components/material-components-ios/tree/develop/components/List). However, neither of those alternatives seem to provide a look and feel that the collections component did:

<img width="428" alt="screen shot 2018-06-15 at 08 45 06" src="https://user-images.githubusercontent.com/1231070/41454099-78289376-7078-11e8-8d0a-d956ec3d7c07.png">

How can I achieve the look and feel shown in the screenshot above using either the Card or the List components?

 On a separate but related note: Is the List component the way to go if I want self-sizing collection view cells?

Thank you guys for the great library and for the info!

Regards
Chris

**Comment by ianegordon** [comment]
Hi @cloudface !  As you correctly noted, we are no longer recommending Collections.  Our replacement, ListItems which are currently being worked on.  (See #4382 for the work-in-progress)

**Comment by ianegordon** [comment]
I hope List meets your needs.
If you have feature request, please open a new issue. 😄
