### ISSUE TITLE
[Textfields] Add the equivalent of UITextInputTraits.secureTextEntry

### ISSUE THREAD

**Issue by ivangodfather** [material-components/material-components-ios#4397]
## Feature Request/Suggestion

I would like to add a password visibility toggle (eye) like android does

passwordToggleEnabled=“true”

---
#### Internal data
- Associated internal bug: [b/117178900](http://b/117178900)

**Comment by ianegordon** [comment]
The UIKit equivalent would be secureTextEntry in UITextInputTraits.

**Comment by ivangodfather** [comment]
@ianegordon im asking for an ["eye" button](https://i.pinimg.com/originals/7c/ce/82/7cce82eebbc46a883c88ff0ca14d8a09.png) inside the textfield to toggle between that.

**Comment by material-mirror** [comment]
The internal issue [b/117178900](http://b/117178900) is now closed. This issue is being closed as a result.
