### ISSUE TITLE
Provide reasonable -description and -debugDescription implementations

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#440]
This is a global task applicable to any object type.

There are two ways to tackle this:
- Directly implement the respective methods.
- Build a runtime manipulation mechanism that dynamically registers a description method on classes that don't provide one. This dynamic method would dump all of the properties (-description) and ivars (-debugDescription).

Specific objects that could use some love:
- [ ] MDCShadowLayer

---
#### Internal data
- Associated internal bug: [b/117179271](http://b/117179271)

**Comment by ianegordon** [comment]
Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄

**Comment by romoore** [comment]
This would certainly have aided me in debugging views in the past. Any reason to ignore this? I think it still has value.  Even as originally worded I think it's valuable, I don't think a new bug is warranted.

**Comment by jverkoey** [comment]
Agreed that there's likely still value here.

**Comment by ianegordon** [comment]
There is absolutely value, but there has been 28 months with no movement. 😞 
What is the path forward?
Do we want to add this to the checklist as a requirement to getting to 'D'one? go/mdc-checklist

**Comment by material-mirror** [comment]
The internal issue [b/117179271](http://b/117179271) is now closed. This issue is being closed as a result.
