### ISSUE TITLE
Make Dynamic Type Sizing Tables customizable

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#4425]
Right now our components hard code the sizing curves for Dynamic Type.  For instance, Feature Highlight uses MDCFontTextStyleTitle and MDCFontTextStyleSubheadline.  These values should be configurable.

---
#### Internal data
- Associated internal bug: [b/117177673](http://b/117177673)

**Comment by material-mirror** [comment]
The internal issue [b/117177673](http://b/117177673) is now closed. This issue is being closed as a result.
