### ISSUE TITLE
[Testing] Add support for snapshot testing

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#4426]
We should have tooling that runs A/B testing on screenshots generated during our testing phase.

**Comment by jverkoey** [comment]
We now have internal snapshot testing as part of our release process. Adding external snapshot testing can/should be explored, with the caveat that it shouldn't significantly add to our presubmit turnaround times.

**Comment by jverkoey** [comment]
Duplicate of https://github.com/material-components/material-components-ios/issues/5199
