### ISSUE TITLE
[TextFields] issue with floating label

### ISSUE THREAD

**Issue by karolsteve** [material-components/material-components-ios#4433]
When using MDCTextField as UITextField in storyboard, after line below, totoField is not editable

```line```
a = MDCTextInputControllerUnderline(textInput: totoField)

---
#### Internal data
- Associated internal bug: [b/117178313](http://b/117178313)

**Comment by karolsteve** [comment]
which title ?

**Comment by willlarche** [comment]
Hey @karolsteve , can you explain so more of what's going?

**Comment by material-mirror** [comment]
The internal issue [b/117178313](http://b/117178313) is now closed. This issue is being closed as a result.
