### ISSUE TITLE
[TextFields] MDCLeadingViewTextInput protocol needs unit tests

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#4437]
Related to #4434 

---
#### Internal data
- Associated internal bug: [b/117178424](http://b/117178424)

**Comment by jverkoey** [comment]
What testing do we feel this component needs specifically?

**Comment by material-mirror** [comment]
The internal issue [b/117178424](http://b/117178424) is now closed. This issue is being closed as a result.
