### ISSUE TITLE
[TextFields] Text Field node is missing description

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#4438]
The Text Fields node is missing a description in the catalog.

![simulator screen shot - iphone 4s - 2018-06-25 at 10 55 45](https://user-images.githubusercontent.com/1753199/41857904-8c8b2360-7866-11e8-9b9f-8624b24185ff.png)

## Reproduction steps

1. Launch the catalog
2. Open "Text Field"

## Expected behavior
A description is shown and the "Start Demo" button is fully visible.

## Actual behavior
No description is available and the "Start Demo" is partially obscured.

## Platform (please complete the following information)
iPhone 4s/iOS 9.0

---
#### Internal data
- Associated internal bug: [b/117178176](http://b/117178176)

**Comment by material-mirror** [comment]
The internal issue [b/117178176](http://b/117178176) is now closed. This issue is being closed as a result.
