### ISSUE TITLE
Write a best practice: how to theme UINavigationBar to look like a Material App Bar

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#445]
The App Bar is a powerful component that provides the full package of Material navigation bar buttons, a flexible header, and space to attach a bottom bar. The cost of this component is that you must create one for every view controller that wishes to use one.

In practice, not all view controllers will take full advantage of the App Bar's functionality.

For example, a simple settings controller can likely get by with simply setting the background color of the navigationBar.

This best practice should:
- [ ] Identify when to use the App Bar vs when to use a simple UINavigationBar.
- [ ] Show how to add Button instances to UINavigationBar.
- [ ] Show how to add Ink to UINavigationBar buttons and views.

The two components should be interchangeable and we should have examples using just a simple UINavigationBar.

**Comment by ianegordon** [comment]
Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄
