### ISSUE TITLE
[Slider] Update Slider design to match material.io guidelines

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#4451]
https://material.io/design/components/sliders.html#discrete-slider

## Notable changes
* Slider at "zero" is no longer "hollow"
* Support 2 "thumbs" for range-based sliders
* Review the rest of the article in case there's more

---
#### Internal data
- Associated internal bug: [b/117178077](http://b/117178077)

**Comment by material-mirror** [comment]
The internal issue [b/117178077](http://b/117178077) is now closed. This issue is being closed as a result.
