### ISSUE TITLE
[Tabs] We don't respect leading/trailing padding for scrollable tabs

### ISSUE THREAD

**Issue by codeman7** [material-components/material-components-ios#4456]
We don't respect the leading or trailing padding for scrollable tabs.

## Reproduction steps

1. TabBar within dragons
2. Select 'TextTabs'

## Expected behavior

The guidelines says we should have a 52dp padding before scrollable tabs.

https://material.io/design/assets/1XBNaDj-1y46FsN4UN5Ak5-F2vTolLDIl/tabs-spec-scrollable.png

## Actual behavior

Currently we have padding but it is 8dp 

<img width="375" alt="screen shot 2018-06-29 at 2 17 09 pm" src="https://user-images.githubusercontent.com/7131294/42108018-51323bd4-7ba7-11e8-9b10-b1c8c4ddaf60.png">

## Platform (please complete the following information)

iPhone X/iOS 11

---
#### Internal data
- Associated internal bug: [b/117178106](http://b/117178106)

**Comment by romoore** [comment]
MDCTabBarView has the correct leading inset and allows clients to adjust `contentInsets` if desired.
