### ISSUE TITLE
[ActionSheet] Prototyping

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#4459]
- Implement a prototype that demonstrates content being placed in some sort of sliding sheet thing.
- The API should resemble UIKit's action sheet APIs.

**Comment by codeman7** [comment]
So far using Bottom sheet for the presentation. Thoughts on the list options were either a UITableView or to loop over the actions and manually add them. As of now using UITableView to add them so we can use the dequeue and reuse methods that apple provides.

**Comment by codeman7** [comment]
Having to support dynamic type within the cells

**Comment by codeman7** [comment]
Also, thinking about possibly a UICollectionView in a case where a ActionSheet is presented on an iPad.

**Comment by codeman7** [comment]
Not going to support the popOver API that a UIAlertControllerStyleActionSheet does on iPad.

**Comment by romoore** [comment]
Does that mean it will present as a full-width Action Sheet like it does on iPhone?

**Comment by codeman7** [comment]
As of now , I think it will be inset and possible a two column grid. Need to confirm with design.
