### ISSUE TITLE
[BottomNavigation] Missing support for selected/unselected font changes

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#4462]
M2 permits parameterization of the selected/unselected item title fonts to vary.  The current implementation of MDCBottomNavigationBar only has `itemTitleFont` as a property. This should be expanded into `-selectedItemTitleFont` and `-unselectedItemTitleFont`.

---
#### Internal data
- Associated internal bug: [b/117176876](http://b/117176876)

**Comment by material-mirror** [comment]
The internal issue [b/117176876](http://b/117176876) is now closed. This issue is being closed as a result.
