### ISSUE TITLE
[Catalog] AnimationTiming has no examples

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#4466]
The "AnimationTiming" component has no examples.

![simulator screen shot - iphone 4s - 2018-07-02 at 14 20 21](https://user-images.githubusercontent.com/1753199/42179882-3226c4fe-7e03-11e8-8f2a-867fdaf2a160.png)

## Reproduction steps
1. Open the Catalog
1. Navigate to "Animation Timing"

## Expected behavior
At least one example

## Actual behavior
No examples

## Platform (please complete the following information)
iPhone 4s/iOS 9

---
#### Internal data
- Associated internal bug: [b/117178921](http://b/117178921)

**Comment by material-mirror** [comment]
The internal issue [b/117178921](http://b/117178921) is now closed. This issue is being closed as a result.
