### ISSUE TITLE
[ProgressView] Showing the progress bar shouldn't steal voice over focus

### ISSUE THREAD

**Issue by gambard** [material-components/material-components-ios#4470]
## Feature Request/Suggestion

When the ProgressView is hidden/shown a UIAccessibility notification is posted. This notification steals the current focus of voice over to set it to the progress bar. But the notification takes time to steal focus and for short loading time, the focus is stolen after the progress is done (and the progress bar can even be hidden).

It would be nice if there is a way to prevent the notification to steal the focus (by passing nil instead of self in UIAccessibilityPostNotification).

---
#### Internal data
- Associated internal bug: [b/117178175](http://b/117178175)

**Comment by material-mirror** [comment]
The internal issue [b/117178175](http://b/117178175) is now closed. This issue is being closed as a result.
