### ISSUE TITLE
[Tabs] Add example with multiple child view controllers

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#4483]
## Feature Request/Suggestion
From an internal developer:

> Would you please make `TabBarTextOnlyExampleSupplemental.m` a little more exhaustive by adding child view controllers for different tabs rather than using the same content for every tab?

---
#### Internal data
- Associated internal bug: [b/117177633](http://b/117177633)

**Comment by C-anuj** [comment]
Can you provide any updates on this / timeline?
Thank you!

**Comment by material-mirror** [comment]
The internal issue [b/117177633](http://b/117177633) is now closed. This issue is being closed as a result.
