### ISSUE TITLE
[Color] Allow Gradients in Color Scheme

### ISSUE THREAD

**Issue by IchordeDionysos** [material-components/material-components-ios#4489]
## Feature Request/Suggestion

It would be soo awesome if I could define a gradient for example for the background of a card.
I know Material Design has nothing mentioned like this in the spec, but sometimes it makes sense to conform with the company's CI and so on.

---
#### Internal data
- Associated internal bug: [b/117177917](http://b/117177917)

**Comment by jverkoey** [comment]
We'd need to explore the mechanisms by which we can store a gradient color in the color scheme.

**Comment by romoore** [comment]
Aren't gradients a property of CALayers and not UIColors?

**Comment by jverkoey** [comment]
Correct, but our schemes are simple data objects. Iteration here would require some means of representing a gradient in the color scheme.

**Comment by jverkoey** [comment]
Unless someone were to craft a gradient from the color scheme properties in a custom mapping, but my understanding of this issue is that there is a desire to say “my primary color is a gradient”.

**Comment by material-mirror** [comment]
The internal issue [b/117177917](http://b/117177917) is now closed. This issue is being closed as a result.
