### ISSUE TITLE
[Cards] Not able to deselect card with no direct previous user interaction

### ISSUE THREAD

**Issue by IchordeDionysos** [material-components/material-components-ios#4490]
The elevation of a Card is not properly updated according to the `isSelected` property if `isSelected` won't be set in direct response to a user interaction.

## Reproduction steps

1. Add an `MDCCard` to your ViewController
2. Add a target for your `MDCCard` 
`card.addTarget(self, action: #selector(cardClicked(_:)), for: .touchUpInside)`
3. Set a different elevation for the selected state, like this:
`card.setShadowElevation(.cardPickedUp, for: .selected)`
3. Implement the card click function like this:
```swift
@objc func cardClicked(_ sender: MDCCard) {
    card.isSelected = true
    
    DispatchQueue.main.asyncAfter(deadline: .now() + 4) {
        self.card.isSelected = false
        // Uncommenting workaround below will fix the problem
        // let elevation = self.card.shadowElevation(for: .normal)
        // self.card.setShadowElevation(elevation, for: .normal)
    }
}
```

## Expected behavior

The card is raised permanently for 4 seconds and then get animated to the default card elevation

## Actual behavior

The card get's raised as expected, but after 4 seconds the card is still in the raised state even if the is not selected anymore.

## Platform (please complete the following information)

 - Device: iPhone X (Simulator)
 - OS: iOS 11.4

## Additional context

---
#### Internal data
- Associated internal bug: [b/117178898](http://b/117178898)

**Comment by yarneo** [comment]
Hi @IchordeDionysos,

At the cards current form, the `MDCCard` doesn't support a selected state but rather only a normal and highlighted state. As per the design spec, a card has a selected state when it is part of a collection. Therefore `MDCCardCollectionCell` fully supports a selected state. You can make it support the selected form by setting: `cell.selectable = true`.

If you want to try and still use the `MDCCard` state with different elevations, you can try manipulating the highlighted state instead.

Let me know if there is anything else I can help you with!

**Comment by jverkoey** [comment]
Un-assigning due to inactivity. Please re-assign if you are working on this.

**Comment by material-mirror** [comment]
The internal issue [b/117178898](http://b/117178898) is now closed. This issue is being closed as a result.
