### ISSUE TITLE
[List] Add Unit Tests For MDCBaseCell

### ISSUE THREAD

**Issue by andrewoverton** [material-components/material-components-ios#4492]
MDCBaseCell doesn't have unit tests. I need to write them!

---
#### Internal data
- Associated internal bug: [b/117178422](http://b/117178422)

**Comment by jverkoey** [comment]
Unassigning due to inactivity. Please re-assign yourself if you are working on this.

**Comment by material-mirror** [comment]
The internal issue [b/117178422](http://b/117178422) is now closed. This issue is being closed as a result.
