### ISSUE TITLE
[List] Give the MDCBaseCell Swift example a storyboard 

### ISSUE THREAD

**Issue by andrewoverton** [material-components/material-components-ios#4493]
Storyboard examples are commonly requested, so we should add a storyboard to our Swift MDCBaseCell example.

---
#### Internal data
- Associated internal bug: [b/117178920](http://b/117178920)

**Comment by jverkoey** [comment]
Unassigning due to inactivity. Please re-assign yourself if you are working on this.

**Comment by material-mirror** [comment]
The internal issue [b/117178920](http://b/117178920) is now closed. This issue is being closed as a result.
