### ISSUE TITLE
[BottomNavigation] MDCBottomNavigationItemView `accessibilityLabel` is not internationalizable

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#4500]
MDCBottomNavigationItemView's `accessibilityLabel` is computed by combining the tab's title and a translated string, "tab". The two values are appended using a comma, but this may be inappropriate for some locales. Instead, they should be joined using a translatable format string. 
Probably something like, `"%1$@, %2$@"`.

---
#### Internal data
- Associated internal bug: [b/117178073](http://b/117178073)

**Comment by material-mirror** [comment]
The internal issue [b/117178073](http://b/117178073) is now closed. This issue is being closed as a result.
