### ISSUE TITLE
[AppBar] Navigating with voiceover on effects the height

### ISSUE THREAD

**Issue by codeman7** [material-components/material-components-ios#4503]
1. Turn on VoiceOver
2. Open up Catalog
3. Go to AppBar -> Primary Demo or UITableView with section headers
4. Navigate the elements within app bar

## Expected behavior

The height shouldn't change

## Actual behavior

Height changes almost every time you navigate to a new element within app bar

iOS 11/iPhone X

**Comment by jverkoey** [comment]
Duplicate of #3658
