### ISSUE TITLE
[TextFields] Animation too slow

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4519]
From the internal bug:

> When tapping a text field the text appears to move too slowly

---

This is an internal issue. If you are a Googler, please visit [b/110705602](http://b/110705602) for more details.

---
#### Internal data
- Associated internal bug: [b/110705602](http://b/110705602)

**Comment by material-mirror** [comment]
The internal issue [b/110705602](http://b/110705602) is now closed. This issue is being closed as a result.
