### ISSUE TITLE
[Slider] Make a 2-handled "Range" slider

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4521]
This is an internal issue. If you are a Googler, please visit [b/110748456](http://b/110748456) for more details.

---
#### Internal data
- Associated internal bug: [b/110748456](http://b/110748456)

**Comment by jverkoey** [comment]
@ianegordon Please re-assign yourself if you're still working on this.

**Comment by material-mirror** [comment]
The internal issue [b/110748456](http://b/110748456) is now closed. This issue is being closed as a result.
