### ISSUE TITLE
[TextFields] LeadingView and TrailingView should be baseline aligned when UILabels

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4527]
From the internal bug:

> Right now they are centerY aligned which is correct for all other views but not text views.

---

This is an internal issue. If you are a Googler, please visit [b/110855696](http://b/110855696) for more details.

---
#### Internal data
- Associated internal bug: [b/110855696](http://b/110855696)

**Comment by material-mirror** [comment]
The internal issue [b/110855696](http://b/110855696) is now closed. This issue is being closed as a result.
