### ISSUE TITLE
[Tabs] Indicator shifts slightly when opening the iOS Camera

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4528]
This is an internal issue. If you are a Googler, please visit [b/110883112](http://b/110883112) for more details.

---
#### Internal data
- Associated internal bug: [b/110883112](http://b/110883112)

**Comment by material-mirror** [comment]
The internal issue [b/110883112](http://b/110883112) is now closed. This issue is being closed as a result.
