### ISSUE TITLE
[MDCBottomSheet] When dismissing a modal controller on top of a bottom sheet, the bottom sheet jumping after re-appearing

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4532]
From the internal bug:

> Steps:
> 1. Present a ViewController modally on top of an MDCBottomSheetViewController (which is presented modally as well).
> 2. Dismiss the top view controller.
> 
> Observed Behavior:
> Bottom Sheet content appears on top and then jumps to its normal position.
> 
> Expected Behavior:
> Bottom Sheet content appears on expected position after dismissing the second view controller.

---

This is an internal issue. If you are a Googler, please visit [b/111329201](http://b/111329201) for more details.

---
#### Internal data
- Associated internal bug: [b/111329201](http://b/111329201)

**Comment by material-mirror** [comment]
The internal issue [b/111329201](http://b/111329201) is now closed. This issue is being closed as a result.
