### ISSUE TITLE
[NavigationBar] Deprecate left/right bar button items `Internal issue b/111435856`

### ISSUE THREAD

**Issue by codeman7** [material-components/material-components-ios#4550]
Currently we are using both leading/trailing bar button items and left/right bar button items. We need to move to leading and trailing only to support RTL.

---
#### Internal data
- Associated internal bug: [b/111435856](http://b/111435856)

**Comment by jverkoey** [comment]
Un-assigning this bug due to inactivity by the assignee. Please re-assign yourself if you are working on this issue.

**Comment by material-mirror** [comment]
The internal issue [b/111435856](http://b/111435856) is now closed. This issue is being closed as a result.
