### ISSUE TITLE
[AppBar] Fix "Reorder" label in Cards Edit/Reorder Demo

### ISSUE THREAD

**Issue by galiak11** [material-components/material-components-ios#4574]
Change **R...R** to **Reorder**:
![image](https://user-images.githubusercontent.com/2329102/42780760-2501a036-8912-11e8-84ca-79a3f137d47f.png)

---
#### Internal data
- Associated internal bug: [b/117176873](http://b/117176873)

**Comment by material-mirror** [comment]
The internal issue [b/117176873](http://b/117176873) is now closed. This issue is being closed as a result.
