### ISSUE TITLE
[Chips] Placeholder goes outside MDCChipField with MDCTextInputControllerUnderline

### ISSUE THREAD

**Issue by bhamiltoncx** [material-components/material-components-ios#4576]
Steps to reproduce (I used Xcode 9.4.1 and iOS 11.4, repro at https://github.com/bhamiltoncx/ChipsFieldInputController ):

```
git clone https://github.com/bhamiltoncx/ChipsFieldInputController && cd ChipsFieldInputController
pod update
open ChipsFieldInputController.xcworkspace
Build and Run in Xcode
Tap on chips input
Type text
```

Expected behavior: Placeholder should stay inside bounds of MDCChipField after tapping on it.
Actual behavior: Placeholder animates outside bounds of MDCChipField after tapping on it.
Expected behavior: Text input cursor should be placed to the right of most recently entered chip.
Actual behavior: Text input cursor is obscured by chips.

Before tapping (note Placeholder is inside bounds)
===

<img width="299" alt="screen shot 2018-07-16 at 4 55 23 pm" src="https://user-images.githubusercontent.com/671827/42787740-109cadfa-8919-11e8-88d7-73f5d18bb5e1.png">

After tapping (note Placeholder is outside bounds)
===

<img width="299" alt="screen shot 2018-07-16 at 4 55 24 pm" src="https://user-images.githubusercontent.com/671827/42787738-108acd7e-8919-11e8-80b7-e8ad26de1361.png">

After entering a chip (note cursor is obscured by chip)
===

<img width="299" alt="screen shot 2018-07-16 at 4 55 28 pm" src="https://user-images.githubusercontent.com/671827/42787737-1076bd5c-8919-11e8-91af-bdcc721e2e30.png">

---
#### Internal data
- Associated internal bug: [b/116779079](http://b/116779079)

**Comment by bhamiltoncx** [comment]
As a note, the same technique works OK for MDCMultilineTextField.

**Comment by bhamiltoncx** [comment]
I also noticed the delegate method `-chipFieldHeightDidChange:` is not called when the placeholder animates. I suspect this is a related issue.

**Comment by romoore** [comment]
Thanks, @bhamiltoncx , but MDCTextFields do not yet support Chips. We have [a project that has scoped the work required](https://github.com/material-components/material-components-ios/projects/42).

**Comment by bhamiltoncx** [comment]
Thanks! I saw the project but didn’t see any items related to text input
controllers, so I incorrectly assumed more progress had been made and text
input controllers were working.

**Comment by material-mirror** [comment]
The internal issue [b/116779079](http://b/116779079) is now closed. This issue is being closed as a result.
