### ISSUE TITLE
[BottomNavigation] On iPhone X touch ripple for MDCBottomNavigationBar is cut off near bottom area

### ISSUE THREAD

**Issue by rajpara** [material-components/material-components-ios#4585]
## Description

This may be intended behavior and if it is feel free to let me know. It seems odd because MDCTabBarViewController seems to do this one way whereas MDCBottomNavigationBar does it another way.

Specifically in this case when I use MDCBottomNavigationBar on an iPhone X and select an item in the tab bar, the ripple is cut off near the bottom.

## Reproduction steps

1. Run the MDCDragons app on an iPhone X simulator
2. Select one of the tab bar items
3. Notice that the ripple is cut off near the bottom since the subview of MDCBottmNavigationBar sizes itself to exactly fit the items and its 'clipsToBounds' property is set to YES

## Expected behavior

The ripple should extend to the bottom of the screen on iPhone X (unsure if this is true but feels like it should be)

## Actual behavior

Ripple doesn't extend to bottom of screen

## Platform

 - Xcode 9.2 iPhone X simulator

![iphonex_cutoff_ripple](https://user-images.githubusercontent.com/41023534/42843341-a968216c-89c4-11e8-829e-2cb2471ef1c8.png)

---
#### Internal data
- Associated internal bug: [b/117178070](http://b/117178070)

**Comment by romoore** [comment]
Fixed in https://github.com/material-components/material-components-ios/pull/6586
