### ISSUE TITLE
[BottomNavigation] On iPod Touch using MDCBottomNavigationBar, selection ink feels delayed in showing up

### ISSUE THREAD

**Issue by rajpara** [material-components/material-components-ios#4586]
## Description

This seems to be a difference between MDCBottomNavigationBar and MDCTabBar. When selecting an item on MDCBottomNavigationBar, the ink feels like it is delayed in showing up. This becomes especially pronounced if instead of a tap a user perform a tap and hold at which point the ink doesn't show up for ~2 seconds.

On the other hand, in the MDCTabBar the ink in both the tap and long press scenario seems to show up immediately.

## Reproduction steps

1. Go to MDCDragons catalog app on an iPod touch 6th gen
2. Open Bottom Navigation -> Bottom Navigation
3. Select an item in tab bar, and then press and hold an item in tab bar.
4. Go back and then select Tab Bar -> Bottom Navigation
5. Complete same as step 3

## Expected behavior

Both step 3 and step 5 produce same latency on ink showing up.

## Actual behavior

In step 3 the ink feels much slower to show up

## Platform (please complete the following information)

 - Device: iPod Touch 6th Generation
 - OS: iOS 11.3

YouTube links which show the difference:
 
Press and hold behavior: https://youtu.be/UWc2zuMX7cI
Tapping behavior: https://youtu.be/h7CVkgCYJZw

**Comment by rajpara** [comment]
Note that we were also able to repro this issue on an iPhone 8 running iOS 12

**Comment by jverkoey** [comment]
Hi @rajpara - are you seeing this behavior in any apps other than MDCDragons?

**Comment by rajpara** [comment]
I see this behavior in my own app as well (didn't upload that code or video since I've got a bunch of other code around it as well).

**Comment by jverkoey** [comment]
Thank you for confirming. We're encountering some particularly odd inconsistencies with how and when the behavior you've described happens. We're looking into it though.

**Comment by romoore** [comment]
@rajpara Could you please confirm if the fix in #4625 fixes the issue for you as well?

You can easily check out a GitHub PR using the following alias (added to your `.gitconfig`):
```
pr = "!sh -c \"git fetch material \"pull/$1/head:pr-$1\"; git checkout \"pr-$1\"\""
```
And then do something like this

```bash
git pr 4625
```

**Comment by samskiter** [comment]
@rajpara I can also show you how to modify the podfile to pull the branch

**Comment by rajpara** [comment]
I just pulled your pr and tried it out in our codebase and it works great! Thanks for the quick fix!
