### ISSUE TITLE
[TextFields] Setting borderFillColor on a TextInputControllerOutlined does nothing

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#4600]
Trying to set the `borderFillColor` on an instance of TextInputControllerOutlined has no effect. Looking into [the implementation of `updateBorder`](https://github.com/material-components/material-components-ios/blob/develop/components/TextFields/src/MDCTextInputControllerOutlined.m#L171), it seems that the property is ignored.

## Reproduction steps
1. Set the `borderFillColor` on an instance of MDCTextInputController and observe the text field's border color

## Expected behavior
The border color of the text field matches the assigned color

## Actual behavior
There is no effect to setting the property

---
#### Internal data
- Associated internal bug: [b/117178172](http://b/117178172)

**Comment by andrewoverton** [comment]
The MDCTextInputControllerOutlined implementation of `updateBorder` calls [super](https://github.com/material-components/material-components-ios/blob/develop/components/TextFields/src/MDCTextInputControllerBase.m#L326), which does seem to do something with `borderFillColor`. I tried setting `borderFillColor` in the Dragons example for outlined Text Fields and I got this:

![simulator screen shot - iphone x - 2018-08-06 at 17 42 57](https://user-images.githubusercontent.com/8020010/43747730-8bdc2bd4-99a0-11e8-8f87-127d48c30096.png)

Super ugly 🤢

**Comment by material-mirror** [comment]
The internal issue [b/117178172](http://b/117178172) is now closed. This issue is being closed as a result.
