### ISSUE TITLE
[AppBar] README should link to FlexibleHeader's notes on scroll views

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#4618]
The AppBar's README should include a section that notifies clients that scroll views will have to be configured according to the guides in the Flexible Header's documentation. 

---
#### Internal data
- Associated internal bug: [b/117178821](http://b/117178821)

**Comment by material-mirror** [comment]
The internal issue [b/117178821](http://b/117178821) is now closed. This issue is being closed as a result.
