### ISSUE TITLE
[NavigationBar] Default title alignment should be `center`, not `leading`

### ISSUE THREAD

**Issue by ajsecord** [material-components/material-components-ios#4619]
The default title alignment of navigation bar titles on iOS [should be center](https://material.io/design/platform-guidance/cross-platform-adaptation.html#cross-platform-guidelines), not leading.

Leading is still appropriate for the occasional case where there are multiple items on the right/trailing side, but the default should be center and the client can choose to use leading in these cases.

This will be a breaking change and will need internal testing early on.

Aside: the implementation ties the alignment to the underlying UILabel's text alignment, which is a bit odd... if UILabel were to change its default then our default would magically change—admittedly that would never happen, but it's still a bit of a code smell. (I'm not suggesting changing this in this issue.)

---
#### Internal data
- Associated internal bug: [b/117178306](http://b/117178306)

**Comment by material-mirror** [comment]
The internal issue [b/117178306](http://b/117178306) is now closed. This issue is being closed as a result.
