### ISSUE TITLE
Consider better semantic naming for flexible header behaviors

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4620]
Some initial thoughts:

```
collapseBehavior = `disabled`, `collapsesToMinimumHeight`, `collapsesToSafeArea`, `collapsesEntirely` // shiftBehavior

detachedHeightBehavior = `disabled`, `canExpandToMaximumHeight` // canAlwaysExpandToMaximumHeight

overExtensionBehavior = `disabled`, `enabled` // canOverExtend
```

The background is that clients have been finding it somewhat challenging to discern what effect each of the behavioral flags will have on the flexible header. I'd like to attempt to consolidate the different behaviors into a set of better-defined and more semantically opaque APIs.

---
#### Internal data
- Associated internal bug: [b/117178918](http://b/117178918)

**Comment by jverkoey** [comment]
Related to https://github.com/material-components/material-components-ios/pull/4596.

**Comment by material-mirror** [comment]
The internal issue [b/117178918](http://b/117178918) is now closed. This issue is being closed as a result.
