### ISSUE TITLE
[BottomNavigation] Bottom alignment not working as expected

### ISSUE THREAD

**Issue by csilv** [material-components/material-components-ios#4623]
MDCBottomNavigationBar has an 'alignment' property to determine the alignment when the device is in landscape. This currently not working as expected. The problem was introduced in a recent commit:
https://github.com/material-components/material-components-ios/commit/1dd5ee9e4acf9a9eb4622b44e8582f50f322003c#diff-126129e6e405e19380e97e1992b4660b

This commit changed the implementation to use size classes instead of device orientation. But this change results in undesirable behavior. Specifically, the 'alignment' setting is now only used on iPad class devices. It is not used on an iPhone device (although perhaps it works on iPhone 8 Plus in landscape.)

The reason for this is illustrated here:
https://developer.apple.com/documentation/uikit/uitraitcollection?changes=_2&language=objc

Namely, the horizontalClass on an iPhone is going to be 'compact' in both portrait and landscape. On the iPad, it is 'regular' in both portrait and landscape.

---
#### Internal data
- Associated internal bug: [b/117177913](http://b/117177913)

**Comment by romoore** [comment]
I believe Plus devices in landscape alignment should also be considered `.Regular` horizontal size class.

Can you please clarify what you think the expected result should be? An iPad may not have sufficient horizontal space for side-by-side alignment, either.

**Comment by romoore** [comment]
That's a fair point. The guidelines specify "mobile on landscape" and we felt that horizontal size class .regular was pretty close platform interpretation of that guidance.   One option would be to disable the automatic behavior in some way, but that may break some clients (or make their code more complex). Maybe we can add a flag or delegate callback to "force" the alignment property to always be used?

**Comment by csilv** [comment]
Yes, a delegate method might be helpful here. Mostly what I would like to see is the same behavior as UITabBar which uses horizontal alignment in landscape on all iPhones.

A key benefit to horizontal alignment is that the tabbar takes up less vertical space, which most beneficial on the iPhone which has very little vertical space in landscape.

**Comment by csilv** [comment]
Thank you very much. FYI, MDCBottomNavigationBar uses a fixed height of 56pt (kMDCBottomNavigationBarHeight), except when using horizontal layout, in which case its height is 40pt (kMDCBottomNavigationBarHeightAdjacentTitles).

**Comment by romoore** [comment]
That's worrying. Since 48 points is the recommended minimum touch target height, I feel like 40 points is pretty short. I'll check that we have an exception for the 40-point height as well. Thanks!

**Comment by ianegordon** [comment]
There is some additional trickiness in that we don't support UIKit's automatic 'More' Tab if you have >5 view controllers.  (We just try and force as many items as possible into the tab bar)
As Rob mentioned, we typically we shoot for 48 point touch targets.
I believe there is an exception for tap targets against the edge of the screen, but with the iPhone X and it's soft home button I'm not sure this applies.

**Comment by romoore** [comment]
I'm seeking clarification with our internal accessibility teams to make sure we are following the latest recommendations.

**Comment by romoore** [comment]
We can go down to 48 points on Landscape, but no shorter based on conversations with our UX and accessibility teams. b/114760804

**Comment by material-mirror** [comment]
The internal issue [b/117177913](http://b/117177913) is now closed. This issue is being closed as a result.
