### ISSUE TITLE
[Catalog] Theme picker color circles are hidden behind the app bar

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#4633]
The catalog Theme color picker circles are hidden behind the app bar on some devices. On others, they are cut-off at the bottom.

**iPhone 4s/iOS 9.0 (Simulator)**

![simulator screen shot - iphone 4s - 2018-07-25 at 10 52 54](https://user-images.githubusercontent.com/1753199/43208847-4e86e16c-8ff9-11e8-970a-983817d6271d.png)

**iPhone X/iOS 11.4 (Simulator)**

![simulator screen shot - iphone x - 2018-07-25 at 10 58 28](https://user-images.githubusercontent.com/1753199/43209050-bb146cb4-8ff9-11e8-9288-075b21fbfd2d.png)

## Reproduction steps
1. Open the Catalog Menu
1. Select "Theme"

## Expected behavior
The theme picker circles are below the app bar

## Actual behavior
The theme picker circles are partly behind the app bar

## Related Information
This was working correctly as of #4468 and #4469

---
#### Internal data
- Associated internal bug: [b/117177667](http://b/117177667)

**Comment by material-mirror** [comment]
The internal issue [b/117177667](http://b/117177667) is now closed. This issue is being closed as a result.
