### ISSUE TITLE
Audit the entire catalog for iOS 12 bugs

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4638]
Definition of done:

## Every component example works as expected on iOS 12 non-X device

- [x] ActivityIndicator
- [x] AnimationTiming
- [x] AppBar
- [ ] Backdrop
- [ ] Banner
- [x] BottomAppBar
- [x] BottomNavigation
- [x] BottomSheet
- [ ] ButtonBar
- [x] Buttons
- [x] Cards
- [ ] Checkboxes
- [x] Chips
- [x] CollectionCells
- [ ] CollectionLayoutAttributes
- [x] Collections
- [ ] DataTables
- [x] Dialogs
- [x] Dividers
- [x] FeatureHighlight
- [x] FlexibleHeader
- [ ] HeaderStackView
- [ ] ImageList
- [x] Ink
- [ ] LibraryInfo
- [x] List
- [x] MaskedTransition
- [ ] Menus
- [x] NavigationBar
- [ ] NavigationDrawer
- [ ] OverlayWindow
- [x] PageControl
- [x] Palettes
- [x] ProgressView
- [ ] RadioButton
- [x] ShadowElevations
- [x] ShadowLayer
- [ ] SideSheet
- [x] Slider
- [x] Snackbar
- [x] Switch
- [ ] Tabs
- [x] TextFields
- [x] Themes
- [ ] Tooltips
- [x] Typography

## Every component example works as expected on an iOS 12 iPhone X

- [x] ActivityIndicator
- [x] AnimationTiming
- [x] AppBar
- [ ] Backdrop
- [ ] Banner
- [x] BottomAppBar
- [x] BottomNavigation
- [x] BottomSheet
- [ ] ButtonBar
- [x] Buttons
- [x] Cards
- [ ] Checkboxes
- [x] Chips
- [x] CollectionCells
- [ ] CollectionLayoutAttributes
- [x] Collections
- [ ] DataTables
- [x] Dialogs
- [x] Dividers
- [x] FeatureHighlight
- [x] FlexibleHeader
- [ ] HeaderStackView
- [ ] ImageList
- [x] Ink
- [ ] LibraryInfo
- [x] List
- [x] MaskedTransition
- [ ] Menus
- [x] NavigationBar
- [ ] NavigationDrawer
- [ ] OverlayWindow
- [x] PageControl
- [x] Palettes
- [x] ProgressView
- [ ] RadioButton
- [x] ShadowElevations
- [x] ShadowLayer
- [ ] SideSheet
- [x] Slider
- [x] Snackbar
- [x] Switch
- [ ] Tabs
- [x] TextFields
- [x] Themes
- [ ] Tooltips
- [x] Typography

**Comment by jverkoey** [comment]
@galiak11 Is this audit complete?

**Comment by jverkoey** [comment]
If complete, please close this issue.

**Comment by galiak11** [comment]
All components appearing in the catalog were checked. 2 issues were found on 2 different components (Lists & Progress view) - on both iphone-x & non-x devices.

**Comment by jverkoey** [comment]
Awesome - please add any new issues to the https://github.com/material-components/material-components-ios/projects/59 project so that we can track progress for August.
