### ISSUE TITLE
[Tabs] MDCTabBar does not expand the items if there is more space

### ISSUE THREAD

**Issue by babakbo** [material-components/material-components-ios#4642]
## Feature Request/Suggestion
Another alignment option in MDCTabBarAlignment which expands the items if there is more room, while having scrolling if the items do not fit.

## Additional context

MDCTabBarAlignment only supports either
1) expand-to-fit without scrolling (MDCTabBarAlignmentJustified) or
2) scrolling while each item is hugging its content (MDCTabBarAlignmentCenter).

Would be nice to have them together.

---
#### Internal data
- Associated internal bug: [b/117178103](http://b/117178103)

**Comment by ianegordon** [comment]
@romoore can you follow up with design on this?

**Comment by romoore** [comment]
I've reached out to one of our designers to get their feedback on this suggestion.  I will update this Issue when I hear back.

**Comment by romoore** [comment]
I've confirmed that this behavior is OK from a design perspective.  Automatically switching from Clustered Fixed tabs to Scrolling tabs or from Fixed tabs to Scrolling tabs is acceptable, particularly when there would not be sufficient space for the non-scrolling layouts (resizing the horizontal dimension of the view).

**Comment by material-mirror** [comment]
The internal issue [b/117178103](http://b/117178103) is now closed. This issue is being closed as a result.
