### ISSUE TITLE
[FlexibleHeader] Consider moving most of the view's APIs to the controller

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4644]
This has a few advantages:

- There is one less level of indirection that clients need to traverse in order to configure the component.
- We can probably drop the MDCFlexibleHeaderView from the public API altogether.
- It will be easier to split the many threads of logic contained within MDCFlexibleHeaderView into subsystems if everything is configured in the controller.

This process will essentially require going through the deprecation pipeline n times, once for each API. I think it may be wise to do this work piecemeal (one API at a time) so that we can iterate safely. Order probably doesn't matter too much.

---
#### Internal data
- Associated internal bug: [b/117178819](http://b/117178819)

**Comment by material-mirror** [comment]
The internal issue [b/117178819](http://b/117178819) is now closed. This issue is being closed as a result.
