### ISSUE TITLE
[BottomSheet] Bottom sheet shows incorrectly when personal hotspot is on

### ISSUE THREAD

**Issue by tipoc123** [material-components/material-components-ios#4645]
When the personal Hotspot is activated and bar resizes itself to 40px, the bottom sheet does not resize correctly. The bottom goes 20px below the screen instead of being resized.

## Reproduction steps

1. Enable personal hotspot in iPhone device
2. Bottom sheet moves down (out of the screen bounds)

## Expected behavior

The bottom sheet UI stays the same.

## Actual behavior

The bottom sheet UI moves down.

## Platform (please complete the following information)

 - Device: iPhone6
 - OS: iOS 11.4.1

## Additional context
Incorrect behavior (personal hotspot is on):

<kbd>
<img src="https://user-images.githubusercontent.com/15922591/43242956-879963a4-90ac-11e8-84ab-adabe5a4619e.jpg" width="360" height="640" border="1" />
</kbd>

&nbsp;
Normal behavior (personal hotspot is off):

<kbd>
<img src="https://user-images.githubusercontent.com/15922591/43242957-87b4c478-90ac-11e8-9a4e-d3510b9b8ac7.jpg" width="360" height="640" /> 
</kbd>

---
#### Internal data
- Associated internal bug: [b/117177629](http://b/117177629)

**Comment by material-mirror** [comment]
The internal issue [b/117177629](http://b/117177629) is now closed. This issue is being closed as a result.
