### ISSUE TITLE
Accessing topLayoutGuide crashes on iOS <10 when built with Xcode 10

### ISSUE THREAD

**Issue by AlimoRabbani** [material-components/material-components-ios#4651]
I'm not sure how many components may have this, but one instance is an opt-in behavior for fhvc:

https://github.com/material-components/material-components-ios/blob/9d16a4a8946e9a356c752427f80c6fbb078133cb/components/FlexibleHeader/src/MDCFlexibleHeaderView.m#L377

**Comment by jverkoey** [comment]
I can't repro this with the following setup:

- Xcode Version 10.0 beta 4 (10L213o)
- iOS 8.1
- iPhone 5s

I added a breakpoint to https://github.com/material-components/material-components-ios/blob/76a5c1e6882f46eb4c40d632c5bfd6ac49aff592/components/FlexibleHeader/src/MDCFlexibleHeaderView.m#L384 and was able verify that it executed the statement without crashing.

Marking as not reproducible, but if you're still seeing this crash please add more repro steps + environment version information.
