### ISSUE TITLE
[AppBar] Add a behavior that enables hideViewWhenShifted for the header stack view

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4655]
This will be an opt-in behavior on the MDCAppBar that makes the app bar's header stack view hide when the app bar is shifted off-screen. This will be accomplished with a Boolean flag that, when enabled, calls the flexible header view's `hideViewWhenShifted` with the header stack view.

---
#### Internal data
- Associated internal bug: [b/117178303](http://b/117178303)

**Comment by samskiter** [comment]
Note that this could be done via a view sat behind the status bar that can clip the appbar, or the appbar itself could fade out as it is shifted.

Would also need to work with collapsing such that the NavBar only is hidden/clipped, not the bottom bar.

**Comment by material-mirror** [comment]
The internal issue [b/117178303](http://b/117178303) is now closed. This issue is being closed as a result.
