### ISSUE TITLE
[Buttons] Unbounded Ripple

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4667]
From the internal bug:

> Is the unbounded ripple no longer a supported feature by design?
>
> We weren't able to get the unbounded behavior by setting the inkStyle to MDCInkStyleUnbounded.
> 
> We had to also change the following properties of inkView:
> [[button inkView] setUsesLegacyInkRipple:YES];
> [[button inkView] setClipsToBounds:NO];

---

This is an internal issue. If you are a Googler, please visit [b/111884558](http://b/111884558) for more details.

---
#### Internal data
- Associated internal bug: [b/111884558](http://b/111884558)

**Comment by material-mirror** [comment]
The internal issue [b/111884558](http://b/111884558) is now closed. This issue is being closed as a result.
