### ISSUE TITLE
[Buttons] Floating Action Button Expands to whole screen with two FABs

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4668]
This is an internal issue. If you are a Googler, please visit [b/111886103](http://b/111886103) for more details.

---
#### Internal data
- Associated internal bug: [b/111886103](http://b/111886103)

**Comment by material-mirror** [comment]
The internal issue [b/111886103](http://b/111886103) is now closed. This issue is being closed as a result.
