### ISSUE TITLE
[FlexibleHeader] Shade below header not showing when scrolled due to expanding

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4669]
This is an internal issue. If you are a Googler, please visit [b/111893667](http://b/111893667) for more details.

---
#### Internal data
- Associated internal bug: [b/111893667](http://b/111893667)

**Comment by material-mirror** [comment]
The internal issue [b/111893667](http://b/111893667) is now closed. This issue is being closed as a result.
