### ISSUE TITLE
[BottomNavigation] When tab bar item is in focused, in VoiceOver mode, the announcement repeats "tab" twice and "# of # twice" as well

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4682]
This is an internal issue. If you are a Googler, please visit [b/112045815](http://b/112045815) for more details.

---
#### Internal data
- Associated internal bug: [b/112045815](http://b/112045815)

**Comment by material-mirror** [comment]
The internal issue [b/112045815](http://b/112045815) is now closed. This issue is being closed as a result.
