### ISSUE TITLE
[SnackBar] Pin Snackbar to top of keyboard

### ISSUE THREAD

**Issue by gmann1** [material-components/material-components-ios#4687]
> For usage questions: ask on [Stack  Overflow](https://stackoverflow.com/questions/tagged/material-components+ios).

When the snackbar is shown while keyboard is visible sometimes there is a gap between the snackbar and keyboard. 

## Reproduction steps

While using a library that adjusts the view's y position, eg a library that will move a textfield when the keyboard is shown, the snackbar will also move relative to the keyboard. 

## Expected behavior

Snackbar always is pinned to keyboard regardless of any other layout changes.

## Actual behavior

A layout change that affects the view's y position will also move the snackbar causing there to sometimes be a gap between the snackbar and keyboard (or vice versa).

## Platform (please complete the following information)

 - Device: iPhone 6
 - OS: 11.3.1

## Additional context

Alternatively, is there an easy way to hide snackbar when keyboard is out? OR have the snackbar not appear above keyboard?

---
#### Internal data
- Associated internal bug: [b/117176852](http://b/117176852)

**Comment by jverkoey** [comment]
@yarneo can you take a look at this?

**Comment by gmann1** [comment]
@yarneo has this gotten any traction? Any sort of ETA on this would be great :D

**Comment by gmann1** [comment]
@jverkoey hey Jeff, is this something you all will still consider doing?

**Comment by yarneo** [comment]
Hey @gmann1 , apologies but would you be willing to clarify what you wish to achieve? Is the Snackbar pinning to the keyboard something you don't wish to have? Also, are you using the legacy Snackbar or the new one? I would recommend toggling the `usesLegacySnackbar` property on the MDCSnackbarMessage to `NO`.

**Comment by gmann1** [comment]
@yarneo The pinning is something I _do_ want to achieve, but currently this isn't happening:
![screen shot 2018-09-26 at 3 43 42 pm](https://user-images.githubusercontent.com/6133289/46113380-f9866f80-c1a2-11e8-8f70-4e0a91fe02ec.png)

v59.2.1 of snackbar.

I don't see the `usesLegacySnackbar` property on the MDCSnackbarMessage.

**Comment by yarneo** [comment]
Please see here: https://github.com/material-components/material-components-ios/blob/21810842725b86f68fb7dcbd023e4c39c56e3a08/components/Snackbar/src/MDCSnackbarMessage.h#L75

Try setting that Boolean to NO, as you are using the legacy snackbar snackbar that isn't upto date with our designs. Let me know if you experience the same issue with the new snackbar as well.

**Comment by gmann1** [comment]
@yarneo ah I see it now. It doesn't exactly solve the problem, but makes it better because now the snackbar 'floats' with and without the keyboard shown, where previously the legacy snackbar is pinned to the bottom of the screen when the keyboard is gone and 'floats' with the keyboard out (instead of pinned directly to the top of it).

It doesn't exactly solve my problem because it doesn't float the same height above the keyboard as it does to the bottom of the screen when the keyboard is gone. The float distance is still too large when the keyboard is out (because it's still not pinned to the keyboard). 

Screenshots to show what I mean:
No Keyboard:
![screen shot 2018-10-08 at 10 56 52 am](https://user-images.githubusercontent.com/6133289/46625491-0bdca380-cae9-11e8-8d65-8405f67ea4ff.png)

Keyboard:
![screen shot 2018-10-08 at 10 57 33 am](https://user-images.githubusercontent.com/6133289/46625497-11d28480-cae9-11e8-93fe-a8bce832db00.png)

**Comment by jverkoey** [comment]
Un-assigning due to inactivity. Please re-assign if you are working on this.

**Comment by material-mirror** [comment]
The internal issue [b/117176852](http://b/117176852) is now closed. This issue is being closed as a result.
