### ISSUE TITLE
[Tabs] Tabs in Hindi or Arabic text appear blurry

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4689]
This is an internal issue. If you are a Googler, please visit [b/112061648](http://b/112061648) for more details.

---
#### Internal data
- Associated internal bug: [b/112061648](http://b/112061648)

**Comment by material-mirror** [comment]
The internal issue [b/112061648](http://b/112061648) is now closed. This issue is being closed as a result.
