### ISSUE TITLE
[TextFields] MDCTextInputControllerOutlined touch area for editting 

### ISSUE THREAD

**Issue by dev-sawd** [material-components/material-components-ios#4710]
Hi.
I wanna MDCTextInputControllerOutlined about textfield.
but It didn't work correctly about touch area.
MDCTextField response when I touch top of it's layout

I got other question and solution
[TextFields] MDCTextField less responsive with MDCTextInputControllerUnderline #3088
but I didn't set height.

let me know what's wrong.

1. set Text Field in storyboard.
2. change Custom Class to MDCTextField
3. set IBOutlet like this
    @IBOutlet weak var sampleView: MDCTextField!
4. adapt attibute in viewDidLoad()
    sampleView.placeholder = "ID"
    textFieldControllerFloating = MDCTextInputControllerOutlined(textInput: sampleView)
    textFieldControllerFloating.isFloatingEnabled = true

---
#### Internal data
- Associated internal bug: [b/117177502](http://b/117177502)

**Comment by material-mirror** [comment]
The internal issue [b/117177502](http://b/117177502) is now closed. This issue is being closed as a result.
