### ISSUE TITLE
[Icons, NavigationBar, Catalog] Update ic_arrow_back_ios to edge-aligned version available on material.io

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#4741]
`ic_arrow_back_ios` should be edge-aligned (left alignment by default). [The latest `ic_arrow_back_ios` assets](https://material.io/tools/icons/?icon=arrow_back_ios&style=baseline) are available on material.io with the correct alignment.  

## Definitions of Done
* The `private/Icons` component has the latest baseline assets available from material.io with the edge-aligned back arrow.
* MDCNavigationBar supports offsetting the center of the Ripple (Ink) for the back icon. This should not be configured by default, but documented so that clients who set the back arrow can also adjust the ripple center offset. Consider using `UIOffset`. 
* Catalog is updated to use the new asset and the unbounded (Ink) Ripple is correctly centered within the visible portion of the image. Be sure to verify that although the Ripple extends outside the bounds of the back button, the full ripple effect is visible. Extending outside the screen edge is acceptable.

## Additional context
Internal issue: b/111761766

---
#### Internal data
- Associated internal bug: [b/111761766](http://b/111761766)

**Comment by romoore** [comment]
I don't think this was resolved. Neither is the internal issue.

**Comment by material-mirror** [comment]
The internal issue [b/111761766](http://b/111761766) is now closed. This issue is being closed as a result.
