### ISSUE TITLE
[schemes] Delete MDCColorScheme and MDCBasicColorScheme

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4760]
- [x] Measure internal usage of the API.
- [x] Create a GitHub project.
- [x] Write a [migration guide](https://github.com/material-components/material-components-ios/blob/develop/components/schemes/Color/docs/migration-guide-semantic-color-scheme.md). https://github.com/material-components/material-components-ios/pull/4737
- [x] Annotate the API as "ToBeDeprecated". https://github.com/material-components/material-components-ios/pull/4738
- [x] Determine a schedule for the API deletion. **Likely two months**.
  - October 10: APIs deprecated.
  - November 10: APIs deleted.
- [x] Announce that the API will be deprecated
- [ ] After the deprecation date, deprecate the API.
- [ ] After the deletion date, re-evaluate usage of the API.
- [ ] Delete the API and migration guide.

Related issues:

- https://github.com/material-components/material-components-ios/issues/4011

---
#### Internal data
- Associated internal bug: [b/117177778](http://b/117177778)

**Comment by material-mirror** [comment]
The internal issue [b/117177778](http://b/117177778) is now closed. This issue is being closed as a result.
