### ISSUE TITLE
[FlexibleHeader] Delete minMaxHeightIncludesSafeArea

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4764]
- [x] Measure internal usage of the API.
- [x] Create a GitHub project.
- [x] Write a migration guide. https://github.com/material-components/material-components-ios/tree/develop/components/FlexibleHeader#migration-guide-minmaxheightincludessafearea
- [x] Annotate the API as "ToBeDeprecated".
- [x] Determine a schedule for the API deletion.
- [ ] Announce that the API will be deprecated
- [ ] After the deprecation date, deprecate the API.
- [ ] After the deletion date, re-evaluate usage of the API.
- [ ] Delete the API and migration guide.

---
#### Internal data
- Associated internal bug: [b/117175876](http://b/117175876)

**Comment by material-mirror** [comment]
The internal issue [b/117175876](http://b/117175876) is now closed. This issue is being closed as a result.
