### ISSUE TITLE
[Snackbar] Allow indefinite duration

### ISSUE THREAD

**Issue by IchordeDionysos** [material-components/material-components-ios#4770]
## Feature Request/Suggestion

It should definitely be allowed to set the Snackbar duration to Indefinite, as it is possible on Android: https://developer.android.com/reference/android/support/design/widget/Snackbar.html#LENGTH_INDEFINITE
To make sure anyone can use the Snackbar on both Android and iOS the same way.

An indefinite snackbar should be cancelled if it is being told to and another snackbar ist being presented.

## Additional context

For example on Android we use the Snackbar in one or two Situations to notify the user that there is currently some background work going on. Why is that?
We have a highly customized loading screen and a Snackbar ist just a sneaky little and beautiful way to fit in a bit information for the user what is going on.
This is unfortunately not possible with the Snackbar...

---
#### Internal data
- Associated internal bug: [b/117176627](http://b/117176627)

**Comment by jverkoey** [comment]
cc @yarneo

**Comment by yarneo** [comment]
Just to clarify @IchordeDionysos , what would be the recommended behavior in your opinion if there is another Snackbar that is waiting to be presented and you have the current one set to stay indefinitely?

**Comment by IchordeDionysos** [comment]
@yarneo On Android, the behavior works like this:
You present a Snackbar with indefinite duration and when you want to present another Snackbar afterward the new Snackbar will stop the indefinite Snackbar.

Probably there could be some minimum duration an indefinite Snackbar will be presented (like 3 seconds or so).
This would make sure the indefinite Snackbar won't be dismissed immediately by a new Snackbar.
I'm not sure how this is handled on Android when you present an indefinite Snackbar and immediately after that a normal Snackbar.

**Comment by dapp** [comment]
+1 for this request.  See comments here: https://github.com/material-components/material-components-web/issues/153

**Comment by material-mirror** [comment]
The internal issue [b/117176627](http://b/117176627) is now closed. This issue is being closed as a result.

**Comment by freakdragon** [comment]
This is not the best solution, but it's better than nothing.

```
class FakeInfiniteMDCSnackbarMessage: MDCSnackbarMessage {
    override init() {
        if (AppSettings.isDebug) {
            print("!!!FakeInfiniteMDCSnackbarMessage init() don't use this initializer for message creation.")
        }
        super.init()
    }
    
    init(text: String) {
        FakeInfiniteMDCSnackbarMessage.customDuration = FakeInfiniteMDCSnackbarMessage.customDurationDefaultValue
        super.init()
        self.text = text
    }
    
    init(text: String, customDuration: TimeInterval) {
        FakeInfiniteMDCSnackbarMessage.customDuration = customDuration
        super.init()
        self.text = text
    }
    
    
    public static let customDurationDefaultValue: TimeInterval = 9999999
    
    public static var customDuration: TimeInterval = customDurationDefaultValue
    override var duration: TimeInterval {
        get {
            return FakeInfiniteMDCSnackbarMessage.customDuration
        }
        set { }
    }
    
    public var customCategory: String? = "infinite"
    override var category: String? {
        get {
            return customCategory
        }
        set { }
    }
}
```

If you'll show the message without setting the time, you'll have to dismiss it manually. For force dismissing of message you should use something like this:

```
MDCSnackbarManager.dismissAndCallCompletionBlocks(withCategory: "infinite")
```

Or you can use this code for close of any messages:

```
MDCSnackbarManager.dismissAndCallCompletionBlocks(withCategory: nil)
```

May be, somebody has better solution without manual editing of the library.
