### ISSUE TITLE
[Tabs] TabBarViewController should be allowed to be embedded in the top appbar

### ISSUE THREAD

**Issue by johnmcconnell** [material-components/material-components-ios#4772]
## Feature Request/Suggestion

The tab bar view controller currently places the tab bar at the bottom of the screen. It should be allowed to be positioned at the top inside the flexible header app bar view controller.

---
#### Internal data
- Associated internal bug: [b/117176851](http://b/117176851)

**Comment by romoore** [comment]
Thanks for the bug report, @johnmcconnell . Would BottomNavigation suit your app's needs instead of using bottom Tabs? Although bottom Tabs are not officially deprecated, less effort has been placed into their maintenance since MDCBottomNavigation was implemented. [Tabs are now focused on the Material Guidelines' "Tabs" use cases.](https://material.io/design/components/tabs.html)

**Comment by jverkoey** [comment]
Hi @johnmcconnell - can you describe in a bit more detail what you've tried to do and what's not working? I'm not aware of any limitations in App Bar that would disallow having another component being added as a subview.

**Comment by johnmcconnell** [comment]
The current implementation will reposition the tab bar to the bottom of the screen when touching a tab.

If you include the tab bar as the bottom view of the app bar

**Comment by romoore** [comment]
@jverkoey He's using the MDCTabBarViewController, which always assumes its going to be at the bottom of the screen. Unfortunately, the VC is no longer actively developed and/because the "bottom tabs" style is replaced with Bottom Navigation.

**Comment by johnmcconnell** [comment]
I agree

**Comment by jverkoey** [comment]
Ah, wild. Ok that's an unfortunate limitation.

**Comment by material-mirror** [comment]
The internal issue [b/117176851](http://b/117176851) is now closed. This issue is being closed as a result.
