### ISSUE TITLE
[MDCNavigationBar] Add backIndicatorImage API to override default image

### ISSUE THREAD

**Issue by gmann1** [material-components/material-components-ios#4777]
## Feature Request/Suggestion

Unable to override the backIndicatorImage on the MDCNavigationBar. However, I recently learned that adding a custom leadingBarButtonItem fixes this problem.

---
#### Internal data
- Associated internal bug: [b/117176692](http://b/117176692)

**Comment by jverkoey** [comment]
The feature request here is to add a `backIndicatorImage` API to MDCNavigationBar, similar to UINavigationBar's equivalent API. This would allow clients to easily change the image of the back button without having to rely on leadingBarButtonItem.

**Comment by material-mirror** [comment]
The internal issue [b/117176692](http://b/117176692) is now closed. This issue is being closed as a result.
