### ISSUE TITLE
[ProgressView] Demo labels have wrong alignment in landscape mode on iOS12

### ISSUE THREAD

**Issue by galiak11** [material-components/material-components-ios#4785]
Progress view labels appear on the right instead of the left on iOS 12 in landscape mode. 
This seems to occur only on iOS12 (tested on: iPhone 8 Plus simulator, iPhoneX simulator & iPhoneX device).
This could potentially be an issue with the progress view component which manifests only on iOS12.

Note: the view being partially covered in iPhoneX devices is tracked by: ["[ProgressView] Demo ignores safe area"](https://github.com/material-components/material-components-ios/issues/3718).

iOS 12 (iPhone X, 8+):
![progress view - iphone x - ios12](https://user-images.githubusercontent.com/2329102/44110190-183a476e-9fcd-11e8-86ae-59e9de787e76.png)

iOS 11.4 (iPhone X, 8+):
![progress view - iphone x - ios11.4](https://user-images.githubusercontent.com/2329102/44110197-219154a6-9fcd-11e8-99a9-5e0be885b8e3.png)

**Comment by romoore** [comment]
I suspect that the layout changes are a result of the VFL for the layout not preferring a leading or trailing edge for the labels. Note in the constraints below that the labels must only be a minimum distance from each edge, and not a fixed distance.

```objectivec
  NSArray *horizontalVisualFormats = @[
    @"H:|-(p)-[stockView]-(p)-|",
    @"H:|-(p)-[tintedView]-(p)-|",
    @"H:|-(p)-[coloredView]-(p)-|",
    @"H:|-(p)-[backwardResetView]-(p)-|",
    @"H:|-(p)-[backwardAnimateView]-(p)-|",
    @"H:|-(>=p)-[stockLabel]-(>=p)-|",
    @"H:|-(>=p)-[tintedLabel]-(>=p)-|",
    @"H:|-(>=p)-[coloredLabel]-(>=p)-|",
    @"H:|-(>=p)-[backwardResetLabel]-(>=p)-|",
    @"H:|-(>=p)-[backwardAnimateLabel]-(>=p)-|",
  ];
```
