### ISSUE TITLE
[Chips] It is difficult to understand how to delete individual chips

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4787]
From the internal report:

> The core issue is that it is difficult to target delete particular chips in the MDCChipField.
>
> Voice supports display a number selecting controller when user taps on a chip, this overlaps with the proposed tapping on chip to display AlertController.

---

This is an internal issue. If you are a Googler, please visit [b/112262983](http://b/112262983) for more details.

**Comment by romoore** [comment]
I don't believe this is client-blocking. The client was provided with mitigation steps but decided to wait until Chips are fully accessible.
