### ISSUE TITLE
[schemes/Color] Umbrella bug for tracking internal client migrations to new color scheme APIs

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4788]
This is an internal issue. If you are a Googler, please visit [b/112284592](http://b/112284592) for more details.

---
#### Internal data
- Associated internal bug: [b/112284592](http://b/112284592)

**Comment by material-mirror** [comment]
The internal issue [b/112284592](http://b/112284592) is now closed. This issue is being closed as a result.
