### ISSUE TITLE
[TextFields] Multiline filled text fields have wrong error color

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#4797]
Probably in other designs too:

![screen shot 2018-08-14 at 6 25 15 pm](https://user-images.githubusercontent.com/1271525/44121894-89a39780-9fef-11e8-824f-88c501e26a75.png)

---
#### Internal data
- Associated internal bug: [b/117176862](http://b/117176862)

**Comment by willlarche** [comment]
I'm not positive. Check the stickersheet for the latest. I can just tell
that it doesn't match and it looks like the old one (I think). Maybe single
line is wrong and it's right.

Will Larche
Software Engineer
Material Design
Google LLC.

**Comment by material-mirror** [comment]
The internal issue [b/117176862](http://b/117176862) is now closed. This issue is being closed as a result.
