### ISSUE TITLE
Update Material.io API docs more frequently

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#4805]
https://material.io/develop/ios/components/bottomnavigation/api-docs/Enums/MDCBottomNavigationBarAlignment.html is a 404, for example.

### Reproduction Steps
1. Navigate to https://material.io/develop/ios/components/bottomnavigation/
2. Click on the link, "Enumeration: MDCBottomNavigationBarAlignment"

<img width="542" alt="screen shot 2018-08-16 at 12 15 23 pm" src="https://user-images.githubusercontent.com/1753199/44220971-17959480-a14e-11e8-8a59-fc39bfc716e3.png">

### Expected Result
Links to a non-404 page

### Actual Result
Links to a 404 page. (https://material.io/develop/ios/components/bottomnavigation/api-docs/Enums/MDCBottomNavigationBarAlignment.html)

---
#### Internal data
- Associated internal bug: [b/117177380](http://b/117177380)

**Comment by romoore** [comment]
Could you please help me undestand:  if the docs are all linking to/from material.io, how does a delayed release process cause problems?  Shouldn't any published version on material.io be self-contained and at least self-consistent? How will publishing more often improve the consistency of the site?

**Comment by jverkoey** [comment]
Our technical documentation links to material.io with the expectation that the material.io site is getting redeployed nightly. This is no longer the case — it's now monthly.

The problem comes from the fact that our links now point to things that may not exist for up to 30 days.

**Comment by romoore** [comment]
I still don't get it - since the source of the link is material.io and the target of the link is material.io, what does it have to do with our release process?

**Comment by romoore** [comment]
Also, what is our "technical documentation" and how does it differ from material.io?

**Comment by jverkoey** [comment]
Internal bug to track this further: [b/112656018](http://b/112656018).

**Comment by material-mirror** [comment]
The internal issue [b/117177380](http://b/117177380) is now closed. This issue is being closed as a result.
