### ISSUE TITLE
[AppBar] Delete MDCAppBarTextColorAccessibilityMutator

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4806]
This API has no internal usage and is a thin wrapper on MDFTextAccessibility.

- [x] Measure internal usage of the API. No internal usage.
- [x] Create a GitHub issue.
- [x] Write a migration guide. No migration guide needed — clients can extract the internal logic if they still require it.
- [x] Annotate the API as "ToBeDeprecated".
- [x] Determine a schedule for the API deletion. No schedule needed.
- [x] Announce that the API will be deprecated. No announcement needed.
- [x] After the deprecation date, deprecate the API.
- [x] After the deletion date, re-evaluate usage of the API.
- [ ] Delete the API and migration guide.

**Comment by randallli** [comment]
The fact that there are no clients of this API is a strong indicator that its not providing value. When we built it we thought that we would have a suite of these to style and ensure the AppBar accessible.

**Comment by jverkoey** [comment]
*nods*

**Comment by jverkoey** [comment]
Note we are seeing warnings in our Swift tests for this:

```
components/AppBar/tests/unit/AppBarAccessibilityMutatorTestColorTest.swift:41:13: warning: 'mutate' is deprecated: Use themers and MDFTextAccessibility instead.
    mutator.mutate(appBar)
            ^
```

These will go away once we delete the API. There is currently no way to suppress our own deprecation warnings in Swift.
