### ISSUE TITLE
[HeaderStackView] Make the component a private component of AppBar

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4812]
We don't intend to support HeaderStackView in any context other than the AppBar, so we'd like to make it a private implementation detail of the AppBar. This will require a multi-step migration of:

- [ ] Move all of the HeaderStackView code into AppBar as a sub-directory, create a new CocoaPods target for it, and point the old HeaderStackView target to the new one.
```
components/AppBar
  src/
    HeaderStackView/
      src/...
      tests/...
```
- [x] There is presently no internal usage, so there shouldn't be any migration work required.
- [ ] Land a release with the component copied over.
- [ ] Delete the old component.

---
#### Internal data
- Associated internal bug: [b/117176530](http://b/117176530)

**Comment by material-mirror** [comment]
The internal issue [b/117176530](http://b/117176530) is now closed. This issue is being closed as a result.
