### ISSUE TITLE
[AppBar/NavigationBar] Documentation Alignment with the spec

### ISSUE THREAD

**Issue by samskiter** [material-components/material-components-ios#4817]
## Feature Request/Suggestion

We had a mix up with our designers over the term 'AppBar' recently. Looking at the spec, what is referred to as the 'App Bar' appears to be what the material-components-ios library calls the 'Navigation Bar' - https://material.io/design/components/app-bars-top.html#

There seems to be no term in the spec for a composite bar containing the Navigation Bar AND other views (e.g. tabs)

It seems that the Spec is in need of 1 more name and then some aligning needs to happen between this library, other libraries and the spec....

---
#### Internal data
- Associated internal bug: [b/117176850](http://b/117176850)

**Comment by romoore** [comment]
Thanks for filing the issue, @samskiter . I agree that sometimes there can be a little ambiguity between the Material Guidelines and specific components built in MDC-iOS.  When we build components, we work closely with our designers to ensure that we're building with as much flexibility as possible while still maintaining Material's unique and opinionated style.   

In this case, I don't  agree that MDCNavigationBar is a Material Top App Bar.  @jverkoey has mentioned on several occasions that MDCNavigationBar is not intended to be used as a stand alone component (Jeff please correct me if I'm wrong). It, along with the Header Stack View and Button Bar are only meant to be used as part of the MDCAppBar.

Reasons why I believe MDCAppBar is Material Top App Bar. 
* Both may have set of navigation elements (MDCNavigationBar) with no other elements while supporting 'hide' behavior.
* MDCAppBar [supports vertically expansion with the navigation elements arranged at the top.](https://material.io/design/components/app-bars-top.html#anatomy) If the title should be bottom-aligned, it can be placed in the lower bar of the AppBar's header stack view.
* I believe the ["Component Behavior" article demonstrates Tabs integration with Top AppBars](https://material.io/design/layout/component-behavior.html#responsive-patterns) although it does not provide redlines or rules of integration - mostly concepts.  [I believe there is an open issue dealing with MDCTabBar integration with MDCAppBar](https://github.com/material-components/material-components-ios/issues/4455).
* The [Tabs article highlights in greater detail (with pictures!) how Tabs and the Top App Bar can be integrated](https://material.io/design/components/tabs.html#usage).  It's not comprehensive, but provides more detail than the AppBars article.

Is there something specific that you think MDC-iOS should do to be better-aligned with the Material Guidelines?  You may want to consider submitting feedback at material.io and request more guidance for how different components should integrate with the App Bars.

**Comment by romoore** [comment]
I think the Tabs article makes it clear that Tabs can be combined with a Top App Bar. From the article,

> *Tabs can be paired with components like top app bars*, or nested in components like cards and sheets" (emphasis added). 
> &mdash; https://material.io/design/components/tabs.html#usage

One of [the Interactions articles also shows Tabs being immediately below an App Bar](https://material.io/design/motion/customization.html#sequencing).  Is your concern that maybe Tabs should not be placed "within" an App Bar and instead should be placed immediately below an App Bar?

**Comment by samskiter** [comment]
@romoore 

>I think the Tabs article makes it clear that Tabs can be combined with a Top App Bar. From the article,

I guess that's a different article so easy to miss it. Also "paired" is ambiguous. I think our designers understand this pairing to mean something different.

I think it would be more useful if the AppBar article said sth like "App bars generally have a top navigation component (ie a navigation bar) and can have loads of extra things in them, like tabs or other views".

**Comment by material-mirror** [comment]
The internal issue [b/117176850](http://b/117176850) is now closed. This issue is being closed as a result.
