### ISSUE TITLE
Consider inverting the structure of our 'standard' CBC examples

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#482]
Right now our samples look like:

ComponentTypicalUseController.m:
@interface ComponentTypicalUseController()
...  // Code demonstrating typical use
ComponentTypicalUseSupplemental.[hm]
@interface ComponentTypicalUseController : UIViewController
... // 'Scaffolding' code

Consider inverting the pattern so ComponentTypicalUseController.[hm] has the main class declaration and definition and the Supplemental is a category or extension with the scaffolding code.

For an example of the new structure, see:
http://codereview.cc/D678

**Comment by ianegordon** [comment]
Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄

**Comment by romoore** [comment]
I'd even prefer to go the opposite way and remove our "Supplemental" files entirely. Too many times I've missed the existence of those files and duplicated a UIVC method or introduced other subtle errors.
