### ISSUE TITLE
[TextFields] Textfield does not work correctly on RTL direction

### ISSUE THREAD

**Issue by doganekici** [material-components/material-components-ios#4820]
When i write new character, earlier characters does not seem

Releated Video:
https://streamable.com/3ycp0

## Platform

 - Device: [e.g. iPhone7]
 - OS: [e.g. iOS11.4.1]

---
#### Internal data
- Associated internal bug: [b/117177758](http://b/117177758)

**Comment by andrewoverton** [comment]
@doganekici - Thanks for filing the bug, and extra thanks for including the video! Is there any more information you can provide as to how I could reproduce this? I tried to using in the "Material Filled Text Field" example in our MDCDragons app and wasn't able to. See the video here: https://streamable.com/bzmzf

**Comment by doganekici** [comment]
I sharing sample code. 
material-components-ios release version : v60.0.0

`  MDCTextField *textFieldUnderline = [[MDCTextField alloc] init];
    textFieldUnderline.frame = CGRectMake(0, 0, 300, 300);
    textFieldUnderline.center = self.view.center;
    [self.view addSubview:textFieldUnderline];
    self.textFieldControllerUnderline =
    [[MDCTextInputControllerUnderline alloc] initWithTextInput:textFieldUnderline];
    self.textFieldControllerUnderline.placeholderText = @"Underline";
    [self.textFieldControllerUnderline setErrorText:@"Error" errorAccessibilityValue:@"accesibility"];`

And I encountered a similar problem. When run same code on LTR direction. i write full text inside textfield. After i start to delete. i can not see the first characters.
https://streamable.com/aul1o

**Comment by andrewoverton** [comment]
@doganekici I looked at this a bit more today... I put your code snippet in an empty view controller and was able to reproduce the bug where the backspace stops working before you get to the beginning of the text. When I made the height 100 instead of 300 the bug wasn't there. Very strange. Still looking into it. Just wanted to give you an update.

**Comment by material-mirror** [comment]
The internal issue [b/117177758](http://b/117177758) is now closed. This issue is being closed as a result.
