### ISSUE TITLE
BottomNavigation should provide a way to get to the viewItems in order to connect to feature highlight

### ISSUE THREAD

**Issue by randallli** [material-components/material-components-ios#4824]
## Feature Request/Suggestion
How do I use FeatureHighlight on a MDCBottomNavigationBar?

I need the internal itemView, which is not exposed.

Can we add a method 
- (UIView *)viewForItem:(UITabBarItem *)item;

## Additional context

more info in internal yaqs/6188300342919168

**Comment by andrewoverton** [comment]
I think this will make https://github.com/material-components/material-components-ios/issues/2833 much easier to address

**Comment by romoore** [comment]
Regarding #2833, I don't think we should expect clients to be modifying the properties of these views. For that one, I think we could add `mdc_badgeTextColor` to UITabBarItem or something similar. That way clients can treat the badge text color the same way as all of the other UI customizations.
