### ISSUE TITLE
[AppBar] Add delegate to MDCAppBarNavigationController initWithRootViewController API

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4846]
From the internal bug ([b/112107844](http://b/112107844)):

> Styling delegate doesn't get called when MDCAppBarNavigationController is initialized with root view controller, since rootViewController has app bar added before delegate can be set.
> 
> CODE FRAGMENT
> 
> ```
> @implementation MyViewController
> 
> + (void)presentMenu
>   MyViewController *myViewController = [MyViewController alloc] init];
>   MDCAppBarNavigationController *navController =
>       [[MDCAppBarNavigationController alloc] initWithRootViewController:myViewController];
>   navController.delegate = myViewController;
>   debugController.navigationItem.leftBarButtonItem =
>       [[UIBarButtonItem alloc] initWithTitle:@"Close"
>                                        style:UIBarButtonItemStyleDone
>                                       target:debugController
>                                       action:@selector(userDidTapCancelButton:)];
>   navController.modalPresentationStyle = UIModalPresentationFormSheet;
>   [[UIViewController currentViewController] presentViewController:navController
>                                                          animated:YES
>                                                        completion:nil];
> }
> 
> - (void)appBarNavigationController:(MDCAppBarNavigationController *)navigationController
>                      willAddAppBar:(MDCAppBar *)appBar
>            asChildOfViewController:(UIViewController *)viewController {
>   MDCSemanticColorScheme *scheme = [[MDCSemanticColorScheme alloc] init];
>   [MDCAppBarColorThemer applySemanticColorScheme:scheme toAppBar:appBar];
> }
> ```

---

This is an internal issue. If you are a Googler, please visit [b/112107844](http://b/112107844) for more details.

The resolution to this is to provide a new designated initializer for MDCAppBarNavigationController that requires a non-nil delegate to be provided.

---
#### Internal data
- Associated internal bug: [b/112107844](http://b/112107844)

**Comment by material-mirror** [comment]
The internal issue [b/112107844](http://b/112107844) is now closed. This issue is being closed as a result.
