### ISSUE TITLE
[ShadowLayer] cornerRadius changes don't render

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#4848]
Changing the cornerRadius of an MDCShadowLayer does not cause them to render with the updated value.

This is reproducible in the Dragons app in the Shadow - Shadow Corner Radius example.

Drag the slider to adjust the corner radius of the shadowed view, but notice the rendering isn't affected.
However, if you rotate the screen, this will cause a layoutSubview invocation which will correctly cause the rendering to be correct.

We *cannot* simply add a cornerRadius property to MDCShadowLayer that set _shadowPathIsInvalid to YES and calls setNeedsLayout.  Doing so causes an endless loop in some of our examples.
Run Test from the MDCCatalog workspace to reproduce this failure.

Additional context: [b/116333193](http://b/116333193).

Internal tracking bug: [b/117176591](http:/b/117176591).

**Comment by jverkoey** [comment]
The proposed fix was rolled back in https://github.com/material-components/material-components-ios/pull/5231.

**Comment by ianegordon** [comment]
An internal team has asked for a resolution on this.

**Comment by jverkoey** [comment]
Escalated the bug internally as well [b/117176591](http:/b/117176591).

**Comment by material-mirror** [comment]
The internal issue [b/117176591](http://b/117176591) is now closed, closing this issue.
