### ISSUE TITLE
[Catalog] CBCViewControllerFromClass should handle .storyboard filenames

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#485]
If you return MyExample.storyboard instead of MyExample from catalogStoryboardName this will assert.
We could be a bit more forgiving and truncate any .storyboard if it exists in the returned string.

**Comment by willlarche** [comment]
@jverkoey , is this really for us or CBC project?

**Comment by jverkoey** [comment]
For CBC

**Comment by ianegordon** [comment]
Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄

**Comment by jverkoey** [comment]
Reopened this in CbyC: https://github.com/material-foundation/cocoapods-catalog-by-convention/issues/32
