### ISSUE TITLE
[ActivityIndicator] Determinate AI fails to render if progress set immediately after calling startAnimation

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#4854]
When creating a new MDCActivityIndicator and setting it to `.determinate` mode, if the value of `progress` is assigned immediately after calling `startAnimation` and before that animation completes, then the Activity Indicator will show its initial animation and then "disappear".

## Steps to reproduce

```objectivec
 self.activityIndicator3 = [[MDCActivityIndicator alloc] init];
  self.activityIndicator3.delegate = self;
  self.activityIndicator3.indicatorMode = MDCActivityIndicatorModeDeterminate;
  self.activityIndicator3.cycleColors =  @[ [MDCPalette bluePalette].tint500,
                                            [MDCPalette redPalette].tint500,
                                            [MDCPalette greenPalette].tint500,
                                            [MDCPalette yellowPalette].tint500 ];
  [self.activityIndicator3 sizeToFit];
  [self.activityIndicator3 startAnimating];
  self.activityIndicator3.progress = 0.6f;
```

## Steps to succeed

```objectivec
 self.activityIndicator3 = [[MDCActivityIndicator alloc] init];
  self.activityIndicator3.delegate = self;
  self.activityIndicator3.indicatorMode = MDCActivityIndicatorModeDeterminate;
  self.activityIndicator3.cycleColors =  @[ [MDCPalette bluePalette].tint500,
                                            [MDCPalette redPalette].tint500,
                                            [MDCPalette greenPalette].tint500,
                                            [MDCPalette yellowPalette].tint500 ];
  [self.activityIndicator3 sizeToFit];
  self.activityIndicator3.progress = 0.6f; // Swapped
  [self.activityIndicator3 startAnimating]; // Swapped
```

To see the effect, note the third Activity Indicator (rightmost) in the videos below.

|Failure|Success|
|--|--|
|![ai-failures](https://user-images.githubusercontent.com/1753199/44376348-1950b680-a4c6-11e8-98f5-065a820eaed5.gif)|![ai-success](https://user-images.githubusercontent.com/1753199/44376372-3dac9300-a4c6-11e8-977f-79dbd4aef9a8.gif)|

---
#### Internal data
- Associated internal bug: [b/117176297](http://b/117176297)

**Comment by material-mirror** [comment]
The internal issue [b/117176297](http://b/117176297) is now closed. This issue is being closed as a result.
