### ISSUE TITLE
[ProgressView] Automatic trackTintColor does not work when progressColor is greyscale

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#4862]
When the `progressTintColor` color is in the greyscale color space (having only white and alpha channels), the `trackTintColor` defaulting behavior does not work correctly. Because the default behavior relies on a 4-channel color space (HSB+Alpha), greyscale colors will fail and `clearColor` will be used instead.

The work-around is for clients to assign a custom color for the `trackTintColor` instead of relying on the "default" behavior.

**Example Code**

Taken from `ProgressViewExample.m`

```objectivec
 _tintedProgressView = [[MDCProgressView alloc] init];
  _tintedProgressView.translatesAutoresizingMaskIntoConstraints = NO;
  [self.view addSubview:_tintedProgressView];
  _tintedProgressView.progressTintColor = [UIColor colorWithWhite:0.12 alpha:1];
  // Reset the track tint color to be based off of the progress tint color.
  _tintedProgressView.trackTintColor = nil;
  // Hide the progress view at setup time.
  _tintedProgressView.hidden = YES;
```

**Result**
The top progress view has a grayscale color for `progressTintColor` and its progress is synchronized with the bottom (yellow and green) progress view. Note the lack of `trackTintColor` and that there is no visible progress ("filling" effect).

![mdc-pv-bug](https://user-images.githubusercontent.com/1753199/44404209-68c5cf80-a524-11e8-92a1-43088d145839.gif)

---
#### Internal data
- Associated internal bug: [b/117176214](http://b/117176214)

**Comment by material-mirror** [comment]
The internal issue [b/117176214](http://b/117176214) is now closed. This issue is being closed as a result.
