### ISSUE TITLE
[Snackbar] Expose the category property in MDCSnackbarMessageView

### ISSUE THREAD

**Issue by yarneo** [material-components/material-components-ios#4864]
When using the delegate `willPresentSnackbarWithMessageView` we pass the `MDCSnackbarMessageView` for styling but there is no way to identify what "type" of message is passed.   The client does not need to identify individual messages, but does need to separate them into different categories for theming.

A good solution would be to expose the `category` property that exists in `MDCSnackbarMessage` so the snackbar can be easily identified.

---
#### Internal data
- Associated internal bug: [b/117176717](http://b/117176717)

**Comment by jverkoey** [comment]
Would it be reasonable to pass the `MDCSnackbarMessage` instance?

**Comment by romoore** [comment]
The SnackbarMessage instance is a copy of the original and we've avoided exposing it in the past. Is there a reason why we might want to expose more than the category in this case?  Do we have other client requests that would also be solved by exposing the message property?

**Comment by romoore** [comment]
The actual client request is to distinguish between different "types" of messages being presented by the Snackbar manager. They don't need to know the exact message any given time, just whether it was flagged as something like "notification", "warning", "error", or other way of categorizing messages.

**Comment by romoore** [comment]
I've updated the description to provide a bit more context about the client request.

**Comment by material-mirror** [comment]
The internal issue [b/117176717](http://b/117176717) is now closed. This issue is being closed as a result.
