### ISSUE TITLE
Catalog root view controller cells don't maintain their highlighted state during dismissal

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#487]
Repro steps:
1. Tap a cell.
2. Tap back.

Expected behavior: the tapped cell unhighlights as the pushed view controller is dismissed.
Actual behavior: no cell is highlighted.

The reason this is important is that it provides an indication of where the user came from in relation to the rest of the root content. You can observe this behavior in standard UIKit applications. We should provide the same functionality here in order to both be consistent with the platform and to provide this context.

The following screenshot is the expected initial state of the view controller when the pushed view controller is dismissed:
![simulator screen shot may 4 2016 5 10 12 pm](https://cloud.githubusercontent.com/assets/45670/15029349/222dc9fe-121b-11e6-9e93-d44f2685c90f.png)

---
#### Internal data
- Associated internal bug: [b/117179214](http://b/117179214)

**Comment by material-mirror** [comment]
The internal issue [b/117179214](http://b/117179214) is now closed. This issue is being closed as a result.
