### ISSUE TITLE
[Icons] Layered Icons

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4873]
From the internal bug:

> We would like to add a circle behind the selected icon (in Cards) so it can be presented over images or other irregular backgrounds.
> That will require creating a layered icon with background and foreground images.
> 
> 1. The size of the background fill circle should be the same as the selected circle icon.
> 2. The color mapping should be, Primary for the selected icon, and surface for the background fill
> 3. We should use the primary color for the selected overlay (in Cards), as opposed to the surface color which seems to be the current implementation.

---

This is an internal issue. If you are a Googler, please visit [b/112072315](http://b/112072315) for more details.

---
#### Internal data
- Associated internal bug: [b/112072315](http://b/112072315)

**Comment by jverkoey** [comment]
Un-assigning due to inactivity. Please re-assign if you are still working on this.

**Comment by material-mirror** [comment]
The internal issue [b/112072315](http://b/112072315) is now closed. This issue is being closed as a result.
