### ISSUE TITLE
[ButtonBar] Evaluate how UIKit handles pure Swift class target/actions in extensions

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4880]
Example setup:

```swift
class SomeObject {
  @objc func someEvent() {

  }
}

let object = SomeObject()

self.navigationItem.rightBarButtonItem =
  UIBarButtonItem(title: "Right", style: .done, target: object, action: #selector(SomeObject.someEvent))
```

Tap the button in an extension.

We need to determine what the expected behavior is.

---
#### Internal data
- Associated internal bug: [b/117176528](http://b/117176528)

**Comment by material-mirror** [comment]
The internal issue [b/117176528](http://b/117176528) is now closed. This issue is being closed as a result.
