### ISSUE TITLE
[TextFields] Perform accessibility usability study and come up with recommendations

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#4882]
## Feature Request/Suggestion
TextField accessibility is complicated and there are no clear "best" solutions. Let's work with our internal research and stakeholder groups to find a good solution with backing data.

---
#### Internal data
- Associated internal bug: [b/117176625](http://b/117176625)

**Comment by material-mirror** [comment]
The internal issue [b/117176625](http://b/117176625) is now closed. This issue is being closed as a result.
