### ISSUE TITLE
[Slider] Support different Thumb radius for UIControlState

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#4883]
## Feature Request/Suggestion

The MDCSlider thumb should support changing size (radius) for each UIControlState value.

For example:
* Disabled: 2 points
* Normal: 6 points
* Selected: 10 points

---
#### Internal data
- Associated internal bug: [b/117176821](http://b/117176821)

**Comment by material-mirror** [comment]
The internal issue [b/117176821](http://b/117176821) is now closed. This issue is being closed as a result.
