### ISSUE TITLE
[Snackbar] Should not be dismissable when a user taps outside the button

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4887]
From the internal report:

> Snackbars should not allow dismissal when the non-button area is activated.  MDC-iOS should remove the dismiss gesture recognizer from the Snackbar's non-button area. 

---

This is an internal issue. If you are a Googler, please visit [b/113074384](http://b/113074384) for more details.

---
#### Internal data
- Associated internal bug: [b/113074384](http://b/113074384)

**Comment by material-mirror** [comment]
The internal issue [b/113074384](http://b/113074384) is now closed. This issue is being closed as a result.
