### ISSUE TITLE
MDCTextField: VoiceOver reads the whole name of the input when entering first character

### ISSUE THREAD

**Issue by jcalabek** [material-components/material-components-ios#4893]
VoiceOver reads the whole name of the input field after I enter the first character, for the second and following characters all seems good.

## Reproduction steps

1. Enable VoiceOver
2. Activate input filed with with label - in our case Create username
3. Enter first character of a given username - in our case "f"

## Expected behavior

VoiceOver reads "f"

## Actual behavior

VoiceOver reads "Create username"

## Platform (please complete the following information)

 - Device: iPhone X
 - OS: iOS 11.4.1

## Additional context

This seems like a bug in MDCTextField.m. If we comment out custom `-accessibilityValue` method this problem goes away.

![screen_setup](https://user-images.githubusercontent.com/12100913/44601259-e51d1480-a7a9-11e8-8c85-e8026aaab810.png)

---
#### Internal data
- Associated internal bug: [b/117176846](http://b/117176846)

**Comment by material-mirror** [comment]
The internal issue [b/117176846](http://b/117176846) is now closed. This issue is being closed as a result.
