### ISSUE TITLE
[NavigationDrawer] Move away from MDCDeviceTopSafeAreaInset

### ISSUE THREAD

**Issue by yarneo** [material-components/material-components-ios#4900]
We should remove all `MDCDeviceTopSaveAreaInset` calls and change them to use safeAreaInsets as this is a soon to be deprecated API.

---
#### Internal data
- Associated internal bug: [b/117177500](http://b/117177500)

**Comment by material-mirror** [comment]
The internal issue [b/117177500](http://b/117177500) is now closed. This issue is being closed as a result.

**Comment by material-mirror** [comment]
The internal issue [b/117177500](http://b/117177500) is now closed. This issue is being closed as a result.

**Comment by material-mirror** [comment]
The internal issue [b/117177500](http://b/117177500) is now closed. This issue is being closed as a result.
