### ISSUE TITLE
[Slider] StatefulAPI and Storyboards don't work

### ISSUE THREAD

**Issue by codeman7** [material-components/material-components-ios#4918]
A slider created within a Storyboard is not visible if statefulAPIEnabled is set to YES.

1. Create a storyboard
2. Add a slider to it
3. Wire that slider to a view controller
4. Within the view controller set `statefulAPIEnabled` to `YES`. 

## Expected behavior

We expect that this has no effect on rendering.

## Actual behavior

You can no longer see the slider.

## Platform (please complete the following information)

 - Device: iPhone X
 - OS: iOS 11

---
#### Internal data
- Associated internal bug: [b/117176008](http://b/117176008)

**Comment by material-mirror** [comment]
The internal issue [b/117176008](http://b/117176008) is now closed. This issue is being closed as a result.
