### ISSUE TITLE
[Snackbar] Document steps to make Snackbar messages accessible

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#4922]
## Feature Request/Suggestion
Snackbar messages should support UIAccessibility. Document how to:

* Set the `accessibilityLabel` or `accessibilityHint` of the title message (it's a button)
* Set the `accessibilityLabel` or `accessibilityHint` of the action button
* Theme the message view so that colors provide sufficient contrast

---
#### Internal data
- Associated internal bug: [b/117176845](http://b/117176845)

**Comment by material-mirror** [comment]
The internal issue [b/117176845](http://b/117176845) is now closed. This issue is being closed as a result.
