### ISSUE TITLE
[BottomAppBar] Shadow is flaky

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#4929]
The BottomAppBar shadow is flaky and causing problems with our screenshot testing.

Here's an image of the problematic shadow. Since our tests don't interact, just loading the VC, I think it's a component problem.

![screen shot 2018-08-28 at 3 32 30 pm](https://user-images.githubusercontent.com/1753199/44746403-46115900-aad8-11e8-8688-7e6612cb0a4d.png)

**Comment by romoore** [comment]
The same component has similar flakes in other internal tests. The component definitely has a flaky shadow.

**Comment by romoore** [comment]
We also have flaky tests in another project using our component but not our VC/example code.

**Comment by material-mirror** [comment]
The internal issue [b/114025293](http://b/114025293) is now closed, closing this issue.
