### ISSUE TITLE
Disable codecov comments on our pull requests

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4943]
The generated codecov comments are mostly noise at this point and we're not currently measuring our public code coverage in any meaningful way. We should disable the comments it generates until we deem it to be an important enough tool to re-enable and ensure that it's generating meaningful information.

**Comment by romoore** [comment]
Can you clarify a bit? I'm really confused about all this stuff on codecov. What do you mean by "disabling comments"?  I think that tracking code coverage on the `develop` branch is still valuable - why do we think we don't want it anymore?

**Comment by jverkoey** [comment]
Code coverage posts a comment to all of our pull requests. I am not convinced that these comments are providing value right now and I would like to reduce the noise generated by the tool. The way to do that is to stop posting coverage as part of our presubmits. We can continue generating coverage for our continuous integration.

**Comment by romoore** [comment]
Thanks!
