### ISSUE TITLE
[Collections] MDCCollectionViewCell loses accessory view in prepareForReuse

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4958]
From the internal bug:
> The accessoryView should only be removed from the superview if the superview is the cell itself.

---

This is an internal issue. If you are a Googler, please visit [b/113503074](http://b/113503074) for more details.

---
#### Internal data
- Associated internal bug: [b/113503074](http://b/113503074)

**Comment by material-mirror** [comment]
The internal issue [b/113503074](http://b/113503074) is now closed. This issue is being closed as a result.
