### ISSUE TITLE
[TextFields] Entering english while in RTL locale causes overlap with clear button.

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4959]
This is an internal issue. If you are a Googler, please visit [b/113335991](http://b/113335991) for more details.

---
#### Internal data
- Associated internal bug: [b/113335991](http://b/113335991)

**Comment by andrewoverton** [comment]
I think this was reopened accidentally. https://github.com/material-components/material-components-ios/pull/4974 closed it.

**Comment by jverkoey** [comment]
The internal issue is not yet closed, re-opening this issue. Googler: please check the state of the internal issue and update it accordingly.

**Comment by jverkoey** [comment]
The internal bug reported that this issue is still reproducible.

**Comment by jverkoey** [comment]
Un-assigning this bug due to inactivity by the assignee. Please re-assign yourself if you are working on this issue.

**Comment by material-mirror** [comment]
The internal issue [b/113335991](http://b/113335991) is now closed. This issue is being closed as a result.
