### ISSUE TITLE
[Snackbar] Expose accessibility identifier MDCSnackbarMessageTitleAutomationIdentifier

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4960]
This is an internal issue. If you are a Googler, please visit [b/113321564](http://b/113321564) for more details.

---
#### Internal data
- Associated internal bug: [b/113321564](http://b/113321564)

**Comment by mgwatt0521** [comment]
Hello! Implementing this will be helpful for a project I'm working on that uses this component, and I think it might be helpful to others too. I've never contributed to open source before, but I think this might be a good issue to start getting into that space. Worth opening a PR?

Thanks

**Comment by material-mirror** [comment]
The internal issue [b/113321564](http://b/113321564) is now closed. This issue is being closed as a result.
