### ISSUE TITLE
When scroll up then bottomSheet not stick to bottom view using MDCBottomSheetController

### ISSUE THREAD

**Issue by SamboVisal** [material-components/material-components-ios#4983]
> For usage questions: ask on [Stack  Overflow](https://stackoverflow.com/questions/tagged/material-components+ios).

## Expected behavior

I really enjoy this library, but today i am having a small problem is that when i started using MDCBottomSheetController and when it shown up and when i want to scroll up then the view is not stick to bottom. I don't know how to figure it out. Here is my sample code:
`let viewController: UIViewController = UIViewController()`
`viewController.view.backgroundColor = .red`
`let bottomSheet: MDCBottomSheetController = MDCBottomSheetController(contentViewController: viewController)`
`self.present(bottomSheet, animated: true, completion: nil)`

 

## Actual behavior

This is what happended [https://ibb.co/eVLBXz](url)
As you can see, the red view is not stick to bottom when i scroll up. 
What another trick if i don't want to able user scroll up but let user to scroll down to dismiss that bottomSheetView.
How can i achieve something like this?

## Platform (please complete the following information)

 - Device: [e.g. iPhoneX]
 - OS: [e.g. iOS11]

## Additional context

---
#### Internal data
- Associated internal bug: [b/117175869](http://b/117175869)

**Comment by mats-claassen** [comment]
This issue is still happening. Is there a fix or workaround for this?

**Comment by material-mirror** [comment]
The internal issue [b/117175869](http://b/117175869) is now closed. This issue is being closed as a result.
