### ISSUE TITLE
[Ink] Flaky test should be disabled

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#4996]
https://fusion.corp.google.com/runanalysis/buildlogs/prod%3AMaterialComponents_iOS%2Fmacos_external%2Fpresubmit_bazel_xcode_900/prod%3AMaterialComponents_iOS%2Fmacos_external%2Fpresubmit_bazel_xcode_900/KOKORO/0c47d694-1903-44bf-a6d3-fba07e36d8ef/1535746380139/prod%3AMaterialComponents_iOS%2Fmacos_external%2Fpresubmit_bazel_xcode_900%20Build%20%232229/Targets

```
Test Case '-[MDCInkLayerTests testEndAnimationTimingInTimeScaledLayer]' started.
components/Ink/tests/unit/MDCInkLayerTests.m:155: error: -[MDCInkLayerTests testEndAnimationTimingInTimeScaledLayer] : ((animation.beginTime) equal to (startTime) +/- (0.010)) failed: ("600.575361263") is not equal to ("600.60193859") +/- ("0.01")
Test Case '-[MDCInkLayerTests testEndAnimationTimingInTimeScaledLayer]' failed (0.070 seconds).
```

---
#### Internal data
- Associated internal bug: [b/117176207](http://b/117176207)

**Comment by material-mirror** [comment]
The internal issue [b/117176207](http://b/117176207) is now closed. This issue is being closed as a result.
