### ISSUE TITLE
Catalog Grid Example "Update styles" button is invisible

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#501]
![simulator screen shot may 9 2016 9 51 11 pm](https://cloud.githubusercontent.com/assets/45670/15133382/5169d0dc-1630-11e6-874d-1b87e15f467f.png)
![simulator screen shot may 9 2016 9 51 44 pm](https://cloud.githubusercontent.com/assets/45670/15133384/545d60d8-1630-11e6-9c8c-55518690201f.png)

**Comment by romoore** [comment]
This is visible as of 27.0.0, though there's a bug in the overlap.

![grid-example-overlap](https://user-images.githubusercontent.com/1753199/28380192-68b5bf48-6c84-11e7-9307-5d17ead353e4.png)
