### ISSUE TITLE
Implement a speed dial component

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5010]
This is an internal issue. If you are a Googler, please visit [b/112254950](http://b/112254950) for more details.

---
#### Internal data
- Associated internal bug: [b/112254950](http://b/112254950)

**Comment by jverkoey** [comment]
Un-assigning due to inactivity. Please re-assign if you are still working on this.

**Comment by material-mirror** [comment]
The internal issue [b/112254950](http://b/112254950) is now closed. This issue is being closed as a result.

**Comment by zakdances** [comment]
Is this permanently closed or just waiting for a contributor...?
