### ISSUE TITLE
[BottomAppBar] Enable customizing the positioning of the FAB

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5011]
This is an internal issue. If you are a Googler, please visit [b/74110942](http://b/74110942) for more details.

**Comment by wenyuzhang666** [comment]
API implemented in https://github.com/material-components/material-components-ios/commit/766a6a7697c755e6cbd012da8339e5536bd1b6ae.

**Comment by jverkoey** [comment]
The internal issue is not yet closed, re-opening this issue. Googler: please check the state of the internal issue and update it accordingly.
