### ISSUE TITLE
[BottomAppBar] FAB centerY should equal the top edge of the app bar

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#5012]
The centerY of the FAB should equal the top edge of the BottomAppBar.  The cut out (inset) is optional.

https://material.io/design/components/app-bars-bottom.html#specs

<img width="820" alt="screen shot 2018-09-05 at 10 20 00 am" src="https://user-images.githubusercontent.com/1753199/45099438-4374bc00-b0f5-11e8-9284-0b4b45b6d53b.png">

Related to #5011

**Comment by wenyuzhang666** [comment]
Fixed in https://github.com/material-components/material-components-ios/commit/766a6a7697c755e6cbd012da8339e5536bd1b6ae
