### ISSUE TITLE
[TextFields] MDCTextInputController inconsistent handling of underline label font and floating placeholder font

### ISSUE THREAD

**Issue by JessBattrick** [material-components/material-components-ios#5036]
> For usage questions: ask on [Stack  Overflow](https://stackoverflow.com/questions/tagged/material-components+ios).

## Reproduction steps

1. Create an MDCTextInput, with a MDCTextInputControllerUnderline, with placeholder text and helperText.
2. Create a second MDCTextInput, using the same controller, but with a different font size.
3. Observe.  The floating placeholder for both text inputs is scaled, accordingly with the MDCTextInput.font.  However, the helper text is not.

## Expected behavior

This occurs because MDCTextInputFloatingPlaceholder uses a floatingPlaceholderScale, but MDCTextInputController does not use a scale for the leadingUnderlineLabel.  While the leadingUnderlineLabel's size can be adjusted using the leadingUnderlineLabelFont, the inconsistencies in the handling seems unnatural.

## Actual behavior

When no leadingUnderlineLabelFont is specified, can a scale be used for the leadingUnderlineLabel font size as well, so that there is more consistency in the behavior?

## Platform (please complete the following information)

Any device / iOS version

---
#### Internal data
- Associated internal bug: [b/117176283](http://b/117176283)

**Comment by willlarche** [comment]
@JessBattrick , that link doesn't go to an SO question. Just the tag's list. Can you add the question's link when you get a chance?

**Comment by willlarche** [comment]
@JessBattrick , clarification, are you use the same instance of a controller or another controller that is just pretty much identical.

**Comment by JessBattrick** [comment]
There should not be a SO question linked.  All details are described in the bug report.

I am using an instance of a MDCTextInputControllerUnderline.

**Comment by willlarche** [comment]
Ha. That's our template I misread. Sorry.

**Comment by willlarche** [comment]
And what I meant about the controllers was, are you using one controller instance for 2 text fields? Or a controller instance for each text field?

**Comment by JessBattrick** [comment]
Each text field has their own controller.  Though the issue happens when there is only one text field, but the issue is more evident when using multiple text fields (the creation of two text fields with different font sizes was more to illustrate that the placeholder text is scaled, and and the underline text is not).

**Comment by material-mirror** [comment]
The internal issue [b/117176283](http://b/117176283) is now closed. This issue is being closed as a result.
