### ISSUE TITLE
Use GitHub permalinks to link to code in our readmes rather than inline code

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5037]
See https://twitter.com/PhilippSpiess/status/1037814891971862528 for an example of how to make a permalink.

Example of what a permalink looks like on GitHub:

https://github.com/material-components/material-components-ios/blob/b662fa5913ae587bc2527e1b80cf2fbe0677995e/components/FlexibleHeader/examples/FlexibleHeaderTypicalUseExample.m#L54-L61

This issue is a proposal to migrate all of our technical docs to make use of permalink code snippets instead of hand-written code.

A potential challenge: permalinks are inherently locked to a specific commit, so the code won't auto-magically update as we change the source; we'll have to update the permalinks in some manner.

---
#### Internal data
- Associated internal bug: [b/117176206](http://b/117176206)

**Comment by romoore** [comment]
Doesn't this run the risk of the docs being outdated if the behavior being linked is no longer valid? Since the old commit could capture outdated API usage (for example), I'm not sure this would be better than hand-documenting code.  Is there a way to link to method or function names?

**Comment by jverkoey** [comment]
We could consider creating one and making it part of our presubmits.

**Comment by romoore** [comment]
You mean a PR against GitHub?

**Comment by jverkoey** [comment]
Nope, I mean CI tooling that checks or updates our permalinks against the code in some manner.

**Comment by material-mirror** [comment]
The internal issue [b/117176206](http://b/117176206) is now closed. This issue is being closed as a result.
