### ISSUE TITLE
[AppBar] Document how to set up an App Bar when using a custom UITableView (not UITableViewController)

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5054]
When the view controller first appears the table view's content inset.y needs to be set to `-contentInset.top`.

---
#### Internal data
- Associated internal bug: [b/117144079](http://b/117144079)

**Comment by material-mirror** [comment]
The internal issue [b/117144079](http://b/117144079) is now closed. This issue is being closed as a result.
