### ISSUE TITLE
[MDCProgressView] Add a way to add Indeterminate linear progress indicator

### ISSUE THREAD

**Issue by bond-** [material-components/material-components-ios#5066]
## Feature Request/Suggestion
As per the documentation or code currently there is no way to do this. Please make this possible.

## Additional context
See Indeterminate linear progress indicator on https://material.io/design/components/progress-indicators.html#linear-progress-indicators

**Comment by andrewoverton** [comment]
Thanks for filing this issue @bond- ! It seems to be a duplicate of https://github.com/material-components/material-components-ios/issues/5066, so what I'm going to do is close this one and we can eventually address that other one.

**Comment by bond-** [comment]
@andrewoverton Did you use the wrong ticket for duplicate?

#5066 is this issue.

**Comment by andrewoverton** [comment]
Yes! Fixed. Thanks @bond-
