### ISSUE TITLE
[Ink] pod MaterialComponents/Ink+Extensions does not exist

### ISSUE THREAD

**Issue by bond-** [material-components/material-components-ios#5067]
Pod MaterialComponents/Ink+Extensions doesn't exist when I do a pod install with versions 62.1.0 or 62.2.0

Please update the website https://material.io/develop/ios/components/ink/ with the right documentation.

**Comment by andrewoverton** [comment]
@jverkoey , is the issue here that the `"Ink+Extensions"` subspec was taken out of MaterialComponents.podspec or that material.io was not updated to reflect that it was taken out?

**Comment by jverkoey** [comment]
Looks like our docs are out of date. We replaced the "Extensions" targets with individual targets for the different themers and our docs need to be updated accordingly.

**Comment by andrewoverton** [comment]
I'll fix the readmes, thanks @jverkoey

**Comment by andrewoverton** [comment]
@bond- , try `Ink+ColorThemer` and you should be good 👍
