### ISSUE TITLE
[Tabs] MDCItemBar should make `_collectionView` a class extension property

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#5085]
In #5071, unit testing required KVC because `_collectionView` is an iVar and not a property on `MDCItemBar`. By transforming it into a property within a class extension, the unit tests can expose this property in a testing category and make use of it. If the class implementation removes the property, then the unit tests will fail at compile time rather than at run time.

---
#### Internal data
- Associated internal bug: [b/117139111](http://b/117139111)

**Comment by material-mirror** [comment]
The internal issue [b/117139111](http://b/117139111) is now closed. This issue is being closed as a result.
