### ISSUE TITLE
[Ink][Masked Transitions] HTTP 404 and broken links

### ISSUE THREAD

**Issue by bond-** [material-components/material-components-ios#5087]
Links to components:
- https://material.io/develop/ios/components/ink/
- https://material.io/develop/ios/components/masked-transitions/

Links not working:
- **Material Design guidelines: Radial Action** (https://material.io/design/animation/responsive-interaction.html#responsive-interaction-radial-action)
- **Material Design guidelines: Radial Transformations** (https://material.io/design/#transforming-material-radial-transformation)
- **API: MDCMaskedTransition** (https://material.io/develop/ios/components/masked-transitions/api-docs/Classes/MDCMaskedTransition.html)

Missing image on https://material.io/develop/ios/components/page-controls/ for **Open bugs badge**

---
#### Internal data
- Associated internal bug: [b/117138884](http://b/117138884)

**Comment by material-mirror** [comment]
The internal issue [b/117138884](http://b/117138884) is now closed. This issue is being closed as a result.
