### ISSUE TITLE
Decide on CGFloat constants being single- or double-precision values

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5095]
From the internal issue:

> The MDC-iOS code base does not treat CGFloat values consistently. We should decide whether we will initialize all CGFloat constants with single-precision numbers (e.g., 0.1f) or double-precision values (e.g., 0.1). Of note, using double-precision values requires explicit casts to CGFloat due to loss of precision on 32-bit architectures (e.g., (CGFloat)0.2 )

---

This is an internal issue. If you are a Googler, please visit [b/114721201](http://b/114721201) for more details.

---
#### Internal data
- Associated internal bug: [b/114721201](http://b/114721201)

**Comment by material-mirror** [comment]
The internal issue [b/114721201](http://b/114721201) is now closed. This issue is being closed as a result.
