### ISSUE TITLE
Internal issue: b/114174218

### ISSUE THREAD

**Issue by andrewoverton** [material-components/material-components-ios#5097]
This is an internal issue. If you are a Googler, please visit [b/114174218](http://b/114174218) for more details.

**Comment by andrewoverton** [comment]
Closed via https://github.com/material-components/material-components-ios/pull/5098

**Comment by jverkoey** [comment]
The internal issue is not yet closed, re-opening this issue. Googler: please check the state of the internal issue and update it accordingly.

**Comment by andrewoverton** [comment]
I just closed the internal issue
