### ISSUE TITLE
[Tabs] Tab indicator doesn't use the correct motion

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5108]
From the internal issue:

> This is more of a nitpick, but certainly a feature that makes the component look more polished.

---

This is an internal issue. If you are a Googler, please visit [b/115485313](http://b/115485313) for more details.

---
#### Internal data
- Associated internal bug: [b/115485313](http://b/115485313)

**Comment by material-mirror** [comment]
The internal issue [b/115485313](http://b/115485313) is now closed. This issue is being closed as a result.
