### ISSUE TITLE
[Tabs] Tab indicator dragging behind tabs

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5109]
From the internal issue:

> There is currently no possibility to have the tab indicator movement be synced to swiping through tabs (i.e., controllers that may be located in a UIPageViewController). Even if one would listen to horizontal scroll events on the page view controller or switch to a custom implementation to get the progress made by swiping between tabs, there is no API on the Tab component to set the progress, updating the indicator accordingly. So now the indicator always lags behind the actual swiping done between tab content.

---

This is an internal issue. If you are a Googler, please visit [b/115483170](http://b/115483170) for more details.

---
#### Internal data
- Associated internal bug: [b/115483170](http://b/115483170)

**Comment by jverkoey** [comment]
@codeman7 is this a duplicate of https://github.com/material-components/material-components-ios/issues/5110 ?

**Comment by material-mirror** [comment]
The internal issue [b/115483170](http://b/115483170) is now closed. This issue is being closed as a result.
