### ISSUE TITLE
[BottomSheet] Provide API to specify Bottom Sheet auto dismissal

### ISSUE THREAD

**Issue by meiwin** [material-components/material-components-ios#5114]
## Feature Request/Suggestion

I am requesting an additional API to specify whether auto dismissal is wanted when using material bottom sheet presentation controller.

## Additional context

This feature is useful to prevent accidental dismissal when bottom sheet is performing long-running async task. For example: completing a purchase in a m-commerce app.

---
#### Internal data
- Associated internal bug: [b/117138252](http://b/117138252)

**Comment by jverkoey** [comment]
Hi @meiwin - you should be able to invoke `dismissViewControllerAnimated:completion:` on the presented bottom sheet. Are you finding that this doesn't work?

**Comment by material-mirror** [comment]
The internal issue [b/117138252](http://b/117138252) is now closed. This issue is being closed as a result.
