### ISSUE TITLE
[BottomSheet] Left to right shake when a fast swipe gesture opens up content

### ISSUE THREAD

**Issue by codeman7** [material-components/material-components-ios#5145]
When a MDCBottomSheetController has enough content to be presented full screen and a user tosses it full screen or back down to half screen it bounces vertically and horizontally.

## Reproduction steps

1. Open up MDCDragons
2. Navigate to BottomSheet
3. Open up "Bottom Sheet" example
4. Tap "Show Bottom Sheet" button
5. Throw content up and down

## Expected behavior

When "throwing" a bottom sheet up or down the content should only bounce vertically.

## Actual behavior

When you "throw" the bottom sheet the content bounces vertically and horizontally.

## Platform (please complete the following information)

 - Device: iPhoneX
 - OS: iOS 11.4

---
#### Internal data
- Associated internal bug: [b/117138205](http://b/117138205)

**Comment by material-mirror** [comment]
The internal issue [b/117138205](http://b/117138205) is now closed. This issue is being closed as a result.
