### ISSUE TITLE
[NavigationDrawer] MDCBottomDrawer scrolls content instead of view if opened halfway on iOS 9 and 10

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5148]
From the internal issue:

> After opening the bottom drawer on landscape, scrolling on the content sometimes does not expand the drawer, but instead scrolls in the content area

---

This is an internal issue. If you are a Googler, please visit [b/115858727](http://b/115858727) for more details.

**Comment by material-mirror** [comment]
The internal issue [b/115858727](http://b/115858727) is now closed, closing this issue.
