### ISSUE TITLE
[NavigationDrawer] MDCBottomDrawer opens up half screen on landscape

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5149]
From the internal issue:

> The bottom drawer component opens up halfway on landscape. If I understood this correctly, it should instead directly open full screen (or full content). If I misunderstood, it would be good to have an option to allow this use case.

---

This is an internal issue. If you are a Googler, please visit [b/115857668](http://b/115857668) for more details.

**Comment by yarneo** [comment]
This has been resolved in https://github.com/material-components/material-components-ios/pull/5443
