### ISSUE TITLE
[NavigationDrawer] Allow snapping to full screen / full content

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5151]
From the internal bug:

> Currently, the bottom drawer opens up halfway and then users can scroll up pixel by pixel to see more content. Would it be possible to allow clients using the bottom drawer to for example enable a flag that would adjust the destination content offset of the scrollview so that it would either fully extend or extend to the top of the screen if scrolled upwards after the initial half-screen opening?

---

This is an internal issue. If you are a Googler, please visit [b/115858141](http://b/115858141) for more details.

---
#### Internal data
- Associated internal bug: [b/115858141](http://b/115858141)

**Comment by material-mirror** [comment]
The internal issue [b/115858141](http://b/115858141) is now closed. This issue is being closed as a result.
