### ISSUE TITLE
Document our policies for behavioral runtime flags

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5154]
When migrating clients from one runtime behavior to another we often need to create a runtime flag that will facilitate the migration. It would be helpful to provide some guidance on these flags in our deprecation guide and to decide on whether we should encourage/discourage any specific conventions.

---
#### Internal data
- Associated internal bug: [b/117137865](http://b/117137865)

**Comment by material-mirror** [comment]
The internal issue [b/117137865](http://b/117137865) is now closed. This issue is being closed as a result.
