### ISSUE TITLE
[FlexibleHeader] Higher importance value for MDCFlexibleHeaderContentImportance that has an anchor length of 0

### ISSUE THREAD

**Issue by dylansturg** [material-components/material-components-ios#5166]
## Feature Request/Suggestion

I'd like to be able to specify an anchor length of 0 in `MDCFlexibleHeaderView` so that the header reappears immediately upon scrolling back after the header is shifted off screen.

The current options for `headerContentImportance` in `MDCFlexibleHeaderView` are `MDCFlexibleHeaderContentImportanceDefault` and `MDCFlexibleHeaderContentImportanceHigh`. These options use an anchor length 175 and 25, respectively. Reference: https://github.com/material-components/material-components-ios/blob/2fee13665fdc0052d1c9df2f8c187109730a50a3/components/FlexibleHeader/src/MDCFlexibleHeaderView.m#L1099

I propose adding another value to the enum, such as `MDCFlexibleHeaderContentImportanceVeryHigh`, which has a hard coded anchor length of 0. This follows the existing pattern and enables the interaction that designers for my app desire.

For reference, this is the `headerContentImportance` option that I'm referencing:
https://github.com/material-components/material-components-ios/blob/fec74d5e0de26314d832dd43812be04caf77df77/components/FlexibleHeader/src/MDCFlexibleHeaderView%2BShiftBehavior.h#L81

---
#### Internal data
- Associated internal bug: [b/117137455](http://b/117137455)

**Comment by dylansturg** [comment]
I played with the behavior adjusted to 0 anchor length, and it seemed alright. My app's UXers haven't tried it because it's not easy to get a build of our app with customizations in MDC out to them. They would make the final call whether or not they like the behavior. But the UXers strongly feel that they _want_ it, if that makes sense.

**Comment by jverkoey** [comment]
That does make sense. What can we do to help you get a test build into the hands of your UXers?

**Comment by jverkoey** [comment]
Reach out to me privately if necessary!

**Comment by material-mirror** [comment]
The internal issue [b/117137455](http://b/117137455) is now closed. This issue is being closed as a result.
