### ISSUE TITLE
The Dragons app doesn't change direction for RTL

### ISSUE THREAD

**Issue by galiak11** [material-components/material-components-ios#5169]
When switching directions through the Settings App (General / Language, then Select Hebrew) - the Dragons app doesn't change RTL direction (in the simulator). The main Catalog app does. 
The Dragons app **does** change direction, if direction is changed through XCode scheme. 

---
#### Internal data
- Associated internal bug: [b/117136653](http://b/117136653)

**Comment by romoore** [comment]
This is interfering with testing some RTL changes to Page Control. It's hard to debug issues if you don't realize the entire app is broken for RTL.

**Comment by material-mirror** [comment]
The internal issue [b/117136653](http://b/117136653) is now closed. This issue is being closed as a result.
