### ISSUE TITLE
Document usage of [Component]! and [Component]? in PULL_REQUEST_TEMPLATE

### ISSUE THREAD

**Issue by Arcank** [material-components/material-components-ios#517]
Context:
https://groups.google.com/forum/#!topic/material-components-ios-discuss/hFlH4YqBsbI

This could go in PULL_REQUEST_TEMPLATE (as mentioned in #88) or CONTRIBUTING_OFTEN (as mentioned in [#291](https://github.com/google/material-components-ios/issues/291#issuecomment-206945447)).

**Comment by ajsecord** [comment]
We've moved away from this.
