### ISSUE TITLE
[FlexibleHeader] Header height changes unexpectedly when changing the tracking scroll view

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5176]
## Repro steps

1. Open MDCDragons.
2. Open App Bar -> Manual Tabs
3. Scroll up on the first tab.
4. Select the second tab.

### Expected behavior

The header's height remains unchanged.

### Actual behavior

The header's height increases to the maximum height.

---
#### Internal data
- Associated internal bug: [b/117136517](http://b/117136517)

**Comment by material-mirror** [comment]
The internal issue [b/117136517](http://b/117136517) is now closed. This issue is being closed as a result.
