### ISSUE TITLE
Remove MDCBottomAppBarView from MDCBottomAppBarView.m static consts

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5177]
We no longer need to prefix our static consts with the name of the file. This is a historical artifact that we can clean up.

Example:

```
// Before
static const CGFloat kMDCBottomAppBarViewFloatingButtonElevationPrimary = 6.f;

// After
static const CGFloat kFloatingButtonElevationPrimary = 6.f;
```

---
#### Internal data
- Associated internal bug: [b/117135349](http://b/117135349)

**Comment by material-mirror** [comment]
The internal issue [b/117135349](http://b/117135349) is now closed. This issue is being closed as a result.
