### ISSUE TITLE
backgroundColor property on MDCButtons is ignored when setting the enabled state

### ISSUE THREAD

**Issue by jpsachse** [material-components/material-components-ios#518]
According to #69, the backgroundColor properties should be gone on MDCButtons, but they are not.

And since they are there, the following behavior is wrong:

Setting the backgroundColor using button.backgroundColor = UIColor.greenColor() works perfectly, as long as no API is used that forces the button to update its background color (such as disabling/enabling the button). Then it automatically falls back to using its default color, as it is ignoring the backgroundColor property and instead using the value stored in _backgroundColors for UIControlstate.Normal. My suggestion would be to override the value in _backgroundColors[UIControlstate.Normal] when setting the background color using the property setter.

**Comment by samnm** [comment]
We implemented the fix as suggested here: https://github.com/material-components/material-components-ios/commit/6670e7409f8fc3ecadbcc18a12de781f16569798
