### ISSUE TITLE
[MDCInkView] Provide ability to generate ink colors

### ISSUE THREAD

**Issue by turbotimbo** [material-components/material-components-ios#5183]
MDCContainedButtonColorThemer and MDCTextButtonColorThemer contain code to set ink colors based on the primaryColor of a color scheme and differing alpha values. 

It is currently difficult to replicate and match these ink colors for other custom components. It would be useful if this color creation code was broken out into a separate object that could be used to generate ink colors for custom components based on an input color.

---
#### Internal data
- Associated internal bug: [b/117135710](http://b/117135710)

**Comment by codeman7** [comment]
Hey @turbotimbo are you hoping to set ink colors on other components?

**Comment by turbotimbo** [comment]
@codeman7 We are making our own UI Components and using MDCInkTouchController. We then set the ink color on them. It would be useful if we could easily generate the ink color in a consistent way to MDCTextButtonColorThemer.

**Comment by material-mirror** [comment]
The internal issue [b/117135710](http://b/117135710) is now closed. This issue is being closed as a result.
