### ISSUE TITLE
[AppBar] Add support for setNavigationBarHidden in MDCAppBarNavigationController

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5185]
## Feature Request/Suggestion

This functionality would allow a child view controller to show/hide the app bar through the typical navigation bar APIs.

Supporting this will require adding support to the flexible header for hiding/showing the header without the shift behavior being enabled.

---
#### Internal data
- Associated internal bug: [b/117135492](http://b/117135492)

**Comment by newmanw** [comment]
Is there a workaround for hiding navigation bar?

**Comment by jverkoey** [comment]
The recommended workaround is to directly hide the navigation bar on the navigation controller.

**Comment by newmanw** [comment]
@jverkoey a working example would go a long way as I have been unsuccessful.

Tried to hide after pushing viewcontroller:

```
    let nav: MDCAppBarNavigationController
    func go() {
        let someController = SomeController(nibName: nil, bundle: nil)
        
        nav.delegate = self
        nav.isNavigationBarHidden = true
        nav.pushViewController(someController!, animated: true)
        let appBarViewController = presenter.appBarViewController(for: someController)
        appBarViewController?.navigationBar.isHidden = true
    }
```

Also tried to hide the navbar in the delegate:

```
    func appBarNavigationController(_ navigationController: MDCAppBarNavigationController, willAdd appBar: MDCAppBar, asChildOf viewController: UIViewController) {
        appBar.navigationBar.isHidden = true
    }
```

**Comment by jverkoey** [comment]
Ah, are you trying to hide the App Bar's navigation bar?

If so, you will need to enable shifting and then call either `shiftHeaderOnScreenAnimated` or `shiftHeaderOffScreenAnimated` when applicable.

```swift
headerViewController.shiftBehavior = .enabled
headerViewController.shiftHeaderOffScreenAnimated(NO)
```

**Comment by newmanw** [comment]
> Ah, are you trying to hide the App Bar's navigation bar?

Yes, isn't that what UINavigationController.setNavigationBarHidden() does?

```
    func appBarNavigationController(_ navigationController: MDCAppBarNavigationController, willAdd appBar: MDCAppBar, asChildOf viewController: UIViewController) {
        appBar.headerViewController.headerView.shiftBehavior = .enabled
        appBar.headerViewController.headerView.shiftHeaderOffScreen(animated: false)
    }
```

Throws the following exception:

`'NSInternalInconsistencyException', reason: 'Flexible Header shift behavior must be disabled before content offset observation is enabled.'`

**Comment by jverkoey** [comment]
In this case you'll likely be best off creating and managing a single `MDCAppBarViewController` whose behavior and configuration is tailored to your needs. Notably, you'll want need to forward scroll view delegate events and keep `observesTrackingScrollViewScrollEvents` disabled.

**Comment by material-mirror** [comment]
The internal issue [b/143490051](http://b/143490051) is now closed. This issue is being closed as a result.

**Comment by material-mirror** [comment]
The internal issue [b/117135492](http://b/117135492) is now closed. This issue is being closed as a result.
