### ISSUE TITLE
[AppBar] App Bar has incorrect width after orientation change.

### ISSUE THREAD

**Issue by bambaragoogle** [material-components/material-components-ios#5192]
App bar uses a width value from when it is initialized, not when it is actually loaded into the view hierarchy. You can confirm this by rotating the device between init and load.

General set up:
- I have two controllers, let's call them `A` and `B`.
- `B` has a `MDCAppBarViewController` and is a child of `A`.

Steps to reproduce:
- `A` is presented in portrait. It initializes controller `B`, but doesn't yet load it into the view hierarchy. On init, `B` creates a `MDCAppBarViewController` and adds it as a child view controller.
- The user rotates the device to landscape.
- `A` loads `B`, `B` calls `-[UIView addSubview:]` and `-[UIViewController didMoveToParentViewController:]` on the app bar.
- The app bar appears in `B` with a width appropriate for portrait orientation. Changing the orientation back to portrait makes the width even thinner, and on some devices the bar disappears entirely.

I can fix the bar's width by assigning a new frame to the `MDCFlexibleHeaderView` after calling `-[UIViewController didMoveToParentViewController:]`, but this seems like a bug because the additional frame assignment is only necessary in this edge case.

**Comment by jverkoey** [comment]
This is working as intended (the view is a typical UIView and subject to all frame and layout considerations as a result). If you recently migrated from MDCAppBar, those APIs did perform the frame setting logic as a convenience, so I understand if the view controller's behavior seems surprising at first. Please see our migration guide for example code:

https://github.com/material-components/material-components-ios/tree/develop/components/AppBar#migration-guide-mdcappbar-to-mdcappbarviewcontroller
