### ISSUE TITLE
Add snapshot tests to Buttons and Cards

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5199]
## Context

We currently do Catalog screenshot testing as part of our release process. This is helpful to identify general changes in behavior across the catalog when we cut releases, but we are limited by the examples we have built and what those examples demonstrate (which is rarely exhaustive).

## Our need

We need snapshot unit tests.

A snapshot unit test is a test that takes a snapshot of an instance of the component's view only; they are not full-screen device screenshots like the ones we use as part of our release process internally. These types of tests can be run in a simplified test host environment that is more similar to unit tests than full-fledged UI tests. These types of tests **do** require a full app host, unlike typical unit tests.

One benefit of snapshot tests is that we can generate variants much easier than if we had to implement a full example. This means we can test a more diverse range of configurations faster. For example, every component should include a matrix of screenshots that test the following theming patterns:

- Defaults.
- Baseline themed.
- Custom themed.

We may also provide different screenshot tests for different permutations of parameter configurations, or different permutations of device characteristics, internationalization, or accessibility.

## Why do we need this?

It's important that we're able to identify and avoid significant user interface regressions before they ship to client apps. Having more comprehensive component tests across a wider range of theming will ensure that we catch regressions as part of our release process.

## Additional resources

We can likely use git lfs to store the screenshot images so that we don't balloon our repo's size.

Some additional reading:

- https://github.com/git-lfs/git-lfs/wiki/Tutorial
- https://github.com/uber/ios-snapshot-test-case

## Prior explorations

https://github.com/material-components/material-components-ios/tree/snapshottesting

Will require modifications to our Kokoro jobs. Learn more at [go/mdc-kokoro](http://go/mdc-kokoro).

## Prior to starting this work

Reach out to @acdvorak to discuss learnings from the material-components-web team.

## Definition of done

- Screenshot tests are running on a kokoro job (may be a new family of jobs or as part of our other jobs).
- There is documentation describing how to write screenshot tests.
- There are at least two components that have screenshot tests testing a "default" component, a "baseline themed" component, and a "custom themed" component.

---
#### Internal data
- Associated internal bug: [b/116240960](http://b/116240960)
- Blocked by: https://github.com/material-components/material-components-ios/issues/5492
- Blocked by: https://github.com/material-components/material-components-ios/issues/5493
- Blocked by: https://github.com/material-components/material-components-ios/issues/5494
- Blocked by: https://github.com/material-components/material-components-ios/issues/5495

**Comment by romoore** [comment]
Cards and Buttons have snapshot tests. Marking this closed.
