### ISSUE TITLE
[Buttons] Minimum touch size states 64 wide 48 high, but the corresponding objc example uses 48 on both lines?

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5216]
This is an internal issue. If you are a Googler, please visit [b/116176880](http://b/116176880) for more details.

---
#### Internal data
- Associated internal bug: [b/116176880](http://b/116176880)

**Comment by material-mirror** [comment]
The internal issue [b/116176880](http://b/116176880) is now closed. This issue is being closed as a result.
