### ISSUE TITLE
[TextFields] Custom font example sets font wrong

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#5233]
It should not set a font on the text field itself. It should use the controller's `textInputFont` and `inlinePlaceholderFont`.

You'll see behavior like #4189
![simulator screen shot - iphone xr - 2018-09-25 at 11 51 50](https://user-images.githubusercontent.com/1271525/46027378-b8fff680-c0bb-11e8-88e6-25cf0b81f8cc.png)
![simulator screen shot - iphone xr - 2018-09-25 at 11 52 02](https://user-images.githubusercontent.com/1271525/46027383-bbfae700-c0bb-11e8-8161-0ce058c3e0e0.png)
![simulator screen shot - iphone xr - 2018-09-25 at 11 51 55](https://user-images.githubusercontent.com/1271525/46027387-bef5d780-c0bb-11e8-8bdf-09abeeb18dd0.png)

---
#### Internal data
- Associated internal bug: [b/117133473](http://b/117133473)

**Comment by material-mirror** [comment]
The internal issue [b/117133473](http://b/117133473) is now closed. This issue is being closed as a result.
