### ISSUE TITLE
Implement an MVP Banner prototype

### ISSUE THREAD

**Issue by wenyuzhang666** [material-components/material-components-ios#5241]
---
#### Internal data
- Associated internal bug: [b/117123271](http://b/117123271)
- Blocked by: https://github.com/material-components/material-components-ios/issues/6771
- Blocked by: https://github.com/material-components/material-components-ios/issues/6769
- Blocked by: https://github.com/material-components/material-components-ios/issues/5563
- Blocked by: https://github.com/material-components/material-components-ios/issues/5534
- Blocked by: https://github.com/material-components/material-components-ios/issues/5529
- Blocked by: https://github.com/material-components/material-components-ios/issues/5489

**Comment by material-mirror** [comment]
The internal issue [b/117123271](http://b/117123271) is now closed. This issue is being closed as a result.
