### ISSUE TITLE
[TextFields] Poor Voiceover experience when changing phone number: Delete the 11th digit, it re-reads it even if the focus is not on it 

### ISSUE THREAD

**Issue by andrewoverton** [material-components/material-components-ios#5250]
This is an internal issue. If you are a Googler, please visit [b/116542697](http://b/116542697) for more details.

---
#### Internal data
- Associated internal bug: [b/116542697](http://b/116542697)

**Comment by jverkoey** [comment]
The internal issue is not yet closed, re-opening this issue. Googler: please check the state of the internal issue and update it accordingly.

**Comment by andrewoverton** [comment]
Closed the internal issue.

**Comment by material-mirror** [comment]
The internal issue [b/116542697](http://b/116542697) is now closed. This issue is being closed as a result.

**Comment by material-mirror** [comment]
The internal issue [b/116542697](http://b/116542697) is now closed. This issue is being closed as a result.
