### ISSUE TITLE
[FlexibleHeader] Add support for changing the flexible header's visibility

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5253]
## Feature Request/Suggestion

MDCFlexibleHeaderView has an API for shifting the header on and off-screen if shift behavior is enabled. We'd like to expand this API to support hiding and showing the header even if shift behavior is not enabled. In this manner, the API would be similar to UINavigationController's [`setNavigationBarHidden:animated:`](https://developer.apple.com/documentation/uikit/uinavigationcontroller/1621885-setnavigationbarhidden?language=objc).

## Existing similar APIs

https://github.com/material-components/material-components-ios/blob/956761ed4d567ef1aaf29370bc2b5be11215128a/components/FlexibleHeader/src/MDCFlexibleHeaderView%2BShiftBehavior.h#L126-L130

## Definition of done

- [ ] There is a new API `setHeaderViewHidden:animated:` on MDCFlexibleHeaderViewController.
- [ ] This existing `shiftHeaderOnScreenAnimated:` and `shiftHeaderOffScreenAnimated:` APIs are put on a path for deprecation.
- [ ] This new API works regardless of the shift behavior.
- [ ] This new API supports animation and no animation.

---
#### Internal data
- Associated internal bug: [b/117123376](http://b/117123376)

**Comment by material-mirror** [comment]
The internal issue [b/117123376](http://b/117123376) is now closed. This issue is being closed as a result.
