### ISSUE TITLE
[NavigationDrawer] Collapsed Mode That Can Be Expanded When Dragged

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5260]
From the internal issue:

> Collapsed mode that can be expanded when dragged, resizing/hiding header and footer, animations between main view and header/footer.

There is an additional link with mocks on the internal issue.

---

This is an internal issue. If you are a Googler, please visit [b/116782981](http://b/116782981) for more details.

---
#### Internal data
- Associated internal bug: [b/116782981](http://b/116782981)

**Comment by material-mirror** [comment]
The internal issue [b/116782981](http://b/116782981) is now closed. This issue is being closed as a result.
