### ISSUE TITLE
[FlexibleHeader] Allow Having A Consistent Header Over Different View Controllers

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5261]
From the internal issue:

> allow having a consistent header over different view controllers, even with different views added to the header (so different header heights)

---

This is an internal issue. If you are a Googler, please visit [b/116782615](http://b/116782615) for more details.

---
#### Internal data
- Associated internal bug: [b/116782615](http://b/116782615)

**Comment by material-mirror** [comment]
The internal issue [b/116782615](http://b/116782615) is now closed. This issue is being closed as a result.
