### ISSUE TITLE
[FlexibleHeader] Allow Adding Multiple Views To The Header Stack

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5262]
From the internal issue:

> allow adding multiple views to the header stack (not just top and bottom bar), which might change their layout based on header size

---

This is an internal issue. If you are a Googler, please visit [b/116782978](http://b/116782978) for more details.

---
#### Internal data
- Associated internal bug: [b/116782978](http://b/116782978)

**Comment by material-mirror** [comment]
The internal issue [b/116782978](http://b/116782978) is now closed. This issue is being closed as a result.
