### ISSUE TITLE
[BottomNavigation] Better Support For Localization

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5264]
From the internal issue:

> Better support for localizations with multiple buttons

---

This is an internal issue. If you are a Googler, please visit [b/116783171](http://b/116783171) for more details.

---
#### Internal data
- Associated internal bug: [b/116783171](http://b/116783171)

**Comment by material-mirror** [comment]
The internal issue [b/116783171](http://b/116783171) is now closed. This issue is being closed as a result.
