### ISSUE TITLE
[TextFields] Inconsistent Margins Between TextField Controllers

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5265]
From the internal issue:

> Margins are not consistent between text input controllers. MDCTextInputControllerUnderline has no margins; MDCTextInputControllerFilled has margins, but adds an outline.

---

This is an internal issue. If you are a Googler, please visit [b/116782532](http://b/116782532) for more details.

---
#### Internal data
- Associated internal bug: [b/116782532](http://b/116782532)

**Comment by material-mirror** [comment]
The internal issue [b/116782532](http://b/116782532) is now closed. This issue is being closed as a result.
