### ISSUE TITLE
[Chips] Self Sizing Chip Container View

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5266]
From the internal issue:

> We need a standard self-sizing view which contains a collection of MDCChipView objects, so we can include that view inside a collection view of our own. Basically, this example code, but split out into a standard chip collection view which self-sizes:
>
> https://github.com/material-components/material-components-ios/blob/21810842725b86f68fb7dcbd023e4c39c56e3a08/components/Chips/examples/ChipsChoiceExampleViewController.m

---

This is an internal issue. If you are a Googler, please visit [b/116783352](http://b/116783352) for more details.

---
#### Internal data
- Associated internal bug: [b/116783352](http://b/116783352)

**Comment by material-mirror** [comment]
The internal issue [b/116783352](http://b/116783352) is now closed. This issue is being closed as a result.
