### ISSUE TITLE
[ButtonBar] UIBarButtonItems use inconsistent ink based on text or image

### ISSUE THREAD

**Issue by mohagan** [material-components/material-components-ios#5275]
## Feature Request/Suggestion

When using UIBarButtonItems on the app bar there is a check to see if it contains text or not and flips the ink style: 

https://github.com/material-components/material-components-ios/blob/7672bcf7a61d48af4da9947efdbbe2d34d241b09/components/ButtonBar/src/private/MDCAppBarButtonBarBuilder.m#L251-L255

We would like to have unbounded support for all barbuttonitems even if they have text to be consistent. Is it possible to make this configurable? 

---
#### Internal data
- Associated internal bug: [b/117122750](http://b/117122750)

**Comment by chickenblood** [comment]
Jeff, see the bug of mine that you duped to this one.

**Comment by material-mirror** [comment]
The internal issue [b/117122750](http://b/117122750) is now closed. This issue is being closed as a result.
