### ISSUE TITLE
[Chips] MDCChipView not invalidating intrinsic content size when text changes

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5280]
This is an internal issue. If you are a Googler, please visit [b/116786204](http://b/116786204) for more details.

---
#### Internal data
- Associated internal bug: [b/116786204](http://b/116786204)

**Comment by material-mirror** [comment]
The internal issue [b/116786204](http://b/116786204) is now closed. This issue is being closed as a result.
