### ISSUE TITLE
[FlexibleHeader] Incorrect shadow after clearing trackingScrollView

### ISSUE THREAD

**Issue by AlimoRabbani** [material-components/material-components-ios#5281]
When trackingScrollView on MDCFlexibleHeaderView is explicitly set to nil, an incorrect shadow is shown, there should be no shadow, similar to when trackingScrollView is not set.

## Reproduction steps
in MDCDragons, add the following to FlexibleHeaderTypicalUseViewController:

- (void)viewDidAppear:(BOOL)animated {
  [super viewDidAppear:animated];
  self.fhvc.headerView.trackingScrollView = nil;
}

Run the app and open FlexibleHeader->FlexibleHeader.

## Expected behavior
No shadow, even though contentInset.top is set to 0 and the scrollView content is hidden behind the app bar.

## Actual behavior
Observe a shadow is added.

## Additional context
This behavior was originally added in https://github.com/material-components/material-components-ios/commit/5ddf405c43ca2abb700877b8fbbf995e2ed422c1, but I'm not sure why.

---
#### Internal data
- Associated internal bug: [b/117293175](http://b/117293175)

**Comment by AlimoRabbani** [comment]
@jverkoey If you don't have any obligations, I have a PR ready for this.

**Comment by jverkoey** [comment]
PRs welcome!

**Comment by AlimoRabbani** [comment]
I certainly meant "If you don't have any objections" above. Damn Friday evening.

**Comment by jverkoey** [comment]
Haha I got what you meant :p

**Comment by AlimoRabbani** [comment]
This is reopened because my commit was reverted in http://go/gh/material-components/material-components-ios/commit/8c52493f6cc6d62c2f43dcab2b41539e5bbc54ce

**Comment by AlimoRabbani** [comment]
Tracking internal failures in b/117269330.

**Comment by AlimoRabbani** [comment]
Should we keep this open until I clean up the optional flag I added?
