### ISSUE TITLE
[AppBar] Custom HeaderView

### ISSUE THREAD

**Issue by FabianTerhorst** [material-components/material-components-ios#5288]
## Feature Request/Suggestion

An api for the AppBar to make it possible to set an UIView between the leading and trailing button.

## Additional context

I need it to implement an filter as shown in the material design doc: https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1y-mLNpsL5uIcVpBTGYQIhMRj4-XRQA2z%2Fbehavior-reveal-02-input.png

I have currently implemented it by using the following constraints. Im applying them in viewDidLoad and extracting the leading and trailing button from ```appBarViewController.navigationBar.subviews```, but this solutions looks a bit hacky and doesn't work 1/10 times.
```swift
[
     containerView.leadingAnchor.constraint(equalTo: leadingButton.trailingAnchor),
     containerView.trailingAnchor.constraint(equalTo: trailingButton.leadingAnchor),
     containerView.heightAnchor.constraint(equalTo: 
     appBarViewController.navigationBar.heightAnchor),
     containerView.centerYAnchor.constraint(equalTo: 
     appBarViewController.navigationBar.centerYAnchor)
]
```

**Comment by jverkoey** [comment]
Thank you for reaching out to us! The App Bar makes use of MDCNavigationBar which, like a UINavigationBar, exposes a `titleView` property that you can set to a custom subview.

The relevant API:

https://github.com/material-components/material-components-ios/blob/develop/components/NavigationBar/src/MDCNavigationBar.h#L106-L115

You can assign a custom title view via your view controller's `navigationItem.titleView` property.

Please re-open this issue if the above does not work for you, including additional context and a repro case.

**Comment by FabianTerhorst** [comment]
Thank you very much for the information. I totally overlooked the titleView attribute. It is working completely fine.
