### ISSUE TITLE
[TextFields] How to set underline for MDCTextInputControllerOutlinedTextArea

### ISSUE THREAD

**Issue by vuhoang1701** [material-components/material-components-ios#5292]
I want to use text area with underline without outline like this

[https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1p3r_LfcfFF_m3zp5oYa419ZY5bfgiMld%2Ftextfields-input-textareas.mp4](url)
And here my code:

 
```
self.textAreaController = [[MDCTextInputControllerOutlinedTextArea alloc] initWithTextInput:self.multilineTextField];

//Clear outline color
self.textAreaController.activeColor = [UIColor clearColor];
self.textAreaController.normalColor = [UIColor clearColor];

[self.textAreaController setUnderlineHeightActive:1];
[self.textAreaController setUnderlineHeightNormal:1];
[self.textAreaController.textInput.underline setColor:[UIColor greenColor]]; 

[self.textAreaController.textInput.underline setDisabledColor:[UIColor lightGrayColor]];

```

But it does not work. Please help me! Thank you.

---
#### Internal data
- Associated internal bug: [b/117120588](http://b/117120588)

**Comment by material-mirror** [comment]
The internal issue [b/117120588](http://b/117120588) is now closed. This issue is being closed as a result.
