### ISSUE TITLE
[Dialogs] Deprecate Alert's ColorThemer & TypographyThemer in favor of AlertControllerThemer

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5295]
From the internal issue:

> Deprecate the MDCAlertColorThemer and MDCAlertTypographyThemer themers, in favor of MDCAlertColorThemer, which includes internal references to a color and typography themers.
This is in order to reduce duplication in themers and reduce confusion about which themer to use for what.

---

This is an internal issue. If you are a Googler, please visit [b/116624173](http://b/116624173) for more details.

**Comment by material-mirror** [comment]
The internal issue is now closed, closing this issue.
