### ISSUE TITLE
Expansion Panel for iOS

### ISSUE THREAD

**Issue by bond-** [material-components/material-components-ios#5313]
Please add expansion panel component to iOS.

Link: https://material.io/archive/guidelines/components/expansion-panels.html
Example: https://material.angular.io/components/expansion/examples

---
#### Internal data
- Associated internal bug: [b/117262544](http://b/117262544)

**Comment by material-mirror** [comment]
The internal issue [b/117262544](http://b/117262544) is now closed. This issue is being closed as a result.
