### ISSUE TITLE
Project is not building when using both MaterialComponents and MaterialComponentsAlpha via pods

### ISSUE THREAD

**Issue by anuranBarman** [material-components/material-components-ios#5316]
I successfully used components from MaterialComponents. Then I added the pod for alpha-components to use **Navigation Drawer**. But project build is failing

## Reproduction steps

1. Add Both MaterialComponents and MaterialComponentsAlpha in podfile
2. pod install

## Expected behavior

Project should be built successfully and we should be able to use alpha components also

## Actual behavior

Project build failed with error 
**Property 'preferredSheetHeight' not found on object of type 'MDCBottomSheetPresentationController'**

## Platform

 - Device: iphone 5s
 - OS: iOS 12.0

## Additional context

I successfully used components from MaterialComponents. Then I added the pod for alpha-components to use **Navigation Drawer**. But project build is failing

---
#### Internal data
- Associated internal bug: [b/117291574](http://b/117291574)

**Comment by ianegordon** [comment]
I know it isn't exactly BottomSheet, but @codeman7 , can you take a look?

**Comment by andrewoverton** [comment]
This seems to be a duplciate of #5380

**Comment by material-mirror** [comment]
The internal issue [b/117291574](http://b/117291574) is now closed. This issue is being closed as a result.
