### ISSUE TITLE
Mediation Test Suite Fails to Build on XCode

### ISSUE THREAD

**Issue by ChaleChan** [material-components/material-components-ios#5317]
$ pod install
Analyzing dependencies
Downloading dependencies
Using Google-Mobile-Ads-SDK (7.34.0)
Using GoogleMobileAdsMediationTestSuite (0.9.1)
Using MDFInternationalization (1.1.0)
Using MDFTextAccessibility (1.2.0)
Using MaterialComponents (63.0.0)
Using MotionAnimator (2.8.1)
Using MotionInterchange (1.6.0)
Using MotionTransitioning (5.0.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 3 dependencies from the Podfile and 8 total pods installed.

but,when i try to build my project.
Error:
ld: warning: directory not found for option '-L/Users/chale/Library/Developer/Xcode/DerivedData/Unity-iPhone-bpvyzmbayukserbimjowdhuxoduy/Build/Products/ReleaseForRunning-iphoneos/MDFInternationalization'
ld: warning: directory not found for option '-L/Users/chale/Library/Developer/Xcode/DerivedData/Unity-iPhone-bpvyzmbayukserbimjowdhuxoduy/Build/Products/ReleaseForRunning-iphoneos/MDFTextAccessibility'
ld: warning: directory not found for option '-L/Users/chale/Library/Developer/Xcode/DerivedData/Unity-iPhone-bpvyzmbayukserbimjowdhuxoduy/Build/Products/ReleaseForRunning-iphoneos/MaterialComponents'
ld: warning: directory not found for option '-L/Users/chale/Library/Developer/Xcode/DerivedData/Unity-iPhone-bpvyzmbayukserbimjowdhuxoduy/Build/Products/ReleaseForRunning-iphoneos/MotionAnimator'
ld: warning: directory not found for option '-L/Users/chale/Library/Developer/Xcode/DerivedData/Unity-iPhone-bpvyzmbayukserbimjowdhuxoduy/Build/Products/ReleaseForRunning-iphoneos/MotionInterchange'
ld: warning: directory not found for option '-L/Users/chale/Library/Developer/Xcode/DerivedData/Unity-iPhone-bpvyzmbayukserbimjowdhuxoduy/Build/Products/ReleaseForRunning-iphoneos/MotionTransitioning'
ld: library not found for -lMDFInternationalization
clang: error: linker command failed with exit code 1 (use -v to see invocation)

pods config:
FRAMEWORK_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Google-Mobile-Ads-SDK/Frameworks/frameworks" "${PODS_ROOT}/GoogleMobileAdsMediationTestSuite/Framework"
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/Google-Mobile-Ads-SDK" "${PODS_ROOT}/Headers/Public/GoogleMobileAdsMediationTestSuite" "${PODS_ROOT}/Headers/Public/MDFInternationalization" "${PODS_ROOT}/Headers/Public/MDFTextAccessibility" "${PODS_ROOT}/Headers/Public/MaterialComponents" "${PODS_ROOT}/Headers/Public/MotionAnimator" "${PODS_ROOT}/Headers/Public/MotionInterchange" "${PODS_ROOT}/Headers/Public/MotionTransitioning"
LIBRARY_SEARCH_PATHS = $(inherited) "${PODS_CONFIGURATION_BUILD_DIR}/MDFInternationalization" "${PODS_CONFIGURATION_BUILD_DIR}/MDFTextAccessibility" "${PODS_CONFIGURATION_BUILD_DIR}/MaterialComponents" "${PODS_CONFIGURATION_BUILD_DIR}/MotionAnimator" "${PODS_CONFIGURATION_BUILD_DIR}/MotionInterchange" "${PODS_CONFIGURATION_BUILD_DIR}/MotionTransitioning" "${PODS_ROOT}/Google-Mobile-Ads-SDK/Libraries"
OTHER_CFLAGS = $(inherited) -isystem "${PODS_ROOT}/Headers/Public" -isystem "${PODS_ROOT}/Headers/Public/Google-Mobile-Ads-SDK" -isystem "${PODS_ROOT}/Headers/Public/GoogleMobileAdsMediationTestSuite" -isystem "${PODS_ROOT}/Headers/Public/MDFInternationalization" -isystem "${PODS_ROOT}/Headers/Public/MDFTextAccessibility" -isystem "${PODS_ROOT}/Headers/Public/MaterialComponents" -isystem "${PODS_ROOT}/Headers/Public/MotionAnimator" -isystem "${PODS_ROOT}/Headers/Public/MotionInterchange" -isystem "${PODS_ROOT}/Headers/Public/MotionTransitioning"
OTHER_LDFLAGS = $(inherited) -ObjC -l"GoogleMobileAds" -l"MDFInternationalization" -l"MDFTextAccessibility" -l"MaterialComponents" -l"MotionAnimator" -l"MotionInterchange" -l"MotionTransitioning" -l"sqlite3" -l"z" -framework "AVFoundation" -framework "AudioToolbox" -framework "CFNetwork" -framework "CoreGraphics" -framework "CoreMedia" -framework "CoreMotion" -framework "CoreTelephony" -framework "CoreVideo" -framework "GLKit" -framework "GoogleMobileAds" -framework "GoogleMobileAdsMediationTestSuite" -framework "MediaPlayer" -framework "MessageUI" -framework "MobileCoreServices" -framework "OpenGLES" -framework "QuartzCore" -framework "Security" -framework "StoreKit" -framework "SystemConfiguration" -weak_framework "AdSupport" -weak_framework "JavaScriptCore" -weak_framework "SafariServices" -weak_framework "WebKit"
PODS_BUILD_DIR = ${BUILD_DIR}
PODS_CONFIGURATION_BUILD_DIR = ${PODS_BUILD_DIR}/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
PODS_PODFILE_DIR_PATH = ${SRCROOT}/.
PODS_ROOT = ${SRCROOT}/Pods

---
#### Internal data
- Associated internal bug: [b/117293377](http://b/117293377)

**Comment by material-mirror** [comment]
The internal issue [b/117293377](http://b/117293377) is now closed. This issue is being closed as a result.
