### ISSUE TITLE
[Dialogs] Clean up Dialogs examples in MDC Catalog

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5318]
From the internal issue:

> Clean up dialog’s catalog examples (MDC Catalog):
> Keep only a main examples demonstrating typical use of dialogs. 
> Move other examples to Dragons.

---

This is an internal issue. If you are a Googler, please visit [b/117264995](http://b/117264995) for more details.

---
#### Internal data
- Associated internal bug: [b/117264995](http://b/117264995)

**Comment by material-mirror** [comment]
The internal issue [b/117264995](http://b/117264995) is now closed. This issue is being closed as a result.
