### ISSUE TITLE
[Dialogs] Conduct an API review for theming Alert Buttons

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5322]
From the internal issue:

> Expose MDCButtons in MDCAlertActions that are added to MDCAlertController, so they can be all or individually customized/themed.

---

This is an internal issue. If you are a Googler, please visit [b/116447500](http://b/116447500) for more details.

**Comment by material-mirror** [comment]
The internal issue [b/116447500](http://b/116447500) is now closed, closing this issue.
