### ISSUE TITLE
[AppBar] Bottom of letter hangs below top of screen when scrolled up

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5323]
From the internal issue:

> When shift behavior is enabled like this:
self.headerViewController.headerView.behavior = MDCFlexibleHeaderShiftBehaviorEnabled;
>
> The bottom of a lowercase g can be seen at the top of the screen

---

This is an internal issue. If you are a Googler, please visit [b/27833045](http://b/27833045) for more details.

---
#### Internal data
- Associated internal bug: [b/27833045](http://b/27833045)

**Comment by material-mirror** [comment]
The internal issue [b/27833045](http://b/27833045) is now closed. This issue is being closed as a result.
