### ISSUE TITLE
[FlexibleHeader] Implement support for edgesForExtendedLayout in GOOHeaderViewController

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5324]
From the internal issue:

> UINavigationController and certain other container view controller classes in UIKit use the edgesForExtendedLayout property in order to determine whether or not a child view controller's content should be laid out underneath visual elements of the container view controller, e.g., the navigation bar. It would be great if MDCHeaderViewController did the same.

---

This is an internal issue. If you are a Googler, please visit [b/23898114](http://b/23898114) for more details.

---
#### Internal data
- Associated internal bug: [b/23898114](http://b/23898114)

**Comment by material-mirror** [comment]
The internal issue [b/23898114](http://b/23898114) is now closed. This issue is being closed as a result.
