### ISSUE TITLE
[ActionSheet] ActionSheet doesn't respect the safe area insets after it rebounds when nudged up a little bit

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#5331]
This is an internal issue. If you are a Googler, please visit [b/117286643](http://b/117286643) for more details.

---
#### Internal data
- Associated internal bug: [b/117286643](http://b/117286643)

**Comment by codeman7** [comment]
Same bug as #5205

**Comment by material-mirror** [comment]
The internal issue [b/117286643](http://b/117286643) is now closed, closing this issue.
