### ISSUE TITLE
[FlexibleHeader] Should only inject the necessary amount of top content inset into the tracking scroll view

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5338]
## Context

Currently the flexible header assumes that its tracking scroll view is always placed directly behind the header view. Based on this assumption, the flexible header injects its maximumHeight into the tracking scroll view's top content inset so that the content of the scroll view is positioned below the header.

If the tracking scroll view is not behind the header view, however, then this assumption results in surprising behaviors. Notably, the scroll view's content gets inset further than it needs to be.

## Proposed fix

Rather than unconditionally inject the maximum height into the tracking scroll view, the flexible header should calculate how much the flexible header will overlap the scroll view content and only inject that amount. If there is no overlap, then the scroll view's content inset does not need to be adjusted.

The rough logic for this will probably be:

```
let headerBottomEdge = headerView.frame.origin.y + maximumHeight
let trackingScrollViewTopEdge = trackingScrollView.frame.origin.y
let overlap = MAX(0, MIN(maximumHeight, headerBottomEdge - trackingScrollViewTopEdge))
```

---
#### Internal data
- Associated internal bug: [b/117411147](http://b/117411147)

**Comment by sreekanth-krishnan** [comment]
Is there any quick work around for this?
I'm getting a padding at the top of tableview while using MDCAppBarNavigationController

**Comment by material-mirror** [comment]
The internal issue [b/117411147](http://b/117411147) is now closed. This issue is being closed as a result.
