### ISSUE TITLE
[TextFields] unable to set custom font to error text

### ISSUE THREAD

**Issue by pikaboo** [material-components/material-components-ios#5340]
> For usage questions: ask on [Stack  Overflow](https://stackoverflow.com/questions/tagged/material-components+ios).

Unable to set custom font to textfield / textinputcontroller error text
## Reproduction steps

1. add custom font to app
2. create MDCTypographyScheme implementation for font
3. apply scheme to textfield and textinputcontroller
4. observe custom font is set everywhere except error label 

## Expected behavior

error label also has custom font
## Actual behavior
error label has system default font
A clear and concise description of what actually happened. Include screenshots or gifs where possible.
<img width="227" alt="error text" src="https://user-images.githubusercontent.com/3405551/46575198-7393d100-c9b9-11e8-9319-ebefae067e5b.png">

## Platform (please complete the following information)

 - Device: All devices
 - OS: all os'

## Additional context

---
#### Internal data
- Associated internal bug: [b/117411197](http://b/117411197)

**Comment by material-mirror** [comment]
The internal issue [b/117411197](http://b/117411197) is now closed. This issue is being closed as a result.
