### ISSUE TITLE
[AppBar] Improve the MDCAppBarNavigationController tracking scroll view heuristics

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5344]
MDCAppBarNavigationController uses a very simple algorithm to find the tracking scroll view for a given view controller:

https://github.com/material-components/material-components-ios/blob/0f35751373fa197d8bd2ea4b760dfa196724f8e5/components/AppBar/src/MDCAppBarNavigationController.m#L198-L209

This algorithm will tend to pick up false positives, resulting in potentially unexpected behavior such as that described in https://github.com/material-components/material-components-ios/issues/5338.

We may want to add more heuristics to the algorithm to detect certain cases where scroll views shouldn't be determined as the tracking scroll view. Some things to explore:

- The bounds of the scroll view.
- The content size of the scroll view.

Note that the MDCAppBarNavigationController inference logic happens when the view controller is pushed onto the navigation controller, so the scroll views may not have set a scroll view content size yet.

---
#### Internal data
- Associated internal bug: [b/117411059](http://b/117411059)

**Comment by material-mirror** [comment]
The internal issue [b/117411059](http://b/117411059) is now closed. This issue is being closed as a result.
