### ISSUE TITLE
[List] SelfSizingStereoCell should use MDCTypography instead of hardcoding its own font opacity

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#5348]
From the internal issue:

> SelfSizingStereoCell is currently using hardcoded values for the opacity of its title and detail labels:
> 
>     static const CGFloat kTitleColorOpacity = 0.87f;
>     static const CGFloat kDetailColorOpacity = 0.6f;
> 
> It should instead respectively use:
> 
>     [MDCTypography subheadFontOpacity] (0.87)
>     [MDCTypography captionFontOpacity] (0.54)

---

This is an internal issue. If you are a Googler, please visit [b/117395438](http://b/117395438) for more details.

**Comment by jpoumailloux** [comment]
fyi, a code change went in for this: https://github.com/material-components/material-components-ios/pull/5361 Let me know if you would like to have it reverted.

**Comment by jverkoey** [comment]
Ah! Yes please.
