### ISSUE TITLE
[BottomNavigation] Does not support dynamic type

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#5355]
From the internal issue:

> MDCBottomNavigationBar does not support dynamic type out of the box.
>
> If the itemTitleFont property is set to a font that gets automatically scaled on iOS 11+ (using methods similar to the ones in [1]), the text gets scaled, but starts getting clipped after a certain size and the icons are pushed out of the bar (see attached screenshots). This can be reproduced by using the "Larger Accessibility Sizes" switch in "Settings > General > Accessibility > Larger Text" and then choosing a value in the right half of the selector.

---

This is an internal issue. If you are a Googler, please visit [b/117323770](http://b/117323770) for more details.

---
#### Internal data
- Associated internal bug: [b/117323770](http://b/117323770)

**Comment by romoore** [comment]
This is intended behavior. We are matching UITabBar here and instead should support an API similar to `largeContentSizeImage` (https://github.com/material-components/material-components-ios/issues/4159)
