### ISSUE TITLE
[AppBar] Does AppBar give you Home Arrow ?

### ISSUE THREAD

**Issue by anuranBarman** [material-components/material-components-ios#5368]
I am using app bar in my view controllers. I am able to use hamburger icon as a leftItem in navigation controller but I was wondering if this gives a go to home arrow back button or not. I could not find it and it's also not mentioned in the example code. is it possible?

**Comment by jverkoey** [comment]
The AppBar component will automatically show a back icon when the app bar view controller is contained within a view controller that has been pushed onto a navigation controller with at least two items on the stack.

If the above doesn't answer your question then I may have misunderstood it. Please provide additional details or potentially a code example if that's the case.

**Comment by anuranBarman** [comment]
I have the following structure

NavigationViewController
--ViewController (holds the app bar)
---ContainerView (adds child view controllers)

Does this satisfy the requirements??

Only push is here for view controller which is holding the app bar to the
navigation bar.
