### ISSUE TITLE
[TextFields] clear button touch target is too small

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#5373]
This is an internal issue. If you are a Googler, please visit [b/116735800](http://b/116735800) for more details.

---
#### Internal data
- Associated internal bug: [b/116735800](http://b/116735800)

**Comment by jverkoey** [comment]
Un-assigning due to inactivity. Please re-assign if you are working on this.

**Comment by material-mirror** [comment]
The internal issue [b/116735800](http://b/116735800) is now closed. This issue is being closed as a result.

**Comment by jverkoey** [comment]
Reopening because the bug was confirmed by an internal client to still be active.
