### ISSUE TITLE
Point objc-diff back to upstream repo

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#538]
`scripts/install_objc_diff` will soon point to the `jverkoey/objc-diff` fork which includes a fix dealing with anonymous categories.

Ideally we'd be pointing upstream, but this is blocked until this pull request lands: https://github.com/mattstevens/objc-diff/pull/9

**Comment by ajsecord** [comment]
`scripts/install_objc_diff` has gone away, closing this out...
