### ISSUE TITLE
[Dialogs] Retain cycle between MDCAlertController and MDCDialogPresentationController

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#5396]
When trying to deallocate properties in our tests, I noticed that there are some retained objects apparently unconnected to the test application.

Looks like MDCAlertController and MDCDialogPresentationController are retaining each other.

![screen shot 2018-10-11 at 9 38 35 am](https://user-images.githubusercontent.com/1753199/46808426-50ab4900-cd3a-11e8-807a-d1a15c368fb3.png)

**Comment by andrewoverton** [comment]
![dialogs](https://user-images.githubusercontent.com/8020010/46812279-66247100-cd42-11e8-9619-67d8dcfe54c5.gif)

Things seem to be deallocated properly in the AlertComparison example at least.. Gif is a little blurry :/

**Comment by romoore** [comment]
This is an artifact of never dismissing the AlertController, even though it's never presented.

**Comment by romoore** [comment]
It may also be an artifact of the testing framework. I'm going to close this as obsolete unless we can produce it in an app.
