### ISSUE TITLE
Add an option to control spacing between [MDCTextField] /MDCTextInputControllerFilled text and floating placeholder.

### ISSUE THREAD

**Issue by EugeneEl** [material-components/material-components-ios#5406]
**## Feature Request/Suggestion**
I looked through the examples/doc but I didn't manage to find some property to control spacing between actual text in textfield and floating vertical hint placeholder (when MDCTextInputControllerFilled is used). 

**A clear and concise description of what the problem is:**
I want to control padding between actual entered text and floating placeholder.
As an assumption linespacing of attributed text should have an affect on this feature.
But as I see MDCTextInputControllerFilled provides only property for font. 
And when I directly set attributedPlaceholder for MDCTextField it has no effect because of MDCTextInputControllerFilled wrapper. 
I would like to have an option to make floating placeholder fully customizable as NSAttributedString or some insets to control padding between actual text and floating placeholder. 

Thanks.

---
#### Internal data
- Associated internal bug: [b/117675100](http://b/117675100)

**Comment by material-mirror** [comment]
The internal issue [b/117675100](http://b/117675100) is now closed. This issue is being closed as a result.
