### ISSUE TITLE
[Dialogs] Theme alert actions using semantic emphasis

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#5407]
From the internal issue:

> Creating an emphasis enum following the emphasis concept and using it to theme MDCAlertController actions.
>
> Buttons created for the actions will be themed differently, based on the different emphasis that was associated with the action when it was created.

---

This is an internal issue. If you are a Googler, please visit [b/117608629](http://b/117608629) for more details.

---
#### Internal data
- Associated internal bug: [b/117608629](http://b/117608629)
- Blocked by: https://github.com/material-components/material-components-ios/issues/5384

**Comment by jverkoey** [comment]
This was closed in https://github.com/material-components/material-components-ios/pull/5416
