### ISSUE TITLE
[BottomAppBar] MDCBottomAppBarView set FAB to overlap instead of having an inset (cutout)

### ISSUE THREAD

**Issue by calhouncole** [material-components/material-components-ios#5414]
## Feature Request/Suggestion

I'd like to be able to set my BottomBar's FAB with overlay instead of the default circular cutout. It appears that this is possible on Android, but I haven't seen any documentation on how to do so for iOS.

Current code:

        self.bottomBar.floatingButton.backgroundColor = UIColor.primaryColor
        self.bottomBar.floatingButton.setTitle("Purchase", for: .normal)
        self.bottomBar.floatingButton.mode = .expanded
        self.bottomBar.floatingButton.accessibilityHint = "Purchase"
        self.bottomBar.floatingButton.accessibilityLabel = "Purchase"
     
        let barButtonLeadingItem = UIBarButtonItem(
            image: UIImage(named:"settingsLogo"),
            style: .plain,
            target: self,
            action: #selector(self.onMenuButtonTapped))
        
        let barButtonTrailingItem = UIBarButtonItem(
            image: UIImage(named: "navigationLogo"),
            style: .plain,
            target: self,
            action: #selector(self.onNavigationButtonTapped))
        
        self.bottomBar.leadingBarButtonItems = [ barButtonLeadingItem ]
        self.bottomBar.trailingBarButtonItems = [ barButtonTrailingItem ]

The above code produces the attached screen shot: 
![screenshot 2018-10-12 16 57 54](https://user-images.githubusercontent.com/5141235/46898660-06ac8b00-ce40-11e8-9046-2de4add2f8bf.png)

You can see that the default inset is still visible. If this is already possible, would love to be pointed in the right direction. Thanks!

## Additional context

---
#### Internal data
- Associated internal bug: [b/117757756](http://b/117757756)

**Comment by peterfriese** [comment]
This issue is resolved by #5958.

**Comment by material-mirror** [comment]
The internal issue [b/117757756](http://b/117757756) is now closed. This issue is being closed as a result.

**Comment by romoore** [comment]
This was reverted in the latest release. Reopening.

**Comment by material-mirror** [comment]
The internal issue [b/117757756](http://b/117757756) is now closed. This issue is being closed as a result.
