### ISSUE TITLE
[Chips] Input Chips example hides Chipfield behind AppBar

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#5424]
The AppBar is hiding the ChipField on an iPhone 4S Simulator (iOS 9.0).

![simulator screen shot - iphone 4s - 2018-10-15 at 14 47 06](https://user-images.githubusercontent.com/1753199/46971173-41553400-d089-11e8-8413-7bc9844b3225.png)
![screen shot 2018-10-15 at 2 47 49 pm](https://user-images.githubusercontent.com/1753199/46971197-4ca85f80-d089-11e8-8f6c-230c36111ce8.png)

---
#### Internal data
- Associated internal bug: [b/117819718](http://b/117819718)

**Comment by material-mirror** [comment]
The internal issue [b/117819718](http://b/117819718) is now closed. This issue is being closed as a result.
