### ISSUE TITLE
[ProgressView] option to set corner radius for active progressView

### ISSUE THREAD

**Issue by EugeneEl** [material-components/material-components-ios#5429]
## Feature Request/Suggestion
Add an option to set corner radius for active tracking view. 

## Description 
My progress view should have corner radiuses (non-linear progress).
I want to have some corner radius for the progress view, but if I set corner radius for the progressView itself it doesn't have any effect on the active tracking progress view.
As I see in the Xcode ViewDebugger  MDCProgressView instance has two subviews.
One of them acts as an active progress indicatory view. 
As a temp hack I'm iterating through the subviews and setting corner radius for all of them.

## Additional context
Without a hack for subviews:
<img width="54" alt="2018-10-17 9 07 14" src="https://user-images.githubusercontent.com/7325854/47065566-2222e780-d1ec-11e8-964b-565a8f46e6d9.png">

With a hack for subviews:
<img width="55" alt="2018-10-17 9 04 50" src="https://user-images.githubusercontent.com/7325854/47068356-be50ec80-d1f4-11e8-99c7-a75570288533.png">

---
#### Internal data
- Associated internal bug: [b/117869851](http://b/117869851)

**Comment by romoore** [comment]
Looks like this is complete. Closing.
