### ISSUE TITLE
[Chips] Allow MDCChipView to scale image down to fit chip

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#5431]
From the internal issue:

> MDCChipView currently resizes the entire chip to fit the width and height of the current image of the image view.
> 
> Clients which don't control the size of the image they receive would rather have MDCChipView scale the image down to fit the size of the chip view.
> 
> We should either:
> 
> 1) Add an option to MDCChipView to control the image scaling behavior (scale image down to fit chip or size chip to fit image), or
> 2) Change the default behavior of MDCChipView to scale the image down to fit the chip
> 
> I think 2) is probably better, but it will change existing behavior, which will likely cause problems, so 1) is safer.

---

This is an internal issue. If you are a Googler, please visit [b/117871189](http://b/117871189) for more details.

---
#### Internal data
- Associated internal bug: [b/117871189](http://b/117871189)

**Comment by fustalol** [comment]
Any news on this?

**Comment by romoore** [comment]
No updates to report at the moment, @fustalol . I don't believe this issue is in our backlog of upcoming work.  However if you think you have a solution that allows existing clients to keep the current behavior but also allows for this solution, please feel free to open a Pull Request and we'll happily review!

**Comment by material-mirror** [comment]
The internal issue [b/117871189](http://b/117871189) is now closed. This issue is being closed as a result.

**Comment by chamitha** [comment]
Any update on this?
