### ISSUE TITLE
Material components should observe `contentMode` and react appropriately

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#5435]
## Feature Request/Suggestion
MDC components should observe the `contentMode` property of UIView in order to adjust their contents' layout and presentation.

This suggestion is not fully fleshed-out, but would allow us to solve some layout/sizing problems consistently and using UIKit APIs already available.

### Example: Chips
`UIViewContentModeLeft`: The chip content will be left-aligned (if it is too small to meet minimum size guidelines. It will increase in size to meet the contents' intrinsic content size.
`UIViewContentModeScaleAspectFill`: The chip will grow to meet the label (text) content requirements, but the images will be scaled to fill.
`UIViewContentModeScaleAspectFit`: The chip will grow to meet the label (text) content requirements, but the images will be scaled to aspect fit. 

### Example: Lists/Stereo Cell
`UIViewContentModeTop`: 
* If the cell's height is too short to fit the content, the bottom will be clipped. 
* If the cell's height is too tall for the content, the content will be pinned to the top.  
* If the cell's width is too narrow to fit the content, the text will be truncated using .Natural alignment.  * Text will be .Natural aligned. 

`UIViewContentModeBottomRight`: 
* If the cell's height is too short to fit the content, the top will be clipped. 
* If the cell's height is too tall, the content will be pinned to the bottom of the cell. 
* If the cell's width is too narrow to fit the content, the beginning of the text will be truncated.  
* If the cell's width is too wide for the content, the extra space is afforded to the text.  
* Text will be trailing-aligned (right aligned in LTR).  

`UIViewContentModeScaleToFill`: 
* If the cell's height is too short to fit the content, the images will be scaled down, text lines reduced, detailLabel may be removed.
* If the cell's height is too tall to fit the content, the images are scaled up, text lines are increased, text labels are vertically centered.
* If the cell's width is too narrow to fit the content, the images are scaled down (to a minimum), text is truncated using .Natural alignment.
* If the cell's width is too wide to fit the content, the images are scaled up, text lines are increased, and text labels will be vertically centered.

---
#### Internal data
- Associated internal bug: [b/117973317](http://b/117973317)

**Comment by material-mirror** [comment]
The internal issue [b/117973317](http://b/117973317) is now closed. This issue is being closed as a result.
