### ISSUE TITLE
[Dialogs] Followup work: changing buttons/actions memory structure

### ISSUE THREAD

**Issue by galiak11** [material-components/material-components-ios#5447]
Issue: b/118394802

This is a followup work for PR #5416, which includes the following items:

1.  Refactoring the list of actions and buttons in MDCActionManager to use the ActionUserInfo object below, instead of NSMapTable, for simplicity, and to avoid relying on opaque comparison. I've pasted the original discussion below for reference.
```objc
interface ActionUserInfo: NSObject {
  initWithAction:
  property(readonly) action;
  property(readwrite nullable) button;
}
```

_Originally posted by @jverkoey in https://github.com/material-components/material-components-ios/pull/5416_

Copied discussion from: https://github.com/material-components/material-components-ios/pull/5416#discussion_r225519669:

![image](https://user-images.githubusercontent.com/2329102/47228722-e9257700-d393-11e8-8fec-317de5ee7215.png)

2. "buttonsInActionOrder":  Consistently return buttons for all actions in any API that accesses buttons, at any time of the Dialog's life cycle.  

Currently, buttons are created at presentation time, or when "buttonForAction" is called before presentation. As a result, "buttonsInActionOrder" may or may not return a button, depending if "buttonForAction" had been called before or not.

3. Renaming "sortedActions" method to "buttonsInActionOrder" (**DONE**):

From:
- (NSArray<MDCButton *> *)sortedButtons;

To:
- (NSArray<MDCButton *> *)buttonsInActionOrder;

Original discussion:

![image](https://user-images.githubusercontent.com/2329102/47228886-5cc78400-d394-11e8-838d-787b9d8572b9.png)

4. Moving ButtonForAction to a separate category header (**DONE**).  Original discussion:
```
Similar to UIGestureRecognizer's subclassing header UIGestureRecognizerSubclass.h, this 
API is a good example of something that we may want to move to a separate category 
header so that clients don't have access to it in their day-to-day use of the Dialogs component.

In order to access this API, a client will explicitly opt-in to importing the relevant header.

Practically speaking, this would mean adding an MDCAlertController+ButtonForAction.h 
header and not including that header in the component's umbrella header.
```

---
#### Internal data
- Associated internal bug: [b/117973250](http://b/117973250)

**Comment by romoore** [comment]
The "link to discussion" link isn't working. Can you please post the reasons behind providing this custom tuple?

**Comment by material-mirror** [comment]
The internal issue [b/117973250](http://b/117973250) is now closed. This issue is being closed as a result.
