### ISSUE TITLE
[Dialogs] Presentation unexpectedly changing to full screen

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#5452]
In a certain case, a presented view controller switches to a full screen presentation.

Reproducible in an internal client.

Present a custom view controller.
From that controller navigate to a webview by opening a URL.
Return to the original app.
The original view controller is now presented full screen instead of as a dialog.

---
#### Internal data
- Associated internal bug: [b/117985863](http://b/117985863)

**Comment by ianegordon** [comment]
First thing to do is build a dragon that demonstrates the issue.

**Comment by ianegordon** [comment]
MDC appears to be working as expected based on the the behavior of:
Dragons > Dialogs > Dialogs > Open URL

![dragonsopenurl](https://user-images.githubusercontent.com/1121006/47230421-28ee5d80-d398-11e8-83d2-43534c1cc845.gif)

**Comment by material-mirror** [comment]
The internal issue [b/117985863](http://b/117985863) is now closed. This issue is being closed as a result.
