### ISSUE TITLE
[Chips] Examples are missing "ic_done" in the assets catalog

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#5459]
The Chips examples use "ic_done" for checked Chips (for example in the Filter Chips example). However, this asset is not in the Chips asset catalog. This causes things to break when building the Chips into a separate bundle from the main app bundle.

**Expected**

<img width="394" alt="screen shot 2018-10-19 at 1 38 14 pm" src="https://user-images.githubusercontent.com/1753199/47234574-3f9ab180-d3a4-11e8-80a2-eceb12b3b78e.png">

**Actual**

<img width="380" alt="screen shot 2018-10-19 at 1 33 28 pm" src="https://user-images.githubusercontent.com/1753199/47234355-95bb2500-d3a3-11e8-8ad7-4b9b29b6fcde.png">

b/117981994

---
#### Internal data
- Associated internal bug: [b/117981994](http://b/117981994)

**Comment by material-mirror** [comment]
The internal issue [b/117981994](http://b/117981994) is now closed. This issue is being closed as a result.
