### ISSUE TITLE
MDCTextField not displaying correctly.

### ISSUE THREAD

**Issue by Dellybro** [material-components/material-components-ios#5477]
> For usage questions: ask on [Stack  Overflow](https://stackoverflow.com/questions/tagged/material-components+ios).

I am using Storyboards, and when i subclass a uibutton to be an MDCTextField it looks very messy and doesn't work as expected.

## Reproduction steps

Setup MDCTextfield on a storyboard.

## Expected behavior

I expect the floating label to float and the line not to move, along with some sort of animation

## Actual behavior

When the textfield is clicked the line for the textfield moves up and the floating label doesn't move.

## Platform (please complete the following information)

iOS 12

## Additional context

Here is a picture and example code

        self.emailField.isEnabled = true;
        let textFieldControllerFloating = MDCTextInputControllerUnderline(textInput: self.emailField);
        textFieldControllerFloating.helperText = "Enter a name"
        textFieldControllerFloating.leadingUnderlineLabelTextColor = UIColor.darkGray       // The helper text
        textFieldControllerFloating.trailingUnderlineLabelTextColor = UIColor.green
        textFieldControllerFloating.inlinePlaceholderColor = UIColor.lightGray              // inline label
        textFieldControllerFloating.borderFillColor = UIColor.white
        textFieldControllerFloating.isFloatingEnabled = true
        
        textFieldControllerFloating.activeColor = UIColor.orange                            // active label & underline
        textFieldControllerFloating.normalColor = UIColor.lightGray                         // default underline
        textFieldControllerFloating.errorColor = UIColor.red

<img width="334" alt="screen shot 2018-10-22 at 2 50 23 pm" src="https://user-images.githubusercontent.com/10732096/47321521-e6cc5280-d609-11e8-82c5-32fa0c284969.png">
<img width="319" alt="screen shot 2018-10-22 at 2 50 49 pm" src="https://user-images.githubusercontent.com/10732096/47321522-e6cc5280-d609-11e8-9c75-6f6c70d8bdf9.png">

---
#### Internal data
- Associated internal bug: [b/118276811](http://b/118276811)

**Comment by Dellybro** [comment]
So based on the labels, I assume this is an interface builder issue, is there any more information I can get at this time?

Are Google Material UI Components for iOS not storyboard/interface builder friendly?

**Comment by romoore** [comment]
Are you retaining your MDCTextInputController object in a property? If not, I believe it will be deallocated once your method goes out of scope.

**Comment by romoore** [comment]
You can see an example of IB support in `TextFieldInterfaceBuilderExample.m`

**Comment by Dellybro** [comment]
The solution was what @romoore said. I must retain the MDCTextInputController

**Comment by romoore** [comment]
Thanks for following-up, @Dellybro !
