### ISSUE TITLE
[Dialogs] MDCAlertAction's initializer methods should use self

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5481]
https://github.com/material-components/material-components-ios/blob/5dafdbaa86031bd15d43ef13ba8f506e254a6910/components/Dialogs/src/MDCAlertController.m#L39-L50

The initializers above refer to `MDCAlertAction` instead of `self`, meaning subclasses of MDCAlertAction cannot call through to these methods to create an instance of the subclass. The ramifications of this are that clients have been exposing our private init method instead.

We should be using `self` in these methods so that subclasses can make use of the public initializers.

Not in scope for this change: marking the action as subclassing_restricted. If we wish to pursue that as a restriction we will need to do so as a separate body of work that involves migrating client teams accordingly.

---
#### Internal data
- Associated internal bug: [b/118277770](http://b/118277770)

**Comment by romoore** [comment]
This is a "won't fix" as the documentation clearly states that subclassing is unsupported.

>  MDCAlertController class is intended to be used as-is and does not support subclassing. The view
 hierarchy for this class is private and must not be modified.
