### ISSUE TITLE
[Banner] Make Banner be a Beta component

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#5488]
This was filed as an internal issue. If you are a Googler, please visit [b/118201133](http://b/118201133) for more details.

---
#### Internal data
- Associated internal bug: [b/118201133](http://b/118201133)
- Blocked by: https://github.com/material-components/material-components-ios/issues/7076
- Blocked by: https://github.com/material-components/material-components-ios/issues/5483
- Blocked by: https://github.com/material-components/material-components-ios/issues/5485
- Blocked by: https://github.com/material-components/material-components-ios/issues/5241

**Comment by romoore** [comment]
Pretty sure Banner is in Beta.
