### ISSUE TITLE
Typography unit tests are occasionally flakey

### ISSUE THREAD

**Issue by randallli** [material-components/material-components-ios#549]
There appear to be some unit test failures when I run off develop sha(841b2ade97f2a4de7e82b2d9451bc791f2777ab7).

It stopped when I switched schemes and ran unit tests to the unit test scheme in xcode. I would have thought that running the tests in xcode would have no change in behavior of the arc unit tests.

   BROKEN  MDCUnitTests
/Users/randallli/code/openSource/material-components-ios/components/Typography/tests/unit/TypographyTests.m:224: error: -[TypographyFontLoaderSetTest testSubheadFont] : failed: caught "NSInternalInconsistencyException", "Font Roboto-Regular not found in location: file:///Users/randallli/Library/Developer/Xcode/DerivedData/MDCCatalog-dytltotxpztkcybfballeldqmzqq/Build/Intermediates/CodeCoverage/MDCUnitTests/Products/Debug-iphonesimulator/MaterialComponents.framework/MaterialRobotoFontLoader.bundle/Roboto-Regular.ttf."
   FAIL  TypographyFontLoaderSetTest::SubheadFont
2016-05-31 15:26:38.048 xctest[29526:10850574] **\* Assertion failure in -[MDCRobotoFontLoader regularFontOfSize:], components/RobotoFontLoader/src/MDCRobotoFontLoader.m:110
(
    0   CoreFoundation                      0x0000000105f60e65 **exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x00000001059d7deb objc_exception_throw + 48
    2   CoreFoundation                      0x0000000105f60cca +[NSException raise:format:arguments:] + 106
    3   Foundation                          0x00000001056234de -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
    4   MaterialComponents                  0x000000010f9e5153 -[MDCRobotoFontLoader regularFontOfSize:] + 531
    5   MaterialComponents                  0x000000010f9f914d +[MDCTypography subheadFont] + 93
    6   MaterialComponentsUnitTests         0x000000010fb247f5 -[TypographyFontLoaderSetTest testSubheadFont] + 69
    7   CoreFoundation                      0x0000000105e4f1cc __invoking_** + 140
    8   CoreFoundation                      0x0000000105e4f01e -[NSInvocation invoke] + 286
    9   XCTest                              0x0000000105476080 **24-[XCTestCase invokeTest]_block_invoke_2 + 159
    10  XCTest                              0x00000001054a9b14 -[XCTestContext performInScope:] + 184
    11  XCTest                              0x0000000105475fd0 -[XCTestCase invokeTest] + 169
    12  XCTest                              0x000000010547646b -[XCTestCase performTest:] + 443
    13  XCTest                              0x0000000105474131 -[XCTestSuite performTest:] + 377
    14  XCTest                              0x0000000105474131 -[XCTestSuite performTest:] + 377
    15  XCTest                              0x0000000105474131 -[XCTestSuite performTest:] + 377
    16  XCTest                              0x0000000105461181 __25-[XCTestDriver _runSuite]_block_invoke + 51
    17  XCTest                              0x0000000105481b5b -[XCTestObservationCenter _observeTestExecutionForBlock:] + 615
    18  XCTest                              0x00000001054610cd -[XCTestDriver _runSuite] + 408
    19  XCTest                              0x0000000105461e2c -[XCTestDriver _checkForTestManager] + 263
    20  XCTest                              0x00000001054aae99 _XCTestMain + 628
    21  xctest                              0x00000001053e8242 xctest + 8770
    22  libdyld.dylib                       0x000000010832192d start + 1
    23  ???                                 0x0000000000000005 0x0 + 5
)
   PASS   <1ms★  TypographyFontLoaderSetTest::SubheadFontOpacity
   PASS   <1ms★  TypographyFontLoaderSetTest::SystemFontBody1Font
   PASS   <1ms★  TypographyFontLoaderSetTest::SystemFontBody2Font
   PASS   <1ms★  TypographyFontLoaderSetTest::SystemFontButtonFont
   PASS   <1ms★  TypographyFontLoaderSetTest::SystemFontCaptionFont
   PASS   <1ms★  TypographyFontLoaderSetTest::SystemFontDisplay1Font
   PASS   <1ms★  TypographyFontLoaderSetTest::SystemFontDisplay2Font
   PASS   <1ms★  TypographyFontLoaderSetTest::SystemFontDisplay3Font
   PASS   <1ms★  TypographyFontLoaderSetTest::SystemFontDisplay4Font
   PASS   <1ms★  TypographyFontLoaderSetTest::SystemFontHeadlineFont
   PASS   <1ms★  TypographyFontLoaderSetTest::SystemFontSubheadFont
   PASS   <1ms★  TypographyFontLoaderSetTest::SystemFontTitleFont
   BROKEN  MDCUnitTests
/Users/randallli/code/openSource/material-components-ios/components/Typography/tests/unit/TypographyTests.m:214: error: -[TypographyFontLoaderSetTest testTitleFont] : failed: caught "NSInternalInconsistencyException", "Font Roboto-Medium not found in location: file:///Users/randallli/Library/Developer/Xcode/DerivedData/MDCCatalog-dytltotxpztkcybfballeldqmzqq/Build/Intermediates/CodeCoverage/MDCUnitTests/Products/Debug-iphonesimulator/MaterialComponents.framework/MaterialRobotoFontLoader.bundle/Roboto-Medium.ttf."
   FAIL  TypographyFontLoaderSetTest::TitleFont
2016-05-31 15:26:38.059 xctest[29526:10850574] **\* Assertion failure in -[MDCRobotoFontLoader mediumFontOfSize:], components/RobotoFontLoader/src/MDCRobotoFontLoader.m:131
(
    0   CoreFoundation                      0x0000000105f60e65 __exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x00000001059d7deb objc_exception_throw + 48
    2   CoreFoundation                      0x0000000105f60cca +[NSException raise:format:arguments:] + 106
    3   Foundation                          0x00000001056234de -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
    4   MaterialComponents                  0x000000010f9e5543 -[MDCRobotoFontLoader mediumFontOfSize:] + 531
    5   MaterialComponents                  0x000000010f9f908d +[MDCTypography titleFont] + 93
    6   MaterialComponentsUnitTests         0x000000010fb235d5 -[TypographyFontLoaderSetTest testTitleFont] + 69
    7   CoreFoundation                      0x0000000105e4f1cc __invoking_** + 140
    8   CoreFoundation                      0x0000000105e4f01e -[NSInvocation invoke] + 286
    9   XCTest                              0x0000000105476080 __24-[XCTestCase invokeTest]_block_invoke_2 + 159
    10  XCTest                              0x00000001054a9b14 -[XCTestContext performInScope:] + 184
    11  XCTest                              0x0000000105475fd0 -[XCTestCase invokeTest] + 169
    12  XCTest                              0x000000010547646b -[XCTestCase performTest:] + 443
    13  XCTest                              0x0000000105474131 -[XCTestSuite performTest:] + 377
    14  XCTest                              0x0000000105474131 -[XCTestSuite performTest:] + 377
    15  XCTest                              0x0000000105474131 -[XCTestSuite performTest:] + 377
    16  XCTest                              0x0000000105461181 __25-[XCTestDriver _runSuite]_block_invoke + 51
    17  XCTest                              0x0000000105481b5b -[XCTestObservationCenter _observeTestExecutionForBlock:] + 615
    18  XCTest                              0x00000001054610cd -[XCTestDriver _runSuite] + 408
    19  XCTest                              0x0000000105461e2c -[XCTestDriver _checkForTestManager] + 263
    20  XCTest                              0x00000001054aae99 _XCTestMain + 628
    21  xctest                              0x00000001053e8242 xctest + 8770
    22  libdyld.dylib                       0x000000010832192d start + 1
    23  ???                                 0x0000000000000005 0x0 + 5
)
   PASS   <1ms★  TypographyTests::FontLoaderIsRoboto

**Comment by ianegordon** [comment]
Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄
