### ISSUE TITLE
[Cards] Add theming snapshot tests to Cards

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#5495]
Definition of done:

- There are snapshot tests for Cards demonstrating a "baseline themed" card, and a "custom themed" card.

---
#### Internal data
- Associated internal bug: [b/118206235](http://b/118206235)
- Blocked by: https://github.com/material-components/material-components-ios/issues/5496

**Comment by jverkoey** [comment]
This landed in https://github.com/material-components/material-components-ios/pull/6049.
