### ISSUE TITLE
[ListItems] Add Stereo Cell example showing mixed RTL and LTR text.

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#5499]
## Feature Request/Suggestion

An example for the Stereo cell should show mixed usage of LTR and RTL languages. Not within a single label, but across title/description labels.  For example: title in Spanish, description in Hebrew.  Another example: title in Arabic, description in Japanese.

---
#### Internal data
- Associated internal bug: [b/118315032](http://b/118315032)

**Comment by material-mirror** [comment]
The internal issue [b/118315032](http://b/118315032) is now closed. This issue is being closed as a result.
