### ISSUE TITLE
[CocoaPods] adding the framework search paths to the runpath search paths to fix IB_DESIGNABLE auto layout rendering errors

### ISSUE THREAD

**Issue by majid701** [material-components/material-components-ios#5518]
Found this in #2961

## Reproduction steps

I'm not quiet sure how to reproduce it. It just popped in one of my storyboards. I'm not even using any of the material components in that particular storyboard

## Expected behavior

There should be no error and the storyboard should render properly

## Actual behavior

Storyboard doesn't render because of this error!

## Platform (please complete the following information)

 - Device: iPhoneX
 - OS: iOS12.0
 - Xcode: 10.0

Any way to fix this?

---
#### Internal data
- Associated internal bug: [b/118481658](http://b/118481658)

**Comment by material-mirror** [comment]
The internal issue [b/118481658](http://b/118481658) is now closed. This issue is being closed as a result.
