### ISSUE TITLE
[ListItems] Self Sizing Stereo Cell Typical Use example hides top cell behind AppBar

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#5521]
Opening the example shows the first cell "stuck" behind the AppBar. Probably some bug related to detecting the content offset of the collection view.

![img_0001 1](https://user-images.githubusercontent.com/1753199/47507373-15337300-d840-11e8-8b99-c762fa418345.PNG)

---
#### Internal data
- Associated internal bug: [b/118481130](http://b/118481130)

**Comment by material-mirror** [comment]
The internal issue [b/118481130](http://b/118481130) is now closed. This issue is being closed as a result.
