### ISSUE TITLE
[Cards] MDCCard and MDCCardCollectionCell have no interface documentation

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#5544]
Neither `MDCCard` nor `MDCCardCollectionCell` have documented interfaces, so it is difficult to understand the class's purpose and expected use by clients.

Ideally the documentation would:
* Explain what the class is, perhaps providing usage examples.
* Explain how it should be used by clients (subclassing, composition, APIs?).

---
#### Internal data
- Associated internal bug: [b/118623430](http://b/118623430)

**Comment by material-mirror** [comment]
The internal issue [b/118623430](http://b/118623430) is now closed. This issue is being closed as a result.
