### ISSUE TITLE
[TextFields] "Storyboard" example is entering an infinite loop

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#5549]
On my iPhone 4S/iOS 9.3.5 test device, opening the "Storyboard" example in the Dragons app causes an infinite loop. The simulator doesn't seem to resymbolicate in Instruments at the moment.

|iPhone 4s/iOS 9.3.5|iPhone 6/iOS 9.0 (Simulator)|iPad Mini 4/iOS 10.3.2|
|--|--|--|
|![screen shot 2018-10-29 at 1 17 26 pm](https://user-images.githubusercontent.com/1753199/47667704-0a991680-db7d-11e8-83fc-fb534618299f.png)|![screen shot 2018-10-29 at 1 22 57 pm](https://user-images.githubusercontent.com/1753199/47668017-c4908280-db7d-11e8-9fe3-defb1f07e11a.png)|![screen shot 2018-10-29 at 1 19 30 pm](https://user-images.githubusercontent.com/1753199/47667917-85fac800-db7d-11e8-98b9-55ca377465d7.png)|

---
#### Internal data
- Associated internal bug: [b/118761205](http://b/118761205)

**Comment by material-mirror** [comment]
The internal issue [b/118761205](http://b/118761205) is now closed. This issue is being closed as a result.
