### ISSUE TITLE
Extract material-like colors from images

### ISSUE THREAD

**Issue by rustyshelf** [material-components/material-components-ios#557]
Material Design features colors heavily. One of the nice things recently added to Android is the Palette library. This allows you to retrieve colors from a bitmap image so that you can do interesting and fun things in your UI with them. For example in Pocket Casts we use it to change background colors of views and tint buttons. It's subtle but really nice.
https://developer.android.com/reference/android/support/v7/graphics/Palette.html

I'd love to have an iOS version of this library. I've talked to a few people at Google and apparently there's a closed source one used internally, so that could be a good starting point?

**Comment by jonathanzong** [comment]
@ajsecord is there still a need for this? Before coming to Google I had made a swift clone of the Palette API which could possibly be cleaned up and adapted for use: https://github.com/jonathanzong/SwiftMaterialPalette

**Comment by ianegordon** [comment]
Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄
