### ISSUE TITLE
Change MDCFlexibleHeaderView to use MDCShadowLayer

### ISSUE THREAD

**Issue by ajsecord** [material-components/material-components-ios#558]
This is surprising to users who expect components in the Material Components library to actually obey the spec. I see two options:
1. Document why in some prominent place.
2. Just use MDCShadowLayer.

**Comment by ianegordon** [comment]
It may be somewhat that we've received very few (possible zero) complaint about how the Flexible Header is matching the Material Guidelines.

Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄
