### ISSUE TITLE
Rename `MDCAppBarButtonBarBuilder` in `MDCBarButtonItemBuilder` or `MDCBarButtonBuilder`

### ISSUE THREAD

**Issue by Arcank** [material-components/material-components-ios#559]
`MDCAppBarButtonBarBuilder` should probably not mention `AppBar` in its name, since it's in the `ButtonBar` component.

---
#### Internal data
- Associated internal bug: [b/117179550](http://b/117179550)

**Comment by material-mirror** [comment]
The internal issue [b/117179550](http://b/117179550) is now closed. This issue is being closed as a result.
