### ISSUE TITLE
AppBar handles in-call statusbar incorrectly

### ISSUE THREAD

**Issue by jpsachse** [material-components/material-components-ios#563]
I know, statusbar handling is hard. Nonetheless, the AppBar handles the statusbar incorrectly (or at least inconsistently), when the app gets started while the in-call statusbar is visible. Then, all views contained in the AppBar are pushed down by 20 points (the amount that gets added to the statusbar's height).

[I have attached an example project](https://github.com/google/material-components-ios/files/301512/InCallStatusbarTest.zip) to demonstrate the issue. To reproduce, start the app normally on an iPhone (simulator works best) and scroll the gray scrollview. The back button stays, where it is, even when the AppBar expands. Toggle the in-call statusbar (sim: CMD + Y) and retry – everything still works as expected.

Now kill the app and restart it, while still having the in-call statusbar visible. This time, the arrow actually moves down by 20 points, when the AppBar expands. This is especially cumbersome if you have an additional view that is supposed to be behind the statusbar in order to make it readable (e.g., when using a background image for the AppBar), which then gets pushed below the in-call statusbar as well.

**Comment by garrettmurray** [comment]
What is the status of this? This affects us still, curious to see when it might be resolved.

**Comment by jverkoey** [comment]
This should be resolved when `inferTopSafeAreaInsetFromViewController` is enabled.
