### ISSUE TITLE
[BottomAppBar] Clean up unit test for path animation

### ISSUE THREAD

**Issue by codeman7** [material-components/material-components-ios#5633]
#5611 was merged in order to make the release so it was rushed. The test added in that PR 
[`- (void)testPathToAndFromEqualNumberOfPoints`](https://github.com/material-components/material-components-ios/blob/7b51a89030ec32d617e11794adfd50741aa3e951/components/BottomAppBar/tests/unit/BottomAppBarTests.m#L102) need to be cleaned up to test all iOS versions. 

Currently this test only tests against iOS 11+, and should test for all supported versions of iOS.
The limitation of OS version can be found in  [`- (int)numberOfPointsInPath:(UIBezierPath *)bezierPath`](https://github.com/material-components/material-components-ios/blob/7b51a89030ec32d617e11794adfd50741aa3e951/components/BottomAppBar/tests/unit/BottomAppBarTests.m#L135) a fix for this would be to use [CGPathApply](https://developer.apple.com/documentation/coregraphics/1411203-cgpathapply?language=objc) which was made available in iOS 2.0+ instead of [CGPathApplyWithBlock](https://developer.apple.com/documentation/coregraphics/2873218-cgpathapplywithblock?language=objc). Additionally the [angles](https://github.com/material-components/material-components-ios/blob/7b51a89030ec32d617e11794adfd50741aa3e951/components/BottomAppBar/tests/unit/BottomAppBarTests.m#L120-L121) aren't right for the test and those can be cleaned up.

---
#### Internal data
- Associated internal bug: [b/119180164](http://b/119180164)

**Comment by material-mirror** [comment]
The internal issue [b/119180164](http://b/119180164) is now closed. This issue is being closed as a result.
