### ISSUE TITLE
Look into editing text of UIBarButtonItem

### ISSUE THREAD

**Issue by eli8527** [material-components/material-components-ios#565]
In CollectionsEditingExample, the Ink animation does not finish firing because we are swapping out the UIBarButtonItem labeled "Edit" with another labeled "Cancel". 

This occurs here:

```
- (void)toggleEditMode:(id)sender {
  BOOL isEditing = self.editor.isEditing;
  [self updatedRightBarButtonItem:!isEditing];
  [self.editor setEditing:!isEditing animated:YES];
}
```

Look into how one might edit the title of the UIBarButtonItem rather than swapping it out to preserve the animations.

**Comment by jverkoey** [comment]
Duplicate of https://github.com/material-components/material-components-ios/issues/266.
