### ISSUE TITLE
MDCShadowLayer - Rendering / Performance

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#570]
If you rotate or resize a UIView with an MDCShadowLayer the rendering can noticeably lag.

An easy way to see this is to create a UIView with an MDCShadowLayer and a second UIView with a standard shadowLayer.

Animate a large. identical change in the size of the UIViews.  The one with MDCShadowLayer will have slow performance.

Note that if you enable Slow Animations in the simulator you will not see the issue.

---
#### Internal data
- Associated internal bug: [b/117179468](http://b/117179468)

**Comment by ianegordon** [comment]
Possibly a dupe of #1287

**Comment by material-mirror** [comment]
The internal issue [b/117179468](http://b/117179468) is now closed. This issue is being closed as a result.
