### ISSUE TITLE
MaterialComponents named Dialog should not dismiss when tapped outside Dialog view.

### ISSUE THREAD

**Issue by SamboVisal** [material-components/material-components-ios#5726]
## Dialog view should not dismiss when user taps outside actions button in Dialog View

When the view has been pop up on screen when i touch outside that pop up view and then that view has been dismiss. I don't want that to happen in my app.

I don't want user to click outside popup view to dismiss that popup view. What i want i just want user to click on action button that i provide for user's choice then the view should be dismiss when click on that action button only.

Really glade that you help.

Here is what i have done so far

       `let alert = MDCAlertController(title: title, message: message)
        
        let okayAction = MDCAlertAction(title: "Okay") { (action) in
            
            if title == "Logout" {
                UserDefaults.standard.setIsLoggedIn(value: false)
                UserDefaults.standard.setUserId(value: "")
                UserDefaults.standard.setupEnableBadgeView(value: false)
                //IMAGELOAD = false
                try! Auth.auth().signOut()
                
                self.tabBarController?.selectedIndex = 0
            } else {
                let loginController = UINavigationController(rootViewController: LoginViewController())
                self.present(loginController, animated: true, completion: nil)
            }
            
        }
        let cancelAction = MDCAlertAction(title: "Cancel", handler: nil)
        alert.addAction(okayAction)
        alert.addAction(cancelAction)
        
        self.present(alert, animated: true, completion: nil)`

When Dialog has been presented on screen then, i tapped outside the Dialog view and the Dialog View just dismiss anyway. I want user click on one of those action buttons to dismiss or perform another taks.

**Comment by romoore** [comment]
@SamboVisal  were you able to find the solution you needed? `DialogsAlertViewController.m` is an example that prevent dismissing the Alert by tapping on the Scrim (background).  If you are using MDCDialogPresentationController (the default), you can set `dismissOnBackgroundTap = NO;`.

```objc
  // This code accesses the presentation controller and turns off dismiss on background tap.
  MDCDialogPresentationController *presentationController =
      materialAlertController.mdc_dialogPresentationController;
  presentationController.dismissOnBackgroundTap = NO;

  [self presentViewController:materialAlertController animated:YES completion:NULL];
```

**Comment by lisheng1219** [comment]
MDCDialogPresentationController

**Comment by lisheng1219** [comment]
I want to be in swift, how to use this MDCDialogPresentationController
To show my pop-up view
