### ISSUE TITLE
MDCCatalog Build Failed

### ISSUE THREAD

**Issue by linnnh** [material-components/material-components-ios#5748]
Hello,

A quick question — In Xcode, MDCCatalog was failed to build on my iPhone 7. 
Anyone also has issues installing the build?

## Reproduction steps

1. Download Zip of https://github.com/material-components/material-components-ios
2. In terminal, 
```
cd material-components-ios-develop/catalog/
pod update
open MDCCatalog.xcworkspace
```
3. In Xcode, select my Team ID. And select my iPhone device. And click run.
4. Xcode shows "Build Failed" and Code Signing Errors:

```
Code Signing Error: No account for team "EQHXZ8M8AV". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.
Code Signing Error: No profiles for 'com.google.mdc-catalog.MDCActionExtension' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'com.google.mdc-catalog.MDCActionExtension'.
Code Signing Error: Code signing is required for product type 'App Extension' in SDK 'iOS 12.1'

```

## Platform

 - Device: iPhone 7 (iOS 12) and iPhone XS Max (iOS 12)
 - Xcode Version: v10.0

---
#### Internal data
- Associated internal bug: [b/119546154](http://b/119546154)

**Comment by romoore** [comment]
I always have to disable "automatic management" of the provisioning Provisioning Profile and select my developer profile manually. I do it for the Catalog (Debug and Release configs) and the ActionExtension (Debug and Release configs).

1. Click on `MDCCatalog` in the Project Explorer
2. In the "General" tab, find "Signing" section
3. Uncheck "Automatically manage signing"
4. Choose your provisioning profile under "Signing (Debug)" and "Signing (Release)"
5. Switch to the "MDCActionExtension" target and repeat steps 2-4

**Comment by ajsecord** [comment]
Hi Linne—to install on your device you'll need to change the bundle ID to match your provisioning profile setup. The com.google.mdc-catalog.* bundle IDs are associated with those in the Google developer account and you won't be able to generate those profiles. Hopefully this documentation from Apple covers your use case from what I understand of it: https://help.apple.com/xcode/mac/current/#/dev60b6fbbc7

**Comment by linnnh** [comment]
Ahh okay, I see. Thanks a lot, @ajsecord and @romoore !
