### ISSUE TITLE
 [TextField] Error Text Overflows Text Field Width 

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#5762]
When setting MDCTextField error text to a long string, the error text runs past the width of the text field itself.

---
#### Internal data
- Associated internal bug: [b/119567486](http://b/119567486)
- Blocked by: https://github.com/material-components/material-components-ios/issues/2153

**Comment by enthuan** [comment]
Hi, is this feature still on the roadmap? I will soon need to make error label on multiple lines and I don't want to use another lib ;)
Thanks

**Comment by romoore** [comment]
I'll ask @randallli to reëvaluate the priority of this work in our backlog.

**Comment by kaal-dam** [comment]
Hello, did you have any idea of when this will be fixed ?

**Comment by zishanj** [comment]
Any update on this issue?

**Comment by sv02** [comment]
Any updates?

**Comment by Fernandez-Aldo** [comment]
How do I implement multiline error text?

**Comment by silvaric** [comment]
You have that feature at **v93.2.0**
```
MDCTextField *textField = [[MDCTextField alloc] init];
textField.leadingUnderlineLabel.numberOfLines = 0;
textField.leadingUnderlineLabel.lineBreakMode = NSLineBreakByWordWrapping;
```

**Comment by Fernandez-Aldo** [comment]
> You have that feature at **v93.2.0**
> 
> ```
> MDCTextField *textField = [[MDCTextField alloc] init];
> textField.leadingUnderlineLabel.numberOfLines = 0;
> textField.leadingUnderlineLabel.lineBreakMode = NSLineBreakByWordWrapping;
> ```
> 
> Release notes : https://github.com/material-components/material-components-ios/releases/tag/v93.2.0

Thanks Silvaric

**Comment by Fernandez-Aldo** [comment]
Is there a way to customize the border color of the texfield when setting errors?

**Comment by andrewoverton** [comment]
@Fernandez-Aldo for MDCTextFields you would do this by setting the `errorColor` on the controller
