### ISSUE TITLE
[Tabs] Review and refactor alignment support

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#5763]
The [Material Guidelines article for Tabs](https://material.io/design/components/tabs.html#fixed-tabs) now calls for several defined tabs alignments:

* Fixed Tabs - Full-view width, each item has equal width.
* Clustered Fixed Tabs - Each item has width equal to longest, tabs are clustered together.
    * Leading-aligned - Tabs are aligned to the leading edge of the view
    * Center-aligned - Tabs are aligned in the center of the view
    * Trailing-aligned - Tabs are aligned to the trailing edge of the view
* Scrollable Tabs - Each item is as wide as its content (plus some internal padding). The first item is "offset to signal that tabs are scrollable."

I believe we should revisit the Tabs APIs available to clients for positioning tabs within the Tab Bar. The guidance for each of these styles depends on things like available screen size, number of tabs, and a few other considerations. As a result, style may need to be determined dynamically at run-time rather than hard-coded at compile time. This could necessitate the use of a delegate or dedicated layout object that can be customized by the client.

---
#### Internal data
- Associated internal bug: [b/119771461](http://b/119771461)

**Comment by romoore** [comment]
We should prefer to support as few styles as we can, while still meeting the Guidelines requirements.  To support client customization and adaptation beyond the basic APIs, we could look into providing some kind of delegate API so that layout can be modified or overridden if necessary.

**Comment by randallli** [comment]
I think this is actionable

**Comment by material-mirror** [comment]
The internal issue [b/119771461](http://b/119771461) is now closed. This issue is being closed as a result.
