### ISSUE TITLE
[ActionSheet] can't update pod file

### ISSUE THREAD

**Issue by 22Round** [material-components/material-components-ios#5764]
can't install ActionSheet with pod

my pod file:

```
# Uncomment the next line to define a global platform for your project
 platform :ios, '11.2'

target 'FinTech' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FinTech

  pod 'Firebase'
  pod 'Firebase/Messaging'
  pod 'SideMenu'
  pod 'NVActivityIndicatorView'
  pod 'Alamofire', '~> 4.7.3'
  pod 'DropDown'
  pod 'QRCodeReader.swift', '~> 9.0.1'
  
  pod 'Material', :git => 'https://github.com/CosmicMind/Material.git', :branch => 'development'
  pod 'Motion', :git => 'https://github.com/CosmicMind/Motion.git', :branch => 'development'
  
  
  pod 'MaterialComponents/ActionSheet'

end
```

the error:

> [!] CocoaPods could not find compatible versions for pod "MaterialComponents/ActionSheet":
>   In Podfile:
>     MaterialComponents/ActionSheet
> 
> None of your spec sources contain a spec satisfying the dependency: `MaterialComponents/ActionSheet`.
> 
> You have either:
>  * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
>  * mistyped the name or version.
>  * not added the source repo that hosts the Podspec to your Podfile.
> 
> Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

can any one help?

**Comment by andrewoverton** [comment]
Hi @22Round, I am able to run `pod install` when I have this line in my Podfile:
```Ruby
pod 'MaterialComponentsAlpha/ActionSheet', :git => "https://github.com/material-components/material-components-ios.git"
```
Please let me know if this helps!

**Comment by 22Round** [comment]
@andrewoverton Thanks, pod installed
