### ISSUE TITLE
[Cards] Shape generator doesn't mask card content.

### ISSUE THREAD

**Issue by bambaragoogle** [material-components/material-components-ios#5765]
## Setup

I'm using an `MDCCard` with a `UIImage` subview. The image fills the entirety of the card. I'm customizing the shape of the card by creating an instance of `MDCRectangleShapeGenerator`, where some of the corners are `MDCRoundedCornerTreatment`s, and assigning it to the card's `shapeGenerator` property.

With this configuration there's no way (as far as I can tell) to mask the image correctly using the card's `shapeGenerator`.

## Expected behavior

If the card has any content (image or otherwise), I would expect the card to clip that content with the custom shape. Or at least it would clip it when `clipsToBounds` is YES.

## Actual behavior

The entire rect of the image renders, and obscures the rounded corners of the card. I can work around this by doing something like this during layout:

```
MDCCard *card = ...;
CAShapeLayer *mask = [CAShapeLayer layer];
mask.path = [card.shapeGenerator pathForSize:size];
card.layer.mask = mask;
```

## Platform

 - iOS, any device

**Comment by andrewoverton** [comment]
Hi @bambaragoogle, I just took a look at the ShapedCardViewController to try to reproduce this issue. The corners are supposed to change as you move the slider in this example, but I found that when I commented out the call to `-setNeedsLayout` on [line 161](https://github.com/material-components/material-components-ios/blob/develop/components/Cards/examples/ShapedCardViewController.swift#L161) this stopped happening. I'm wondering if calling `-setNeedsLayout` on your card after setting all the corners might fix your issue? If it does, there might be a case for moving the call to `-setNeedsLayout` into each corner setter, I dunno :/

**Comment by bambaragoogle** [comment]
Hi Andrew. Thanks for pointing me to the `ShapedCardViewController` example. It looks like this example works by applying the same workaround mentioned above (see `-[CardView layoutSubviews]` in that same file to see where the shape layer is set). I will solve this in our app using this same same subclass approach for now, but ideally `MDCCard` would do this masking.

**Comment by andrewoverton** [comment]
Oh @bambaragoogle, I didn't look in the `CardView` implementation earlier. It really is doing exactly what you described huh. I guess just keep doing that, unless @yarneo has any other ideas?

**Comment by yarneo** [comment]
sorry for the delay @bambaragoogle .

The best way to currently mask content is by using the exposed `shapedLayer` here: https://github.com/material-components/material-components-ios/blob/develop/components/private/Shapes/src/MDCShapedShadowLayer.h#L71
An example of usage can be seen here: https://github.com/material-components/material-components-ios/blob/develop/components/Cards/examples/ShapedCardViewController.swift#L86
Let me know if this helps.

**Comment by bambaragoogle** [comment]
Yes, I now see I should use the `MDCShapedShadowLayer` like in the example. The issue, at least as I initially perceived it, was the deviation from the 'Expected behavior' described in my initial comment. As the user of this API, it seems strange that it requires a subclass in order to handle the shape masking correctly.
