### ISSUE TITLE
Unable to install the `MaterialComponents` pod: the `MaterialComponents-Unit-private-Application-tests-unit` target in Xcode would have no sources to compile

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#5771]
This was filed as an internal issue. If you are a Googler, please visit [b/119622655](http://b/119622655) for more details.

---
#### Internal data
- Associated internal bug: [b/119622655](http://b/119622655)

**Comment by andrewoverton** [comment]
This was fixed by https://github.com/material-components/material-components-ios/pull/6580
