### ISSUE TITLE
Build fails in Xcode10 and above with: "Multiple commands produce ..."

### ISSUE THREAD

**Issue by Skoti** [material-components/material-components-ios#5812]
## Reproduction steps

1. Integrate material-components-ios manually (from source) into your Xcode project
2. Make sure you are using New Build System via File -> Workspace settings
2. Build your project using Xcode10 or above

## Expected behavior

Build is successful.

## Actual behavior

Build is failing.

## Additional context
Output:
```
Multiple commands produce '/path_from_derived_data/.jazzy.yaml':
1) Target 'YourTarget' (project 'YourProject') has copy command from '/path_from_derived_data/ShadowElevations/.jazzy.yaml' to '/path_from_derived_data/.jazzy.yaml'
2) Target 'YourTarget' (project 'YourProject') has copy command from '/path_from_derived_data/ShadowLayer/.jazzy.yaml' to '/path_from_derived_data/.jazzy.yaml'
3) Target 'YourTarget' (project 'YourProject') has copy command from '/path_from_derived_data/Themes/.jazzy.yaml' to '/path_from_derived_data/.jazzy.yaml'
4) Target 'YourTarget' (project 'YourProject') has copy command from '/path_from_derived_data/Typography/.jazzy.yaml' to '/path_from_derived_data/.jazzy.yaml'
```

If I enable Legacy Build System in Workspace settings then building is successful.

Do you guys plan to support Xcode10 new build system in the near future?
Is there a workaround for these .jazzy.yaml files error?

---
#### Internal data
- Associated internal bug: [b/119862724](http://b/119862724)

**Comment by romoore** [comment]
Assigning to @jverkoey since he knows the most about how/why we have the jazzy files.

**Comment by andrewoverton** [comment]
Hi @Skoti, is this still an issue for you?

**Comment by jverkoey** [comment]
Closing this because it is not reproducible on Xcode Version 10.2.1 (10E1001).
