### ISSUE TITLE
MDCFlexibleHeaderViewController does not update status bar for multitasking

### ISSUE THREAD

**Issue by jyquinn** [material-components/material-components-ios#583]
When set as view controller for status bar, MDCFlexibleHeaderViewController does not appropriately update the status bar style when entering and exiting multitasking mode if transitioning from modal fullscreen and non-fullscreen.

**Comment by jverkoey** [comment]
Marking this as obsolete, but if this bug is still active please re-open. I believe the underlying problem is likely in how the status bar style is routed through view controllers and not likely in the App Bar code itself.
