### ISSUE TITLE
[TextFields] Scheme Does Not Applied to Clear Button

### ISSUE THREAD

**Issue by zgosalvez** [material-components/material-components-ios#5895]
Calling `MDCTextFieldColorThemer.applySemanticColorScheme` does not apply the scheme to the clear button. You must manually call `.textInputClearButtonTintColor`

## Reproduction steps

1. Create an MDCTextField
2. Run the app
3. Enter anything in the text field

## Expected behavior

The clear button should be colored as an icon.

## Actual behavior

The clear button is black.

## Platform (please complete the following information)

 - Device: iPhone X
 - OS: iOS 12.1

---
#### Internal data
- Associated internal bug: [b/120671390](http://b/120671390)

**Comment by romoore** [comment]
Fixed in #4449
