### ISSUE TITLE
[Buttons] MDCFloatingButtonShapeThemer does not support shapes

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#5899]
The MDCFloatingButtonShapeThemer does not support creating the diamond-like FAB shown in the [Material Guidelines article for Floating Action Buttons](https://material.io/design/components/buttons-floating-action-button.html#theming). Instead, it completely ignores the Shape Scheme provided to it.

## Acceptance Criteria
1.   Theming extension for floating button uses the provided shape scheme for theming.

---
#### Internal data
- Associated internal bug: [b/120671041](http://b/120671041)

**Comment by yarneo** [comment]
our FAB in the baseline is an override, that's how the shape scheme works in the baseline. If a user wants to create a diamond shaped FAB they should create his own themer that receives the shape scheme value and applies it on the FAB.

**Comment by romoore** [comment]
Thanks, @yarneo I think I misunderstood the current code in the themer. Instead of fixing the themer to use the passed shape scheme, we should remove the shape scheme parameter entirely since it's not intended to be used with Material Theming for Floating Action Buttons.  If I understand correctly, this bug should be rewritten to remove the parameter entirely from the API.  Does that sound right?

**Comment by romoore** [comment]
Marking this obsolete as Themers are being replaced with Theming Extensions.
