### ISSUE TITLE
Refactor ButtonBarBuilder to be inlined with ButtonBar

### ISSUE THREAD

**Issue by eli8527** [material-components/material-components-ios#590]
Refactor ButtonBarBuilder into ButtonBar or something else as it is not totally necessary to have these as separate files anymore.

Update tint color change so that button tints are changed without a call to:

```
  [self reloadButtonViews];
```

---
#### Internal data
- Associated internal bug: [b/117179410](http://b/117179410)

**Comment by sigito** [comment]
Hi @ShepJGoogle, is anyone working on this? If no, do you have any details on this issue? What exactly is the goal?

**Comment by material-mirror** [comment]
The internal issue [b/117179410](http://b/117179410) is now closed. This issue is being closed as a result.
