### ISSUE TITLE
Consider making [self snapshotVerifyView:self.testView]; explicit in snapshot tests

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5941]
`[self snapshotVerifyView:self.testView];` is currently invoked as part of the snapshot test class' tearDown method here:

https://github.com/material-components/material-components-ios/blob/fe0099d65c4fa67a02d7b842baf16b540bb2fa86/components/private/Snapshot/MDCSnapshotTestCase.m#L24-L38

This is somewhat magical. Ideally, every test explicitly lists its expectations in the test method itself so that the expectations are clear for each test.

The proposal here is to remove the tearDown expectation logic from `MDCSnapshotTestCase` and to move the `snapshotVerifyView` invocation to each of the tests.

---
#### Internal data
- Associated internal bug: [b/120654625](http://b/120654625)

**Comment by rami-a** [comment]
I think I understand the concern here. However, this behavior enforces the idea that each test method should call verify on a single `testView`.

**Comment by jverkoey** [comment]
> this behavior enforces the idea that each test method should call verify on a single testView.

Are we required to do this because of a technical limitation? I.e. each test method can only validate one snapshot image?

**Comment by rami-a** [comment]
The library allows multiple validations per test if you choose to, but I think for us it will be better to have one snapshot image per test

**Comment by jverkoey** [comment]
What's your thoughts on us enforcing that by explicit convention rather than implicitly? Making an assumption on every test today will make it more difficult to change that assumption in the future.

**Comment by rami-a** [comment]
I think that would be fine, so long as we're all on the same page.
