### ISSUE TITLE
Add a padding parameter to MDCSnapshotTestCase's addBackgroundViewToView: 

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#5942]
MDCSnapshotTestCase currently assumes a padding of 20 points on all sides of the provided view.

It is possible for a view's contents to extend past its bounds up to and beyond 20 points, and in cases like this it will be helpful to be able to customize the padding so that the excess content can be included in the snapshot.

### The request

Add an argument to MDCSnapshotTestCase's addBackgroundViewToView: for either a CGFloat padding or a UIEdgeInsets padding. UIEdgeInsets padding is likely preferable because content often tends to overflow more in one direction than another.

Example pseudocode:

```objc
addBackgroundViewToView:view padding:UIEdgeInsetsMake(...)
addBackgroundViewToView:view padding:50
```

---
#### Internal data
- Associated internal bug: [b/120654904](http://b/120654904)

**Comment by romoore** [comment]
Snapshots were failing even with identical `center` assignments. Wasn't a quick-and-easy API add.

**Comment by jverkoey** [comment]
To clarify: are you referring to the proposed API in this issue?
