### ISSUE TITLE
Content view doesn't know where it overlaps with accessory view

### ISSUE THREAD

**Issue by Arcank** [material-components/material-components-ios#596]
Accessory view is laid on the cell itself:
https://github.com/google/material-components-ios/blob/f15f6d5db6bcb0ddc6a750683daa649775f1e049/components/CollectionCells/src/MDCCollectionViewCell.m#L148

The content view is thus below and overlaps with the accessory view, without knowing how it could adapt.

So either:
1- could the content view be inset when there is an accessory view?
or
2- If overlaying both is supported, could MDCCollectionViewCell have a public API to notify how much the accessory view overlaps?

In case of 2-, the subclass could access the min X of the accessory view for example, to place itself.

**Comment by jverkoey** [comment]
Marking as Obsolete because we do not intend to continue to invest effort into Collections. Please consider using the new List component instead: https://github.com/material-components/material-components-ios/tree/develop/components/List
