### ISSUE TITLE
[NavigationDrawer] non full screen landscape 

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#5960]
This was filed as an internal issue. If you are a Googler, please visit [b/120759989](http://b/120759989) for more details.

---
#### Internal data
- Associated internal bug: [b/120759989](http://b/120759989)

**Comment by randallli** [comment]
This is a design UX decision around accessibility and is unlikely to change.

**Comment by material-mirror** [comment]
The internal issue [b/120759989](http://b/120759989) is now closed. This issue is being closed as a result.
