### ISSUE TITLE
Audit options to improve backporting of RTL UIImage flipping on iOS 8 and below

### ISSUE THREAD

**Issue by Arcank** [material-components/material-components-ios#599]
Related CL: http://codereview.cc/D980.
This introduces partial backporting of `-[UIView imageFlippedForRightToLeftLayoutDirection]`, requiring iOS 8 users to only call it in RTL environment (whereas in iOS 9, it can be called in all configurations, and will automatically be flipped if necessary at layout time).

**Comment by ianegordon** [comment]
This exists in MDFI18n.
