### ISSUE TITLE
git clone fails in temporary_clone_at_ref

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#6040]
The following line is failing, seemingly related to git lfs:

https://github.com/material-components/material-components-ios/blob/430e37b0d126769aa6ae6112e166d8dee9307bee/scripts/temporary_clone_at_ref#L40

---
#### Internal data
- Associated internal bug: [b/121193779](http://b/121193779)

**Comment by material-mirror** [comment]
The internal issue [b/121193779](http://b/121193779) is now closed. This issue is being closed as a result.
