### ISSUE TITLE
Add global override for RTL on iOS 8 and below

### ISSUE THREAD

**Issue by Arcank** [material-components/material-components-ios#607]
On iOS 8 and below, UIKit doesn’t natively implement RTL layout (full mirroring).
It is a goal of Material Components to support clients who would like to support RTL layout on these OS versions.

Currently, the default on iOS 8 and below is LTR layout. To let clients override that default, we should add a global override (such as a C function or class method on `UIApplication`) that would be set early in the app lifecycle (before creating any UI, so at the beginning of `applicationDidFinishLaunching` or before `UIApplicationMain`).

**Comment by ianegordon** [comment]
Closing as obsolete.
