### ISSUE TITLE
[Tabs] MDCTabBar setImageTintColor doesn't work

### ISSUE THREAD

**Issue by amoghpalnitkar** [material-components/material-components-ios#6111]
I am using MDCTabBar with appearance as titledImages. I have set tabBar tint color as my app's accent color. This changes the tab title color to the accent color, when the tab is selected. But it does not change the tint of the selected tab's image. 

I have also tried calling the setImageTintColor method for both, normal and selected state but it still fails to work. 

## Platform

 - Device: Tried on iPhone 5s, iPhone 6, iPhone 8 and iPhone X.
 - OS: iOS 10,1, 11.0, 12.1

Is there anything I am missing here?

**Comment by amoghpalnitkar** [comment]
Oh! My Bad. I was using it as original. Thanks a lot!

**Comment by romoore** [comment]
👍
