### ISSUE TITLE
[BottomNavigation] Title visibility changes don't happen immediately

### ISSUE THREAD

**Issue by Ruberik** [material-components/material-components-ios#6151]
When bottomNavigation.titleVisibility is set for an already-displayed MDCBottomNavigationBar, there is no visible change until a tab is selected.

## Reproduction steps

1. Make an app with an MDCBottomNavigationBar.
2. Put a button in your app that toggles bottomNavigation.titleVisibility between .always and .never.

## Expected behavior

When the toggling button is tapped, the title immediately becomes visible or invisible.

## Actual behavior

When the toggling button is tapped, nothing visible happens. The next time a tab is tapped, the title visibility change happens.

This is particularly egregious when switching visibility on tab selection. You can end up with the title and the image both centered, and thus on top of each other.

## Platform

 - Device: Simulated iPhone 5s
 - OS: iOS 12.1

---
#### Internal data
- Associated internal bug: [b/122264214](http://b/122264214)

**Comment by Ruberik** [comment]
FYI I intend to solve this. It's a one-line fix, but I haven't worked with this project before, and it's a huge effort to figure out how to get it open in XCode, run tests, etc.

**Comment by codeman7** [comment]
Hey @Ruberik what errors are you finding when trying to build the project?

**Comment by Ruberik** [comment]
Thanks for asking, @codeman7. My difficulty is in getting started. With other, smaller libraries, there's usually a single demo .xcodeproj I can open, which opens all the code and lets me modify and test the library changes. Then they have no documentation or tests, so that part's easy. :-)

So concretely, I don't know how to:
1. Get a window in XCode that includes the various tests, demos, and source code.
2. Test my change without writing a new demo project, or hacking it into an old one. Perhaps I should write a new, simple demo project, though that doesn't seem to be a common procedure, since there are only three.
3. Run the existing tests and any presubmits.

Is there a guide on how to get started with those, or are they simply common knowledge that I haven't picked up yet?

Thanks,
Bartholomew

**Comment by codeman7** [comment]
Sorry you're having a tough time I believe these steps should help you get started.

1. Install [git](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git)
2. Install [git lfs](https://github.com/material-components/material-components-ios/blob/develop/contributing/tools.md#using-git-lfs)
3. Make a directory some where on your machine
4. Navigate to the directory you made in step 3
5. Run `git init` from the command line
6. Run `git pull git@github.com:material-components/material-components-ios.git`
7. If you don't have cocoapods, install [cocoapods](https://guides.cocoapods.org/using/getting-started.html#installation)
8. Navigate to `catalog` folder within the directory created in step 3
9. Run `pod install`
10. Open up either MDCCatalog.xcworkspace
11. Navigate to the component you want to work on in 
Pods -> Development Pods -> Material Components ->  _<#component>_

I believe that should get you set up to do changes. If you work on an example and can't find it in MDCCatalog it will most likely show up in MDCDragons. The team and I appreciate any contributions and apologize for the trouble you encountered getting set up. 

_Note:_ Some of theses steps my be redundant but I don't know how far along in the process you are.

**Comment by Ruberik** [comment]
Thank you! That's tremendously helpful. You're right that I had some of that down already, but I didn't see the `catalog` folder as something worth considering. Do you mind if I send a PR to put that into contributing/README.md?

Note that I ran into #5825, which I got around by switching to version 1.5.3 with `sudo gem uninstall cocoapods` and `sudo gem install cocoapods 1.5.3`.

**Comment by Ruberik** [comment]
Added #6152 to fix this issue, and #6155 to (hopefully) improve the documentation.
