### ISSUE TITLE
{kokoro} Drop CocoaPods presubmit jobs

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#6197]
## Feature Request/Suggestion
In order to reduce the time spent waiting for presubmits before merging Pull Requests, we should only execute presubmit tests that evaluate the changed code and affected targets. 

### Detailed Description
The Cocoapods presubmit jobs don't let us perform dependency analysis and so have to build and test all targets. This can take a significant amount of time. For example, snapshot tests for Text Fields currently take over 1 minute to execute.  The bazel build system support dependency analysis and should be able to build and test (nearly) all of our code. Exceptions currently include Swift code that relies on Objective-C code across targets (e.g., Swift examples that import Objective-C example code).

## Acceptance Criteria
* [ ] No cocoapods jobs run as presubmits on merges to the `develop` branch
* [ ] bazel presubmits run on every PR to the `develop` branch
* [ ] bazel presubmits to `develop` only build/test affected targets
* [ ] Snapshot tests are executed by at least one bazel presubmit job if they are affected
* [ ] All source, examples, and tests (with any exceptions filed as bugs and marked as `TODO`) are included in a bazel build rule.

---
#### Internal data
- Associated internal bug: [b/122520233](http://b/122520233)
- Blocked by: https://github.com/material-components/material-components-ios/issues/6429
- Blocked by: https://github.com/material-components/material-components-ios/issues/6232
- Blocked by: https://github.com/material-components/material-components-ios/issues/6219
- Blocked by: https://github.com/material-components/material-components-ios/issues/6245
- Blocked by: https://github.com/material-components/material-components-ios/issues/6238
- Blocked by: https://github.com/material-components/material-components-ios/issues/6293
- Blocked by: https://github.com/material-components/material-components-ios/issues/6294
- Blocked by: https://github.com/material-components/material-components-ios/issues/6295
- Blocked by: https://github.com/material-components/material-components-ios/issues/6296
- Blocked by: 
- Blocked by: https://github.com/material-components/material-components-ios/issues/6228
- Blocked by: https://github.com/material-components/material-components-ios/issues/6229
- Blocked by: https://github.com/material-components/material-components-ios/issues/6230
- Blocked by: https://github.com/material-components/material-components-ios/issues/6231
- Blocked by: https://github.com/material-components/material-components-ios/issues/6232
- Blocked by: https://github.com/material-components/material-components-ios/issues/6233
- Blocked by: https://github.com/material-components/material-components-ios/issues/6234
- Blocked by: https://github.com/material-components/material-components-ios/issues/6235
- Blocked by: https://github.com/material-components/material-components-ios/issues/6236
- Blocked by: https://github.com/material-components/material-components-ios/issues/6237
- Blocked by: https://github.com/material-components/material-components-ios/issues/6238
- Blocked by: https://github.com/material-components/material-components-ios/issues/6239
- Blocked by: https://github.com/material-components/material-components-ios/issues/6240
- Blocked by: https://github.com/material-components/material-components-ios/issues/6241
- Blocked by: https://github.com/material-components/material-components-ios/issues/6242
- Blocked by: https://github.com/material-components/material-components-ios/issues/6243
- Blocked by: https://github.com/material-components/material-components-ios/issues/6244
- Blocked by: https://github.com/material-components/material-components-ios/issues/6245
- Blocked by: https://github.com/material-components/material-components-ios/issues/6246
- Blocked by: https://github.com/material-components/material-components-ios/issues/6247
- Blocked by: https://github.com/material-components/material-components-ios/issues/6248
- Blocked by: https://github.com/material-components/material-components-ios/issues/6212
- Blocked by: https://github.com/material-components/material-components-ios/issues/6213
- Blocked by: https://github.com/material-components/material-components-ios/issues/6214
- Blocked by: https://github.com/material-components/material-components-ios/issues/6215
- Blocked by: https://github.com/material-components/material-components-ios/issues/6216
- Blocked by: https://github.com/material-components/material-components-ios/issues/6217
- Blocked by: https://github.com/material-components/material-components-ios/issues/6218
- Blocked by: https://github.com/material-components/material-components-ios/issues/6219
- Blocked by: https://github.com/material-components/material-components-ios/issues/6220
- Blocked by: https://github.com/material-components/material-components-ios/issues/6221
- Blocked by: https://github.com/material-components/material-components-ios/issues/6222
- Blocked by: https://github.com/material-components/material-components-ios/issues/6223
- Blocked by: https://github.com/material-components/material-components-ios/issues/6224
- Blocked by: https://github.com/material-components/material-components-ios/issues/6225
- Blocked by: https://github.com/material-components/material-components-ios/issues/6226
- Blocked by: https://github.com/material-components/material-components-ios/issues/6227

**Comment by andrewoverton** [comment]
This may be useful to look at: https://github.com/material-foundation/material-internationalization-ios/blob/develop/apple_framework_relative_headers.bzl

**Comment by material-mirror** [comment]
The internal issue [b/122520233](http://b/122520233) is now closed. This issue is being closed as a result.
