### ISSUE TITLE
MDCCollectionView doesn't handle multiple touches well.

### ISSUE THREAD

**Issue by Jicks** [material-components/material-components-ios#625]
As can be seen on the video (using stock MDCCatalog), the MDCCollectionView doesn't support multiple touches very well. The behavior is quite erratic, so I'm not sure what exactly isn't intended but at least:
- The ink effect stays forever, and can be stacked (the cell becomes darker and darker).
- Tapping the switch while holding another cell doesn't work but queue the action.  Sliding the switch while holding another cell works. The two should probably be consistent.

It looks like the touches are exclusive for the cells, but not for their accesoryView.

[MDCCollectionView_ExclusiveTouch.zip](https://github.com/google/material-components-ios/files/354204/MDCCollectionView_ExclusiveTouch.zip)

**Comment by ianegordon** [comment]
Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄
