### ISSUE TITLE
MDCSnackbarMessageViewTitleA11yHint is not localized

### ISSUE THREAD

**Issue by Arcank** [material-components/material-components-ios#627]
[MDCSnackbarMessageViewTitleA11yHint](https://github.com/google/material-components-ios/blob/b92d724d906f6c0f072bca17f92177db819651c5/components/Snackbar/src/private/MDCSnackbarMessageView.m#L27) is in plain english, not translated.

**Comment by ianegordon** [comment]
Fixed in #2107
