### ISSUE TITLE
[Catalog] Add MDCCatalog targets to bazel

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#6296]
This was filed as an internal issue. If you are a Googler, please visit [b/122550863](http://b/122550863) for more details.

---
#### Internal data
- Associated internal bug: [b/122550863](http://b/122550863)

**Comment by romoore** [comment]
Still missing the bridging header

```
catalog/MDCCatalog/MDCCatalog-Bridging-Header.h
```

**Comment by material-mirror** [comment]
The internal issue [b/122550863](http://b/122550863) is now closed. This issue is being closed as a result.
