### ISSUE TITLE
MDCTypography should respect Dynamic Type settings

### ISSUE THREAD

**Issue by allevato** [material-components/material-components-ios#633]
iOS supports Dynamic Type, which lets users change the size of any text in an app that uses the `[UIFont preferredFontForTextStyle:]` API to obtain fonts for body text, headers, and other styles. Unfortunately, since `MDCTypography` uses hard-coded point sizes, it ignores those settings, which not only ignores user preference but is also extremely harmful to accessibility.

On Android, this is easily solved because the fonts in the Material spec are specified in `sp` units, which automatically scale to the user's settings. Text point sizes on iOS, however, do not to this.

Since the text styles defined in the Material spec are not the same as those defined by the `UIFontTextStyle*` constants, a 1:1 mapping between them would not be possible. But it should still be feasible to scale the fonts proportionally to respect the user's settings.

One possibility would be to note the ratio between the point size for `UIFontTextStyleBody` on a device with the default text size setting and Material's desired 14pt for "Body 1" style, and map the Material sizes to those scaled sizes. Then, query the actual descriptor for `UIFontTextStyleBody` at runtime, whose point size will be scaled to the user's preference. The ratio between it and the default `UIFontTextStyleBody` then determines the multiplier used to compute the actual point sizes for all of the remaining styles in `MDCTypography`.

**Comment by ianegordon** [comment]
MDCTypography support [UIFont mdc_preferredFontForStyle:MDCMaterialStyle]
