### ISSUE TITLE
[FlexibleHeader] Incorrect insets during animated transitions

### ISSUE THREAD

**Issue by brianjmoore** [material-components/material-components-ios#6437]
During animated transitions between tracking scroll views, MDCFlexibleHeader provides incorrect content insets.

## Reproduction steps

1. Open MDCDragons app, go to "App Bar" > "Manual Tabs Jump (Animated)" example. (Provided in https://github.com/material-components/material-components-ios/pull/6447)
2. Tap on "Second" tab.
3. Tap on "Third" tab.
4. Tap on "Second" tab.
5. Tap on "First" tab.

(Generally: This happens when the view is added to the view hierarchy and visible between calls to `trackingScrollWillChange` and `setTrackingScrollView`)

## Expected behavior
Consistent content insets and offsets during and after the animation in. (The animation is a fade-in in this case, but might also be a slide-in managed by UIPageViewController for example).

## Actual behavior
When displaying a tab for the first time, it has insets that are ~40pt too tall. This creates a jumping effect when switching between tabs.

## Platform

 - Device: iPhone XR simulator
 - OS: iOS 12.1

## Additional context

![insets](https://user-images.githubusercontent.com/395995/51554264-ddd66180-1e42-11e9-9b36-65da73dd069c.gif)

---
#### Internal data
- Associated internal bug: [b/123297383](http://b/123297383)

**Comment by material-mirror** [comment]
The internal issue [b/123297383](http://b/123297383) is now closed. This issue is being closed as a result.
