### ISSUE TITLE
{kokoro} Website generation is broken

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#6444]
```
In file included from ../src/binding.cpp:1:
In file included from ../../nan/nan.h:191:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../src/binding.cpp:1:
In file included from ../../nan/nan.h:197:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:337:28: warning: 'New' is deprecated: Use Isolate* version [-Wdeprecated-declarations]
  return v8::StringObject::New(value).As<v8::StringObject>();
                           ^
/Users/kbuilder/.node-gyp/11.7.0/include/node/v8.h:5242:37: note: 'New' has been explicitly marked deprecated here
                static Local<Value> New(Local<String> value));
```

---
#### Internal data
- Associated internal bug: [b/123242943](http://b/123242943)

**Comment by romoore** [comment]
Still broken

```
In file included from ../src/binding.cpp:1:
../../nan/nan.h:1472:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/kbuilder/.node-gyp/11.7.0/include/node/node.h:172:50: note: 'MakeCallback' has been explicitly marked deprecated here
                NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                 ^
7 warnings and 1 error generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Volumes/BuildData/tmpfs/src/github/repo/docsite-generator/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/Cellar/node/11.7.0/bin/node" "/Volumes/BuildData/tmpfs/src/github/repo/docsite-generator/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Volumes/BuildData/tmpfs/src/github/repo/docsite-generator/node_modules/node-sass
gyp ERR! node -v v11.7.0
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok 
Build failed with error code: 1
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.


[ID: 3524916] Build finished after 419 secs, exit value: 1
```

**Comment by material-mirror** [comment]
The internal issue [b/123242943](http://b/123242943) is now closed. This issue is being closed as a result.

**Comment by jverkoey** [comment]
I believe that failure did not include the latest changes that resolve the issue. Marking this issue as closed because other pull requests do appear to be passing as expected.

**Comment by romoore** [comment]
This is still broken. Many other PRs are still failing.

See https://fusion.corp.google.com/runanalysis/info/prod%3AMaterialComponents_iOS%2Fmacos_external%2Fpresubmit_site/prod%3AMaterialComponents_iOS%2Fmacos_external%2Fpresubmit_site/KOKORO/94e3c48c-34fc-4098-8b3a-e8eb7afd942c/1548681364874/prod%3AMaterialComponents_iOS%2Fmacos_external%2Fpresubmit_site%20Build%20%233785/Targets for an example.

**Comment by material-mirror** [comment]
The internal issue [b/123242943](http://b/123242943) is now closed. This issue is being closed as a result.

**Comment by material-mirror** [comment]
The internal issue [b/123242943](http://b/123242943) is now closed. This issue is being closed as a result.

**Comment by material-mirror** [comment]
The internal issue [b/123242943](http://b/123242943) is now closed. This issue is being closed as a result.

**Comment by material-mirror** [comment]
The internal issue [b/123242943](http://b/123242943) is now closed. This issue is being closed as a result.

**Comment by material-mirror** [comment]
The internal issue [b/123242943](http://b/123242943) is now closed. This issue is being closed as a result.

**Comment by material-mirror** [comment]
The internal issue [b/123242943](http://b/123242943) is now closed. This issue is being closed as a result.

**Comment by material-mirror** [comment]
The internal issue [b/123242943](http://b/123242943) is now closed. This issue is being closed as a result.

**Comment by jverkoey** [comment]
I have not yet seen a new PR that is failing for a reason that isn't valid.

The linked to example:

https://fusion.corp.google.com/runanalysis/info/prod%3AMaterialComponents_iOS%2Fmacos_external%2Fpresubmit_site/prod%3AMaterialComponents_iOS%2Fmacos_external%2Fpresubmit_site/KOKORO/94e3c48c-34fc-4098-8b3a-e8eb7afd942c/1548681364874/prod%3AMaterialComponents_iOS%2Fmacos_external%2Fpresubmit_site%20Build%20%233785/Targets

is failing because of a valid failure:

```
Error:
Broken link docs/../../contributing/beta_componetns.md in /Volumes/BuildData/tmpfs/src/github/repo/docsite-generator/.stage/ios/catalog/dialogs/index.md
```
