### ISSUE TITLE
`clang-format` job breaks when no files are edited?

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#6464]
Seen in https://github.com/material-components/material-components-ios/pull/6460 which was only adding a new `.MD` file to the project root.

```
Downloading clang-format...
SHAs match. Proceeding.
Downloading git-clang-format...
SHAs match. Proceeding.
Submodule 'scripts/external/clang-format-linter' (https://github.com/vhbit/clang-format-linter.git) registered for path 'scripts/external/clang-format-linter'
Submodule 'scripts/external/github-comment' (https://github.com/material-foundation/github-comment) registered for path 'scripts/external/github-comment'
Submodule 'scripts/external/material-motion-apidiff' (https://github.com/material-motion/material-motion-apidiff.git) registered for path 'scripts/external/material-motion-apidiff'
Cloning into '/Volumes/BuildData/tmpfs/src/github/repo/scripts/external/clang-format-linter'...
Cloning into '/Volumes/BuildData/tmpfs/src/github/repo/scripts/external/github-comment'...
Cloning into '/Volumes/BuildData/tmpfs/src/github/repo/scripts/external/material-motion-apidiff'...
Submodule path 'scripts/external/clang-format-linter': checked out 'd66020bd322cd0e737c8f5c9e459007f5b088ae0'
Submodule path 'scripts/external/github-comment': checked out 'dcf2de5a96b83207530c76075a40d5f8583f75ec'
Submodule path 'scripts/external/material-motion-apidiff': checked out 'f896480395a6c67855cde7048078cd42ae0fce21'
Submodule 'third_party/jardiff' (https://github.com/JakeWharton/jardiff.git) registered for path 'scripts/external/material-motion-apidiff/third_party/jardiff'
Cloning into '/Volumes/BuildData/tmpfs/src/github/repo/scripts/external/material-motion-apidiff/third_party/jardiff'...
Submodule path 'scripts/external/material-motion-apidiff/third_party/jardiff': checked out '6646a195df8dc5868482875498ee2b5aed9c7818'
Running clang-format on changes from 39c0529d0adb557a19ba66d11ab453f1df24e34f to HEAD...
no modified files to format
error: root manifest not found


[ID: 3756338] Build finished after 11 secs, exit value: 1

```

---
#### Internal data
- Associated internal bug: [b/123299546](http://b/123299546)

**Comment by romoore** [comment]
Looks like it's breaking even when there are files being edited. For example, https://github.com/material-components/material-components-ios/pull/6447 introduces a new "examples" file in `components/AppBar/examples/AppBarAnimatedGlitchExample.swift`

**Comment by romoore** [comment]
```
Build version 9C40b
Downloading clang-format...
clang-format does not match sha. Aborting.
```

**Comment by material-mirror** [comment]
The internal issue [b/123299546](http://b/123299546) is now closed. This issue is being closed as a result.

**Comment by romoore** [comment]
Still broken as of Jan 25 2019, 7:59:39 PM UTC

```
Cloning into '.clang-format-ci-src'...
/tmpfs/src/.clang-format-ci-src /tmpfs/src
Note: checking out 'v1.1.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 5ed3be4... Merge branch 'release-candidate' into stable
Using clang-format-ci v1.1.0
/tmpfs/src
Xcode 9.2
Build version 9C40b
Downloading clang-format...
clang-format does not match sha. Aborting.
```

https://fusion.corp.google.com/runanalysis/info/prod%3AClangFormatCI%2Fmacos_external%2Fmaterial_components_material_components_ios/prod%3AClangFormatCI%2Fmacos_external%2Fmaterial_components_material_components_ios/KOKORO/cc21eabf-c567-4397-a049-370bd11498f6/1548446379926/prod%3AClangFormatCI%2Fmacos_external%2Fmaterial_components_material_components_ios%20Build%20%231147/Targets

**Comment by material-mirror** [comment]
The internal issue [b/123299546](http://b/123299546) is now closed. This issue is being closed as a result.

**Comment by romoore** [comment]
Can we please turn off or fix @material-mirror  if it's going to keep closing issues that are reopened?

**Comment by material-mirror** [comment]
The internal issue [b/123299546](http://b/123299546) is now closed. This issue is being closed as a result.

**Comment by romoore** [comment]
Gah! This needs to be reopened.

**Comment by material-mirror** [comment]
The internal issue [b/123299546](http://b/123299546) is now closed. This issue is being closed as a result.

**Comment by material-mirror** [comment]
The internal issue [b/123299546](http://b/123299546) is now closed. This issue is being closed as a result.

**Comment by romoore** [comment]
From the history of the failure in https://github.com/material-components/material-components-ios/issues/6464#issuecomment-457718183:

![screen shot 2019-01-28 at 10 21 51 am](https://user-images.githubusercontent.com/1753199/51845951-9b030680-22e6-11e9-8c18-dc9f367f6977.png)

That failure includes the commit `2b56920e4d52bd35dde8e06729e8d0efecbc783a` (#6471) but did not fix the build.

**Comment by material-mirror** [comment]
The internal issue [b/123299546](http://b/123299546) is now closed. This issue is being closed as a result.

**Comment by jverkoey** [comment]
This was fixed by uploading the clang-format binary to https://github.com/material-foundation/clang-format/releases/tag/r351607

**Comment by romoore** [comment]
Thanks!
