### ISSUE TITLE
[Component]MDCChipView. The MDCChipView has a tap target that is 32 pt in height 

### ISSUE THREAD

**Issue by C-anuj** [material-components/material-components-ios#6537]
Apple recommends minimum tappable area of 44pt x 44pt for all controls
https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/adaptivity-and-layout/

The MDCChipView has a tap target of 32 pt

**Comment by romoore** [comment]
That's correct. You can either increase the size of the Chip to be as large as you need or you can [use `hitAreaInsets` to adjust the tappable area around the MDCChipView](https://github.com/material-components/material-components-ios/blob/de5d200599035b8e67ed95a7507f82ad2f35d8c4/components/Chips/src/MDCChipView.h#L150).
