### ISSUE TITLE
[MDCCardCollectionCell] Cell selection only works on screens that have a notch (X, XS, XS Max)

### ISSUE THREAD

**Issue by tylerjames** [material-components/material-components-ios#6573]
I have been using `MDCCardCollectionCell` and had been using an iPhone XS simulator. Things were going well, everything was working fine, the cell showed the ripple animation when it was tapped and `didSelectItem` was triggered.

Then I figured I'd try it on iPad. Result:
Nothing happens when you tap on a cell. No ripple, no `didSelectItem`.

Tried on iPhone 8 Plus: Nothing happens when tapping on a cell.

Tried on real iPhone 6S Plus: Nothing happens.

I tried on several other iPhone and iPad simulators and have found that cell selection only works on iPhone X/XS/XS Max simulators. Tried on both iOS 11 and iOS 12.1

I'll try to look into the code if I get some time but I could not find anything on my end that should cause things to work differently.

---
#### Internal data
- Associated internal bug: [b/124074330](http://b/124074330)

**Comment by tylerjames** [comment]
It looks like `hitTest` and `touchesBegan` are not triggered at all on the non-X devices. 

I tried to Debug View Hierarchy but couldn't find anything obviously different at between X and 8 Plus

**Comment by ianegordon** [comment]
@yarneo , could you please investigate.
I would recommend checking a variety of hardware and iOS versions.

**Comment by tylerjames** [comment]
I think this might not be your bug. I'm still investigating the the X models all have the `safeAreaInsets` and I must be doing something stupid related to those. I'm also using the `BottomAppaBar` component so I might be doing something foolish with that when trying to position it correctly. I'll let you know.

**Comment by tylerjames** [comment]
Okay I figured out what was going on here, sort of.

It had to do with the way I was handling the MDCBottomAppBarView. I'm not sure exactly what it was doing but on views that did not have safe area insets it was somehow affecting my whole content view.

I've switched to adding the bottom bar using autolayout constraints and now everything is working fine.

**Comment by yarneo** [comment]
That's great to hear! Thanks for looking into it and helping figure out the issue. If you do find issues with the Cards component feel free to open another issue.
