### ISSUE TITLE
[Buttons] Theming documentation is really confusing

### ISSUE THREAD

**Issue by bernaferrari** [material-components/material-components-ios#6592]
I skipped Material Components from version 43 to 76, so a lot of things changed.

I got really frustrated today trying to understand the [Buttons Theming documentation](https://github.com/material-components/material-components-ios/blob/develop/components/Buttons/docs/theming.md). Sometimes, the authors use `import MaterialComponents.MaterialButtons_ButtonThemer`, others `import MaterialComponentsBeta.MaterialConainerScheme` (yeah, that is a typo on the documentation!). When using the beta, there is no instruction on how to Pod install the Beta component or how stable it is.

Besides this, the flow of information is really bad.

1. It starts saying "you must first import the extension [from where??] and create an `MDCContainerScheme` instance [what?!]". It goes to import a beta component from nowhere, and that beta component has no relation with the `MDCContainerScheme` (might be, but remember, everything changed since I last used these components, so I don't know).
2. Theming an `MDCButton`. Another dependency to import. What happened to `MDCContainerScheme`? Then it goes to applyTextTheme with `containerScheme`, which appeared out of nowhere. There is so much information, gifs, and Swift+Objective C code takes so much space. Maybe a table could help. Also, some descriptions look really basic or unnecessary: "Contained buttons" -> gif -> "To theme a button as a Material Design outlined button". Why repeat what was just written?
3. Theming an `MDCFloatingButton`. Same frustrations as 2.
4. Using a themer. Another dependency to import, this one is not in beta. 

There is a lot of repeated information and instructions, that change slightly. However, due to their placement on screen, the person reading will hardly notice there is a pattern.

BTW, should I use `MaterialComponentsBeta.MaterialButtons_Theming` or `MaterialComponents.MaterialButtons_ButtonThemer`? They are different, but (from my understand) kind of similar, one is stable, the other is not.. Documentation could be better on this regard.

After that, if the user is reading the [main page](https://github.com/material-components/material-components-ios/tree/develop/components/Buttons), he still have to deal with themer and colors, which are better written but still can cause some confusion.

When reading the `MDCSemanticColorScheme`, for example, there is no example besides the really basic. I have no idea how to initialise it with the colors I want. I'm going to read the samples, which shouldn't be necessary.

---
#### Internal data
- Associated internal bug: [b/124241464](http://b/124241464)

**Comment by jverkoey** [comment]
Duping this to https://github.com/material-components/material-components-ios/issues/7074

**Comment by bernaferrari** [comment]
Technically, "Write a document teaching MDC clients how to use theming extensions" is different than fixing the existing one, which is hard to understand and even has typo.

**Comment by jverkoey** [comment]
Ah. Agreed. I'll keep this open so we make sure to revisit our buttons documentation.

**Comment by bernaferrari** [comment]
I think you forgot to reopen it.

**Comment by jverkoey** [comment]
Yep; thank you!

**Comment by material-mirror** [comment]
The internal issue [b/124241464](http://b/124241464) is now closed. This issue is being closed as a result.

**Comment by jverkoey** [comment]
Hi @bernaferrari: we have https://github.com/material-components/material-components-ios/pull/7192 out for review. Would love your feedback on the PR :)

**Comment by jverkoey** [comment]
I'll keep making copy-edits to this doc over the next few working days. The next content I'll focus on are the individual theming sections, which can likely largely be annotated as to-be-deleted or pointed to our general theming documentation.

**Comment by bernaferrari** [comment]
Hey, thanks. I gave a fast look, things look a lot better! 
My initial feedback:
- The theming link is broken.
- There is no place telling what containerScheme is, where it comes from, how do I use it.
- You could save some lines (and duplications) by using Contained Buttons [learn more] instead of Contained Buttons followed by "Learn more about contained buttons" in the next line.
- "you can theme the mdcbutton to match one of material design button styles" ok.. Then you link to itself, makes no sense.
- same above. "see the buttonthemer documentation for a full list". But hey, that file contains exactly the same things as the file showing it.

**Comment by jverkoey** [comment]
@bernaferrari another PR out at https://github.com/material-components/material-components-ios/pull/7206 plus some related PRs to fix URL linking throughout our docs.

**Comment by bernaferrari** [comment]
Awesome! A lot better! Isn't the hierarchy inverted in this case? Swift/Objective c is larger than component name.

![image](https://user-images.githubusercontent.com/351125/56510515-69be5f00-6500-11e9-8308-4c2fa44c915c.png)

Sometimes you use ##### for Swift/Objective C, sometimes you use ####. I think it would be better to see how you are using on other components and standardise it.

I really liked you put the unsupported to the end, and everything is way better than before! Thanks!

**Comment by jverkoey** [comment]
Ah agreed; this is an artifact of how our code snippets show up on material.io. I'll investigate if we can improve the headers here though.

**Comment by jverkoey** [comment]
Made some more adjustments in https://github.com/material-components/material-components-ios/pull/7236

**Comment by bernaferrari** [comment]
There are 21 occurences of ##### swift and 2 of #### swift
