### ISSUE TITLE
[Releasing] script/release publish fails silently

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#6596]
During the last release scripts/release publish failed silently.

When scripts/release publish was invoked from the command line during the 76.1.x release there was no feedback and the actions behind publish did not take place.

Investigate why this failed.
Fix or remove.

---
#### Internal data
- Associated internal bug: [b/124241059](http://b/124241059)

**Comment by romoore** [comment]
@ianegordon What would you like fixed/removed?  

I would suggest that calling `release publish` should either succeed or fail loudly.

**Comment by ianegordon** [comment]
I agree with @romoore .

A. scripts/release publish should either succeed or fail loudly
-OR-
B. Remove the publish capability from scripts/release

I'm very much in favor of A.

**Comment by romoore** [comment]
Do we have any logs/details about the conditions that caused the failure? @ianegordon do you happen to have any bash logs or history that might be helpful for debugging this issue?

**Comment by randallli** [comment]
I experienced this for the 84.0.0 release. @andrewoverton shadowed.

We think it was related to $ghtoken being empty or just whitespace.

We put in echo statements to determine this.

running 
`rm ~/.gh.json` 
`gh user --whoami`

solved this for me.
