### ISSUE TITLE
[Releasing] scripts/release bump isn't very flexible.

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#6606]
## Feature Request/Suggestion

If you try and release bump from a version that has not been tagged, the script exit with an error.  This functionality was required during our last release.

Consider adding a --force flag to allow this functionality.

## Acceptance Criteria
1. Any failure generates a diagnostic message AND the general usage documentation.

---
#### Internal data
- Associated internal bug: [b/124384012](http://b/124384012)

**Comment by romoore** [comment]
You can use `scripts/release bump 100.0.0 98.0.0` to skip 99.0.0 if you want.  The script produces an error message showing this optional parameter (the previous version number).  By forcing the user to explicitly call-out the previous version number, the human has a chance to verify that they're intentionally skipping a version.

We previously had an error where [a release version was accidentally skipped](https://github.com/material-components/material-components-ios/commit/73dc1eac9aeea1f2e3c2409eac280e6c9b1d24e2).  Having a `--force` option make it that much easier to do something unintentional.  Especially if the user thinks the script is misbehaving.
