### ISSUE TITLE
MDCBottomNavigationControllerTests lacks proper availability guards

### ISSUE THREAD

**Issue by andrewoverton** [material-components/material-components-ios#6608]
`MDCBottomNavigationBarController` has a `NS_CLASS_AVAILABLE_IOS(9_0)`, but its accompanying protocol and tests do not. I believe this is causing pod lib lint validation failures.

---
#### Internal data
- Associated internal bug: [b/124304557](http://b/124304557)

**Comment by romoore** [comment]
@andrewoverton  Can you determine if you're still seeing the same errors that caused this ticket?

**Comment by andrewoverton** [comment]
I just did `pod lib lint MaterialComponents.podspec --subspec=NavigationDrawer` and everything was fine so I'm going to close this ticket I guess.
