### ISSUE TITLE
MaterialComponentsBeta in example

### ISSUE THREAD

**Issue by beraybentesen** [material-components/material-components-ios#6610]
MDCBottomNavigationBarController example is not available through the pod library.

---
#### Internal data
- Associated internal bug: [b/124384457](http://b/124384457)

**Comment by randallli** [comment]
@romoore do we have a tracking bug for moving it to the beta podspec?

**Comment by romoore** [comment]
It is beta already - this issue is that it's not in the published Podspec (Ready).

https://github.com/material-components/material-components-ios/blob/develop/MaterialComponentsBeta.podspec#L53

**Comment by romoore** [comment]
Closing as intended behavior.
