### ISSUE TITLE
Show or hide status bar when shifting header

### ISSUE THREAD

**Issue by sharonw** [material-components/material-components-ios#662]
### Overview

My feature's design requires me to animate the header both onto the screen and off the screen. This includes shifting the header so that it's fully off-screen and hiding the status bar text.

Here's what the header looks like when the view controller initially loads:

![header on-screen](https://cloud.githubusercontent.com/assets/1641666/17500091/49164c28-5d87-11e6-9889-b96ca534c1d6.png)

Here's what the header looks like after I call `shiftHeaderOffScreenAnimated:`

![header off-screen](https://cloud.githubusercontent.com/assets/1641666/17500104/56e0deae-5d87-11e6-8898-dd62de103a7a.png)
### Motivation and context

According to my spec, in a particular mode of my app, the user shouldn't be able to see the header color, the shadow, the Carrier, the time, or the battery icon. The header and status bar should be completely gone.
### Workaround

I'm able to achieve the important part of this (animating to the desired height) by adding the following lines to `viewDidLoad`:

```
self.headerViewController.headerView.shiftBehavior = MDCFlexibleHeaderShiftBehaviorEnabledWithStatusBar;
self.headerViewController.headerView.sharedWithManyScrollViews = YES;
```

![header almost fully off-screen](https://cloud.githubusercontent.com/assets/1641666/17500271/e943d49e-5d88-11e6-8540-f92f8f7c5607.png)

However, it would be nice to have official support for doing this without enabling header shift behavior, and to get rid of the shadow and status bar text too.
### Operating system and hardware

I'm testing using iOS 9.3 on an iPhone 6 Simulator, but I don't believe this is version-specific.
### Related issues
#624

**Comment by ianegordon** [comment]
Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄
