### ISSUE TITLE
v76.1.2 is  tagged to the `develop` branch instead of `stable`

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#6626]
It looks like [`v76.1.2`](https://github.com/material-components/material-components-ios/commit/f840f43e1e21820e5b3d1ef1c64ebbf16cb346aa) was tagged on `develop` instead of `stable`.  I don't see `v76.1.2` in the history of `stable`, but it is in the history of `develop`.  The HEAD of `stable` should show a tag, but it is currently empty.

## History of `stable`
```
*   155f278b60 (HEAD -> stable, origin/stable) Merge branch 'release-candidate' into stable
|\  
| * 0cf64863af Hand modify CHANGELOG to add notes
| * ac78d824a9 Bumped version number to 76.1.2.
| * c79fe2c9ce Hand modified CHANGELOG
| * 3b9d66bf69 {kokoro} Fix develop (#6575)
| * d04bc7397b Automatic changelog preparation for release.
|/  
*   c77a2f8eea (tag: v76.1.1) Merge branch 'release-candidate' into stable
|\  
```

## History of `develop`

```
* 1785bcd356 [Releasing] Require presubmits to pass (#6577)
*   f840f43e1e (tag: v76.1.2) Merge branch 'release-candidate' into develop
|\  
| * 0cf64863af Hand modify CHANGELOG to add notes
| * ac78d824a9 Bumped version number to 76.1.2.
| * c79fe2c9ce Hand modified CHANGELOG
| * 3b9d66bf69 {kokoro} Fix develop (#6575)
| * d04bc7397b Automatic changelog preparation for release.
| *   c77a2f8eea (tag: v76.1.1) Merge branch 'release-candidate' into stable
```

---
#### Internal data
- Associated internal bug: [b/124757318](http://b/124757318)

**Comment by ianegordon** [comment]
This is likely a side-effect of the uneven 76.1.x release.

As 77.0.0 has been released, there may be no further action possible.
