### ISSUE TITLE
[MDCTextInputControllerOutlined] Bordering for MDCTextInputControllerBase / MDCTextInputControllerOutlined

### ISSUE THREAD

**Issue by prateekhegde** [material-components/material-components-ios#6627]
## Feature Request/Suggestion

The MDCTextInputControllerBase / MDCTextInputControllerOutlined has no way to disable the border crossing gap. Is there no way to remove the gap, so that it appears like MDCTextInputControllerOutlinedArea, except for a single line text field?  

The documentation provides no links to exemplify simple customisation. 

## Additional context

Essentially, the border gap / border crossing needs to be disabled in MDCTextInputControllerOutlined to replicate the MDCTextInputControllerOutlinedTextArea's behaviour. 

---
#### Internal data
- Associated internal bug: [b/124757953](http://b/124757953)

**Comment by romoore** [comment]
Setting the placeholder to `nil` should achieve this result.  I believe this was fixed in https://github.com/material-components/material-components-ios/pull/6322
