### ISSUE TITLE
[ButtonBar] Promote Theming Extensions to Ready

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#6634]
This was filed as an internal issue. If you are a Googler, please visit [b/124515608](http://b/124515608) for more details.

---
#### Internal data
- Associated internal bug: [b/124515608](http://b/124515608)

**Comment by jverkoey** [comment]
We will not be promoting button bar's theming extension to ready because this component is meant to be an implementation detail for other components.
