### ISSUE TITLE
+[MDCSnackbar defaultManager] throws error if first called on background thread

### ISSUE THREAD

**Issue by jctrouble** [material-components/material-components-ios#6759]
`MDCSnackbar`'s documentation says that it is thread safe, however if the first access to the default snackbar is on a different thread, XCode's Main Thread Checker will trigger and cause issues:

```
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIView initWithFrame:]
PID: 47741, TID: 583557, Thread name: (none), Queue name: <REDACTED>, QoS: 0
Backtrace:
4   <REDACTED>                          0x000000010a345be9 -[MDCSnackbarOverlayView initWithFrame:] + 121
5   <REDACTED>                          0x000000010a330831 -[MDCSnackbarManagerInternal initWithSnackbarManager:] + 625
6   <REDACTED>                          0x000000010a335438 -[MDCSnackbarManager init] + 152
7   <REDACTED>                          0x000000010a335365 __36+[MDCSnackbarManager defaultManager]_block_invoke + 69
8   libdispatch.dylib                   0x0000000113b7e602 _dispatch_client_callout + 8
9   libdispatch.dylib                   0x0000000113b800c4 _dispatch_once_callout + 66
10  <REDACTED>                          0x000000010a3352c2 +[MDCSnackbarManager defaultManager] + 98
```

The issue stems from the initialization of `_overlayView` in `MDCSnackbarManagerInternal`.

It may be sufficient to lazily load `overlayView`, given that (a) it's a view, and by convention views are only accessed on the main thread and (b) all of the usages of `overlayView` are currently guarded by `+[NSThread isMainThread]` checks.

---
#### Internal data
- Associated internal bug: [b/127484858](http://b/127484858)

**Comment by romoore** [comment]
Thanks for the bug report! OverlayView should definitely be created on the main thread (and probably lazily).
