### ISSUE TITLE
[MDC-iOS] Set minimum os version to 9.0

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#6787]
This was filed as an internal issue. If you are a Googler, please visit [b/127659702](http://b/127659702) for more details.

---
#### Internal data
- Associated internal bug: [b/127659702](http://b/127659702)

**Comment by jverkoey** [comment]
Fixed by https://github.com/material-components/material-components-ios/pull/7135

**Comment by material-mirror** [comment]
The internal issue [b/127659702](http://b/127659702) is now closed. This issue is being closed as a result.
