### ISSUE TITLE
[ActionSheet] Sheet spans width of screen on iPad with UISplitViewController. Add option to have it only span the detail VC

### ISSUE THREAD

**Issue by tylerjames** [material-components/material-components-ios#6832]
I've been using the ActionSheet as a simple menu and primarily using the iPhone simulator. I recently used the iPad simulator in which my app is displayed using a UISplitViewController. 

When I display the ActionSheet from the detail VC in my split view the sheet takes up the full width of the screen as if it was being presented by the root VC.

Is there any way to show the sheet only within the bounds of the detail VC? If not I would like to suggest this as a feature.

---
#### Internal data
- Associated internal bug: [b/128528206](http://b/128528206)

**Comment by jverkoey** [comment]
ActionSheets should not be used on the iPad. Use a UIPopoverController or UIMenu instead.
