### ISSUE TITLE
[Banner] Verify if UIImageRenderingModeAlwaysTemplate should be used.

### ISSUE THREAD

**Issue by wenyuzhang666** [material-components/material-components-ios#6838]
Verify with designers on whether clients are allowed to use full-color images or single-color icons.

Verify with designers on what icon color params should be used for banner on m2.

---
#### Internal data
- Associated internal bug: [b/128425749](http://b/128425749)

**Comment by andrewoverton** [comment]
I'm not a designer lol but I feel like people shouldn't be forced into using `UIImageRenderingModeAlwaysTemplate`

**Comment by romoore** [comment]
This Issue was motivated by a question on an example VC. I just wanted to know if the example was accidentally not setting a rendering mode and if we should demonstrate using `.alwaysTemplate` as the typical use case.

**Comment by jverkoey** [comment]
> I just wanted to know if the example was accidentally not setting a rendering mode and if we should demonstrate using .alwaysTemplate as the typical use case.

This seems like a fair demonstration of a typical use case, but we should not restrict the types of images clients can set here.

**Comment by wenyuzhang666** [comment]
Thanks for the inputs. I will just use it in the typical example.
