### ISSUE TITLE
#

### ISSUE THREAD

**Issue by BigAlInTheHouse** [material-components/material-components-ios#6854]
### Overview
For usage questions: ask on [Stack  Overflow](https://stackoverflow.com/questions/tagged/material-components+ios).

 - Context, problem or idea, solution or next step
 - Screenshots/Video (if possible)
 - Stack trace (if possible)

### Reproduction steps
 - Detailed steps to reproduce

### Version number
1111+

 - Found in CHANGELOG.md

### Related issues
 - Type `#` and the issue number or `#` and select the from the inline drop down.

**Comment by BigAlInTheHouse** [comment]
Self select options inline from your own coding

**Comment by romoore** [comment]
Looks like this was opened by mistake.
