### ISSUE TITLE
Font for code snippets seems broken on the site homepage

### ISSUE THREAD

**Issue by Arcank** [material-components/material-components-ios#687]
### Overview of the issue

On https://material-ext.appspot.com/mdc-ios-preview/:
<img width="489" alt="screen shot 2016-08-26 at 10 09 15" src="https://cloud.githubusercontent.com/assets/197492/17998574/6adbe484-6b75-11e6-985b-4a907fdd346b.png">
### Reproduction steps

Just loading the page.
### Operating system and hardware

OS X 10.11.6, Chrome 52.0.2743.116

**Comment by ianegordon** [comment]
Closing as obsolete.
