### ISSUE TITLE
[TabBar] Back with an MDCShadowLayer

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#6902]
That way clients could explicitly set an elevation if they wanted one.

See a team attempting a workaround:
cl/238321471

---
#### Internal data
- Associated internal bug: [b/128619160](http://b/128619160)

**Comment by romoore** [comment]
Tabs cannot have shadow/elevation. They can be embedded in an AppBar and the AppBar can have elevation.  A hairline below the Tabs is allowed, but not elevation.

**Comment by romoore** [comment]
See https://github.com/material-components/material-components-ios/issues/6930 for a discussion on the topic.
