### ISSUE TITLE
Button: Ink: visual jank on iPhone 5S

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#692]
Providing the following information will increase the chances of your issue being dealt with quickly:
### Overview of the issue

MDCButton's Ink animation doesn't look quite right on iPhone 5Ses
### Reproduction steps

?
### Motivation and context

Reported by user
### Version number

N/A
### Operating system and hardware

?? iPhone 5S
### Related issues
- Are there similar issue been reported before?

**Comment by romoore** [comment]
@willlarche Could you provide any description/idea of what the problem was? Was it only reproducible on devices or simulator as well?

**Comment by romoore** [comment]
Closing this as unreproducible. Please file a new issue if the problem reoccurs.
