### ISSUE TITLE
[CollectionLayoutAttributes] Crash when section headers properties not completely set

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#6933]
From the internal issue (edited and distilled):

Diagnosis: `-[MDCCollectionViewLayoutAttributes isEqual:]`  compares all the fields of the layout attribute object, but MDCCollectionViewLayout doesn't reliably set all the fields of the attribute, for section headers and footers, so random junk can be left behind that causes otherwise equal objects to compare as unequal. The stricter checking in iOS 12 triggers the crash. 

 The fix is change the MDCCollectionViewLayout object to be more careful.

`MDCCollectionViewOrdinalPositionVerticalTopBottom` in `_sectionOrdinalPosition` one and 
`MDCCollectionViewOrdinalPositionVerticalTop` in the other,
`_backgroundImageViewInsets` differ and all components are very close to zero.
`_separatorInset` also, except one `_separatorInset.right` which is 1.9e93 !

 It sure looks to me like there is a code path in `MDCCollectionViewLayout` where it isn't setting every field of the MDCCollectionViewLayoutAttributes for section headers, so when one is re-used it can have junk in some of the fields.

---
#### Internal data
- Associated internal bug: [b/128998213](http://b/128998213)

**Comment by randallli** [comment]
I am confused why these are were opened.

**Comment by romoore** [comment]
This was opened as a result of a client filing a bug against Collections.

**Comment by DavidPhillipOster** [comment]
I'm the author of the original internal issue that led to the creation of this issue.
This issue is a false alarm.

MDCCollectionViewLayoutAttributes'sectionOrdinalPosition in a section header was being set inconsistently because of my bug in the code driving my collectionView.

Please close this issue.
