### ISSUE TITLE
[Collections] Drag handles have delay before allowing dragging

### ISSUE THREAD

**Issue by kwasimensah** [material-components/material-components-ios#694]
### Overview of the issue

On iOS tapping on a drag handle allows users to instantaneously star dragging an item. In Material Kit there's still a slight delay before we're able to drag the cell.

Video showing this off: https://drive.google.com/open?id=0BzO-ucTGhRD0U0ZyVk5XZVRZYTQ
### Reproduction steps

Reproducible in Collections -> Cell Editing Example using steps in the video above.
### Motivation and context

It's a polish bug for a featuring we're adding.
### Version number

13.2.0
### Operating system and hardware

iPhone 6s Plus ios 9.0 simulator

[Contributing](./contributing/README.md) has more information for making a great issue.

**Comment by ianegordon** [comment]
We are not intending on any significant updates to the current Collections component. 😞
We are working on a much simpler [List component](https://github.com/material-components/material-components-ios/tree/develop/components/List). 😄
