### ISSUE TITLE
[Buttons] Extended FAB with truncated title in the middle for long text

### ISSUE THREAD

**Issue by theSnare** [material-components/material-components-ios#6940]
> For usage questions: ask on [Stack  Overflow](https://stackoverflow.com/questions/tagged/material-components+ios).

## Reproduction steps

        fab.mode = .expanded
        fab.setImageTintColor(UIColor.white, for: .normal)
        fab.imageLocation = .leading
        fab.setImage(UIImage(named: "fab_sensor_icon"), for: .normal)
        fab.setTitle(NSLocalizedString("start_measuring", comment: ""), for: .normal)
        fab.imageTitleSpace = 16
        fab.setTitleColor(UIColor.white, for: .normal)
        fab.setContentEdgeInsets(UIEdgeInsets(top: 0, left: 6, bottom: 0, right: 6), for: .default, in: .expanded)
        fab.setTitleFont(UIFont(name: "FuturaStd-Heavy", size: 14), for: .normal)

## Expected behavior

The button should look like this (and it becomes like this as soon as I interact with it):

![IMG_0008](https://user-images.githubusercontent.com/19301796/54621380-f68c7d80-4a67-11e9-88f7-66f106395aad.jpg)

## Actual behavior

When the fab is created, the title text is truncated in the middle, for no reason:

![IMG_0007](https://user-images.githubusercontent.com/19301796/54621439-0a37e400-4a68-11e9-8b81-8b2e7fee51c0.jpg)

## Platform (please complete the following information)

 - Device: iPad (5th gen.)
 - OS: iOS 12.1.4

**Comment by romoore** [comment]
Have you tried setting the minimum size for the expanded mode?

```objc
- (void)setMaximumSize:(CGSize)maximumSize
              forShape:(MDCFloatingButtonShape)shape
                inMode:(MDCFloatingButtonMode)mode;
```

For your use case, looks like you have a shape `MDCFloatingButtonShapeDefault` and mode `MDCFloatingButtonModeExpanded`.  The default value based on internal design guidance is `CGSizeMake(328, 0)` and you may be bumping-up against this maximum.

**Comment by theSnare** [comment]
The setMaximumSize function doesn't solve the problem.
I tried to use setMinimumSize function, increasing the minimum width, and yes the text is not truncated anymore, but this way the width doesn't adapt according to the content of the button.
Also, why does the button adjust the text as soon as I press on it?
It seems a bug to me.

**Comment by theSnare** [comment]
I solved the problem calling view.layoutSubviews() after adding the fab as a subview:

        view.addSubview(fab)
        fab.translatesAutoresizingMaskIntoConstraints = false
        view.addConstraint(NSLayoutConstraint(item: view, attribute: .bottom, relatedBy: .equal, toItem: fab, attribute: .bottom, multiplier: 1, constant: 16.0))
        view.addConstraint(NSLayoutConstraint(item: view, attribute: .centerX, relatedBy: .equal, toItem: fab, attribute: .centerX, multiplier: 1, constant: 0))
        view.layoutSubviews()

**Comment by romoore** [comment]
I was about to suggest calling `sizeThatFits` on the FAB or else calling `layoutIfNeeded`. If you need to call `layoutSubviews` directly, then there is a bug in the MDC code because `setNeedsLayout` should already be set if you change a property that affects the current state.

**Comment by theSnare** [comment]
layoutIfNeeded works as well. I will use it then instead of layoutSubviews.

**Comment by romoore** [comment]
Sorry for the frustration, glad you found the solution! :)
