### ISSUE TITLE
[InkView] Cannot change inkColor when added to UITableViewCell

### ISSUE THREAD

**Issue by tylerjames** [material-components/material-components-ios#6946]
I'm using a UITableViewController with custom UITableViewCells and I've added an MDCInkView as the main view to which all other cell subviews are added.

In the `awakeFromNib()` function I add an `MDCInkTouchController` and make sure the view has `userInteractionEnabled = true`.

I've been able to get the ripple to show but for some reason it is always grey. I've tried setting the ink color in:

1. `cellForRowAtIndexPath` of the view controller
2. `awakeFromNib` of the cell
3. `layoutSubviews` of the cell

No matter what it always turns out grey. I don't know if the table view is doing some weird masking of the colour or that the ink colour just gets reset back to default for some reason.

**Comment by romoore** [comment]
Thanks, @tylerjames.  Could you post a minimal snippet of code showing how you're configuring the UITabBarItem's view to use MDCInkTouchController and how you're configuring the inkColor?

You may also find it useful to confirm the `inkView.inkColor` value in Xcode at a breakpoint. [The Quick Look feature in Xcode](https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/debugging_with_xcode/chapters/quick_look_data_types.html) is helpful in visually representing UIColors in the debugger.

**Comment by romoore** [comment]
Great! Glad to hear you figured it out. This might warrant better header documentation for MDCInkViewController in the future.
