### ISSUE TITLE
Bazel 0.23 does not work with the existing BUILD files

### ISSUE THREAD

**Issue by ianegordon** [material-components/material-components-ios#6954]
Install Bazel 0.23
Attempt to build the project
ERROR: /private/var/tmp/_bazel_iangordon/b75d48b0b8d3d4cee5dbda9ddac0fbee/external/build_bazel_rules_apple/apple/internal/rule_factory.bzl:110:35: late-bound attributes must not have a split configuration transition

The BUILD files work as expected with Bazel 0.20.

---
#### Internal data
- Associated internal bug: [b/128997538](http://b/128997538)

**Comment by romoore** [comment]
I think the way forward here is to update our rules/BUILD files and bump up to the latest bazel binary.
