### ISSUE TITLE
Unable to find a specification for 'MaterialComponentsBeta' [MDC-iOS] 

### ISSUE THREAD

**Issue by doronkatz** [material-components/material-components-ios#6982]
I wanted to switch over to using the beta podspec, and updating my Podfile according to the documentation, and received the error "unable to find a specification for MaterialComponentsbeta`.

## Reproduction steps

1. Updated `Podfile` with `pod  'MaterialComponentsBeta', :git => 'https://github.com/material-components/material-components-ios.git', :branch => 'develop'`
2. Ran `pod install`.
3. Received error.

## Expected behavior

Install appropriate pod libraries 

## Actual behavior

Received the following error:
```
Analyzing dependencies
Pre-downloading: `AlertOnboarding` from `https://github.com/doronkatz/AlertOnboarding.git`, branch `master`
Pre-downloading: `MaterialComponentsBeta` from `https://github.com/material-components/material-components-ios`, branch `develop`
[!] Unable to find a specification for 'MaterialComponentsBeta'.

[!] Unable to load a podspec from `MaterialComponentsSnapshotTests.podspec`, skipping:

Pod::DSLError

[!] Unable to load a podspec from `MaterialComponents.podspec`, skipping:

Pod::DSLError

[!] Unable to load a podspec from `MaterialComponentsBeta.podspec`, skipping:

Pod::DSLError
```

## Platform (please complete the following information)

 - Cocoapod 1.2.0.rc.1
 - Mojave

---
#### Internal data
- Associated internal bug: [b/129232807](http://b/129232807)

**Comment by romoore** [comment]
@doronkatz Can you please try updating to CocoaPods 1.6.0 and see if that works?  I don't believe we support versions earlier than 1.5.0 for installation. Version 1.6.0+ is required for library contributors and authors.

**Comment by doronkatz** [comment]
Actually i just did and it worked. So yes it must have been the older version. Thanks. Ill mark as closed and completed.. Thanks!
