### ISSUE TITLE
How to replace Roboto font with our custom font in MDC(MaterialComponents) framework?

### ISSUE THREAD

**Issue by mohsinbmwm3** [material-components/material-components-ios#7055]
Any way of changing/replacing Roboto(default) font of framework with SanFrancisco font in iOS?
I want SanFrancisco font through out the framework. 

Is there any single point of control for this?
Please let me know.

Thanks Much.

**Comment by romoore** [comment]
Hi @mohsinbmwm3 . Which version of MDC-iOS are you using? I don't believe we've used Roboto in MDC-iOS for more than a year.  [Material guidelines are clear that the iOS platform fonts should be used on iOS.](https://material.io/design/platform-guidance/cross-platform-adaptation.html#cross-platform-guidelines)

**Comment by mohsinbmwm3** [comment]
Hi @romoore ,
I am using 80.0.0 version.
Got it, Thanks @romoore, it is mentioned in guidelines.

**Comment by mohsinbmwm3** [comment]
But what if we want to use other font?

**Comment by romoore** [comment]
If you want to use non-system fonts, then I would recommend that you assign those fonts in a [Typography Scheme](https://github.com/material-components/material-components-ios/tree/develop/components/schemes/Typography) and use the scheme to style your componentry and views.

[Buttons has a simple example showing how to apply a custom font](https://github.com/material-components/material-components-ios/blob/develop/components/Buttons/examples/ButtonsCustomFontViewController.swift) for one of the typography types.
