### ISSUE TITLE
Overriding `canMoveItemAtIndexPath:` trumps `collectionViewAllowsReordering:`

### ISSUE THREAD

**Issue by Arcank** [material-components/material-components-ios#706]
### Overview of the issue

In MDCCollectionViewEditingDelegate, one can select to return NO to `-collectionView:collectionViewAllowsReordering:`, but it has no effect if `-collectionView:canMoveItemAtIndexPath:` is also overridden and return YES for index paths.

Since `~collectionViewAllowsReordering:` is checked in the parent class implementation of `~canMoveItemAtIndexPath:`, the subclass can easily bypass the logic to forbid reordering.

Is it intended?
### Reproduction steps

https://github.com/google/material-components-ios/pull/707
### Version number

d597cb5

**Comment by jverkoey** [comment]
Marking as Obsolete because we do not intend to continue to invest effort into Collections. Please consider using the new List component instead: https://github.com/material-components/material-components-ios/tree/develop/components/List
