### ISSUE TITLE
{Xcode 10.2} Compilation fails on 32-bit architectures due to loss of precision

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#7079]
MDC-iOS library clients are seeing failures compiling the library using Xcode 10.2. Specifically, there are loss-of-precision errors being generated due to the use of uncast doubles in our code base.

### Examples

```
/components/Collections/src/private/MDCCollectionInfoBarView.m:138:30: error: implicit conversion when assigning computation result loses floating-point precision: 'double' to 'CGFloat' (aka 'float') [-Werror,-Wconversion]
    _backgroundTransformY *= -1.0;
                          ~~ ^~~~
1 error generated.

/components/Shapes/src/MDCRectangleShapeGenerator.m:215:16: error: implicit conversion when assigning computation result loses floating-point precision: 'double' to 'CGFloat' (aka 'float') [-Werror,-Wconversion]
    angle += 2 * M_PI;
          ~~ ~~^~~~~~
1 error generated.
```

---
#### Internal data
- Associated internal bug: [b/130040111](http://b/130040111)

**Comment by andrewoverton** [comment]
@romoore, I think this issue was resolved by https://github.com/material-components/material-components-ios/pull/7130. I am able to compile with "Generic iOS Device" chosen in Xcode 10.2.1 and 10.1. Do you think this is safe to close?

**Comment by romoore** [comment]
Yep, as long as Xcode 10.2 is compiling without errors it's good to resolve. Thanks!
