### ISSUE TITLE
[Xcode 10.1] Can't build catalog project

### ISSUE THREAD

**Issue by zlib** [material-components/material-components-ios#7093]
## Reproduction steps

1. pod install
2. Open xcworkspace in Xcode 10.1
3. Try to build the Catalog project

## Expected behavior

Build succeed

## Actual behavior

Build failed.

## Platform (please complete the following information)

 - MacOS 10.14.3

---
#### Internal data
- Associated internal bug: [b/130301500](http://b/130301500)

**Comment by romoore** [comment]
@zlib Can you post the error message you're seeing in Xcode?

**Comment by andrewoverton** [comment]
@zlib This is probably a silly question but have you tried deleting derived data and stuff like that? I'm not having any problems building the catalog with the latest on develop using Xcode 10.1.

**Comment by zlib** [comment]
@andrewoverton Of course, I tried that. And I asked my colleague to build it on his MacBook. Same problem.

**Comment by zlib** [comment]
@romoore I have 2 errors:
<img width="256" alt="Screenshot 2019-04-11 at 11 16 22" src="https://user-images.githubusercontent.com/7572263/55941808-a8742f80-5c4b-11e9-9cbf-797d45b9a8f7.png">

**Comment by romoore** [comment]
@zlib Can you confirm which version of CocoaPods you're using?

```
pod --version
```

**Comment by romoore** [comment]
Could you also post the relevant portion of your Podfile (the part that includes MaterialComponents)?

**Comment by zlib** [comment]
I had cocoapods version 1.5.3. I have just updated to version 1.6.1 and now everything builds without a problem. 
Thank you!
