### ISSUE TITLE
[Ink] Remove MDCInkColorThemer

### ISSUE THREAD

**Issue by dmaclach** [material-components/material-components-ios#7097]
MDCInkColorThemer is deprecated and appears to be referenced by nothing. Please remove it to reduce code size.

**Comment by romoore** [comment]
To be clear, it's not deprecated but is planned for deprecation.  There is currently no theming extension for it, so we cannot deprecate it just yet.

**Comment by material-mirror** [comment]
The internal issue [b/130301690](http://b/130301690) is now closed. This issue is being closed as a result.
