### ISSUE TITLE
[TextFields] Remove MDCTextFieldColorThemer

### ISSUE THREAD

**Issue by dmaclach** [material-components/material-components-ios#7098]
MDCTextFieldColorThemer doesn't appear to be being used by anything. Let's get rid of it and reduce codesize.

**Comment by romoore** [comment]
@dmaclach  I believe you mean inside Google. It may be used by third parties.

**Comment by dmaclach** [comment]
How do you measure? Given that it's deprecated, what is the schedule for
removal?

**Comment by romoore** [comment]
MDCTextFieldColorThemer is not deprecated, although two methods are planned for deprecation.  We try to stick to the [MDC-iOS Deprecation Policy](https://github.com/material-components/material-components-ios/blob/develop/contributing/deprecation_policy.md) when deprecating APIs, especially when they've been available for a significant period of time.

**Comment by romoore** [comment]
We cannot measure use by third parties, which is why we have a deprecation policy.  I was trying to clarify your statement that doesn't appear to be used by anything.

**Comment by material-mirror** [comment]
The internal issue [b/130300768](http://b/130300768) is now closed. This issue is being closed as a result.

**Comment by tansaku** [comment]
MDCTextFieldColorThemer is used in https://github.com/GoogleCloudPlatform/ios-docs-samples/tree/master/dialogflow/stopwatch - is there a simple replacement for it?
