### ISSUE TITLE
Internal issue:: b/130723794

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#7155]
This was filed as an internal issue. If you are a Googler, please visit [b/130723794](http://b/130723794) for more details.

---
#### Internal data
- Associated internal bug: [b/130723794](http://b/130723794)

**Comment by jverkoey** [comment]
The internal issue was mis-filed.

**Comment by material-mirror** [comment]
The internal issue [b/130723794](http://b/130723794) is now closed. This issue is being closed as a result.

**Comment by randallli** [comment]
Dont know how this is pointing at 2 different internal bugs but it was not fixed.

**Comment by romoore** [comment]
@randallli That usually happens when one of the internal bugs gets reassigned to another team.

**Comment by material-mirror** [comment]
The internal issue [b/130723794](http://b/130723794) is now closed. This issue is being closed as a result.
