### ISSUE TITLE
Add an option for not displaying the footer infobar

### ISSUE THREAD

**Issue by gambard** [material-components/material-components-ios#716]
### Overview of the issue

I may have missed it, but I don't see a way to prevent the MDCCollectionViewController from presenting the footer infobar (with "Delete") when editing some elements.
I would love to have such an option, to have my own infobar. For now I can either override -updateFooterInfoBarIfNecessary or put my own infobar in front of the default one, which is far from being perfect.
### Reproduction steps
- Create a MDCCollectionViewController
- Enter edit mode and select some element
- The infobar shows
### Motivation and context
- I want to be able to have my own infobar with more options.
### Version number
- 203562553800ed3d3b5eebfd1dd76cda875d833c
### Operating system and hardware
- iOS 10.0

**Comment by jverkoey** [comment]
Marking as Obsolete because we do not intend to continue to invest effort into Collections. Please consider using the new List component instead: https://github.com/material-components/material-components-ios/tree/develop/components/List
