### ISSUE TITLE
[Site] Add asset tests to site

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#717]
The site needs automatic testing on production deploy. Specifically it needs to check for missing assets (.js, styling & images.)

There have been a couple times when file lock conflict prevented the files from uploading. The users then saw a raw html page and 404s.

Other tests welcomed.

**Comment by shyndman** [comment]
Hey Will,

Mind going into a bit more detail on this?
> There have been a couple times when file lock conflict prevented the files from uploading. The users then saw a raw html page and 404s.

**Comment by willlarche** [comment]
Sure thing!

Deploying site changes will the responsibility of the MDC iOS Engineers and we are not web platform specialists. In the earlier experiments with this, we found a case where because of a state of the machine doing the deploy, the assets never got uploaded. Something that would be easy for a web eng to fix is expensive for us since we don't have expertise.

So we'd like some simple tests on deploy like: did the files make it and are they available.

**Comment by jverkoey** [comment]
This is now being done through kokoro: https://github.com/material-components/material-components-ios/blob/develop/.kokoro#L231
