### ISSUE TITLE
[Ripple] How to add inkstyle to a custom UIButton?

### ISSUE THREAD

**Issue by mohsinbmwm3** [material-components/material-components-ios#7174]
Hello,

I wanted to add MDCButton ripple effect on my custom UIButton. I cannot extend from MDCButton because my custom button already extended from another class. 

Is there any way to add inkstyle separately?

Thanks

---
#### Internal data
- Associated internal bug: [b/130790490](http://b/130790490)

**Comment by romoore** [comment]
In your case, I would [see if `MDCRippleTouchController` would work for your button](https://github.com/material-components/material-components-ios/tree/develop/components/Ripple#mdcrippletouchcontroller). If not, [a simpler example of integrating `MDCStatefulRippleView` can be seen in `MDCCard`](https://github.com/material-components/material-components-ios/blob/develop/components/Cards/src/MDCCard.m#L327), where the rippleView is added as a subview.  For a more complex case like MDCButton, you may want to see [how Ripple was added to MDCButton](https://github.com/material-components/material-components-ios/pull/7087) to give yourself an idea.

**Comment by mohsinbmwm3** [comment]
Thanks @romoore, MDCStatefulRippleView worked for me.
