### ISSUE TITLE
Please provide instruction to install manually without Cocoapods

### ISSUE THREAD

**Issue by BeerPoldet** [material-components/material-components-ios#7200]
## Feature Request/Suggestion

I'm on project that's not using Cocoapods. So I need clear instruction to install each components into my Xcode project.

## Additional context

\-

---
#### Internal data
- Associated internal bug: [b/131061228](http://b/131061228)

**Comment by BeerPoldet** [comment]
Any updates?

**Comment by ThePragmaticArt** [comment]
Welcome to Google, land of the stubborn and lack of care....

**Comment by ThePragmaticArt** [comment]
@jverkoey did this really just get closed without any feedback/response. It's a ridiculously straight forward and commonly expected ask.

**Comment by jverkoey** [comment]
My apologies! Didn't get the comment landed into each of these issue closures:

As of July 15 MDC entered maintenance mode. Learn more at https://github.com/material-components/material-components-ios#material-components-for-ios
