### ISSUE TITLE
Create a readme generator presubmit job

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#7202]
## Context

Our components use a component generator, `scripts/generate_readme` to generate a composite README.md from the files in the `docs/` folder for each component. This script needs to be run any time the `docs/` content changes. It is understandably easy to forget to run this script though.

## Feature Request/Suggestion

The purpose of this job will be to catch any missed invocations of the readme generator script. It should fail if the readme generator resulted in any new changes to a component's readme files, otherwise it should pass.

The job should simply run `scripts/generate_all_readmes` and check whether there are any new diffs.

---
#### Internal data
- Associated internal bug: [b/131062156](http://b/131062156)

**Comment by bernaferrari** [comment]
I suggest making a pre-commit hook with this:
https://stackoverflow.com/a/51550375/4418073 while iterating on `components/*` (but ignoring `testing/*`, `docs/*`, `schemes/*` and `private/*`). I'm not a shell wizard, but this shouldn't be a lot of trouble to implement.
