### ISSUE TITLE
[NavigationBar] MDCNavigationBar lost `titleView`

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#7207]
This was filed as an internal issue. If you are a Googler, please visit [b/131065490](http://b/131065490) for more details.

From the internal bug:

> I found that my MDCNavigationBar.titleView always got stolen by UINavigationBar when [titleView is assigned] more than once. I stepped into MDCNavigationBar's setTitleView: method, and found by the time it reaches here the titleView's superView is already changed from MDCNavigationBar to some iOS internal object. However since the (self.titleView == titleView) condition is true, MDCNavigationBar.setTitleView just early returned without grabbing back the titleView.

---
#### Internal data
- Associated internal bug: [b/131065490](http://b/131065490)

**Comment by jverkoey** [comment]
The root cause here is that we only do the Indiana Jones sandbag swap the first time the titleView is assigned. On subsequent assignments of the same value we don't re-swap the sandbag, resulting in navigationItem.titleView being stolen by UINavigationBar.

A test case to simulate this behavior:

```swift
  func testNavigationItemTitleViewAssignmentWithReassignmentThenTheftKeepsTitleViewAsSubview() {
    // Given
    let navigationBar = MDCNavigationBar()
    let titleView = UIView()
    let navigationItem = UINavigationItem()

    // When
    navigationItem.titleView = titleView
    navigationBar.observe(navigationItem)
    navigationItem.titleView = titleView
    let simulatedThiefView = UIView()
    simulatedThiefView.addSubview(navigationItem.titleView!)

    // Then
    XCTAssertEqual(navigationItem.titleView?.superview, simulatedThiefView)
    XCTAssertEqual(titleView.superview, navigationBar)
  }
```

**Comment by jverkoey** [comment]
The culprit lines are:

https://github.com/material-components/material-components-ios/blob/3543c1cfbd6155432ce209cae26a77857f7daead/components/NavigationBar/src/MDCNavigationBar.m#L565-L568
