### ISSUE TITLE
MDCCollectionViewStyling allowsItemInlay property not honored in editing mode

### ISSUE THREAD

**Issue by jyquinn** [material-components/material-components-ios#722]
Setting self.styler.allowsItemInlay = NO in an MDCCollectionViewController subclass does not prevent items from being inlaid when entering edit mode. I believe this is because MDCCollectionViewController sets _styler.allowsItemInlay to YES in collectionViewWillBeginEditing. Is this intentional?

This prevents clients from having editing mode without the item inlay. We would like to prevent inlays because in long lists, entering editing mode with inlays shifts the scroll index in a jarring way.

@chriscox @Arcank

**Comment by ianegordon** [comment]
Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄
