### ISSUE TITLE
Adding Ink to an enclosed shape (circle) requires extra work

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#724]
### Overview of the issue

Ink on a circular button spreads beyond the circle
### Reproduction steps

Take an opaque button with ink and adjust its corner radius. Touch. The ink will expand beyond the visible path of the button. It will expand all the way to the bounds.

Therefore, you must set the button's layer to clip to its bounds.
### Motivation and context

Looks incorrect. The layer has a shape enclosed by the bounds. Ink should expand only to fill it.

This problem doesn't exist in floating action button. Consider using the existing solution from that class here.
### Related issues

---
#### Internal data
- Associated internal bug: [b/117179640](http://b/117179640)

**Comment by material-mirror** [comment]
The internal issue [b/117179640](http://b/117179640) is now closed. This issue is being closed as a result.
