### ISSUE TITLE
Ink doc doesn't have warning not to add to UIButton

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#725]
### Overview of the issue

The documentation for inkView and inkTouchController have no mention of best practice regarding buttons.
### Reproduction steps

Read it.
### Motivation and context

InkViewControllers contain gesture recognizers. They will conflict with the gesture recognizers in the UIButtons. MDCButton already deals with this collision implicitly and should be mentioned as the best practice when ink is needed on a button.

We can also mention that when a user needs to subclass UIControl (or something else that includes touch response) they could manually handle forwarding touch output to an inkView.

**Comment by ianegordon** [comment]
Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄
