### ISSUE TITLE
[Dialogs] Disable dismiss on background tap by default

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#7257]
This was filed as an internal issue. If you are a Googler, please visit [b/120672501](http://b/120672501) for more details.

---
#### Internal data
- Associated internal bug: [b/120672501](http://b/120672501)
- Blocked by: https://github.com/material-components/material-components-ios/issues/6553

**Comment by galiak11** [comment]
Dismissing on background tap is the intended default behavior. Closing the ticket since this is no longer an issue.

**Comment by galiak11** [comment]
Dismissing on background tap is the intended default behavior. Closing the ticket since this is no longer an issue.
