### ISSUE TITLE
The scripts/release notes command doesn't include changes that only affect `docs/` directories.

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#7278]
The `notes` command doesn't appear to include changes that only affect `docs/` directories.

_Originally posted by @jverkoey in https://github.com/material-components/material-components-ios/pull/7273/review_comment/create_

---
#### Internal data
- Associated internal bug: [b/131422784](http://b/131422784)

**Comment by codeman7** [comment]
@jverkoey Do you feel like it should affect the `docs/` directory?

**Comment by jverkoey** [comment]
The release notes should likely include documentation-only changes as well yes.

**Comment by romoore** [comment]
Does that mean we should be calling out documentation changes alongside features or major API changes?

**Comment by jverkoey** [comment]
No, this issue is only related to making the automated tooling pick up docs-related changes.
