### ISSUE TITLE
build_all_pod_projects should not call `pod install` every time

### ISSUE THREAD

**Issue by ajsecord** [material-components/material-components-ios#730]
1. A script should do one and only one thing, and its name should reflect that.
2. If there are build problems and the `build_all_pod_projects` script needs to be run again, it calls `pod install` _again_ [sucking more precious life away](http://www.imdb.com/title/tt0093779/quotes?item=qt0482729).
3. The release instructions should just include a step to run `scripts/release/manage_pods install` before the build stage.

**Comment by samsymons** [comment]
Is this still an issue after [this commit](https://github.com/material-components/material-components-ios/commit/b54f2fbec06b328add56120e7aa75aa01f79c1fa#diff-d6c5855a62cf32a4dadbc2831f0f295f)?

**Comment by jverkoey** [comment]
Likely obsolete.
