### ISSUE TITLE
[Tabs] MDCTabBarItemAppearanceTitles with image to the side of text.

### ISSUE THREAD

**Issue by matgar26** [material-components/material-components-ios#7302]
## Feature Request/Suggestion
It would be awesome to be able to have the `MDCTabBarItemAppearanceTitles` with an option to have text and images, but with the image next to the text instead of it above the text.

## Additional context
 I am working on a project that has that requirement, but found no way to get the image to the side of the text.

![Screen Shot 2019-04-30 at 1 48 27 PM](https://user-images.githubusercontent.com/13424343/56989024-ab798600-6b4e-11e9-96b1-06a387db9abb.png)

---
#### Internal data
- Associated internal bug: [b/131768656](http://b/131768656)

**Comment by romoore** [comment]
Thanks, @matgar26! I've forwarded this suggestion on to our design team. Googlers see the internal Issue for details.

**Comment by romoore** [comment]
Hey @matgar26. [MDCTabBarView](https://github.com/material-components/material-components-ios/tree/develop/components/Tabs#mdctabbarview) supports custom views if you want customized layout options like that. Please try it out and feel free to reach out to me if you have any questions or feedback about the APIs and documentation!

**Comment by romoore** [comment]
Closing this now that MDCTabBarView supports custom views. Please file a new issue if you find specific problems working with MDCTabBarView. Thanks!
