### ISSUE TITLE
Release scripts should just manage CHANGELOG automatically

### ISSUE THREAD

**Issue by ajsecord** [material-components/material-components-ios#731]
In the release there are currently several steps that involve running a script that spews out contents for the CHANGELOG, copying them, then pasting them into the CHANGELOG. More wasted life. 

The problem isn't with the `api_diff` script per se, it's the copying and pasting. Make a script that just inserts the correct text into the CHANGELOG. The releaser can then edit the file to clean it up if necessary (preferably not, but <shrug>).

**Comment by ianegordon** [comment]
Done.
