### ISSUE TITLE
Refactor reusable methods in MDCFontScaler class

### ISSUE THREAD

**Issue by wenyuzhang666** [material-components/material-components-ios#7312]
The code logic in `scaledFontWithFont:` and `scaledValueForValue:` should not be coupled with instance properties (e.g. `_scalingCurve`).

We need to extract the reusable part from them to a helper class so that other classes can use them.

This issue blocks the development of b/129762938.

---
#### Internal data
- Associated internal bug: [b/131745902](http://b/131745902)

**Comment by romoore** [comment]
@wenyuzhang666 Can you please clarify why it should not be an instance method? Why do these methods need to be used outside of an MDCFontScaler?

**Comment by romoore** [comment]
Are you proposing an API similar to this?

```objc
+ [MDCFontScalerHelper scaledFontWithFont:(UIFont *)font scalingCurves:(NSDictionary *)scalingCurves]
```

**Comment by material-mirror** [comment]
The internal issue [b/131745902](http://b/131745902) is now closed. This issue is being closed as a result.
