### ISSUE TITLE
scripts/release/api_diff fails

### ISSUE THREAD

**Issue by ajsecord** [material-components/material-components-ios#737]
./scripts/release/api_diff 
Note: checking out '5d7ad466b9e1429ad6242272958b149ded34da63'.
Note: checking out '205b1b49fd311af9246133e1499007dec0957e4b'.

Auto-generated by running:
    scripts/api_diff -o 5d7ad466b9e1429ad6242272958b149ded34da63 -n 205b1b49fd311af9246133e1499007dec0957e4b
### Slider

/var/folders/td/c9xng9g11ws4w4dmw14bzknm005lr4/T/tmp.RHVzhtlz/old/components/Slider/src/MDCSlider.h:19:9: fatal error: 'MDCThumbTrack.h' file not found
No public API changes detected.

**Comment by ianegordon** [comment]
Closing as obsolete.  😞 
Please open a new bug if this is still an issue.  😄
