### ISSUE TITLE
[Typography] No scaling curves attached when I set mdc_adjustsFontForContentSizeCategory

### ISSUE THREAD

**Issue by codeman7** [material-components/material-components-ios#7442]
I created a MDCTypographyScheme with the following snippet and then set `mdc_adjustsFontForContentSizeCategory` and it didn't scale my fonts.

```swift
let typographyScheme = MDCTypographyScheme(defaults: .material201804)
typographyScheme.mdc_adjustsFontForContentSizeCategory = true
```

I thought this would give me scaled fonts but it just sets the property. This property should either be _readonly_ or the _setter_ should scale my fonts.

**Comment by romoore** [comment]
That flag is intended as a pass-through for App code to set so that library code (like ours) can know whether or not to scale fonts when applying theming.

**Comment by romoore** [comment]
Opened https://github.com/material-components/material-components-ios/issues/7449 to track the confusing property name.
