### ISSUE TITLE
[Typography] mdc_adjustsFontForContentSizeCategory is set to YES my font didn't scale

### ISSUE THREAD

**Issue by codeman7** [material-components/material-components-ios#7444]
I tried to use the latest MDCTypographyScheme with mdc_adjustsFontForContentSizeCategory set to YES and then use a custom font and it didn't scale as expected.

```swift
 // This scheme sets mdc_adjustFontForContentSizeCategory to true
let customTypographyScheme = MDCTypographyScheme(defaults: .material201902)
 // This font should scale for me
customTypographyScheme.button = UIFont.systemFont(ofSize: 19) // This font should scale for me
// Prints out `nil`
print(customTypographyScheme.button.mdc_scalingCurve)
```

Either

1. The fonts should all be _readonly_ 
2. When I set a font and _mdc_adjustFontForContentSizeCategory_ is set to `true` and I set a font it should scale.

---
#### Internal data
- Associated internal bug: [b/133320510](http://b/133320510)

**Comment by jverkoey** [comment]
Is the `mdc_adjustFontForContentSizeCategory` you're referring to here the typography scheme's `mdc_adjustFontForContentSizeCategory`?

**Comment by codeman7** [comment]
WAI
