### ISSUE TITLE
[TypographyScheme] `mdc_adjustsFontForContentSizeCategory` is poorly named

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#7449]
The `mdc_adjustsFontForContentSizeCategory` property on TypographyScheme is confusing since it matches unrelated APIs on components for automatically adjusting dynamic type fonts. It's intended as a pass-through to theming code so that it can know whether the user wants to apply scaled fonts as part of theming.

```objc
/**
 Whether user interface elements should automatically resize based on the device's setting.

 This can be used by client to communicate whether they support dynamic type to both our theming
 functionality and embedded frameworks that also render UI.
*/
@property(nonatomic, readonly) BOOL mdc_adjustsFontForContentSizeCategory;
```

---
#### Internal data
- Associated internal bug: [b/134058145](http://b/134058145)

**Comment by codeman7** [comment]
#7465 Fixed this
