### ISSUE TITLE
[schemes/color] Please provide a high contrast scheme

### ISSUE THREAD

**Issue by codeman7** [material-components/material-components-ios#7522]
As a developer I would like to switch between two schemes based on if my users have enabled _high contrast mode_ via Settings -> General -> Accessibility -> Increase Contrast. 

Currently I use `MDCColorSchemeDefaultsMaterial201804` within my application but I would love to switch to something along the lines of `MDCColorSchemeDefaultsMaterialHighContrast201804` when a user has enabled this so I can get high contrast out of the box to use within my application.

---
#### Internal data
- Associated internal bug: [b/134131378](http://b/134131378)

**Comment by romoore** [comment]
Looks like this is part of https://github.com/material-components/material-components-ios/issues/4339
