### ISSUE TITLE
[Buttons] Voiceover announcement when changing the title 

### ISSUE THREAD

**Issue by codeman7** [material-components/material-components-ios#7525]
When changing the title of a button after it is tapped, voiceover sometimes announces the label incorrectly. 

## Reproduction steps

Create a MDCButton with the following snippet
```
let button = MDCButton()
button.setTitle("New", for: .normal)
button.addTarget(self, action: #selector(toggle(_:)), for: .touchUpInside)

func toggle(_ sender: MDCButton) {
  if (button.title(for: .normal) == "New") {
    button.setTitle("Old", for: .normal)
  } else {
    button.setTitle("New", for: .normal)
  }
}
```

1. Navigate to the button with VoiceOver on
2. Tap the button

## Expected behavior

VoiceOver announce the standard _click_ and then the title.

## Actual behavior

At times the title gets cut off by the click sound.

## Additional context

This only occurs if a client does not set the `accessibilityLabel` of the button, if they set that property then this issue is Works as Intended.

---
#### Internal data
- Associated internal bug: [b/134158241](http://b/134158241)

**Comment by material-mirror** [comment]
The internal issue [b/134158241](http://b/134158241) is now closed. This issue is being closed as a result.
