### ISSUE TITLE
[AppBar] Content jumps a in different incremental amounts

### ISSUE THREAD

**Issue by codeman7** [material-components/material-components-ios#7582]
## Reproduction steps

0. Turn on VoiceOver
1. Open MDCDragons
2. Navigate to "AppBar+UITableViewController" example
3. Navigate down the cells

## Expected behavior

As I navigate down the table I'd expect the app bar to shift in equal incremental amounts

## Actual behavior

As I navigate down the table the AppBar shrinks in different amounts 40/40/100/40pt as an example.

## Video
![Movie](https://user-images.githubusercontent.com/7131294/59456928-6c914e00-8de5-11e9-8e90-e33e884f5f46.gif)

---
#### Internal data
- Associated internal bug: [b/135194813](http://b/135194813)

**Comment by material-mirror** [comment]
The internal issue [b/135194813](http://b/135194813) is now closed. This issue is being closed as a result.
