### ISSUE TITLE
[AppBar] When used with VoiceOver sometimes does a loop of the elements

### ISSUE THREAD

**Issue by codeman7** [material-components/material-components-ios#7585]
## Reproduction steps

0. Turn on VoiceOver
1. Open MDCDragons
2. Navigate to "Manual Tabs Jump" example
3. Navigate from the back button to the table

## Expected behavior

The accessibility elements go Back Button, Title, Tab 1, Tab 2

## Actual behavior

The accessibility elements go Back Button, Title, Back Button, Title, Tab 1, Tab 2

## Video
_Note:_ I am constantly swiping to the right, I never swipe back.
![Move](https://user-images.githubusercontent.com/7131294/59463756-b2a1de00-8df4-11e9-935d-d62f95bda221.gif)

---
#### Internal data
- Associated internal bug: [b/135209512](http://b/135209512)

**Comment by material-mirror** [comment]
The internal issue [b/135209512](http://b/135209512) is now closed. This issue is being closed as a result.
