### ISSUE TITLE
[TextFields] MDCTextInputControllerOutlinedTextArea border does not become wider on edit

### ISSUE THREAD

**Issue by istvanp** [material-components/material-components-ios#7587]
## Reproduction steps

1. Create a MDCMultilineTextField textfield and attach a MDCTextInputControllerOutlinedTextArea controller to it.
2. Run it. Tap into the field to edit.

## Expected behavior

Border becomes 2 points wide, like for the single-line version (MDCTextInputControllerOutlined).

## Actual behavior

Notice the border remains 1 point wide instead of 2.

## Platform (please complete the following information)

 - Device: iPhone 6
 - OS: iOS 12.3.1

## Additional context

None.

---
#### Internal data
- Associated internal bug: [b/135208372](http://b/135208372)

**Comment by andrewoverton** [comment]
This issue was closed by https://github.com/material-components/material-components-ios/pull/9454
