### ISSUE TITLE
[AppBar] Does not invert colors

### ISSUE THREAD

**Issue by codeman7** [material-components/material-components-ios#7592]
An appbar with an image does not invert the colors of that image if smart invert is on

## Reproduction steps

0. Turn on Smart Invert
1. Open MDCDragons
2. Navigate to AppBar -> "Imagery" example

## Expected behavior

The image should invert its colors

## Actual behavior

The same image as before is represented.
 

---
#### Internal data
- Associated internal bug: [b/135209485](http://b/135209485)

**Comment by jverkoey** [comment]
I believe images are not actually supposed to be inverted when smart invert is enabled.

"Smart Invert reverses the colors on the display, except for images, media, and some apps that use dark color styles."
From: https://support.apple.com/en-us/HT207025
