### ISSUE TITLE
[Typography] Delete mdc_adjustsFontForContentSizeCategory from MDCTypographyScheme

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#7618]
useCurrentContentSizeCategoryWhenApplied is the replacement API.

Acceptance criteria:

- `mdc_adjustsFontForContentSizeCategory` is deleted from MDCTypographyScheme
- `useCurrentContentSizeCategoryWhenApplied` is marked as its replacement.
- `useCurrentContentSizeCategoryWhenApplied` is no longer optional in `MDCTypographyScheming`.

---
#### Internal data
- Associated internal bug: [b/135471973](http://b/135471973)

**Comment by romoore** [comment]
What are we replacing it with?
