### ISSUE TITLE
[TextFields] Character count limit repeatedly indicates that "zero characters are remaining" 

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#7624]
## Repro steps

1. Open MDCDragons.
2. Open Kitchen Sink Text Fields example.
3. Focus the single line text field with a character count.
4. Type 49 characters.
5. Enable VoiceOver.
6. Type 5 more characters.

## Expected behavior

After the first character is typed, VoiceOver announces "0 characters remaining".
After the second character is typed, VoiceOver announces something to indicate that the text is overflowing even further.

## Actual behavior

VoiceOver announces "0 characters remaining" after every new character.

---
#### Internal data
- Associated internal bug: [b/135492412](http://b/135492412)

**Comment by romoore** [comment]
Should we reopen this to [fix FullWidth](https://github.com/material-components/material-components-ios/blob/8dbebd1/components/TextFields/src/MDCTextInputControllerFullWidth.m#L1071) as well?

**Comment by bryanoltman** [comment]
Ah, good catch. Yes, I think so.

**Comment by material-mirror** [comment]
The internal issue [b/135492412](http://b/135492412) is now closed. This issue is being closed as a result.
