### ISSUE TITLE
[TextFields] When an error occurs it interupts VoiceOver

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#7625]
## Repro steps

1. Open MDCDragons.
2. Open TextFields' kitchen sink example.
3. Focus a single line text field with a character count.
4. Enable VoiceOver.
5. Type a space character.

## Expected behavior

VoiceOver announces the remaining characters and then the error, or vice-versa.

## Actual behavior

VoiceOver starts announcing the number of remaining characters but then gets interrupted by the error.

---
#### Internal data
- Associated internal bug: [b/135492146](http://b/135492146)

**Comment by romoore** [comment]
@jverkoey Can you please clarify which of the single-line text fields with character count fields is producing this error?
