### ISSUE TITLE
[TextFields] Dynamic Type is not demonstrated in the catalog

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#7626]
## Repro steps

1. Open MDCDragons.
2. Increase or decrease the dynamic type size.
3. Open the kitchen sink example.

## Expected behavior

The text fields have reacted to the new dynamic type size.

## Actual behavior

None of the text fields have reacted to dynamic type.

---
#### Internal data
- Associated internal bug: [b/135492318](http://b/135492318)

**Comment by romoore** [comment]
This is already done. The "Custom font" example shows a UIFontMetrics-based font.

![Simulator Screen Shot - iPhone 7 - 2019-11-13 at 23 48 40](https://user-images.githubusercontent.com/1753199/68827494-36941680-0670-11ea-8a50-6b5661376269.png)
