### ISSUE TITLE
[Catalog] FAB is not shaped

### ISSUE THREAD

**Issue by aufflick** [material-components/material-components-ios#7634]
[Catalog app > Buttons > Shaped buttons] FAB is not shaped

## Reproduction steps

1. Build and run Catalog app (Xcode 10 or 11)
2. Launch app > Buttons > Shaped buttons

## Expected behavior

All buttons shown on screen will use the shape described

## Actual behavior

FAB is not shaped.

## Platform (please complete the following information)

 - Device: Simulator
 - OS: iOS 12 or 13

## Additional context

Perhaps related to #5899

Screenshot: https://www.dropbox.com/s/phi5an2tnesr7o3/IMG_4090.JPG?dl=0

---
#### Internal data
- Associated internal bug: [b/135618204](http://b/135618204)

**Comment by romoore** [comment]
Note that [the Material Guidelines for Floating Action Buttons](https://material.io/design/components/buttons-floating-action-button.html#theming) expressly shows a shaped FAB.

<img width="751" alt="posivibes material example showing shaped FAB" src="https://user-images.githubusercontent.com/1753199/59787443-701a4e80-9297-11e9-8af0-3fd0f791255a.png">

**Comment by zakdances** [comment]
Also, the [documentation](https://github.com/material-components/material-components-ios/tree/stable/components/schemes/Shape) for shapes only shows how to create and configure a `MDCShapeScheme` object, it doesn't show how to apply the scheme to anything.

**Comment by romoore** [comment]
Closing this since the Catalog is not demonstrating all possibilities, but is showcasing the base component and material theming. In this case, the Theming for Material does not support a shaped FAB.
