### ISSUE TITLE
[Dialogs] Accessibility frame is larger than displayed text

### ISSUE THREAD

**Issue by codeman7** [material-components/material-components-ios#7637]
If the text in a Dialog is really long then the accessibility frame is larger than the visible window of text on screen.  

## Reproduction steps

0. Turn on Voiceover
1. Open MDCDragons
2. Open Dialogs -> More Material Alert Examples -> Overpopulated Alert
3. Bring the message into focus

## Expected behavior

The accessibility frame should only be what is rendered on screen.

## Actual behavior

The accessibility frame includes text that isn't visible

## Screenshot
![IMG_4263](https://user-images.githubusercontent.com/7131294/59738153-3fea9580-922e-11e9-831a-0ff9b6692669.PNG)

---
#### Internal data
- Associated internal bug: [b/135572756](http://b/135572756)

**Comment by bryanoltman** [comment]
Reopening due to internal issue b/145722771, where dialog messages are not properly displayed after iPad rotation while VoiceOver is on.

**Comment by material-mirror** [comment]
The internal issue [b/135572756](http://b/135572756) is now closed. This issue is being closed as a result.

**Comment by romoore** [comment]
We should verify that UIAlertController will "truncate" the accessibility frame before we attempt to do the same.
