### ISSUE TITLE
[MaskedTransition] Full screen Masked transition broken in iOS 13

### ISSUE THREAD

**Issue by aufflick** [material-components/material-components-ios#7666]
In iOS 13, full screen masked transition does not end with the content showing, nor can it be dismissed.

## Reproduction steps

1. Build and run catalog app with Xcode 12 (beta 1 or beta 2)
2. Navigate to Masked transition -> Start Demo
3. Tap on "Full screen"
4. Tap on a FAB

## Expected behavior

Full screen transition behaves as on iOS 12, the content is visible at the end of the transition, and the view reverts to the menu when tapped.

## Actual behavior

The content appears temporarily and then disappears, leaving the previous content zoomed out and with a UIDimmingView on top, which cannot be dismissed.

## Platform (please complete the following information)

 - Device: Simulator
 - OS: iOS 13 (Xcode 12 b2)

## Additional context

Video: https://www.dropbox.com/s/06rxbvxst7dhza8/FullScreenTransitionBug.mov?dl=0

---
#### Internal data
- Associated internal bug: [b/135917089](http://b/135917089)

**Comment by material-mirror** [comment]
The internal issue [b/135917089](http://b/135917089) is now closed. This issue is being closed as a result.
