### ISSUE TITLE
[FlexibleHeader] Bar width doesn't correctly track window under UIKit for Mac

### ISSUE THREAD

**Issue by aufflick** [material-components/material-components-ios#7667]
When you create and add an MDCFlexibleHeaderViewController to your view controller, it attempts to create the right initial frame by looking at `[UIScreen mainScreen].bounds` and then setting `autoresizingMask = UIViewAutoresizingFlexibleWidth`.

This is not always reliable under UIKit for Mac since the size returned by `[UIScreen mainScreen].bounds` may not be appropriate at the time the view hierarchy is created.

## Reproduction steps

1. Launch the catalog app
2. Remain on the home/catalog screen
3. Resize the window

## Expected behavior

The title should begin centred and remain centred as the window resizes.

## Actual behavior

The title is never centred.
## Platform (please complete the following information)

 - Device: Mac
 - OS: Mac OS 10.15 Beta (19A487l), Xcode 12 b2

## Additional context

Video of incorrect behaviour: https://www.dropbox.com/s/iao5q3qz57xq0le/FlexibleBarBad.mov?dl=0

---
#### Internal data
- Associated internal bug: [b/135917201](http://b/135917201)

**Comment by marcobambini** [comment]
@aufflick how did you managed to have MDC compiled under UIKit for MacOS on 10.15?
I've got a lot of signing issues even if all the required certificates are correct installed...
