### ISSUE TITLE
[Tabs] Add `image`, `selectedImage`, `selected` APIs to MDCTabBarViewItemView

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#7706]
In order to support KVO changes to UITabBarItem's `selectedImage` API correctly, the item view of the tab bar will need to manage its imageview's image internally.

When setting `UITabBarItem.image`, the `selectedImage` property is also set (though can be overridden). As a result, when trying to observe changes to `image` it's not possible to determine whether the selected image view's image should be updated.
  *  You cannot check for a `nil` value on `UITabBarItem.selectedImage` because `selectedImage` returns a copy of `image`.
  *  You cannot compare if `UITabBarItem.image == UITabBarItem.selectedImage`  because the copy in `selectedImage` is not the same object as `image`.

---
#### Internal data
- Associated internal bug: [b/136004466](http://b/136004466)

**Comment by material-mirror** [comment]
The internal issue [b/136004466](http://b/136004466) is now closed. This issue is being closed as a result.
