### ISSUE TITLE
[BottomAppBar] Add customization of elevation

### ISSUE THREAD

**Issue by codeman7** [material-components/material-components-ios#7719]
As a user I'd like to customize my elevation of my BottomAppBar, for certain instances of my application I want it to be flat and other instances I want to be really _raised (elevated)_.

## Acceptance criteria
1. MDCBottomAppBar uses MDCShadowLayer to represent its shadow
2. MDCBottomAppBar has an elevation property that I can set to raise or lower the elevation.

---
#### Internal data
- Associated internal bug: [b/136097560](http://b/136097560)

**Comment by material-mirror** [comment]
The internal issue [b/136097560](http://b/136097560) is now closed. This issue is being closed as a result.
