### ISSUE TITLE
[Tabs] Push animation "zooms in" items when pushed

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#7759]
When pushing the `MDCTabBarView`, the constraints of the Stack View seem to animate incorrectly.

![tabbar-push-animation-bug](https://user-images.githubusercontent.com/1753199/60436948-34f31600-9bdb-11e9-9e77-0c88554dc810.gif)

---
#### Internal data
- Associated internal bug: [b/136576286](http://b/136576286)

**Comment by andrewoverton** [comment]
@romoore, Is this bug obsolete after your decision to move away from Auto Layout?

**Comment by romoore** [comment]
Ah yes, this is no longer reproducible with the latest layout code.
