### ISSUE TITLE
[MDCTextInputControllerOutlined] default border color

### ISSUE THREAD

**Issue by zishanj** [material-components/material-components-ios#7792]
Any idea what is the default border color for `MDCTextInputControllerOutlined` and where it is defined?
![image](https://user-images.githubusercontent.com/1451292/60749436-73aa1700-9fb3-11e9-8fe4-02f4dc65504b.png)
I want to use this similar color for custom `UITextField`.

**Comment by romoore** [comment]
The [outlined controller's border color is controlled with `normalColor`](https://github.com/material-components/material-components-ios/blob/2803125/components/TextFields/src/MDCTextInputController.h#L174). Hope that helps you!

**Comment by zishanj** [comment]
Thanks @romoore  for your reply. Can you please tell me how to change the default black text color in above image when the field is not in focus?

**Comment by romoore** [comment]
You can configure the placeholder color for Outlined text fields using 3 properties. Each property controls the placeholder text color in a different state:

|State|Property|Example|
|---|---|---|
|`textField.text == nil`<br />`textField.isFirstResponder == NO` |`inlinePlaceholderColor`|`controller.inlinePlaceholderColor = UIColor.purpleColor;<br />![placeholder-inline](https://user-images.githubusercontent.com/1753199/60819041-ced33980-a16c-11e9-944e-2cb862781bbc.png)|
|`textField.text != nil`<br />`textField.isFirstResponder == NO`|`floatingPlaceholderNormalColor`|`controller.floatingPlaceholderNormalColor = UIColor.redColor;`<br />![placeholder-floating-normal](https://user-images.githubusercontent.com/1753199/60819104-f7f3ca00-a16c-11e9-9d7c-7d0f40a6cf67.png)|
|`textField.isFirstResponder = YES`|`floatingPlaceholderActiveColor|`controller.floatingPlaceholderActiveColor = UIColor.brownColor;`<br />![placeholder-floating-active](https://user-images.githubusercontent.com/1753199/60819205-2e314980-a16d-11e9-8245-490082793c30.png)|
