### ISSUE TITLE
[TextFields] Open source internal TextFields with validation state display

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#788]
### Overview of the issue

The material design spec illustrates textfields that Google has built but has not yet made public. Make these textfields public code.
### Motivation and context

This is an oft-requested component that is also oft-recreated. This will standardize implementations, ensure adherence to the material guidelines and bring in valuable new cases and feedback (in the long run.)
### Related issues

Internal issue b/32328902

**Comment by ajsecord** [comment]
Ongoing PR here: https://github.com/material-components/material-components-ios/pull/1318

**Comment by IsmailHassanein** [comment]
Aren't we there yet? 
@willlarche Is there a way to use the [TextFields] from your repo to the PR is merged?
Thanks,

**Comment by willlarche** [comment]
Hi, @IsmailHassanein . We're almost there. We had to stop work on TextFields to work the big [I/O](https://events.google.com/io/0) conference this year.

You can definitely use my pull request if you'd like to.

In your Podfile, add this line:
`pod 'MaterialComponents/TextFields', :git => 'https://github.com/willlarche/material-components-ios.git', :branch => 'feature-text-fields-singleline'`

In your ObjC file add:
`@import MaterialComponents.MaterialTextFields;`

Or in your Swift file add:
`import MaterialComponents`

Then you can use them just like in the examples! 

Let me know if there's any access issue. The fork is public but let me know.
