### ISSUE TITLE
[Typography] naming convention does not follow Material guideline

### ISSUE THREAD

**Issue by zishanj** [material-components/material-components-ios#7921]
I develop app for Android also and the typography naming convention on it conforms to the [type scale guideline](https://material.io/design/typography/the-type-system.html#type-scale). On iOS there is a confusion, for instance `body1` appears to be smaller than `body2` whereas on Android and in guideline its mentioned `body1` to be bigger than `body2`. 

Please revise these type scale naming convention on iOS again to avoid any confusion.

---
#### Internal data
- Associated internal bug: [b/138620140](http://b/138620140)

**Comment by romoore** [comment]
Please use [`MDCTypographyScheme`](https://github.com/material-components/material-components-ios/blob/8a139a8/components/schemes/Typography/src/MDCTypographyScheme.m#L45) which has the latest values available for the Material Typographic scales as well as newer support for Dynamic Type scaling.

**Comment by romoore** [comment]
Assigned to @zishanj to clarify which "Typography" component is being referenced.

**Comment by zishanj** [comment]
I am using `MDCTypography` like this:
```
label.font = MDCTypography.body1Font()
label.alpha = MDCTypography.body1FontOpacity()
```
In this way `body1` appears to be smaller than `body2` as opposed to what is mentioned in [material guideline](https://material.io/design/typography/the-type-system.html#type-scale)

**Comment by romoore** [comment]
Thanks for clarifying, @zishanj .  Please use MDCTypographyScheme for retrieving the latest Material Typography font values.  Here would be the recommended way to get the latest fonts:

```swift
let typographyScheme = MDCTypographyScheme(defaults: .material201902) // Use .material201804 for non-Dynamic Type fonts
label.font = typographyScheme.body1()
```

The Typography Scheme no longer provides opacities for each text style. Instead, the components use Theming Extensions (Button example below) to adjust fonts, colors, opacities, and shapes as needed.  You can certainly use opacities on your font if your own designs call for it.

```swift
import MaterialComponents.MaterialButtons_Theming
...

let myButton = MDCButton()
// Ideally this would be done once in the App's start-up
let containerScheme: MDCContainerScheming = {
  let colorScheme = MDCSemanticColorScheme(defaults: .material201907) // Supports dynamic colors
  let typographyScheme = MDCTypographyScheme(defaults: .material201902) // Use .material201804 for non-Dynamic Type fonts
  let containerScheme = MDCContainerScheme()
  containerScheme.colorScheme = colorScheme
  containerScheme.typographyScheme = typographyScheme
  return containerScheme
}()
myButton.applyOutlinedTheme(withScheme: containerScheme) // Creates an Outlined button
```

**Comment by zishanj** [comment]
Is there any usage difference between dynamic and non-dynamic type fonts?

**Comment by romoore** [comment]
The only differences to use Material Typography fonts with Dynamic Type support would be to call `mdc_scaledFont(for: UITraitEnvironment)` to pre-scale the font. You would need to call this method every time the `UIContentSizeCategory` changes in the environment. Alternatively, you can set `mdc_adjustsFontForContentSizeCategory` on an MDC-iOS component after setting its font property with a scalable font.

The easiest way to get a scalable Material Typography font is to load the `MDCTypographyScheme` with defaults `MDCTypographySchemeDefaultsMaterial201902`.  More details can be found in [the Dynamic Type support documentation for the Typography component](https://github.com/material-components/material-components-ios/blob/8735ebb8e8c57521a7b26b9bcfb7f370b6421a9d/components/Typography/docs/dynamic-type.md).

```swift
let typographyScheme = MDCTypographyScheme(defaults: .material201902)
let mdcButton = MDCButton()
self.view.addSubview(mdcButton)
mdcButton.setTitle("Accept", for: .normal)
// Use the current UIContentSizeCategory from self (UIViewController) to scale the font when
// it's assigned.  Note that this only works once the UIViewController is part of a view
// hierarchy.
mdcButton.setTitleFont(typographyScheme.button.mdc_scaledFont(for: self), for: .normal)
// Enable the MDCButton to automatically rescale its title font whenever the UIContentSizeCategory changes
mdcButton.mdc_adjustsFontForContentSizeCategory = true
```

**Comment by romoore** [comment]
Closing this for now. Please reopen it if you still have more questions. :)
