### ISSUE TITLE
[TextFields] MDCTextInputController error messages cover entered text

### ISSUE THREAD

**Issue by seljabali** [material-components/material-components-ios#7982]
## Reproduction steps

Using material-components/material-components-ios v85.8.0

```swift
import MaterialComponents

....

var usernameTextField = MDCTextField()
var userNameTextLayout = MDCTextInputControllerUnderline()
usernameTextField = {
    let usernameTextEdit = MDCTextField()
    usernameTextEdit.translatesAutoresizingMaskIntoConstraints = false
    usernameTextEdit.clearButtonMode = .unlessEditing
    usernameTextEdit.backgroundColor = .white
    return usernameTextEdit
}()
userNameTextLayout.textInput = usernameTextField
userNameTextLayout.placeholderText = "Username"
// add to view
....

private func isUserNameValid() -> Bool {
    let enteredUsername = usernameTextField.text ?? ""
	if (!enteredUsername.isValidEmail) {
	    userNameTextLayout.setErrorText("Invalid e-mail address",
	                                    errorAccessibilityValue: nil)
	    return false
	}
}
```

  [1]: https://i.stack.imgur.com/3Vh73.png
  [2]: https://i.stack.imgur.com/yWWfN.png
## Expected behavior

Following Android material design, placing the error underneath the line:
[![Android][2]][2]

## Actual behavior

Error messages covering the text entered:
[![iOS][1]][1]

## Platform

 - Device: iPhone Xr
 - OS: 12.2

## Additional context

I followed official tutorial: https://codelabs.developers.google.com/codelabs/mdc-101-swift/#2

---
#### Internal data
- Associated internal bug: [b/138619370](http://b/138619370)

**Comment by romoore** [comment]
This looks like a bug, though the `underline` controllers are not fully supported.  As a work-around for now, have you tried using `- [MDCTextInputControllerUnderline initWithTextInput:]`?

**Comment by romoore** [comment]
I would also like to ask whether you're retaining the controller in a property. From the code snippet you provided, it looks like `userNameTextLayout` is only an automatic (local) variable and not retained when the method returns.   If it's not retained by your code, the controller will deallocate and you won't get most of the behavior of the text field.

**Comment by s6joui** [comment]
Hello, I have the same problem. Using `initWithTextInput` doesn't solve it. And it also happens with `MDCTextInputControllerOutlined` 
![visual bug](https://i.imgur.com/MkO9Gii.png)

```
controller = MDCTextInputControllerOutlined(textInput: input)
MDCTextFieldColorThemer.applySemanticColorScheme(colorScheme, to: controller!)
controller?.setErrorText("Error!", errorAccessibilityValue: "Error")
```

**Comment by s6joui** [comment]
Okay! so I was setting the height of the view with a constraint. I made the height bigger and now it works fine

**Comment by romoore** [comment]
Glad to hear you figured it out. You shouldn't need to set a height constraint - I believe the MDCTextField has an intrinsic content size for its height.

**Comment by romoore** [comment]
Reassigning to @seljabali to provide a little more detail about the controller retention. If you could provide the full text field/controller controller set-up code in a snippet, that would help us to reproduce the issue.

**Comment by seljabali** [comment]
> Okay! so I was setting the height of the view with a constraint. I made the height bigger and now it works fine

That too was the case for me! Thanks @s6joui & @romoore for looking into to this with me.

**Comment by romoore** [comment]
Great! Glad we could get this resolved. Sorry it took 9 days. >_<
