### ISSUE TITLE
Add more examples for Flexible Header

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#80]
Demo ideas:
- [ ] FAB attached to the header.
- [ ] Various UIKit views added to the header (UINavigationBar, UIToolbar, UILabel, UIButton, UIImage, etc...)
- [x] "Configurator" demo allowing for quick adjustments to min/max height, status bar behavior, etc...
- [ ] "Wrapped" view controller.
- [ ] UIPageController and any other system UIViewControllers that an app might want to give custom headers to.

**Comment by ianegordon** [comment]
Closing as obsolete.  😞 
Please open a new bug if this is still an issue.  😄
