### ISSUE TITLE
Video assets are not loading for all users

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#809]
On page [](https://material-ext.appspot.com/mdc-ios-preview/howto/tutorial/) in section 3 there are 2 video tags that seem to be correctly parsed but the get for the .m4v files themselves errors out for almost all users. Doesn't error out for @larche on Chrome. Does error out for @larche on Safari.

[](https://material-ext.appspot.com/mdc-ios-preview/howto/tutorial/docs/assets/Xcode-Storyboard-Replace-Controller.m4v) and [](https://material-ext.appspot.com/mdc-ios-preview/howto/tutorial/docs/assets/Xcode-Storyboard-Define-Cell.m4v)

**Comment by ajsecord** [comment]
Obsolete.
