### ISSUE TITLE
[Buttons] VoiceOver Does Not Recognize Disabled MDCButton

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#8122]
This was filed as an internal issue. If you are a Googler, please visit [b/137200027](http://b/137200027) for more details.

---
#### Internal data
- Associated internal bug: [b/137200027](http://b/137200027)

**Comment by jverkoey** [comment]
Duplicate of https://github.com/material-components/material-components-ios/issues/8123
