### ISSUE TITLE
Point xctestrunner dependency back to google/xctestrunner.

### ISSUE THREAD

**Issue by wenyuzhang666** [material-components/material-components-ios#8182]
The original source repository (google/xctestrunner) hasn't release their version compatible with Xcode 11 logic test. We need to point our dependency to a Material foundation before they release a compatible version.

Point our xctestrunner dependency back to google/xctestrunner once they make a new release.

---
#### Internal data
- Associated internal bug: [b/138928176](http://b/138928176)

**Comment by randallli** [comment]
We have pointed at our own fork in Material foundation.
We believe it has been exported to google/xctestrunner.
Remaining work is to point us at that newer release.

**Comment by randallli** [comment]
@wenyuzhang666 is saying this should be a config change
