### ISSUE TITLE
Snapshot test fails on iOS 13 under XCode 11.

### ISSUE THREAD

**Issue by wenyuzhang666** [material-components/material-components-ios#8219]
On iOS 13, `drawViewHierarchyInRect:afterScreenUpdates:` can't draw view correctly under snapshot tests on Bazel on our project and vanilla project created under XCode11.

When running snapshot test, the error shows "failed: caught "NSInternalInconsistencyException", "View <UIView: 0x7fdcbd6155d0; frame = (0 0; 44 52); layer = <CALayer: 0x600000022a60>    > must draw correctly"

Apparently, this API is not able to be used on a vanilla project created by XCode 11. It seems to be a XCode beta issue.

---
#### Internal data
- Associated internal bug: [b/138929121](http://b/138929121)

**Comment by wenyuzhang666** [comment]
Tested on XCode 11 beta 6, this API still doesn't work.

**Comment by yarneo** [comment]
Hi Wenyu, we had a discussion on this by the team. There seems to be a misunderstanding if the snapshot tests fail on iOS13 locally and everywhere, or just on bazel/blaze/cocoapods.

I told the team that locally we can still run snapshot tests on iOS13, correct me if i'm wrong though!

I'm assigning this ticket to you, feel free to unassign if you are too busy.

**Comment by wenyuzhang666** [comment]
@yarneo Yes. The team can still run snapshot tests on iOS13 (only) on our current project. It doesn't work for Bazel and vanilla (brand new) XCode project created by XCode 13, which I believe go through the same route. Sorry for the confusion if any wrong message was delivered.

**Comment by wenyuzhang666** [comment]
Tested with XCode 11.2.1 `//components/Banner:snapshot_tests` target. The test passes now. Closing this issue since XCode 11 is not causing this issue anymore. If there is any remaining issue, please file separate issues for it.
