### ISSUE TITLE
Unable to set backgroundColor as white on UITableView.

### ISSUE THREAD

**Issue by wenyuzhang666** [material-components/material-components-ios#8238]
Reproduction:
Xcode 11 beta 5, iPhone 8, iOS 13 simulator.

Setting `UIColor.white` as backgroundColor on a tableView causes `<UIDynamicSystemColor: 0x7fab88c49d50; name = tableBackgroundColor>` to be set in the end. It seems to be an XCode 11 beta issue.

It is causing `testDefaultBackgroundColor`on ActionSheet test to fail

---
#### Internal data
- Associated internal bug: [b/139096555](http://b/139096555)

---
#### Internal data
- Associated internal bug: [b/139096555](http://b/139096555)

**Comment by romoore** [comment]
@wenyuzhang666  Could you please document which Xcode beta is producing this error?

**Comment by wenyuzhang666** [comment]
@romoore Sorry, the number dropped off somehow. I put it back. Thanks for catching it.

**Comment by jverkoey** [comment]
What is the error you're seeing?

**Comment by wenyuzhang666** [comment]
There was no error. It was an assertion failure to indicate that `UIColor.white` is not equal to `<UIDynamicSystemColor: 0x7fab88c49d50; name = tableBackgroundColor>`

**Comment by material-mirror** [comment]
The internal issue [b/139096555](http://b/139096555) is now closed. This issue is being closed as a result.
