### ISSUE TITLE
Swift tests are failing on iOS 13 Bazel tests.

### ISSUE THREAD

**Issue by wenyuzhang666** [material-components/material-components-ios#8249]
Running some swift tests on an iOS 13 runner by Bazel causes errors. (Stacktrace not available because they are `segmentation fault`).

This issue is opened for tracking those issues found and the solution used to fix them (permanently swapped with ObjC test or temporarily disabling and re-enabling/audit after XCode 11 is stable or updating Bazel compatible with XCode 11)

### Tests that have been rewritten in Obj-C. (No future actions)
ActivityIndicator: https://github.com/material-components/material-components-ios/pull/8248.
LibraryInfo:https://github.com/material-components/material-components-ios/commit/861f6361653beb4cd56fcca4235e2676d5964bdf.
AppBar: https://github.com/material-components/material-components-ios/commit/3565b6506ea67b0ccec35c2671ac23f6c4eb1924.
Palette: https://github.com/material-components/material-components-ios/commit/707b49dd0ea34badde67ae3c3df1b1f7b4e279d5.

### Tests that have been temporarily disable on Autobot. (Need to be re-enabled)
ButtonBar: https://github.com/material-components/material-components-ios/pull/8267
Flexible Header: https://github.com/material-components/material-components-ios/pull/8269
NavigationBar: https://github.com/material-components/material-components-ios/pull/8272
Actionsheet: https://github.com/material-components/material-components-ios/pull/8274
Textfields: https://github.com/material-components/material-components-ios/pull/8275.

---
#### Internal data
- Associated internal bug: [b/139179932](http://b/139179932)

**Comment by randallli** [comment]
update: we need to confirm with latest beta.

These tests are manually turned off for iOS13 only.

**Comment by acecilia** [comment]
Hi 👋 This issue was closed in August. Could you talk a bit about the resolution? 
* Was this a Bazel bug?
* Was this an xcode bug?
* Was it something else?

I am currently experiencing this issue sometimes (flaky test), and this ticket is the only one I found mentioning that bazel/xcode could be the root cause.

Thanks!

**Comment by jverkoey** [comment]
This issue was close because of a combination of this repo entering maintenance mode and the issue being fairly old.
