### ISSUE TITLE
[Catalog] AppDelegate's performPostLaunchSelector appears to be unused

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#8281]
It was added in https://github.com/material-components/material-components-ios/pull/6445 but it appears we never made use of it.

## Acceptance criteria

- AppDelegate's performPostLaunchSelector is deleted.

---
#### Internal data
- Associated internal bug: [b/139209914](http://b/139209914)

**Comment by romoore** [comment]
This is used internally. Please do not remove it.

**Comment by romoore** [comment]
Created b/139207929 to track the correct internal change for this selector.
