### ISSUE TITLE
[AppBar] Custom button does not support tap

### ISSUE THREAD

**Issue by zishanj** [material-components/material-components-ios#8284]
I have added `MDCButton` in `MDCAppBarViewController().headerStackView.bottomBar` but this button does not support tap. I have also seen in debug view that `isUserInteractionEnabled = true` for this view. Is this a bug or I am missing something? 

---
#### Internal data
- Associated internal bug: [b/139271883](http://b/139271883)

**Comment by romoore** [comment]
Thanks, @zishanj.  Could you please post a snippet with the code you used to add the button (and its action) to the AppBar?

**Comment by zishanj** [comment]
Here is the sample code... I am using `buttonTakeCourse` which is a `MDCButton`
```
let bottomView = UIView()
        bottomView.addSubview(labelLessons)
        bottomView.addSubview(buttonTakeCourse)
        bottomView.addSubview(progressCourse)
        bottomView.addSubview(labelProgress)
        
        appBarViewController.headerStackView.bottomBar = bottomView
```

In the above sample code I am using `buttonTakeCourse` which is a `MDCButton` created in this way:

```
lazy var buttonTakeCourse: MDCButton = {
        let button = MDCButton()
        button.setTitleColor(.white, for: .normal)
        button.backgroundColor = Config.Colors.accent
        button.setTitle("Take Course", for: .normal)
        button.translatesAutoresizingMaskIntoConstraints = false
        button.sizeToFit()
        button.isHidden = true
        
        return button
    }()
```

Here is its layout:
![image](https://user-images.githubusercontent.com/1451292/63525977-07aa5080-c518-11e9-93b7-17bc1966f1a0.png)

**Comment by romoore** [comment]
Thanks for the details, @zishanj. I'm not able to reproduce your issue with my testing code. Perhaps there's something with the constraints or custom view that's interacting with the button actions? I was able to take the `MDCAppBarImagaeryExample` and throw in a custom `UIView` with an `MDCButton`. Although the layout is pretty poor, I'm able to get the events I expect from the button.  Could you try reproducing the issue in more stand-alone code?  Ideally one that I could copy-paste into a VC to try out?

```objc
  MDCButton *button = [[MDCButton alloc] init];
  [button setTitle:@"Button" forState:UIControlStateNormal];
  [button applyContainedThemeWithScheme:[[MDCContainerScheme alloc] init]];
  [button addTarget:self action:@selector(tapped) forControlEvents:UIControlEventTouchUpInside];
  [button sizeToFit];
  UIView *buttonView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 50, 50)];
  button.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleTopMargin | UIViewAutoresizingFlexibleLeftMargin | UIViewAutoresizingFlexibleBottomMargin;
  [buttonView addSubview:button];
  button.center = CGPointMake(CGRectGetMidX(buttonView.bounds), CGRectGetMidY(buttonView.bounds));
  buttonView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
  self.appBarViewController.headerStackView.bottomBar = buttonView;
```

I'm definitely able to get Taps on the button, here's a screenshot showing the button being pressed.
![Simulator Screen Shot - iPhone 7 - 2019-08-22 at 11 42 25](https://user-images.githubusercontent.com/1753199/63529021-fdfdfa00-c4d1-11e9-88a1-381e64ba5932.png)

**Comment by zishanj** [comment]
Thanks for the helpful reply. I forgot to apply the `.autoresizingMask` on my `bottomView` which was making its width and height to zero. It works now!

**Comment by romoore** [comment]
Awesome, glad I could help!
