### ISSUE TITLE
While I was trying to implement it in my project  dyld: Symbol not found: _OBJC_CLASS_$_MDCOutlinedTextFieldColorThemer.................Application is crashing at the time of loading

### ISSUE THREAD

**Issue by KiranYechuri** [material-components/material-components-ios#8375]

**Comment by romoore** [comment]
Gentle ping @KiranYechuri .

**Comment by romoore** [comment]
Closing this for now. Please reopen it if you can provide more details for us to debug the issue. Thanks for reaching out.

**Comment by MarkDylan100** [comment]
@romoore I also have almost the same issue, the difference is I'm implementing the snackbar on ios, the error I'm getting was `dyld: Symbol not found: _OBJC_CLASS_$_MDCSnackbarManager`, I'm using CocoaPods and working in `.xcworkspace`, with Swift 4.2 and xcode 10.
