### ISSUE TITLE
[BottomSheet] ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs

### ISSUE THREAD

**Issue by ferufab** [material-components/material-components-ios#8381]
When I archive the binary file for App Store today, the following issues occurs :

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

We aren't using any UIWebview in our project, but we display BottomSheet and MDCBottomSheetPresentationController has references to UIWebview, I think this could be the cause of that warning.

Environment: MaterialComponents (88.1.0)

---
#### Internal data
- Associated internal bug: [b/140408773](http://b/140408773)

**Comment by federicopolesello** [comment]
+1

**Comment by federicopolesello** [comment]
I have the same issue. Is there any news?

**Comment by romoore** [comment]
Thanks @ferufab  and @federicopolesello . I'll bring this to the attention of my team's leadership.

**Comment by zishanj** [comment]
Any update on this issue? I am afraid if I submitted for app review and it get rejected from Apple.

**Comment by mzahidimran** [comment]
+1

**Comment by jverkoey** [comment]
We're looking in to this this week.

**Comment by zishanj** [comment]
when its new version will be released?

**Comment by jverkoey** [comment]
This coming week.

**Comment by ferufab** [comment]
Any news on when this version will be released to download it by cocoapods?

**Comment by jverkoey** [comment]
We are cutting the release now; track progress at https://github.com/material-components/material-components-ios/pull/8463

**Comment by jverkoey** [comment]
While we have y'all's attention here, we'd love it if you could share which Material Components for iOS you're making use of and any other issues you'd like to see prioritized.

Please leave comments at https://github.com/material-components/material-components-ios/issues/8464
