### ISSUE TITLE
While Registering the MDCChipCollectionViewCell getting error 

### ISSUE THREAD

**Issue by NatashaChhibber707** [material-components/material-components-ios#8385]
collectionView.register(MDCChipCollectionViewCell.self, forCellWithReuseIdentifier: "identifier")

Getting error -->
could not dequeue a view of kind: UICollectionElementKindCell with identifier identifier - must register a nib or a class for the identifier or connect a prototype cell in a storyboard

https://material.io/develop/ios/components/chips/

Using above given link to implement Action Chips . Please guide

**Comment by romoore** [comment]
Could you please include the code snippet that is dequeuing the cell?

**Comment by NatashaChhibber707** [comment]
guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "identifier", for: indexPath) as? MDCChipCollectionViewCell else {
            return UICollectionViewCell()
        }
        cell.chipView.mdc_adjustsFontForContentSizeCategory = true
        cell.alwaysAnimateResize = true
        let data = model()
        cell.chipView.titleLabel.text = data?[indexPath.row]
        return cell

**Comment by NatashaChhibber707** [comment]
Code snippet added used in dequeuing the cell .

**Comment by romoore** [comment]
Can you verify that the cell is correctly registered in `viewDidLoad` or at least after the collection view is loaded?  [The Chips example](https://github.com/material-components/material-components-ios/blob/develop/components/Chips/examples/ChipsTypicalUseViewController.m#L43) has a good usage pattern to copy for this case.
