### ISSUE TITLE
Is there any Example of CollectionView Cell (MDCChipCollectionViewCell) with MDCChipField ?

### ISSUE THREAD

**Issue by NatashaChhibber707** [material-components/material-components-ios#8389]
So it is easy to create the Functionality of added more tags with MDCChipField to previous tag added in CollectionView in Swift .

**Comment by romoore** [comment]
@NatashaChhibber707 Can you please clarify the behavior you expect? Are you placing an `MDCChipField` within a `UICollectionView`?  If you are managing `MDCChipCollectionViewCell` directly, have you considered using a plain UITextField for text input? Alternatively, have you tried using the `- addChip:` API in `MDCChipField`?

In general, `MDCChipField` doesn't work very well for some things including Dynamic Type and Material Theming. I would recommend not using it if you can, although I cannot recommend a good replacement for it at the moment.

**Comment by NatashaChhibber707** [comment]
Hi Moore ,

Actually I am using MDCChipField to Add chips and also to show some
previous data in chips . In this case I have to manage with the Scrolling
part But if same input chips works with MDCChipCollectionViewCell then no
managing of scrolling take place . As I shared the screenshot what I want
below . Thanks

[image: Screenshot 2019-09-04 at 12.22.49 AM.png]

**Comment by romoore** [comment]
Hi @NatashaChhibber707. Your image wasn't uploaded - it may be a limitation of the email interface for GitHub. When you have a chance, could you edit your comment in the web interface and upload the image?

**Comment by NatashaChhibber707** [comment]
![Screenshot 2019-09-04 at 12 22 49 AM](https://user-images.githubusercontent.com/49919804/64202664-51e3e800-ceaf-11e9-9d49-b52e0cef4fb0.png)
Please have a look .

**Comment by romoore** [comment]
Thanks! It looks like it might be best for you to use either a UISearchController with custom behavior to add a Chip, or else a Text Field for the same.  I don't think mixing Chips and ChipTextField can easily give you the design you want.

**Comment by romoore** [comment]
I'm going to close this question now. Please reopen it if you don't think I've answered it well enough. Thanks!
