### ISSUE TITLE
[TextFields] Floating Placeholder text changes size when you type in the 2nd word into the text field

### ISSUE THREAD

**Issue by ggdiez** [material-components/material-components-ios#8390]
I just copied the text of closed issue #4189 because this bug continue on latest version and I'm going to launch a PR to try fix this.

Description:

In a controller make a MDCTextfield a wrap a MDCTextInputControllerFilled controller on it

let textField:BITextField = BITextField()
MDCTextInputControllerFilled(textInput: textField)

In the text field type 1 letter in, the floating placeholder text will get smaller and go on top
When you type in a 2nd letter in, the floating placeholder text will get smaller again.

Expected behavior: The floating placeholder text should remain the same size and not change

---
#### Internal data
- Associated internal bug: [b/140496989](http://b/140496989)

**Comment by ggdiez** [comment]
This is the PR 
https://github.com/material-components/material-components-ios/pull/8391

**Comment by romoore** [comment]
Does the same problem occur with `MDCTextField`?

**Comment by ggdiez** [comment]
Yes, the problem happen with MDCTextField and MDCTextInputControllerLegacyDefault or MDCTextInputControllerUnderline
Typing text in the text field the floating placeholder change the size.

**Comment by romoore** [comment]
Thanks. So to clarify, it happens with:

* `MDCTextInputControllerFilled`
* `MDCTextInputControllerLegacyDefault`
* `MDCTextInputControllerUnderline`

Is that correct?
