### ISSUE TITLE
Internal issue: b/140798790 (investigate swift package manager)

### ISSUE THREAD

**Issue by material-mirror** [material-components/material-components-ios#8433]
This was filed as an internal issue. If you are a Googler, please visit [b/140798790](http://b/140798790) for more details.

---
#### Internal data
- Associated internal bug: [b/140798790](http://b/140798790)

**Comment by Bernix01** [comment]
Recently started a project and tried to use SPM and this library, MaterialTextFields to be specific. So I played around with the files and the `Package.swift` and got it working! (Just Textfields at this time, which is what I need). Maybe it's not the best way to achieve it but for sure might help you in your investigation and maybe hint a way of achieving this.

[The repo](https://github.com/grupopulpo/material-components-ios)
