### ISSUE TITLE
[BottomSheet] Make MDCBottomSheetController not dismissable

### ISSUE THREAD

**Issue by jongarate** [material-components/material-components-ios#8457]
## Feature Request/Suggestion

Currently only `dismissOnBackgroundTap` can be toggled on `MDCBottomSheetController`, which disables the dismissal of the view upon clicking in the top part of the underlying view. However, it's still possible for a user to dismiss the bottom sheet by swipping it down. It would be nice to have the possibility to make the entire view not cancelable.

---
#### Internal data
- Associated internal bug: [b/141135419](http://b/141135419)

**Comment by yarneo** [comment]
I have started working on this feature request!

**Comment by ezefire** [comment]
I think the solution is not correct because when using 'dismissOnDraggingDownSheet' = false any drag event is handled making that we cannot expand the view.
