### ISSUE TITLE
Remove all usage of typeof() and change .xcconfig to disallow GCC extensions

### ISSUE THREAD

**Issue by ajsecord** [material-components/material-components-ios#846]
typeof() is a GCC extension that we don't want to support in the code base.

Internal build settings disallow it by specifying that the compiler should use C99, not C99+GCC extensions, but it seems that MDCCatalog does not do so.

**Comment by romoore** [comment]
Looks like there are no remaining references to `typeof()` in the catalog and no blockers to switching to `-std=c99` in the project file.

**Comment by ajsecord** [comment]
There's still a [few references](https://github.com/material-components/material-components-ios/search?utf8=%E2%9C%93&q=typeof&type=) kicking around...

**Comment by willlarche** [comment]
I thought __typeof was valid.

**Comment by romoore** [comment]
I also thought this issue was to remove `typeof()` (and replace it with) `__typeof__()`?

**Comment by ajsecord** [comment]
There are two closely-related issues, the first is worse than the second.

`typeof()` is a GNU C extension, which isn't something we want to rely on at all. The only reason clang supports it is for backwards compatibility.

`__foo__()` is a standard way of saying "this is completely compiler-dependent, feel free to blow up if you don't happen to understand it." `__typeof__()` a little more honest than `typeof()` (which looks like a real language feature), but has the same problem as `typeof()`.

These features were added for situations [where you don't know the type](https://gcc.gnu.org/onlinedocs/gcc/Typeof.html) (like when writing a macro where you have to declare a temp variable of the _same type_ as an argument. Of course they can be convenient, but it's better to be explicit than save a few characters (especially in shared library code).

**Comment by willlarche** [comment]
OK! So we'll say the best practice is just being explicit about the class?

**Comment by ajsecord** [comment]
Also, extensions are [called out in the style guide](https://engdoc.corp.google.com/eng/doc/objcguide.xml?showone=Nonstandard_Extensions&cl=head#Nonstandard_Extensions).

Yes, please be explicit about the class.
