### ISSUE TITLE
[Thread] Share your usage of Material Components for iOS

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#8464]
This is not a bug, feature request, or other traditional type of issue.

The purpose of this issue is to allow users of Material Components for iOS to share which components they're using and in which products, so that the Material iOS team can make more informed decisions around prioritizing work related to our components.

Please consider using the following template to share your use of Material Components for iOS:

```
Link to the app: <link>
Which version number of MDC iOS you're currently depending on: <version>
Which components your app uses:
- <component>
- <component>
- ...
Which issues you'd like to see resolved:
- <link to issue>
- <link to issue>
- ...
```

---
#### Internal data
- Associated internal bug: [b/142340276](http://b/142340276)

**Comment by zishanj** [comment]
Link to the app: https://apple.co/2m4aROk
Which components your app uses:
- AppBar
- BottomNavigation
- Buttons
- Cards
- Chips
- FlexibleHeader
- NavigationDrawer
- Ripple

**Comment by rustyshelf** [comment]
Link to the app: Not yet shipped in any store versions
Which components your app uses:
- BottomSheet
Which issues you'd like to see resolved:
- https://github.com/material-components/material-components-ios/issues/8457

At least that's the closest issue I can find. I want a way to programatically turn on and off the pull down gesture. 

Basically the equivalent of this in `MDCSheetContainerView`
```
- (BOOL)draggableView:(__unused MDCDraggableView *)view
    shouldBeginDraggingWithVelocity:(CGPoint)velocity {
    // ....
    if (_allowDragToClose == NO) return NO;
   // ...
```

Where `allowDragToClose` (or a better named variable) can be accessed from my presented view controller somehow.

**Comment by jverkoey** [comment]
Thanks @rustyshelf! I've escalated #8457 internally so that we'll take a look at it in our next sprint.

**Comment by yarneo** [comment]
Hey @rustyshelf, the feature request has been added in https://github.com/material-components/material-components-ios/pull/9004

**Comment by rustyshelf** [comment]
That's excellent, thanks! Any idea of roughly when we could expect that to make it into a release version?

**Comment by yarneo** [comment]
This should happen in our weekly release; which should be released by the end of the week!

**Comment by razor313** [comment]
Link to the app: https://anardoni.com/ios/app/Bw5riXoQ?lng=fa
Which version number of MDC iOS you're currently depending on: the latest (119.0.0)

Which components your app uses:
- TextFields
- Cards
- Tabs
- TextControls+OutlinedTextAreas
- TextControls+OutlinedTextFields
- PageControl

Which issues you'd like to see resolved:
- <https://github.com/material-components/material-components-ios/issues/10117>

**Comment by fanij** [comment]
Link to the app: [Capitalise.a‪i‬](https://apps.apple.com/us/app/capitalise-ai/id1497858562)
Which version number of MDC iOS you're currently depending on: latest (124.1.1)

Which components your app uses:
- ActivityIndicator
- TextControls+FilledTextFields
- BottomNavigation
- AppBar
- Ripple
- Tabs+TabBarView
- Chips
- Snackbar
- Buttons

Which issues you'd like to see resolved:
- [#10163](https://github.com/material-components/material-components-ios/issues/10163)

**Comment by jverkoey** [comment]
As of July 15 MDC entered maintenance mode. Learn more at https://github.com/material-components/material-components-ios#material-components-for-ios
