### ISSUE TITLE
UIWebView APIs

### ISSUE THREAD

**Issue by DevPrata** [material-components/material-components-ios#8482]
Hey, i have receive e-mail from my application use UIWebView, i look where i use, file MDCBottomSheetPresentationController.m in the line 35, Apple will stop accepting submissions of apps that use UIWebView APIs.

- [x] Measure internal usage of the API.
- [x] Create a GitHub issue.
- [ ] Write a migration guide.
- [ ] Add a comment to the API indicating that it will be deprecated.
- [ ] Determine a schedule for the API deletion.
- [ ] Announce that the API will be deprecated
- [ ] After the deprecation date, annotate the API as deprecated.
- [ ] After the deletion date, re-evaluate usage of the API.
- [x ] Delete the API and migration guide.

**Comment by romoore** [comment]
I believe this is a dupliate of https://github.com/material-components/material-components-ios/issues/8381. Can you try with the latest Material Components iOS release and verify that you're still receiving warnings?

**Comment by romoore** [comment]
If it is still a problem, please document the Material Components for iOS version you're using and reopen this issue. Thanks!

**Comment by DevPrata** [comment]
Hey thanks, i didn't see
