### ISSUE TITLE
[Component] UIWebView APIs Deprecated API Usage

### ISSUE THREAD

**Issue by DevPrata** [material-components/material-components-ios#8483]
Hey, i have receive e-mail from my application use UIWebView, i look where i use, file MDCBottomSheetPresentationController.m in the line 35, Apple will stop accepting submissions of apps that use UIWebView APIs.

- [x] Measure internal usage of the API.
- [x] Create a GitHub issue.
- [ ] Write a migration guide.
- [ ] Add a comment to the API indicating that it will be deprecated.
- [ ] Determine a schedule for the API deletion.
- [ ] Announce that the API will be deprecated
- [ ] After the deprecation date, annotate the API as deprecated.
- [ ] After the deletion date, re-evaluate usage of the API.
- [ ] Delete the API and migration guide.

---
#### Internal data
- Associated internal bug: [b/142078323](http://b/142078323)

**Comment by farfromrefug** [comment]
same issue here

**Comment by yarneo** [comment]
Thanks for notifying us. this seems to have been fixed here: https://github.com/material-components/material-components-ios/pull/8453
