### ISSUE TITLE
[FeatureHighlight] crashing when tried to present modally

### ISSUE THREAD

**Issue by adman44** [material-components/material-components-ios#8506]
MDCFeatureHighlightAnimationController crashing when tried to present modally in iOS 13

line 85: [transitionContext completeTransition:YES]; <<< crash

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present modally an active controller <***.DashViewController: 0x7fcf1a4b26d0>.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23afdbde __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff5015cb20 objc_exception_throw + 48
	2   UIKitCore                           0x00007fff468b616b -[UIViewController _presentViewController:withAnimationController:completion:] + 5214
	3   UIKitCore                           0x00007fff468b866b __63-[UIViewController _presentViewController:animated:completion:]_block_invoke + 98
	4   UIKitCore                           0x00007fff468d272d -[_UIViewControllerTransitionCoordinator _applyBlocks:releaseBlocks:] + 294
	5   UIKitCore                           0x00007fff468ce7fb -[_UIViewControllerTransitionContext _runAlongsideCompletions] + 126
	6   UIKitCore                           0x00007fff468ce560 -[_UIViewControllerTransitionContext completeTransition:] + 104
	7   MaterialComponents                  0x00000001063a20ca __60-[MDCFeatureHighlightAnimationController animateTransition:]_block_invoke.34 + 106
	8   UIKitCore                           0x00007fff473d0c54 -[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:] + 671
	9   UIKitCore                           0x00007fff473a1969 -[UIViewAnimationState sendDelegateAnimationDidStop:finished:] + 268
	10  UIKitCore                           0x00007fff473a1edb -[UIViewAnimationState animationDidStop:finished:] + 259
	11  UIKitCore                           0x00007fff473a2062 -[UIViewAnimationState animationDidStop:finished:] + 650
	12  QuartzCore                          0x00007fff2af8a3ee _ZN2CA5Layer23run_animation_callbacksEPv + 306
	13  libdispatch.dylib                   0x00000001075bed64 _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x00000001075cce1c _dispatch_main_queue_callback_4CF + 1500
	15  CoreFoundation                      0x00007fff23a60699 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	16  CoreFoundation                      0x00007fff23a5b2f9 __CFRunLoopRun + 2329
	17  CoreFoundation                      0x00007fff23a5a6b6 CFRunLoopRunSpecific + 438
	18  GraphicsServices                    0x00007fff38016bb0 GSEventRunModal + 65
	19  UIKitCore                           0x00007fff46f0990f UIApplicationMain + 1621
	20  ***                                0x0000000105750d3b main + 75
	21  libdyld.dylib                       0x00007fff50fe1cf5 start + 1
	22  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

---
#### Internal data
- Associated internal bug: [b/142079097](http://b/142079097)

**Comment by yarneo** [comment]
Hi @adman44 ,

I have looked into this bug and wasn't able to reproduce this when presenting modally in iOS 13.

However, I was able to reproduce it when trying to present the MDCFeatureHighlightViewController twice.

Something like so:
```
  MDCFeatureHighlightViewController *vc =
      [[MDCFeatureHighlightViewController alloc] initWithHighlightedView:_button completion:nil];
  [self presentViewController:vc animated:YES completion:nil];
  [self presentViewController:vc animated:YES completion:nil];
```

What I believe is happening is that somewhere in your code the feature highlight view controller is being presented modally more than once.

One way to mitigate it is to check if the view controller has already been presented using the `isBeingPresented` property.

Something like so:
```
  if (!vc.isBeingPresented) {
    [self presentViewController:vc animated:YES completion:nil];
  }
```

Closing this issue. Feel free to reopen it if you find some new information that you would like me to look into. Thanks!
