### ISSUE TITLE
[NavigationBar] Move all of the examples into the AppBar examples

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#851]
This issue has been updated to: move all NavigationBar examples to the AppBar component.

---

Original issue:

### Overview of the issue
This example was created to show RTL in addition to bar items but needs some instruction.

### Reproduction steps
When you look at the view controller, it has "leading" and "trailing" buttons in the nav bar but tapping them does nothing.

The title and description also only reference the fact that this example includes items. 

If you set the device to be in a RTL reversed language and then return, you can see the difference.

### Motivation and context
No one right now will think to change the device's localization setting in this view controller. They will, like I did, just click on those buttons expecting something to happen.
![simulator screen shot nov 10 2016 4 05 58 pm](https://cloud.githubusercontent.com/assets/1271525/20194413/383ef670-a760-11e6-9fe6-c96805dee279.png)

---
#### Internal data
- Associated internal bug: [b/117179236](http://b/117179236)

**Comment by jverkoey** [comment]
These examples need to be folded in to the App Bar examples.

**Comment by material-mirror** [comment]
The internal issue [b/117179236](http://b/117179236) is now closed. This issue is being closed as a result.
