### ISSUE TITLE
[Tutorial] Replace usage of FAB

### ISSUE THREAD

**Issue by liquidx** [material-components/material-components-ios#853]
The FAB is used incorrectly in the tutorial. It should not be a used as a modal toggle. 

I suggest changing it so that by pressing it, it adds an extra row or section to the collection view. 

By doing so, I would suggest removing the editing example in the tutorial, that's a little too indepth for the tutorial there.

**Comment by ianegordon** [comment]
Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄
