### ISSUE TITLE
[Tabs] MDCTabBarView selection indicator does not update when the frame of a custom view changes

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#8545]
Related to me by @mrhappyasthma 

---

Not sure if it's a bug or WAI, but the problem was that we were setting the selected tab item before the view was sized, so it was {0, 0, 0, 0}. This was causing the indicator to get set up based on that call to select the first item.
If i delay that call until the view will appear, it fixes the bug
but perhaps we should assert on that case or handle it more elegantly, as it was a bit tricky to debug
repro steps:

- Create a tab bar with a custom view item with non-fixed dimensions.
- Set the selected item (e.g. to 0)
- Then size the view and add to the view hierarchy

Notice: the tab bar selector is set based on the size at the time of updating the selected item. and does not readjust once the view is sized

---
#### Internal data
- Associated internal bug: [b/142338730](http://b/142338730)

**Comment by mrhappyasthma** [comment]
Seems it could be related to https://github.com/material-components/material-components-ios/issues/8546. When setting up that example, notice the selected item is not underlined.

<img width="411" alt="Mjrgs6RqDtP" src="https://user-images.githubusercontent.com/1547356/66357841-50ca2e80-e925-11e9-8c38-59cec545cbc1.png">

**Comment by romoore** [comment]
Confirming as a duplicate of https://github.com/material-components/material-components-ios/issues/8546 and closing.
