### ISSUE TITLE
[Tabs] UI Issues with MDTabBarViewController

### ISSUE THREAD

**Issue by shubhankarbhavsar** [material-components/material-components-ios#8556]
> For usage questions: ask on [Stack  Overflow](https://stackoverflow.com/questions/tagged/material-components+ios).

## Reproduction steps

1. Go to 'Tab bar page'
2. Tap on '.'

## Expected behavior

Tab bar list should appear and look proper.
## Actual behavior

UI is not working as expected. The behaviour is shift in colors.

## Platform (please complete the following information)

 - Device: All
 - OS: iOS 13

## Additional context

The tab representation is affected in iOS 13. The tab's color is shifted to random.

---
#### Internal data
- Associated internal bug: [b/142384933](http://b/142384933)

**Comment by yarneo** [comment]
Hi @shubhankarbhavsar, can you please expand on what issue you are seeing with Tabs?

Are you going into our catalog app and seeing something in the UI on iOS 13 that doesn't look good? Can you tell us what example you are in and what UI issues you are experiencing? Thanks

**Comment by shubhankarbhavsar** [comment]
Hello @yarneo 

Please find the attached screenshot of the tab bar.

![2019-10-09](https://user-images.githubusercontent.com/30254936/66487550-206fc500-eaca-11e9-8eab-000e88ceb0ea.jpeg)

**Comment by yarneo** [comment]
Thanks!

This seems like it is happening in your app. If you are able to reproduce this with easy steps please provide a code snippet or consider adding an example to our Catalog.

**Comment by romoore** [comment]
I suspect this is the Ripple color being set to white, but I cannot be sure. I'm going to close this for now, but please reopen it if you can provide a self-contained section of code that demonstrates the issue. Thanks!
