### ISSUE TITLE
[Scripts] Linting and Formatting

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#857]
There's no easy linting and formatting solution anymore in our process. clang-format should really be run.

This should be scripted.

**Comment by samsymons** [comment]
@willlarche This is less important than having `clang-format` automatically format the core library, but how do you feel about including [SwiftLint](https://github.com/realm/SwiftLint) where relevant?

**Comment by willlarche** [comment]
I believe that's a great idea. SwiftLint has a lot going for it.

**Comment by samsymons** [comment]
Nice, I will try to open up a PR with some changes there today. We've been using SwiftLint a lot at PayPal and Venmo and it's been super useful!

**Comment by seanoshea** [comment]
https://github.com/seanoshea/BostonFreedomTrail/issues/126 for where I've introduced `SwiftLint` in a different project. Definitely useful!

**Comment by samsymons** [comment]
I have done a basic integration of SwiftLint in #1129.

**Comment by ianegordon** [comment]
Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄
