### ISSUE TITLE
[Documentation] Doc on clang-format is out of date

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#858]
### Overview of the issue
The contributing/clang-format.md file needs better instruction and removal of plugins suggestion

### Motivation and context
Xcode 8 doesn't support plugins.
Therefore users need to use clang-format manually and that is not completely captured.

### Related issues
#857

**Comment by ianegordon** [comment]
Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄
