### ISSUE TITLE
Remove conditionals around `systemFontOfSize:weight:`

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#8580]
Now that iOS 9 is the minimum supported iOS and we support Xcode 10+, we no longer need to have conditional logic around `systemFontOfSize:weight:`.

---
#### Internal data
- Associated internal bug: [b/142811072](http://b/142811072)

**Comment by material-mirror** [comment]
The internal issue [b/142811072](http://b/142811072) is now closed. This issue is being closed as a result.
