### ISSUE TITLE
[Tutorial] Recapture videos without mouse

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#859]
Use triple tap hack to show red circle and use device instead of simulator.

---
#### Internal data
- Associated internal bug: [b/117179270](http://b/117179270)

**Comment by ajsecord** [comment]
Blocked only on #853 now.

**Comment by material-mirror** [comment]
The internal issue [b/117179270](http://b/117179270) is now closed. This issue is being closed as a result.
