### ISSUE TITLE
FeatureHighlightViewController can change prefers status bar hidden

### ISSUE THREAD

**Issue by SheldonSandbekkhaug** [material-components/material-components-ios#861]
As a developer, my app hides the status bar but MDCFeatureHighlightViewController doesn't. The child view controller should keep the same status bar behavior as its parent.

**Comment by samnm** [comment]
Sorry for the lack of response on this. I haven't been able to reproduce this and as far as I can tell MDCFeatureHighlightViewController doesn't do anything unique to influence the status bar. Feel free to reopen this if it is still an issue and I'll take another look.
