### ISSUE TITLE
[BottomSheet] disable Bottom Sheet vertical bounce

### ISSUE THREAD

**Issue by androdev700** [material-components/material-components-ios#8616]
## Feature Request/Suggestion

Is there any way to disable vertical over-scroll/bounce of the bottomsheet

## Additional context

The UIScrollView method 'alwaysBounceVertical' disables bounce in a scrollview type view. Can it be applied to the bottomsheet as well?

---
#### Internal data
- Associated internal bug: [b/144388086](http://b/144388086)

**Comment by mariorsjr** [comment]
Any updates on this issue?

**Comment by andrewoverton** [comment]
Hello, this issue should be resolved after https://github.com/material-components/material-components-ios/commit/1b985100ec89ed142981bd8f3d51b247f88e6f0c. Try doing the following:
`bottomSheet.mdc_bottomSheetPresentationController?.simulateScrollViewBounce = false`

**Comment by andrewoverton** [comment]
Ah, note that my above comment only applies when there is no `trackingScrollView`. If there _is_ a `trackingScrollView`, you can disable bouncing on it directly.
