### ISSUE TITLE
[CollectionViewFlowLayout] Setting sectionHeadersPinToVisibleBounds to YES has no effect on iOS 9

### ISSUE THREAD

**Issue by tomaszmaciejko** [material-components/material-components-ios#862]
Using _MDCCollectionViewFlowLayout_ and setting property _sectionHeadersPinToVisibleBounds_ has no effect when run against devices and simulators with **iOS9+**. Changing layout to Apple's _UICollectionViewFlowLayout_ mitigates this issue

Version: 16.2.0

**Comment by peterfriese** [comment]
+1 would be great to have this.

**Comment by chriscox** [comment]
Removing myself from assignee to allow the team to re-prioritize this if anyone can jump on it sooner than myself.

**Comment by jverkoey** [comment]
Marking as Obsolete because we do not intend to continue to invest effort into Collections. Please consider using the new List component instead: https://github.com/material-components/material-components-ios/tree/develop/components/List
