### ISSUE TITLE
[MDCFlexibleHeaderContainerViewController] Support SwiftUi

### ISSUE THREAD

**Issue by vasquezdennisalon** [material-components/material-components-ios#8647]
### Overview
How to implement MDCFlexibleHeaderContainerViewController with swiftUi I have tried in different ways and none has worked correctly

---
#### Internal data
- Associated internal bug: [b/143526189](http://b/143526189)

**Comment by jverkoey** [comment]
We are unlikely to support SwiftUI for the FlexibleHeader. Consider using standard SwiftUI features to accomplish this instead.
