### ISSUE TITLE
[Examples] ObjC imports usually "Materialxxx.h" could be module instead?

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#865]
I might be wrong on this one!

### Overview
Most imports in the examples have this form:
`#import "MaterialButtons.h"`

I believe we can move to module importing now that we support it for Swift:
`@import MaterialComponents.MaterialButtons`

### Motivation and context
Xcode offers the module version in autocomplete.

**Comment by jverkoey** [comment]
Likely still stuck with `""` imports for a while into the future.
