### ISSUE TITLE
[Dialogs] AlertController is not adjusting `titleFont` for Dynamic Type

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#8672]
## Acceptance Criteria
1. `titleFont` is scaled for Dynamic Type when set with a UIFontMetrics-based font and `adjustsFontForContentSizeCategory` is enabled on its label.
2. `titleFont` is scaled for Dynamic Type when set with an MDCFontScaler-generated font and `mdc_adjustsFontForContentSizeCategory` is enabled on the controller.
3. `titleFont` is scaled for Dynamic Type when set with a "system" font (neither UIFontMetrics-based nor MDCFontScaler-based) and `mdc_adjustsFontForContentSizeCategory` and `adjustsFontForContentSizeCategoryWhenScaledFontIsUnavailable` are enabled on the controller.

---
#### Internal data
- Associated internal bug: [b/143525948](http://b/143525948)

**Comment by material-mirror** [comment]
The internal issue [b/143525948](http://b/143525948) is now closed. This issue is being closed as a result.
