### ISSUE TITLE
[MDCMaskedTransitionController] MaskedTransitionController no longer works in iOS 13

### ISSUE THREAD

**Issue by zishanj** [material-components/material-components-ios#8762]
I am using MaterialComponents ver 89.0. `MDCMaskedTransitionController` has been working perfectly up till iOS 12.x. In iOS 13.2.2 as soon as I tapped on a cell the screen disappears after short transition and my entire app stops accepting any tap. 

I have seen that `MDCMaskedTransitionController` has been removed from latest MaterialComponents version, is there any alternate method to play transition similar to `MDCMaskedTransitionController` on iOS 13? Or is there any possibility to fix `MDCMaskedTransitionController`?

---
#### Internal data
- Associated internal bug: [b/144437754](http://b/144437754)

**Comment by zishanj** [comment]
Just to add further, this issue comes after updating to XCode 11.2. App compiled with older XCode version (i think it was v10), does not have this issue in iOS 13.2.2.

**Comment by romoore** [comment]
Thanks for filing this issue, @zishanj . Unfortunately, I do not believe we will support MaskedTransition any longer.  MaskedTransition was removed as a component in [release 93.0.0](https://github.com/material-components/material-components-ios/releases/tag/v93.0.0), so I don't believe we will be able to fix compatibility with iOS 13.

**Comment by zishanj** [comment]
Any good reason of removing this component? Its a very active component in my apps. 
--
Sent from my phone. Please excuse my brevity.On 11/12/19, 7:26 PM Robert Moore <notifications@github.com> wrote:
Thanks for filing this issue, @zishanj . Unfortunately, I do not believe we will support MaskedTransition any longer.  MaskedTransition was removed as a component in release 93.0.0, so I don't believe we will be able to fix compatibility with iOS 13.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/material-components/material-components-ios/issues/8762?email_source=notifications\u0026email_token=AALCKHENSTNGTB4GQYF44YTQTK4J3A5CNFSM4JLDN5L2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOED2NG6Q#issuecomment-552915834",
"url": "https://github.com/material-components/material-components-ios/issues/8762?email_source=notifications\u0026email_token=AALCKHENSTNGTB4GQYF44YTQTK4J3A5CNFSM4JLDN5L2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOED2NG6Q#issuecomment-552915834",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by romoore** [comment]
Assigning @jverkoey who worked on https://github.com/material-components/material-components-ios/issues/8228 to remove the component.

**Comment by jverkoey** [comment]
We removed this transition for two primary reasons:

1. We had no usage of this transition in any of Google's products.
2. The transition itself, while interesting, is not expected to significantly improve the user experience of a product, particularly in light of Apple's recent investments in gesturally controllable modal presentations in iOS 13. We encourage making use of native system transitions instead of custom transitions like this.

That being said, while we do not intend to continue supporting this functionality, the code for this component is still available in our history and the code is Apache 2 licensed. You are still able to fork the repo and make use of that component independently by checking out that snapshot in our repo's history.

**Comment by zishanj** [comment]
> Just to add further, this issue comes after updating to XCode 11.2. App compiled with older XCode version (i think it was v10.3), does not have this issue in iOS 13.2.2.

@jverkoey I am using this actively in my iOS apps and due to its incompatibility with latest version of iOS I have to report here.

**Comment by jverkoey** [comment]
> I am using this actively in my iOS apps and due to its incompatibility with latest version of iOS I have to report here.

I understand, but we will not be adding iOS 13 support to this component.

**Comment by material-mirror** [comment]
The internal issue [b/144437754](http://b/144437754) is now closed. This issue is being closed as a result.
