### ISSUE TITLE
Back buttons should support title and icon 

### ISSUE THREAD

**Issue by ajsecord** [material-components/material-components-ios#889]
To match the system UI, our back button should support the title and/or icon of the previous view.

https://developer.apple.com/reference/uikit/uibarbuttonitem

(From Apple's Navigation Bar docs): ![uinavbar_intro_2x](https://cloud.githubusercontent.com/assets/742162/20570973/ae9a7944-b173-11e6-9c12-1b3660a582a9.png)

**Comment by ianegordon** [comment]
Closing as obsolete.  😞 
Please open a new bug if this is still an issue.  😄
