### ISSUE TITLE
{CocoaPods} dyld: Symbol not found: _OBJC_CLASS_$_MDCChipView

### ISSUE THREAD

**Issue by muaviya** [material-components/material-components-ios#8987]
**### It is work to my iPhone 7 iOS 13.3.2,  but crash on iPhone 11 iOS 13.2.2**

> Version 11.2.1 (11B500)

After I include  into Podfile pod:
>       pod 'MaterialComponents/Chips'
 whenever I running project, app crash. With this error: 

>       dyld: Symbol not found: _OBJC_CLASS_$_MDCChipView

my Podfile: 

```
target 'DerbentTour' do
source 'https://cdn.cocoapods.org/‘

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
      pod 'SDWebImage'
    	pod 'AlamofireObjectMapper'
      pod 'Alamofire', '~> 5.0.0-rc.2'
      pod 'PromiseKit', "~> 6.8"
      pod 'Mapbox-iOS-SDK'
      pod 'RealmSwift'
      pod 'ObjectMapper+Realm'
    	pod 'PinLayout'
      pod "CTPanoramaView", "~> 1.3"
      pod 'MaterialComponents/BottomAppBar'
      pod 'MaterialComponents/Chips'
      pod 'DropDown'
      pod 'Cosmos', '~> 20.0'
  target 'DerbentTourTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

```

---
#### Internal data
- Associated internal bug: [b/144760283](http://b/144760283)

**Comment by romoore** [comment]
Thanks for reporting this, @muaviya . Could you run `pod update` and see if that fixes it? Could you also confirm which version of CocoaPods you're using?

**Comment by muaviya** [comment]
> Thanks for reporting this, @muaviya . Could you run `pod update` and see if that fixes it? Could you also confirm which version of CocoaPods you're using?

pod version 1.8.4

<img width="658" alt="Снимок экрана 2019-11-18 в 16 50 13" src="https://user-images.githubusercontent.com/4594192/69057885-9f3e1300-0a23-11ea-9777-d54e39bd514f.png">

**Comment by romoore** [comment]
Unfortunately, [MDC-iOS currently supports CocoaPods 1.6.1](https://github.com/material-components/material-components-ios/tree/develop/docs/build-env#cocoapods). Could you try with 1.6.1 and report back on the results?

**Comment by romoore** [comment]
How you switch to 1.6.1 depends on how you installed CocoaPods. I installed using Ruby Gems, so I specified the version I wanted explicitly.

```bash
sudo gem install cocoapods -v 1.6.1
```

**Comment by muaviya** [comment]
> Unfortunately, [MDC-iOS currently supports CocoaPods 1.6.1](https://github.com/material-components/material-components-ios/tree/develop/docs/build-env#cocoapods). Could you try with 1.6.1 and report back on the results?

it is work for me. Thank you. 
Do you plan to upgrade to the latest version cocoaPods ?

**Comment by romoore** [comment]
@jverkoey @randallli Do we have plans to support newer versions of CocoaPods this year or early next?

**Comment by jverkoey** [comment]
Let's bring this issue and https://github.com/material-components/material-components-ios/issues/75 to the team's attention today.

**Comment by romoore** [comment]
Opened an issue (will be mirrored separately) to bring this to the team's attention.

**Comment by andrewoverton** [comment]
This bug is now being tracked by https://github.com/material-components/material-components-ios/issues/8997.

Also, for what it's worth, I just tried creating a new project using Cocoapods 1.8.4 and had no problems running pod install or compiling the app. 

Did you try doing clearing derived data using option+command+shift+k?

**Comment by deepesh-vasthimal-cko** [comment]
> This bug is now being tracked by #8997.
> 
> Also, for what it's worth, I just tried creating a new project using Cocoapods 1.8.4 and had no problems running pod install or compiling the app.
> 
> @muaviya, did you try clearing derived data using option+command+shift+k?
> 
> So far I've tried on both the MDC Catalog and a new sample project after clearing derived data, clearing the cocoapods cache (`pod cache clean --all`), and doing `rn -rf ~/.cocoapods` and everything has worked.

what is the command `rn -rf ~/.cocoapods ` when i run this i get back command not found : rn . @andrewoverton Please can you help
