### ISSUE TITLE
[Chips] - MDCChipField overlaps other components with large number of Chips

### ISSUE THREAD

**Issue by anuragfluke** [material-components/material-components-ios#9021]
I am using MDCChipField for entering email id's and create chip view, Problem is coming when user will enter lot of email ids & chip field will touch other screen components.  Right now I am using with UIViewcontroller view's, chipfield added through XIB and showing lot of email id's though below code. 

```objc
- (void)viewWillLayoutSubviews {
    [super viewWillLayoutSubviews];

    CGRect frame = CGRectInset(self.view.bounds, 10, 10);
    if (@available(iOS 11.0, *)) {
        frame = UIEdgeInsetsInsetRect(frame, self.view.safeAreaInsets);
    }
    frame.size = [self.chipField sizeThatFits:frame.size];
    self.chipField.frame = frame;
}

```

Chipfield and chip views are working fine but as chipfield will grow with lot of email id's . it will cover other objects in screen. contraints and code will not work for this issue.

I am trying to use with scroll view and Tableview but it is not giving me success. Do you have any solution for this  ?

Please suggest for the same.

## Expected behavior

It should not overlap other objects 
@romoore @jverkoey @randallli @ajsecord @codeman7 

---
#### Internal data
- Associated internal bug: [b/145128530](http://b/145128530)

**Comment by anuragfluke** [comment]
@randallli and @romoore Any update on this ticket...or can you provide some solution... So that We can get rid out of it ... some sort of work around is also appreciated ?

**Comment by randallli** [comment]
Sorry that we haven't responded sooner. Can you share a snapshot of what you are experiencing?

Sharing some plans: we are working on a newer version of textfields and once that lands successfully we will pivot to chipfields. Right now the chipfields are not styled the same as textfields.

**Comment by randallli** [comment]
Our example has very similar flow to the code snippet that you posted.

https://github.com/material-components/material-components-ios/blob/develop/components/Chips/examples/ChipsInputExampleViewController.m#L82

We do a couple more things before we call sizeThatFits. Can you try following that example to see if it fixes your issues?

**Comment by randallli** [comment]
![Simulator Screen Shot - iPhone 7 - 2019-12-20 at 14 51 33](https://user-images.githubusercontent.com/943565/71288152-47533e80-2338-11ea-96a4-0a11cf82b2fa.png)
here is the example in action with alot of chips in it.

**Comment by randallli** [comment]
Conversation seems to have died. Please reopen with new information.
