### ISSUE TITLE
[Readmes] First image of each component is too big

### ISSUE THREAD

**Issue by willlarche** [material-components/material-components-ios#917]
### Overview of the issue
Every component has an image of itself in its readme.md. But they are 50% too big in GitHub

### Reproduction steps
Look at any component's readme.md

### Motivation and context
Pushes the more important content too far down.

**Comment by Arcank** [comment]
I just discovered [`sips`](http://lifehacker.com/5962420/batch-resize-images-quickly-in-the-os-x-terminal). Comes bundled with macOS (might be when you install the developer tools). That way we don't introduce another dependency contributors have to install.

**Comment by ShepJGoogle** [comment]
Sweet! Good find @Arcank! Agreed about not introducing unnecessary deps

**Comment by ajsecord** [comment]
I fixed this on the main README.md by just specifying the width to be half the horizontal resolution. That also ensured that the images look good on retina displays. (There are other, better, solutions for retina display images in general HTML, but they don't work in Markdown.)

Can we just update the other README.md files the same way?

**Comment by ShepJGoogle** [comment]
This is done... @ajsecord Wanted to ask about the missing naming_convention script so haven't renamed any screenshot files. Otherwise good to go.
