### ISSUE TITLE
[Banner] Internal issue: b/145223592

### ISSUE THREAD

**Issue by wenyuzhang666** [material-components/material-components-ios#9213]
This was filed as an internal issue. If you are a Googler, please visit b/145223592 for more details.

Internal data
Associated internal bug: b/145223592

---
#### Internal data
- Associated internal bug: [b/145223592](http://b/145223592)

**Comment by material-mirror** [comment]
The internal issue [b/145223592](http://b/145223592) is now closed. This issue is being closed as a result.
