### ISSUE TITLE
[Dialogs] Alert icon is not correctly centered.

### ISSUE THREAD

**Issue by bambaragoogle** [material-components/material-components-ios#9216]
Title icons for `MDCAlertController` should mimic the alignment of the title. When centering the title on an alert, the icon is not correctly centered.

## Reproduction steps

1. Create an alert with a title and icon.
2. Center the title.
3. Present the alert.

The following code reproduces the issue for me:
```
MDCAlertController *alertController = [MDCAlertController
    alertControllerWithTitle:@"Placeholder Title"
                          message:nil];
alertController.titleAlignment = NSTextAlignmentCenter;
alertController.titleIcon = [UIImage imageNamed:@"myIcon"];
[presentingController presentViewController:alertController animated:YES completion:nil];
```

## Expected behavior

The alert should center the icon over the title. I expect the screenshot to look like this:
<img width="427" alt="centered" src="https://user-images.githubusercontent.com/38367602/70480890-22d8a600-1a9e-11ea-8b7c-649651ffbec7.png">

## Actual behavior

The above code will render an alert that looks like this:
<img width="426" alt="off center" src="https://user-images.githubusercontent.com/38367602/70480882-1fddb580-1a9e-11ea-8fac-c20e1636ab98.png">

## Platform (please complete the following information)

 - Device: Any
 - OS: Any

---
#### Internal data
- Associated internal bug: [b/146432918](http://b/146432918)

**Comment by material-mirror** [comment]
The internal issue [b/146432918](http://b/146432918) is now closed. This issue is being closed as a result.
