### ISSUE TITLE
Submodule material-motion-apidiff uses https. Should it use ssh?

### ISSUE THREAD

**Issue by Arcank** [material-components/material-components-ios#924]
### Overview of the issue
Submodule `material-motion-apidiff` uses `https`. Should it use `ssh`?
https://github.com/material-components/material-components-ios/blob/develop/.gitmodules#L18

All other submodules use `ssh`.

### Motivation and context
 - Explain why this is a bug for you. Context gives us a better ability to meet your needs.

### Version number
ed311e7

**Comment by ajsecord** [comment]
All the submodules should actually be using https:// to be compatible with Travis CI, we found out the hard way. (Travis CI won't have any SSH keys locally when the instance comes up.)
