### ISSUE TITLE
[TextFields] MDCTextInputControllerUnderline doesn't support theming

### ISSUE THREAD

**Issue by versoworks** [material-components/material-components-ios#9242]
MDCTextInputControllerUnderline  doesn't support theming via the applyThemeWithScheme: method. Since MDCTextFieldColorThemer has been removed from v96.0.0 onward, it renders the class broken.

While I have read the docs which discourage use of the MDCTextInputControllerUnderline style due to poor testing, as it's in use in existing projects we cannot use the recommended styles.

Please add theming to the MDCTextInputControllerUnderline class. 

---
#### Internal data
- Associated internal bug: [b/146434278](http://b/146434278)

**Comment by rene-dohan** [comment]
Last compatible version seems to be  95.0.1, so I am stuck to that.

**Comment by andrewoverton** [comment]
Hi @versoworks,

I think the underline style is considered a legacy style, and I think MDCTextInputControllerUnderline is considered a legacy class. I don't think writing a theming extension for it is a big priority for us right now.

Have you considered using the new TextControls component? It has a filled textfield class that can be configured to look like an underline textfield. See this gif:

![underline](https://user-images.githubusercontent.com/8020010/71484056-75250100-27d8-11ea-8494-8acdecd8c2ea.gif)

To achieve that behavior you would have to add something like this to your setup code:
```
[self.filledTextField setFilledBackgroundColor:[UIColor clearColor] forState:MDCTextControlStateNormal];
[self.filledTextField setFilledBackgroundColor:[UIColor clearColor] forState:MDCTextControlStateEditing];
[self.filledTextField setFilledBackgroundColor:[UIColor clearColor] forState:MDCTextControlStateDisabled];
```
I didn't do this for the gif, but if you want the underline color to be clear in all the non-editing states you could do this too:
```
[self.filledTextField setUnderlineColor:[UIColor clearColor] forState:MDCTextControlStateNormal];
[self.filledTextField setUnderlineColor:[UIColor clearColor] forState:MDCTextControlStateDisabled];
```

**Comment by romoore** [comment]
After discussing with @randallli I opened #9371 to track writing the Theming Extension or removing the Underline controller.
