### ISSUE TITLE
[Chips] `contentPadding` does not apply top/bottom values correctly

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#9249]
Setting a `contentPadding` value of `UIEdgeInsetsMake(-20, 0, 20, 0)` should result in the Chip positioning its content nearer to the top than the bottom. However, the content is centered.

<img width="76" alt="Chip with content vertically centered." src="https://user-images.githubusercontent.com/1753199/70645439-fdb97400-1c12-11ea-8bf3-68e73467a419.png">

## Steps to reproduce
1. Set the `contentPadding` to `UIEdgeInsetsMake(-20, 0, 20, 0`
2. Render the Chip

### Expected Result
The chip positions its content based on the `contentPadding` value.

### Actual result
The top/bottom content padding is combined and the content is then centered within the Chip's bounds.

---
#### Internal data
- Associated internal bug: [b/147294685](http://b/147294685)

**Comment by randallli** [comment]
this got rolled back in the release candidate

**Comment by randallli** [comment]
ref: https://github.com/material-components/material-components-ios/releases/tag/v98.0.0
