### ISSUE TITLE
[Chips] `imagePadding` mispositions layout for title label

### ISSUE THREAD

**Issue by romoore** [material-components/material-components-ios#9250]
The `imagePadding` API affects the position of the `titleLabel` frame incorrectly.

## Steps to reproduce
1. Assign an `imagePadding` value of `UIEdgeInsetsMake(10, 20, 30, 40)` and all other padding to `.zero`
2. Render the Chip.

<img width="216" alt="Chip with positive image padding values showing incorrect label position." src="https://user-images.githubusercontent.com/1753199/70646385-c8ae2100-1c14-11ea-8639-d8e5ed42a346.png">

### Expected Result
1. The chip is inset based on its padding values and the label is unaffected relative to the trailing edge of the Chip.

### Actual Result
1. The label is mispositioned as a result of the image padding.

---
#### Internal data
- Associated internal bug: [b/147294309](http://b/147294309)

**Comment by randallli** [comment]
This was rolled back in the release 98.0.0. reopening this issue.

**Comment by randallli** [comment]
ref: https://github.com/material-components/material-components-ios/releases/tag/v98.0.0
