### ISSUE TITLE
[TextFields] Updating MDCMultilineTextField's trailingView leads to crash

### ISSUE THREAD

**Issue by felixaemiliano** [material-components/material-components-ios#9257]
The MDCMultilineTextField has a trailingView property. In the setter for this property, it ensures that it removes any previously set trailingView from its view hierarchy.

What it *doesn't* do is ensure that any constraints it had cached that refer to the previous trailingView (such as the ) are invalidated so that they are recalculated the next time the "updateTrailingViewLayout" method is called. Since these constraints aren't cleaned up, they lead to a crash when "updateConstraints" is called (which is guaranteed after setting a new trailingView which calls setNeedsUpdateConstraints).

## Reproduction steps

Create a MDCMultilineTextField and add a trailing view. Update the trailing view to a new view.

## Expected behavior

The MDCMultilineTextField updates the trailing view and positions it correctly.

## Actual behavior

Autolayout causes a crash because of an attempt to activate a constraint for a view that is not in the hierarchy. It is not allowed to establish constraints between items that aren't in the same view hierarchy.

## Platform (please complete the following information)

All platforms.

## Additional context

---
#### Internal data
- Associated internal bug: [b/146433741](http://b/146433741)

**Comment by andrewoverton** [comment]
This issue was closed by https://github.com/material-components/material-components-ios/pull/9336
