### ISSUE TITLE
[TextFields] MDCMultilineTextField doesn't report size changes to LayoutDelegate unless a TextFieldDelegate is set

### ISSUE THREAD

**Issue by felixaemiliano** [material-components/material-components-ios#9262]
MDCMultilineTextField has a MDCMultilineTextInputLayoutDelegate that can be informed when a change in the text field causes a change in its content size. However, simply setting a |layoutDelegate| is not enough since there is an additional check that the textView's delegate be non-nil.

## Reproduction steps

1. Create a MDCMultilineTextField and set its |layoutDelegate| (but don't set a delegate for the textView).
2. Add enough text so that a new line is required in the text field.

## Expected behavior

The |layoutDelegate| is informed of this size change using the -multilineTextField:didChangeContentSize: method.

## Actual behavior

The |layoutDelegate|'s -multilineTextField:didChangeContentSize: method is not called unless a delegate is set on the textView.

Note that the textView delegate conforms to the protocol UITextViewDelegate which is not related to the desired MDCMultilineTextInputLayoutDelegate.

## Platform (please complete the following information)

All platforms.

---
#### Internal data
- Associated internal bug: [b/146433660](http://b/146433660)

**Comment by andrewoverton** [comment]
This issue was closed by https://github.com/material-components/material-components-ios/pull/9337
