### ISSUE TITLE
[Snackbar] Snapshot test testSnackbarOverlayViewWithHighElevation is unreliable 

### ISSUE THREAD

**Issue by bryanoltman** [material-components/material-components-ios#9380]
As can be seen in https://github.com/material-components/material-components-ios/pull/9373, this test passes with different reference images.

**Comment by romoore** [comment]
Changing from "flaky" to "unreliable" since "flaky" most frequently means that the test will fail for no good reason. In this case, the problem is in its passing for no clear reason even when the inputs are incorrect.
