### ISSUE TITLE
[ActionSheet] Ability to enable or disable individual action sheet actions

### ISSUE THREAD

**Issue by ianrahman** [material-components/material-components-ios#9434]
### Overview
It would be convenient for `ActionSheetActions` to have a property which allows for the action to easily be disabled or enabled.

Setting `isEnabled` to `false` would disable user interaction and change the opacity / tint of the action's image and title to an alternative color.

An example of this UI change is in iOS Settings, flipping the radio switch for Airplane Mode disables Personal Hotspot and changes its appearance.

---
#### Internal data
- Associated internal bug: [b/147808479](http://b/147808479)

**Comment by mehulparmar4ever** [comment]
I need this feature too, Is there any way?

**Comment by jverkoey** [comment]
We will be turning down MDC Action Sheet. Please use UIMenu and UIAlertController on iOS 14+ instead.
