### ISSUE TITLE
MDCBaseCell's inkColor property should be null_resettable, or the default inkColor should be exposed

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#9488]
From @jlukas: "a way to reset the ink color (expose the default or reset it)" would make it easier to work with this cell.

---
#### Internal data
- Associated internal bug: [b/148289750](http://b/148289750)

**Comment by material-mirror** [comment]
The internal issue [b/148289750](http://b/148289750) is now closed. This issue is being closed as a result.
