### ISSUE TITLE
Crash in -[MDCCollectionViewFlowLayout updateSupplementaryViewAttribute:]

### ISSUE THREAD

**Issue by Arcank** [material-components/material-components-ios#961]
### Overview of the issue
Crash in `-[MDCCollectionViewFlowLayout updateSupplementaryViewAttribute:]`

Under certain conditions, this method can raise an exception:
`UICollectionViewLayoutAttributes: -setFrame: with CGRectNull is undefined.`

### Reproduction steps
This is a crash we got on the field, I don't have a repro case yet.

### Motivation and context
Stack trace:
```
Thread 0 CRASHED [EXC_SOFTWARE / UNCAUGHT_NS_EXCEPTION @ 0x00000001850f61c0 ] 
(CoreFoundation + 0x0012f1c0 )	__exceptionPreprocess
(libobjc.A.dylib + 0x00008558 )	objc_exception_throw
(CoreFoundation + 0x0012f090 )	+[NSException raise:format:arguments:]
(Foundation + 0x000ae798 )	-[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
(UIKit + 0x0006f73c )	-[UICollectionViewLayoutAttributes setFrame:]
(Chrome -MDCCollectionViewFlowLayout.m:388 )	-[MDCCollectionViewFlowLayout updateSupplementaryViewAttribute:]
(Chrome -MDCCollectionViewFlowLayout.m:352 )	-[MDCCollectionViewFlowLayout updateAttribute:]
(Chrome -MDCCollectionViewFlowLayout.m:155 )	-[MDCCollectionViewFlowLayout layoutAttributesForSupplementaryViewOfKind:atIndexPath:]
(UIKit + 0x001936e8 )	-[UICollectionViewData layoutAttributesForSupplementaryElementOfKind:atIndexPath:]
(UIKit + 0x0093fa60 )	-[UICollectionViewData rectForSupplementaryElementOfKind:atIndexPath:]
(UIKit + 0x001e5168 )	-[UICollectionView _viewAnimationsForCurrentUpdate]
(UIKit + 0x0090f198 )	__71-[UICollectionView _updateWithItems:tentativelyForReordering:animator:]_block_invoke.1983
(UIKit + 0x0001df64 )	+[UIView(Animation) performWithoutAnimation:]
(UIKit + 0x0090e1c8 )	-[UICollectionView _updateWithItems:tentativelyForReordering:animator:]
(UIKit + 0x0090c268 )	-[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:]
(UIKit + 0x0090fc30 )	-[UICollectionView _endUpdatesWithInvalidationContext:tentativelyForReordering:animator:]
(UIKit + 0x0090ff10 ) -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:animator:]
(UIKit + 0x0090fd70 ) -[UICollectionView _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:]
(UIKit + 0x0090fcf4 ) -[UICollectionView _performBatchUpdates:completion:invalidationContext:]
(UIKit + 0x001ea1bc ) -[UICollectionView performBatchUpdates:completion:]
(Chrome -MDCCollectionViewStyler.m:408 )  -[MDCCollectionViewStyler updateLayoutAnimated:completion:]
(Chrome -MDCCollectionViewStyler.m:376 )  -[MDCCollectionViewStyler applyInlayToAllItemsAnimated:]
(Chrome -MDCCollectionViewController.m:404 )  -[MDCCollectionViewController collectionViewWillBeginEditing:]
(Chrome -MDCCollectionViewEditor.m:141 )  -[MDCCollectionViewEditor setEditing:animated:]
...
```

### Diagnostic
From the stack trace, the crash happens in https://github.com/material-components/material-components-ios/blob/fb3cd29dce2ab78a55b4664d0b87bf0b4eae4779/components/Collections/src/MDCCollectionViewFlowLayout.m#L388.

From the crash report, the exception thrown is:
`UICollectionViewLayoutAttributes: -setFrame: with CGRectNull is undefined.`

There are two occurrences of `CGRectNull` in `MaterialCollections`:
- (probably unrelated) https://github.com/material-components/material-components-ios/blob/b5b128784c6182b5ed9de546adaaed8e9b44fcfa/components/Collections/src/private/MDCCollectionViewEditor.m#L247
- (might be related) https://github.com/material-components/material-components-ios/blob/fb3cd29dce2ab78a55b4664d0b87bf0b4eae4779/components/Collections/src/MDCCollectionViewFlowLayout.m#L198

The weird thing is that `insetFrame` is taken from the `attr` var to be modified and put back. So when `insetFrame` is declared line 379, we can assume it's already valid, otherwise, the exception would have happened when first set.
That leaves the mutating code to scrutiny:
1- line 382 insets the frame
2- lines 384 and 386 move the origin.
It seems safe to assume that line 384 and 386 can't possibly make the rect become `CGRectNull` (note that this is completely different than `CGRectZero`).

So the question is: can `CGRectInset` return `CGRectNull`?
Yes it can: https://developer.apple.com/reference/coregraphics/1454218-cgrectinset

"The rectangle is standardized and then the inset parameters are applied. If the resulting rectangle would have a negative height or width, a null rectangle is returned."

So there are conditions under which the insets applied to the frame would make the `insetFrame` have negative width or height. A trivial example is when the original frame is `CGRectZero`, and it is applied positive insets.

### Version number
Likely https://github.com/material-components/material-components-ios/commit/203562553800ed3d3b5eebfd1dd76cda875d833c

### Operating system and hardware
Happened on iOS 10.1, iPad and iPhone (low volume, so the OS is probably not an indication).

### Related issues
[crbug.com/671678](http://crbug.com/671678)

**Comment by Arcank** [comment]
Chris, could you have a look at this issue?

**Comment by chriscox** [comment]
Hey @Arcank looking...

**Comment by Arcank** [comment]
@ShepJGoogle Justin, are you the new owner of Collections?

**Comment by ShepJGoogle** [comment]
Yeah I'm acting owner. Will take a look when I close out a couple issues in the queue.

**Comment by ianegordon** [comment]
Closing as obsolete.
