### ISSUE TITLE
Explore whether MDCShadowLayer's renderInContext needs to disable CA animations

### ISSUE THREAD

**Issue by jverkoey** [material-components/material-components-ios#98]
MDCShadowLayer's `renderInContext:` implementation changes the background color of the top and bottom shadow. It's possible that this is causing animations to be created which could cause odd artifacts on the rendered context.

---
#### Internal data
- Associated internal bug: [b/117179554](http://b/117179554)

**Comment by material-mirror** [comment]
The internal issue [b/117179554](http://b/117179554) is now closed. This issue is being closed as a result.
