### ISSUE TITLE
[Can not import libary MaterialComponents]  pod 'MaterialComponents/BottomSheet'(Swift 5.1, Xcode 11.4)

### ISSUE THREAD

**Issue by VietNamBookingApp** [material-components/material-components-ios#9958]
Hi everyone,
How to import MaterialComponent( pod 'MaterialComponents/BottomSheet')
I use pod install, but error
Can you support?
Thanks all

This my error when pod install:

JSON::ParserError - 416: unexpected token at '{
      "name": "MaskedTransition",
      "platforms": {
        "ios": "8.0"
      },
      "public_header_files": "components/MaskedTransition/src/*.h",
      "source_files": [
        "components/MaskedTransition/src/*.{h,m}",
        "components/MaskedTransition/src/private/*.{h,m}"
      ],
      "dependencies": {
        "MotionTransitioning": [
          "~> 3.0"
        ],
        "MotionAnimator": [
          "~> 1.0"
        ],
        "MotionIntercha'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification.rb:742:in `from_string'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification.rb:716:in `from_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/source.rb:186:in `specification'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver/lazy_specification.rb:37:in `specification'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver/lazy_specification.rb:29:in `subspec_by_name'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:362:in `block in specifications_for_dependency'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:362:in `map'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:362:in `specifications_for_dependency'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:165:in `search_for'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `sort_by'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:288:in `initial_state'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:210:in `start_resolution'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:168:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:94:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1065:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:410:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=416%3A+unexpected+token+at+%27%7B%0A++++++%22name%22%3A+%22MaskedTransition%22%2C%0A++++++%22platforms%22%3A+%7B%0A++++++++%22ios%22%3A+%228.0%22%0A++++++%7D%2C%0A++++++%22public_header_files%22%3A+%22components%2FMaskedTransition%2Fsrc%2F%2A.h%22%2C%0A++++++%22source_files%22%3A+%5B%0A++++++++%22components%2FMaskedTransition%2Fsrc%2F%2A.%7Bh%2Cm%7D%22%2C%0A++++++++%22components%2FMaskedTransition%2Fsrc%2Fprivate%2F%2A.%7Bh%2Cm%7D%22%0A++++++%5D%2C%0A++++++%22dependencies%22%3A+%7B%0A++++++++%22MotionTransitioning%22%3A+%5B%0A++++++++++%22~%3E+3.0%22%0A++++++++%5D%2C%0A++++++++%22MotionAnimator%22%3A+%5B%0A++++++++++%22~%3E+1.0%22%0A++++++++%5D%2C%0A++++++++%22MotionIntercha%27&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass

**Comment by codeman7** [comment]
What components are you depending on in your Podfile? I see `MaskedTransition` we no longer support that component as of `v93.0.0`.

**Comment by marcojusto** [comment]
Hey I've also tried installing this library MaterialComponents/BottomSheet , following  the instructions you have on - https://material.io/develop/ios/components/bottom-sheet/

After I executed `pod install` I got a similar result: 

>  JSON::ParserError - 434: unexpected token at '{
>       "name": "TextControls+FilledTextAreas",
>       "platforms": {
>         "ios": "9.0"
>       },
>       "public_header_files": "components/TextControls/src/FilledTextAreas/*.h",
>       "source_files": [
>         "components/TextControls/src/FilledTextAreas/*.{h,m}",
>         "components/TextControls/src/FilledTextAreas/private/*.{h,m}"
>       ],
>       "dependencies": {
>         "MaterialComponents/Availability": [
> 
>         ],
>         "MaterialComponents/

I'm wondering do I need any other pods before I run  `pod install`?

**Comment by andrewoverton** [comment]
I just created a new sample project and followed the steps at material.io and I didn't have a problem. My Podfile ended up looking like this:
```
target 'MyApp' do
  pod 'MaterialComponents/BottomSheet'
end
```
What cocoapods version are you on? I'm using 1.8.4. Have you tried `pod cache clean --all`?

**Comment by iqbalprabu** [comment]
i got same issue in xcode 11.3.1 and swift 5.1
somebody help me ?

**Comment by andrewoverton** [comment]
I'm using Xcode 11.4 and Swift 5 and it's working fine for me. I would try doing the ol' shift + option + command + k (⇧⌥⌘K), running `pod cache clean --all`,  and quitting and re-opening Xcode. What error message are you seeing @iqbalprabu ?

**Comment by iqbalprabu** [comment]
@andrewoverton which version are you using ? can you share the Podfile ?
im getting error when pod install 

`JSON::ParserError - 767: unexpected token at ''`

**Comment by andrewoverton** [comment]
I'm still using the Podfile in https://github.com/material-components/material-components-ios/issues/9958#issuecomment-611101368. Maybe try what this person did, it looks promising: https://github.com/CocoaPods/CocoaPods/issues/9260#issuecomment-542586026

**Comment by iqbalprabu** [comment]
@andrewoverton wow nice, it's working. thanks bro

**Comment by andrewoverton** [comment]
Great! I'll close this issue for now.
