### ISSUE TITLE
[TextFields] MDCTextField placeholder is not vertically aligned with input text

### ISSUE THREAD

**Issue by fanij** [material-components/material-components-ios#9961]
I'm using MDCTextInputControllerUnderline and MDCTextField, with set leadingView image.
MDCTextField placeholder is not vertically aligned with input text.

![Screen Shot 2020-04-07 at 10 09 57](https://user-images.githubusercontent.com/41965586/78653846-03bf1900-78c4-11ea-92cd-e4090e5108ad.png)

expecting placeholder to be above text input:
![Screen Shot 2020-04-07 at 10 32 11](https://user-images.githubusercontent.com/41965586/78654557-fa827c00-78c4-11ea-86e2-4f5bffc460aa.png)

Steps to reproduce:
1. Create MDCTextField
2. Set UIImageView for leadingView
3. Use MDCTextInputControllerUnderline

```
@IBOutlet var txtPassword: MDCTextField!

txtPassword.leadingViewMode = .always
let passIcon =  UIImageView.init(image: UIImage(named: "password-icon"))
txtPassword.leadingView = passIcon
txtPassword.placeholder = "Password"
var txtPassController = MDCTextInputControllerUnderline(textInput: txtPassword)
```

 - OS: tested on iOS 13.3, 12.4

**Comment by andrewoverton** [comment]
We have a newer text fields implementation that has better support than MDCTextField. You can read more about the new text fields [here](https://github.com/material-components/material-components-ios/blob/develop/components/TextControls/README.md). Note that the new text fields don't support the underline style. They might someday, but they don't now. Here are some gifs of the leadingView functionality in the new MDCFilledTextField.

This is with `leadingViewMode` set to `.always`:

![always](https://user-images.githubusercontent.com/8020010/78818702-13f9f580-79a3-11ea-82a8-22f9a056db85.gif)

This is with `leadingViewMode` set to `.whileEditing`:

![while_editing](https://user-images.githubusercontent.com/8020010/78818743-22e0a800-79a3-11ea-93c2-a62d54c0d15e.gif)

**Comment by fanij** [comment]
@andrewoverton Thanks for the response. I'm using the newer text fields implementation - MDCFilledTextField, trying to make the look similar as the Underline style.
Is there any way to remove the dark border around the field?
I'm using setFilledBackgroundColor and border is not changing color.
![Screen Shot 2020-04-10 at 16 41 35](https://user-images.githubusercontent.com/41965586/78999279-9670e980-7b4a-11ea-9001-6e41e632d704.png)

**Comment by fanij** [comment]
@andrewoverton Thanks for the response. I'm using the newer text fields implementation. 
Looking good.
![Screen Shot 2020-04-10 at 17 34 27](https://user-images.githubusercontent.com/41965586/79002829-96281c80-7b51-11ea-971d-7f8fc5d2502a.png)
In android there is option for error state
![Screen Shot 2020-04-10 at 17 34 33](https://user-images.githubusercontent.com/41965586/79003917-eef8b480-7b53-11ea-8fbd-d9033d187856.png)
With old MDCTextField I was setting error with MDCTextInputControllerUnderline setErrorText method.
Is there similar option for MDCFilledTextField?

**Comment by andrewoverton** [comment]
You need to add `MaterialComponents/TextControls+FilledTextFieldsTheming` if you don't have the theming extensions already. Then you need to `#import "MaterialTextControls+FilledTextFields.h`. From there, if you want to enter the error state you do this:
```
self.textField.leadingAssistiveLabel.text = @"Error text";
[self.textField gmdc_applyErrorThemeWithScheme:self.containerScheme];
```
And when you want to exit the error state you do this:
```
self.textField.leadingAssistiveLabel.text = @"Helper text";
[self.textField gmdc_applyThemeWithScheme:self.containerScheme];
```
Unfortunately, because of the way our theming works, calling these theming methods will not only apply color theming, it will apply typography theming as well. So any setting of fonts you want to do on the text field may have to be re-applied as you enter and exit the error mode.

**Comment by andrewoverton** [comment]
I'll close this issue for now, please feel free to re-open or open a new one if something comes up!
