### ISSUE TITLE
[MDCTextField] How do i resolve those deprecated class warnings?

### ISSUE THREAD

**Issue by kristinamartinkevich** [material-components/material-components-ios#9988]
<img width="571" alt="Screenshot 2020-05-07 at 09 36 41" src="https://user-images.githubusercontent.com/31727202/81262341-56682e00-9046-11ea-930c-7155a6b7fab3.png">
<img width="569" alt="Screenshot 2020-05-07 at 09 36 54" src="https://user-images.githubusercontent.com/31727202/81262352-58ca8800-9046-11ea-9839-ca9c43ec6aa0.png">

**Comment by codeman7** [comment]
Hey @kristinamartinkevich are you seeing those from building our catalog or in your app?

**Comment by kristinamartinkevich** [comment]
i just needed to update the version of material components pod in the pod file

**Comment by mehulparmar4ever** [comment]
I have update cocoapod, still I am getting warnings

Please guide me to fix this warning ⚠️ related issues. Thank you.

<img width="456" alt="Screenshot 2021-04-21 at 4 17 55 PM" src="https://user-images.githubusercontent.com/7687920/115541765-23ea2c00-a2bd-11eb-9562-66a8d8987097.png">

**Comment by Ryubal** [comment]
This issue should be reopened. It's still happening even after updating MaterialComponents to the latest version available with Cocoapods.
