### ISSUE TITLE
[Development Guide] Should provide detailed instructions how to set up the development environment

### ISSUE THREAD

**Issue by peterfriese** [material-components/material-components-ios#999]
The setup instructions for the build environment at https://github.com/material-components/material-components-ios/tree/develop/howto/build-env are rather vague. It'd be helpful to provide detailed instructions to make setting up a productive development environment easier.

**Comment by randallli** [comment]
@peterfriese what are you looking for when looking at the build-env page? Im trying to understand why its vague.

**Comment by ianegordon** [comment]
Closing as ignored.  😞 
Please open a new bug if this is still an issue.  😄
